Dakota: C3Approximation Class Reference
C3Approximation Class Reference
Derived approximation class for global basis polynomials.
Public Member Functions
C3Approximation ()
default constructor
C3Approximation (ProblemDescDB &problem_db, const SharedApproxData &shared_data, const String &approx_label)
standard ProblemDescDB-driven constructor
C3Approximation (const SharedApproxData &shared_data)
alternate constructor
C3FnTrainData & active_ftd ()
return the active C3FnTrainData instance in levelApprox
C3FnTrainData & combined_ftd ()
return combinedC3FTData
size_t regression_size ()
size_t regression_size (const SizetVector &ranks, size_t max_rank, const UShortArray &orders, unsigned short max_order)
void recover_function_train_ranks (struct FunctionTrain *ft)
void recover_function_train_orders (const std::vector< OneApproxOpts * > &a_opts)
void expansion_coefficient_flag (bool coeff_flag)
bool expansion_coefficient_flag () const
void expansion_gradient_flag (bool grad_flag)
bool expansion_gradient_flag () const
void compute_moments (bool full_stats=true, bool combined_stats=false)
void compute_moments (const Pecos::RealVector &x, bool full_stats=true, bool combined_stats=false)
const RealVector & moments () const
const RealVector & expansion_moments () const
const RealVector & numerical_integration_moments () const
const RealVector & combined_moments () const
Real moment (size_t i) const
void moment (Real mom, size_t i)
Real combined_moment (size_t i) const
void combined_moment (Real mom, size_t i)
void compute_component_effects ()
void compute_total_effects ()
void compute_all_sobol_indices (size_t)
Real total_sobol_index (size_t)
Real main_sobol_index (size_t)
void sobol_iterate_apply (void(*)(double, size_t, size_t *, void *), void *)
Real mean ()
return the mean of the expansion, where all active vars are random
Real mean (const RealVector &)
return the mean of the expansion for a given parameter vector, where a subset of the active variables are random
const RealVector & mean_gradient ()
return the gradient of the expansion mean
const RealVector & mean_gradient (const RealVector &, const SizetArray &)
return the gradient of the expansion mean
Real variance ()
return the variance of the expansion, where all active vars are random
Real variance (const RealVector &)
return the variance of the expansion for a given parameter vector, where a subset of the active variables are random
const RealVector & variance_gradient ()
const RealVector & variance_gradient (const RealVector &, const SizetArray &)
Real covariance (Approximation &approx_2)
return the covariance between two response expansions, treating all variables as random
Real covariance (const RealVector &x, Approximation &approx_2)
return the covariance between two response expansions, treating a subset of the variables as random
Real skewness ()
Real kurtosis ()
Real third_central ()
Real fourth_central ()
Real combined_mean ()
return the mean of the combined expansion, where all active vars are random
Real combined_mean (const RealVector &)
return the mean of the combined expansion for a given parameter vector, where a subset of the active variables are random
Real combined_variance ()
Real combined_variance (const RealVector &)
Real combined_covariance (Approximation &approx_2)
return the covariance between two combined response expansions, where all active variables are random
Real combined_covariance (const RealVector &x, Approximation &approx_2)
return the covariance between two combined response expansions, where a subset of the active variables are random
Real combined_third_central ()
Real combined_fourth_central ()
void synchronize_surrogate_data ()
update surrData to define aggregated data from raw data, when indicated by an active aggregated key
void generate_synthetic_data (Pecos::SurrogateData &surr_data, const Pecos::ActiveKey &active_key, short combine_type)
generate synthetic data for the surrogate QoI prediction corresponding to the level key preceding active key; for use in surplus estimation for new level data relative to a previous level's surrogate prediction
Public Member Functions inherited from Approximation
Approximation ()
default constructor
Approximation (ProblemDescDB &problem_db, const SharedApproxData &shared_data, const String &approx_label)
standard constructor for envelope
Approximation (const SharedApproxData &shared_data)
alternate constructor
Approximation (const Approximation &approx)
copy constructor
virtual ~Approximation ()
destructor
Approximation operator= (const Approximation &approx)
assignment operator
virtual void export_model (const StringArray &var_labels=StringArray(), const String &fn_label="", const String &export_prefix="", const unsigned short export_format=NO_MODEL_FORMAT)
exports the approximation; if export_format > NO_MODEL_FORMAT, uses all 3 parameters, otherwise extracts these from the Approximation's sharedDataRep to build a filename
virtual void export_model (const Variables &vars, const String &fn_label="", const String &export_prefix="", const unsigned short export_format=NO_MODEL_FORMAT)
approximation export that generates labels from the passed Variables, since only the derived classes know how the variables are ordered w.r.t. the surrogate build; if export_format > NO_MODEL_FORMAT, uses all 3 parameters, otherwise extracts these from the Approximation's sharedDataRep to build a filename
virtual void replace (const IntResponsePair &response_pr, size_t fn_index)
replace the response data
virtual void finalize_coefficients ()
finalize approximation by applying all remaining trial sets
virtual void clear_current_active_data ()
clear current build data in preparation for next build
virtual Real prediction_variance (const Variables &vars)
retrieve the variance of the predicted value for a given parameter vector
virtual Real value (const RealVector &c_vars)
retrieve the approximate function value for a given parameter vector
virtual const RealVector & gradient (const RealVector &c_vars)
retrieve the approximate function gradient for a given parameter vector
virtual const RealSymMatrix & hessian (const RealVector &c_vars)
retrieve the approximate function Hessian for a given parameter vector
virtual Real prediction_variance (const RealVector &c_vars)
retrieve the variance of the predicted value for a given parameter vector
virtual void compute_moments (const RealVector &x, bool full_stats=true, bool combined_stats=false)
virtual void clear_component_effects ()
virtual const RealVector & sobol_indices () const
virtual const RealVector & total_sobol_indices () const
virtual ULongULongMap sparse_sobol_index_map () const
virtual bool diagnostics_available ()
check if diagnostics are available for this approximation type
virtual Real diagnostic (const String &metric_type)
retrieve a single diagnostic metric for the diagnostic type specified
virtual RealArray cv_diagnostic (const StringArray &metric_types, unsigned num_folds)
retrieve diagnostic metrics for the diagnostic types specified, applying
virtual void primary_diagnostics (size_t fn_index)
compute and print all requested diagnostics and cross-validation
virtual RealArray challenge_diagnostic (const StringArray &metric_types, const RealMatrix &challenge_points, const RealVector &challenge_responses)
compute requested diagnostics for user provided challenge pts
virtual void challenge_diagnostics (size_t fn_index, const RealMatrix &challenge_points, const RealVector &challenge_responses)
compute and print all requested diagnostics for user provided challenge pts
virtual RealVector approximation_coefficients (bool normalized) const
return the coefficient array computed by build()/rebuild()
virtual void approximation_coefficients (const RealVector &approx_coeffs, bool normalized)
set the coefficient array from external sources, rather than computing with build()/rebuild()
virtual void coefficient_labels (std::vector< std::string > &coeff_labels) const
print the coefficient array computed in build()/rebuild()
virtual void print_coefficients (std::ostream &s, bool normalized)
print the coefficient array computed in build()/rebuild()
virtual int recommended_coefficients () const
return the recommended number of samples (unknowns) required to build the derived class approximation type in numVars dimensions
virtual int num_constraints () const
return the number of constraints to be enforced via an anchor point
virtual void clear_computed_bits ()
clear tracking of computed moments, due to (expansion) change that invalidates previous results
virtual void map_variable_labels (const Variables &dfsm_vars)
if needed, map passed all variable labels to approximation's labels
int min_points (bool constraint_flag) const
return the minimum number of points required to build the approximation type in numVars dimensions. Uses *_coefficients() and num_constraints().
int recommended_points (bool constraint_flag) const
return the recommended number of samples to build the approximation type in numVars dimensions (default same as min_points)
void pop_data (bool save_data)
removes entries from end of SurrogateData::{vars,resp}Data (last points appended, or as specified in args)
void push_data ()
restores SurrogateData state prior to previous pop()
void finalize_data ()
finalize SurrogateData by applying all remaining trial sets
const Pecos::SurrogateData & surrogate_data () const
return approxData
Pecos::SurrogateData & surrogate_data ()
return approxData
void add (const Variables &vars, bool v_copy, const Response &response, size_t fn_index, bool r_copy, bool anchor_flag, int eval_id, size_t key_index=_NPOS)
create SurrogateData{Vars,Resp} and append to SurrogateData:: {varsData,respData,dataIdentifiers}
void add (const Real *c_vars, bool v_copy, const Response &response, size_t fn_index, bool r_copy, bool anchor_flag, int eval_id, size_t key_index=_NPOS)
create SurrogateData{Vars,Resp} and append to SurrogateData:: {varsData,respData,dataIdentifiers}
void add (const Pecos::SurrogateDataVars &sdv, bool v_copy, const Response &response, size_t fn_index, bool r_copy, bool anchor_flag, int eval_id, size_t key_index=_NPOS)
create a SurrogateDataResp and append to SurrogateData:: {varsData,respData,dataIdentifiers}
void add (const Pecos::SurrogateDataVars &sdv, bool v_copy, const Pecos::SurrogateDataResp &sdr, bool r_copy, bool anchor_flag, int eval_id, size_t key_index=_NPOS)
append to SurrogateData::{varsData,respData,dataIdentifiers}
void add_array (const RealMatrix &sample_vars, bool v_copy, const RealVector &sample_resp, bool r_copy, size_t key_index=_NPOS)
add surrogate data from the provided sample and response data, assuming continuous variables and function values only
void pop_count (size_t count, size_t key_index)
appends to SurrogateData::popCountStack (number of entries to pop from end of SurrogateData::{vars,resp}Data, based on size of last data append)
void clear_data ()
clear SurrogateData::{vars,resp}Data for activeKey + embedded keys
void clear_active_data ()
clear active approximation data
void clear_inactive_data ()
clear inactive approximation data
void clear_active_popped ()
clear SurrogateData::popped{Vars,Resp}Trials,popCountStack for activeKey
void clear_popped ()
clear SurrogateData::popped{Vars,Resp}Trials,popCountStack for all keys
void set_bounds (const RealVector &c_l_bnds, const RealVector &c_u_bnds, const IntVector &di_l_bnds, const IntVector &di_u_bnds, const RealVector &dr_l_bnds, const RealVector &dr_u_bnds)
set approximation lower and upper bounds (currently only used by graphics)
std::shared_ptr< Approximation > approx_rep () const
returns approxRep for access to derived class member functions that are not mapped to the top Approximation level
Protected Member Functions
void active_model_key (const Pecos::ActiveKey &key)
activate an approximation state based on its multi-index key
void clear_model_keys ()
reset initial state by removing all model keys for an approximation
Real value (const Variables &vars)
retrieve the approximate function value for a given parameter vector
const RealVector & gradient (const Variables &vars)
retrieve the approximate function gradient for a given parameter vector
const RealSymMatrix & hessian (const Variables &vars)
retrieve the approximate function Hessian for a given parameter vector
bool advancement_available ()
check if resolution advancement (e.g., order, rank) is available for this approximation instance
void build ()
builds the approximation from scratch
void rebuild ()
rebuilds the approximation incrementally
void pop_coefficients (bool save_data)
removes entries from end of SurrogateData::{vars,resp}Data (last points appended, or as specified in args)
void push_coefficients ()
restores state prior to previous pop()
void combine_coefficients ()
combine all level approximations into a single aggregate approximation
void combined_to_active_coefficients (bool clear_combined=true)
promote combined approximation into active approximation
void clear_inactive_coefficients ()
prune inactive coefficients following combination and promotion to active
int min_coefficients () const
return the minimum number of samples (unknowns) required to build the derived class approximation type in numVars dimensions
Protected Member Functions inherited from Approximation
Approximation (BaseConstructor, const ProblemDescDB &problem_db, const SharedApproxData &shared_data, const String &approx_label)
constructor initializes the base class part of letter classes (BaseConstructor overloading avoids infinite recursion in the derived class constructors - Coplien, p. 139)
Approximation (NoDBBaseConstructor, const SharedApproxData &shared_data)
constructor initializes the base class part of letter classes (BaseConstructor overloading avoids infinite recursion in the derived class constructors - Coplien, p. 139)
Pecos::SurrogateDataVars variables_to_sdv (const Real *sample_c_vars)
create a SurrogateDataVars instance from a Real*
Pecos::SurrogateDataVars variables_to_sdv (const Variables &vars)
create a SurrogateDataVars instance by extracting data from a Variables object
Pecos::SurrogateDataResp response_to_sdr (const Response &response, size_t fn_index)
create a SurrogateDataResp instance by extracting data for a particular QoI from a Response object
void add (const Pecos::SurrogateDataVars &sdv, bool v_copy, const Pecos::SurrogateDataResp &sdr, bool r_copy, bool anchor_flag)
tracks a new data point by appending to SurrogateData::{vars,Resp}Data
void add (int eval_id)
tracks a new data point by appending to SurrogateData::dataIdentifiers
void check_points (size_t num_build_pts)
Check number of build points against minimum required.
void assign_key_index (size_t key_index)
extract and assign i-th embedded active key
Private Member Functions
bool max_rank_advancement_available ()
bool max_order_advancement_available ()
Real stored_value (const RealVector &c_vars, const Pecos::ActiveKey &key)
void compute_derived_statistics (C3FnTrainData &ftd, size_t num_mom, bool overwrite=false)
void compute_derived_statistics_av (C3FnTrainData &ftd, size_t num_mom, bool overwrite=false)
void check_function_gradient ()
differentiate the ft to form its gradient, if not previously performed
void check_function_hessian ()
differentiate the ftg to form the ft Hessian, if not previously performed
Real mean (C3FnTrainData &ftd)
compute mean corresponding to the passed FT expansion
Real mean (const RealVector &x, C3FnTrainData &ftd)
compute mean corresponding to the passed FT expansion
Real variance (C3FnTrainData &ftd)
compute variance corresponding to the passed FT expansion
Real variance (const RealVector &x, C3FnTrainData &ftd)
compute variance corresponding to the passed FT expansion
Real covariance (C3FnTrainData &ftd1, C3FnTrainData &ftd2)
compute variance corresponding to the passed FT expansion
Real covariance (const RealVector &x, C3FnTrainData &ftd1, C3FnTrainData &ftd2)
compute variance corresponding to the passed FT expansion
Real third_central (C3FnTrainData &ftd)
compute 3rd central moment corresponding to the passed FT expansion
Real fourth_central (C3FnTrainData &ftd)
compute 4th central moment corresponding to the passed FT expansion
Real skewness (C3FnTrainData &ftd)
compute skewness corresponding to the passed FT expansion
Real kurtosis (C3FnTrainData &ftd)
compute excess kurtosis corresponding to the passed FT expansion
Private Attributes
std::map< Pecos::ActiveKey, C3FnTrainData > levelApprox
set of pointers to QoI approximation data for each model key
std::map< Pecos::ActiveKey, C3FnTrainData >::iterator levApproxIter
iterator to active levelApprox
C3FnTrainData prevC3FTData
the previous approximation, cached for restoration
std::map< Pecos::ActiveKey, std::deque< C3FnTrainData > > poppedLevelApprox
bookkeeping for previously evaluated FT approximations that may be restored
C3FnTrainData combinedC3FTData
the combined approximation, summed across model keys
RealVector secondaryMoments
secondary (numerical) moments: inactive
RealVector combinedMoments
combined moments from multilevel-multifidelity FT rollup
bool expansionCoeffFlag
flag indicating need to build a fn train approximation for this QoI
bool expansionCoeffGradFlag
flag indicating need to build a fn train gradient approx for this QoI
Additional Inherited Members
Protected Attributes inherited from Approximation
Pecos::SurrogateData approxData
contains the variables/response data for constructing a single approximation model (one response function). There is only one SurrogateData instance per Approximation, although it may contain keys for different model forms/resolutions and aggregations (e.g., discrepancies) among forms/resolutions.
RealVector approxGradient
gradient of the approximation returned by gradient()
RealSymMatrix approxHessian
Hessian of the approximation returned by hessian()
String approxLabel
label for approximation, if applicable
std::shared_ptr< SharedApproxData > sharedDataRep
contains the approximation data that is shared among the response set
Detailed Description
Derived approximation class for global basis polynomials.
The PecosApproximation class provides a global approximation based on basis polynomials. This includes orthogonal polynomials used for polynomial chaos expansions and interpolation polynomials used for stochastic collocation.
Member Function Documentation
regression_size()
size_t regression_size (const SizetVector & ranks, size_t max_rank, const UShortArray & orders, unsigned short max_order)
compute the regression size (number of unknowns) for ranks per dimension and (polynomial) basis orders per dimension
References Dakota::abort_handler(), Approximation::sharedDataRep, and Dakota::sum().
recover_function_train_orders()
void recover_function_train_orders (const std::vector< OneApproxOpts * > & a_opts)
returns the recovered orders, reflecting the latest CV if adapt_order
References C3Approximation::levApproxIter, and Approximation::sharedDataRep.
Referenced by C3Approximation::build().
build()
void build () protected virtual
builds the approximation from scratch
This is the common base class portion of the virtual fn and is insufficient on its own; derived implementations should explicitly invoke (or reimplement) this base class contribution.
Reimplemented from Approximation.
References Approximation::approxData, Approximation::build(), C3FnTrainData::free_all(), C3FnTrainData::function_train(), C3Approximation::levApproxIter, C3Approximation::recover_function_train_orders(), Approximation::sharedDataRep, C3Approximation::synchronize_surrogate_data(), Dakota::SZ_MAX, and Dakota::write_precision.
Referenced by C3Approximation::rebuild().
The documentation for this class was generated from the following files:
C3Approximation.hpp
C3Approximation.cpp