Dakota: Graphics Class Reference
Graphics Class Reference
The Graphics class provides a single interface to 2D (motif) and 3D (PLPLOT) graphics; there is only one instance of this OutputManager::dakotaGraphics.
Public Member Functions
Graphics ()
constructor
~Graphics ()
destructor
void create_plots_2d (const Variables &vars, const Response &response)
creates the 2d graphics window and initializes the plots
void add_datapoint (int graphics_cntr, const Variables &vars, const Response &response)
adds data to each window in the 2d graphics based on the results of a model evaluation
void add_datapoint (int i, double x, double y)
adds data to a single window in the 2d graphics
void new_dataset (int i)
creates a separate line graphic for subsequent data points for a single window in the 2d graphics
void close ()
close graphics windows
void set_x_labels2d (const char *x_label)
set x label for each plot equal to x_label
void set_y_labels2d (const char *y_label)
set y label for each plot equal to y_label
void set_x_label2d (int i, const char *x_label)
set x label for ith plot equal to x_label
void set_y_label2d (int i, const char *y_label)
set y label for ith plot equal to y_label
Private Attributes
Graphics2D * graphics2D
pointer to the 2D graphics object
bool win2dOn
flag to indicate if 2D graphics window is active
Detailed Description
The Graphics class provides a single interface to 2D (motif) and 3D (PLPLOT) graphics; there is only one instance of this OutputManager::dakotaGraphics.
Member Function Documentation
create_plots_2d()
void create_plots_2d (const Variables & vars, const Response & response)
creates the 2d graphics window and initializes the plots
Sets up a single event loop for duration of the dakotaGraphics object, continuously adding data to a single window. There is no reset. To start over with a new data set, you need a new object (delete old and instantiate new).
References Variables::continuous_variable_labels(), Variables::cv(), Variables::discrete_int_variable_labels(), Variables::discrete_real_variable_labels(), Variables::div(), Variables::drv(), Response::function_labels(), Graphics::graphics2D, Response::num_functions(), Dakota::re_match(), and Graphics::win2dOn.
Referenced by Model::create_2d_plots().
add_datapoint() [1/2]
void add_datapoint (int graphics_cntr, const Variables & vars, const Response & response)
adds data to each window in the 2d graphics based on the results of a model evaluation
Adds data to each 2d plot and each tabular data column (one for each active variable and for each response function). graphicsCntr is used for the x axis in the graphics and the first column in the tabular data.
References Response::active_set_request_vector(), Variables::continuous_variables(), Variables::discrete_int_variables(), Variables::discrete_real_variables(), Response::function_values(), Graphics::graphics2D, and Graphics::win2dOn.
Referenced by OutputManager::add_tabular_data(), NonDLocalReliability::mean_value(), and NonDLocalReliability::update_level_data().
add_datapoint() [2/2]
void add_datapoint (int i, double x, double y)
adds data to a single window in the 2d graphics
Adds data to a single 2d plot. Allows complete flexibility in defining other kinds of x-y plotting in the 2D graphics.
References Graphics::graphics2D, and Graphics::win2dOn.
new_dataset()
void new_dataset (int i)
creates a separate line graphic for subsequent data points for a single window in the 2d graphics
Used for displaying multiple data sets within the same plot.
References Graphics::graphics2D, and Graphics::win2dOn.
Referenced by NonDLocalReliability::update_level_data().
The documentation for this class was generated from the following files:
DakotaGraphics.hpp
DakotaGraphics.cpp