Dakota: restart_util.cpp File Reference
restart_util.cpp File Reference
file containing the DAKOTA restart utility main program
Namespaces
Dakota
The primary namespace for DAKOTA.
Functions
void print_usage (std::ostream &s)
print restart utility help message
void print_restart (StringArray pos_args, String print_dest)
print a restart file
void print_restart_pdb (StringArray pos_args, String print_dest)
print a restart file (PDB format)
void print_restart_tabular (StringArray pos_args, String print_dest, unsigned short tabular_format, int tabular_precision)
print a restart file (tabular format)
void read_neutral (StringArray pos_args)
read a restart file (neutral file format)
void repair_restart (StringArray pos_args, String identifier_type)
repair a restart file by removing corrupted evaluations
void concatenate_restart (StringArray pos_args)
concatenate multiple restart files
int main (int argc, char *argv[])
The main program for the DAKOTA restart utility.
Detailed Description
file containing the DAKOTA restart utility main program
Function Documentation
main()
int main (int argc, char * argv[])
The main program for the DAKOTA restart utility.
Parse command line inputs and invoke the appropriate utility function (print_restart(), print_restart_tabular(), read_neutral(), repair_restart(), or concatenate_restart()).
References Dakota::concatenate_restart(), Dakota::print_restart(), Dakota::print_restart_pdb(), Dakota::print_restart_tabular(), Dakota::print_usage(), Dakota::read_neutral(), Dakota::repair_restart(), and Dakota::write_precision.