Dakota: GP_Objective Class Reference
GP_Objective Class Reference
ROL objective function for the Gaussian Process (GP) surrogate.
Inherits Objective< double >.
Public Member Functions
GP_Objective (GaussianProcess &gp_model)
Constructor for GP_Objective.
double value (const ROL::Vector< double > &p, double &tol)
Get the value of the objective function at a point.
void gradient (ROL::Vector< double > &g, const ROL::Vector< double > &p, double &tol)
Get the gradient of the objective function at a point.
Private Member Functions
bool pdiff (const std::vector< double > &pnew)
Compute the l2 norm of the difference between new and old parameter vectors.
ROL::Ptr< const std::vector< double > > getVector (const ROL::Vector< double > &vec)
Convert a const ROL Vector to a ROL::Ptr<const std::vector>
ROL::Ptr< std::vector< double > > getVector (ROL::Vector< double > &vec)
Convert a ROL Vector to a ROL::Ptr<std::vector>
Private Attributes
GaussianProcess & gp
Pointer to the GaussianProcess surrogate.
int nopt
Number of optimization variables.
double Jold
Previously computed value of the objective function.
VectorXd grad_old
Previously computed gradient of the objective function.
VectorXd pold
Previous value of the parameter vector.
Detailed Description
ROL objective function for the Gaussian Process (GP) surrogate.
Constructor & Destructor Documentation
GP_Objective()
GP_Objective (GaussianProcess & gp_model)
Constructor for GP_Objective.
Parameters
[in] gp_model Reference to the GaussianProcess surrogate.
References GaussianProcess::get_num_opt_variables(), GP_Objective::gp, GP_Objective::grad_old, GP_Objective::Jold, GP_Objective::nopt, and GP_Objective::pold.
Member Function Documentation
value()
double value (const ROL::Vector< double > & p, double & tol)
Get the value of the objective function at a point.
Parameters
[in] p ROL vector of parameters.
[in] tol Tolerance for inexact evaluation (not used here).
References GP_Objective::getVector(), GP_Objective::gp, GaussianProcess::negative_marginal_log_likelihood(), GP_Objective::nopt, GP_Objective::pdiff(), GaussianProcess::set_opt_params(), and dakota::silence_unused_args().
gradient()
void gradient (ROL::Vector< double > & g, const ROL::Vector< double > & p, double & tol)
Get the gradient of the objective function at a point.
Parameters
[out] g Gradient of the objective function.
[in] p ROL vector of parameters.
[in] tol Tolerance for inexact evaluation (not used here).
References GP_Objective::getVector(), GP_Objective::gp, GaussianProcess::negative_marginal_log_likelihood(), GP_Objective::nopt, GP_Objective::pdiff(), GaussianProcess::set_opt_params(), and dakota::silence_unused_args().
pdiff()
bool pdiff (const std::vector< double > & pnew) private
Compute the l2 norm of the difference between new and old parameter vectors.
Parameters
[in] pnew New value of the parameter vector.
References dakota::near_zero, GP_Objective::nopt, and GP_Objective::pold.
Referenced by GP_Objective::gradient(), and GP_Objective::value().
getVector() [1/2]
ROL::Ptr<const std::vector<double> > getVector (const ROL::Vector< double > & vec) inline private
Convert a const ROL Vector to a ROL::Ptr<const std::vector>
Parameters
[in] vec const ROL vector
Referenced by GP_Objective::getVector(), GP_Objective::gradient(), and GP_Objective::value().
getVector() [2/2]
ROL::Ptr<std::vector<double> > getVector (ROL::Vector< double > & vec) inline private
Convert a ROL Vector to a ROL::Ptr<std::vector>
Parameters
[in] vec ROL vector
References GP_Objective::getVector().
The documentation for this class was generated from the following files:
SurrogatesGPObjective.hpp
SurrogatesGPObjective.cpp