Dakota: Model Class Reference
Model Class Reference
Base class for the model class hierarchy.
Public Member Functions
Model ()
default constructor
Model (ProblemDescDB &problem_db)
standard constructor for envelope
Model (const Model &model)
copy constructor
virtual ~Model ()
destructor
Model operator= (const Model &model)
assignment operator
virtual Iterator & subordinate_iterator ()
return the sub-iterator in nested and surrogate models
virtual Model & subordinate_model ()
return a single sub-model defined from subModel in nested and recast models and truth_model() in surrogate models; used for a directed dive through model recursions that may bypass some components.
virtual void active_model_key (const Pecos::ActiveKey &key)
set the active model key within surrogate data, grid driver, and approximation classes that support the management of multiple approximation states within surrogate models
virtual const Pecos::ActiveKey & active_model_key () const
return the active model key (used by surrogate data, grid driver, and approximation classes to support the management of multiple approximation states within surrogate models)
virtual void clear_model_keys ()
reset by removing all model keys within surrogate data, grid driver, and approximation classes that support the management of multiple approximation states within surrogate models
virtual size_t qoi () const
return number of unique response functions (managing any aggregations)
virtual Model & surrogate_model (size_t i=_NPOS)
return the i-th approximation sub-model in surrogate models
virtual const Model & surrogate_model (size_t i=_NPOS) const
return the i-th approximation sub-model in surrogate models
virtual Model & truth_model ()
return the truth sub-model in surrogate models
virtual const Model & truth_model () const
return the truth sub-model in surrogate models
virtual unsigned short active_surrogate_model_form (size_t i) const
return the model form of the i-th active surrogate model
virtual unsigned short active_truth_model_form () const
return the model form of the active truth model
virtual Model & active_surrogate_model (size_t i=_NPOS)
return the i-th active approximation sub-model in surrogate models
virtual const Model & active_surrogate_model (size_t i=_NPOS) const
return the i-th active approximation sub-model in surrogate models
virtual Model & active_truth_model ()
return the active truth sub-model in surrogate models
virtual const Model & active_truth_model () const
return the active truth sub-model in surrogate models
virtual bool multifidelity () const
identify if hierarchy is across model forms
virtual bool multilevel () const
identify if hierarchy is across resolution levels
virtual bool multilevel_multifidelity () const
identify if hierarchy is across both model forms and resolution levels
virtual bool multifidelity_precedence () const
return precedence for hierarchy definition, model forms or resolution levels
virtual void multifidelity_precedence (bool mf_prec, bool update_default=false)
assign precedence for hierarchy definition (model forms or resolution levels) as determined from algorithm context
virtual void derived_subordinate_models (ModelList &ml, bool recurse_flag)
portion of subordinate_models() specific to derived model classes
virtual void resize_from_subordinate_model (size_t depth=SZ_MAX)
resize vars/resp if needed from the bottom up
virtual void update_from_subordinate_model (size_t depth=SZ_MAX)
propagate vars/labels/bounds/targets from the bottom up
virtual Interface & derived_interface ()
return the interface employed by the derived model class, if present: SimulationModel::userDefinedInterface, DataFitSurrModel::approxInterface, or NestedModel::optionalInterface
virtual size_t solution_levels (bool lwr_bnd=true) const
number of discrete levels within solution control (SimulationModel)
virtual void solution_level_cost_index (size_t index)
activate a particular level within the solution level control (SimulationModel)
virtual size_t solution_level_cost_index () const
return currently active level within the solution level control (SimulationModel)
virtual RealVector solution_level_costs () const
return ordered cost estimates across solution levels (SimulationModel)
virtual Real solution_level_cost () const
return currently active cost estimate from solution level control (SimulationModel)
virtual short solution_control_variable_type () const
return type of solution control variable
virtual size_t solution_control_variable_index () const
return index of solution control variable within all variables
virtual size_t solution_control_discrete_variable_index () const
return index of solution control variable within all discrete variables
virtual int solution_level_int_value () const
return the active (integer) value of the solution control
virtual String solution_level_string_value () const
return the active (string) value of the solution control
virtual Real solution_level_real_value () const
return the active (real) value of the solution control
virtual size_t cost_metadata_index () const
return index of online cost estimates within metadata
virtual void primary_response_fn_weights (const RealVector &wts, bool recurse_flag=true)
set the relative weightings for multiple objective functions or least squares terms
virtual void surrogate_function_indices (const SizetSet &surr_fn_indices)
set the (currently active) surrogate function index set
virtual Pecos::ProbabilityTransformation & probability_transformation ()
return probability transformation employed by the Model (forwarded along to ProbabilityTransformModel recasting)
virtual bool initialize_mapping (ParLevLIter pl_iter)
Perform any global updates prior to individual evaluate() calls; returns true if the variables size has changed.
virtual bool finalize_mapping ()
restore state in preparation for next initialization; returns true if the variables size has changed
virtual bool resize_pending () const
return true if a potential resize is still pending, such that sizing-based initialization should be deferred
virtual void nested_variable_mappings (const SizetArray &c_index1, const SizetArray &di_index1, const SizetArray &ds_index1, const SizetArray &dr_index1, const ShortArray &c_target2, const ShortArray &di_target2, const ShortArray &ds_target2, const ShortArray &dr_target2)
set primaryA{C,DI,DS,DR}VarMapIndices, secondaryA{C,DI,DS,DR}VarMapTargets (coming from a higher-level NestedModel context to inform derivative est.)
virtual const SizetArray & nested_acv1_indices () const
return primaryACVarMapIndices
virtual const ShortArray & nested_acv2_targets () const
return secondaryACVarMapTargets
virtual short query_distribution_parameter_derivatives () const
calculate and return derivative composition of final results w.r.t. distribution parameters (none, all, or mixed)
virtual void activate_distribution_parameter_derivatives ()
activate derivative setting w.r.t. distribution parameters
virtual void deactivate_distribution_parameter_derivatives ()
deactivate derivative setting w.r.t. distribution parameters
virtual void trans_U_to_X (const RealVector &u_c_vars, RealVector &x_c_vars)
transform u-space variable values to x-space
virtual void trans_X_to_U (const RealVector &x_c_vars, RealVector &u_c_vars)
transform x-space variable values to u-space
virtual void trans_grad_X_to_U (const RealVector &fn_grad_x, RealVector &fn_grad_u, const RealVector &x_vars)
transform x-space gradient vector to u-space
virtual void trans_grad_U_to_X (const RealVector &fn_grad_u, RealVector &fn_grad_x, const RealVector &x_vars)
transform u-space gradient vector to x-space
virtual void trans_grad_X_to_S (const RealVector &fn_grad_x, RealVector &fn_grad_s, const RealVector &x_vars)
transform x-space gradient vector to gradient with respect to inserted distribution parameters
virtual void trans_hess_X_to_U (const RealSymMatrix &fn_hess_x, RealSymMatrix &fn_hess_u, const RealVector &x_vars, const RealVector &fn_grad_x)
transform x-space Hessian matrix to u-space
virtual void build_approximation ()
build a new SurrogateModel approximation
virtual bool build_approximation (const Variables &vars, const IntResponsePair &response_pr)
build a new SurrogateModel approximation using/enforcing anchor response at vars; rebuild if needed
virtual void rebuild_approximation ()
incremental rebuild of an existing SurrogateModel approximation
virtual void rebuild_approximation (const IntResponsePair &response_pr)
incremental rebuild of an existing SurrogateModel approximation
virtual void rebuild_approximation (const IntResponseMap &resp_map)
incremental rebuild of an existing SurrogateModel approximation
virtual void update_approximation (bool rebuild_flag)
replace the approximation data within an existing surrogate based on data updates propagated elsewhere
virtual void update_approximation (const Variables &vars, const IntResponsePair &response_pr, bool rebuild_flag)
replace the anchor point data within an existing surrogate
virtual void update_approximation (const VariablesArray &vars_array, const IntResponseMap &resp_map, bool rebuild_flag)
replace the data points within an existing surrogate
virtual void update_approximation (const RealMatrix &samples, const IntResponseMap &resp_map, bool rebuild_flag)
replace the data points within an existing surrogate
virtual void append_approximation (bool rebuild_flag)
append to the existing approximation data within a surrogate based on data updates propagated elsewhere
virtual void append_approximation (const Variables &vars, const IntResponsePair &response_pr, bool rebuild_flag)
append a single point to an existing surrogate's data
virtual void append_approximation (const RealMatrix &samples, const IntResponseMap &resp_map, bool rebuild_flag)
append multiple points to an existing surrogate's data
virtual void append_approximation (const VariablesArray &vars_array, const IntResponseMap &resp_map, bool rebuild_flag)
append multiple points to an existing surrogate's data
virtual void append_approximation (const IntVariablesMap &vars_map, const IntResponseMap &resp_map, bool rebuild_flag)
append multiple points to an existing surrogate's data
virtual void replace_approximation (const IntResponsePair &response_pr, bool rebuild_flag)
replace the response for a single point (based on eval id from response_pr) within an existing surrogate's data
virtual void replace_approximation (const IntResponseMap &resp_map, bool rebuild_flag)
replace the responses for a set of points (based on eval ids from resp_map) within an existing surrogate's data
virtual void track_evaluation_ids (bool track)
assigns a flag to track evaluation ids within surrogate data, enabling id-based lookups for data replacement
virtual void pop_approximation (bool save_surr_data, bool rebuild_flag=false)
remove the previous data set addition to a surrogate (e.g., due to a previous append_approximation() call); flag manages storing of surrogate data for use in a subsequent push_approximation()
virtual void push_approximation ()
push a previous approximation data state; reverse of pop_approximation
virtual bool push_available ()
query for whether a trial increment is restorable within a surrogate
virtual void finalize_approximation ()
finalize an approximation by applying all previous trial increments
virtual void combine_approximation ()
combine the current approximation with previously stored data sets
virtual void combined_to_active (bool clear_combined=true)
promote the combined approximation into the active approximation
virtual void clear_inactive ()
clear inactive approximations (finalization + combination completed)
virtual bool advancement_available ()
query the approximation for available advancement in resolution controls (order, rank, etc.); an input to adaptive refinement strategies
virtual bool formulation_updated () const
query the approximation for updates in formulation, requiring a rebuild even if no updates to the build data
virtual void formulation_updated (bool update)
assign the status of approximation formulation updates
virtual void run_dace ()
execute the DACE iterator (prior to building/appending the approximation)
virtual bool force_rebuild ()
determine whether a surrogate model rebuild should be forced based on changes in the inactive data
virtual SharedApproxData & shared_approximation ()
retrieve the shared approximation data within the ApproximationInterface of a DataFitSurrModel
virtual std::vector< Approximation > & approximations ()
retrieve the set of Approximations within the ApproximationInterface of a DataFitSurrModel
virtual const Pecos::SurrogateData & approximation_data (size_t fn_index)
retrieve a SurrogateData instance from a particular Approximation instance within the ApproximationInterface of a DataFitSurrModel
virtual const RealVectorArray & approximation_coefficients (bool normalized=false)
retrieve the approximation coefficients from each Approximation within a DataFitSurrModel
virtual void approximation_coefficients (const RealVectorArray &approx_coeffs, bool normalized=false)
set the approximation coefficients for each Approximation within a DataFitSurrModel
virtual const RealVector & approximation_variances (const Variables &vars)
retrieve the prediction variances from each Approximation within a DataFitSurrModel
virtual void surrogate_response_mode (short mode)
set response computation mode used in SurrogateModels for forming currentResponse
virtual short surrogate_response_mode () const
return response computation mode used in SurrogateModels for forming currentResponse
virtual void discrepancy_emulation_mode (short mode)
set discrepancy emulation mode used in SurrogateModels for approximating response differences
virtual const RealVector & error_estimates ()
retrieve error estimates corresponding to the Model's response (could be surrogate error for SurrogateModels, statistical MSE for NestedModels, or adjoint error estimates for SimulationModels). Errors returned correspond to most recent evaluate().
virtual DiscrepancyCorrection & discrepancy_correction ()
return the DiscrepancyCorrection object used by SurrogateModels
virtual void correction_type (short corr_type)
set the correction type from the DiscrepancyCorrection object used by SurrogateModels
virtual short correction_type () const
return the correction type from the DiscrepancyCorrection object used by SurrogateModels
virtual short correction_order () const
return the correction order from the DiscrepancyCorrection object used by SurrogateModels
virtual unsigned short correction_mode () const
return correctionMode
virtual void correction_mode (unsigned short corr_mode)
set correctionMode
virtual void single_apply (const Variables &vars, Response &resp, const Pecos::ActiveKey &paired_key)
apply a DiscrepancyCorrection to correct an approximation within an EnsembleSurrModel
virtual void recursive_apply (const Variables &vars, Response &resp)
apply a sequence of DiscrepancyCorrections to recursively correct an approximation within an EnsembleSurrModel
virtual void component_parallel_mode (short mode)
update componentParallelMode for supporting parallelism in model sub-components
virtual IntIntPair estimate_partition_bounds (int max_eval_concurrency)
estimate the minimum and maximum partition sizes that can be utilized by this Model
virtual size_t mi_parallel_level_index () const
return the index for the metaiterator-iterator parallelism level within ParallelConfiguration::miPLIters that is active for use in a particular Model at runtime
virtual void cache_unmatched_response (int raw_id)
migrate an unmatched response record from active response map (computed by synchronize() or synhronize_nowait()) to cached response map
virtual void cache_unmatched_responses ()
migrate remaining response records from responseMap to cachedResponseMap
virtual short local_eval_synchronization ()
return derived model synchronization setting
virtual int local_eval_concurrency ()
return derived model asynchronous evaluation concurrency
virtual void serve_run (ParLevLIter pl_iter, int max_eval_concurrency)
Service job requests received from the master. Completes when a termination message is received from stop_servers().
virtual void stop_servers ()
Executed by the master to terminate all server operations for a particular model when iteration on the model is complete.
virtual bool derived_master_overload () const
Return a flag indicating the combination of multiprocessor evaluations and a dedicated master iterator scheduling. Used in synchronous evaluate functions to prevent the error of trying to run a multiprocessor job on the master.
virtual void create_2d_plots ()
create 2D graphics plots for automatic logging of vars/response data
virtual void create_tabular_datastream ()
create a tabular output stream for automatic logging of vars/response data
virtual void derived_auto_graphics (const Variables &vars, const Response &resp)
Update tabular/graphics data with latest variables/response data.
virtual void active_view (short view, bool recurse_flag=true)
update the Model's active view based on a higher level context
virtual void inactive_view (short view, bool recurse_flag=true)
update the Model's inactive view based on a higher level context
virtual const String & interface_id () const
return the interface identifier
virtual int derived_evaluation_id () const
Return the value of the evaluation id counter for the Model.
virtual bool evaluation_cache (bool recurse_flag=true) const
Indicates the usage of an evaluation cache by the Model.
virtual bool restart_file (bool recurse_flag=true) const
Indicates the usage of a restart file by the Model.
virtual void set_evaluation_reference ()
Set the reference points for the evaluation counters within the Model.
virtual void fine_grained_evaluation_counters ()
Request fine-grained evaluation reporting within the Model.
virtual void print_evaluation_summary (std::ostream &s, bool minimal_header=false, bool relative_count=true) const
Print an evaluation summary for the Model.
virtual void eval_tag_prefix (const String &eval_id_str)
set the hierarchical eval ID tag prefix
virtual bool db_lookup (const Variables &search_vars, const ActiveSet &search_set, Response &found_resp)
search the eval database (during derivative estimation); derived may need to reimplement due to problem transformations (RecastModel); return true if found in DB
virtual void stop_init_mapping (ParLevLIter pl_iter)
called from IteratorScheduler::run_iterator() for iteratorComm rank 0 to terminate serve_init_mapping() on other iteratorComm processors
virtual int serve_init_mapping (ParLevLIter pl_iter)
called from IteratorScheduler::run_iterator() for iteratorComm rank != 0 to balance resize() calls on iteratorComm rank 0
virtual void stop_finalize_mapping (ParLevLIter pl_iter)
called from IteratorScheduler::run_iterator() for iteratorComm rank 0 to terminate serve_finalize_mapping() on other iteratorComm processors
virtual int serve_finalize_mapping (ParLevLIter pl_iter)
called from IteratorScheduler::run_iterator() for iteratorComm rank != 0 to balance resize() calls on iteratorComm rank 0
virtual void warm_start_flag (const bool flag)
set the warm start flag (warmStartFlag)
virtual void declare_sources ()
Declare a model's sources to the evaluationsDB.
ModelList & subordinate_models (bool recurse_flag=true)
return the sub-models in nested and surrogate models
void evaluate ()
Compute the Response at currentVariables (default ActiveSet).
void evaluate (const ActiveSet &set)
Compute the Response at currentVariables (specified ActiveSet).
void evaluate_nowait ()
Spawn an asynchronous job (or jobs) that computes the value of the Response at currentVariables (default ActiveSet).
void evaluate_nowait (const ActiveSet &set)
Spawn an asynchronous job (or jobs) that computes the value of the Response at currentVariables (specified ActiveSet).
const IntResponseMap & synchronize ()
Execute a blocking scheduling algorithm to collect the complete set of results from a group of asynchronous evaluations.
const IntResponseMap & synchronize_nowait ()
Execute a nonblocking scheduling algorithm to collect all available results from a group of asynchronous evaluations.
int evaluation_id () const
return Model's (top-level) evaluation counter, not to be confused with derived counter returned by derived_evaluation_id()
bool mapping_initialized () const
void init_communicators (ParLevLIter pl_iter, int max_eval_concurrency, bool recurse_flag=true)
allocate communicator partitions for a model and store configuration in modelPCIterMap
void init_serial ()
for cases where init_communicators() will not be called, modify some default settings to behave properly in serial.
void set_communicators (ParLevLIter pl_iter, int max_eval_concurrency, bool recurse_flag=true)
set active parallel configuration for the model (set modelPCIter from modelPCIterMap)
void free_communicators (ParLevLIter pl_iter, int max_eval_concurrency, bool recurse_flag=true)
deallocate communicator partitions for a model
MPI_Comm analysis_comm () const
retrieve the MPI communicator on which this model is configured to conduct function evaluation analyses (provided for library clients)
void stop_init_communicators (ParLevLIter pl_iter)
called from IteratorScheduler::init_iterator() for iteratorComm rank 0 to terminate serve_init_communicators() on other iteratorComm processors
int serve_init_communicators (ParLevLIter pl_iter)
called from IteratorScheduler::init_iterator() for iteratorComm rank != 0 to balance init_communicators() calls on iteratorComm rank 0
void estimate_message_lengths ()
estimate messageLengths for a model
size_t response_size () const
return (potentially aggregated) size of response vector in currentResponse
bool manage_data_recastings ()
initialize modelList and recastFlags for data import/export
bool recastings () const
return true if recastFlags is defined
void user_space_to_iterator_space (const Variables &user_vars, const Response &user_resp, Variables &iter_vars, Response &iter_resp)
employ the model recursion to transform from bottom level user-space data to top level iterator-space data
void iterator_space_to_user_space (const Variables &iter_vars, const Response &iter_resp, Variables &user_vars, Response &user_resp)
employ the model recursion to transform from top level iterator-space data to bottom level user-space data
void assign_rep (std::shared_ptr< Model > model_rep)
replaces existing letter with a new one
size_t tv () const
returns total number of vars
size_t cv () const
returns number of active continuous variables
size_t div () const
returns number of active discrete integer vars
size_t dsv () const
returns number of active discrete string vars
size_t drv () const
returns number of active discrete real vars
size_t icv () const
returns number of inactive continuous variables
size_t idiv () const
returns number of inactive discrete integer vars
size_t idsv () const
returns number of inactive discrete string vars
size_t idrv () const
returns number of inactive discrete real vars
size_t acv () const
returns total number of continuous variables
size_t adiv () const
returns total number of discrete integer vars
size_t adsv () const
returns total number of discrete string vars
size_t adrv () const
returns total number of discrete real vars
void active_variables (const Variables &vars)
set the active variables in currentVariables
void inactive_variables (const Variables &vars)
set the inactive variables in currentVariables
const RealVector & continuous_variables () const
return the active continuous variables from currentVariables
Real continuous_variable (size_t i) const
return an active continuous variable from currentVariables
void continuous_variables (const RealVector &c_vars)
set the active continuous variables in currentVariables
void continuous_variable (Real c_var, size_t i)
set an active continuous variable in currentVariables
const IntVector & discrete_int_variables () const
return the active discrete integer variables from currentVariables
int discrete_int_variable (size_t i) const
return an active discrete integer variable from currentVariables
void discrete_int_variables (const IntVector &d_vars)
set the active discrete integer variables in currentVariables
void discrete_int_variable (int d_var, size_t i)
set an active discrete integer variable in currentVariables
StringMultiArrayConstView discrete_string_variables () const
return the active discrete string variables from currentVariables
const String & discrete_string_variable (size_t i) const
return an active discrete string variable from currentVariables
void discrete_string_variables (StringMultiArrayConstView d_vars)
set the active discrete string variables in currentVariables
void discrete_string_variable (const String &d_var, size_t i)
set an active discrete string variable in currentVariables
const RealVector & discrete_real_variables () const
return the active discrete real variables from currentVariables
Real discrete_real_variable (size_t i) const
return an active discrete real variable from currentVariables
void discrete_real_variables (const RealVector &d_vars)
set the active discrete real variables in currentVariables
void discrete_real_variable (Real d_var, size_t i)
set an active discrete real variable in currentVariables
UShortMultiArrayConstView continuous_variable_types () const
return the active continuous variable types from currentVariables
void continuous_variable_types (UShortMultiArrayConstView cv_types)
set the active continuous variable types in currentVariables
void continuous_variable_type (unsigned short cv_type, size_t i)
set an active continuous variable type in currentVariables
UShortMultiArrayConstView discrete_int_variable_types () const
return the active discrete variable types from currentVariables
void discrete_int_variable_types (UShortMultiArrayConstView div_types)
set the active discrete variable types in currentVariables
void discrete_int_variable_type (unsigned short div_type, size_t i)
set an active discrete variable type in currentVariables
UShortMultiArrayConstView discrete_string_variable_types () const
return the active discrete variable types from currentVariables
void discrete_string_variable_types (UShortMultiArrayConstView div_types)
set the active discrete variable types in currentVariables
void discrete_string_variable_type (unsigned short div_type, size_t i)
set an active discrete variable type in currentVariables
UShortMultiArrayConstView discrete_real_variable_types () const
return the active discrete variable types from currentVariables
void discrete_real_variable_types (UShortMultiArrayConstView drv_types)
set the active discrete variable types in currentVariables
void discrete_real_variable_type (unsigned short drv_type, size_t i)
set an active discrete variable type in currentVariables
SizetMultiArrayConstView continuous_variable_ids () const
return the active continuous variable identifiers from currentVariables
void continuous_variable_ids (SizetMultiArrayConstView cv_ids)
set the active continuous variable identifiers in currentVariables
void continuous_variable_id (size_t cv_id, size_t i)
set an active continuous variable identifier in currentVariables
const RealVector & inactive_continuous_variables () const
return the inactive continuous variables in currentVariables
void inactive_continuous_variables (const RealVector &i_c_vars)
set the inactive continuous variables in currentVariables
const IntVector & inactive_discrete_int_variables () const
return the inactive discrete variables in currentVariables
void inactive_discrete_int_variables (const IntVector &i_d_vars)
set the inactive discrete variables in currentVariables
StringMultiArrayConstView inactive_discrete_string_variables () const
return the inactive discrete variables in currentVariables
void inactive_discrete_string_variables (StringMultiArrayConstView i_d_vars)
set the inactive discrete variables in currentVariables
const RealVector & inactive_discrete_real_variables () const
return the inactive discrete variables in currentVariables
void inactive_discrete_real_variables (const RealVector &i_d_vars)
set the inactive discrete variables in currentVariables
UShortMultiArrayConstView inactive_continuous_variable_types () const
return the inactive continuous variable types from currentVariables
SizetMultiArrayConstView inactive_continuous_variable_ids () const
return the inactive continuous variable identifiers from currentVariables
const RealVector & all_continuous_variables () const
return all continuous variables in currentVariables
void all_continuous_variables (const RealVector &a_c_vars)
set all continuous variables in currentVariables
void all_continuous_variable (Real a_c_var, size_t i)
set a variable within the all continuous variables in currentVariables
const IntVector & all_discrete_int_variables () const
return all discrete variables in currentVariables
void all_discrete_int_variables (const IntVector &a_d_vars)
set all discrete variables in currentVariables
void all_discrete_int_variable (int a_d_var, size_t i)
set a variable within the all discrete variables in currentVariables
StringMultiArrayConstView all_discrete_string_variables () const
return all discrete variables in currentVariables
void all_discrete_string_variables (StringMultiArrayConstView a_d_vars)
set all discrete variables in currentVariables
void all_discrete_string_variable (const String &a_d_var, size_t i)
set a variable within the all discrete variables in currentVariables
const RealVector & all_discrete_real_variables () const
return all discrete variables in currentVariables
void all_discrete_real_variables (const RealVector &a_d_vars)
set all discrete variables in currentVariables
void all_discrete_real_variable (Real a_d_var, size_t i)
set a variable within the all discrete variables in currentVariables
UShortMultiArrayConstView all_continuous_variable_types () const
return all continuous variable types from currentVariables
UShortMultiArrayConstView all_discrete_int_variable_types () const
return all discrete variable types from currentVariables
UShortMultiArrayConstView all_discrete_string_variable_types () const
return all discrete variable types from currentVariables
UShortMultiArrayConstView all_discrete_real_variable_types () const
return all discrete variable types from currentVariables
SizetMultiArrayConstView all_continuous_variable_ids () const
return all continuous variable identifiers from currentVariables
const BitArray & discrete_int_sets ()
define and return discreteIntSets using active view from currentVariables
const BitArray & discrete_int_sets (short active_view)
define and return discreteIntSets using passed active view
const IntSetArray & discrete_set_int_values ()
return the sets of values available for each of the active discrete set integer variables (aggregated in activeDiscSetIntValues)
const IntSetArray & discrete_set_int_values (short active_view)
return the sets of values available for each of the active discrete set integer variables (aggregated in activeDiscSetIntValues)
const StringSetArray & discrete_set_string_values ()
return the sets of values available for each of the active discrete set string variables (aggregated in activeDiscSetStringValues)
const StringSetArray & discrete_set_string_values (short active_view)
return the sets of values available for each of the active discrete set string variables (aggregated in activeDiscSetStringValues)
const RealSetArray & discrete_set_real_values ()
return the sets of values available for each of the active discrete set real variables (aggregated in activeDiscSetRealValues)
const RealSetArray & discrete_set_real_values (short active_view)
return the sets of values available for each of the active discrete set real variables (aggregated in activeDiscSetRealValues)
Pecos::MultivariateDistribution & multivariate_distribution ()
return mvDist
const Pecos::MultivariateDistribution & multivariate_distribution () const
return mvDist
StringMultiArrayConstView continuous_variable_labels () const
return the active continuous variable labels from currentVariables
void continuous_variable_labels (StringMultiArrayConstView c_v_labels)
set the active continuous variable labels in currentVariables
StringMultiArrayConstView discrete_int_variable_labels () const
return the active discrete variable labels from currentVariables
void discrete_int_variable_labels (StringMultiArrayConstView d_v_labels)
set the active discrete variable labels in currentVariables
StringMultiArrayConstView discrete_string_variable_labels () const
return the active discrete variable labels from currentVariables
void discrete_string_variable_labels (StringMultiArrayConstView d_v_labels)
set the active discrete variable labels in currentVariables
StringMultiArrayConstView discrete_real_variable_labels () const
return the active discrete variable labels from currentVariables
void discrete_real_variable_labels (StringMultiArrayConstView d_v_labels)
set the active discrete variable labels in currentVariables
StringArray ordered_labels () const
Return labels of all active variables in "input spec" order.
StringMultiArrayConstView inactive_continuous_variable_labels () const
return the inactive continuous variable labels in currentVariables
void inactive_continuous_variable_labels (StringMultiArrayConstView i_c_v_labels)
set the inactive continuous variable labels in currentVariables
StringMultiArrayConstView inactive_discrete_int_variable_labels () const
return the inactive discrete variable labels in currentVariables
void inactive_discrete_int_variable_labels (StringMultiArrayConstView i_d_v_labels)
set the inactive discrete variable labels in currentVariables
StringMultiArrayConstView inactive_discrete_string_variable_labels () const
return the inactive discrete variable labels in currentVariables
void inactive_discrete_string_variable_labels (StringMultiArrayConstView i_d_v_labels)
set the inactive discrete variable labels in currentVariables
StringMultiArrayConstView inactive_discrete_real_variable_labels () const
return the inactive discrete variable labels in currentVariables
void inactive_discrete_real_variable_labels (StringMultiArrayConstView i_d_v_labels)
set the inactive discrete variable labels in currentVariables
StringArray inactive_ordered_labels () const
Return labels of all inactive variables in "input spec" order.
StringMultiArrayConstView all_continuous_variable_labels () const
return all continuous variable labels in currentVariables
void all_continuous_variable_labels (StringMultiArrayConstView a_c_v_labels)
set all continuous variable labels in currentVariables
void all_continuous_variable_label (const String &a_c_v_label, size_t i)
set a label within the all continuous labels in currentVariables
StringMultiArrayConstView all_discrete_int_variable_labels () const
return all discrete variable labels in currentVariables
void all_discrete_int_variable_labels (StringMultiArrayConstView a_d_v_labels)
set all discrete variable labels in currentVariables
void all_discrete_int_variable_label (const String &a_d_v_label, size_t i)
set a label within the all discrete labels in currentVariables
StringMultiArrayConstView all_discrete_string_variable_labels () const
return all discrete variable labels in currentVariables
void all_discrete_string_variable_labels (StringMultiArrayConstView a_d_v_labels)
set all discrete variable labels in currentVariables
void all_discrete_string_variable_label (const String &a_d_v_label, size_t i)
set a label within the all discrete labels in currentVariables
StringMultiArrayConstView all_discrete_real_variable_labels () const
return all discrete variable labels in currentVariables
void all_discrete_real_variable_labels (StringMultiArrayConstView a_d_v_labels)
set all discrete variable labels in currentVariables
void all_discrete_real_variable_label (const String &a_d_v_label, size_t i)
set a label within the all discrete labels in currentVariables
StringArray all_ordered_labels () const
Return labels of all variables in "input spec" order.
const StringArray & response_labels () const
return the response labels from currentResponse
void response_labels (const StringArray &resp_labels)
set the response labels in currentResponse
const RealVector & continuous_lower_bounds () const
return the active continuous lower bounds from userDefinedConstraints
Real continuous_lower_bound (size_t i) const
return an active continuous lower bound from userDefinedConstraints
void continuous_lower_bounds (const RealVector &c_l_bnds)
set the active continuous lower bounds in userDefinedConstraints
void continuous_lower_bound (Real c_l_bnd, size_t i)
set the i-th active continuous lower bound in userDefinedConstraints
const RealVector & continuous_upper_bounds () const
return the active continuous upper bounds from userDefinedConstraints
Real continuous_upper_bound (size_t i) const
return an active continuous upper bound from userDefinedConstraints
void continuous_upper_bounds (const RealVector &c_u_bnds)
set the active continuous upper bounds in userDefinedConstraints
void continuous_upper_bound (Real c_u_bnd, size_t i)
set the i-th active continuous upper bound from userDefinedConstraints
const IntVector & discrete_int_lower_bounds () const
return the active discrete int lower bounds from userDefinedConstraints
int discrete_int_lower_bound (size_t i) const
return an active discrete int lower bound from userDefinedConstraints
void discrete_int_lower_bounds (const IntVector &d_l_bnds)
set the active discrete int lower bounds in userDefinedConstraints
void discrete_int_lower_bound (int d_l_bnd, size_t i)
set the i-th active discrete int lower bound in userDefinedConstraints
const IntVector & discrete_int_upper_bounds () const
return the active discrete int upper bounds from userDefinedConstraints
int discrete_int_upper_bound (size_t i) const
return an active discrete int upper bound from userDefinedConstraints
void discrete_int_upper_bounds (const IntVector &d_u_bnds)
set the active discrete int upper bounds in userDefinedConstraints
void discrete_int_upper_bound (int d_u_bnd, size_t i)
set the i-th active discrete int upper bound in userDefinedConstraints
const RealVector & discrete_real_lower_bounds () const
return the active discrete real lower bounds from userDefinedConstraints
Real discrete_real_lower_bound (size_t i) const
return an active discrete real lower bound from userDefinedConstraints
void discrete_real_lower_bounds (const RealVector &d_l_bnds)
set the active discrete real lower bounds in userDefinedConstraints
void discrete_real_lower_bound (Real d_l_bnd, size_t i)
set the i-th active discrete real lower bound in userDefinedConstraints
const RealVector & discrete_real_upper_bounds () const
return the active discrete real upper bounds from userDefinedConstraints
Real discrete_real_upper_bound (size_t i) const
return an active discrete real upper bound from userDefinedConstraints
void discrete_real_upper_bounds (const RealVector &d_u_bnds)
set the active discrete real upper bounds in userDefinedConstraints
void discrete_real_upper_bound (Real d_u_bnd, size_t i)
set the i-th active discrete real upper bound in userDefinedConstraints
const RealVector & inactive_continuous_lower_bounds () const
return the inactive continuous lower bounds in userDefinedConstraints
void inactive_continuous_lower_bounds (const RealVector &i_c_l_bnds)
set the inactive continuous lower bounds in userDefinedConstraints
const RealVector & inactive_continuous_upper_bounds () const
return the inactive continuous upper bounds in userDefinedConstraints
void inactive_continuous_upper_bounds (const RealVector &i_c_u_bnds)
set the inactive continuous upper bounds in userDefinedConstraints
const IntVector & inactive_discrete_int_lower_bounds () const
return the inactive discrete lower bounds in userDefinedConstraints
void inactive_discrete_int_lower_bounds (const IntVector &i_d_l_bnds)
set the inactive discrete lower bounds in userDefinedConstraints
const IntVector & inactive_discrete_int_upper_bounds () const
return the inactive discrete upper bounds in userDefinedConstraints
void inactive_discrete_int_upper_bounds (const IntVector &i_d_u_bnds)
set the inactive discrete upper bounds in userDefinedConstraints
const RealVector & inactive_discrete_real_lower_bounds () const
return the inactive discrete lower bounds in userDefinedConstraints
void inactive_discrete_real_lower_bounds (const RealVector &i_d_l_bnds)
set the inactive discrete lower bounds in userDefinedConstraints
const RealVector & inactive_discrete_real_upper_bounds () const
return the inactive discrete upper bounds in userDefinedConstraints
void inactive_discrete_real_upper_bounds (const RealVector &i_d_u_bnds)
set the inactive discrete upper bounds in userDefinedConstraints
const RealVector & all_continuous_lower_bounds () const
return all continuous lower bounds in userDefinedConstraints
void all_continuous_lower_bounds (const RealVector &a_c_l_bnds)
set all continuous lower bounds in userDefinedConstraints
void all_continuous_lower_bound (Real a_c_l_bnd, size_t i)
set a lower bound within continuous lower bounds in userDefinedConstraints
const RealVector & all_continuous_upper_bounds () const
return all continuous upper bounds in userDefinedConstraints
void all_continuous_upper_bounds (const RealVector &a_c_u_bnds)
set all continuous upper bounds in userDefinedConstraints
void all_continuous_upper_bound (Real a_c_u_bnd, size_t i)
set an upper bound within all continuous upper bounds in userDefinedConstraints
const IntVector & all_discrete_int_lower_bounds () const
return all discrete lower bounds in userDefinedConstraints
void all_discrete_int_lower_bounds (const IntVector &a_d_l_bnds)
set all discrete lower bounds in userDefinedConstraints
void all_discrete_int_lower_bound (int a_d_l_bnd, size_t i)
set a lower bound within all discrete lower bounds in userDefinedConstraints
const IntVector & all_discrete_int_upper_bounds () const
return all discrete upper bounds in userDefinedConstraints
void all_discrete_int_upper_bounds (const IntVector &a_d_u_bnds)
set all discrete upper bounds in userDefinedConstraints
void all_discrete_int_upper_bound (int a_d_u_bnd, size_t i)
set an upper bound within all discrete upper bounds in userDefinedConstraints
const RealVector & all_discrete_real_lower_bounds () const
return all discrete lower bounds in userDefinedConstraints
void all_discrete_real_lower_bounds (const RealVector &a_d_l_bnds)
set all discrete lower bounds in userDefinedConstraints
void all_discrete_real_lower_bound (Real a_d_l_bnd, size_t i)
set a lower bound within all discrete lower bounds in userDefinedConstraints
const RealVector & all_discrete_real_upper_bounds () const
return all discrete upper bounds in userDefinedConstraints
void all_discrete_real_upper_bounds (const RealVector &a_d_u_bnds)
set all discrete upper bounds in userDefinedConstraints
void all_discrete_real_upper_bound (Real a_d_u_bnd, size_t i)
set an upper bound within all discrete upper bounds in userDefinedConstraints
size_t num_linear_ineq_constraints () const
reshape the linear/nonlinear constraint arrays
size_t num_linear_eq_constraints () const
return the number of linear equality constraints
const RealMatrix & linear_ineq_constraint_coeffs () const
return the linear inequality constraint coefficients
void linear_ineq_constraint_coeffs (const RealMatrix &lin_ineq_coeffs)
set the linear inequality constraint coefficients
const RealVector & linear_ineq_constraint_lower_bounds () const
return the linear inequality constraint lower bounds
void linear_ineq_constraint_lower_bounds (const RealVector &lin_ineq_l_bnds)
set the linear inequality constraint lower bounds
const RealVector & linear_ineq_constraint_upper_bounds () const
return the linear inequality constraint upper bounds
void linear_ineq_constraint_upper_bounds (const RealVector &lin_ineq_u_bnds)
set the linear inequality constraint upper bounds
const RealMatrix & linear_eq_constraint_coeffs () const
return the linear equality constraint coefficients
void linear_eq_constraint_coeffs (const RealMatrix &lin_eq_coeffs)
set the linear equality constraint coefficients
const RealVector & linear_eq_constraint_targets () const
return the linear equality constraint targets
void linear_eq_constraint_targets (const RealVector &lin_eq_targets)
set the linear equality constraint targets
size_t num_nonlinear_ineq_constraints () const
return the number of nonlinear inequality constraints
size_t num_nonlinear_eq_constraints () const
return the number of nonlinear equality constraints
const RealVector & nonlinear_ineq_constraint_lower_bounds () const
return the nonlinear inequality constraint lower bounds
void nonlinear_ineq_constraint_lower_bounds (const RealVector &nln_ineq_l_bnds)
set the nonlinear inequality constraint lower bounds
const RealVector & nonlinear_ineq_constraint_upper_bounds () const
return the nonlinear inequality constraint upper bounds
void nonlinear_ineq_constraint_upper_bounds (const RealVector &nln_ineq_u_bnds)
set the nonlinear inequality constraint upper bounds
const RealVector & nonlinear_eq_constraint_targets () const
return the nonlinear equality constraint targets
void nonlinear_eq_constraint_targets (const RealVector &nln_eq_targets)
set the nonlinear equality constraint targets
const Variables & current_variables () const
return the current variables (currentVariables) as const reference (preferred)
Variables & current_variables ()
return the current variables (currentVariables) in mutable form (special cases)
const Constraints & user_defined_constraints () const
return the user-defined constraints (userDefinedConstraints) as const reference (preferred)
Constraints & user_defined_constraints ()
return the user-defined constraints (userDefinedConstraints) in mutable form (special cases)
const Response & current_response () const
return the current response (currentResponse)
ProblemDescDB & problem_description_db () const
return the problem description database (probDescDB)
ParallelLibrary & parallel_library () const
return the parallel library (parallelLib)
const String & model_type () const
return the model type (modelType)
const String & surrogate_type () const
return the surrogate type (surrogateType)
const String & model_id () const
return the model identifier (modelId)
size_t num_primary_fns () const
return number of primary functions (total less nonlinear constraints)
size_t num_secondary_fns () const
return number of secondary functions (number of nonlinear constraints)
const String & gradient_type () const
return the gradient evaluation type (gradientType)
const String & method_source () const
return the numerical gradient evaluation method source (methodSource)
const String & interval_type () const
return the numerical gradient evaluation interval type (intervalType)
bool ignore_bounds () const
option for ignoring bounds when numerically estimating derivatives
bool central_hess () const
option for using old 2nd-order scheme when computing finite-diff Hessian
const RealVector & fd_gradient_step_size () const
return the finite difference gradient step size (fdGradStepSize)
const String & fd_gradient_step_type () const
return the finite difference gradient step type (fdGradStepType)
const IntSet & gradient_id_analytic () const
return the mixed gradient analytic IDs (gradIdAnalytic)
const IntSet & gradient_id_numerical () const
return the mixed gradient numerical IDs (gradIdNumerical)
const String & hessian_type () const
return the Hessian evaluation type (hessianType)
const String & quasi_hessian_type () const
return the Hessian evaluation type (quasiHessType)
const RealVector & fd_hessian_by_grad_step_size () const
return gradient-based finite difference Hessian step size (fdHessByGradStepSize)
const RealVector & fd_hessian_by_fn_step_size () const
return function-based finite difference Hessian step size (fdHessByFnStepSize)
const String & fd_hessian_step_type () const
return the finite difference Hessian step type (fdHessStepType)
const IntSet & hessian_id_analytic () const
return the mixed Hessian analytic IDs (hessIdAnalytic)
const IntSet & hessian_id_numerical () const
return the mixed Hessian analytic IDs (hessIdNumerical)
const IntSet & hessian_id_quasi () const
return the mixed Hessian analytic IDs (hessIdQuasi)
void primary_response_fn_sense (const BoolDeque &sense)
set the optimization sense for multiple objective functions
const BoolDeque & primary_response_fn_sense () const
get the optimization sense for multiple objective functions
const RealVector & primary_response_fn_weights () const
get the relative weightings for multiple objective functions or least squares terms
const ScalingOptions & scaling_options () const
user-provided scaling options
short primary_fn_type () const
get the primary response function type (generic, objective, calibration)
void primary_fn_type (short type)
set the primary response function type, e.g., when recasting
bool derivative_estimation ()
indicates potential usage of estimate_derivatives() based on gradientType/hessianType
void supports_derivative_estimation (bool sed_flag)
set whether this model should perform or pass on derivative estimation
void init_comms_bcast_flag (bool icb_flag)
set initCommsBcastFlag
int evaluation_capacity () const
return the evaluation capacity for use in iterator logic
int derivative_concurrency () const
return the gradient concurrency for use in parallel configuration logic
bool asynch_flag () const
return the asynchronous evaluation flag (asynchEvalFlag)
void asynch_flag (const bool flag)
set the asynchronous evaluation flag (asynchEvalFlag)
short output_level () const
return the outputLevel
void output_level (const short level)
set the outputLevel
const IntArray & message_lengths () const
return the array of MPI packed message buffer lengths (messageLengths)
void parallel_configuration_iterator (ParConfigLIter pc_iter)
set modelPCIter
ParConfigLIter parallel_configuration_iterator () const
return modelPCIter
void auto_graphics (const bool flag)
set modelAutoGraphicsFlag to activate posting of graphics data within evaluate/synchronize functions (automatic graphics posting in the model as opposed to graphics posting at the strategy level).
bool auto_graphics () const
get modelAutoGraphicsFlag to activate posting of graphics data within evaluate/synchronize functions (automatic graphics posting in the model as opposed to graphics posting at the strategy level).
bool is_null () const
function to check modelRep (does this envelope contain a letter)
std::shared_ptr< Model > model_rep () const
returns modelRep for access to derived class member functions that are not mapped to the top Model level
virtual String root_model_id ()
Return the model ID of the "innermost" model. For all derived Models except RecastModels, return modelId. The RecastModel override returns the root_model_id() of the subModel.
virtual ActiveSet default_active_set ()
Static Public Member Functions
static void active_variables (const RealVector &config_vars, Model &model)
set the specified configuration to the Model's inactive vars, converting from real to integer or through index to string value as needed
static void inactive_variables (const RealVector &config_vars, Model &model)
set the specified configuration to the Model's inactive vars, converting from real to integer or through index to string value as needed
static void inactive_variables (const RealVector &config_vars, Model &model, Variables &updated_vars)
static void evaluate (const RealMatrix &samples_matrix, Model &model, RealMatrix &resp_matrix)
Bulk synchronously evaluate the model for each column (of active variables) in the samples matrix and return as columns of the response matrix.
static void evaluate (const VariablesArray &sample_vars, Model &model, RealMatrix &resp_matrix)
Bulk synchronously evaluate the model for each entry (of active variables) in the samples vector and return as columns of the response matrix.
Protected Member Functions
Model (BaseConstructor, ProblemDescDB &problem_db)
constructor initializing the base class part of letter classes (BaseConstructor overloading avoids infinite recursion in the derived class constructors - Coplien, p. 139)
Model (LightWtBaseConstructor, const ShortShortPair &vars_view, const SharedVariablesData &svd, bool share_svd, const SharedResponseData &srd, bool share_srd, const ActiveSet &set, short output_level, ProblemDescDB &problem_db=dummy_db, ParallelLibrary &parallel_lib=dummy_lib)
constructor initializing base class for derived model class instances constructed on the fly
Model (LightWtBaseConstructor, ProblemDescDB &problem_db=dummy_db, ParallelLibrary &parallel_lib=dummy_lib)
constructor initializing base class for recast model instances
virtual void derived_evaluate (const ActiveSet &set)
portion of evaluate() specific to derived model classes
virtual void derived_evaluate_nowait (const ActiveSet &set)
portion of evaluate_nowait() specific to derived model classes
virtual const IntResponseMap & derived_synchronize ()
portion of synchronize() specific to derived model classes
virtual const IntResponseMap & derived_synchronize_nowait ()
portion of synchronize_nowait() specific to derived model classes
virtual void derived_init_communicators (ParLevLIter pl_iter, int max_eval_concurrency, bool recurse_flag=true)
portion of init_communicators() specific to derived model classes
virtual void derived_init_serial ()
portion of init_serial() specific to derived model classes
virtual void derived_set_communicators (ParLevLIter pl_iter, int max_eval_concurrency, bool recurse_flag=true)
portion of set_communicators() specific to derived model classes
virtual void derived_free_communicators (ParLevLIter pl_iter, int max_eval_concurrency, bool recurse_flag=true)
portion of free_communicators() specific to derived model classes
void update_model_active_variables (Model &model)
update incoming (sub-)model with active values from currentVariables
IntResponseMap & response_map ()
return responseMap
void initialize_distribution (Pecos::MultivariateDistribution &mv_dist, bool active_only=false)
initialize distribution types from problemDescDB
void initialize_active_types (Pecos::MultivariateDistribution &mv_dist)
initialize distribution types from problemDescDB
void initialize_distribution_parameters (Pecos::MultivariateDistribution &mv_dist, bool active_only=false)
initialize distribution parameters from problemDescDB
void set_ie_asynchronous_mode (int max_eval_concurrency)
default logic for defining asynchEvalFlag and evaluationCapacity based on ie_pl settings
void assign_max_strings (const Pecos::MultivariateDistribution &mv_dist, Variables &vars)
assign all of the longest possible string values into vars
SSCIter max_string (const StringSet &ss)
return iterator for longest string value found in string set
SRMCIter max_string (const StringRealMap &srm)
return iterator for longest string value found in string map
SizetMultiArrayConstView initialize_x0_bounds (const SizetArray &original_dvv, bool &active_derivs, bool &inactive_derivs, RealVector &x0, RealVector &fd_lb, RealVector &fd_ub) const
Initialize data needed for computing finite differences (active/inactive, center point, and bounds)
Real forward_grad_step (size_t num_deriv_vars, size_t xj_index, Real x0_j, Real lb_j, Real ub_j)
Compute the forward step for a finite difference gradient; updates shortStep.
EvaluationsDBState evaluations_db_state (const Interface &interface)
Return the interface flag for the EvaluationsDB state.
EvaluationsDBState evaluations_db_state (const Model &model)
Return the model flag for the EvaluationsDB state.
void asynch_eval_store (const Interface &interface, const int &id, const Response &response)
Store the response portion of an interface evaluation. Called from rekey_response_map()
void asynch_eval_store (const Model &model, const int &id, const Response &response)
Exists to support storage of interface evaluations. No-op so that rekey_response_map<Model> can be generated.
template<typename MetaType >
void rekey_response_map (MetaType &meta_object, IntIntMapArray &id_maps, IntResponseMapArray &resp_maps_rekey, bool deep_copy)
rekey returned jobs matched in array of id_maps into array of resp_maps_rekey; unmatched jobs can be cached within the meta_object
template<typename MetaType >
void rekey_response_map (MetaType &meta_object, IntIntMap &id_map, IntResponseMap &resp_map_rekey, bool deep_copy)
rekey returned jobs matched in id_map into resp_map_rekey; unmatched jobs can be cached within the meta_object
template<typename MetaType >
void rekey_synch (MetaType &meta_object, bool block, IntIntMapArray &id_maps, IntResponseMapArray &resp_maps_rekey, bool deep_copy=false)
synchronize via meta_object and rekey returned jobs matched in array of id_maps into array of resp_maps_rekey; unmatched jobs are cached within the meta_object
template<typename MetaType >
void rekey_synch (MetaType &meta_object, bool block, IntIntMap &id_map, IntResponseMap &resp_map_rekey, bool deep_copy=false)
synchronize via meta_object and rekey returned jobs matched in id_map into resp_map_rekey; unmatched jobs are cached within the meta_object
Static Protected Member Functions
static String user_auto_id ()
return the next available model ID for no-ID user methods
static String no_spec_id ()
return the next available model ID for on-the-fly methods
Protected Attributes
Variables currentVariables
the set of current variables used by the model for performing function evaluations
size_t numDerivVars
the number of active continuous variables used in computing most response derivatives (i.e., in places such as quasi-Hessians and response corrections where only the active continuous variables are supported)
Response currentResponse
the set of current responses that holds the results of model function evaluations
size_t numFns
the number of functions in currentResponse
Constraints userDefinedConstraints
Explicit constraints on variables are maintained in the Constraints class hierarchy. Currently, this includes linear constraints and bounds, but could be extended in the future to include other explicit constraints which (1) have their form specified by the user, and (2) are not catalogued in Response since their form and coefficients are published to an iterator at startup.
String modelId
model identifier string from the input file
String modelType
type of model: simulation, nested, or surrogate
String surrogateType
type of surrogate model: local_*, multipoint_*, global_*, or hierarchical
String gradientType
type of gradient data: analytic, numerical, mixed, or none
String methodSource
source of numerical gradient routine: dakota or vendor
String intervalType
type of numerical gradient interval: central or forward
String hessianType
type of Hessian data: analytic, numerical, quasi, mixed, or none
RealVector fdGradStepSize
relative finite difference step size for numerical gradients
String fdGradStepType
type of finite difference step to use for numerical gradient: relative - step length is relative to x absolute - step length is what is specified bounds - step length is relative to range of x
RealVector fdHessByGradStepSize
relative finite difference step size for numerical Hessians estimated using first-order differences of gradients
RealVector fdHessByFnStepSize
relative finite difference step size for numerical Hessians estimated using second-order differences of function values
String fdHessStepType
type of finite difference step to use for numerical Hessian: relative - step length is relative to x absolute - step length is what is specified bounds - step length is relative to range of x
bool ignoreBounds
option to ignore bounds when computing finite diffs
bool centralHess
option to use old 2nd-order finite diffs for Hessians
bool warmStartFlag
if in warm-start mode, don't reset accumulated data (e.g., quasiHessians)
bool supportsEstimDerivs
whether model should perform or forward derivative estimation
String quasiHessType
quasi-Hessian type: bfgs, damped_bfgs, sr1
IntSet gradIdAnalytic
analytic id's for mixed gradients
IntSet gradIdNumerical
numerical id's for mixed gradients
IntSet hessIdAnalytic
analytic id's for mixed Hessians
IntSet hessIdNumerical
numerical id's for mixed Hessians
IntSet hessIdQuasi
quasi id's for mixed Hessians
EvaluationsDBState modelEvaluationsDBState
Whether to write model evals to the evaluations DB.
EvaluationsDBState interfEvaluationsDBState
Whether to write interface evals to the evaluations DB.
IntArray messageLengths
length of packed MPI buffers containing vars, vars/set, response, and PRPair
bool mappingInitialized
track use of initialize_mapping() and finalize_mapping()
ProblemDescDB & probDescDB
class member reference to the problem description database
ParallelLibrary & parallelLib
class member reference to the parallel library
ParConfigLIter modelPCIter
the ParallelConfiguration node used by this Model instance
short componentParallelMode
the component parallelism mode: NO_PARALLEL_MODE, SURROGATE_MODEL_MODE,
bool asynchEvalFlag
flags asynch evaluations (local or distributed)
int evaluationCapacity
capacity for concurrent evaluations supported by the Model
short outputLevel
output verbosity level: {SILENT,QUIET,NORMAL,VERBOSE,DEBUG}_OUTPUT
Pecos::MultivariateDistribution mvDist
the multivariate random variable distribution (in probability space corresponding to currentVariables)
BoolDeque primaryRespFnSense
array of flags (one per primary function) for switching the sense to maximize the primary function (default is minimize)
RealVector primaryRespFnWts
primary response function weightings (either weights for multiobjective optimization or weighted least squares)
bool hierarchicalTagging
whether to perform hierarchical evalID tagging of params/results
ScalingOptions scalingOpts
user-provided scaling data from the problem DB, possibly modified by Recasting
String evalTagPrefix
cached evalTag Prefix from parents to use at evaluate time
EvaluationStore & evaluationsDB
reference to the global evaluation database
Private Member Functions
std::shared_ptr< Model > get_model (ProblemDescDB &problem_db)
Used by the envelope to instantiate the correct letter class.
int estimate_derivatives (const ShortArray &map_asv, const ShortArray &fd_grad_asv, const ShortArray &fd_hess_asv, const ShortArray &quasi_hess_asv, const ActiveSet &original_set, const bool asynch_flag)
evaluate numerical gradients using finite differences. This routine is selected with "method_source dakota" (the default method_source) in the numerical gradient specification.
void synchronize_derivatives (const Variables &vars, const IntResponseMap &fd_responses, Response &new_response, const ShortArray &fd_grad_asv, const ShortArray &fd_hess_asv, const ShortArray &quasi_hess_asv, const ActiveSet &original_set)
combine results from an array of finite difference response objects (fd_grad_responses) into a single response (new_response)
void update_response (const Variables &vars, Response &new_response, const ShortArray &fd_grad_asv, const ShortArray &fd_hess_asv, const ShortArray &quasi_hess_asv, const ActiveSet &original_set, Response &initial_map_response, const RealMatrix &new_fn_grads, const RealSymMatrixArray &new_fn_hessians)
overlay results to update a response object
void update_quasi_hessians (const Variables &vars, Response &new_response, const ActiveSet &original_set)
perform quasi-Newton Hessian updates
bool manage_asv (const ActiveSet &original_set, ShortArray &map_asv_out, ShortArray &fd_grad_asv_out, ShortArray &fd_hess_asv_out, ShortArray &quasi_hess_asv_out)
Coordinates usage of estimate_derivatives() calls based on asv_in.
Real initialize_h (Real x_j, Real lb_j, Real ub_j, Real step_size, String step_type) const
function to determine initial finite difference h (before step length adjustment) based on type of step desired
Real FDstep1 (Real x0_j, Real lb_j, Real ub_j, Real h_mag)
function returning finite-difference step size (affected by bounds)
Real FDstep2 (Real x0_j, Real lb_j, Real ub_j, Real h)
function returning second central-difference step size (affected by bounds)
Private Attributes
int modelEvalCntr
evaluation counter for top-level evaluate() and evaluate_nowait() calls. Differs from lower level counters in case of numerical derivative estimation (several lower level evaluations are assimilated into a single higher level evaluation)
bool estDerivsFlag
flags presence of estimated derivatives within a set of calls to evaluate_nowait()
bool shortStep
flags finite-difference step size adjusted by bounds
std::map< SizetIntPair, ParConfigLIter > modelPCIterMap
map<> used for tracking modelPCIter instances using depth of parallelism level and max evaluation concurrency as the lookup keys
bool initCommsBcastFlag
flag for determining need to bcast the max concurrency from init_communicators(); set from IteratorScheduler::init_iterator()
bool modelAutoGraphicsFlag
flag for posting of graphics data within evaluate() (automatic graphics posting in the model as opposed to graphics posting at the strategy level)
IntVariablesMap varsMap
history of vars populated in evaluate_nowait() and used in synchronize().
std::list< ShortArray > asvList
if estimate_derivatives() is used, transfers ASVs from evaluate_nowait() to synchronize()
std::list< ActiveSet > setList
if estimate_derivatives() is used, transfers ActiveSets from evaluate_nowait() to synchronize()
BoolList initialMapList
transfers initial_map flag values from estimate_derivatives() to synchronize_derivatives()
BoolList dbCaptureList
transfers db_capture flag values from estimate_derivatives() to synchronize_derivatives()
ResponseList dbResponseList
transfers database captures from estimate_derivatives() to synchronize_derivatives()
RealList deltaList
transfers deltas from estimate_derivatives() to synchronize_derivatives()
IntIntMap numFDEvalsMap
tracks the number of evaluations used within estimate_derivatives(). Used in synchronize() as a key for combining finite difference responses into numerical gradients.
IntIntMap rawEvalIdMap
maps from the raw evaluation ids returned by derived_synchronize() and derived_synchronize_nowait() to the corresponding modelEvalCntr id. Used for rekeying responseMap.
RealVectorArray xPrev
previous parameter vectors used in computing s for quasi-Newton updates
RealMatrix fnGradsPrev
previous gradient vectors used in computing y for quasi-Newton updates
RealSymMatrixArray quasiHessians
quasi-Newton Hessian approximations
SizetArray numQuasiUpdates
number of quasi-Newton Hessian updates applied
IntResponseMap responseMap
used to return a map of responses for asynchronous evaluations in final concatenated form. The similar map in Interface contains raw responses.
IntResponseMap cachedResponseMap
caching of responses returned by derived_synchronize{,_nowait}() but not matched within current rawEvalIdMap
IntResponseMap graphicsRespMap
used to cache the data returned from derived_synchronize_nowait() prior to sequential input into the graphics
IntSetArray activeDiscSetIntValues
aggregation of the admissible value sets for all active discrete set integer variables
StringSetArray activeDiscSetStringValues
aggregation of the admissible value sets for all active discrete set string variables
RealSetArray activeDiscSetRealValues
aggregation of the admissible value sets for all active discrete set real variables
BitArray discreteIntSets
key for identifying discrete integer set variables within the active discrete integer variables
short prevDSIView
previous view used in discrete_set_int_values(view): avoids recomputation of activeDiscSetIntValues
short prevDSSView
previous view used in discrete_set_string_values(view): avoids recomputation of activeDiscSetStringValues
short prevDSRView
previous view used in discrete_set_real_values(view): avoids recomputation of activeDiscSetRealValues
ModelList modelList
used to collect sub-models for subordinate_models()
BoolDeque recastFlags
a key indicating which models within a model recursion involve recasting
std::shared_ptr< Model > modelRep
pointer to the letter (initialized only for the envelope)
Static Private Attributes
static size_t noSpecIdNum = 0
the last used model ID number for on-the-fly instantiations (increment before each use)
Friends
bool operator== (const Model &m1, const Model &m2)
equality operator (detect same letter instance)
bool operator!= (const Model &m1, const Model &m2)
inequality operator (detect different letter instances)
Detailed Description
Base class for the model class hierarchy.
The Model class is the base class for one of the primary class hierarchies in DAKOTA. The model hierarchy contains a set of variables, an interface, and a set of responses, and an iterator operates on the model to map the variables into responses using the interface. For memory efficiency and enhanced polymorphism, the model hierarchy employs the "letter/envelope idiom" (see Coplien "Advanced C++", p. 133), for which the base class (Model) serves as the envelope and one of the derived classes (selected in Model::get_model()) serves as the letter.
Constructor & Destructor Documentation
Model() [1/5]
Model ()
default constructor
The default constructor is used in vector<Model> instantiations and for default initialization of Model objects. modelRep is NULL in this case (a populated problem_db is needed to build a meaningful Model object).
Model() [2/5]
Model (ProblemDescDB & problem_db)
standard constructor for envelope
Used for envelope instantiations within strategy constructors. Envelope constructor only needs to extract enough data to properly execute get_model, since Model(BaseConstructor, problem_db) builds the actual base class data for the derived models.
References Dakota::abort_handler(), and Model::modelRep.
Model() [3/5]
Model (const Model & model)
copy constructor
Copy constructor manages sharing of modelRep.
Model() [4/5]
Model (BaseConstructor , ProblemDescDB & problem_db) protected
constructor initializing the base class part of letter classes (BaseConstructor overloading avoids infinite recursion in the derived class constructors - Coplien, p. 139)
This constructor builds the base class data for all inherited models. get_model() instantiates a derived class and the derived class selects this base class constructor in its initialization list (to avoid the recursion of the base class constructor calling get_model() again). Since the letter IS the representation, its representation pointer is set to NULL.
References Dakota::abort_handler(), Model::currentResponse, Dakota::expand_for_fields_sdv(), Model::fdGradStepSize, Model::fdHessByFnStepSize, Model::fdHessByGradStepSize, ProblemDescDB::get_rv(), ProblemDescDB::get_sa(), Model::gradIdNumerical, Model::gradientType, Model::hessianType, Model::hessIdNumerical, Model::initialize_distribution(), Model::initialize_distribution_parameters(), Model::modelId, Model::mvDist, Model::num_primary_fns(), Model::primaryRespFnSense, Model::primaryRespFnWts, Model::probDescDB, Response::shared_data(), Dakota::strbegins(), Dakota::strtolower(), and Model::user_auto_id().
Model() [5/5]
Model (LightWtBaseConstructor , ProblemDescDB & problem_db = dummy_db, ParallelLibrary & parallel_lib = dummy_lib) protected
constructor initializing base class for recast model instances
This constructor also builds the base class data for inherited models. However, it is used for derived models which are instantiated on the fly. Therefore it only initializes a small subset of attributes.
Member Function Documentation
subordinate_iterator()
Iterator & subordinate_iterator () virtual
return the sub-iterator in nested and surrogate models
return by reference requires use of dummy objects, but is important to allow use of assign_rep() since this operation must be performed on the original envelope object.
Reimplemented in RecastModel, NestedModel, and DataFitSurrModel.
References Dakota::dummy_iterator, and Model::modelRep.
Referenced by NonDExpansion::append_expansion(), NonDMultilevelPolynomialChaos::assign_specification_sequence(), NonDMultilevelStochCollocation::assign_specification_sequence(), CONMINOptimizer::check_sub_iterator_conflict(), NCSUOptimizer::check_sub_iterator_conflict(), NonDLocalInterval::check_sub_iterator_conflict(), NonDLocalReliability::check_sub_iterator_conflict(), SOLBase::check_sub_iterator_conflict(), NonDExpansion::compute_expansion(), SurrBasedGlobalMinimizer::core_run(), NonDExpansion::decrement_grid(), NonDExpansion::decrement_order_and_grid(), NonDExpansion::finalize_sets(), NonDGlobalReliability::get_best_sample(), NonDExpansion::increment_grid(), NonDExpansion::increment_order_and_grid(), NonDExpansion::increment_sets(), NonDMultilevelPolynomialChaos::increment_specification_sequence(), NonDMultilevelStochCollocation::increment_specification_sequence(), NonDExpansion::initialize_expansion(), NonDExpansion::initialize_ml_regression(), NonDExpansion::initialize_u_space_grid(), NonDPolynomialChaos::initialize_u_space_model(), NonDStochCollocation::initialize_u_space_model(), NonDExpansion::merge_grid(), NonDExpansion::pop_increment(), NonDExpansion::pre_refinement(), NonDExpansion::print_refinement_diagnostics(), NonDExpansion::push_increment(), NonDExpansion::select_candidate(), NonDExpansion::select_index_set_candidate(), RecastModel::subordinate_iterator(), NonDExpansion::update_expansion(), NonDBayesCalibration::update_model(), NonDExpansion::update_model_from_samples(), and NonDExpansion::update_u_space_sampler().
subordinate_model()
Model & subordinate_model () virtual
return a single sub-model defined from subModel in nested and recast models and truth_model() in surrogate models; used for a directed dive through model recursions that may bypass some components.
return by reference requires use of dummy objects, but is important to allow use of assign_rep() since this operation must be performed on the original envelope object.
Reimplemented in SurrogateModel, RecastModel, and NestedModel.
References Dakota::dummy_model, and Model::modelRep.
Referenced by SurrogateModel::check_rebuild(), NonDGlobalReliability::expected_feasibility(), NonDGlobalReliability::expected_improvement(), AdaptedBasisModel::get_sub_model(), Minimizer::initialize_run(), NonDExpansion::initialize_u_space_grid(), NonDGlobalReliability::optimize_gaussian_process(), Minimizer::original_model(), COLINOptimizer::post_run(), Optimizer::primary_resp_reducer(), DataFitSurrModel::update_global_reference(), and NonDGlobalReliability::x_truth_evaluation().
surrogate_model()
Model & surrogate_model (size_t i = _NPOS) virtual
return the i-th approximation sub-model in surrogate models
return by reference requires use of dummy objects, but is important to allow use of assign_rep() since this operation must be performed on the original envelope object.
Reimplemented in RecastModel, EnsembleSurrModel, and DataFitSurrModel.
References Dakota::dummy_model, and Model::modelRep.
Referenced by Model::active_surrogate_model(), NonDAdaptiveSampling::calc_score_delta_y(), NonDAdaptiveSampling::calc_score_topo_alm_hybrid(), NonDAdaptiveSampling::calc_score_topo_avg_persistence(), NonDAdaptiveSampling::calc_score_topo_bottleneck(), NonDMultilevelSampling::configure_indices(), NonDBayesCalibration::construct_mcmc_model(), SurrBasedGlobalMinimizer::core_run(), NonDMultilevControlVarSampling::evaluate_pilot(), SurrBasedLocalMinimizer::find_approx_response(), NonDMultilevControlVarSampling::multilevel_control_variate_mc_Qcorr(), NonDAdaptiveSampling::output_round_data(), and RecastModel::surrogate_model().
truth_model()
Model & truth_model () virtual
return the truth sub-model in surrogate models
return by reference requires use of dummy objects, but is important to allow use of assign_rep() since this operation must be performed on the original envelope object.
Reimplemented in RecastModel, EnsembleSurrModel, and DataFitSurrModel.
References Model::modelRep.
Referenced by SurrogateModel::activate_distribution_parameter_derivatives(), Model::active_truth_model(), NonDMultilevelSampling::compute_error_estimates(), NonDMultilevelSampling::configure_indices(), SurrBasedGlobalMinimizer::core_run(), SurrogateModel::deactivate_distribution_parameter_derivatives(), NonDMultilevControlVarSampling::evaluate_pilot(), SurrBasedLocalMinimizer::find_truth_response(), NonDNonHierarchSampling::hf_indices(), SurrBasedLocalMinimizer::initialize(), SurrBasedGlobalMinimizer::initialize_graphics(), SurrBasedLocalMinimizer::initialize_graphics(), NonDC3FunctionTrain::initialize_u_space_model(), NonDMultilevelFunctionTrain::initialize_u_space_model(), SurrogateModel::insert_response_start(), NonDMultilevControlVarSampling::multilevel_control_variate_mc_offline_pilot(), NonDMultilevControlVarSampling::multilevel_control_variate_mc_Qcorr(), NonDBayesCalibration::NonDBayesCalibration(), NonDLocalReliability::NonDLocalReliability(), NonDMultilevControlVarSampling::pre_run(), NonDEnsembleSampling::print_results(), SurrBasedMinimizer::print_results(), SurrogateModel::probability_transformation(), SurrogateModel::subordinate_model(), SurrBasedGlobalMinimizer::SurrBasedGlobalMinimizer(), SurrogateModel::trans_grad_U_to_X(), SurrogateModel::trans_grad_X_to_S(), SurrogateModel::trans_grad_X_to_U(), SurrogateModel::trans_hess_X_to_U(), SurrogateModel::trans_U_to_X(), SurrogateModel::trans_X_to_U(), and RecastModel::truth_model().
active_surrogate_model()
Model & active_surrogate_model (size_t i = _NPOS) virtual
return the i-th active approximation sub-model in surrogate models
return by reference requires use of dummy objects, but is important to allow use of assign_rep() since this operation must be performed on the original envelope object.
Reimplemented in RecastModel, and EnsembleSurrModel.
References Model::modelRep, and Model::surrogate_model().
Referenced by RecastModel::active_surrogate_model(), and NonDMultilevControlVarSampling::lf_perform_samples().
active_truth_model()
Model & active_truth_model () virtual
return the active truth sub-model in surrogate models
return by reference requires use of dummy objects, but is important to allow use of assign_rep() since this operation must be performed on the original envelope object.
Reimplemented in RecastModel, and EnsembleSurrModel.
References Model::modelRep, and Model::truth_model().
Referenced by RecastModel::active_truth_model(), SurrogateModel::check_rebuild(), and NonDMultilevelSampling::evaluate_ml_sample_increment().
update_from_subordinate_model()
void update_from_subordinate_model (size_t depth = SZ_MAX) virtual
propagate vars/labels/bounds/targets from the bottom up
used only for instantiate-on-the-fly model recursions (all RecastModel instantiations and alternate DataFitSurrModel instantiations). Simulation, Hierarchical, and Nested Models do not redefine the function since they do not support instantiate-on-the-fly. This means that the recursion will stop as soon as it encounters a Model that was instantiated normally, which is appropriate since ProblemDescDB-constructed Models use top-down information flow and do not require bottom-up updating.
Reimplemented in RecastModel, ProbabilityTransformModel, EnsembleSurrModel, DataTransformModel, and DataFitSurrModel.
References Model::modelRep.
Referenced by EffGlobalMinimizer::build_gp(), NonDGlobalInterval::core_run(), NonDLocalInterval::core_run(), NonDExpansion::initialize_expansion(), LeastSq::initialize_run(), Optimizer::initialize_run(), NonDExpansion::multilevel_regression(), NonDBayesCalibration::pre_run(), NonDGlobalReliability::pre_run(), NonDLocalReliability::pre_run(), DataFitSurrModel::update_from_subordinate_model(), DataTransformModel::update_from_subordinate_model(), EnsembleSurrModel::update_from_subordinate_model(), ProbabilityTransformModel::update_from_subordinate_model(), and RecastModel::update_from_subordinate_model().
derived_interface()
Interface & derived_interface () virtual
return the interface employed by the derived model class, if present: SimulationModel::userDefinedInterface, DataFitSurrModel::approxInterface, or NestedModel::optionalInterface
return by reference requires use of dummy objects, but is important to allow use of assign_rep() since this operation must be performed on the original envelope object.
Reimplemented in SimulationModel, RecastModel, NestedModel, and DataFitSurrModel.
References Dakota::dummy_interface, and Model::modelRep.
Referenced by SurrBasedGlobalMinimizer::core_run(), and RecastModel::derived_interface().
solution_levels()
size_t solution_levels (bool lwr_bnd = true) const virtual
number of discrete levels within solution control (SimulationModel)
return the number of levels within a solution / discretization hierarchy.
Reimplemented in SimulationModel.
References Model::modelRep.
Referenced by EnsembleSurrModel::assign_default_keys(), NonDMultilevelSampling::compute_error_estimates(), EnsembleSurrModel::create_tabular_datastream(), NonDMultilevControlVarSampling::evaluate_pilot(), EnsembleSurrModel::multifidelity(), EnsembleSurrModel::multilevel(), NonDMultilevControlVarSampling::multilevel_control_variate_mc_offline_pilot(), NonDMultilevControlVarSampling::multilevel_control_variate_mc_Qcorr(), EnsembleSurrModel::multilevel_multifidelity(), NonDMultilevControlVarSampling::pre_run(), EnsembleSurrModel::recursive_apply(), and RecastModel::solution_levels().
solution_level_cost_index()
void solution_level_cost_index (size_t index) virtual
activate a particular level within the solution level control (SimulationModel)
activate a particular level within a solution / discretization hierarchy.
Reimplemented in SimulationModel, and RecastModel.
References Dakota::abort_handler(), and Model::modelRep.
Referenced by EnsembleSurrModel::assign_default_keys(), EnsembleSurrModel::assign_surrogate_key(), EnsembleSurrModel::assign_truth_key(), NonDMultilevelSampling::configure_indices(), NonDNonHierarchSampling::hf_indices(), and RecastModel::solution_level_cost_index().
local_eval_synchronization()
short local_eval_synchronization () virtual
return derived model synchronization setting
SimulationModels and EnsembleSurrModels redefine this virtual function. A default value of "synchronous" prevents asynch local operations for:
NestedModels: a subIterator can support message passing parallelism, but not asynch local.
DataFitSurrModels: while asynch evals on approximations will work due to some added bookkeeping, avoiding them is preferable.
Reimplemented in SimulationModel, RecastModel, and NestedModel.
References Model::modelRep.
Referenced by Model::init_serial(), RecastModel::local_eval_synchronization(), and Model::set_ie_asynchronous_mode().
local_eval_concurrency()
int local_eval_concurrency () virtual
return derived model asynchronous evaluation concurrency
SimulationModels and EnsembleSurrModels redefine this virtual function.
Reimplemented in SimulationModel, RecastModel, and NestedModel.
References Model::modelRep.
Referenced by RecastModel::local_eval_concurrency(), and Model::set_ie_asynchronous_mode().
interface_id()
const String & interface_id () const virtual
return the interface identifier
return by reference requires use of dummy objects, but is important to allow use of assign_rep() since this operation must be performed on the original envelope object.
Reimplemented in SimulationModel, RecastModel, NestedModel, and DataFitSurrModel.
References Dakota::dummy_interface, Interface::interface_id(), and Model::modelRep.
Referenced by NonDDREAMBayesCalibration::archive_acceptance_chain(), Minimizer::archive_best_results(), DataTransformModel::archive_submodel_responses(), DataFitSurrModel::build_global(), NonDMUQBayesCalibration::cache_chain(), NonDQUESOBayesCalibration::cache_chain(), DataFitSurrModel::DataFitSurrModel(), Model::db_lookup(), Model::derived_auto_graphics(), EnsembleSurrModel::derived_auto_graphics(), Model::estimate_message_lengths(), NonDEnsembleSampling::export_all_samples(), NonDBayesCalibration::export_chain(), NonDBayesCalibration::export_discrepancy(), NonDBayesCalibration::export_field_discrepancy(), SurrBasedLocalMinimizer::find_approx_response(), SurrBasedLocalMinimizer::find_truth_response(), DataFitSurrModel::import_points(), RecastModel::interface_id(), Minimizer::local_recast_retrieve(), EnsembleSurrModel::matching_active_interface_ids(), EnsembleSurrModel::matching_all_interface_ids(), Analyzer::pre_output(), LeastSq::print_results(), Optimizer::print_results(), SurrBasedMinimizer::print_results(), SeqHybridMetaIterator::run_sequential(), DiscrepancyCorrection::search_db(), Analyzer::update_best(), ConcurrentMetaIterator::update_local_results(), SeqHybridMetaIterator::update_local_results(), and NonDLocalReliability::update_mpp_search_data().
evaluation_cache()
bool evaluation_cache (bool recurse_flag = true) const virtual
Indicates the usage of an evaluation cache by the Model.
Only Models including ApplicationInterfaces support an evaluation cache: surrogate, nested, and recast mappings are not stored in the cache. Possible exceptions: EnsembleSurrModel, NestedModel::optionalInterface.
Reimplemented in SimulationModel, RecastModel, EnsembleSurrModel, and DataFitSurrModel.
References Model::modelRep.
Referenced by DataFitSurrModel::DataFitSurrModel(), DataFitSurrModel::evaluation_cache(), EnsembleSurrModel::evaluation_cache(), RecastModel::evaluation_cache(), DataFitSurrModel::import_points(), and Analyzer::read_variables_responses().
restart_file()
bool restart_file (bool recurse_flag = true) const virtual
Indicates the usage of a restart file by the Model.
Only Models including ApplicationInterfaces interact with the restart file: surrogate, nested, and recast mappings are not stored in restart. Possible exceptions: DataFitSurrModel::import_points(), NestedModel::optionalInterface.
Reimplemented in SimulationModel, RecastModel, EnsembleSurrModel, and DataFitSurrModel.
References Model::modelRep.
Referenced by DataFitSurrModel::import_points(), Analyzer::read_variables_responses(), DataFitSurrModel::restart_file(), EnsembleSurrModel::restart_file(), and RecastModel::restart_file().
eval_tag_prefix()
void eval_tag_prefix (const String & eval_id_str) virtual
set the hierarchical eval ID tag prefix
Derived classes containing additional models or interfaces should implement this function to pass along to their sub Models/Interfaces.
Reimplemented in SimulationModel, and RecastModel.
References Model::evalTagPrefix, and Model::modelRep.
Referenced by EnsembleSurrModel::build_approximation(), DataFitSurrModel::derived_evaluate(), EnsembleSurrModel::derived_evaluate(), DataFitSurrModel::derived_evaluate_nowait(), EnsembleSurrModel::derived_evaluate_nowait(), Iterator::eval_tag_prefix(), and RecastModel::eval_tag_prefix().
subordinate_models()
ModelList & subordinate_models (bool recurse_flag = true)
return the sub-models in nested and surrogate models
since modelList is built with list insertions (using envelope copies), these models may not be used for model.assign_rep() since this operation must be performed on the original envelope object. They may, however, be used for letter-based operations (including assign_rep() on letter contents such as an interface).
References Model::derived_subordinate_models(), Model::modelList, and Model::modelRep.
Referenced by CONMINOptimizer::check_sub_iterator_conflict(), NCSUOptimizer::check_sub_iterator_conflict(), NonDLocalInterval::check_sub_iterator_conflict(), NonDLocalReliability::check_sub_iterator_conflict(), SOLBase::check_sub_iterator_conflict(), NonD::configure_sequence(), NonDMultilevControlVarSampling::core_run(), NonD::inflate_approx_samples(), NonD::inflate_sequence_samples(), Model::manage_data_recastings(), NonDEnsembleSampling::NonDEnsembleSampling(), NonD::print_multilevel_model_summary(), and NonD::query_cost().
init_communicators()
void init_communicators (ParLevLIter pl_iter, int max_eval_concurrency, bool recurse_flag = true)
allocate communicator partitions for a model and store configuration in modelPCIterMap
The init_communicators() and derived_init_communicators() functions are stuctured to avoid performing the messageLengths estimation more than once. init_communicators() (not virtual) performs the estimation and then forwards the results to derived_init_communicators (virtual) which uses the data in different contexts.
References ParallelLibrary::bcast(), Model::derived_init_communicators(), Model::estimate_message_lengths(), ParallelLibrary::increment_parallel_configuration(), Model::initCommsBcastFlag, Model::messageLengths, Model::modelPCIter, Model::modelPCIterMap, Model::modelRep, ParallelLibrary::parallel_configuration_iterator(), ParallelLibrary::parallel_level_index(), and Model::parallelLib.
Referenced by Iterator::derived_init_communicators(), NonDAdaptImpSampling::derived_init_communicators(), NonDAdaptiveSampling::derived_init_communicators(), NonDBayesCalibration::derived_init_communicators(), NonDExpansion::derived_init_communicators(), NonDGlobalInterval::derived_init_communicators(), NonDGlobalReliability::derived_init_communicators(), NonDGPImpSampling::derived_init_communicators(), NonDLocalInterval::derived_init_communicators(), NonDLocalReliability::derived_init_communicators(), NonDPolynomialChaos::derived_init_communicators(), SurrBasedMinimizer::derived_init_communicators(), ActiveSubspaceModel::derived_init_communicators(), AdaptedBasisModel::derived_init_communicators(), DataFitSurrModel::derived_init_communicators(), EnsembleSurrModel::derived_init_communicators(), RecastModel::derived_init_communicators(), DataFitSurrModel::derived_set_communicators(), and Model::serve_init_communicators().
init_serial()
void init_serial ()
for cases where init_communicators() will not be called, modify some default settings to behave properly in serial.
The init_serial() and derived_init_serial() functions are stuctured to separate base class (common) operations from derived class (specialized) operations.
References Model::asynchEvalFlag, Model::derived_init_serial(), Model::local_eval_synchronization(), and Model::modelRep.
Referenced by DataFitSurrModel::derived_init_serial(), EnsembleSurrModel::derived_init_serial(), NestedModel::derived_init_serial(), and RecastModel::derived_init_serial().
estimate_message_lengths()
void estimate_message_lengths ()
estimate messageLengths for a model
This functionality has been pulled out of init_communicators() and defined separately so that it may be used in those cases when messageLengths is needed but model.init_communicators() is not called, e.g., for the master processor in the self-scheduling of a concurrent iterator strategy.
References Response::active_set(), Response::active_set_derivative_vector(), Model::assign_max_strings(), Response::copy(), Variables::copy(), Model::currentResponse, Model::currentVariables, Variables::cv(), Variables::icv(), Model::interface_id(), Model::messageLengths, Model::modelRep, ParallelLibrary::mpirun_flag(), Model::mvDist, Model::numFns, Model::parallelLib, MPIPackBuffer::reset(), and MPIPackBuffer::size().
Referenced by Model::init_communicators(), RandomFieldModel::initialize_mapping(), RecastModel::initialize_mapping(), ConcurrentMetaIterator::pre_run(), Iterator::resize_communicators(), and SubspaceModel::serve_init_mapping().
manage_data_recastings()
bool manage_data_recastings ()
initialize modelList and recastFlags for data import/export
Constructor helper to manage model recastings for data import/export.
References Model::modelRep, Model::recastFlags, and Model::subordinate_models().
Referenced by DataFitSurrModel::DataFitSurrModel(), and Analyzer::read_variables_responses().
assign_rep()
void assign_rep (std::shared_ptr< Model > model_rep)
replaces existing letter with a new one
The assign_rep() function is used for publishing derived class letters to existing envelopes, as opposed to sharing representations among multiple envelopes (in particular, assign_rep is passed a letter object and operator= is passed an envelope object).
Use case assumes the incoming letter is instantiated on the fly and has no envelope. This case is modeled after get_model(): a letter is dynamically allocated and passed into assign_rep (its memory management is passed over to the envelope).
If the letter happens to be managed by another envelope, it will persist as long as the last envelope referencing it.
References Model::model_rep(), and Model::modelRep.
Referenced by ActiveSubspaceModel::build_surrogate(), NonDBayesCalibration::calibrate_to_hifi(), ActiveSubspaceModel::compute_cross_validation_metric(), NonDBayesCalibration::construct_map_model(), NonDBayesCalibration::construct_mcmc_model(), Minimizer::data_transform_model(), DataFitSurrModel::DataFitSurrModel(), ActiveSubspaceModel::get_sub_model(), SurrBasedLocalMinimizer::initialize_sub_model(), EffGlobalMinimizer::initialize_sub_problem(), NonDAdaptImpSampling::NonDAdaptImpSampling(), NonDAdaptiveSampling::NonDAdaptiveSampling(), NonDBayesCalibration::NonDBayesCalibration(), NonDC3FunctionTrain::NonDC3FunctionTrain(), NonDGlobalInterval::NonDGlobalInterval(), NonDGlobalReliability::NonDGlobalReliability(), NonDGPImpSampling::NonDGPImpSampling(), NonDLocalInterval::NonDLocalInterval(), NonDLocalReliability::NonDLocalReliability(), NonDMultilevelFunctionTrain::NonDMultilevelFunctionTrain(), NonDMultilevelPolynomialChaos::NonDMultilevelPolynomialChaos(), NonDMultilevelStochCollocation::NonDMultilevelStochCollocation(), NonDPolynomialChaos::NonDPolynomialChaos(), NonDStochCollocation::NonDStochCollocation(), Analyzer::recast_model_view(), Optimizer::reduce_model(), NonDPolynomialChaos::resize(), Minimizer::scale_model(), NonDBayesCalibration::scale_model(), LeastSq::weight_model(), and NonDBayesCalibration::weight_model().
num_linear_ineq_constraints()
size_t num_linear_ineq_constraints () const inline
reshape the linear/nonlinear constraint arrays
return the number of linear inequality constraints
References Model::modelRep, Constraints::num_linear_ineq_constraints(), and Model::userDefinedConstraints.
Referenced by CONMINOptimizer::allocate_constraints(), Dakota::apply_linear_constraints(), Dakota::apply_nonlinear_constraints(), CONMINOptimizer::core_run(), DataTransformModel::expand_linear_constraints(), Dakota::get_nonlinear_ineq_constraints(), JEGAOptimizer::Evaluator::GetNumberLinearConstraints(), ScalingModel::initialize_scaling(), COLINApplication::set_problem(), Minimizer::update_from_model(), RecastModel::update_linear_constraints(), and SurrogateModel::update_response_from_model().
derivative_concurrency()
int derivative_concurrency () const
return the gradient concurrency for use in parallel configuration logic
This function assumes derivatives with respect to the active continuous variables. Therefore, concurrency with respect to the inactive continuous variables is not captured.
References Dakota::contains(), Model::gradIdAnalytic, Model::gradientType, Model::hessianType, Model::hessIdNumerical, Model::intervalType, Model::methodSource, Model::modelRep, and Model::numDerivVars.
Referenced by ActiveSubspaceModel::ActiveSubspaceModel(), EnsembleSurrModel::derived_free_communicators(), DataFitSurrModel::derived_init_communicators(), EnsembleSurrModel::derived_init_communicators(), EnsembleSurrModel::derived_set_communicators(), DataFitSurrModel::estimate_partition_bounds(), NonDExpansion::initialize_u_space_grid(), Analyzer::num_samples(), and Iterator::update_from_model().
active_variables()
void active_variables (const RealVector & config_vars, Model & model) static
set the specified configuration to the Model's inactive vars, converting from real to integer or through index to string value as needed
config_vars consists of [continuous, integer, string, real].
References Model::continuous_variables(), Model::current_variables(), Model::cv(), Model::discrete_int_variables(), Model::discrete_real_variables(), Model::discrete_set_string_values(), Variables::discrete_string_variable(), Model::div(), Model::drv(), Model::dsv(), Dakota::iround(), and Dakota::set_index_to_value().
inactive_variables() [1/2]
void inactive_variables (const RealVector & config_vars, Model & model) static
set the specified configuration to the Model's inactive vars, converting from real to integer or through index to string value as needed
config_vars consists of [continuous, integer, string, real].
References Model::current_variables(), and Model::inactive_variables().
inactive_variables() [2/2]
void inactive_variables (const RealVector & config_vars, Model & model, Variables & vars) static
config_vars consists of [continuous, integer, string, real].
References Model::current_variables(), Model::discrete_set_string_values(), Model::icv(), Model::idiv(), Model::idrv(), Model::idsv(), Variables::inactive_continuous_variables(), Variables::inactive_discrete_int_variables(), Variables::inactive_discrete_real_variables(), Variables::inactive_discrete_string_variable(), Dakota::iround(), Dakota::set_index_to_value(), and Variables::view().
user_auto_id()
String user_auto_id () static protected
return the next available model ID for no-ID user methods
Rationale: The parser allows multiple user-specified models with empty (unspecified) ID. However, only a single Model with empty ID can be constructed (if it's the only one present, or the "last one parsed"). Therefore decided to prefer NO_MODEL_ID over NO_MODEL_ID_<num> for (some) consistency with interface NO_ID convention. MODEL was inserted in the middle to distinguish "anonymous" MODELS from methods and interfaces in the hdf5 output. Note that this function is not used to name recast models; see their constructors for how its done.
Referenced by Model::Model().
no_spec_id()
String no_spec_id () static protected
return the next available model ID for on-the-fly methods
Rationale: For now NOSPEC_MODEL_ID_ is chosen due to historical id="NO_SPECIFICATION" used for internally-constructed Models. Longer-term, consider auto-generating an ID that includes the context from which the method is constructed, e.g., the parent method or model's ID, together with its name. Note that this function is not used to name recast models; see their constructors for how its done.
References Model::noSpecIdNum.
initialize_distribution()
void initialize_distribution (Pecos::MultivariateDistribution & mv_dist, bool active_only = false) protected
initialize distribution types from problemDescDB
Build random variable distribution types and active subset. This function is used when the Model variables are in x-space.
References SharedVariablesData::active_subsets(), Dakota::assign_value(), Model::currentVariables, Variables::cv(), Variables::div(), Variables::drv(), Model::dsv(), Variables::dsv(), ProblemDescDB::get_rv(), ProblemDescDB::get_sizet(), Model::probDescDB, Variables::shared_data(), and Variables::tv().
Referenced by Model::Model().
initialize_active_types()
void initialize_active_types (Pecos::MultivariateDistribution & mv_dist) protected
initialize distribution types from problemDescDB
Build random variable distribution types and active subset. This function is used when the Model variables are in x-space.
References SharedVariablesData::active_to_all_mask(), Model::currentVariables, and Variables::shared_data().
Referenced by DataFitSurrModel::DataFitSurrModel(), RecastModel::init_distribution(), and ProbabilityTransformModel::initialize_transformation().
get_model()
std::shared_ptr< Model > get_model (ProblemDescDB & problem_db) private
Used by the envelope to instantiate the correct letter class.
Used only by the envelope constructor to initialize modelRep to the appropriate derived type, as given by the modelType attribute.
References ProblemDescDB::get_string(), and Model::model_type().
estimate_derivatives()
int estimate_derivatives (const ShortArray & map_asv, const ShortArray & fd_grad_asv, const ShortArray & fd_hess_asv, const ShortArray & quasi_hess_asv, const ActiveSet & original_set, const bool asynch_flag) private
evaluate numerical gradients using finite differences. This routine is selected with "method_source dakota" (the default method_source) in the numerical gradient specification.
Estimate derivatives by computing finite difference gradients, finite difference Hessians, and/or quasi-Newton Hessians. The total number of finite difference evaluations is returned for use by synchronize() to track response arrays, and it could be used to improve management of max_function_evaluations within the iterators.
! new logic
References Variables::all_continuous_variables(), Model::asynch_flag(), Model::centralHess, Variables::continuous_variables(), Model::currentResponse, Model::currentVariables, Model::db_lookup(), Model::dbCaptureList, Model::dbResponseList, Model::deltaList, ActiveSet::derivative_vector(), Model::derived_evaluate(), Model::derived_evaluate_nowait(), Model::fdHessByFnStepSize, Model::fdHessByGradStepSize, Model::fdHessStepType, Model::FDstep1(), Model::FDstep2(), Dakota::find_index(), Model::forward_grad_step(), Response::function_gradients(), Response::function_values(), Model::ignoreBounds, Variables::inactive_continuous_variables(), Model::initialize_h(), Model::initialize_x0_bounds(), Model::initialMapList, Model::intervalType, Model::numFns, Model::outputLevel, ActiveSet::request_vector(), Response::shared_data(), Model::shortStep, Response::update(), and Model::update_response().
Referenced by Model::evaluate(), and Model::evaluate_nowait().
synchronize_derivatives()
void synchronize_derivatives (const Variables & vars, const IntResponseMap & fd_responses, Response & new_response, const ShortArray & fd_grad_asv, const ShortArray & fd_hess_asv, const ShortArray & quasi_hess_asv, const ActiveSet & original_set) private
combine results from an array of finite difference response objects (fd_grad_responses) into a single response (new_response)
Merge an array of fd_responses into a single new_response. This function is used both by synchronous evaluate() for the case of asynchronous estimate_derivatives() and by synchronize() for the case where one or more evaluate_nowait() calls has employed asynchronous estimate_derivatives().
!
References Model::acv(), Variables::all_continuous_variable_ids(), Model::centralHess, Variables::continuous_variable_ids(), Model::currentResponse, Model::currentVariables, Model::cv(), Model::dbCaptureList, Model::dbResponseList, Model::deltaList, ActiveSet::derivative_vector(), Dakota::find_index(), Response::function_gradients(), Response::function_values(), Model::icv(), Variables::inactive_continuous_variable_ids(), Model::initialMapList, Model::intervalType, Model::numFns, Response::shared_data(), and Model::update_response().
Referenced by Model::evaluate(), and Model::synchronize().
update_response()
void update_response (const Variables & vars, Response & new_response, const ShortArray & fd_grad_asv, const ShortArray & fd_hess_asv, const ShortArray & quasi_hess_asv, const ActiveSet & original_set, Response & initial_map_response, const RealMatrix & new_fn_grads, const RealSymMatrixArray & new_fn_hessians) private
overlay results to update a response object
Overlay the initial_map_response with numerically estimated new_fn_grads and new_fn_hessians to populate new_response as governed by asv vectors. Quasi-Newton secant Hessian updates are also performed here, since this is where the gradient data needed for the updates is first consolidated. Convenience function used by estimate_derivatives() for the synchronous case and by synchronize_derivatives() for the asynchronous case.
References Response::active_set_request_vector(), Variables::continuous_variable_ids(), Response::copy(), Model::currentResponse, Model::currentVariables, ActiveSet::derivative_vector(), Response::function_gradients(), Response::function_hessians(), Response::function_values(), Model::hessianType, Model::hessIdQuasi, Response::is_null(), Model::numFns, Model::outputLevel, Model::quasiHessians, ActiveSet::request_vector(), Response::reset_inactive(), Model::supportsEstimDerivs, Model::surrogate_response_mode(), and Model::update_quasi_hessians().
Referenced by Model::estimate_derivatives(), and Model::synchronize_derivatives().
update_quasi_hessians()
void update_quasi_hessians (const Variables & vars, Response & new_response, const ActiveSet & original_set) private
perform quasi-Newton Hessian updates
quasi-Newton updates are performed for approximating response function Hessians using BFGS or SR1 formulations. These Hessians are supported only for the active continuous variables, and a check is performed on the DVV prior to invoking the function.
References Dakota::contains(), Variables::continuous_variables(), Dakota::copy_data(), Model::fnGradsPrev, Response::function_gradients(), Model::hessianType, Model::hessIdQuasi, Model::modelType, Model::numDerivVars, Model::numFns, Model::numQuasiUpdates, Model::outputLevel, Model::quasiHessians, Model::quasiHessType, ActiveSet::request_vector(), and Model::xPrev.
Referenced by Model::update_response().
manage_asv()
bool manage_asv (const ActiveSet & original_set, ShortArray & map_asv_out, ShortArray & fd_grad_asv_out, ShortArray & fd_hess_asv_out, ShortArray & quasi_hess_asv_out) private
Coordinates usage of estimate_derivatives() calls based on asv_in.
Splits asv_in total request into map_asv_out, fd_grad_asv_out, fd_hess_asv_out, and quasi_hess_asv_out as governed by the responses specification. If the returned use_est_deriv is true, then these asv outputs are used by estimate_derivatives() for the initial map, finite difference gradient evals, finite difference Hessian evals, and quasi-Hessian updates, respectively. If the returned use_est_deriv is false, then only map_asv_out is used.
References Dakota::abort_handler(), Dakota::contains(), ActiveSet::derivative_vector(), Model::FDstep2(), Dakota::find_index(), Model::forward_grad_step(), Model::gradIdAnalytic, Model::gradIdNumerical, Model::gradientType, Model::hessianType, Model::hessIdAnalytic, Model::hessIdNumerical, Model::hessIdQuasi, Model::ignoreBounds, Model::initialize_x0_bounds(), Model::intervalType, Model::methodSource, Model::model_id(), ActiveSet::request_vector(), Model::shortStep, Model::supportsEstimDerivs, and Model::surrogate_response_mode().
Referenced by Model::evaluate(), and Model::evaluate_nowait().
initialize_h()
Real initialize_h (Real x_j, Real lb_j, Real ub_j, Real step_size, String step_type) const private
function to determine initial finite difference h (before step length adjustment) based on type of step desired
Auxiliary function to determine initial finite difference h (before step length adjustment) based on type of step desired.
Referenced by Model::estimate_derivatives(), and Model::forward_grad_step().
FDstep1()
Real FDstep1 (Real x0_j, Real lb_j, Real ub_j, Real h_mag) private
function returning finite-difference step size (affected by bounds)
Auxiliary function to compute forward or first central-difference step size, honoring bounds. The first step is away from zero, when possible. Flips the direction or updates shortStep if can't take the full requested step h_mag.
References Model::ignoreBounds, and Model::shortStep.
Referenced by Model::estimate_derivatives(), and Model::forward_grad_step().
FDstep2()
Real FDstep2 (Real x0_j, Real lb_j, Real ub_j, Real h) private
function returning second central-difference step size (affected by bounds)
Auxiliary function to compute the second central-difference step size, honoring bounds.
References Model::ignoreBounds, and Model::shortStep.
Referenced by Model::estimate_derivatives(), and Model::manage_asv().
Member Data Documentation
fdGradStepSize
RealVector fdGradStepSize protected
relative finite difference step size for numerical gradients
A scalar value (instead of the vector fd_gradient_step_size spec) is used within the iterator hierarchy since this attribute is only used to publish a step size to vendor numerical gradient algorithms.
Referenced by DataFitSurrModel::DataFitSurrModel(), Model::fd_gradient_step_size(), Model::forward_grad_step(), RecastModel::initialize_data_from_submodel(), and Model::Model().
fdHessByGradStepSize
RealVector fdHessByGradStepSize protected
relative finite difference step size for numerical Hessians estimated using first-order differences of gradients
For vendor numerical Hessian algorithms, a scalar value is used.
Referenced by DataFitSurrModel::DataFitSurrModel(), Model::estimate_derivatives(), Model::fd_hessian_by_grad_step_size(), RecastModel::initialize_data_from_submodel(), and Model::Model().
fdHessByFnStepSize
RealVector fdHessByFnStepSize protected
relative finite difference step size for numerical Hessians estimated using second-order differences of function values
For vendor numerical Hessian algorithms, a scalar value is used.
Referenced by DataFitSurrModel::DataFitSurrModel(), Model::estimate_derivatives(), Model::fd_hessian_by_fn_step_size(), RecastModel::initialize_data_from_submodel(), and Model::Model().
probDescDB
ProblemDescDB& probDescDB protected
class member reference to the problem description database
Iterator and Model cannot use a shallow copy of ProblemDescDB due to circular destruction dependency (reference counts can't get to 0), since ProblemDescDB contains {iterator,model}List.
Referenced by ActiveSubspaceModel::ActiveSubspaceModel(), DataFitSurrModel::derived_init_communicators(), EnsembleSurrModel::derived_init_communicators(), NestedModel::derived_init_communicators(), NestedModel::derived_init_serial(), DataFitSurrModel::estimate_partition_bounds(), EnsembleSurrModel::estimate_partition_bounds(), NestedModel::estimate_partition_bounds(), SimulationModel::estimate_partition_bounds(), NestedModel::init_sub_iterator(), Model::initialize_distribution(), Model::initialize_distribution_parameters(), Model::Model(), Model::problem_description_db(), and SimulationModel::SimulationModel().
The documentation for this class was generated from the following files:
DakotaModel.hpp
DakotaModel.cpp