Dakota: NonDBayesCalibration Class Reference
NonDBayesCalibration Class Reference abstract
Base class for Bayesian inference: generates posterior distribution on model parameters given experimental data.
Public Member Functions
NonDBayesCalibration (ProblemDescDB &problem_db, Model &model)
standard constructor
~NonDBayesCalibration ()
destructor
template<typename VectorType >
Real prior_density (const VectorType &vec)
compute the prior PDF for a particular MCMC sample
template<typename VectorType >
Real log_prior_density (const VectorType &vec)
compute the log prior PDF for a particular MCMC sample
template<typename Engine >
void prior_sample (Engine &rng, RealVector &prior_samples)
draw a multivariate sample from the prior distribution
template<typename VectorType >
void prior_mean (VectorType &mean_vec) const
return the mean of the prior distribution
template<typename MatrixType >
void prior_variance (MatrixType &var_mat) const
return the covariance of the prior distribution
template<>
Real prior_density (const RealVector &vec)
template<>
Real log_prior_density (const RealVector &vec)
Public Member Functions inherited from NonDCalibration
NonDCalibration (ProblemDescDB &problem_db, Model &model)
standard constructor
~NonDCalibration ()
destructor
bool resize ()
reinitializes iterator based on new variable size
Public Member Functions inherited from NonD
void requested_levels (const RealVectorArray &req_resp_levels, const RealVectorArray &req_prob_levels, const RealVectorArray &req_rel_levels, const RealVectorArray &req_gen_rel_levels, short resp_lev_tgt, short resp_lev_tgt_reduce, bool cdf_flag, bool pdf_output)
set requestedRespLevels, requestedProbLevels, requestedRelLevels, requestedGenRelLevels, respLevelTarget, cdfFlag, and pdfOutput (used in combination with alternate ctors)
void print_level_mappings (std::ostream &s) const
prints the z/p/beta/beta* mappings reflected in {requested,computed}{Resp,Prob,Rel,GenRel}Levels for default qoi_type and qoi_labels
void print_level_mappings (std::ostream &s, String qoi_type, const StringArray &qoi_labels) const
prints the z/p/beta/beta* mappings reflected in {requested,computed}{Resp,Prob,Rel,GenRel}Levels
void print_level_mappings (std::ostream &s, const RealVector &level_maps, bool moment_offset, const String &prepend="")
print level mapping statistics using optional pre-pend
bool pdf_output () const
get pdfOutput
void pdf_output (bool output)
set pdfOutput
short final_moments_type () const
get finalMomentsType
void final_moments_type (short type)
set finalMomentsType
Public Member Functions inherited from Analyzer
const VariablesArray & all_variables ()
return the complete set of evaluated variables
const RealMatrix & all_samples ()
return the complete set of evaluated samples
const IntResponseMap & all_responses () const
return the complete set of computed responses
size_t num_samples () const
virtual void vary_pattern (bool pattern_flag)
sets varyPattern in derived classes that support it
Public Member Functions inherited from Iterator
Iterator (std::shared_ptr< TraitsBase > traits=std::shared_ptr< TraitsBase >(new TraitsBase()))
default constructor
Iterator (ProblemDescDB &problem_db, std::shared_ptr< TraitsBase > traits=std::shared_ptr< TraitsBase >(new TraitsBase()))
standard envelope constructor, which constructs its own model(s)
Iterator (ProblemDescDB &problem_db, Model &model, std::shared_ptr< TraitsBase > traits=std::shared_ptr< TraitsBase >(new TraitsBase()))
alternate envelope constructor which uses the ProblemDescDB but accepts a model from a higher level (meta-iterator) context, instead of constructing its own
Iterator (const String &method_string, Model &model, std::shared_ptr< TraitsBase > traits=std::shared_ptr< TraitsBase >(new TraitsBase()))
alternate envelope constructor for instantiations by name without the ProblemDescDB
Iterator (const Iterator &iterator)
copy constructor
virtual ~Iterator ()
destructor
Iterator operator= (const Iterator &iterator)
assignment operator
virtual void post_input ()
read tabular data for post-run mode
virtual void reset ()
restore initial state for repeated sub-iterator executions
virtual void nested_variable_mappings (const SizetArray &c_index1, const SizetArray &di_index1, const SizetArray &ds_index1, const SizetArray &dr_index1, const ShortArray &c_target2, const ShortArray &di_target2, const ShortArray &ds_target2, const ShortArray &dr_target2)
set primaryA{CV,DIV,DRV}MapIndices, secondaryA{CV,DIV,DRV}MapTargets within derived Iterators; supports computation of higher-level sensitivities in nested contexts (e.g., derivatives of statistics w.r.t. inserted design variables)
virtual void nested_response_mappings (const RealMatrix &primary_coeffs, const RealMatrix &secondary_coeffs)
set primaryResponseCoefficients, secondaryResponseCoefficients within derived Iterators; Necessary for scalarization case in MLMC NonDMultilevelSampling to map scalarization in nested context
virtual void initialize_iterator (int job_index)
used by IteratorScheduler to set the starting data for a run
virtual void pack_parameters_buffer (MPIPackBuffer &send_buffer, int job_index)
used by IteratorScheduler to pack starting data for an iterator run
virtual void unpack_parameters_buffer (MPIUnpackBuffer &recv_buffer, int job_index)
used by IteratorScheduler to unpack starting data for an iterator run
virtual void unpack_parameters_initialize (MPIUnpackBuffer &recv_buffer, int job_index)
used by IteratorScheduler to unpack starting data and initialize an iterator run
virtual void pack_results_buffer (MPIPackBuffer &send_buffer, int job_index)
used by IteratorScheduler to pack results data from an iterator run
virtual void unpack_results_buffer (MPIUnpackBuffer &recv_buffer, int job_index)
used by IteratorScheduler to unpack results data from an iterator run
virtual void update_local_results (int job_index)
used by IteratorScheduler to update local results arrays
virtual const RealSymMatrix & response_error_estimates () const
return error estimates associated with the final iterator solution
virtual bool accepts_multiple_points () const
indicates if this iterator accepts multiple initial points. Default return is false. Override to return true if appropriate.
virtual void initial_point (const Variables &pt)
sets the initial point for this iterator (user-functions mode for which Model updating is not used)
virtual void initial_point (const RealVector &pt)
sets the initial point (active continuous variables) for this iterator (user-functions mode for which Model updating is not used)
virtual void initial_points (const VariablesArray &pts)
sets the multiple initial points for this iterator. This should only be used if accepts_multiple_points() returns true.
virtual void variable_bounds (const RealVector &cv_lower_bnds, const RealVector &cv_upper_bnds)
assign nonlinear inequality and equality constraint allowables for this iterator (user-functions mode for which Model updating is not used)
virtual void linear_constraints (const RealMatrix &lin_ineq_coeffs, const RealVector &lin_ineq_lb, const RealVector &lin_ineq_ub, const RealMatrix &lin_eq_coeffs, const RealVector &lin_eq_tgt)
assign linear inequality and linear equality constraints for this iterator (user-functions mode for which Model updating is not used)
virtual void nonlinear_constraints (const RealVector &nln_ineq_lb, const RealVector &nln_ineq_ub, const RealVector &nln_eq_tgt)
assign nonlinear inequality and equality constraint allowables for this iterator (user-functions mode for which Model updating is not used)
virtual void initialize_graphics (int iterator_server_id=1)
initialize the 2D graphics window and the tabular graphics data
virtual void check_sub_iterator_conflict ()
detect any conflicts due to recursive use of the same Fortran solver
virtual unsigned short uses_method () const
return name of any enabling iterator used by this iterator
virtual void method_recourse ()
perform a method switch, if possible, due to a detected conflict
virtual void sampling_reset (size_t min_samples, bool all_data_flag, bool stats_flag)
reset sampling iterator to use at least min_samples
virtual void sampling_reference (size_t samples_ref)
set reference number of samples, which is a lower bound during reset
virtual void sampling_increment ()
increment to next in sequence of refinement samples
virtual void random_seed (int seed)
set randomSeed, if present
virtual unsigned short sampling_scheme () const
return sampling name
virtual IntIntPair estimate_partition_bounds ()
estimate the minimum and maximum partition sizes that can be utilized by this Iterator
virtual void declare_sources ()
Declare sources to the evaluations database.
void init_communicators (ParLevLIter pl_iter)
initialize the communicators associated with this Iterator instance
void set_communicators (ParLevLIter pl_iter)
set the communicators associated with this Iterator instance
void free_communicators (ParLevLIter pl_iter)
free the communicators associated with this Iterator instance
void resize_communicators (ParLevLIter pl_iter, bool reinit_comms)
Resize the communicators. This is called from the letter's resize()
void parallel_configuration_iterator (ParConfigLIter pc_iter)
set methodPCIter
ParConfigLIter parallel_configuration_iterator () const
return methodPCIter
void parallel_configuration_iterator_map (std::map< size_t, ParConfigLIter > pci_map)
set methodPCIterMap
std::map< size_t, ParConfigLIter > parallel_configuration_iterator_map () const
return methodPCIterMap
void run (ParLevLIter pl_iter)
invoke set_communicators(pl_iter) prior to run()
void run ()
orchestrate initialize/pre/core/post/finalize phases
void assign_rep (std::shared_ptr< Iterator > iterator_rep)
replaces existing letter with a new one
void iterated_model (const Model &model)
set the iteratedModel (iterators and meta-iterators using a single model instance)
Model & iterated_model ()
return the iteratedModel (iterators & meta-iterators using a single model instance)
ProblemDescDB & problem_description_db () const
return the problem description database (probDescDB)
ParallelLibrary & parallel_library () const
return the parallel library (parallelLib)
void method_name (unsigned short m_name)
set the method name to an enumeration value
unsigned short method_name () const
return the method name via its native enumeration value
void method_string (const String &m_str)
set the method name by string
String method_string () const
return the method name by string
String method_enum_to_string (unsigned short method_enum) const
convert a method name enumeration value to a string
unsigned short method_string_to_enum (const String &method_str) const
convert a method name string to an enumeration value
String submethod_enum_to_string (unsigned short submethod_enum) const
convert a sub-method name enumeration value to a string
const String & method_id () const
return the method identifier (methodId)
int maximum_evaluation_concurrency () const
return the maximum evaluation concurrency supported by the iterator
void maximum_evaluation_concurrency (int max_conc)
set the maximum evaluation concurrency supported by the iterator
size_t maximum_iterations () const
return the maximum iterations for this iterator
void maximum_iterations (size_t max_iter)
set the maximum iterations for this iterator
void convergence_tolerance (Real conv_tol)
set the method convergence tolerance (convergenceTol)
Real convergence_tolerance () const
return the method convergence tolerance (convergenceTol)
void output_level (short out_lev)
set the method output level (outputLevel)
short output_level () const
return the method output level (outputLevel)
void summary_output (bool summary_output_flag)
Set summary output control; true enables evaluation/results summary.
size_t num_final_solutions () const
return the number of solutions to retain in best variables/response arrays
void num_final_solutions (size_t num_final)
set the number of solutions to retain in best variables/response arrays
void active_set (const ActiveSet &set)
set the default active set (for use with iterators that employ evaluate_parameter_sets())
const ActiveSet & active_set () const
return the default active set (used by iterators that employ evaluate_parameter_sets())
void active_set_request_vector (const ShortArray &asv)
return the default active set request vector (used by iterators that employ evaluate_parameter_sets())
const ShortArray & active_set_request_vector () const
return the default active set request vector (used by iterators that employ evaluate_parameter_sets())
void active_set_request_values (short asv_val)
return the default active set request vector (used by iterators that employ evaluate_parameter_sets())
void sub_iterator_flag (bool si_flag)
set subIteratorFlag (and update summaryOutputFlag if needed)
bool is_null () const
function to check iteratorRep (does this envelope contain a letter?)
std::shared_ptr< Iterator > iterator_rep () const
returns iteratorRep for access to derived class member functions that are not mapped to the top Iterator level
virtual void eval_tag_prefix (const String &eval_id_str)
set the hierarchical eval ID tag prefix
std::shared_ptr< TraitsBase > traits () const
returns methodTraits for access to derived class member functions that are not mapped to the top TraitsBase level
bool top_level ()
Return whether the iterator is the top level iterator.
void top_level (bool tflag)
Set the iterator's top level flag.
Static Public Member Functions
static void get_positive_definite_covariance_from_hessian (const RealSymMatrix &hessian, const RealMatrix &prior_chol_fact, RealSymMatrix &covariance, short output_lev)
Compute the proposal covariance C based on low-rank approximation to the prior-preconditioned misfit Hessian.
static Real knn_kl_div (RealMatrix &distX_samples, RealMatrix &distY_samples, size_t dim)
static Real knn_mutual_info (RealMatrix &Xmatrix, int dimX, int dimY, unsigned short alg)
Protected Member Functions
void pre_run ()
pre-run portion of run (optional); re-implemented by Iterators which can generate all Variables (parameter sets) a priori
void core_run ()
core portion of run; implemented by all derived classes and may include pre/post steps in lieu of separate pre/post
void derived_init_communicators (ParLevLIter pl_iter)
derived class contributions to initializing the communicators associated with this Iterator instance
void derived_set_communicators (ParLevLIter pl_iter)
derived class contributions to setting the communicators associated with this Iterator instance
void derived_free_communicators (ParLevLIter pl_iter)
derived class contributions to freeing the communicators associated with this Iterator instance
virtual void print_results (std::ostream &s, short results_state=FINAL_RESULTS)
print the final iterator results
void print_variables (std::ostream &s, const RealVector &c_vars)
convenience function to print calibration parameters, e.g., for MAP / best parameters
const Model & algorithm_space_model () const
virtual void specify_prior ()
Methods for instantiating a Bayesian inverse problem. No-ops in the base class that can be specialized by child classes.
virtual void specify_likelihood ()
virtual void init_bayesian_solver ()
virtual void specify_posterior ()
virtual void calibrate ()=0
Perform Bayesian calibration (all derived classes must implement)
void construct_mcmc_model ()
construct mcmcModel (no emulation, GP, PCE, or SC) that wraps inbound Model
void init_hyper_parameters ()
initialize the hyper-parameter priors
void init_map_optimizer ()
initialize the MAP optimizer selection
void construct_map_model ()
construct the negative log posterior RecastModel (negLogPostModel)
void construct_map_optimizer ()
construct the MAP optimizer for minimization of negLogPostModel
virtual void map_pre_solve ()
void initialize_model ()
initialize emulator model and probability space transformations
void calibrate_with_adaptive_emulator ()
Run calibration, looping to refine emulator around posterior mode.
virtual void filter_chain_by_conditioning ()
Filter mcmc chain for PCE adaptive emulator. extract batchSize points from the MCMC chain and store final aggregated set within allSamples; unique points with best conditioning are selected, as determined by pivoted LU.
void best_to_all ()
copy bestSamples to allSamples to use in surrogate update
void update_model ()
evaluates allSamples on iteratedModel and update the mcmcModel emulator with all{Samples,Responses}
Real assess_emulator_convergence ()
compute the L2 norm of the change in emulator coefficients
void calibrate_to_hifi ()
calibrate the model to a high-fidelity data source, using mutual information-guided design of experiments (adaptive experimental design)
void eval_hi2lo_stop (bool &stop_metric, double &prev_MI, const RealVector &MI_vec, int num_hifi, int max_hifi, int num_candidates)
evaluate stopping criteria for calibrate_to_hifi
void print_hi2lo_file (std::ostream &out_file, int num_it, const VariablesArray &optimal_config_matrix, const RealVector &MI_vec, RealMatrix &resp_matrix)
print calibrate_to_hifi progress to file
void print_hi2lo_begin (int num_it)
print calibrate_to_hifi progress
void print_hi2lo_status (int num_it, int i, const Variables &xi_i, double MI)
void print_hi2lo_batch_status (int num_it, int batch_n, int batchEvals, const Variables &optimal_config, double max_MI)
void print_hi2lo_selected (int num_it, const VariablesArray &optimal_config_matrix, const RealVector &MI_vec)
void print_hi2lo_chain_moments ()
void add_lhs_hifi_data ()
supplement high-fidelity data with LHS samples
void choose_batch_from_mutual_info (int random_seed, int num_it, int max_hifi, int num_hifi, RealMatrix &mi_chain, VariablesArray &design_matrix, VariablesArray &optimal_config_matrix, RealVector &MI_vec)
calculate the optimal points to add for a given batch
void apply_hifi_sim_error (int &random_seed, int num_exp, int exp_offset=0)
apply simulation error vector
void apply_error_vec (const RealVector &error_vec, int &seed, int experiment)
void build_error_matrix (const RealVector &sim_error_vec, RealMatrix &sim_error_matrix, int &seed)
build matrix of errors
void build_designs (VariablesArray &design_matrix)
build matrix of candidate points
void build_hi2lo_xmatrix (RealMatrix &Xmatrix, int i, const RealMatrix &mi_chain, RealMatrix &sim_error_matrix)
build matrix to calculate mutual information for calibrate_to_hifi
void run_hifi (const VariablesArray &optimal_config_matrix, RealMatrix &resp_matrix)
run high-fidelity model at several configs and add to experiment data
void build_model_discrepancy ()
calculate model discrepancy with respect to experimental data
void build_scalar_discrepancy ()
void build_field_discrepancy ()
void build_GP_field (const RealMatrix &t, RealMatrix &t_pred, const RealVector &concat_disc, RealVector &disc_pred, RealVector &disc_var)
void calculate_kde ()
calculate a Kernel Density Estimate (KDE) for the posterior samples
void calculate_evidence ()
calculate the model evidence
void extract_selected_posterior_samples (const std::vector< int > &points_to_keep, const RealMatrix &samples_for_posterior_eval, const RealVector &posterior_density, RealMatrix &posterior_data) const
void export_posterior_samples_to_file (const std::string filename, const RealMatrix &posterior_data) const
template<typename VectorType1 , typename VectorType2 >
void augment_gradient_with_log_prior (VectorType1 &log_grad, const VectorType2 &vec)
compute the (approximate) gradient of the negative log posterior by augmenting the (approximate) gradient of the negative log likelihood with the gradient of the negative log prior
template<typename MatrixType , typename VectorType >
void augment_hessian_with_log_prior (MatrixType &log_hess, const VectorType &vec)
compute the (approximate) Hessian of the negative log posterior by augmenting the (approximate) Hessian of the negative log likelihood with the Hessian of the negative log prior
Real log_likelihood (const RealVector &residuals, const RealVector &hyper_params)
calculate log-likelihood from the passed residuals (assuming they are already sized and scaled by covariance / hyperparams...
void prior_cholesky_factorization ()
compute priorCovCholFactor based on prior distributions for random variables and any hyperparameters
void get_positive_definite_covariance_from_hessian (const RealSymMatrix &hessian, RealSymMatrix &covariance)
member version forwards member data to static function
void scale_model ()
Wrap iteratedModel in a RecastModel that performs response scaling.
void weight_model ()
Wrap iteratedModel in a RecastModel that weights the residuals.
void export_discrepancy (RealMatrix &pred_config_mat)
print tabular files containing model+discrepancy responses and variances
void export_field_discrepancy (RealMatrix &pred_vars_mat)
print tabular files containing model+discrepancy responses and variances for field responses
virtual void compute_statistics ()
Compute final stats for MCMC chains.
void export_chain ()
export the acceptance chain in user space
void export_chain (RealMatrix &filtered_chain, RealMatrix &filtered_fn_vals)
Print filtered posterior and function values (later: credibility and prediction intervals)
void filter_chain (const RealMatrix &acceptance_chain, RealMatrix &filtered_chain, int target_length)
Perform chain filtering based on target chain length.
void filter_chain (const RealMatrix &acceptance_chain, RealMatrix &filtered_chain)
Perform chain filtering with burn-in and sub-sampling.
void filter_fnvals (const RealMatrix &accepted_fn_vals, RealMatrix &filtered_fn_vals)
void filter_matrix_cols (const RealMatrix &orig_matrix, int start_index, int stride, RealMatrix &filtered_matrix)
return a newly allocated filtered matrix including start_index and every stride-th index after; for burn-in cases, start_index is the number of burn-in discards
void compute_intervals ()
void compute_prediction_vals (RealMatrix &filtered_fn_vals, RealMatrix &PredVals, int num_filtered, size_t num_exp, size_t num_concatenated)
void print_intervals_file (std::ostream &stream, RealMatrix &functionvalsT, RealMatrix &predvalsT, int length, size_t aug_length)
void print_intervals_screen (std::ostream &stream, RealMatrix &functionvalsT, RealMatrix &predvalsT, int length)
void kl_post_prior (RealMatrix &acceptanceChain)
Compute information metrics.
void prior_sample_matrix (RealMatrix &prior_dist_samples)
void mutual_info_buildX ()
void print_kl (std::ostream &stream)
void print_chain_diagnostics (std::ostream &s)
void print_batch_means_intervals (std::ostream &s)
Protected Member Functions inherited from NonD
NonD (ProblemDescDB &problem_db, Model &model)
constructor
NonD (unsigned short method_name, Model &model)
alternate constructor for sample generation and evaluation "on the fly"
NonD (unsigned short method_name, Model &model, const ShortShortPair &approx_view)
alternate constructor for sample generation and evaluation "on the fly"
NonD (unsigned short method_name, const RealVector &lower_bnds, const RealVector &upper_bnds)
alternate constructor for sample generation "on the fly"
~NonD ()
destructor
void initialize_run ()
utility function to perform common operations prior to pre_run(); typically memory initialization; setting of instance pointers
void finalize_run ()
utility function to perform common operations following post_run(); deallocation and resetting of instance pointers
const Response & response_results () const
return the final statistics from the nondeterministic iteration
void response_results_active_set (const ActiveSet &set)
set the active set within finalStatistics
virtual void initialize_response_covariance ()
initializes respCovariance
virtual void initialize_final_statistics ()
initializes finalStatistics for storing NonD final results
virtual void update_final_statistics ()
update finalStatistics::functionValues
virtual bool discrepancy_sample_counts () const
flag identifying whether sample counts correspond to level discrepancies
void pull_level_mappings (RealVector &level_maps, size_t offset)
concatenate computed{Resp,Prob,Rel,GenRel}Levels into level_maps
void push_level_mappings (const RealVector &level_maps, size_t offset)
update computed{Resp,Prob,Rel,GenRel}Levels from level_maps
void configure_sequence (size_t &num_steps, size_t &secondary_index, short &seq_type)
configure fidelity/level counts from model hierarchy
void configure_cost (unsigned short num_steps, bool multilevel, RealVector &cost)
extract cost estimates from model hierarchy (forms or resolutions)
bool query_cost (unsigned short num_steps, bool multilevel, RealVector &cost)
extract cost estimates from model hierarchy, if available
bool query_cost (unsigned short num_steps, Model &model, RealVector &cost)
extract cost estimates from model hierarchy, if available
bool valid_cost_values (const RealVector &cost)
test cost for valid values > 0
void load_pilot_sample (const SizetArray &pilot_spec, size_t num_steps, SizetArray &delta_N_l)
distribute pilot sample specification across model forms or levels
void load_pilot_sample (const SizetArray &pilot_spec, short seq_type, const Sizet3DArray &N_l, Sizet2DArray &delta_N_l)
distribute pilot sample specification across model forms and levels
template<typename ArrayType >
void inflate_approx_samples (const ArrayType &N_l, bool multilev, size_t secondary_index, std::vector< ArrayType > &N_l_vec)
update the relevant slice of N_l_3D from the final 2D multilevel or 2D multifidelity sample profile
template<typename ArrayType >
void inflate_sequence_samples (const ArrayType &N_l, bool multilev, size_t secondary_index, std::vector< ArrayType > &N_l_vec)
update the relevant slice of N_l_3D from the final 2D multilevel or 2D multifidelity sample profile
void resize_final_statistics_gradients ()
resizes finalStatistics::functionGradients based on finalStatistics ASV
void update_aleatory_final_statistics ()
update finalStatistics::functionValues from momentStats and computed{Prob,Rel,GenRel,Resp}Levels
void update_system_final_statistics ()
update system metrics from component metrics within finalStatistics
void update_system_final_statistics_gradients ()
update finalStatistics::functionGradients
void initialize_level_mappings ()
size computed{Resp,Prob,Rel,GenRel}Levels
void compute_densities (const RealRealPairArray &min_max_fns, bool prob_refinement=false, bool all_levels_computed=false)
compute the PDF bins from the CDF/CCDF values and store in computedPDF{Abscissas,Ordinates}
void print_densities (std::ostream &s) const
output the PDFs reflected in computedPDF{Abscissas,Ordinates} using default qoi_type and pdf_labels
void print_densities (std::ostream &s, String qoi_type, const StringArray &pdf_labels) const
output the PDFs reflected in computedPDF{Abscissas,Ordinates}
void print_system_mappings (std::ostream &s) const
print system series/parallel mappings for response levels
void print_multilevel_evaluation_summary (std::ostream &s, const SizetArray &N_m)
print evaluation summary for multilevel sampling across 1D level profile
void print_multilevel_evaluation_summary (std::ostream &s, const Sizet2DArray &N_m)
print evaluation summary for multilevel sampling across 2D level+QoI profile
void print_multilevel_discrepancy_summary (std::ostream &s, const SizetArray &N_m)
print evaluation summary for multilevel sampling across 1D level profile for discrepancy across levels
void print_multilevel_discrepancy_summary (std::ostream &s, const SizetArray &N_m, const SizetArray &N_mp1)
print evaluation summary for multilevel sampling across 1D level profile for discrepancy across model forms
void print_multilevel_discrepancy_summary (std::ostream &s, const Sizet2DArray &N_m)
print evaluation summary for multilevel sampling across 2D level+QoI profile for discrepancy across levels
void print_multilevel_discrepancy_summary (std::ostream &s, const Sizet2DArray &N_m, const Sizet2DArray &N_mp1)
print evaluation summary for multilevel sampling across 2D level+QoI profile for discrepancy across model forms
template<typename ArrayType >
void print_multilevel_model_summary (std::ostream &s, const std::vector< ArrayType > &N_samp, String type, short seq_type, bool discrep_flag)
print evaluation summary for multilevel sampling across 2D model+level profile (allocations) or 3D model+level+QoI profile (actual)
void construct_lhs (Iterator &u_space_sampler, Model &u_model, unsigned short sample_type, int num_samples, int seed, const String &rng, bool vary_pattern, short sampling_vars_mode=ACTIVE)
assign a NonDLHSSampling instance within u_space_sampler
unsigned short sub_optimizer_select (unsigned short requested_sub_method, unsigned short default_sub_method=SUBMETHOD_NPSOL)
utility for vetting sub-method request against optimizers within the package configuration
size_t one_sided_delta (Real current, Real target)
compute a one-sided sample increment for multilevel methods to move current sampling level to a new target
size_t one_sided_delta (const SizetArray &current, const RealVector &targets, size_t power)
compute a one-sided sample increment for multilevel methods to move current sampling level to a new target
size_t one_sided_delta (const SizetArray &current, Real target, size_t power)
compute a one-sided sample increment for multilevel methods to move current sampling level to a new target
bool differ (size_t N_alloc_ij, const SizetArray &N_actual_ij) const
return true if fine-grained reporting differs from coarse-grained
bool differ (const SizetArray &N_alloc_i, const Sizet2DArray &N_actual_i) const
return true if fine-grained reporting differs from coarse-grained
bool differ (const Sizet2DArray &N_alloc, const Sizet3DArray &N_actual) const
return true if fine-grained reporting differs from coarse-grained
void archive_allocate_mappings ()
allocate results array storage for distribution mappings
void archive_from_resp (size_t fn_index, size_t inc_id=0)
archive the mappings from specified response levels for specified fn
void archive_to_resp (size_t fn_index, size_t inc_id=0)
archive the mappings to computed response levels for specified fn and (optional) increment id.
void archive_allocate_pdf ()
allocate results array storage for pdf histograms
void archive_pdf (size_t fn_index, size_t inc_id=0)
archive a single pdf histogram for specified function
void archive_equiv_hf_evals (const Real equiv_hf_evals)
archive the equivalent number of HF evals (used by ML/MF methods)
Protected Member Functions inherited from Analyzer
Analyzer ()
default constructor
Analyzer (ProblemDescDB &problem_db, Model &model)
standard constructor
Analyzer (unsigned short method_name, Model &model)
alternate constructor for instantiations "on the fly" with a Model
Analyzer (unsigned short method_name, Model &model, const ShortShortPair &view_override)
alternate constructor for instantiations "on the fly" with a Model
Analyzer (unsigned short method_name)
alternate constructor for instantiations "on the fly" without a Model
~Analyzer ()
destructor
virtual void get_parameter_sets (Model &model)
Generate one block of numSamples samples (ndim * num_samples), populating allSamples; ParamStudy is the only class that specializes to use allVariables.
virtual void get_parameter_sets (Model &model, const size_t num_samples, RealMatrix &design_matrix)
Generate one block of numSamples samples (ndim * num_samples), populating design_matrix.
virtual void update_model_from_sample (Model &model, const Real *sample_vars)
update model's current variables with data from sample
virtual void update_model_from_variables (Model &model, const Variables &vars)
update model's current variables with data from vars
virtual void sample_to_variables (const Real *sample_vars, Variables &vars)
convert column of samples array to variables; derived classes may reimplement for more than active continuous variables
void update_from_model (const Model &model)
set inherited data attributes based on extractions from incoming model
void post_run (std::ostream &s)
post-run portion of run (optional); verbose to print results; re-implemented by Iterators that can read all Variables/Responses and perform final analysis phase in a standalone way
void pre_output ()
const Variables & variables_results () const
return a single final iterator solution (variables)
const VariablesArray & variables_array_results ()
return multiple final iterator solutions (variables). This should only be used if returns_multiple_points() returns true.
const ResponseArray & response_array_results ()
return multiple final iterator solutions (response). This should only be used if returns_multiple_points() returns true.
bool compact_mode () const
returns Analyzer::compactMode
bool returns_multiple_points () const
indicates if this iterator returns multiple final points. Default return is false. Override to return true if appropriate.
void evaluate_parameter_sets (Model &model, bool log_resp_flag, bool log_best_flag)
perform function evaluations to map parameter sets (allVariables) into response sets (allResponses)
void get_vbd_parameter_sets (Model &model, size_t num_samples)
generate replicate parameter sets for use in variance-based decomposition
void compute_vbd_stats (const size_t num_samples, const IntResponseMap &resp_samples)
compute VBD-based Sobol indices
void archive_sobol_indices () const
archive VBD-based Sobol indices
virtual void archive_model_variables (const Model &, size_t idx) const
archive model evaluation points
virtual void archive_model_response (const Response &, size_t idx) const
archive model evaluation responses
void read_variables_responses (int num_evals, size_t num_vars)
convenience function for reading variables/responses (used in derived classes post_input)
void print_sobol_indices (std::ostream &s) const
Printing of VBD results.
void samples_to_variables_array (const RealMatrix &sample_matrix, VariablesArray &vars_array)
convert samples array to variables array; e.g., allSamples to allVariables
virtual void variables_to_sample (const Variables &vars, Real *sample_c_vars)
convert the active continuous variables into a column of allSamples
void variables_array_to_samples (const VariablesArray &vars_array, RealMatrix &sample_matrix)
convert variables array to samples array; e.g., allVariables to allSamples
Protected Member Functions inherited from Iterator
Iterator (BaseConstructor, ProblemDescDB &problem_db, std::shared_ptr< TraitsBase > traits=std::shared_ptr< TraitsBase >(new TraitsBase()))
constructor initializes the base class part of letter classes (BaseConstructor overloading avoids infinite recursion in the derived class constructors - Coplien, p. 139)
Iterator (NoDBBaseConstructor, unsigned short method_name, Model &model, std::shared_ptr< TraitsBase > traits=std::shared_ptr< TraitsBase >(new TraitsBase()))
alternate constructor for base iterator classes constructed on the fly
Iterator (NoDBBaseConstructor, unsigned short method_name, std::shared_ptr< TraitsBase > traits=std::shared_ptr< TraitsBase >(new TraitsBase()))
alternate constructor for base iterator classes constructed on the fly
Iterator (NoDBBaseConstructor, Model &model, size_t max_iter, size_t max_eval, Real conv_tol, std::shared_ptr< TraitsBase > traits=std::shared_ptr< TraitsBase >(new TraitsBase()))
alternate envelope constructor for instantiations without ProblemDescDB
virtual const VariablesArray & initial_points () const
gets the multiple initial points for this iterator. This will only be meaningful after a call to initial_points mutator.
StrStrSizet run_identifier () const
get the unique run identifier based on method name, id, and number of executions
void initialize_model_graphics (Model &model, int iterator_server_id)
helper function that encapsulates initialization operations, modular on incoming Model instance
void export_final_surrogates (Model &data_fit_surr_model)
export final surrogates generated, e.g., GP in EGO and friends
Static Protected Member Functions
static void neg_log_post_resp_mapping (const Variables &model_vars, const Variables &nlpost_vars, const Response &model_resp, Response &nlpost_resp)
static function passed by pointer to negLogPostModel recast model
static void ann_dist (const ANNpointArray matrix1, const ANNpointArray matrix2, RealVector &distances, int NX, int NY, int dim2, IntVector &k, double eps)
static void ann_dist (const ANNpointArray matrix1, const ANNpointArray matrix2, RealVector &distances, Int2DArray &indices, int NX, int NY, int dim2, IntVector &k, double eps)
Static Protected Member Functions inherited from Iterator
static void gnewton_set_recast (const Variables &recast_vars, const ActiveSet &recast_set, ActiveSet &sub_model_set)
conversion of request vector values for the Gauss-Newton Hessian approximation
Protected Attributes
String scalarDataFilename
short emulatorType
the emulator type: NO_EMULATOR, GP_EMULATOR, PCE_EMULATOR, SC_EMULATOR, ML_PCE_EMULATOR, MF_PCE_EMULATOR, or MF_SC_EMULATOR
RealVectorArray prevCoeffs
cache previous expansion coefficients for assessing convergence of emulator refinement process
Model mcmcModel
Model instance employed in the likelihood function; provides response function values from Gaussian processes, stochastic expansions (PCE/SC), or direct access to simulations (no surrogate option)
bool mcmcModelHasSurrogate
whether the MCMC Model is a surrogate, or a thin transformation around a surrogate, so can be cheaply re-evaluated in chain recovery
Model residualModel
DataTransformModel wrapping the mcmcModel.
Iterator mapOptimizer
SQP or NIP optimizer for pre-solving for the MAP point prior to MCMC. This is restricted to emulator cases for now, but as for derivative preconditioning, could be activated for no-emulator cases with a specification option (not active by default).
Model negLogPostModel
RecastModel for solving for MAP: reduces residualModel to scalar negative log posterior.
unsigned short mapOptAlgOverride
user setting of the MAP optimization algorithm type
Iterator stochExpIterator
NonDPolynomialChaos or NonDStochCollocation instance for defining a PCE/SC-based mcmcModel.
int chainSamples
number of samples in the chain (e.g. number of MCMC samples); for iterative update cycles, number of samples per update cycle
int randomSeed
random seed for MCMC process
unsigned int batchSize
number of points to add to surrogate at each iteration of calibrate_with_adaptive_emulator
short mcmcDerivOrder
order of derivatives used in MCMC process (bitwise like ASV)
RealVector mapSoln
solution for most recent MAP pre-solve; also serves as initial guess for initializing the first solve and warm-starting the next solve (posterior emulator refinement)
bool adaptExpDesign
whether to perform iterative design of experiments with high-fidelity model
size_t numCandidates
number of candidate designs for adaptive Bayesian experimental design
String importCandPtsFile
whether to import candidate design points for adaptive Bayesian experimental design
unsigned short importCandFormat
tabular format for the candidate design points import file
int maxHifiEvals
maximum number of high-fidelity model runs to be used for adaptive Bayesian experimental design
int batchEvals
number of optimal designs selected per iteration of experimental design algorithm
unsigned short mutualInfoAlg
algorithm to employ in calculating mutual information
bool readFieldCoords
need field coordinates for model discrepancy
bool calModelDiscrepancy
flag whether to calculate model discrepancy
String discrepancyType
set discrepancy type
String exportCorrModelFile
filename for corrected model (model+discrepancy) calculations output
String exportDiscrepFile
filename for discrepancy calculations output
String exportCorrVarFile
filename for corrected model variance calculations
unsigned short exportCorrModelFormat
format options for corrected model output
unsigned short exportDiscrepFormat
format options for discrepancy output
unsigned short exportCorrVarFormat
format options for corrected model variance output
short discrepPolyOrder
specify polynomial or trend order for discrepancy correction
size_t numPredConfigs
number of prediction configurations at which to calculate model discrepancy
RealVector configLowerBnds
lower bounds on configuration domain
RealVector configUpperBnds
upper bounds on configuration domain
ResponseArray discrepancyResponses
array containing predicted of model+discrepancy
ResponseArray correctedResponses
array containing predicted of model+discrepancy
RealMatrix correctedVariances
matrix containing variances of model+discrepancy
RealVector predictionConfigList
list of prediction configurations at which to calculate model discrepancy
String importPredConfigs
whether to import prediction configurations at which to calculate model discrepancy
unsigned short importPredConfigFormat
tabular format for prediction configurations import file
RealVector discrepancyFieldResponses
array containing predicted of model+discrepancy
RealVector correctedFieldResponses
array containing predicted of model+discrepancy
RealVector correctedFieldVariances
matrix containing variances of model+discrepancy
Model hifiModel
a high-fidelity model data source (given by pointer in input)
int initHifiSamples
initial high-fidelity model samples
Iterator hifiSampler
LHS iterator to generate hi-fi model data.
RealMatrix priorCovCholFactor
the Cholesky factor of the prior covariance
unsigned short obsErrorMultiplierMode
mode for number of observation error multipliers to calibrate (default none)
int numHyperparams
calculated number of hyperparameters augmenting the calibration parameter set, e.g., due to calibrate observation error multipliers
RealVector invGammaAlphas
alphas for inverse gamma distribution on hyper-params
RealVector invGammaBetas
alphas for inverse gamma distribution on hyper-params
std::vector< Pecos::RandomVariable > invGammaDists
distributions for hyper-params
bool standardizedSpace
flag indicating use of a variable transformation to standardized probability space for the model or emulator
bool posteriorStatsKL
flag indicating the calculation of KL divergence between prior and posterior
bool posteriorStatsMutual
flag indicating the calculation of mutual information between prior and posterior
bool posteriorStatsKDE
flag indicating the calculation of the kernel density estimate of the posteriors
bool chainDiagnostics
flag indicating calculation of chain diagnostics
bool chainDiagnosticsCI
flag indicating calculation of confidence intervals as a chain diagnositc
bool calModelEvidence
flag indicating calculation of the evidence of the model
bool calModelEvidMC
flag indicating use of Monte Carlo approximation to calculate evidence
bool calModelEvidLaplace
flag indicating use of Laplace approximation to calculate evidence
int evidenceSamples
number of samples to be used in model evidence calculation
bool adaptPosteriorRefine
flag indicating usage of adaptive posterior refinement; currently makes sense for unstructured grids in GP and PCE least squares/CS
String proposalCovarType
approach for defining proposal covariance
RealVector proposalCovarData
data from user input of proposal covariance
String proposalCovarFilename
filename for user-specified proposal covariance
String proposalCovarInputType
approach for defining proposal covariance
RealMatrix acceptanceChain
Post-processing-related controls.
RealMatrix acceptedFnVals
cached function values corresponding to acceptanceChain for final statistics reporting
std::map< Real, RealVector > bestSamples
container for managing best MCMC samples (points and associated log posterior) collected across multiple (restarted) chains
int burnInSamples
number of MCMC samples to discard from acceptance chain
int subSamplingPeriod
period or skip in post-processing the acceptance chain
RealMatrix chainStats
RealMatrix fnStats
RealMatrix predVals
Compute credibility and prediction intervals of final chain.
RealMatrix filteredFnVals
cached filtered function values for printing (may be a view of acceptedFnVals)
String exportMCMCFilename
output filename for the MCMC chain
short exportMCMCFormat
output formatting options for MCMC export
short filteredMCMCFormat
Real kl_est
bool scaleFlag
whether response scaling is active
bool weightFlag
whether weight scaling is active
Protected Attributes inherited from NonDCalibration
bool calibrationData
flag indicating whether there is calibration data present
ExperimentData expData
Container for experimental data to which to calibrate model.
Protected Attributes inherited from NonD
NonD * prevNondInstance
pointer containing previous value of nondInstance
size_t startCAUV
starting index of continuous aleatory uncertain variables within active continuous variables (convenience for managing offsets)
size_t numCAUV
number of active continuous aleatory uncertain variables
bool epistemicStats
flag for computing interval-type metrics instead of integrated metrics If any epistemic vars are active in a metric evaluation, then flag is set.
RealMatrix momentStats
standardized or central resp moments, as determined by finalMomentsType. Calculated in compute_moments()) and indexed as (moment,fn).
RealVectorArray requestedRespLevels
requested response levels for all response functions
RealVectorArray computedProbLevels
output probability levels for all response functions resulting from requestedRespLevels
RealVectorArray computedRelLevels
output reliability levels for all response functions resulting from requestedRespLevels
RealVectorArray computedGenRelLevels
output generalized reliability levels for all response functions resulting from requestedRespLevels
short respLevelTarget
indicates mapping of z->p (PROBABILITIES), z->beta (RELIABILITIES), or z->beta* (GEN_RELIABILITIES)
short respLevelTargetReduce
indicates component or system series/parallel failure metrics
RealVectorArray requestedProbLevels
requested probability levels for all response functions
RealVectorArray requestedRelLevels
requested reliability levels for all response functions
RealVectorArray requestedGenRelLevels
requested generalized reliability levels for all response functions
RealVectorArray computedRespLevels
output response levels for all response functions resulting from requestedProbLevels, requestedRelLevels, or requestedGenRelLevels
size_t totalLevelRequests
total number of levels specified within requestedRespLevels, requestedProbLevels, and requestedRelLevels
bool cdfFlag
flag for type of probabilities/reliabilities used in mappings: cumulative/CDF (true) or complementary/CCDF (false)
bool pdfOutput
flag for managing output of response probability density functions (PDFs)
RealVectorArray computedPDFAbscissas
sorted response PDF intervals bounds extracted from min/max sample and requested/computedRespLevels (vector lengths = num bins + 1)
RealVectorArray computedPDFOrdinates
response PDF densities computed from bin counts divided by (unequal) bin widths (vector lengths = num bins)
Response finalStatistics
final statistics from the uncertainty propagation used in strategies: response means, standard deviations, and probabilities of failure
short finalMomentsType
type of moments logged within finalStatistics: none, central, standard
size_t miPLIndex
index for the active ParallelLevel within ParallelConfiguration::miPLIters
BitArray pdfComputed
Whether PDF was computed for function i; used to determine whether a pdf should be archived.
Protected Attributes inherited from Analyzer
size_t numFunctions
number of response functions
size_t numContinuousVars
number of active continuous vars
size_t numDiscreteIntVars
number of active discrete integer vars
size_t numDiscreteStringVars
number of active discrete string vars
size_t numDiscreteRealVars
number of active discrete real vars
bool compactMode
switch for allSamples (compact mode) instead of allVariables (normal mode)
VariablesArray allVariables
array of all variables to be evaluated in evaluate_parameter_sets()
RealMatrix allSamples
compact alternative to allVariables
IntResponseMap allResponses
array of all responses to be computed in evaluate_parameter_sets()
StringArray allHeaders
array of headers to insert into output while evaluating allVariables
size_t numObjFns
number of objective functions
size_t numLSqTerms
number of least squares terms
RealPairPRPMultiMap bestVarsRespMap
map which stores best set of solutions
Protected Attributes inherited from Iterator
ProblemDescDB & probDescDB
class member reference to the problem description database
ParallelLibrary & parallelLib
class member reference to the parallel library
ParConfigLIter methodPCIter
the active ParallelConfiguration used by this Iterator instance
Model iteratedModel
the model to be iterated (for iterators and meta-iterators employing a single model instance)
size_t myModelLayers
number of Models locally (in Iterator or derived classes) wrapped around the initially passed in Model
unsigned short methodName
name of the iterator (the user's method spec)
Real convergenceTol
iteration convergence tolerance
size_t maxIterations
maximum number of iterations for the method
size_t maxFunctionEvals
maximum number of fn evaluations for the method
int maxEvalConcurrency
maximum number of concurrent model evaluations
ActiveSet activeSet
the response data requirements on each function evaluation
size_t numFinalSolutions
number of solutions to retain in best variables/response arrays
VariablesArray bestVariablesArray
collection of N best solution variables found during the study; always in context of Model originally passed to the Iterator (any in-flight Recasts must be undone)
ResponseArray bestResponseArray
collection of N best solution responses found during the study; always in context of Model originally passed to the Iterator (any in-flight Recasts must be undone)
bool subIteratorFlag
flag indicating if this Iterator is a sub-iterator (NestedModel::subIterator or DataFitSurrModel::daceIterator)
short outputLevel
output verbosity level: {SILENT,QUIET,NORMAL,VERBOSE,DEBUG}_OUTPUT
bool summaryOutputFlag
flag for summary output (evaluation stats, final results); default true, but false for on-the-fly (helper) iterators and sub-iterator use cases
ResultsManager & resultsDB
reference to the global iterator results database
EvaluationStore & evaluationsDB
reference to the global evaluation database
EvaluationsDBState evaluationsDBState
State of evaluations DB for this iterator.
ResultsNames resultsNames
valid names for iterator results
std::shared_ptr< TraitsBase > methodTraits
pointer that retains shared ownership of a TraitsBase object, or child thereof
bool topLevel
Whether this is the top level iterator.
bool exportSurrogate = false
whether to export final surrogates
String surrExportPrefix
base filename for exported surrogates
unsigned short surrExportFormat = NO_MODEL_FORMAT
(bitwise) format(s) to export
Static Protected Attributes
static NonDBayesCalibration * nonDBayesInstance
Pointer to current class instance for use in static callback functions.
Static Protected Attributes inherited from NonD
static NonD * nondInstance
pointer to the active object instance used within static evaluator functions in order to avoid the need for static data
Detailed Description
Base class for Bayesian inference: generates posterior distribution on model parameters given experimental data.
This class will eventually provide a general-purpose framework for Bayesian inference. In the short term, it only collects shared code between QUESO and GPMSA implementations.
Constructor & Destructor Documentation
NonDBayesCalibration()
NonDBayesCalibration (ProblemDescDB & problem_db, Model & model)
standard constructor
This constructor is called for a standard letter-envelope iterator instantiation. In this case, set_db_list_nodes has been called and probDescDB can be queried for settings from the method specification.
References Dakota::abort_handler(), NonDBayesCalibration::adaptExpDesign, NonDBayesCalibration::adaptPosteriorRefine, Model::all_continuous_variables(), Iterator::assign_rep(), Model::assign_rep(), NonDBayesCalibration::batchSize, NonDBayesCalibration::burnInSamples, NonDCalibration::calibrationData, NonDBayesCalibration::chainSamples, NonDBayesCalibration::construct_map_model(), NonDBayesCalibration::construct_mcmc_model(), Model::continuous_lower_bound(), Model::continuous_upper_bound(), Dakota::copy_data_partial(), Model::current_variables(), Variables::cv(), Variables::cv_start(), NonDBayesCalibration::emulatorType, NonDCalibration::expData, Dakota::generate_system_seed(), ProblemDescDB::get_bool(), NonDBayesCalibration::hifiModel, NonDBayesCalibration::hifiSampler, NonDBayesCalibration::init_hyper_parameters(), NonDBayesCalibration::init_map_optimizer(), NonDBayesCalibration::initHifiSamples, NonDBayesCalibration::invGammaDists, Iterator::iteratedModel, NonDBayesCalibration::mapSoln, Iterator::maxEvalConcurrency, Iterator::maxIterations, NonDBayesCalibration::mcmcDerivOrder, NonDBayesCalibration::mcmcModel, Model::model_type(), Model::multivariate_distribution(), ExperimentData::num_experiments(), Analyzer::numContinuousVars, NonDBayesCalibration::numHyperparams, NonDBayesCalibration::obsErrorMultiplierMode, Iterator::probDescDB, NonDBayesCalibration::randomSeed, NonDBayesCalibration::residualModel, NonDBayesCalibration::scale_model(), NonDBayesCalibration::scaleFlag, NonDBayesCalibration::standardizedSpace, NonDBayesCalibration::subSamplingPeriod, Dakota::SZ_MAX, Model::truth_model(), Analyzer::vary_pattern(), Variables::view(), NonDBayesCalibration::weight_model(), and NonDBayesCalibration::weightFlag.
Member Function Documentation
prior_mean()
void prior_mean (VectorType & mean_vec) const
return the mean of the prior distribution
Assume the target mean_vec is sized by client
References NonDBayesCalibration::invGammaDists, Iterator::iteratedModel, Model::multivariate_distribution(), Analyzer::numContinuousVars, NonDBayesCalibration::numHyperparams, NonDBayesCalibration::residualModel, and NonDBayesCalibration::standardizedSpace.
prior_variance()
void prior_variance (MatrixType & var_mat) const
return the covariance of the prior distribution
Assumes the target var_mat is sized by client
References NonDBayesCalibration::invGammaDists, Iterator::iteratedModel, Model::multivariate_distribution(), Analyzer::numContinuousVars, NonDBayesCalibration::numHyperparams, NonDBayesCalibration::residualModel, and NonDBayesCalibration::standardizedSpace.
pre_run()
void pre_run () protected virtual
pre-run portion of run (optional); re-implemented by Iterators which can generate all Variables (parameter sets) a priori
pre-run phase, which a derived iterator may optionally reimplement; when not present, pre-run is likely integrated into the derived run function. This is a virtual function; when re-implementing, a derived class must call its nearest parent's pre_run(), if implemented, typically before performing its own implementation steps.
Reimplemented from Analyzer.
References NonDBayesCalibration::construct_map_optimizer(), Model::is_null(), NonDBayesCalibration::negLogPostModel, Analyzer::pre_run(), NonDBayesCalibration::residualModel, and Model::update_from_subordinate_model().
core_run()
void core_run () protected virtual
core portion of run; implemented by all derived classes and may include pre/post steps in lieu of separate pre/post
Virtual run function for the iterator class hierarchy. All derived classes need to redefine it.
Reimplemented from Iterator.
References NonDBayesCalibration::adaptExpDesign, NonDBayesCalibration::adaptPosteriorRefine, NonDBayesCalibration::build_model_discrepancy(), NonDBayesCalibration::calibrate(), NonDBayesCalibration::calibrate_to_hifi(), NonDBayesCalibration::calibrate_with_adaptive_emulator(), NonDBayesCalibration::calModelDiscrepancy, NonDBayesCalibration::compute_statistics(), NonDBayesCalibration::initialize_model(), NonDBayesCalibration::nonDBayesInstance, and NonDBayesCalibration::specify_prior().
print_results()
void print_results (std::ostream & s, short results_state = FINAL_RESULTS) protected virtual
print the final iterator results
This virtual function provides additional iterator-specific final results outputs beyond the function evaluation summary printed in finalize_run().
Reimplemented from Analyzer.
Reimplemented in NonDWASABIBayesCalibration, NonDQUESOBayesCalibration, NonDMUQBayesCalibration, and NonDGPMSABayesCalibration.
References NonDBayesCalibration::chainDiagnostics, Model::continuous_variable_labels(), Dakota::copy_data(), Model::current_response(), NonDBayesCalibration::filteredFnVals, Response::function_labels(), Dakota::length(), NonDBayesCalibration::mcmcModel, Iterator::outputLevel, NonDBayesCalibration::posteriorStatsKL, NonDBayesCalibration::predVals, NonDSampling::print_moments(), NonD::requestedProbLevels, and NonDBayesCalibration::residualModel.
Referenced by NonDGPMSABayesCalibration::print_results(), NonDMUQBayesCalibration::print_results(), and NonDQUESOBayesCalibration::print_results().
algorithm_space_model()
const Model & algorithm_space_model () const inline protected virtual
default definition that gets redefined in selected derived Minimizers
Reimplemented from Analyzer.
References NonDBayesCalibration::residualModel.
init_map_optimizer()
void init_map_optimizer () protected
initialize the MAP optimizer selection
Construct optimizer for MAP pre-solve Emulator: on by default; can be overridden with "pre_solve none" No emulator: off by default; can be activated with "pre_solve {sqp,nip}" relies on mapOptimizer ctor to enforce min derivative support Calculation of model evidence using Laplace approximation: this requires a MAP solve.
References Dakota::abort_handler(), NonDBayesCalibration::calModelEvidLaplace, NonDBayesCalibration::emulatorType, and NonDBayesCalibration::mapOptAlgOverride.
Referenced by NonDBayesCalibration::NonDBayesCalibration().
map_pre_solve()
void map_pre_solve () protected virtual
Runs a pre-solve for the MAP point. If running calibrate_to_hifi() or calibrate_with_adaptive_emulator(), propagates the solution to the mapSoln variable. Returns the optimal solution as a vector.
References Variables::continuous_variables(), Dakota::copy_data(), Model::current_variables(), Iterator::is_null(), NonDBayesCalibration::mapOptimizer, NonDBayesCalibration::mapSoln, NonDBayesCalibration::negLogPostModel, NonDBayesCalibration::print_variables(), Iterator::run(), and Iterator::variables_results().
calibrate_with_adaptive_emulator()
void calibrate_with_adaptive_emulator () protected
Run calibration, looping to refine emulator around posterior mode.
This method will perform a Bayesian calibration with an emulator, but periodically the emulator is updated with more sample points from the original model in the high-posterior-density region of parameter space.
References Dakota::abort_handler(), NonDBayesCalibration::assess_emulator_convergence(), NonDBayesCalibration::best_to_all(), NonDBayesCalibration::calibrate(), Analyzer::compactMode, Iterator::convergenceTol, NonDBayesCalibration::emulatorType, NonDBayesCalibration::filter_chain_by_conditioning(), Iterator::maxIterations, and NonDBayesCalibration::update_model().
Referenced by NonDBayesCalibration::core_run().
build_designs()
void build_designs (VariablesArray & design_matrix) protected
build matrix of candidate points
On entry, design_matrix already sized to numCandidates.
References Iterator::all_variables(), Iterator::assign_rep(), NonDBayesCalibration::hifiModel, NonDBayesCalibration::importCandFormat, NonDBayesCalibration::importCandPtsFile, NonDBayesCalibration::numCandidates, Iterator::outputLevel, Iterator::pre_run(), NonDBayesCalibration::randomSeed, and Analyzer::vary_pattern().
Referenced by NonDBayesCalibration::calibrate_to_hifi().
log_likelihood()
Real log_likelihood (const RealVector & residuals, const RealVector & all_params) protected
calculate log-likelihood from the passed residuals (assuming they are already sized and scaled by covariance / hyperparams...
Calculate the log-likelihood, accounting for contributions from covariance and hyperparameters, as well as constant term:
log(L) = -1/2*Nr*log(2*pi) - 1/2*log(det(Cov)) - 1/2*r'(Cov^{-1})*r
The passed residuals must already be size-adjusted, differenced with any data, if present, and scaled by covariance^{-1/2}.
References NonDCalibration::expData, Dakota::HALF_LOG_2PI, ExperimentData::half_log_cov_determinant(), Analyzer::numContinuousVars, NonDBayesCalibration::numHyperparams, and NonDBayesCalibration::obsErrorMultiplierMode.
Referenced by NonDBayesCalibration::calculate_evidence(), NonDQUESOBayesCalibration::dakotaLogLikelihood(), NonDBayesCalibration::neg_log_post_resp_mapping(), and NonDDREAMBayesCalibration::sample_likelihood().
neg_log_post_resp_mapping()
void neg_log_post_resp_mapping (const Variables & residual_vars, const Variables & nlpost_vars, const Response & residual_resp, Response & nlpost_resp) static protected
static function passed by pointer to negLogPostModel recast model
Response mapping callback used by RecastModel for MAP pre-solve. Computes
-log(post) = -log(like) - log(prior); where -log(like) = 1/2*Nr*log(2*pi) + 1/2*log(det(Cov)) + 1/2*r'(Cov^{-1})*r = 1/2*Nr*log(2*pi) + 1/2*log(det(Cov)) + misfit
(misfit defined as 1/2 r^T (mult^2*Gamma_d)^{-1} r) The passed residual_resp has been differenced, interpolated, and covariance-scaled
References Response::active_set_request_vector(), NonDBayesCalibration::augment_gradient_with_log_prior(), NonDBayesCalibration::augment_hessian_with_log_prior(), ExperimentData::build_gradient_of_sum_square_residuals(), ExperimentData::build_hessian_of_sum_square_residuals(), Variables::continuous_variables(), NonDCalibration::expData, Response::function_gradient_view(), Response::function_hessian_view(), Response::function_value(), Response::function_values(), ExperimentData::half_log_cov_det_gradient(), ExperimentData::half_log_cov_det_hessian(), NonDBayesCalibration::log_likelihood(), NonDBayesCalibration::log_prior_density(), NonDBayesCalibration::nonDBayesInstance, Analyzer::numContinuousVars, NonDBayesCalibration::numHyperparams, NonDBayesCalibration::obsErrorMultiplierMode, and Iterator::outputLevel.
Referenced by NonDBayesCalibration::calculate_evidence(), and NonDBayesCalibration::construct_map_model().
scale_model()
void scale_model () protected
Wrap iteratedModel in a RecastModel that performs response scaling.
Wrap the residualModel in a scaling transformation, such that residualModel now contains a scaling recast model.
References Model::assign_rep(), Iterator::outputLevel, and NonDBayesCalibration::residualModel.
Referenced by NonDBayesCalibration::NonDBayesCalibration().
weight_model()
void weight_model () protected
Wrap iteratedModel in a RecastModel that weights the residuals.
Setup Recast for weighting model. The weighting transformation doesn't resize, and makes no vars, active set or secondary mapping. All indices are one-to-one mapped (no change in counts).
References Dakota::abort_handler(), Model::assign_rep(), Iterator::outputLevel, Model::primary_response_fn_weights(), and NonDBayesCalibration::residualModel.
Referenced by NonDBayesCalibration::NonDBayesCalibration().
export_chain()
void export_chain (RealMatrix & filtered_chain, RealMatrix & filtered_fn_vals) protected
Print filtered posterior and function values (later: credibility and prediction intervals)
Print tabular file with filtered chain, function values, and pred values
References Variables::continuous_variables(), Variables::copy(), Model::current_response(), Model::current_variables(), NonDBayesCalibration::exportMCMCFilename, NonDBayesCalibration::exportMCMCFormat, Response::function_labels(), Model::interface_id(), NonDBayesCalibration::mcmcModel, Analyzer::numFunctions, NonDBayesCalibration::residualModel, Dakota::write_precision, and Variables::write_tabular().
Member Data Documentation
acceptanceChain
RealMatrix acceptanceChain protected
Post-processing-related controls.
accumulation of acceptance chain across restarts (stored in user-space) TO DO: retire once restarts are retired; optimize to convert to user-space only in final results
Referenced by NonDDREAMBayesCalibration::archive_acceptance_chain(), NonDGPMSABayesCalibration::cache_acceptance_chain(), NonDMUQBayesCalibration::cache_chain(), NonDQUESOBayesCalibration::cache_chain(), NonDDREAMBayesCalibration::cache_chain(), NonDBayesCalibration::calculate_kde(), NonDBayesCalibration::calibrate_to_hifi(), NonDBayesCalibration::compute_statistics(), and NonDBayesCalibration::kl_post_prior().
The documentation for this class was generated from the following files:
NonDBayesCalibration.hpp
NonDBayesCalibration.cpp