Dakota: Surrogate Class Reference
Surrogate Class Reference abstract
Parent class for surrogate models.
Public Member Functions
Surrogate ()
Constructor that uses defaultConfigOptions and does not build.
Surrogate (const ParameterList &param_list)
Constructor that sets configOptions but does not build.
Surrogate (const MatrixXd &samples, const MatrixXd &response, const ParameterList &param_list)
Constructor for the Surrogate that sets configOptions and builds the surrogate (does nothing in the base class).
virtual ~Surrogate ()
Default destructor.
virtual void build (const MatrixXd &samples, const MatrixXd &response)=0
Build the Surrogate using specified build data.
virtual VectorXd value (const MatrixXd &eval_points)
Evaluate the Surrogate at a set of prediction points for a scalar QoI.
virtual VectorXd values (const MatrixXd &eval_points)
Evaluate the Surrogate at a set of prediction points for field QoIs.
virtual MatrixXd gradient (const MatrixXd &eval_points)
Evaluate the gradient of the scalar Surrogate at a set of prediction points.
MatrixXd gradients (const MatrixXd &eval_points)
Evaluate the gradient of the field Surrogate at a set of prediction points.
virtual MatrixXd hessian (const MatrixXd &eval_point)
Evaluate the Hessian of the scalar Surrogate at a set of prediction points.
virtual MatrixXd hessians (const MatrixXd &eval_point)
Evaluate the Hessian of the field Surrogate at a set of prediction points.
void variable_labels (const std::vector< std::string > &var_labels)
Set the variable/feature names.
const std::vector< std::string > & variable_labels () const
Get the (possibly empty) variable/feature names.
void response_labels (const std::vector< std::string > &resp_labels)
Set the response/QoI names.
const std::vector< std::string > & response_labels () const
Get the (possibly empty) response/QoI names.
void set_options (const ParameterList &options)
Set the Surrogate's configOptions.
void get_options (ParameterList &options)
Get the Surrogate's configOptions.
void print_options ()
Print the Surrogate's configOptions.
virtual void default_options ()=0
Initialize the Surrogate's defaultConfigOptions.
virtual bool diagnostics_available ()
VectorXd evaluate_metrics (const StringArray &mnames, const MatrixXd &points, const MatrixXd &ref_values)
Evalute metrics at specified points (within surrogates)
VectorXd cross_validate (const MatrixXd &samples, const MatrixXd &response, const StringArray &mnames, const int num_folds=5, const int seed=20)
Perform K-folds cross-validation (within surrogates)
template<typename DerivedSurr >
void save (const DerivedSurr &surr_out, const std::string &outfile, const bool binary)
Serialize a derived (i.e. non-base) surrogate model.
template<typename DerivedSurr >
void load (const std::string &infile, const bool binary, DerivedSurr &surr_in)
Load a derived (i.e. non-base) surrogate model.
Static Public Member Functions
template<typename SurrHandle >
static void save (const SurrHandle &surr_out, const std::string &outfile, const bool binary)
serialize Surrogate to file (typically through shared_ptr<Surrogate>, but Derived& or Derived* okay too)
template<typename SurrHandle >
static void load (const std::string &infile, const bool binary, SurrHandle &surr_in)
serialize Surrogate from file (typically through shared_ptr<Surrogate>, but Derived& or Derived* okay too)
static std::shared_ptr< Surrogate > load (const std::string &infile, const bool binary)
serialize Surrogate from file through pointer to base class (must have been saved via same data type)
Public Attributes
util::DataScaler dataScaler
DataScaler class for a Surrogate's build samples.
double responseOffset = 0.
Response offset.
double responseScaleFactor = 1.
Response scale factor.
Protected Member Functions
virtual std::shared_ptr< Surrogate > clone () const =0
clone derived Surrogate class for use in cross-validation
Protected Attributes
int numSamples
Number of samples in the Surrogate's build samples.
int numVariables
Number of features/variables in the Surrogate's build samples.
std::vector< std::string > variableLabels
Names of the variables/features; need not be populated.
int numQOI
Number of quantities of interest predicted by the surrogate. For scalar-valued surrogates numQOI = 1.
std::vector< std::string > responseLabels
Names of the responses/QoIs; need not be populated.
ParameterList defaultConfigOptions
Default Key/value options to configure the surrogate.
ParameterList configOptions
Key/value options to configure the surrogate - will override defaultConfigOptions.
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Serializer for base class data (call from dervied with base_object)
Friends
class boost::serialization::access
Allow serializers access to private class data.
Detailed Description
Parent class for surrogate models.
The Surrogate class defines the API for surrogate models contained in the Dakota surrogates module.
Pure virtual functions include build, value, and default_options. Gradient and Hessian methods are optional.
Configuration options for a surrogate are set through the use of a Teuchos ParameterList named configOptions.
Constructor & Destructor Documentation
Surrogate() [1/2]
Surrogate (const ParameterList & param_list)
Constructor that sets configOptions but does not build.
Parameters
[in] param_list List that overrides entries in defaultConfigOptions.
References Surrogate::numQOI, and dakota::silence_unused_args().
Surrogate() [2/2]
Surrogate (const MatrixXd & samples, const MatrixXd & response, const ParameterList & param_list)
Constructor for the Surrogate that sets configOptions and builds the surrogate (does nothing in the base class).
Parameters
[in] samples Matrix of data for surrogate construction - (num_samples by num_features).
[in] response Vector of targets for surrogate construction - (num_samples by num_qoi = 1; only 1 response is supported currently).
[in] param_list List that overrides entries in defaultConfigOptions.
References Surrogate::numQOI, and dakota::silence_unused_args().
Member Function Documentation
build()
virtual void build (const MatrixXd & samples, const MatrixXd & response) pure virtual
Build the Surrogate using specified build data.
Parameters
[in] samples Matrix of data for surrogate construction - (num_samples by num_features).
[in] response Vector of responses/targets for surrogate construction - (num_samples by num_qoi = 1).
Implemented in Python, PolynomialRegression, and GaussianProcess.
value()
VectorXd value (const MatrixXd & eval_points) virtual
Evaluate the Surrogate at a set of prediction points for a scalar QoI.
Parameters
[in] eval_points Matrix of prediction points - (num_pts by num_features).
Returns
Values of the Surrogate at the prediction points - (num_pts).
Reimplemented in Python, PolynomialRegression, GaussianProcess, and PyPolyReg.
References dakota::silence_unused_args().
Referenced by Surrogate::evaluate_metrics(), dakota::surrogates::fd_check_gradient(), dakota::surrogates::fd_check_hessian(), PYBIND11_MODULE(), and PyPolyReg::value().
values()
VectorXd values (const MatrixXd & eval_points) virtual
Evaluate the Surrogate at a set of prediction points for field QoIs.
Parameters
[in] eval_points Vector of prediction points - (num_features).
Returns
Values of the Surrogate at the prediction points - (num_pts).
Reimplemented in Python.
References dakota::silence_unused_args().
Referenced by PYBIND11_MODULE().
gradient()
MatrixXd gradient (const MatrixXd & eval_points) virtual
Evaluate the gradient of the scalar Surrogate at a set of prediction points.
Parameters
[in] eval_points Matrix of prediction points - (num_pts by num_features).
Returns
Matrix of gradient vectors at the prediction points - (num_pts by num_features).
Reimplemented in Python, PolynomialRegression, and GaussianProcess.
References dakota::silence_unused_args().
Referenced by dakota::surrogates::fd_check_gradient(), and PYBIND11_MODULE().
gradients()
MatrixXd gradients (const MatrixXd & eval_points)
Evaluate the gradient of the field Surrogate at a set of prediction points.
Parameters
[in] eval_points Matrix of prediction points
(num_pts by num_features).
Returns
Matrix of gradient vectors at the prediction points - (num_pts by num_features).
References dakota::silence_unused_args().
Referenced by PYBIND11_MODULE().
hessian()
MatrixXd hessian (const MatrixXd & eval_point) virtual
Evaluate the Hessian of the scalar Surrogate at a set of prediction points.
Parameters
[in] eval_point Coordinates of the prediction point - (1 by num_features).
Returns
Hessian matrix at the prediction point - (num_features by num_features).
Reimplemented in Python, PolynomialRegression, and GaussianProcess.
References dakota::silence_unused_args().
Referenced by dakota::surrogates::fd_check_hessian(), and PYBIND11_MODULE().
hessians()
MatrixXd hessians (const MatrixXd & eval_point) virtual
Evaluate the Hessian of the field Surrogate at a set of prediction points.
Parameters
[in] eval_point Coordinates of the prediction point - (1 by num_features).
Returns
Hessian matrix at the prediction point - (num_features by num_features).
References dakota::silence_unused_args().
Referenced by PYBIND11_MODULE().
variable_labels() [1/2]
void variable_labels (const std::vector< std::string > & var_labels)
Set the variable/feature names.
Parameters
[in] var_labels Vector of strings, one per input variable
References Surrogate::variableLabels.
variable_labels() [2/2]
const std::vector< std::string > & variable_labels () const
Get the (possibly empty) variable/feature names.
Returns
Vector of strings, one per input variable; empty if not set
References Surrogate::variableLabels.
Referenced by PYBIND11_MODULE().
response_labels() [1/2]
void response_labels (const std::vector< std::string > & resp_labels)
Set the response/QoI names.
Parameters
[in] resp_labels Vector of strings, one per surrogate response
References Surrogate::responseLabels.
response_labels() [2/2]
const std::vector< std::string > & response_labels () const
Get the (possibly empty) response/QoI names.
Returns
Vector of strings, one per surrogate response; empty if not set
References Surrogate::responseLabels.
Referenced by PYBIND11_MODULE().
set_options()
void set_options (const ParameterList & options)
Set the Surrogate's configOptions.
Parameters
[in] options ParameterList of configuration options.
References Surrogate::configOptions.
get_options()
void get_options (ParameterList & options)
Get the Surrogate's configOptions.
Parameters
[out] options ParameterList of configuration options.
References Surrogate::configOptions.
save()
void save (const DerivedSurr & surr_out, const std::string & outfile, const bool binary)
Serialize a derived (i.e. non-base) surrogate model.
Parameters
[in] surr_out Surrogate to seralize.
[in] outfile Name of the output text or binary file.
[in] binary Flag for binary or text format.
load()
void load (const std::string & infile, const bool binary, DerivedSurr & surr_in)
Load a derived (i.e. non-base) surrogate model.
Parameters
[in] infile Filename for serialized surrogate.
[in] binary Flag for binary or text format.
[in] surr_in Derived surrogate class to be populated with serialized data.
The documentation for this class was generated from the following files:
SurrogatesBase.hpp
SurrogatesBase.cpp