Dakota: Minimizer Class Reference
Minimizer Class Reference
Base class for the optimizer and least squares branches of the iterator hierarchy.
Public Member Functions
void constraint_tolerance (Real constr_tol)
set the method constraint tolerance (constraintTol)
Real constraint_tolerance () const
return the method constraint tolerance (constraintTol)
std::shared_ptr< TPLDataTransfer > get_data_transfer_helper () const
bool resize () override
reinitializes iterator based on new variable size
Public Member Functions inherited from Iterator
Iterator (std::shared_ptr< TraitsBase > traits=std::shared_ptr< TraitsBase >(new TraitsBase()))
default constructor
Iterator (const Iterator &iterator)=delete
copy constructor
virtual ~Iterator ()
destructor
Iterator & operator= (const Iterator &iterator)=delete
assignment operator
virtual void derived_set_communicators (ParLevLIter pl_iter)
derived class contributions to setting the communicators associated with this Iterator instance
virtual void derived_free_communicators (ParLevLIter pl_iter)
derived class contributions to freeing the communicators associated with this Iterator instance
virtual void pre_run ()
pre-run portion of run (optional); re-implemented by Iterators which can generate all Variables (parameter sets) a priori
virtual void core_run ()
core portion of run; implemented by all derived classes and may include pre/post steps in lieu of separate pre/post
virtual void pre_output ()
write variables to file, following pre-run
virtual void post_input ()
read tabular data for post-run mode
virtual void reset ()
restore initial state for repeated sub-iterator executions
virtual void nested_variable_mappings (const SizetArray &c_index1, const SizetArray &di_index1, const SizetArray &ds_index1, const SizetArray &dr_index1, const ShortArray &c_target2, const ShortArray &di_target2, const ShortArray &ds_target2, const ShortArray &dr_target2)
set primaryA{CV,DIV,DRV}MapIndices, secondaryA{CV,DIV,DRV}MapTargets within derived Iterators; supports computation of higher-level sensitivities in nested contexts (e.g., derivatives of statistics w.r.t. inserted design variables)
virtual void nested_response_mappings (const RealMatrix &primary_coeffs, const RealMatrix &secondary_coeffs)
set primaryResponseCoefficients, secondaryResponseCoefficients within derived Iterators; Necessary for scalarization case in MLMC NonDMultilevelSampling to map scalarization in nested context
virtual void initialize_iterator (int job_index)
used by IteratorScheduler to set the starting data for a run
virtual void pack_parameters_buffer (MPIPackBuffer &send_buffer, int job_index)
used by IteratorScheduler to pack starting data for an iterator run
virtual void unpack_parameters_buffer (MPIUnpackBuffer &recv_buffer, int job_index)
used by IteratorScheduler to unpack starting data for an iterator run
virtual void unpack_parameters_initialize (MPIUnpackBuffer &recv_buffer, int job_index)
used by IteratorScheduler to unpack starting data and initialize an iterator run
virtual void pack_results_buffer (MPIPackBuffer &send_buffer, int job_index)
used by IteratorScheduler to pack results data from an iterator run
virtual void unpack_results_buffer (MPIUnpackBuffer &recv_buffer, int job_index)
used by IteratorScheduler to unpack results data from an iterator run
virtual void update_local_results (int job_index)
used by IteratorScheduler to update local results arrays
virtual const Variables & variables_results () const
return a single final iterator solution (variables)
virtual const Response & response_results () const
return a single final iterator solution (response)
virtual const VariablesArray & variables_array_results ()
return multiple final iterator solutions (variables). This should only be used if returns_multiple_points() returns true.
virtual const ResponseArray & response_array_results ()
return multiple final iterator solutions (response). This should only be used if returns_multiple_points() returns true.
virtual void response_results_active_set (const ActiveSet &set)
set the requested data for the final iterator response results
virtual const RealSymMatrix & response_error_estimates () const
return error estimates associated with the final iterator solution
virtual bool accepts_multiple_points () const
indicates if this iterator accepts multiple initial points. Default return is false. Override to return true if appropriate.
virtual bool returns_multiple_points () const
indicates if this iterator returns multiple final points. Default return is false. Override to return true if appropriate.
virtual void initial_point (const Variables &pt)
sets the initial point for this iterator (user-functions mode for which Model updating is not used)
virtual void initial_point (const RealVector &pt)
sets the initial point (active continuous variables) for this iterator (user-functions mode for which Model updating is not used)
virtual void initial_points (const VariablesArray &pts)
sets the multiple initial points for this iterator. This should only be used if accepts_multiple_points() returns true.
virtual void update_callback_data (const RealVector &cv_initial, const RealVector &cv_lower_bnds, const RealVector &cv_upper_bnds, const RealMatrix &lin_ineq_coeffs, const RealVector &lin_ineq_lb, const RealVector &lin_ineq_ub, const RealMatrix &lin_eq_coeffs, const RealVector &lin_eq_tgt, const RealVector &nln_ineq_lb, const RealVector &nln_ineq_ub, const RealVector &nln_eq_tgt)
assign variable values and bounds and constraint coefficients and bounds for this iterator (user-functions mode for which iteratedModel is null)
virtual const RealMatrix & callback_linear_ineq_coefficients () const
return linear constraint coefficients for this iterator (user-functions mode for which iteratedModel is null)
virtual const RealVector & callback_linear_ineq_lower_bounds () const
return linear constraint lower bounds for this iterator (user-functions mode for which iteratedModel is null)
virtual const RealVector & callback_linear_ineq_upper_bounds () const
return linear constraint upper bounds for this iterator (user-functions mode for which iteratedModel is null)
virtual void initialize_graphics (int iterator_server_id=1)
initialize the 2D graphics window and the tabular graphics data
virtual void print_results (std::ostream &s, short results_state=FINAL_RESULTS)
print the final iterator results
virtual void check_sub_iterator_conflict ()
detect any conflicts due to recursive use of the same Fortran solver
virtual unsigned short uses_method () const
return name of any enabling iterator used by this iterator
virtual void method_recourse (unsigned short method_name)
perform a method switch, if possible, due to a detected conflict with the simultaneous use of method_name at an higher-level
virtual const VariablesArray & all_variables ()
return the complete set of evaluated variables
virtual const RealMatrix & all_samples ()
return the complete set of evaluated samples
virtual const IntResponseMap & all_responses () const
return the complete set of computed responses
virtual size_t num_samples () const
get the current number of samples
virtual void sampling_reset (size_t min_samples, bool all_data_flag, bool stats_flag)
reset sampling iterator to use at least min_samples
virtual void sampling_reference (size_t samples_ref)
set reference number of samples, which is a lower bound during reset
virtual void sampling_increment ()
increment to next in sequence of refinement samples
virtual void random_seed (int seed)
set randomSeed, if present
virtual unsigned short sampling_scheme () const
return sampling name
virtual bool compact_mode () const
returns Analyzer::compactMode
virtual IntIntPair estimate_partition_bounds ()
estimate the minimum and maximum partition sizes that can be utilized by this Iterator
virtual void declare_sources ()
Declare sources to the evaluations database.
void init_communicators (ParLevLIter pl_iter)
initialize the communicators associated with this Iterator instance
void set_communicators (ParLevLIter pl_iter)
set the communicators associated with this Iterator instance
void free_communicators (ParLevLIter pl_iter)
free the communicators associated with this Iterator instance
void resize_communicators (ParLevLIter pl_iter, bool reinit_comms)
Resize the communicators. This is called from the letter's resize()
void parallel_configuration_iterator (ParConfigLIter pc_iter)
set methodPCIter
ParConfigLIter parallel_configuration_iterator () const
return methodPCIter
void parallel_configuration_iterator_map (std::map< size_t, ParConfigLIter > pci_map)
set methodPCIterMap
std::map< size_t, ParConfigLIter > parallel_configuration_iterator_map () const
return methodPCIterMap
void run (ParLevLIter pl_iter)
invoke set_communicators(pl_iter) prior to run()
void run ()
orchestrate initialize/pre/core/post/finalize phases
void iterated_model (std::shared_ptr< Model > model)
set the iteratedModel (iterators and meta-iterators using a single model instance)
std::shared_ptr< Model > iterated_model ()
return the iteratedModel (iterators & meta-iterators using a single model instance)
ProblemDescDB & problem_description_db () const
return the problem description database (probDescDB)
ParallelLibrary & parallel_library () const
return the parallel library (parallelLib)
void method_name (unsigned short m_name)
set the method name to an enumeration value
unsigned short method_name () const
return the method name via its native enumeration value
void method_string (const String &m_str)
set the method name by string
String method_string () const
return the method name by string
const String & method_id () const
return the method identifier (methodId)
int maximum_evaluation_concurrency () const
return the maximum evaluation concurrency supported by the iterator
void maximum_evaluation_concurrency (int max_conc)
set the maximum evaluation concurrency supported by the iterator
size_t maximum_iterations () const
return the maximum iterations for this iterator
void maximum_iterations (size_t max_iter)
set the maximum iterations for this iterator
void convergence_tolerance (Real conv_tol)
set the method convergence tolerance (convergenceTol)
Real convergence_tolerance () const
return the method convergence tolerance (convergenceTol)
void output_level (short out_lev)
set the method output level (outputLevel)
short output_level () const
return the method output level (outputLevel)
void summary_output (bool summary_output_flag)
Set summary output control; true enables evaluation/results summary.
size_t num_final_solutions () const
return the number of solutions to retain in best variables/response arrays
void num_final_solutions (size_t num_final)
set the number of solutions to retain in best variables/response arrays
void active_set (const ActiveSet &set)
set the default active set (for use with iterators that employ evaluate_parameter_sets())
const ActiveSet & active_set () const
return the default active set (used by iterators that employ evaluate_parameter_sets())
void active_set_request_vector (const ShortArray &asv)
return the default active set request vector (used by iterators that employ evaluate_parameter_sets())
const ShortArray & active_set_request_vector () const
return the default active set request vector (used by iterators that employ evaluate_parameter_sets())
void active_set_request_values (short asv_val)
return the default active set request vector (used by iterators that employ evaluate_parameter_sets())
void sub_iterator_flag (bool si_flag)
set subIteratorFlag (and update summaryOutputFlag if needed)
virtual void eval_tag_prefix (const String &eval_id_str)
set the hierarchical eval ID tag prefix
std::shared_ptr< TraitsBase > traits () const
returns methodTraits for access to derived class member functions that are not mapped to the top TraitsBase level
bool top_level ()
Return whether the iterator is the top level iterator.
void top_level (bool tflag)
Set the iterator's top level flag.
Static Public Member Functions
static Real sum_squared_residuals (size_t num_pri_fns, const RealVector &residuals, const RealVector &weights)
return weighted sum of squared residuals
static void print_residuals (size_t num_terms, const RealVector &best_terms, const RealVector &weights, size_t num_best, size_t best_index, std::ostream &s)
print num_terms residuals and misfit for final results
static void print_model_resp (size_t num_pri_fns, const RealVector &best_fns, size_t num_best, size_t best_index, std::ostream &s)
print the original user model resp in the case of data transformations
static void print_best_eval_ids (const String &interface_id, const Variables &best_vars, const ActiveSet &active_set, std::ostream &s)
print best evaluation matching vars and set, or partial matches with matching variables only.
Static Public Member Functions inherited from Iterator
static String method_enum_to_string (unsigned short method_enum)
convert a method name enumeration value to a string
static unsigned short method_string_to_enum (const String &method_str)
convert a method name string to an enumeration value
static String submethod_enum_to_string (unsigned short submethod_enum)
convert a sub-method name enumeration value to a string
Protected Member Functions
Minimizer (std::shared_ptr< TraitsBase > traits=std::shared_ptr< TraitsBase >(new TraitsBase()))
default constructor
Minimizer (ProblemDescDB &problem_db, std::shared_ptr< Model > model, std::shared_ptr< TraitsBase > traits=std::shared_ptr< TraitsBase >(new TraitsBase()))
standard constructor
Minimizer (unsigned short method_name, std::shared_ptr< Model > model, std::shared_ptr< TraitsBase > traits=std::shared_ptr< TraitsBase >(new TraitsBase()))
alternate constructor for "on the fly" instantiations
Minimizer (unsigned short method_name, size_t num_lin_ineq, size_t num_lin_eq, size_t num_nln_ineq, size_t num_nln_eq, std::shared_ptr< TraitsBase > traits=std::shared_ptr< TraitsBase >(new TraitsBase()))
alternate constructor for "on the fly" instantiations
Minimizer (std::shared_ptr< Model > model, size_t max_iter, size_t max_eval, Real conv_tol, std::shared_ptr< TraitsBase > traits=std::shared_ptr< TraitsBase >(new TraitsBase()))
alternate constructor for "on the fly" instantiations
~Minimizer () override
destructor
void update_from_model (const Model &model) override
set inherited data attributes based on extractions from incoming model
void initialize_run () override
utility function to perform common operations prior to pre_run(); typically memory initialization; setting of instance pointers
void post_run (std::ostream &s) override
post-run portion of run (optional); verbose to print results; re-implemented by Iterators that can read all Variables/Responses and perform final analysis phase in a standalone way
void finalize_run () override
utility function to perform common operations following post_run(); deallocation and resetting of instance pointers
std::shared_ptr< Model > algorithm_space_model () override
std::shared_ptr< Model > original_model (unsigned short recasts_left=0) const
Return a shallow copy of the original model this Iterator was originally passed, optionally leaving recasts_left on top of it.
void data_transform_model ()
Wrap iteratedModel in a RecastModel that subtracts provided observed data from the primary response functions (variables and secondary responses are unchanged)
void scale_model ()
Wrap iteratedModel in a RecastModel that performs variable and/or response scaling.
void enforce_null_model ()
ensure iteratedModel is null when using function callbacks for evaluation
Real objective (const RealVector &fn_vals, const BoolDeque &max_sense, const RealVector &primary_wts) const
compute a composite objective value from one or more primary functions
Real objective (const RealVector &fn_vals, size_t num_fns, const BoolDeque &max_sense, const RealVector &primary_wts) const
compute a composite objective with specified number of source primary functions, instead of userPrimaryFns
void objective_gradient (const RealVector &fn_vals, const RealMatrix &fn_grads, const BoolDeque &max_sense, const RealVector &primary_wts, RealVector &obj_grad) const
compute the gradient of the composite objective function
void objective_gradient (const RealVector &fn_vals, size_t num_fns, const RealMatrix &fn_grads, const BoolDeque &max_sense, const RealVector &primary_wts, RealVector &obj_grad) const
compute the gradient of the composite objective function
void objective_hessian (const RealVector &fn_vals, const RealMatrix &fn_grads, const RealSymMatrixArray &fn_hessians, const BoolDeque &max_sense, const RealVector &primary_wts, RealSymMatrix &obj_hess) const
compute the Hessian of the composite objective function
void objective_hessian (const RealVector &fn_vals, size_t num_fns, const RealMatrix &fn_grads, const RealSymMatrixArray &fn_hessians, const BoolDeque &max_sense, const RealVector &primary_wts, RealSymMatrix &obj_hess) const
compute the Hessian of the composite objective function
virtual void archive_best_results ()
top-level archival method
void archive_best_variables (const bool active_only=false) const
archive best variables for the index'th final solution
void archive_best_objective_functions () const
archive the index'th set of objective functions
void archive_best_constraints () const
archive the index'th set of constraints
void archive_best_residuals () const
Archive residuals when calibration terms are used.
void resize_best_vars_array (size_t newsize)
Safely resize the best variables array to newsize taking into account the envelope-letter design pattern and any recasting.
void resize_best_resp_array (size_t newsize)
Safely resize the best response array to newsize taking into account the envelope-letter design pattern and any recasting.
bool local_recast_retrieve (const Variables &vars, Response &response) const
infers MOO/NLS solution from the solution of a single-objective optimizer and returns true if lookup succeeds
void reshape_best (size_t num_cv, size_t num_fns)
reshape input/output sizes within best{Variables,Response}Array
Protected Member Functions inherited from Iterator
Iterator (ProblemDescDB &problem_db, std::shared_ptr< TraitsBase > traits=std::shared_ptr< TraitsBase >(new TraitsBase()))
constructor initializes the base class part of letter classes (BaseConstructor overloading avoids infinite recursion in the derived class constructors - Coplien, p. 139)
Iterator (unsigned short method_name, std::shared_ptr< Model > model, std::shared_ptr< TraitsBase > traits=std::shared_ptr< TraitsBase >(new TraitsBase()))
alternate constructor for base iterator classes constructed on the fly
Iterator (unsigned short method_name, std::shared_ptr< TraitsBase > traits=std::shared_ptr< TraitsBase >(new TraitsBase()))
alternate constructor for base iterator classes constructed on the fly
Iterator (std::shared_ptr< Model > model, size_t max_iter, size_t max_eval, Real conv_tol, std::shared_ptr< TraitsBase > traits=std::shared_ptr< TraitsBase >(new TraitsBase()))
alternate envelope constructor for instantiations without ProblemDescDB
virtual void derived_init_communicators (ParLevLIter pl_iter)
derived class contributions to initializing the communicators associated with this Iterator instance
virtual const VariablesArray & initial_points () const
gets the multiple initial points for this iterator. This will only be meaningful after a call to initial_points mutator.
StrStrSizet run_identifier () const
get the unique run identifier based on method name, id, and number of executions
void initialize_model_graphics (Model &model, int iterator_server_id)
helper function that encapsulates initialization operations, modular on incoming Model instance
void export_final_surrogates (Model &data_fit_surr_model)
export final surrogates generated, e.g., GP in EGO and friends
Protected Attributes
size_t numFunctions
number of response functions
size_t numContinuousVars
number of active continuous vars
size_t numDiscreteIntVars
number of active discrete integer vars
size_t numDiscreteStringVars
number of active discrete string vars
size_t numDiscreteRealVars
number of active discrete real vars
Real constraintTol
optimizer/least squares constraint tolerance
Real bigRealBoundSize
cutoff value for inequality constraint and continuous variable bounds
int bigIntBoundSize
cutoff value for discrete variable bounds
size_t numNonlinearIneqConstraints
number of nonlinear inequality constraints
size_t numNonlinearEqConstraints
number of nonlinear equality constraints
size_t numLinearIneqConstraints
number of linear inequality constraints
size_t numLinearEqConstraints
number of linear equality constraints
size_t numNonlinearConstraints
total number of nonlinear constraints
size_t numLinearConstraints
total number of linear constraints
size_t numConstraints
total number of linear and nonlinear constraints
bool optimizationFlag
flag for use where optimization and NLS must be distinguished
size_t numUserPrimaryFns
number of objective functions or least squares terms in the inbound model; always initialize at Minimizer, even if overridden later
size_t numIterPrimaryFns
number of objective functions or least squares terms in iterator's view, after transformations; always initialize at Minimizer, even if overridden later
bool boundConstraintFlag
convenience flag for denoting the presence of user-specified bound constraints. Used for method selection and error checking.
bool speculativeFlag
flag for speculative gradient evaluations
bool calibrationDataFlag
flag indicating whether user-supplied calibration data is active
ExperimentData expData
Container for experimental data to which to calibrate model using least squares or other formulations which minimize SSE.
size_t numExperiments
number of experiments
size_t numTotalCalibTerms
number of total calibration terms (sum over experiments of number of experimental data per experiment, including field data)
std::shared_ptr< Model > dataTransformModel
Shallow copy of the data transformation model, when present (cached in case further wrapped by other transformations)
bool scaleFlag
whether Iterator-level scaling is active
std::shared_ptr< Model > scalingModel
Shallow copy of the scaling transformation model, when present (cached in case further wrapped by other transformations)
Minimizer * prevMinInstance
pointer containing previous value of minimizerInstance
bool vendorNumericalGradFlag
convenience flag for gradient_type == numerical && method_source == vendor
std::shared_ptr< TPLDataTransfer > dataTransferHandler
Emerging helper class for handling data transfers to/from Dakota and the underlying TPL.
Protected Attributes inherited from Iterator
std::shared_ptr< Model > iteratedModel
the model to be iterated (for iterators and meta-iterators employing a single model instance)
ProblemDescDB & probDescDB
class member reference to the problem description database
ParallelLibrary & parallelLib
class member reference to the parallel library
ParConfigLIter methodPCIter
the active ParallelConfiguration used by this Iterator instance
size_t myModelLayers
number of Models locally (in Iterator or derived classes) wrapped around the initially passed in Model
unsigned short methodName
name of the iterator (the user's method spec)
Real convergenceTol
iteration convergence tolerance
size_t maxIterations
maximum number of iterations for the method
size_t maxFunctionEvals
maximum number of fn evaluations for the method
int maxEvalConcurrency
maximum number of concurrent model evaluations
ActiveSet activeSet
the response data requirements on each function evaluation
size_t numFinalSolutions
number of solutions to retain in best variables/response arrays
VariablesArray bestVariablesArray
collection of N best solution variables found during the study; always in context of Model originally passed to the Iterator (any in-flight Recasts must be undone)
ResponseArray bestResponseArray
collection of N best solution responses found during the study; always in context of Model originally passed to the Iterator (any in-flight Recasts must be undone)
bool subIteratorFlag
flag indicating if this Iterator is a sub-iterator (NestedModel::subIterator or DataFitSurrModel::daceIterator)
short outputLevel
output verbosity level: {SILENT,QUIET,NORMAL,VERBOSE,DEBUG}_OUTPUT
bool summaryOutputFlag
flag for summary output (evaluation stats, final results); default true, but false for on-the-fly (helper) iterators and sub-iterator use cases
ResultsManager & resultsDB
reference to the global iterator results database
EvaluationStore & evaluationsDB
reference to the global evaluation database
EvaluationsDBState evaluationsDBState
State of evaluations DB for this iterator.
ResultsNames resultsNames
valid names for iterator results
std::shared_ptr< TraitsBase > methodTraits
pointer that retains shared ownership of a TraitsBase object, or child thereof
bool topLevel
Whether this is the top level iterator.
bool exportSurrogate = false
whether to export final surrogates
String surrExportPrefix
base filename for exported surrogates
unsigned short surrExportFormat = NO_MODEL_FORMAT
(bitwise) format(s) to export
Static Protected Attributes
static Minimizer * minimizerInstance
pointer to Minimizer used in static member functions
Friends
class SOLBase
the SOLBase class is not derived the iterator hierarchy but still needs access to iterator hierarchy data (to avoid attribute replication)
class SNLLBase
the SNLLBase class is not derived the iterator hierarchy but still needs access to iterator hierarchy data (to avoid attribute replication)
Additional Inherited Members
Static Protected Member Functions inherited from Iterator
static void gnewton_set_recast (const Variables &recast_vars, const ActiveSet &recast_set, ActiveSet &sub_model_set)
conversion of request vector values for the Gauss-Newton Hessian approximation
Detailed Description
Base class for the optimizer and least squares branches of the iterator hierarchy.
The Minimizer class provides common data and functionality for Optimizer and LeastSq.
Constructor & Destructor Documentation
Minimizer()
Minimizer (ProblemDescDB & problem_db, std::shared_ptr< Model > model, std::shared_ptr< TraitsBase > traits = std::shared_ptr<TraitsBase>(new TraitsBase())) protected
standard constructor
This constructor extracts inherited data for the optimizer and least squares branches and performs sanity checking on constraint settings.
References Iterator::iteratedModel, Iterator::maxFunctionEvals, Iterator::maxIterations, Iterator::methodName, Iterator::numFinalSolutions, Dakota::SZ_MAX, and Minimizer::update_from_model().
Member Function Documentation
print_best_eval_ids()
void print_best_eval_ids (const String & search_interface_id, const Variables & search_vars, const ActiveSet & search_set, std::ostream & s) static
print best evaluation matching vars and set, or partial matches with matching variables only.
Lookup evaluation id where best occurred. This cannot be catalogued directly because the optimizers track the best iterate internally and return the best results after iteration completion. Therfore, perform a search in data_pairs to extract the evalId for the best fn eval.
References Dakota::data_pairs, and Dakota::lookup_by_val().
Referenced by LeastSq::print_results(), Optimizer::print_results(), and SurrBasedMinimizer::print_results().
resize()
bool resize () override virtual
reinitializes iterator based on new variable size
This constructor assigns a representation pointer into this envelope, transferring ownership. It behaves the same as a default construction followed by assign_rep().
Reimplemented from Iterator.
References Dakota::abort_handler(), Iterator::method_enum_to_string(), Iterator::methodName, and Iterator::resize().
Referenced by Minimizer::finalize_run(), and Minimizer::initialize_run().
initialize_run()
void initialize_run () override protected virtual
utility function to perform common operations prior to pre_run(); typically memory initialization; setting of instance pointers
Perform initialization phases of run sequence, like allocating memory and setting instance pointers. Commonly used in sub-iterator executions. This is a virtual function; when re-implementing, a derived class must call its nearest parent's initialize_run(), typically before performing its own implementation steps.
Reimplemented from Iterator.
Reimplemented in SNLLOptimizer, SNLLLeastSq, ROLOptimizer, and Optimizer.
References Iterator::bestVariablesArray, Iterator::iteratedModel, Iterator::methodPCIter, Minimizer::minimizerInstance, Iterator::myModelLayers, Minimizer::prevMinInstance, Minimizer::resize(), Iterator::subIteratorFlag, and Iterator::summaryOutputFlag.
Referenced by LeastSq::initialize_run(), and Optimizer::initialize_run().
post_run()
void post_run (std::ostream & s) override protected virtual
post-run portion of run (optional); verbose to print results; re-implemented by Iterators that can read all Variables/Responses and perform final analysis phase in a standalone way
Post-run phase, which a derived iterator may optionally reimplement; when not present, post-run is likely integrated into run. This is a virtual function; when re-implementing, a derived class must call its nearest parent's post_run(), typically after performing its own implementation steps.
Reimplemented from Iterator.
Reimplemented in SurrBasedLocalMinimizer, SNLLOptimizer, EffGlobalMinimizer, and Optimizer.
References Minimizer::archive_best_results(), Iterator::iteratedModel, Iterator::print_results(), and Iterator::summaryOutputFlag.
Referenced by LeastSq::post_run(), Optimizer::post_run(), EffGlobalMinimizer::post_run(), and SurrBasedLocalMinimizer::post_run().
finalize_run()
void finalize_run () override protected virtual
utility function to perform common operations following post_run(); deallocation and resetting of instance pointers
Optional: perform finalization phases of run sequence, like deallocating memory and resetting instance pointers. Commonly used in sub-iterator executions. This is a virtual function; when re-implementing, a derived class must call its nearest parent's finalize_run(), typically after performing its own implementation steps.
Reimplemented from Iterator.
Reimplemented in SNLLOptimizer, SNLLLeastSq, and Optimizer.
References Iterator::iteratedModel, Minimizer::minimizerInstance, Minimizer::prevMinInstance, and Minimizer::resize().
Referenced by LeastSq::finalize_run(), and Optimizer::finalize_run().
algorithm_space_model()
std::shared_ptr< Model > algorithm_space_model () inline override protected virtual
default definition that gets redefined in selected derived Minimizers
Reimplemented from Iterator.
Reimplemented in EffGlobalMinimizer.
References Iterator::iteratedModel.
data_transform_model()
void data_transform_model () protected
Wrap iteratedModel in a RecastModel that subtracts provided observed data from the primary response functions (variables and secondary responses are unchanged)
Reads observation data to compute least squares residuals and expands residuals for multiple experiments.
References Dakota::abort_handler(), Iterator::activeSet, Minimizer::dataTransformModel, Minimizer::expData, ProblemDescDB::get_sizet(), Iterator::iteratedModel, ExperimentData::load_data(), Iterator::myModelLayers, ExperimentData::num_config_vars(), Minimizer::numExperiments, Minimizer::numFunctions, Minimizer::numIterPrimaryFns, Minimizer::numNonlinearConstraints, Minimizer::numTotalCalibTerms, Iterator::outputLevel, Iterator::probDescDB, and ActiveSet::request_vector().
Referenced by LeastSq::LeastSq(), and Optimizer::Optimizer().
scale_model()
void scale_model () protected
Wrap iteratedModel in a RecastModel that performs variable and/or response scaling.
Wrap the iteratedModel in a scaling transformation, such that iteratedModel now contains a scaling recast model. Potentially affects variables, primary, and secondary responses
References Iterator::iteratedModel, Iterator::myModelLayers, and Minimizer::scalingModel.
Referenced by LeastSq::LeastSq(), and Optimizer::Optimizer().
objective() [1/2]
Real objective (const RealVector & fn_vals, const BoolDeque & max_sense, const RealVector & primary_wts) const protected
compute a composite objective value from one or more primary functions
The composite objective computation sums up the contributions from one of more primary functions using the primary response fn weights.
References Minimizer::numUserPrimaryFns.
Referenced by SurrBasedLocalMinimizer::approx_subprob_objective_eval(), SurrBasedMinimizer::augmented_lagrangian_merit(), EffGlobalMinimizer::compute_expected_improvement(), EffGlobalMinimizer::compute_lower_confidence_bound(), EffGlobalMinimizer::compute_probability_improvement(), SurrBasedLocalMinimizer::compute_trust_region_ratio(), SurrBasedMinimizer::initialize_filter(), SurrBasedMinimizer::lagrangian_merit(), Optimizer::objective_reduction(), SurrBasedMinimizer::penalty_merit(), COLINOptimizer::post_run(), SurrBasedMinimizer::update_filter(), and SurrBasedLocalMinimizer::update_penalty().
objective() [2/2]
Real objective (const RealVector & fn_vals, size_t num_fns, const BoolDeque & max_sense, const RealVector & primary_wts) const protected
compute a composite objective with specified number of source primary functions, instead of userPrimaryFns
This "composite" objective is a more general case of the previous objective(), but doesn't presume a reduction map from user to iterated space. Used to apply weights and sense in COLIN results sorting. Leaving as a duplicate implementation pending resolution of COLIN lookups.
References Minimizer::optimizationFlag.
objective_gradient()
void objective_gradient (const RealVector & fn_vals, size_t num_fns, const RealMatrix & fn_grads, const BoolDeque & max_sense, const RealVector & primary_wts, RealVector & obj_grad) const protected
compute the gradient of the composite objective function
The composite objective gradient computation combines the contributions from one of more primary function gradients, including the effect of any primary function weights. In the case of a linear mapping (MOO), only the primary function gradients are required, but in the case of a nonlinear mapping (NLS), primary function values are also needed. Within RecastModel::set_mapping(), the active set requests are automatically augmented to make values available when needed, based on nonlinearRespMapping settings.
References Minimizer::numContinuousVars, and Minimizer::optimizationFlag.
objective_hessian()
void objective_hessian (const RealVector & fn_vals, size_t num_fns, const RealMatrix & fn_grads, const RealSymMatrixArray & fn_hessians, const BoolDeque & max_sense, const RealVector & primary_wts, RealSymMatrix & obj_hess) const protected
compute the Hessian of the composite objective function
The composite objective Hessian computation combines the contributions from one of more primary function Hessians, including the effect of any primary function weights. In the case of a linear mapping (MOO), only the primary function Hessians are required, but in the case of a nonlinear mapping (NLS), primary function values and gradients are also needed in general (gradients only in the case of a Gauss-Newton approximation). Within the default RecastModel::set_mapping(), the active set requests are automatically augmented to make values and gradients available when needed, based on nonlinearRespMapping settings.
References Dakota::abort_handler(), Minimizer::numContinuousVars, Minimizer::optimizationFlag, and Dakota::sum().
resize_best_vars_array()
void resize_best_vars_array (size_t newsize) protected
Safely resize the best variables array to newsize taking into account the envelope-letter design pattern and any recasting.
Uses data from the innermost model, should any Minimizer recasts be active. Called by multipoint return solvers. Do not directly call resize on the bestVariablesArray object unless you intend to share the internal content (letter) with other objects after assignment.
References Iterator::bestVariablesArray, and Minimizer::original_model().
Referenced by COLINOptimizer::post_run().
resize_best_resp_array()
void resize_best_resp_array (size_t newsize) protected
Safely resize the best response array to newsize taking into account the envelope-letter design pattern and any recasting.
Uses data from the innermost model, should any Minimizer recasts be active. Called by multipoint return solvers. Do not directly call resize on the bestResponseArray object unless you intend to share the internal content (letter) with other objects after assignment.
References Iterator::bestResponseArray, and Minimizer::original_model().
Referenced by COLINOptimizer::post_run().
local_recast_retrieve()
bool local_recast_retrieve (const Variables & vars, Response & response) const protected
infers MOO/NLS solution from the solution of a single-objective optimizer and returns true if lookup succeeds
Retrieve a MOO/NLS response based on the data returned by a single objective optimizer by performing a data_pairs search. This may get called even for a single user-specified function, since we may be recasting a single NLS residual into a squared objective. Always returns best data in the space of the original inbound Model.
References Response::active_set(), Dakota::data_pairs, Iterator::iteratedModel, Dakota::lookup_by_val(), and Response::update().
Referenced by Optimizer::post_run().
The documentation for this class was generated from the following files:
DakotaMinimizer.hpp
DakotaMinimizer.cpp