Dakota: NonDMultilevControlVarSampling Class Reference
NonDMultilevControlVarSampling Class Reference
Performs multilevel-multifidelity Monte Carlo sampling for uncertainty quantification.
Public Member Functions
NonDMultilevControlVarSampling (ProblemDescDB &problem_db, std::shared_ptr< Model > model)
standard constructor
~NonDMultilevControlVarSampling () override
destructor
Public Member Functions inherited from NonDMultilevelSampling
NonDMultilevelSampling (ProblemDescDB &problem_db, std::shared_ptr< Model > model)
standard constructor
~NonDMultilevelSampling () override
destructor
Public Member Functions inherited from NonDHierarchSampling
NonDHierarchSampling (ProblemDescDB &problem_db, std::shared_ptr< Model > model)
standard constructor
~NonDHierarchSampling () override
destructor (virtual declaration should be redundant with ~Iterator, but this is top of MLMF diamond so doesn't hurt to be explicit)
Public Member Functions inherited from NonDEnsembleSampling
NonDEnsembleSampling (ProblemDescDB &problem_db, std::shared_ptr< Model > model)
standard constructor
~NonDEnsembleSampling () override
destructor (virtual declaration should be redundant with ~Iterator, but this is top of MLMF diamond so doesn't hurt to be explicit)
bool resize () override
reinitializes iterator based on new variable size
Public Member Functions inherited from NonDSampling
NonDSampling (std::shared_ptr< Model > model, const RealMatrix &sample_matrix)
alternate constructor for evaluating and computing statistics for the provided set of samples
~NonDSampling () override
destructor
void compute_statistics (const RealMatrix &vars_samples, const IntResponseMap &resp_samples)
For the input sample set, computes mean, standard deviation, and probability/reliability/response levels (aleatory uncertainties) or intervals (epsitemic or mixed uncertainties)
void compute_intervals (RealRealPairArray &extreme_fns)
called by compute_statistics() to calculate min/max intervals using allResponses
void compute_intervals (const IntResponseMap &samples)
called by compute_statistics() to calculate extremeValues from samples
void compute_intervals (RealRealPairArray &extreme_fns, const IntResponseMap &samples)
called by compute_statistics() to calculate min/max intervals using samples
void compute_moments (const RealVectorArray &fn_samples)
calculates sample moments from a matrix of observations for a set of QoI
void compute_moments (const IntResponseMap &samples)
calculate sample moments and confidence intervals from a map of response observations
void compute_moments (const IntResponseMap &samples, RealMatrix &moment_stats, RealMatrix &moment_grads, RealMatrix &moment_conf_ints, short moments_type, const StringArray &labels)
convert IntResponseMap to RealVectorArray and invoke helpers
void compute_moment_gradients (const RealVectorArray &fn_samples, const RealMatrixArray &grad_samples, const RealMatrix &moment_stats, RealMatrix &moment_grads, short moments_type)
compute moment_grads from function and gradient samples
void compute_moment_confidence_intervals (const RealMatrix &moment_stats, RealMatrix &moment_conf_ints, const SizetArray &sample_counts, short moments_type)
compute moment confidence intervals from moment values
void archive_moments (size_t inc_id=0)
archive moment statistics in results DB
void archive_moment_confidence_intervals (size_t inc_id=0)
archive moment confidence intervals in results DB
void archive_std_regress_coeffs ()
archive standardized regression coefficients in results DB
void archive_extreme_responses (size_t inc_id=0)
archive extreme values (epistemic result) in results DB
void compute_level_mappings (const IntResponseMap &samples)
called by compute_statistics() to calculate CDF/CCDF mappings of z to p/beta and of p/beta to z as well as PDFs
void print_statistics (std::ostream &s) const
prints the statistics computed in compute_statistics()
void print_intervals (std::ostream &s) const
prints the intervals computed in compute_intervals() with default qoi_type and moment_labels
void print_intervals (std::ostream &s, String qoi_type, const StringArray &interval_labels) const
prints the intervals computed in compute_intervals()
void print_moments (std::ostream &s) const
prints the moments computed in compute_moments() with default qoi_type and moment_labels
void print_moments (std::ostream &s, String qoi_type, const StringArray &moment_labels) const
prints the moments computed in compute_moments()
void print_wilks_stastics (std::ostream &s) const
prints the Wilks stastics
void print_tolerance_intervals_statistics (std::ostream &s) const
prints the tolerance intervals stastics
void archive_tolerance_intervals (size_t inc_id=0)
archive the tolerance intervals statistics in results DB
void update_final_statistics () override
update finalStatistics from minValues/maxValues, momentStats, and computedProbLevels/computedRelLevels/computedRespLevels
void transform_samples (Model &src_model, Model &tgt_model)
transform allSamples using configuration data from the source and target models
void transform_samples (Pecos::ProbabilityTransformation &nataf, bool x_to_u=true)
alternate version to transform allSamples. This is needed since random variable distribution parameters are not updated until run time and an imported sample_matrix is typically in x-space.
void transform_samples (Pecos::ProbabilityTransformation &nataf, RealMatrix &sample_matrix, bool x_to_u=true)
transform the specified samples matrix from x to u or u to x, assuming identical view and ids
void transform_samples (Pecos::ProbabilityTransformation &nataf, RealMatrix &sample_matrix, SizetMultiArrayConstView src_cv_ids, SizetMultiArrayConstView tgt_cv_ids, bool x_to_u=true)
transform the specified samples matrix from x to u or u to x
unsigned short sampling_scheme () const override
return sampleType
const String & random_number_generator () const
return rngName
Public Member Functions inherited from NonD
void requested_levels (const RealVectorArray &req_resp_levels, const RealVectorArray &req_prob_levels, const RealVectorArray &req_rel_levels, const RealVectorArray &req_gen_rel_levels, short resp_lev_tgt, short resp_lev_tgt_reduce, bool cdf_flag, bool pdf_output)
set requestedRespLevels, requestedProbLevels, requestedRelLevels, requestedGenRelLevels, respLevelTarget, cdfFlag, and pdfOutput (used in combination with alternate ctors)
void print_level_mappings (std::ostream &s) const
prints the z/p/beta/beta* mappings reflected in {requested,computed}{Resp,Prob,Rel,GenRel}Levels for default qoi_type and qoi_labels
void print_level_mappings (std::ostream &s, String qoi_type, const StringArray &qoi_labels) const
prints the z/p/beta/beta* mappings reflected in {requested,computed}{Resp,Prob,Rel,GenRel}Levels
void print_level_mappings (std::ostream &s, const RealVector &level_maps, bool moment_offset, const String &prepend="") const
print level mapping statistics using optional pre-pend
bool pdf_output () const
get pdfOutput
void pdf_output (bool output)
set pdfOutput
short final_moments_type () const
get finalMomentsType
void final_moments_type (short type)
set finalMomentsType
Public Member Functions inherited from Analyzer
const VariablesArray & all_variables () override
return the complete set of evaluated variables
const RealMatrix & all_samples () override
return the complete set of evaluated samples
const IntResponseMap & all_responses () const override
return the complete set of computed responses
Public Member Functions inherited from Iterator
Iterator (std::shared_ptr< TraitsBase > traits=std::shared_ptr< TraitsBase >(new TraitsBase()))
default constructor
Iterator (const Iterator &iterator)=delete
copy constructor
virtual ~Iterator ()
destructor
Iterator & operator= (const Iterator &iterator)=delete
assignment operator
virtual void derived_free_communicators (ParLevLIter pl_iter)
derived class contributions to freeing the communicators associated with this Iterator instance
virtual void post_input ()
read tabular data for post-run mode
virtual void reset ()
restore initial state for repeated sub-iterator executions
virtual void nested_variable_mappings (const SizetArray &c_index1, const SizetArray &di_index1, const SizetArray &ds_index1, const SizetArray &dr_index1, const ShortArray &c_target2, const ShortArray &di_target2, const ShortArray &ds_target2, const ShortArray &dr_target2)
set primaryA{CV,DIV,DRV}MapIndices, secondaryA{CV,DIV,DRV}MapTargets within derived Iterators; supports computation of higher-level sensitivities in nested contexts (e.g., derivatives of statistics w.r.t. inserted design variables)
virtual void initialize_iterator (int job_index)
used by IteratorScheduler to set the starting data for a run
virtual void pack_parameters_buffer (MPIPackBuffer &send_buffer, int job_index)
used by IteratorScheduler to pack starting data for an iterator run
virtual void unpack_parameters_buffer (MPIUnpackBuffer &recv_buffer, int job_index)
used by IteratorScheduler to unpack starting data for an iterator run
virtual void unpack_parameters_initialize (MPIUnpackBuffer &recv_buffer, int job_index)
used by IteratorScheduler to unpack starting data and initialize an iterator run
virtual void pack_results_buffer (MPIPackBuffer &send_buffer, int job_index)
used by IteratorScheduler to pack results data from an iterator run
virtual void unpack_results_buffer (MPIUnpackBuffer &recv_buffer, int job_index)
used by IteratorScheduler to unpack results data from an iterator run
virtual void update_local_results (int job_index)
used by IteratorScheduler to update local results arrays
virtual bool accepts_multiple_points () const
indicates if this iterator accepts multiple initial points. Default return is false. Override to return true if appropriate.
virtual void initial_point (const Variables &pt)
sets the initial point for this iterator (user-functions mode for which Model updating is not used)
virtual void initial_point (const RealVector &pt)
sets the initial point (active continuous variables) for this iterator (user-functions mode for which Model updating is not used)
virtual void initial_points (const VariablesArray &pts)
sets the multiple initial points for this iterator. This should only be used if accepts_multiple_points() returns true.
virtual void update_callback_data (const RealVector &cv_initial, const RealVector &cv_lower_bnds, const RealVector &cv_upper_bnds, const RealMatrix &lin_ineq_coeffs, const RealVector &lin_ineq_lb, const RealVector &lin_ineq_ub, const RealMatrix &lin_eq_coeffs, const RealVector &lin_eq_tgt, const RealVector &nln_ineq_lb, const RealVector &nln_ineq_ub, const RealVector &nln_eq_tgt)
assign variable values and bounds and constraint coefficients and bounds for this iterator (user-functions mode for which iteratedModel is null)
virtual const RealMatrix & callback_linear_ineq_coefficients () const
return linear constraint coefficients for this iterator (user-functions mode for which iteratedModel is null)
virtual const RealVector & callback_linear_ineq_lower_bounds () const
return linear constraint lower bounds for this iterator (user-functions mode for which iteratedModel is null)
virtual const RealVector & callback_linear_ineq_upper_bounds () const
return linear constraint upper bounds for this iterator (user-functions mode for which iteratedModel is null)
virtual void initialize_graphics (int iterator_server_id=1)
initialize the 2D graphics window and the tabular graphics data
virtual void check_sub_iterator_conflict ()
detect any conflicts due to recursive use of the same Fortran solver
virtual unsigned short uses_method () const
return name of any enabling iterator used by this iterator
virtual void method_recourse (unsigned short method_name)
perform a method switch, if possible, due to a detected conflict with the simultaneous use of method_name at an higher-level
virtual void sampling_increment ()
increment to next in sequence of refinement samples
virtual IntIntPair estimate_partition_bounds ()
estimate the minimum and maximum partition sizes that can be utilized by this Iterator
virtual void declare_sources ()
Declare sources to the evaluations database.
void init_communicators (ParLevLIter pl_iter)
initialize the communicators associated with this Iterator instance
void set_communicators (ParLevLIter pl_iter)
set the communicators associated with this Iterator instance
void free_communicators (ParLevLIter pl_iter)
free the communicators associated with this Iterator instance
void resize_communicators (ParLevLIter pl_iter, bool reinit_comms)
Resize the communicators. This is called from the letter's resize()
void parallel_configuration_iterator (ParConfigLIter pc_iter)
set methodPCIter
ParConfigLIter parallel_configuration_iterator () const
return methodPCIter
void parallel_configuration_iterator_map (std::map< size_t, ParConfigLIter > pci_map)
set methodPCIterMap
std::map< size_t, ParConfigLIter > parallel_configuration_iterator_map () const
return methodPCIterMap
void run (ParLevLIter pl_iter)
invoke set_communicators(pl_iter) prior to run()
void run ()
orchestrate initialize/pre/core/post/finalize phases
void iterated_model (std::shared_ptr< Model > model)
set the iteratedModel (iterators and meta-iterators using a single model instance)
std::shared_ptr< Model > iterated_model ()
return the iteratedModel (iterators & meta-iterators using a single model instance)
ProblemDescDB & problem_description_db () const
return the problem description database (probDescDB)
ParallelLibrary & parallel_library () const
return the parallel library (parallelLib)
void method_name (unsigned short m_name)
set the method name to an enumeration value
unsigned short method_name () const
return the method name via its native enumeration value
void method_string (const String &m_str)
set the method name by string
String method_string () const
return the method name by string
const String & method_id () const
return the method identifier (methodId)
int maximum_evaluation_concurrency () const
return the maximum evaluation concurrency supported by the iterator
void maximum_evaluation_concurrency (int max_conc)
set the maximum evaluation concurrency supported by the iterator
size_t maximum_iterations () const
return the maximum iterations for this iterator
void maximum_iterations (size_t max_iter)
set the maximum iterations for this iterator
void convergence_tolerance (Real conv_tol)
set the method convergence tolerance (convergenceTol)
Real convergence_tolerance () const
return the method convergence tolerance (convergenceTol)
void output_level (short out_lev)
set the method output level (outputLevel)
short output_level () const
return the method output level (outputLevel)
void summary_output (bool summary_output_flag)
Set summary output control; true enables evaluation/results summary.
size_t num_final_solutions () const
return the number of solutions to retain in best variables/response arrays
void num_final_solutions (size_t num_final)
set the number of solutions to retain in best variables/response arrays
void active_set (const ActiveSet &set)
set the default active set (for use with iterators that employ evaluate_parameter_sets())
const ActiveSet & active_set () const
return the default active set (used by iterators that employ evaluate_parameter_sets())
void active_set_request_vector (const ShortArray &asv)
return the default active set request vector (used by iterators that employ evaluate_parameter_sets())
const ShortArray & active_set_request_vector () const
return the default active set request vector (used by iterators that employ evaluate_parameter_sets())
void active_set_request_values (short asv_val)
return the default active set request vector (used by iterators that employ evaluate_parameter_sets())
void sub_iterator_flag (bool si_flag)
set subIteratorFlag (and update summaryOutputFlag if needed)
virtual void eval_tag_prefix (const String &eval_id_str)
set the hierarchical eval ID tag prefix
std::shared_ptr< TraitsBase > traits () const
returns methodTraits for access to derived class member functions that are not mapped to the top TraitsBase level
bool top_level ()
Return whether the iterator is the top level iterator.
void top_level (bool tflag)
Set the iterator's top level flag.
Protected Member Functions
void pre_run () override
pre-run portion of run (optional); re-implemented by Iterators which can generate all Variables (parameter sets) a priori
void core_run () override
void print_variance_reduction (std::ostream &s) const override
bool discrepancy_sample_counts () const override
flag identifying whether sample counts correspond to level discrepancies
Protected Member Functions inherited from NonDMultilevelSampling
void core_run () override
core portion of run; implemented by all derived classes and may include pre/post steps in lieu of separate pre/post
Real estimator_accuracy_metric () const override
return the scalar optimization metric (objective or constraint) defined from the QoI-vector of estimator variances
void print_variance_reduction (std::ostream &s) const override
void nested_response_mappings (const RealMatrix &primary_coeffs, const RealMatrix &secondary_coeffs) override
set primaryResponseCoefficients, secondaryResponseCoefficients within derived Iterators; Necessary for scalarization case in MLMC NonDMultilevelSampling to map scalarization in nested context
bool discrepancy_sample_counts () const override
flag identifying whether sample counts correspond to level discrepancies
void ml_increments (SizetArray &delta_N_l, String prepend)
evaluate multiple sample batches concurrently, where each batch involves either a single model or model pair
void increment_ml_equivalent_cost (size_t new_N_l, Real lev_cost, Real ref_cost, Real &equiv_hf)
increment the equivalent number of HF evaluations based on new model evaluations
void compute_ml_estimator_variance (const RealMatrix &var_Y, const Sizet2DArray &num_Y, RealVector &ml_est_var)
compute MLMC estimator variance from level QoI variances
void recover_variance (const RealMatrix &moment_stats, RealVector &var_H)
recover variance from raw moments
void initialize_ml_Ysums (IntRealMatrixMap &sum_Y, size_t num_lev, size_t num_mom=4)
initialize the ML accumulators for computing means, variances, and covariances across resolution levels
void initialize_ml_Qsums (IntRealMatrixMap &sum_Ql, IntRealMatrixMap &sum_Qlm1, IntIntPairRealMatrixMap &sum_QlQlm1, size_t num_lev)
initialize the ML accumulators for computing means, variances, and covariances across resolution levels
void accumulate_ml_Ysums (const IntResponseMap &resp_map, IntRealMatrixMap &sum_Y, IntRealMatrixMap &sum_YY, size_t lev, size_t lev_offset, SizetArray &num_Y)
update accumulators for multilevel telescoping running sums using set of model evaluations within allResponses
void accumulate_ml_Ysums (const IntResponseMap &resp_map, IntRealMatrixMap &sum_Y, RealMatrix &sum_YY, size_t lev, size_t lev_offset, SizetArray &num_Y)
update accumulators for multilevel telescoping running sums using set of model evaluations within allResponses
void accumulate_ml_Ysums (const IntResponseMap &resp_map, RealMatrix &sum_Y, RealMatrix &sum_YY, size_t lev, size_t lev_offset, SizetArray &num_Y)
update accumulators for multilevel telescoping running sums using set of model evaluations within allResponses
void accumulate_ml_Qsums (const IntResponseMap &resp_map, IntRealMatrixMap &sum_Q, size_t lev, SizetArray &num_Q)
update running QoI sums for one model (sum_Q) using set of model evaluations within allResponses; used for level 0 from other accumulators
Real variance_Ysum (Real sum_Y, Real sum_YY, size_t Nlq)
compute variance scalar from sum accumulators
void variance_Ysum (const Real *sum_Y, const Real *sum_YY, const SizetArray &N_l, Real *var_Y)
compute variance column vec (all QoI for one level) from sum accumulators
Real variance_Qsum (Real sum_Ql, Real sum_Qlm1, Real sum_QlQl, Real sum_QlQlm1, Real sum_Qlm1Qlm1, size_t Nlq)
compute variance from sum accumulators
Real aggregate_variance_Ysum (const Real *sum_Y, const Real *sum_YY, const SizetArray &N_l)
sum up variances across QoI (using sum_YY with means from sum_Y)
Real aggregate_mse_Yvar (const Real *var_Y, const SizetArray &N_l)
sum up Monte Carlo estimates for mean squared error (MSE) across QoI using discrepancy variances
Real aggregate_mse_Ysum (const Real *sum_Y, const Real *sum_YY, const SizetArray &N_l)
sum up Monte Carlo estimates for mean squared error (MSE) across QoI using discrepancy sums
void ml_Q_raw_moments (const RealMatrix &sum_Hl_1, const RealMatrix &sum_Hlm1_1, const RealMatrix &sum_Hl_2, const RealMatrix &sum_Hlm1_2, const Sizet2DArray &N_actual, size_t start, size_t end, RealMatrix &ml_raw_mom)
accumulate ML-only contributions (levels with no CV) to 2 raw moments
void ml_Y_raw_moments (const RealMatrix &sum_H1, const RealMatrix &sum_H2, const Sizet2DArray &N_l, size_t start, size_t end, RealMatrix &ml_raw_mom)
accumulate ML-only contributions (levels with no CV) to 2 raw moments
void ml_Y_raw_moments (const RealMatrix &sum_H1, const RealMatrix &sum_H2, const RealMatrix &sum_H3, const RealMatrix &sum_H4, const Sizet2DArray &N_l, size_t start, size_t end, RealMatrix &ml_raw_mom)
accumulate ML-only contributions (levels with no CV) to 4 raw moments
void configure_indices (unsigned short group, unsigned short form, size_t lev, short seq_type)
manage response mode and active model key from {group,form,lev} triplet. seq_type defines the active dimension for a 1D model sequence.
void configure_indices (size_t group, size_t form, size_t lev, short seq_type)
convert group and form and call overload
Real level_cost (const RealVector &cost, size_t step, size_t offset=0)
return (aggregate) level cost
Protected Member Functions inherited from NonDHierarchSampling
void ensemble_sample_batch (const String &prepend, int batch_id, bool new_samples=true)
queue a batch of samples to be performed for the active model subset
void ml_active_set (size_t lev, size_t offset=0, bool clear_req=true)
set request = 1 for QoI in (lev-1,lev)
void export_all_samples (String root_prepend, const Model &model, size_t iter, int batch_id)
export allSamples to tagged tabular file
Protected Member Functions inherited from NonDEnsembleSampling
virtual Real inactive_budget_deduction () const
compute the deduction in available budget for optimal allocation, generally any sunk pilot cost for deactivated groups/models
virtual void print_multimodel_summary (std::ostream &s, const String &summary_type, bool projections)
virtual void print_multigroup_summary (std::ostream &s, const String &summary_type, bool projections) const
void post_run (std::ostream &s) override
post-run portion of run (optional); verbose to print results; re-implemented by Iterators that can read all Variables/Responses and perform final analysis phase in a standalone way
void print_results (std::ostream &s, short results_state=FINAL_RESULTS) override
print the final iterator results
void initialize_final_statistics () override
initializes finalStatistics for storing NonD final results
void update_final_statistics () override
update finalStatistics::functionValues
bool seed_updated () override
void active_set_mapping () override
in the case of sub-iteration, map from finalStatistics.active_set() requests to activeSet used in evaluate_parameter_sets()
Real active_budget () const
return the amount of budget available for optimal allocation, generally maxFunctionEvals minus any deductions
void recover_online_cost (const IntResponseMap &all_resp)
recover estimates of simulation cost using aggregated response metadata spanning one batch of samples
void recover_online_cost (const IntIntResponse2DMap &batch_resp_map)
recover estimates of simulation cost using aggregated response metadata spanning multiple batches of samples
void check_cost_options (const BitArray &cost_specs, const SizetSizetPairArray &cost_md_indices, short seq_type)
enforce either a user cost specification or online cost recovery for each ACTIVE model within the sequence type
Real estimator_cost_metric () const
return cost metric for entry into finalStatistics
void assign_specification_sequence (size_t index)
advance any sequence specifications
int seed_sequence (size_t index)
extract current random seed from randomSeedSeqSpec
void resize_active_set ()
synchronize activeSet with iteratedModel's response size
void increment_samples (SizetArray &N_l, size_t incr)
increment samples array with a shared scalar
void increment_samples (SizetArray &N_l, const SizetArray &incr)
increment samples array with a shared scalar
void increment_samples (Sizet2DArray &N_l, const SizetArray &incr)
increment 2D samples array with a shared 1D array (additional dim is QoI)
void increment_sums (Real *sum_l, const Real *incr, size_t len)
increment samples array with a shared scalar
void compute_mc_estimator_variance (const RealVector &var_l, const SizetArray &N_l, RealVector &mc_est_var)
compute the variance of the mean estimator (Monte Carlo sample average)
void project_mc_estimator_variance (const RealVector &var_l, const SizetArray &N_l, size_t new_samp, RealVector &mc_est_var)
compute the variance of the mean estimator (Monte Carlo sample average) after projection with additional samples (var_l remains fixed)
void reset_relaxation ()
initialize relaxFactor prior to iteration
void advance_relaxation ()
update relaxFactor based on iteration number
void compute_mf_control (Real sum_L, Real sum_H, Real sum_LL, Real sum_LH, size_t N_shared, Real &beta)
compute scalar control variate parameters
void export_all_samples (const Model &model, const String &tabular_filename)
export allSamples to tagged tabular file
void convert_moments (const RealMatrix &raw_mom, RealMatrix &final_mom)
convert uncentered raw moments (multilevel expectations) to standardized moments
void uncentered_to_centered (const RealMatrix &raw_mom, RealMatrix &cent_mom)
convert uncentered (raw) moments to centered moments; biased estimators
void centered_to_standard (const RealMatrix &cent_mom, RealMatrix &std_mom)
convert centered moments to standardized moments
bool valid_variance (Real estvar) const
check for valid values for (estimator) variance
bool valid_variances (const RealVector &estvar) const
check for valid values for vectir of (estimator) variances
void compute_mean_confidence_intervals (const RealMatrix &moment_stats, const RealVector &mean_estvar, RealMatrix &mean_conf_ints)
compute 95% confidence intervals for mean estimator
Protected Member Functions inherited from NonDSampling
NonDSampling (ProblemDescDB &problem_db, std::shared_ptr< Model > model)
constructor
NonDSampling (unsigned short method_name, std::shared_ptr< Model > model, unsigned short sample_type, size_t samples, int seed, const String &rng, bool vary_pattern, short sampling_vars_mode)
alternate constructor for sample generation and evaluation "on the fly"
NonDSampling (unsigned short sample_type, size_t samples, int seed, const String &rng, const RealVector &lower_bnds, const RealVector &upper_bnds)
alternate constructor for sample generation "on the fly"
NonDSampling (unsigned short sample_type, size_t samples, int seed, const String &rng, const RealVector &means, const RealVector &std_devs, const RealVector &lower_bnds, const RealVector &upper_bnds, RealSymMatrix &correl)
alternate constructor for sample generation of correlated normals "on the fly"
void pre_run () override
pre-run portion of run (optional); re-implemented by Iterators which can generate all Variables (parameter sets) a priori
void core_run () override
size_t num_samples () const override
void sampling_reset (size_t min_samples, bool all_data_flag, bool stats_flag) override
resets number of samples and sampling flags
void sampling_reference (size_t samples_ref) override
set reference number of samples, which is a lower bound during reset
void random_seed (int seed) override
assign randomSeed
void vary_pattern (bool pattern_flag) override
set varyPattern
void get_parameter_sets (std::shared_ptr< Model > model) override
Uses samplerDriver to generate a set of samples from the distributions/bounds defined in the incoming model.
void get_parameter_sets (std::shared_ptr< Model > model, const size_t num_samples, RealMatrix &design_matrix) override
Uses samplerDriver to generate a set of samples from the distributions/bounds defined in the incoming model and populates the specified design matrix.
void get_parameter_sets (std::shared_ptr< Model > model, const size_t num_samples, RealMatrix &design_matrix, bool write_msg)
core of get_parameter_sets that accepts message print control
void get_parameter_sets (const RealVector &lower_bnds, const RealVector &upper_bnds)
Uses samplerDriver to generate a set of uniform samples over lower_bnds/upper_bnds.
void get_parameter_sets (const RealVector &means, const RealVector &std_devs, const RealVector &lower_bnds, const RealVector &upper_bnds, RealSymMatrix &correl)
Uses samplerDriver to generate a set of normal samples.
void update_model_from_sample (Model &model, const Real *sample_vars) override
Override default update of continuous vars only.
void sample_to_variables (const Real *sample_vars, Variables &vars) override
override default mapping of continuous variables only
void variables_to_sample (const Variables &vars, Real *sample_vars) override
override default mapping of continuous variables only
const RealSymMatrix & response_error_estimates () const override
return error estimates associated with each of the finalStatistics
void initialize_sample_driver (bool write_message, size_t num_samples)
increments numLHSRuns, sets random seed, and initializes samplerDriver
void mode_counts (const Variables &vars, size_t &cv_start, size_t &num_cv, size_t &div_start, size_t &num_div, size_t &dsv_start, size_t &num_dsv, size_t &drv_start, size_t &num_drv) const
compute sampled subsets (all, active, uncertain) within all variables (acv/adiv/adrv) from samplingVarsMode and model
void mode_bits (const Variables &vars, BitArray &active_vars, BitArray &active_corr) const
define subset views for sampling modes
Protected Member Functions inherited from NonD
NonD (ProblemDescDB &problem_db, std::shared_ptr< Model > model)
constructor
NonD (unsigned short method_name, std::shared_ptr< Model >)
alternate constructor for sample generation and evaluation "on the fly"
NonD (unsigned short method_name, std::shared_ptr< Model >, const ShortShortPair &approx_view)
alternate constructor for sample generation and evaluation "on the fly"
NonD (unsigned short method_name, const RealVector &lower_bnds, const RealVector &upper_bnds)
alternate constructor for sample generation "on the fly"
~NonD () override
destructor
void derived_set_communicators (ParLevLIter pl_iter) override
derived class contributions to setting the communicators associated with this Iterator instance
void initialize_run () override
utility function to perform common operations prior to pre_run(); typically memory initialization; setting of instance pointers
void finalize_run () override
utility function to perform common operations following post_run(); deallocation and resetting of instance pointers
const Response & response_results () const override
return the final statistics from the nondeterministic iteration
void response_results_active_set (const ActiveSet &set) override
set the active set within finalStatistics
virtual void initialize_response_covariance ()
initializes respCovariance
void pull_level_mappings (RealVector &level_maps, size_t offset)
concatenate computed{Resp,Prob,Rel,GenRel}Levels into level_maps
void push_level_mappings (const RealVector &level_maps, size_t offset)
update computed{Resp,Prob,Rel,GenRel}Levels from level_maps
void configure_1d_sequence (size_t &num_steps, size_t &secondary_index, short &seq_type)
configure a one-dimensional hierarchical sequence (ML or MF)
void configure_2d_sequence (size_t &num_steps, size_t &secondary_index, short &seq_type)
configure a two-dimensional hierarchical sequence (MLMF)
void configure_enumeration (size_t &num_combinations, short &seq_type)
configure the total number of model form/resolution level options
short configure_cost (size_t num_steps, short seq_type, RealVector &cost)
extract cost estimates from model ensemble, enforcing requirements (case without metadata support)
short configure_cost (size_t num_steps, short seq_type, RealVector &cost, SizetSizetPairArray &cost_md_indices)
extract cost estimates from model ensemble, enforcing requirements (case with metadata support)
short query_cost (size_t num_steps, short seq_type, RealVector &cost)
optionally extract cost estimates from model ensemble, if available (case without metadata support)
short query_cost (size_t num_steps, short seq_type, RealVector &cost, BitArray &model_cost_spec, const SizetSizetPairArray &cost_md_indices)
optionally extract cost estimates from model ensemble, if available (case with metadata support)
void test_cost (short seq_type, const BitArray &model_cost_spec, SizetSizetPairArray &cost_md_indices)
check cost specification and metadata indices for each active model
bool test_cost (bool cost_spec, SizetSizetPair &cost_md_indices, const String &model_id)
check cost specification and metadata indices for a given model
bool valid_cost (Real cost) const
test cost for value > 0
bool valid_costs (const RealVector &costs) const
test costs for valid values > 0
void load_pilot_sample (const SizetArray &pilot_spec, size_t num_steps, SizetArray &delta_N_l)
distribute pilot sample specification across model forms or levels
void load_pilot_sample (const SizetArray &pilot_spec, short seq_type, const Sizet3DArray &N_l, Sizet2DArray &delta_N_l)
distribute pilot sample specification across model forms and levels
template<typename ArrayType >
void inflate_approx_samples (const ArrayType &N_l, bool multilev, size_t secondary_index, std::vector< ArrayType > &N_l_vec)
update the relevant slice of N_l_3D from the final 2D multilevel or 2D multifidelity sample profile
template<typename ArrayType >
void inflate_sequence_samples (const ArrayType &N_l, bool multilev, size_t secondary_index, std::vector< ArrayType > &N_l_vec)
update the relevant slice of N_l_3D from the final 2D multilevel or 2D multifidelity sample profile
void resize_final_statistics_gradients ()
resizes finalStatistics::functionGradients based on finalStatistics ASV
void update_aleatory_final_statistics ()
update finalStatistics::functionValues from momentStats and computed{Prob,Rel,GenRel,Resp}Levels
void update_system_final_statistics ()
update system metrics from component metrics within finalStatistics
void update_system_final_statistics_gradients ()
update finalStatistics::functionGradients
void initialize_level_mappings ()
size computed{Resp,Prob,Rel,GenRel}Levels
void compute_densities (const RealRealPairArray &min_max_fns, bool prob_refinement=false, bool all_levels_computed=false)
compute the PDF bins from the CDF/CCDF values and store in computedPDF{Abscissas,Ordinates}
void print_densities (std::ostream &s) const
output the PDFs reflected in computedPDF{Abscissas,Ordinates} using default qoi_type and pdf_labels
void print_densities (std::ostream &s, String qoi_type, const StringArray &pdf_labels) const
output the PDFs reflected in computedPDF{Abscissas,Ordinates}
void print_system_mappings (std::ostream &s) const
print system series/parallel mappings for response levels
void print_multilevel_evaluation_summary (std::ostream &s, const SizetArray &N_m) const
print evaluation summary for multilevel sampling across 1D level profile
void print_multilevel_evaluation_summary (std::ostream &s, const Sizet2DArray &N_m) const
print evaluation summary for multilevel sampling across 2D level+QoI profile
void print_multilevel_discrepancy_summary (std::ostream &s, const SizetArray &N_m) const
print evaluation summary for multilevel sampling across 1D level profile for discrepancy across levels
void print_multilevel_discrepancy_summary (std::ostream &s, const SizetArray &N_m, const SizetArray &N_mp1) const
print evaluation summary for multilevel sampling across 1D level profile for discrepancy across model forms
void print_multilevel_discrepancy_summary (std::ostream &s, const Sizet2DArray &N_m) const
print evaluation summary for multilevel sampling across 2D level+QoI profile for discrepancy across levels
void print_multilevel_discrepancy_summary (std::ostream &s, const Sizet2DArray &N_m, const Sizet2DArray &N_mp1) const
print evaluation summary for multilevel sampling across 2D level+QoI profile for discrepancy across model forms
template<typename ArrayType >
void print_multilevel_model_summary (std::ostream &s, const std::vector< ArrayType > &N_samp, String type, short seq_type, bool discrep_flag)
print evaluation summary for multilevel sampling across 2D model+level profile (allocations) or 3D model+level+QoI profile (actual)
void construct_lhs (std::shared_ptr< Iterator > &u_space_sampler, std::shared_ptr< Model > u_model, unsigned short sample_type, int num_samples, int seed, const String &rng, bool vary_pattern, short sampling_vars_mode=ACTIVE)
assign a NonDLHSSampling instance within u_space_sampler
unsigned short sub_optimizer_select (unsigned short requested_sub_method, unsigned short default_sub_method=SUBMETHOD_NPSOL)
utility for vetting sub-method request against optimizers within the package configuration
size_t one_sided_relax_round (Real diff, Real relax_factor=1.)
compute a one-sided sample increment for multilevel methods to move current sampling level to a new target
size_t one_sided_delta (Real current, Real target, Real relax_factor=1.)
compute a one-sided sample increment for multilevel methods to move current sampling level to a new target
size_t one_sided_delta (const SizetArray &current, const RealVector &targets, Real relax_factor=1., size_t power=1)
compute a one-sided sample increment for multilevel methods to move current sampling level to a new target
size_t one_sided_delta (const SizetArray &current, Real target, Real relax_factor=1., size_t power=1)
compute a one-sided sample increment for multilevel methods to move current sampling level to a new target
void one_sided_delta (const SizetArray &current, const RealVector &targets, SizetArray &delta_N, Real relax_factor=1.)
compute a one-sided sample increment vector to move current sampling levels to new targets
void one_sided_delta (const Sizet2DArray &current, const RealVector &targets, SizetArray &delta_N, Real relax_factor=1.)
compute a one-sided sample increment vector to move current sampling levels to new targets
bool differ (size_t N_alloc_ij, const SizetArray &N_actual_ij) const
return true if fine-grained reporting differs from coarse-grained
bool differ (const SizetArray &N_alloc_i, const Sizet2DArray &N_actual_i) const
return true if fine-grained reporting differs from coarse-grained
bool differ (const Sizet2DArray &N_alloc, const Sizet3DArray &N_actual) const
return true if fine-grained reporting differs from coarse-grained
void archive_allocate_mappings ()
allocate results array storage for distribution mappings
void archive_from_resp (size_t fn_index, size_t inc_id=0)
archive the mappings from specified response levels for specified fn
void archive_to_resp (size_t fn_index, size_t inc_id=0)
archive the mappings to computed response levels for specified fn and (optional) increment id.
void archive_allocate_pdf ()
allocate results array storage for pdf histograms
void archive_pdf (size_t fn_index, size_t inc_id=0)
archive a single pdf histogram for specified function
void archive_equiv_hf_evals (const Real equiv_hf_evals)
archive the equivalent number of HF evals (used by ML/MF methods)
bool zeros (const SizetArray &N_m) const
return true if N_m is empty or only populated with zeros
bool zeros (const Sizet2DArray &N_m) const
return true if N_m is empty or only populated with zeros
bool zeros (const SizetVector &N_m) const
return true if N_m is empty or only populated with zeros
bool homogeneous (const SizetArray &N_l) const
return true if N_l has consistent values
Protected Member Functions inherited from Analyzer
Analyzer ()
default constructor
Analyzer (ProblemDescDB &problem_db, std::shared_ptr< Model > model)
standard constructor
Analyzer (unsigned short method_name, std::shared_ptr< Model > model)
alternate constructor for instantiations "on the fly" with a Model
Analyzer (unsigned short method_name, std::shared_ptr< Model > model, const ShortShortPair &view_override)
alternate constructor for instantiations "on the fly" with a Model
Analyzer (unsigned short method_name)
alternate constructor for instantiations "on the fly" without a Model
~Analyzer () override
destructor
virtual void update_model_from_variables (Model &model, const Variables &vars)
update model's current variables with data from vars
void update_from_model (const Model &model) override
set inherited data attributes based on extractions from incoming model
void pre_output () override
std::shared_ptr< Model > algorithm_space_model () override
const Variables & variables_results () const override
return a single final iterator solution (variables)
const VariablesArray & variables_array_results () override
return multiple final iterator solutions (variables). This should only be used if returns_multiple_points() returns true.
const ResponseArray & response_array_results () override
return multiple final iterator solutions (response). This should only be used if returns_multiple_points() returns true.
bool compact_mode () const override
returns Analyzer::compactMode
bool returns_multiple_points () const override
indicates if this iterator returns multiple final points. Default return is false. Override to return true if appropriate.
void evaluate_parameter_sets (Model &model, bool log_resp_flag=true, bool log_best_flag=false)
perform function evaluations to map parameter sets (allVariables) into response sets (allResponses)
void evaluate_batch (Model &model, int batch_id, bool log_best_flag=false)
perform function evaluations to map a keyed batch of parameter sets (batchVariablesMap[key]) into a corresponding batch of response sets (batchResponsesMap[key])
const IntIntResponse2DMap & synchronize_batches (Model &model, bool log_best_flag=false)
perform function evaluations to map a keyed batch of parameter sets (batchVariablesMap[key]) into a corresponding batch of response sets (batchResponsesMap[key])
void clear_batches ()
since synchronize returns the aggregation of all evaluated batches, we use a separate call to indicate when processing of this data is complete and bookkeeping can be cleared
void get_vbd_parameter_sets (std::shared_ptr< Model > model, size_t num_samples)
generate replicate parameter sets for use in variance-based decomposition
virtual void archive_model_variables (const Model &, size_t idx) const
archive model evaluation points
virtual void archive_model_response (const Response &, size_t idx) const
archive model evaluation responses
void read_variables_responses (int num_evals, size_t num_vars)
convenience function for reading variables/responses (used in derived classes post_input)
void samples_to_variables_array (const RealMatrix &sample_matrix, VariablesArray &vars_array)
convert samples array to variables array; e.g., allSamples to allVariables
void variables_array_to_samples (const VariablesArray &vars_array, RealMatrix &sample_matrix)
convert variables array to samples array; e.g., allVariables to allSamples
Protected Member Functions inherited from Iterator
Iterator (ProblemDescDB &problem_db, std::shared_ptr< TraitsBase > traits=std::shared_ptr< TraitsBase >(new TraitsBase()))
constructor initializes the base class part of letter classes (BaseConstructor overloading avoids infinite recursion in the derived class constructors - Coplien, p. 139)
Iterator (unsigned short method_name, std::shared_ptr< Model > model, std::shared_ptr< TraitsBase > traits=std::shared_ptr< TraitsBase >(new TraitsBase()))
alternate constructor for base iterator classes constructed on the fly
Iterator (unsigned short method_name, std::shared_ptr< TraitsBase > traits=std::shared_ptr< TraitsBase >(new TraitsBase()))
alternate constructor for base iterator classes constructed on the fly
Iterator (std::shared_ptr< Model > model, size_t max_iter, size_t max_eval, Real conv_tol, std::shared_ptr< TraitsBase > traits=std::shared_ptr< TraitsBase >(new TraitsBase()))
alternate envelope constructor for instantiations without ProblemDescDB
virtual void derived_init_communicators (ParLevLIter pl_iter)
derived class contributions to initializing the communicators associated with this Iterator instance
virtual const VariablesArray & initial_points () const
gets the multiple initial points for this iterator. This will only be meaningful after a call to initial_points mutator.
StrStrSizet run_identifier () const
get the unique run identifier based on method name, id, and number of executions
void initialize_model_graphics (Model &model, int iterator_server_id)
helper function that encapsulates initialization operations, modular on incoming Model instance
void export_final_surrogates (Model &data_fit_surr_model)
export final surrogates generated, e.g., GP in EGO and friends
Private Member Functions
void multilevel_control_variate_mc_online_pilot ()
Perform multilevel Monte Carlo across levels in combination with control variate Monte Carlo across model forms at each level; CV computes correlations for Q (LH correlations for QoI)
void multilevel_control_variate_mc_offline_pilot ()
Qcorr approach using a pilot sample treated as separate offline cost.
void multilevel_control_variate_mc_pilot_projection ()
Qcorr approach projecting estimator performance from a pilot sample.
void assign_active_key ()
define the truth and surrogate keys
void evaluate_levels (IntRealMatrixMap &sum_Ll_pilot, IntRealMatrixMap &sum_Llm1_pilot, IntRealMatrixMap &sum_Hl_pilot, IntRealMatrixMap &sum_Hlm1_pilot, IntRealMatrixMap &sum_Ll_Ll_pilot, IntRealMatrixMap &sum_Ll_Llm1_pilot, IntRealMatrixMap &sum_Llm1_Llm1_pilot, IntRealMatrixMap &sum_Hl_Ll_pilot, IntRealMatrixMap &sum_Hl_Llm1_pilot, IntRealMatrixMap &sum_Hlm1_Ll_pilot, IntRealMatrixMap &sum_Hlm1_Llm1_pilot, IntRealMatrixMap &sum_Hl_Hl_pilot, IntRealMatrixMap &sum_Hl_Hlm1_pilot, IntRealMatrixMap &sum_Hlm1_Hlm1_pilot, RealVectorArray &eval_ratios, RealMatrix &Lambda, RealMatrix &var_YH, Real &eps_sq_div_2, SizetArray &delta_N_hf, Sizet2DArray &N_actual, SizetArray &N_alloc, RealVector &hf_targets, bool accumulate_cost, bool pilot_estvar)
helper for shared code among online and offline pilot modes
void evaluate_pilot (RealVectorArray &eval_ratios, RealMatrix &Lambda, RealMatrix &var_YH, Real &eps_sq_div_2, Sizet2DArray &N_actual, SizetArray &N_alloc, RealVector &hf_targets, RealMatrix &pilot_mom, bool accumulate_cost, bool pilot_estvar)
helper for shared code among pilot-projection modes
void mlmf_increments (const SizetArray &delta_N_l, String prepend)
evaluate multiple sample batches concurrently, where each batch involves either a single level or level pair for both HF and LF models
template<typename SumContainer1 , typename SumContainer2 >
void accumulate_increments (const SizetArray &delta_N_hf, Sizet2DArray &N_actual, SizetArray &N_alloc, const RealVector &hf_targets, SumContainer1 &sum_Ll, SumContainer1 &sum_Llm1, SumContainer2 &sum_Hl, SumContainer2 &sum_Hlm1, SumContainer1 &sum_Ll_Ll, SumContainer1 &sum_Ll_Llm1, SumContainer1 &sum_Llm1_Llm1, SumContainer1 &sum_Hl_Ll, SumContainer1 &sum_Hl_Llm1, SumContainer1 &sum_Hlm1_Ll, SumContainer1 &sum_Hlm1_Llm1, SumContainer1 &sum_Hl_Hl, SumContainer1 &sum_Hl_Hlm1, SumContainer1 &sum_Hlm1_Hlm1, bool incr_cost)
accumulate sample values for multiple sample batches coming from mlmf_increments()
template<typename SumContainer1 , typename SumContainer2 >
void compute_allocations (RealVectorArray &eval_ratios, RealMatrix &Lambda, RealMatrix &var_YH, Real &eps_sq_div_2, SizetArray &delta_N_hf, Sizet2DArray &N_actual, SizetArray &N_alloc, RealVector &hf_targets, bool accumulate_cost, bool pilot_estvar, SumContainer1 &sum_Ll, SumContainer1 &sum_Llm1, SumContainer2 &sum_Hl, SumContainer2 &sum_Hlm1, SumContainer1 &sum_Ll_Ll, SumContainer1 &sum_Ll_Llm1, SumContainer1 &sum_Llm1_Llm1, SumContainer1 &sum_Hl_Ll, SumContainer1 &sum_Hl_Llm1, SumContainer1 &sum_Hlm1_Ll, SumContainer1 &sum_Hlm1_Llm1, SumContainer1 &sum_Hl_Hl, SumContainer1 &sum_Hl_Hlm1, SumContainer1 &sum_Hlm1_Hlm1)
helper to compute allocations based on sample accumulations
void lf_increments (const SizetArray &delta_N_lf, String prepend)
evaluate multiple sample batches concurrently, where each batch involves either a single level or level pair for the LF model
template<typename SumContainer >
void accumulate_lf_increments (const SizetArray &delta_N_lf, Sizet2DArray &N_actual_lf, SizetArray &N_alloc_lf, const RealVectorArray &lf_targets, SumContainer &sum_Ll_refined, SumContainer &sum_Llm1_refined)
accumulate sample values for multiple sample batches coming from lf_increments()
size_t lf_increment (const RealVector &eval_ratios, const SizetArray &N_lf, Real hf_target, RealVector &lf_targets)
compute a LF sample increment as indicated by evaluation ratios
size_t lf_increment (const RealVector &eval_ratios, size_t N_lf, Real hf_target, RealVector &lf_targets)
compute a LF sample increment as indicated by evaluation ratios
Real compute_mlmf_equivalent_cost (const SizetArray &raw_N_hf, const RealVector &hf_cost, const SizetArray &raw_N_lf, const RealVector &lf_cost)
compute the equivalent number of HF evaluations (includes any sim faults)
void increment_mlmf_equivalent_cost (size_t new_N_hf, Real hf_lev_cost, size_t new_N_lf, Real lf_lev_cost, Real hf_ref_cost, Real &equiv_hf)
increment the equivalent number of HF evaluations
void compute_mlmf_estimator_variance (const RealMatrix &var_Y, const Sizet2DArray &num_Y, const RealMatrix &Lambda, RealVector &mlmf_est_var)
compute the variance of the MLMF estimator
void compute_eval_ratios (RealMatrix &sum_L_shared, RealMatrix &sum_H, RealMatrix &sum_LL, RealMatrix &sum_LH, RealMatrix &sum_HH, Real cost_ratio, size_t lev, const SizetArray &N_shared, RealMatrix &var_H, RealMatrix &rho2_LH, RealVector &eval_ratios)
compute the LF/HF evaluation ratio, averaged over the QoI
void compute_eval_ratios (RealMatrix &sum_Ll, RealMatrix &sum_Llm1, RealMatrix &sum_Hl, RealMatrix &sum_Hlm1, RealMatrix &sum_Ll_Ll, RealMatrix &sum_Ll_Llm1, RealMatrix &sum_Llm1_Llm1, RealMatrix &sum_Hl_Ll, RealMatrix &sum_Hl_Llm1, RealMatrix &sum_Hlm1_Ll, RealMatrix &sum_Hlm1_Llm1, RealMatrix &sum_Hl_Hl, RealMatrix &sum_Hl_Hlm1, RealMatrix &sum_Hlm1_Hlm1, Real cost_ratio, size_t lev, const SizetArray &N_shared, RealMatrix &var_YHl, RealMatrix &rho_dot2_LH, RealVector &eval_ratios)
compute the LF/HF evaluation ratio, averaged over the QoI
void compute_eval_ratios (RealMatrix &sum_Ll, RealMatrix &sum_Llm1, IntRealMatrixMap &sum_Hl, IntRealMatrixMap &sum_Hlm1, RealMatrix &sum_Ll_Ll, RealMatrix &sum_Ll_Llm1, RealMatrix &sum_Llm1_Llm1, RealMatrix &sum_Hl_Ll, RealMatrix &sum_Hl_Llm1, RealMatrix &sum_Hlm1_Ll, RealMatrix &sum_Hlm1_Llm1, RealMatrix &sum_Hl_Hl, RealMatrix &sum_Hl_Hlm1, RealMatrix &sum_Hlm1_Hlm1, Real cost_ratio, size_t lev, const SizetArray &N_shared, RealMatrix &var_YHl, RealMatrix &rho_dot2_LH, RealVector &eval_ratios)
compute the LF/HF evaluation ratio, averaged over the QoI
void compute_eval_ratios (IntRealMatrixMap &sum_Ll, IntRealMatrixMap &sum_Llm1, IntRealMatrixMap &sum_Hl, IntRealMatrixMap &sum_Hlm1, IntRealMatrixMap &sum_Ll_Ll, IntRealMatrixMap &sum_Ll_Llm1, IntRealMatrixMap &sum_Llm1_Llm1, IntRealMatrixMap &sum_Hl_Ll, IntRealMatrixMap &sum_Hl_Llm1, IntRealMatrixMap &sum_Hlm1_Ll, IntRealMatrixMap &sum_Hlm1_Llm1, IntRealMatrixMap &sum_Hl_Hl, IntRealMatrixMap &sum_Hl_Hlm1, IntRealMatrixMap &sum_Hlm1_Hlm1, Real cost_ratio, size_t lev, const SizetArray &N_shared, RealMatrix &var_YHl, RealMatrix &rho_dot2_LH, RealVector &eval_ratios)
compute the LF/HF evaluation ratio, averaged over the QoI
void compute_mf_correlation (Real sum_L, Real sum_H, Real sum_LL, Real sum_LH, Real sum_HH, size_t N_shared, Real &var_H, Real &rho2_LH)
compute scalar variance and correlation parameters for control variates
void variance_Ysum (IntRealMatrixMap &sum_Hl, IntRealMatrixMap &sum_Hl_Hl, const Sizet2DArray &N_actual, RealMatrix &var_YH, size_t lev)
roll up HF level variances from sums
void variance_Ysum (IntRealMatrixMap &sum_Hl, RealMatrix &sum_Hl_Hl, const Sizet2DArray &N_actual, RealMatrix &var_YH, size_t lev)
roll up HF level variances from sums
void cv_raw_moments (IntRealMatrixMap &sum_Ll, IntRealMatrixMap &sum_Llm1, IntRealMatrixMap &sum_Hl, IntRealMatrixMap &sum_Hlm1, IntRealMatrixMap &sum_Ll_Ll, IntRealMatrixMap &sum_Ll_Llm1, IntRealMatrixMap &sum_Llm1_Llm1, IntRealMatrixMap &sum_Hl_Ll, IntRealMatrixMap &sum_Hl_Llm1, IntRealMatrixMap &sum_Hlm1_Ll, IntRealMatrixMap &sum_Hlm1_Llm1, IntRealMatrixMap &sum_Hl_Hl, IntRealMatrixMap &sum_Hl_Hlm1, IntRealMatrixMap &sum_Hlm1_Hlm1, const SizetArray &N_shared, IntRealMatrixMap &sum_Ll_refined, IntRealMatrixMap &sum_Llm1_refined, const SizetArray &N_refined, size_t lev, RealMatrix &H_raw_mom)
apply control variate parameters for MLMF MC to estimate raw moment contributions
void compute_mf_controls (const Real *sum_L, const Real *sum_H, const Real *sum_LL, const Real *sum_LH, const SizetArray &N_shared, RealVector &beta)
compute control variate parameters for pointer
void compute_mlmf_controls (IntRealMatrixMap &sum_Ll, IntRealMatrixMap &sum_Llm1, IntRealMatrixMap &sum_Hl, IntRealMatrixMap &sum_Hlm1, IntRealMatrixMap &sum_Ll_Ll, IntRealMatrixMap &sum_Ll_Llm1, IntRealMatrixMap &sum_Llm1_Llm1, IntRealMatrixMap &sum_Hl_Ll, IntRealMatrixMap &sum_Hl_Llm1, IntRealMatrixMap &sum_Hlm1_Ll, IntRealMatrixMap &sum_Hlm1_Llm1, IntRealMatrixMap &sum_Hl_Hl, IntRealMatrixMap &sum_Hl_Hlm1, IntRealMatrixMap &sum_Hlm1_Hlm1, const Sizet2DArray &N_shared, size_t num_cv_lev, RealVector2DArray &beta_2d, RealVector2DArray &gamma_2d)
compute control variate parameters for all moments, levels, qoi
void compute_mlmf_controls (const Real *sum_Ll_m, const Real *sum_Llm1_m, const Real *sum_Hl_m, const Real *sum_Hlm1_m, const Real *sum_Ll_Ll_m, const Real *sum_Ll_Llm1_m, const Real *sum_Llm1_Llm1_m, const Real *sum_Hl_Ll_m, const Real *sum_Hl_Llm1_m, const Real *sum_Hlm1_Ll_m, const Real *sum_Hlm1_Llm1_m, const Real *sum_Hl_Hl_m, const Real *sum_Hl_Hlm1_m, const Real *sum_Hlm1_Hlm1_m, const SizetArray &N_shared, RealVector &beta_dot, RealVector &gamma)
compute control variate parameters for all QoI (given moment, level)
void compute_mlmf_control (Real sum_Ll, Real sum_Llm1, Real sum_Hl, Real sum_Hlm1, Real sum_Ll_Ll, Real sum_Ll_Llm1, Real sum_Llm1_Llm1, Real sum_Hl_Ll, Real sum_Hl_Llm1, Real sum_Hlm1_Ll, Real sum_Hlm1_Llm1, Real sum_Hl_Hl, Real sum_Hl_Hlm1, Real sum_Hlm1_Hlm1, size_t N_shared, Real &var_YHl, Real &rho_dot2_LH, Real &beta_dot, Real &gamma)
compute scalar control variate parameters
void apply_mf_control (Real sum_H, Real sum_L_shared, size_t N_shared, Real sum_L_refined, size_t N_refined, Real beta, Real &H_raw_mom)
apply scalar control variate parameter (beta) to approximate HF moment
void apply_mf_controls (const Real *sum_H, const Real *sum_L_shared, const SizetArray &N_shared, const Real *sum_L_refined, const SizetArray &N_refined, const RealVector &beta, RealMatrix &H_raw_mom, int m_index)
apply matrix control variate parameter (beta) to approximate HF moment
void apply_mlmf_controls (IntRealMatrixMap &sum_Ll, IntRealMatrixMap &sum_Llm1, IntRealMatrixMap &sum_Hl, IntRealMatrixMap &sum_Hlm1, const Sizet2DArray &N_shared, IntRealMatrixMap &sum_Ll_refined, IntRealMatrixMap &sum_Llm1_refined, const Sizet2DArray &N_refined, size_t num_cv_lev, const RealVector2DArray &beta_2d, const RealVector2DArray &gamma_2d, RealMatrix &H_raw_mom)
apply control variate parameter (beta) for all moments, levels, qoi
void apply_mlmf_controls (const Real *sum_Hl, const Real *sum_Hlm1, const Real *sum_Ll, const Real *sum_Llm1, const SizetArray &N_shared, const Real *sum_Ll_refined, const Real *sum_Llm1_refined, const SizetArray &N_refined, const RealVector &beta_dot, const RealVector &gamma, RealMatrix &H_raw_mom, int m_index)
apply control variate parameters for all QoI (given moment, level)
void apply_mlmf_control (Real sum_Hl, Real sum_Hlm1, Real sum_Ll, Real sum_Llm1, size_t N_shared, Real sum_Ll_refined, Real sum_Llm1_refined, size_t N_refined, Real beta_dot, Real gamma, Real &H_raw_mom)
apply scalar control variate parameter (beta) to approximate HF moment
void update_projected_samples (const RealVector &hf_targets, const RealVectorArray &eval_ratios, const Sizet2DArray &N_actual_hf, SizetArray &N_alloc_hf, const Sizet2DArray &N_actual_lf, SizetArray &N_alloc_lf, SizetArray &delta_N_actual_hf, Real &delta_equiv_hf)
for pilot projection mode, advance sample counts and accumulated cost
void update_projected_lf_samples (const RealVector &hf_targets, const RealVectorArray &eval_ratios, const Sizet2DArray &N_actual_lf, SizetArray &N_alloc_lf, Real &delta_equiv_hf)
for pilot projection mode, advance sample counts and accumulated cost
void initialize_mlmf_sums (IntRealMatrixMap &sum_Ll, IntRealMatrixMap &sum_Llm1, IntRealMatrixMap &sum_Hl, IntRealMatrixMap &sum_Hlm1, IntRealMatrixMap &sum_Ll_Ll, IntRealMatrixMap &sum_Ll_Llm1, IntRealMatrixMap &sum_Llm1_Llm1, IntRealMatrixMap &sum_Hl_Ll, IntRealMatrixMap &sum_Hl_Llm1, IntRealMatrixMap &sum_Hlm1_Ll, IntRealMatrixMap &sum_Hlm1_Llm1, IntRealMatrixMap &sum_Hl_Hl, IntRealMatrixMap &sum_Hl_Hlm1, IntRealMatrixMap &sum_Hlm1_Hlm1, size_t num_ml_lev, size_t num_cv_lev, size_t num_mom=4)
initialize the MLMF accumulators for computing means, variances, and covariances across fidelity levels
void accumulate_mlmf_Qsums (const IntResponseMap &resp_map, IntRealMatrixMap &sum_Ql, IntRealMatrixMap &sum_Qlm1, size_t lev, SizetArray &num_Q)
update running QoI sums for one model at two levels (sum_Ql, sum_Qlm1) using set of model evaluations within allResponses
void accumulate_mlmf_Qsums (const IntResponseMap &mlmf_resp_map, IntRealMatrixMap &sum_L_shared, IntRealMatrixMap &sum_H, IntRealMatrixMap &sum_LL, IntRealMatrixMap &sum_LH, IntRealMatrixMap &sum_HH, size_t lev, SizetArray &N_shared)
update running QoI sums for two models (sum_L, sum_H, sum_LL, sum_LH, and sum_HH) from set of low/high fidelity model evaluations within mlmf_resp_map; used for level 0 from other accumulators
void accumulate_mlmf_Qsums (const IntResponseMap &mlmf_resp_map, IntRealMatrixMap &sum_Ll, IntRealMatrixMap &sum_Llm1, IntRealMatrixMap &sum_Hl, IntRealMatrixMap &sum_Hlm1, IntRealMatrixMap &sum_Ll_Ll, IntRealMatrixMap &sum_Ll_Llm1, IntRealMatrixMap &sum_Llm1_Llm1, IntRealMatrixMap &sum_Hl_Ll, IntRealMatrixMap &sum_Hl_Llm1, IntRealMatrixMap &sum_Hlm1_Ll, IntRealMatrixMap &sum_Hlm1_Llm1, IntRealMatrixMap &sum_Hl_Hl, IntRealMatrixMap &sum_Hl_Hlm1, IntRealMatrixMap &sum_Hlm1_Hlm1, size_t lev, SizetArray &N_shared)
update running QoI sums for two models and two levels from set of low/high fidelity model evaluations within mlmf_resp_map
void accumulate_mlmf_Qsums (const IntResponseMap &mlmf_resp_map, RealMatrix &sum_L_shared, IntRealMatrixMap &sum_H, RealMatrix &sum_LL, RealMatrix &sum_LH, RealMatrix &sum_HH, size_t lev, SizetArray &N_shared)
update running QoI sums for two models (sum_L, sum_H, sum_LL, sum_LH, and sum_HH) from set of low/high fidelity model evaluations within mlmf_resp_map; used for level 0 from other accumulators
void accumulate_mlmf_Qsums (const IntResponseMap &mlmf_resp_map, RealMatrix &sum_Ll, RealMatrix &sum_Llm1, IntRealMatrixMap &sum_Hl, IntRealMatrixMap &sum_Hlm1, RealMatrix &sum_Ll_Ll, RealMatrix &sum_Ll_Llm1, RealMatrix &sum_Llm1_Llm1, RealMatrix &sum_Hl_Ll, RealMatrix &sum_Hl_Llm1, RealMatrix &sum_Hlm1_Ll, RealMatrix &sum_Hlm1_Llm1, RealMatrix &sum_Hl_Hl, RealMatrix &sum_Hl_Hlm1, RealMatrix &sum_Hlm1_Hlm1, size_t lev, SizetArray &N_shared)
update running QoI sums for two models and two levels from set of low/high fidelity model evaluations within mlmf_resp_map
Private Attributes
short delegateMethod
core_run() can delegate execution to either ML or CV if hierarchy does not support MLCV; in this case output must also be delegated
Additional Inherited Members
Static Public Member Functions inherited from NonDSampling
static void compute_moments (const RealVectorArray &fn_samples, SizetArray &sample_counts, RealMatrix &moment_stats, short moments_type, const StringArray &labels)
core compute_moments() implementation with all data as inputs
static void compute_moments (const RealVectorArray &fn_samples, RealMatrix &moment_stats, short moments_type)
core compute_moments() implementation with all data as inputs
static void compute_moments (const RealMatrix &fn_samples, RealMatrix &moment_stats, short moments_type)
alternate RealMatrix samples API for use by external clients
static void print_moments (std::ostream &s, const RealMatrix &moment_stats, const RealMatrix &moment_cis, String qoi_type, short moments_type, const StringArray &moment_labels, bool print_cis)
core print moments that can be called without object
static int compute_wilks_sample_size (unsigned short order, Real alpha, Real beta, bool twosided=false)
calculates the number of samples using the Wilks formula Static so I can test without instantiating a NonDSampling object - RWH
static Real compute_wilks_residual (unsigned short order, int nsamples, Real alpha, Real beta, bool twosided)
Helper function - calculates the Wilks residual.
static Real compute_wilks_alpha (unsigned short order, int nsamples, Real beta, bool twosided=false)
calculates the alpha paramter given number of samples using the Wilks formula Static so I can test without instantiating a NonDSampling object - RWH
static Real compute_wilks_beta (unsigned short order, int nsamples, Real alpha, bool twosided=false)
calculates the beta parameter given number of samples using the Wilks formula Static so I can test without instantiating a NonDSampling object - RWH
static Real get_wilks_alpha_min ()
Get the lower and upper bounds supported by Wilks bisection solves.
static Real get_wilks_alpha_max ()
static Real get_wilks_beta_min ()
static Real get_wilks_beta_max ()
Static Public Member Functions inherited from Iterator
static String method_enum_to_string (unsigned short method_enum)
convert a method name enumeration value to a string
static unsigned short method_string_to_enum (const String &method_str)
convert a method name string to an enumeration value
static String submethod_enum_to_string (unsigned short submethod_enum)
convert a sub-method name enumeration value to a string
Static Protected Member Functions inherited from NonDEnsembleSampling
static void uncentered_to_centered (Real rm1, Real rm2, Real rm3, Real rm4, Real &cm1, Real &cm2, Real &cm3, Real &cm4)
convert uncentered (raw) moments to centered moments; unbiased estimators
static void uncentered_to_centered (Real rm1, Real rm2, Real rm3, Real rm4, Real &cm1, Real &cm2, Real &cm3, Real &cm4, size_t Nlq)
convert uncentered (raw) moments to centered moments; biased estimators
static void uncentered_to_centered (const Real *rm, Real *cm, size_t num_mom)
convert uncentered (raw) moments to centered moments; biased estimators
static void centered_to_standard (Real cm1, Real cm2, Real cm3, Real cm4, Real &sm1, Real &sm2, Real &sm3, Real &sm4)
convert centered moments to standardized moments
static void centered_to_standard (const Real *cm, Real *sm, size_t num_mom)
convert centered moments to standardized moments
static void check_negative (Real &cm)
detect, warn, and repair a negative central moment (for even orders)
Static Protected Member Functions inherited from Iterator
static void gnewton_set_recast (const Variables &recast_vars, const ActiveSet &recast_set, ActiveSet &sub_model_set)
conversion of request vector values for the Gauss-Newton Hessian approximation
Protected Attributes inherited from NonDMultilevelSampling
RealVector estVar
final estimator variance for output in print_variance_reduction()
Protected Attributes inherited from NonDHierarchSampling
size_t numSteps
number of model forms/resolution in the (outer) sequence
size_t secondaryIndex
setting for inactive model dimension not traversed by loop over numSteps
Protected Attributes inherited from NonDEnsembleSampling
short sequenceType
type of model sequence enumerated with primary MF/ACV loop over steps
RealVector sequenceCost
relative costs of model forms/resolution levels within a 1D sequence
size_t numApprox
number of approximation models managed by non-hierarchical iteratedModel
Sizet3DArray NLevActual
total number of successful sample evaluations (excluding faults) for each model form, discretization level, and QoI
Sizet2DArray NLevAlloc
total number of allocated sample evaluations (prior to any faults) for each model form and discretization level (same for all QoI)
SizetArray pilotSamples
store the pilot_samples input specification, prior to run-time invocation of load_pilot_sample()
short pilotMgmtMode
enumeration for pilot management modes: ONLINE_PILOT (default), OFFLINE_PILOT, ONLINE_PILOT_PROJECTION, or OFFLINE_PILOT_PROJECTION
short optSubProblemForm
formulation for optimization sub-problem that targets maximal accuracy fo fixed budget or minimal cost for specified accuracy
unsigned short optSubProblemSolver
SQP or NIP.
short costSource
indicates use of user-specified cost ratios, online cost recovery, or a combination
SizetSizetPairArray costMetadataIndices
indices of cost data within response metadata, one per model form
SizetArray randomSeedSeqSpec
user specification for seed_sequence
size_t mlmfIter
major iteration counter
bool backfillFailures
(inactive) option to backfill simulation failures by comparing targets against successful sample completions rather than sample allocations
Real equivHFEvals
equivalent number of high fidelity evaluations accumulated using samples across multiple model forms and/or discretization levels
Real deltaEquivHF
for sample projections, the calculated increment in equivHFEvals that would be incurred if full iteration/statistics were needed
RealVector varH
variances for HF truth (length numFunctions)
RealVector estVarIter0
initial estimator variance from shared pilot (no CV reduction)
short estVarMetricType
approach for defining scalar optimization metric from vectors of estimator variances/ratios
Real estVarMetricNormOrder
order of p-norm applied to estVariances or estVarRatios according to incoming metric type
short finalStatsType
QOI_STATISTICS (moments, level mappings) or ESTIMATOR_PERFORMANCE (for model tuning of estVar,equivHFEvals by an outer loop)
RealMatrix meanCIs
Matrix of confidence internals on moments, with rows for mean_lower, mean_upper (calculated in compute_mean_confidence_intervals())
bool exportSampleSets
if defined, export each of the sample increments in ML, CV, MLCV using tagged tabular files
unsigned short exportSamplesFormat
format for exporting sample increments using tagged tabular files
Real relaxFactor
the current relaxation factor applied to the predicted sample increment; in typical use, this is an under-relaxation factor to mitigate over-estimation of the sample allocation based on an initial approximation to response covariance data
size_t relaxIndex
index into relaxFactorSequence
RealVector relaxFactorSequence
a sequence of relaxation factors to use across ML/MF iterations (see DataMethod.hpp for usage notes)
Real relaxRecursiveFactor
a recursive relaxation factor (see DataMethod.hpp for usage notes)
ResponseContainer responseContainer
ResponseContainer pilotResponseContainer
Protected Attributes inherited from NonDSampling
int seedSpec
the user seed specification (default is 0)
int randomSeed
the current seed
const int samplesSpec
initial specification of number of samples
size_t samplesRef
reference number of samples updated for refinement
size_t numSamples
the current number of samples to evaluate
String rngName
name of the random number generator
unsigned short sampleType
the sample type: default, random, lhs, incremental random, or incremental lhs
bool wilksFlag
flags use of Wilks formula to calculate num samples
unsigned short wilksOrder
Real wilksAlpha
Real wilksBeta
short wilksSidedness
RealMatrix momentGrads
gradients of standardized or central moments of response functions, as determined by finalMomentsType. Calculated in compute_moments() and indexed as (var,moment) when moment id runs from 1:2*numFunctions.
RealSymMatrix finalStatErrors
standard errors (estimator std deviation) for each of the finalStatistics
int samplesIncrement
current increment in a sequence of samples
std::unique_ptr< SamplerDriver > samplerDriver
size_t numLHSRuns
counter for number of sample set generations
bool stdRegressionCoeffs
flags computation/output of standardized regression coefficients
bool toleranceIntervalsFlag
flags of double sided tolerance interval equivalent normal
Real tiCoverage
coverage to be used in the calculation of the double sided tolerance interval equivaluent normal
Real tiConfidenceLevel
confidence interval to be used in the calculation of the double sided tolerance interval equivalent normal
size_t tiNumValidSamples
RealVector tiDstienMus
Real tiDeltaMultiplicativeFactor
RealVector tiSampleSigmas
RealVector tiDstienSigmas
bool statsFlag
flags computation/output of statistics
bool allDataFlag
flags update of allResponses (allVariables or allSamples already defined)
short samplingVarsMode
the sampling mode: ALEATORY_UNCERTAIN{,_UNIFORM}, EPISTEMIC_UNCERTAIN{,_UNIFORM}, UNCERTAIN{,_UNIFORM}, ACTIVE{,_UNIFORM}, or ALL{,_UNIFORM}. This is a secondary control on top of the variables view that allows sampling over subsets of variables that may differ from the view.
short sampleRanksMode
mode for input/output of LHS sample ranks: IGNORE_RANKS, GET_RANKS, SET_RANKS, or SET_GET_RANKS
bool varyPattern
flag for generating a sequence of seed values within multiple get_parameter_sets() calls so that these executions (e.g., for SBO/SBNLS) are not repeated, but are still repeatable
RealMatrix sampleRanks
data structure to hold the sample ranks
SensAnalysisGlobal nonDSampCorr
initialize statistical post processing
bool backfillDuplicates
flags whether to use backfill to enforce uniqueness of discrete LHS samples
RealRealPairArray extremeValues
Minimum and maximum values of response functions for epistemic calculations (calculated in compute_intervals()),.
bool functionMomentsComputed
Function moments have been computed; used to determine whether to archive the moments.
Protected Attributes inherited from NonD
NonD * prevNondInstance
pointer containing previous value of nondInstance
size_t startCAUV
starting index of continuous aleatory uncertain variables within active continuous variables (convenience for managing offsets)
size_t numCAUV
number of active continuous aleatory uncertain variables
bool epistemicStats
flag for computing interval-type metrics instead of integrated metrics If any epistemic vars are active in a metric evaluation, then flag is set.
RealMatrix momentStats
standardized or central resp moments, as determined by finalMomentsType. Calculated in compute_moments()) and indexed as (moment,fn).
RealVectorArray requestedRespLevels
requested response levels for all response functions
RealVectorArray computedProbLevels
output probability levels for all response functions resulting from requestedRespLevels
RealVectorArray computedRelLevels
output reliability levels for all response functions resulting from requestedRespLevels
RealVectorArray computedGenRelLevels
output generalized reliability levels for all response functions resulting from requestedRespLevels
short respLevelTarget
indicates mapping of z->p (PROBABILITIES), z->beta (RELIABILITIES), or z->beta* (GEN_RELIABILITIES)
short respLevelTargetReduce
indicates component or system series/parallel failure metrics
RealVectorArray requestedProbLevels
requested probability levels for all response functions
RealVectorArray requestedRelLevels
requested reliability levels for all response functions
RealVectorArray requestedGenRelLevels
requested generalized reliability levels for all response functions
RealVectorArray computedRespLevels
output response levels for all response functions resulting from requestedProbLevels, requestedRelLevels, or requestedGenRelLevels
size_t totalLevelRequests
total number of levels specified within requestedRespLevels, requestedProbLevels, and requestedRelLevels
bool cdfFlag
flag for type of probabilities/reliabilities used in mappings: cumulative/CDF (true) or complementary/CCDF (false)
bool pdfOutput
flag for managing output of response probability density functions (PDFs)
RealVectorArray computedPDFAbscissas
sorted response PDF intervals bounds extracted from min/max sample and requested/computedRespLevels (vector lengths = num bins + 1)
RealVectorArray computedPDFOrdinates
response PDF densities computed from bin counts divided by (unequal) bin widths (vector lengths = num bins)
Response finalStatistics
final statistics from the uncertainty propagation used in strategies: response means, standard deviations, and probabilities of failure
short finalMomentsType
type of moments logged within finalStatistics: none, central, standard
size_t miPLIndex
index for the active ParallelLevel within ParallelConfiguration::miPLIters
BitArray pdfComputed
Whether PDF was computed for function i; used to determine whether a pdf should be archived.
Protected Attributes inherited from Analyzer
size_t numFunctions
number of response functions
size_t numContinuousVars
number of active continuous vars
size_t numDiscreteIntVars
number of active discrete integer vars
size_t numDiscreteStringVars
number of active discrete string vars
size_t numDiscreteRealVars
number of active discrete real vars
bool compactMode
switch for allSamples (compact mode) instead of allVariables (normal mode)
VariablesArray allVariables
array of all variables to be evaluated in evaluate_parameter_sets()
RealMatrix allSamples
compact alternative to allVariables
IntResponseMap allResponses
array of all responses to be computed in evaluate_parameter_sets()
IntIntVariables2DMap batchVariablesMap
alternate container for Variables samples supporting evaluate_batch() and synchronize_batches(), a 2D map with outer batch_id and inner eval_id
IntIntRealVector2DMap batchSamplesMap
alternate container for RealVector samples supporting evaluate_batch() and synchronize_batches(), a 2D map with outer batch_id and inner eval_id
IntIntResponse2DMap batchResponsesMap
alternate container for Response samples supporting evaluate_batch() and synchronize_batches(), a 2D map with outer batch_id and inner eval_id
StringArray allHeaders
array of headers to insert into output while evaluating allVariables
size_t numObjFns
number of objective functions
size_t numLSqTerms
number of least squares terms
RealPairPRPMultiMap bestVarsRespMap
map which stores best set of solutions
bool vbdFlag
flag indicating the activation of variance-bsaed decomposition for computing Sobol' indices, via either PCE or sampling
Real vbdDropTol
tolerance for omitting output of small VBD indices computed via either PCE or sampling
Protected Attributes inherited from Iterator
std::shared_ptr< Model > iteratedModel
the model to be iterated (for iterators and meta-iterators employing a single model instance)
ProblemDescDB & probDescDB
class member reference to the problem description database
ParallelLibrary & parallelLib
class member reference to the parallel library
ParConfigLIter methodPCIter
the active ParallelConfiguration used by this Iterator instance
size_t myModelLayers
number of Models locally (in Iterator or derived classes) wrapped around the initially passed in Model
unsigned short methodName
name of the iterator (the user's method spec)
Real convergenceTol
iteration convergence tolerance
size_t maxIterations
maximum number of iterations for the method
size_t maxFunctionEvals
maximum number of fn evaluations for the method
int maxEvalConcurrency
maximum number of concurrent model evaluations
ActiveSet activeSet
the response data requirements on each function evaluation
size_t numFinalSolutions
number of solutions to retain in best variables/response arrays
VariablesArray bestVariablesArray
collection of N best solution variables found during the study; always in context of Model originally passed to the Iterator (any in-flight Recasts must be undone)
ResponseArray bestResponseArray
collection of N best solution responses found during the study; always in context of Model originally passed to the Iterator (any in-flight Recasts must be undone)
bool subIteratorFlag
flag indicating if this Iterator is a sub-iterator (NestedModel::subIterator or DataFitSurrModel::daceIterator)
short outputLevel
output verbosity level: {SILENT,QUIET,NORMAL,VERBOSE,DEBUG}_OUTPUT
bool summaryOutputFlag
flag for summary output (evaluation stats, final results); default true, but false for on-the-fly (helper) iterators and sub-iterator use cases
ResultsManager & resultsDB
reference to the global iterator results database
EvaluationStore & evaluationsDB
reference to the global evaluation database
EvaluationsDBState evaluationsDBState
State of evaluations DB for this iterator.
ResultsNames resultsNames
valid names for iterator results
std::shared_ptr< TraitsBase > methodTraits
pointer that retains shared ownership of a TraitsBase object, or child thereof
bool topLevel
Whether this is the top level iterator.
bool exportSurrogate = false
whether to export final surrogates
String surrExportPrefix
base filename for exported surrogates
unsigned short surrExportFormat = NO_MODEL_FORMAT
(bitwise) format(s) to export
Static Protected Attributes inherited from NonD
static NonD * nondInstance
pointer to the active object instance used within static evaluator functions in order to avoid the need for static data
Detailed Description
Performs multilevel-multifidelity Monte Carlo sampling for uncertainty quantification.
Multilevel-multifidelity Monte Carlo (MLMFMC) combines variance decay across model resolutions with variance reduction from a control variate across model fidelities.
Constructor & Destructor Documentation
NonDMultilevControlVarSampling()
NonDMultilevControlVarSampling (ProblemDescDB & problem_db, std::shared_ptr< Model > model)
standard constructor
This constructor is called for a standard letter-envelope iterator instantiation. In this case, set_db_list_nodes has been called and probDescDB can be queried for settings from the method specification.
References NonD::configure_2d_sequence(), NonD::configure_cost(), NonDEnsembleSampling::costMetadataIndices, NonDEnsembleSampling::costSource, Iterator::iteratedModel, NonDEnsembleSampling::numApprox, NonDHierarchSampling::numSteps, NonDHierarchSampling::secondaryIndex, NonDEnsembleSampling::sequenceCost, and NonDEnsembleSampling::sequenceType.
Member Function Documentation
pre_run()
void pre_run () override protected virtual
pre-run portion of run (optional); re-implemented by Iterators which can generate all Variables (parameter sets) a priori
pre-run phase, which a derived iterator may optionally reimplement; when not present, pre-run is likely integrated into the derived run function. This is a virtual function; when re-implementing, a derived class must call its nearest parent's pre_run(), if implemented, typically before performing its own implementation steps.
Reimplemented from NonDEnsembleSampling.
References NonDEnsembleSampling::NLevActual, NonDEnsembleSampling::NLevAlloc, Analyzer::numFunctions, and NonDEnsembleSampling::pre_run().
core_run()
void core_run () override protected virtual
The primary run function manages the general case: a hierarchy of model forms (from the ordered model fidelities within an EnsembleSurrModel), each of which may contain multiple discretization levels.
Reimplemented from Iterator.
References NonDMultilevControlVarSampling::assign_active_key(), NonDMultilevelSampling::core_run(), NonDMultilevControlVarSampling::delegateMethod, NonDEnsembleSampling::finalStatsType, NonDMultilevControlVarSampling::multilevel_control_variate_mc_offline_pilot(), NonDMultilevControlVarSampling::multilevel_control_variate_mc_online_pilot(), NonDMultilevControlVarSampling::multilevel_control_variate_mc_pilot_projection(), NonDEnsembleSampling::pilotMgmtMode, and NonDEnsembleSampling::sequenceType.
multilevel_control_variate_mc_online_pilot()
void multilevel_control_variate_mc_online_pilot () private
Perform multilevel Monte Carlo across levels in combination with control variate Monte Carlo across model forms at each level; CV computes correlations for Q (LH correlations for QoI)
This function performs "geometrical" MLMC across discretization levels for the high fidelity model form where CVMC is employed across two model forms. It generalizes the Y_l correlation case to separately target correlations for each QoI level embedded within the level discrepancies.
References NonDMultilevControlVarSampling::accumulate_lf_increments(), NonDEnsembleSampling::advance_relaxation(), NonDMultilevControlVarSampling::apply_mlmf_controls(), NonDEnsembleSampling::backfillFailures, NonDEnsembleSampling::compute_mean_confidence_intervals(), NonDMultilevControlVarSampling::compute_mlmf_controls(), NonDMultilevControlVarSampling::compute_mlmf_estimator_variance(), NonDEnsembleSampling::convert_moments(), NonDEnsembleSampling::deltaEquivHF, NonDMultilevelSampling::estVar, NonDMultilevControlVarSampling::evaluate_levels(), NonDEnsembleSampling::finalStatsType, NonDMultilevControlVarSampling::initialize_mlmf_sums(), Iterator::iteratedModel, NonDMultilevControlVarSampling::lf_increment(), NonDMultilevControlVarSampling::lf_increments(), NonD::load_pilot_sample(), Iterator::maxIterations, NonDEnsembleSampling::meanCIs, NonDMultilevelSampling::ml_Q_raw_moments(), NonDMultilevelSampling::ml_Y_raw_moments(), NonDEnsembleSampling::mlmfIter, NonD::momentStats, NonDEnsembleSampling::NLevActual, NonDEnsembleSampling::NLevAlloc, Analyzer::numFunctions, NonDEnsembleSampling::pilotSamples, NonDMultilevelSampling::recover_variance(), NonDEnsembleSampling::sequenceType, NonDMultilevControlVarSampling::update_projected_lf_samples(), NonDEnsembleSampling::varH, and NonD::zeros().
Referenced by NonDMultilevControlVarSampling::core_run().
mlmf_increments()
void mlmf_increments (const SizetArray & delta_N_l, String prepend) private
evaluate multiple sample batches concurrently, where each batch involves either a single level or level pair for both HF and LF models
The version in NonDNonHierarchSampling would be sufficiently general here as well, given AGGREGATED_MODELS controlled by the ASV. However, MLMC and MLCV MC employ AGGREGATED_MODEL_PAIR without ASV subsetting, so we specialize for that case.
References Dakota::abort_handler(), NonDEnsembleSampling::assign_specification_sequence(), NonDHierarchSampling::ensemble_sample_batch(), Iterator::iteratedModel, NonDHierarchSampling::ml_active_set(), NonDEnsembleSampling::mlmfIter, NonDEnsembleSampling::NLevActual, Analyzer::numFunctions, NonDSampling::numSamples, and Analyzer::synchronize_batches().
Referenced by NonDMultilevControlVarSampling::evaluate_levels(), NonDMultilevControlVarSampling::evaluate_pilot(), and NonDMultilevControlVarSampling::multilevel_control_variate_mc_offline_pilot().
lf_increments()
void lf_increments (const SizetArray & delta_N_lf, String prepend) private
evaluate multiple sample batches concurrently, where each batch involves either a single level or level pair for the LF model
The version in NonDNonHierarchSampling would be sufficiently general here as well, given AGGREGATED_MODELS controlled by the ASV. However, MLMC and MLCV MC employ AGGREGATED_MODEL_PAIR without ASV subsetting, so we specialize for that case.
References NonDHierarchSampling::ensemble_sample_batch(), Iterator::iteratedModel, NonDHierarchSampling::ml_active_set(), NonDEnsembleSampling::mlmfIter, NonDSampling::numSamples, and Analyzer::synchronize_batches().
Referenced by NonDMultilevControlVarSampling::multilevel_control_variate_mc_offline_pilot(), and NonDMultilevControlVarSampling::multilevel_control_variate_mc_online_pilot().
accumulate_mlmf_Qsums()
void accumulate_mlmf_Qsums (const IntResponseMap & resp_map, IntRealMatrixMap & sum_Ql, IntRealMatrixMap & sum_Qlm1, size_t lev, SizetArray & num_Q) private
update running QoI sums for one model at two levels (sum_Ql, sum_Qlm1) using set of model evaluations within allResponses
Used in CV lf_increment() for leading (LF) function values in resp_map
References NonDMultilevelSampling::accumulate_ml_Qsums(), and Analyzer::numFunctions.
Referenced by NonDMultilevControlVarSampling::accumulate_increments(), NonDMultilevControlVarSampling::accumulate_lf_increments(), and NonDMultilevControlVarSampling::accumulate_mlmf_Qsums().
The documentation for this class was generated from the following files:
NonDMultilevControlVarSampling.hpp
NonDMultilevControlVarSampling.cpp