Dakota: LinearSolverBase Class Reference
LinearSolverBase Class Reference
The LinearSolverBase class serves as an API for derived solvers.
Public Types
enum SOLVER_TYPE {
CHOLESKY, EQ_CONS_LEAST_SQ_REGRESSION, LASSO_REGRESSION, LEAST_ANGLE_REGRESSION,
LU, ORTHOG_MATCH_PURSUIT, QR_LEAST_SQ_REGRESSION, SVD_LEAST_SQ_REGRESSION
}
How best to Doxygenate class enums? RWH.
Public Member Functions
LinearSolverBase ()
Constructor.
~LinearSolverBase ()
Destructor.
virtual bool is_factorized () const
Query to determine if the matrix of the solver has been factored.
virtual void factorize (const MatrixXd &A)
Perform the matrix factorization for the linear solver matrix.
virtual void solve (const MatrixXd &A, const MatrixXd &b, MatrixXd &x)
Find a solution to linear problem.
virtual void solve (const MatrixXd &b, MatrixXd &x)
Find a solution to linear problem where the LHS is already factorized.
Static Public Member Functions
static SOLVER_TYPE solver_type (const std::string &solver_name)
Convert solver name to enum type.
Detailed Description
The LinearSolverBase class serves as an API for derived solvers.
Member Function Documentation
solver_type()
SOLVER_TYPE solver_type (const std::string & solver_name) static
Convert solver name to enum type.
Parameters
[in] solver_name LinearSolverBase name to map
Returns
Corresponding LinearSolverBase enum
References dakota::util::type_name_bimap.
Referenced by PolynomialRegression::build().
factorize()
void factorize (const MatrixXd & A) virtual
Perform the matrix factorization for the linear solver matrix.
Parameters
[in] A The incoming matrix to factorize.
Reimplemented in CholeskySolver, QRSolver, SVDSolver, and LUSolver.
References dakota::silence_unused_args().
solve() [1/2]
void solve (const MatrixXd & A, const MatrixXd & b, MatrixXd & x) virtual
Find a solution to linear problem.
Parameters
[in] A The linear system left-hand-side matrix.
[in] b The linear system right-hand-side (multi-)vector.
[in] x The linear system solution (multi-)vector.
Reimplemented in CholeskySolver, QRSolver, SVDSolver, and LUSolver.
References dakota::silence_unused_args().
solve() [2/2]
void solve (const MatrixXd & b, MatrixXd & x) virtual
Find a solution to linear problem where the LHS is already factorized.
Parameters
[in] b The linear system right-hand-side (multi-)vector.
[in] x The linear system solution (multi-)vector.
Reimplemented in CholeskySolver, QRSolver, SVDSolver, and LUSolver.
References dakota::silence_unused_args().
The documentation for this class was generated from the following files:
UtilLinearSolvers.hpp
UtilLinearSolvers.cpp