Dakota: Iterator Class Reference
Iterator Class Reference
Base class for the iterator class hierarchy.
Public Member Functions
Iterator (std::shared_ptr< TraitsBase > traits=std::shared_ptr< TraitsBase >(new TraitsBase()))
default constructor
Iterator (ProblemDescDB &problem_db, std::shared_ptr< TraitsBase > traits=std::shared_ptr< TraitsBase >(new TraitsBase()))
standard envelope constructor, which constructs its own model(s)
Iterator (ProblemDescDB &problem_db, Model &model, std::shared_ptr< TraitsBase > traits=std::shared_ptr< TraitsBase >(new TraitsBase()))
alternate envelope constructor which uses the ProblemDescDB but accepts a model from a higher level (meta-iterator) context, instead of constructing its own
Iterator (const String &method_string, Model &model, std::shared_ptr< TraitsBase > traits=std::shared_ptr< TraitsBase >(new TraitsBase()))
alternate envelope constructor for instantiations by name without the ProblemDescDB
Iterator (const Iterator &iterator)
copy constructor
virtual ~Iterator ()
destructor
Iterator operator= (const Iterator &iterator)
assignment operator
virtual void derived_set_communicators (ParLevLIter pl_iter)
derived class contributions to setting the communicators associated with this Iterator instance
virtual void derived_free_communicators (ParLevLIter pl_iter)
derived class contributions to freeing the communicators associated with this Iterator instance
virtual void initialize_run ()
utility function to perform common operations prior to pre_run(); typically memory initialization; setting of instance pointers
virtual void pre_run ()
pre-run portion of run (optional); re-implemented by Iterators which can generate all Variables (parameter sets) a priori
virtual void core_run ()
core portion of run; implemented by all derived classes and may include pre/post steps in lieu of separate pre/post
virtual void post_run (std::ostream &s)
post-run portion of run (optional); verbose to print results; re-implemented by Iterators that can read all Variables/Responses and perform final analysis phase in a standalone way
virtual void finalize_run ()
utility function to perform common operations following post_run(); deallocation and resetting of instance pointers
virtual void pre_output ()
write variables to file, following pre-run
virtual void post_input ()
read tabular data for post-run mode
virtual void reset ()
restore initial state for repeated sub-iterator executions
virtual void nested_variable_mappings (const SizetArray &c_index1, const SizetArray &di_index1, const SizetArray &ds_index1, const SizetArray &dr_index1, const ShortArray &c_target2, const ShortArray &di_target2, const ShortArray &ds_target2, const ShortArray &dr_target2)
set primaryA{CV,DIV,DRV}MapIndices, secondaryA{CV,DIV,DRV}MapTargets within derived Iterators; supports computation of higher-level sensitivities in nested contexts (e.g., derivatives of statistics w.r.t. inserted design variables)
virtual void nested_response_mappings (const RealMatrix &primary_coeffs, const RealMatrix &secondary_coeffs)
set primaryResponseCoefficients, secondaryResponseCoefficients within derived Iterators; Necessary for scalarization case in MLMC NonDMultilevelSampling to map scalarization in nested context
virtual void initialize_iterator (int job_index)
used by IteratorScheduler to set the starting data for a run
virtual void pack_parameters_buffer (MPIPackBuffer &send_buffer, int job_index)
used by IteratorScheduler to pack starting data for an iterator run
virtual void unpack_parameters_buffer (MPIUnpackBuffer &recv_buffer, int job_index)
used by IteratorScheduler to unpack starting data for an iterator run
virtual void unpack_parameters_initialize (MPIUnpackBuffer &recv_buffer, int job_index)
used by IteratorScheduler to unpack starting data and initialize an iterator run
virtual void pack_results_buffer (MPIPackBuffer &send_buffer, int job_index)
used by IteratorScheduler to pack results data from an iterator run
virtual void unpack_results_buffer (MPIUnpackBuffer &recv_buffer, int job_index)
used by IteratorScheduler to unpack results data from an iterator run
virtual void update_local_results (int job_index)
used by IteratorScheduler to update local results arrays
virtual const Variables & variables_results () const
return a single final iterator solution (variables)
virtual const Response & response_results () const
return a single final iterator solution (response)
virtual const VariablesArray & variables_array_results ()
return multiple final iterator solutions (variables). This should only be used if returns_multiple_points() returns true.
virtual const ResponseArray & response_array_results ()
return multiple final iterator solutions (response). This should only be used if returns_multiple_points() returns true.
virtual void response_results_active_set (const ActiveSet &set)
set the requested data for the final iterator response results
virtual const RealSymMatrix & response_error_estimates () const
return error estimates associated with the final iterator solution
virtual bool accepts_multiple_points () const
indicates if this iterator accepts multiple initial points. Default return is false. Override to return true if appropriate.
virtual bool returns_multiple_points () const
indicates if this iterator returns multiple final points. Default return is false. Override to return true if appropriate.
virtual void initial_point (const Variables &pt)
sets the initial point for this iterator (user-functions mode for which Model updating is not used)
virtual void initial_point (const RealVector &pt)
sets the initial point (active continuous variables) for this iterator (user-functions mode for which Model updating is not used)
virtual void initial_points (const VariablesArray &pts)
sets the multiple initial points for this iterator. This should only be used if accepts_multiple_points() returns true.
virtual void variable_bounds (const RealVector &cv_lower_bnds, const RealVector &cv_upper_bnds)
assign nonlinear inequality and equality constraint allowables for this iterator (user-functions mode for which Model updating is not used)
virtual void linear_constraints (const RealMatrix &lin_ineq_coeffs, const RealVector &lin_ineq_lb, const RealVector &lin_ineq_ub, const RealMatrix &lin_eq_coeffs, const RealVector &lin_eq_tgt)
assign linear inequality and linear equality constraints for this iterator (user-functions mode for which Model updating is not used)
virtual void nonlinear_constraints (const RealVector &nln_ineq_lb, const RealVector &nln_ineq_ub, const RealVector &nln_eq_tgt)
assign nonlinear inequality and equality constraint allowables for this iterator (user-functions mode for which Model updating is not used)
virtual void initialize_graphics (int iterator_server_id=1)
initialize the 2D graphics window and the tabular graphics data
virtual void print_results (std::ostream &s, short results_state=FINAL_RESULTS)
print the final iterator results
virtual const Model & algorithm_space_model () const
return the result of any recasting or surrogate model recursion layered on top of iteratedModel by the derived Iterator ctor chain
virtual void check_sub_iterator_conflict ()
detect any conflicts due to recursive use of the same Fortran solver
virtual unsigned short uses_method () const
return name of any enabling iterator used by this iterator
virtual void method_recourse ()
perform a method switch, if possible, due to a detected conflict
virtual const VariablesArray & all_variables ()
return the complete set of evaluated variables
virtual const RealMatrix & all_samples ()
return the complete set of evaluated samples
virtual const IntResponseMap & all_responses () const
return the complete set of computed responses
virtual size_t num_samples () const
get the current number of samples
virtual void sampling_reset (size_t min_samples, bool all_data_flag, bool stats_flag)
reset sampling iterator to use at least min_samples
virtual void sampling_reference (size_t samples_ref)
set reference number of samples, which is a lower bound during reset
virtual void sampling_increment ()
increment to next in sequence of refinement samples
virtual void random_seed (int seed)
set randomSeed, if present
virtual unsigned short sampling_scheme () const
return sampling name
virtual bool compact_mode () const
returns Analyzer::compactMode
virtual IntIntPair estimate_partition_bounds ()
estimate the minimum and maximum partition sizes that can be utilized by this Iterator
virtual bool resize ()
reinitializes iterator based on new variable size
virtual void declare_sources ()
Declare sources to the evaluations database.
void init_communicators (ParLevLIter pl_iter)
initialize the communicators associated with this Iterator instance
void set_communicators (ParLevLIter pl_iter)
set the communicators associated with this Iterator instance
void free_communicators (ParLevLIter pl_iter)
free the communicators associated with this Iterator instance
void resize_communicators (ParLevLIter pl_iter, bool reinit_comms)
Resize the communicators. This is called from the letter's resize()
void parallel_configuration_iterator (ParConfigLIter pc_iter)
set methodPCIter
ParConfigLIter parallel_configuration_iterator () const
return methodPCIter
void parallel_configuration_iterator_map (std::map< size_t, ParConfigLIter > pci_map)
set methodPCIterMap
std::map< size_t, ParConfigLIter > parallel_configuration_iterator_map () const
return methodPCIterMap
void run (ParLevLIter pl_iter)
invoke set_communicators(pl_iter) prior to run()
void run ()
orchestrate initialize/pre/core/post/finalize phases
void assign_rep (std::shared_ptr< Iterator > iterator_rep)
replaces existing letter with a new one
void iterated_model (const Model &model)
set the iteratedModel (iterators and meta-iterators using a single model instance)
Model & iterated_model ()
return the iteratedModel (iterators & meta-iterators using a single model instance)
ProblemDescDB & problem_description_db () const
return the problem description database (probDescDB)
ParallelLibrary & parallel_library () const
return the parallel library (parallelLib)
void method_name (unsigned short m_name)
set the method name to an enumeration value
unsigned short method_name () const
return the method name via its native enumeration value
void method_string (const String &m_str)
set the method name by string
String method_string () const
return the method name by string
String method_enum_to_string (unsigned short method_enum) const
convert a method name enumeration value to a string
unsigned short method_string_to_enum (const String &method_str) const
convert a method name string to an enumeration value
String submethod_enum_to_string (unsigned short submethod_enum) const
convert a sub-method name enumeration value to a string
const String & method_id () const
return the method identifier (methodId)
int maximum_evaluation_concurrency () const
return the maximum evaluation concurrency supported by the iterator
void maximum_evaluation_concurrency (int max_conc)
set the maximum evaluation concurrency supported by the iterator
size_t maximum_iterations () const
return the maximum iterations for this iterator
void maximum_iterations (size_t max_iter)
set the maximum iterations for this iterator
void convergence_tolerance (Real conv_tol)
set the method convergence tolerance (convergenceTol)
Real convergence_tolerance () const
return the method convergence tolerance (convergenceTol)
void output_level (short out_lev)
set the method output level (outputLevel)
short output_level () const
return the method output level (outputLevel)
void summary_output (bool summary_output_flag)
Set summary output control; true enables evaluation/results summary.
size_t num_final_solutions () const
return the number of solutions to retain in best variables/response arrays
void num_final_solutions (size_t num_final)
set the number of solutions to retain in best variables/response arrays
void active_set (const ActiveSet &set)
set the default active set (for use with iterators that employ evaluate_parameter_sets())
const ActiveSet & active_set () const
return the default active set (used by iterators that employ evaluate_parameter_sets())
void active_set_request_vector (const ShortArray &asv)
return the default active set request vector (used by iterators that employ evaluate_parameter_sets())
const ShortArray & active_set_request_vector () const
return the default active set request vector (used by iterators that employ evaluate_parameter_sets())
void active_set_request_values (short asv_val)
return the default active set request vector (used by iterators that employ evaluate_parameter_sets())
void sub_iterator_flag (bool si_flag)
set subIteratorFlag (and update summaryOutputFlag if needed)
bool is_null () const
function to check iteratorRep (does this envelope contain a letter?)
std::shared_ptr< Iterator > iterator_rep () const
returns iteratorRep for access to derived class member functions that are not mapped to the top Iterator level
virtual void eval_tag_prefix (const String &eval_id_str)
set the hierarchical eval ID tag prefix
std::shared_ptr< TraitsBase > traits () const
returns methodTraits for access to derived class member functions that are not mapped to the top TraitsBase level
bool top_level ()
Return whether the iterator is the top level iterator.
void top_level (bool tflag)
Set the iterator's top level flag.
Protected Member Functions
Iterator (BaseConstructor, ProblemDescDB &problem_db, std::shared_ptr< TraitsBase > traits=std::shared_ptr< TraitsBase >(new TraitsBase()))
constructor initializes the base class part of letter classes (BaseConstructor overloading avoids infinite recursion in the derived class constructors - Coplien, p. 139)
Iterator (NoDBBaseConstructor, unsigned short method_name, Model &model, std::shared_ptr< TraitsBase > traits=std::shared_ptr< TraitsBase >(new TraitsBase()))
alternate constructor for base iterator classes constructed on the fly
Iterator (NoDBBaseConstructor, unsigned short method_name, std::shared_ptr< TraitsBase > traits=std::shared_ptr< TraitsBase >(new TraitsBase()))
alternate constructor for base iterator classes constructed on the fly
Iterator (NoDBBaseConstructor, Model &model, size_t max_iter, size_t max_eval, Real conv_tol, std::shared_ptr< TraitsBase > traits=std::shared_ptr< TraitsBase >(new TraitsBase()))
alternate envelope constructor for instantiations without ProblemDescDB
virtual void derived_init_communicators (ParLevLIter pl_iter)
derived class contributions to initializing the communicators associated with this Iterator instance
virtual void update_from_model (const Model &model)
set inherited data attributes based on extractions from incoming model
virtual const VariablesArray & initial_points () const
gets the multiple initial points for this iterator. This will only be meaningful after a call to initial_points mutator.
StrStrSizet run_identifier () const
get the unique run identifier based on method name, id, and number of executions
void initialize_model_graphics (Model &model, int iterator_server_id)
helper function that encapsulates initialization operations, modular on incoming Model instance
void export_final_surrogates (Model &data_fit_surr_model)
export final surrogates generated, e.g., GP in EGO and friends
Static Protected Member Functions
static void gnewton_set_recast (const Variables &recast_vars, const ActiveSet &recast_set, ActiveSet &sub_model_set)
conversion of request vector values for the Gauss-Newton Hessian approximation
Protected Attributes
ProblemDescDB & probDescDB
class member reference to the problem description database
ParallelLibrary & parallelLib
class member reference to the parallel library
ParConfigLIter methodPCIter
the active ParallelConfiguration used by this Iterator instance
Model iteratedModel
the model to be iterated (for iterators and meta-iterators employing a single model instance)
size_t myModelLayers
number of Models locally (in Iterator or derived classes) wrapped around the initially passed in Model
unsigned short methodName
name of the iterator (the user's method spec)
Real convergenceTol
iteration convergence tolerance
size_t maxIterations
maximum number of iterations for the method
size_t maxFunctionEvals
maximum number of fn evaluations for the method
int maxEvalConcurrency
maximum number of concurrent model evaluations
ActiveSet activeSet
the response data requirements on each function evaluation
size_t numFinalSolutions
number of solutions to retain in best variables/response arrays
VariablesArray bestVariablesArray
collection of N best solution variables found during the study; always in context of Model originally passed to the Iterator (any in-flight Recasts must be undone)
ResponseArray bestResponseArray
collection of N best solution responses found during the study; always in context of Model originally passed to the Iterator (any in-flight Recasts must be undone)
bool subIteratorFlag
flag indicating if this Iterator is a sub-iterator (NestedModel::subIterator or DataFitSurrModel::daceIterator)
short outputLevel
output verbosity level: {SILENT,QUIET,NORMAL,VERBOSE,DEBUG}_OUTPUT
bool summaryOutputFlag
flag for summary output (evaluation stats, final results); default true, but false for on-the-fly (helper) iterators and sub-iterator use cases
ResultsManager & resultsDB
reference to the global iterator results database
EvaluationStore & evaluationsDB
reference to the global evaluation database
EvaluationsDBState evaluationsDBState
State of evaluations DB for this iterator.
ResultsNames resultsNames
valid names for iterator results
std::shared_ptr< TraitsBase > methodTraits
pointer that retains shared ownership of a TraitsBase object, or child thereof
bool topLevel
Whether this is the top level iterator.
bool exportSurrogate = false
whether to export final surrogates
String surrExportPrefix
base filename for exported surrogates
unsigned short surrExportFormat = NO_MODEL_FORMAT
(bitwise) format(s) to export
Private Member Functions
std::shared_ptr< Iterator > get_iterator (ProblemDescDB &problem_db)
Used by the envelope to instantiate the correct letter class.
std::shared_ptr< Iterator > get_iterator (ProblemDescDB &problem_db, Model &model)
Used by the envelope to instantiate the correct letter class.
std::shared_ptr< Iterator > get_iterator (const String &method_string, Model &model)
Used by the envelope to instantiate the correct letter class.
Static Private Member Functions
static String user_auto_id ()
return the next available method ID for no-ID user methods
static String no_spec_id ()
return the next available method ID for on-the-fly methods
Private Attributes
String methodId
method identifier string from the input file, or an auto-generated ID, such that each instance of an Iterator has a unique ID
size_t execNum
An execution number for this instance of the class. Now that each instance has a unique methodId, this is just a simple counter.
std::map< size_t, ParConfigLIter > methodPCIterMap
track the available configurations that have been created (init_communicators) and are available for activation at run time (set_communicators)
std::shared_ptr< Iterator > iteratorRep
pointer to the letter (initialized only for the envelope)
Static Private Attributes
static size_t noSpecIdNum = 0
the last used method ID number for on-the-fly instantiations (increment before each use)
Detailed Description
Base class for the iterator class hierarchy.
The Iterator class is the base class for one of the primary class hierarchies in DAKOTA. The iterator hierarchy contains all of the iterative algorithms which use repeated execution of simulations as function evaluations. For memory efficiency and enhanced polymorphism, the iterator hierarchy employs the "letter/envelope idiom" (see Coplien "Advanced C++", p. 133), for which the base class (Iterator) serves as the envelope and one of the derived classes (selected in Iterator::get_iterator()) serves as the letter.
Constructor & Destructor Documentation
Iterator() [1/9]
Iterator (std::shared_ptr< TraitsBase > traits = std::shared_ptr<TraitsBase>(new TraitsBase()))
default constructor
The default constructor is used in Vector<Iterator> instantiations and for initialization of Iterator objects contained in meta-Iterators and Model recursions. iteratorRep is NULL in this case.
Iterator() [2/9]
Iterator (ProblemDescDB & problem_db, std::shared_ptr< TraitsBase > traits = std::shared_ptr<TraitsBase>(new TraitsBase()))
standard envelope constructor, which constructs its own model(s)
This constructor assigns a representation pointer into this envelope, transferring ownership. It behaves the same as a default construction followed by assign_rep(). Envelope constructor only needs to extract enough data to properly execute get_iterator(), since letter holds the actual base class data. This version is used for top-level ProblemDescDB-driven construction of all Iterators and MetaIterators, which construct their own Model instances.
References Dakota::abort_handler(), and Iterator::iteratorRep.
Iterator() [3/9]
Iterator (ProblemDescDB & problem_db, Model & model, std::shared_ptr< TraitsBase > traits = std::shared_ptr<TraitsBase>(new TraitsBase()))
alternate envelope constructor which uses the ProblemDescDB but accepts a model from a higher level (meta-iterator) context, instead of constructing its own
Envelope constructor only needs to extract enough data to properly execute get_iterator(), since letter holds the actual base class data. This version is used for ProblemDescDB-driven construction of Iterators that are passed a Model from a higher-level context (e.g., a MetaIterator instantiates its sub-iterator(s) by name instead of pointer and passes in its iteratedModel, since these sub-iterators lack their own model pointers).
References Dakota::abort_handler(), and Iterator::iteratorRep.
Iterator() [4/9]
Iterator (const String & method_string, Model & model, std::shared_ptr< TraitsBase > traits = std::shared_ptr<TraitsBase>(new TraitsBase()))
alternate envelope constructor for instantiations by name without the ProblemDescDB
Used in sub-iterator instantiations within iterator constructors. Envelope constructor only needs to extract enough data to properly execute get_iterator(), since letter holds the actual base class data. This version is used for lightweight constructions without the ProblemDescDB.
References Dakota::abort_handler(), and Iterator::iteratorRep.
Iterator() [5/9]
Iterator (const Iterator & iterator)
copy constructor
Copy constructor manages sharing of iteratorRep.
Iterator() [6/9]
Iterator (BaseConstructor , ProblemDescDB & problem_db, std::shared_ptr< TraitsBase > traits = std::shared_ptr<TraitsBase>(new TraitsBase())) protected
constructor initializes the base class part of letter classes (BaseConstructor overloading avoids infinite recursion in the derived class constructors - Coplien, p. 139)
This constructor builds the base class data for all inherited iterators, including meta-iterators. get_iterator() instantiates a derived class and the derived class selects this base class constructor in its initialization list (to avoid the recursion of the base class constructor calling get_iterator() again). Since the letter IS the representation, its representation pointer is set to NULL
References Iterator::method_enum_to_string(), Iterator::methodId, Iterator::methodName, Iterator::outputLevel, and Iterator::user_auto_id().
Iterator() [7/9]
Iterator (NoDBBaseConstructor , unsigned short method_name, Model & model, std::shared_ptr< TraitsBase > traits = std::shared_ptr<TraitsBase>(new TraitsBase())) protected
alternate constructor for base iterator classes constructed on the fly
This alternate constructor builds base class data for inherited iterators. It is used for on-the-fly instantiations for which DB queries cannot be used, and is not used for construction of meta-iterators.
Iterator() [8/9]
Iterator (NoDBBaseConstructor , unsigned short method_name, std::shared_ptr< TraitsBase > traits = std::shared_ptr<TraitsBase>(new TraitsBase())) protected
alternate constructor for base iterator classes constructed on the fly
This alternate constructor builds base class data for inherited iterators. It is used for on-the-fly instantiations for which DB queries cannot be used, and is not used for construction of meta-iterators. It has no incoming model, so only sets up a minimal set of defaults. However, its use is preferable to the default constructor, which should remain as minimal as possible.
Iterator() [9/9]
Iterator (NoDBBaseConstructor , Model & model, size_t max_iter, size_t max_eval, Real conv_tol, std::shared_ptr< TraitsBase > traits = std::shared_ptr<TraitsBase>(new TraitsBase())) protected
alternate envelope constructor for instantiations without ProblemDescDB
This alternate constructor builds base class data for inherited iterators. It is used for on-the-fly instantiations for which DB queries cannot be used, and is not used for construction of meta-iterators.
Member Function Documentation
initialize_run()
void initialize_run () virtual
utility function to perform common operations prior to pre_run(); typically memory initialization; setting of instance pointers
Perform initialization phases of run sequence, like allocating memory and setting instance pointers. Commonly used in sub-iterator executions. This is a virtual function; when re-implementing, a derived class must call its nearest parent's initialize_run(), typically before performing its own implementation steps.
Reimplemented in ROLOptimizer, SNLLOptimizer, SNLLLeastSq, Optimizer, NonD, Minimizer, LeastSq, Analyzer, CONMINOptimizer, and APPSOptimizer.
References Iterator::iteratorRep.
Referenced by Iterator::run(), and SeqHybridMetaIterator::run_sequential_adaptive().
pre_run()
void pre_run () virtual
pre-run portion of run (optional); re-implemented by Iterators which can generate all Variables (parameter sets) a priori
pre-run phase, which a derived iterator may optionally reimplement; when not present, pre-run is likely integrated into the derived run function. This is a virtual function; when re-implementing, a derived class must call its nearest parent's pre_run(), if implemented, typically before performing its own implementation steps.
Reimplemented in SurrBasedLocalMinimizer, PSUADEDesignCompExp, ParamStudy, NonDSampling, NonDRKDDarts, NonDNonHierarchSampling, NonDMultilevControlVarSampling, NonDLocalReliability, NonDLHSSampling, NonDGlobalReliability, NonDEnsembleSampling, NonDBayesCalibration, FSUDesignCompExp, EffGlobalMinimizer, DDACEDesignCompExp, Analyzer, and ConcurrentMetaIterator.
References Iterator::iteratorRep.
Referenced by NonDBayesCalibration::build_designs(), and Iterator::run().
core_run()
void core_run () virtual
core portion of run; implemented by all derived classes and may include pre/post steps in lieu of separate pre/post
Virtual run function for the iterator class hierarchy. All derived classes need to redefine it.
Reimplemented in ROLOptimizer, SurrBasedLocalMinimizer, SurrBasedGlobalMinimizer, SNLLOptimizer, SNLLLeastSq, SeqHybridMetaIterator, RichExtrapVerification, PSUADEDesignCompExp, ParamStudy, OptDartsOptimizer, NOWPACOptimizer, NonlinearCGOptimizer, NonDSampling, NonDRKDDarts, NonDPOFDarts, NonDMultilevelStochCollocation, NonDMultilevelSampling, NonDMultilevelPolynomialChaos, NonDMultilevelFunctionTrain, NonDMultilevControlVarSampling, NonDMultifidelitySampling, NonDLocalReliability, NonDLocalInterval, NonDLHSSampling, NonDLHSInterval, NonDIntegration, NonDGPImpSampling, NonDGlobalReliability, NonDGlobalInterval, NonDExpansion, NonDControlVariateSampling, NonDBayesCalibration, NonDAdaptiveSampling, NonDAdaptImpSampling, NonDACVSampling, NLSSOLLeastSq, NL2SOLLeastSq, NCSUOptimizer, JEGAOptimizer, FSUDesignCompExp, EmbedHybridMetaIterator, EffGlobalMinimizer, DDACEDesignCompExp, CONMINOptimizer, ConcurrentMetaIterator, CollabHybridMetaIterator, COLINOptimizer, and APPSOptimizer.
References Dakota::abort_handler(), and Iterator::iteratorRep.
Referenced by Iterator::run().
post_run()
void post_run (std::ostream & s) virtual
post-run portion of run (optional); verbose to print results; re-implemented by Iterators that can read all Variables/Responses and perform final analysis phase in a standalone way
Post-run phase, which a derived iterator may optionally reimplement; when not present, post-run is likely integrated into run. This is a virtual function; when re-implementing, a derived class must call its nearest parent's post_run(), typically after performing its own implementation steps.
Reimplemented in NonDPolynomialChaos, SurrBasedLocalMinimizer, SNLLOptimizer, PSUADEDesignCompExp, ParamStudy, NonDRKDDarts, NonDReliability, NonDLHSSampling, NonDEnsembleSampling, MetaIterator, FSUDesignCompExp, EffGlobalMinimizer, DDACEDesignCompExp, Optimizer, Minimizer, LeastSq, Analyzer, and COLINOptimizer.
References Iterator::iteratorRep.
Referenced by Iterator::run().
finalize_run()
void finalize_run () virtual
utility function to perform common operations following post_run(); deallocation and resetting of instance pointers
Optional: perform finalization phases of run sequence, like deallocating memory and resetting instance pointers. Commonly used in sub-iterator executions. This is a virtual function; when re-implementing, a derived class must call its nearest parent's finalize_run(), typically after performing its own implementation steps.
Reimplemented in SNLLOptimizer, SNLLLeastSq, Optimizer, NonD, Minimizer, LeastSq, and Analyzer.
References Iterator::iteratorRep.
Referenced by Iterator::run(), and SeqHybridMetaIterator::run_sequential_adaptive().
initialize_graphics()
void initialize_graphics (int iterator_server_id = 1) virtual
initialize the 2D graphics window and the tabular graphics data
This is a convenience function for encapsulating graphics initialization operations. It is overridden by derived classes that specialize the graphics display.
Reimplemented in SurrBasedLocalMinimizer, SurrBasedGlobalMinimizer, and NonDLocalReliability.
References Iterator::initialize_model_graphics(), Iterator::iteratedModel, and Iterator::iteratorRep.
Referenced by CollabHybridMetaIterator::core_run(), ConcurrentMetaIterator::core_run(), EmbedHybridMetaIterator::core_run(), Environment::execute(), SeqHybridMetaIterator::run_sequential(), and SeqHybridMetaIterator::run_sequential_adaptive().
print_results()
void print_results (std::ostream & s, short results_state = FINAL_RESULTS) virtual
print the final iterator results
This virtual function provides additional iterator-specific final results outputs beyond the function evaluation summary printed in finalize_run().
Reimplemented in NonDWASABIBayesCalibration, NonDQUESOBayesCalibration, SurrBasedMinimizer, SeqHybridMetaIterator, RichExtrapVerification, NonDPolynomialChaos, NonDPOFDarts, NonDMUQBayesCalibration, NonDMultilevelStochCollocation, NonDMultilevelPolynomialChaos, NonDMultilevelFunctionTrain, NonDLocalReliability, NonDLHSSampling, NonDInterval, NonDGPMSABayesCalibration, NonDGPImpSampling, NonDGlobalReliability, NonDExpansion, NonDEnsembleSampling, NonDBayesCalibration, NonDAdaptiveSampling, NonDAdaptImpSampling, Verification, PStudyDACE, Optimizer, LeastSq, Analyzer, and ConcurrentMetaIterator.
References Iterator::iteratorRep.
Referenced by Minimizer::post_run(), and MetaIterator::post_run().
check_sub_iterator_conflict()
void check_sub_iterator_conflict () virtual
detect any conflicts due to recursive use of the same Fortran solver
This is used to avoid clashes in state between non-object-oriented (i.e., F77, C) iterator executions, when such iterators could potentially be executing simultaneously (e.g., nested execution). It is not an issue (and a used method is not reported) in cases where a helper execution is completed before a lower level one could be initiated; an example of this is DIRECT for maximization of expected improvement: the EIF maximization is completed before a new point evaluation (which could include nested iteration) is performed.
Reimplemented in NonDLocalReliability, NonDLocalInterval, NLSSOLLeastSq, NCSUOptimizer, and CONMINOptimizer.
References Iterator::iteratorRep.
Referenced by Iterator::init_communicators().
run()
void run ()
orchestrate initialize/pre/core/post/finalize phases
Iterator supports a construct/initialize-run/pre-run/core-run/post-run/ finalize-run/destruct progression. This member (non-virtual) function sequences these run phases.
References ParallelLibrary::command_line_post_run(), ParallelLibrary::command_line_pre_run(), ParallelLibrary::command_line_run(), Iterator::core_run(), Iterator::declare_sources(), Iterator::evaluationsDB, Iterator::evaluationsDBState, Iterator::execNum, Iterator::finalize_run(), ResultsManager::flush(), Iterator::initialize_run(), Iterator::iteratorRep, Iterator::method_enum_to_string(), Iterator::method_id(), Iterator::method_string(), Iterator::methodName, Iterator::outputLevel, Iterator::parallelLib, Iterator::post_input(), Iterator::post_run(), Iterator::pre_output(), Iterator::pre_run(), Iterator::resultsDB, Iterator::summaryOutputFlag, and Iterator::top_level().
Referenced by Iterator::run().
assign_rep()
void assign_rep (std::shared_ptr< Iterator > iterator_rep)
replaces existing letter with a new one
The assign_rep() function is used for publishing derived class letters to existing envelopes, as opposed to sharing representations among multiple envelopes (in particular, assign_rep is passed a letter object and operator= is passed an envelope object).
Use case assumes the incoming letter is instantiated on the fly and has no envelope. This case is modeled after get_iterator(): a letter is dynamically allocated and passed into assign_rep (its memory management is passed over to the envelope).
If the letter happens to be managed by another envelope, it will persist as long as the last envelope referencing it.
References Iterator::iterator_rep(), and Iterator::iteratorRep.
Referenced by AdaptedBasisModel::AdaptedBasisModel(), NonDBayesCalibration::build_designs(), NonDExpansion::construct_cubature(), NonDExpansion::construct_expansion_sampler(), NonDAdaptiveSampling::construct_fsu_sampler(), NonD::construct_lhs(), NonDBayesCalibration::construct_map_optimizer(), NonDBayesCalibration::construct_mcmc_model(), NonDExpansion::construct_quadrature(), NonDExpansion::construct_sparse_grid(), Minimizer::data_transform_model(), ActiveSubspaceModel::init_fullspace_sampler(), EffGlobalMinimizer::initialize_sub_problem(), NonDLocalInterval::method_recourse(), NonDLocalReliability::method_recourse(), NonDAdaptiveSampling::NonDAdaptiveSampling(), NonDBayesCalibration::NonDBayesCalibration(), NonDGlobalInterval::NonDGlobalInterval(), NonDGlobalReliability::NonDGlobalReliability(), NonDGPImpSampling::NonDGPImpSampling(), NonDGPMSABayesCalibration::NonDGPMSABayesCalibration(), NonDLHSInterval::NonDLHSInterval(), NonDLocalInterval::NonDLocalInterval(), NonDLocalReliability::NonDLocalReliability(), GaussProcApproximation::optimize_theta_global(), GaussProcApproximation::optimize_theta_multipoint(), and SurrBasedLocalMinimizer::relax_constraints().
eval_tag_prefix()
void eval_tag_prefix (const String & eval_id_str) virtual
set the hierarchical eval ID tag prefix
This prepend may need to become a virtual function if the tagging should propagate to other subModels or helper Iterators an Iterator may contain.
References Model::eval_tag_prefix(), Iterator::iteratedModel, and Iterator::iteratorRep.
Referenced by NestedModel::derived_evaluate(), Iterator::init_communicators(), NestedModel::initialize_iterator(), and DataFitSurrModel::run_dace().
gnewton_set_recast()
void gnewton_set_recast (const Variables & recast_vars, const ActiveSet & recast_set, ActiveSet & sub_model_set) static protected
conversion of request vector values for the Gauss-Newton Hessian approximation
For Gauss-Newton Hessian requests, activate the 2 bit and mask the 4 bit.
References ActiveSet::request_value(), and ActiveSet::request_vector().
Referenced by NonDBayesCalibration::construct_map_model(), and Optimizer::reduce_model().
initialize_model_graphics()
void initialize_model_graphics (Model & model, int iterator_server_id) protected
helper function that encapsulates initialization operations, modular on incoming Model instance
This is a helper function that provides modularity on incoming Model.
References Model::auto_graphics(), Model::create_2d_plots(), Model::create_tabular_datastream(), OutputManager::graph2DFlag, ParallelLibrary::output_manager(), Iterator::parallelLib, and OutputManager::tabularDataFlag.
Referenced by Iterator::initialize_graphics(), and SurrBasedGlobalMinimizer::initialize_graphics().
export_final_surrogates()
void export_final_surrogates (Model & data_fit_surr_model) protected
export final surrogates generated, e.g., GP in EGO and friends
Protected function to only be called on letters
References Dakota::abort_handler(), Model::approximations(), Model::current_variables(), Iterator::exportSurrogate, Model::response_labels(), Iterator::surrExportFormat, and Iterator::surrExportPrefix.
Referenced by NonDGlobalInterval::core_run(), NonDGlobalReliability::optimize_gaussian_process(), and EffGlobalMinimizer::retrieve_final_results().
get_iterator() [1/3]
std::shared_ptr< Iterator > get_iterator (ProblemDescDB & problem_db) private
Used by the envelope to instantiate the correct letter class.
Used only by the envelope constructor to initialize iteratorRep to the appropriate derived type, as given by the DB's method_name. Supports all iterators and meta-iterators. These instantiations will NOT recurse on the Iterator(problem_db) constructor due to the use of BaseConstructor.
References ProblemDescDB::get_model(), ProblemDescDB::get_ushort(), Iterator::method_name(), and Dakota::SUBMETHOD_COLLABORATIVE.
get_iterator() [2/3]
std::shared_ptr< Iterator > get_iterator (ProblemDescDB & problem_db, Model & model) private
Used by the envelope to instantiate the correct letter class.
Used only by the envelope constructor to initialize iteratorRep to the appropriate derived type. Alternate construction of meta-iterators is supported to enable use of meta-iterators as components. These instantiations will NOT recurse on the Iterator(problem_db, model) constructor due to the use of BaseConstructor.
References ProblemDescDB::get_ushort(), Iterator::method_enum_to_string(), Iterator::method_name(), Iterator::probDescDB, Dakota::SUBMETHOD_COLLABORATIVE, Iterator::submethod_enum_to_string(), and Model::surrogate_type().
get_iterator() [3/3]
std::shared_ptr< Iterator > get_iterator (const String & method_string, Model & model) private
Used by the envelope to instantiate the correct letter class.
Used only by the envelope constructor to initialize iteratorRep to the appropriate derived type, as given by the passed method_string. Lightweight instantiations by name are supported by a subset of Iterators (primarily Minimizers).
References Iterator::method_string(), Dakota::strbegins(), and Dakota::strends().
user_auto_id()
String user_auto_id () static private
return the next available method ID for no-ID user methods
Rationale: The parser allows multiple user-specified methods with empty (unspecified) ID. However, only a single Iterator with empty ID can be constructed (if it's the only one present, or the "last one parsed"). Therefore decided to prefer NO_METHOD_ID over NO_METHOD_ID_<num> for (partial) consistency with interface NO_ID convention. The addition of METHOD is it distinguish methods, models and interfaces in the HDF5 output.
Referenced by Iterator::Iterator().
no_spec_id()
String no_spec_id () static private
return the next available method ID for on-the-fly methods
Rationale: For now NOSPEC_METHOD_ID_ is chosen due to historical id="NO_SPECIFICATION" used for internally-constructed Iterators. Longer-term, consider auto-generating an ID that includes the context from which the method is constructed, e.g., the parent method or model's ID, together with its name.
References Iterator::noSpecIdNum.
Member Data Documentation
probDescDB
ProblemDescDB& probDescDB protected
class member reference to the problem description database
Iterator and Model cannot use a shallow copy of ProblemDescDB due to circular destruction dependency (reference counts can't get to 0), since ProblemDescDB contains {iterator,model}List.
Referenced by MetaIterator::allocate_by_name(), MetaIterator::allocate_by_pointer(), Analyzer::Analyzer(), MetaIterator::check_model(), COLINOptimizer::COLINOptimizer(), NonDC3FunctionTrain::config_regression(), NonDBayesCalibration::construct_mcmc_model(), Minimizer::data_transform_model(), ConcurrentMetaIterator::derived_init_communicators(), EmbedHybridMetaIterator::derived_init_communicators(), SurrBasedMinimizer::derived_init_communicators(), EffGlobalMinimizer::EffGlobalMinimizer(), MetaIterator::estimate_by_name(), MetaIterator::estimate_by_pointer(), CollabHybridMetaIterator::estimate_partition_bounds(), ConcurrentMetaIterator::estimate_partition_bounds(), EmbedHybridMetaIterator::estimate_partition_bounds(), SeqHybridMetaIterator::estimate_partition_bounds(), FSUDesignCompExp::FSUDesignCompExp(), Optimizer::get_common_stopping_criteria(), Iterator::get_iterator(), NonDC3FunctionTrain::initialize_c3_db_options(), ConcurrentMetaIterator::initialize_model(), NOWPACOptimizer::initialize_options(), SurrBasedLocalMinimizer::initialize_sub_minimizer(), JEGAOptimizer::JEGAOptimizer(), NLSSOLLeastSq::NLSSOLLeastSq(), NonDAdaptImpSampling::NonDAdaptImpSampling(), NonDAdaptiveSampling::NonDAdaptiveSampling(), NonDBayesCalibration::NonDBayesCalibration(), NonDC3FunctionTrain::NonDC3FunctionTrain(), NonDGlobalInterval::NonDGlobalInterval(), NonDGlobalReliability::NonDGlobalReliability(), NonDGPImpSampling::NonDGPImpSampling(), NonDGPMSABayesCalibration::NonDGPMSABayesCalibration(), NonDInterval::NonDInterval(), NonDLocalInterval::NonDLocalInterval(), NonDLocalReliability::NonDLocalReliability(), NonDMultilevelFunctionTrain::NonDMultilevelFunctionTrain(), NonDMultilevelPolynomialChaos::NonDMultilevelPolynomialChaos(), NonDMultilevelSampling::NonDMultilevelSampling(), NonDMultilevelStochCollocation::NonDMultilevelStochCollocation(), NonDNonHierarchSampling::NonDNonHierarchSampling(), NonDQuadrature::NonDQuadrature(), NonDSampling::NonDSampling(), NonDSparseGrid::NonDSparseGrid(), NonDStochCollocation::NonDStochCollocation(), NonDSurrogateExpansion::NonDSurrogateExpansion(), OptDartsOptimizer::OptDartsOptimizer(), ParamStudy::ParamStudy(), NonDAdaptiveSampling::parse_options(), NonlinearCGOptimizer::parse_options(), Iterator::problem_description_db(), NonDC3FunctionTrain::resolve_refinement(), APPSOptimizer::set_apps_parameters(), ROLOptimizer::set_rol_parameters(), COLINOptimizer::set_solver_parameters(), SNLLLeastSq::SNLLLeastSq(), SNLLOptimizer::SNLLOptimizer(), COLINOptimizer::solver_setup(), and SurrBasedGlobalMinimizer::SurrBasedGlobalMinimizer().
maxEvalConcurrency
int maxEvalConcurrency protected
maximum number of concurrent model evaluations
This is important for parallel configuration init/set/free and may be set within empty envelope instances. Therefore, it cannot be pushed down into Analyzer/Minimizer derived classes.
Referenced by NonDPolynomialChaos::config_expectation(), NonDPolynomialChaos::config_regression(), NonDC3FunctionTrain::config_regression(), DDACEDesignCompExp::DDACEDesignCompExp(), Iterator::derived_free_communicators(), NonDAdaptiveSampling::derived_free_communicators(), NonDBayesCalibration::derived_free_communicators(), NonDExpansion::derived_free_communicators(), NonDGlobalInterval::derived_free_communicators(), NonDGlobalReliability::derived_free_communicators(), NonDGPImpSampling::derived_free_communicators(), NonDLocalInterval::derived_free_communicators(), NonDLocalReliability::derived_free_communicators(), NonDPolynomialChaos::derived_free_communicators(), SurrBasedMinimizer::derived_free_communicators(), Iterator::derived_init_communicators(), NonDAdaptiveSampling::derived_init_communicators(), NonDBayesCalibration::derived_init_communicators(), NonDExpansion::derived_init_communicators(), NonDGlobalInterval::derived_init_communicators(), NonDGlobalReliability::derived_init_communicators(), NonDGPImpSampling::derived_init_communicators(), NonDLocalInterval::derived_init_communicators(), NonDLocalReliability::derived_init_communicators(), NonDPolynomialChaos::derived_init_communicators(), SurrBasedMinimizer::derived_init_communicators(), Iterator::derived_set_communicators(), NonD::derived_set_communicators(), NonDBayesCalibration::derived_set_communicators(), NonDExpansion::derived_set_communicators(), NonDLocalReliability::derived_set_communicators(), NonDPolynomialChaos::derived_set_communicators(), SurrBasedMinimizer::derived_set_communicators(), Iterator::estimate_partition_bounds(), FSUDesignCompExp::FSUDesignCompExp(), NonDCubature::initialize_grid(), NonDQuadrature::initialize_grid(), NonDSparseGrid::initialize_grid(), EffGlobalMinimizer::initialize_sub_problem(), NonDExpansion::initialize_u_space_grid(), JEGAOptimizer::JEGAOptimizer(), Iterator::maximum_evaluation_concurrency(), NonDAdaptImpSampling::NonDAdaptImpSampling(), NonDBayesCalibration::NonDBayesCalibration(), NonDCubature::NonDCubature(), NonDGlobalInterval::NonDGlobalInterval(), NonDGlobalReliability::NonDGlobalReliability(), NonDHierarchSampling::NonDHierarchSampling(), NonDLHSInterval::NonDLHSInterval(), NonDNonHierarchSampling::NonDNonHierarchSampling(), NonDQuadrature::NonDQuadrature(), NonDSampling::NonDSampling(), NonDSparseGrid::NonDSparseGrid(), Analyzer::num_samples(), ParamStudy::ParamStudy(), PSUADEDesignCompExp::PSUADEDesignCompExp(), Iterator::resize_communicators(), RichExtrapVerification::RichExtrapVerification(), APPSOptimizer::set_apps_parameters(), COLINOptimizer::set_solver_parameters(), SNLLOptimizer::SNLLOptimizer(), and Iterator::update_from_model().
The documentation for this class was generated from the following files:
DakotaIterator.hpp
DakotaIterator.cpp