Dakota: NonDAdaptImpSampling Class Reference
NonDAdaptImpSampling Class Reference
Class for the Adaptive Importance Sampling methods within DAKOTA.
Public Member Functions
NonDAdaptImpSampling (ProblemDescDB &problem_db, Model &model)
standard constructor
NonDAdaptImpSampling (Model &model, unsigned short sample_type, int samples, int seed, const String &rng, bool vary_pattern, unsigned short is_type, bool cdf_flag, bool x_space_model, bool use_model_bounds, bool track_extreme)
alternate constructor for on-the-fly instantiations
~NonDAdaptImpSampling ()
destructor
bool resize ()
reinitializes iterator based on new variable size
void derived_init_communicators (ParLevLIter pl_iter)
derived class contributions to initializing the communicators associated with this Iterator instance
void derived_set_communicators (ParLevLIter pl_iter)
derived class contributions to setting the communicators associated with this Iterator instance
void derived_free_communicators (ParLevLIter pl_iter)
derived class contributions to freeing the communicators associated with this Iterator instance
void nested_variable_mappings (const SizetArray &c_index1, const SizetArray &di_index1, const SizetArray &ds_index1, const SizetArray &dr_index1, const ShortArray &c_target2, const ShortArray &di_target2, const ShortArray &ds_target2, const ShortArray &dr_target2)
set primaryA{CV,DIV,DRV}MapIndices, secondaryA{CV,DIV,DRV}MapTargets within derived Iterators; supports computation of higher-level sensitivities in nested contexts (e.g., derivatives of statistics w.r.t. inserted design variables)
void core_run ()
performs adaptive importance sampling and computes probability of failure
void print_results (std::ostream &s, short results_state=FINAL_RESULTS)
print the final statistics
unsigned short sampling_scheme () const
return importanceSamplingType
int refinement_samples () const
return refineSamples
void initialize (const RealVectorArray &full_points, bool x_space_data, size_t resp_index, Real initial_prob, Real failure_threshold)
initializes data needed for importance sampling: an initial set of points around which to sample, a failure threshold, an initial probability to refine, and flags to control transformations
void initialize (const RealMatrix &full_points, bool x_space_data, size_t resp_index, Real initial_prob, Real failure_threshold)
initializes data needed for importance sampling: an initial set of points around which to sample, a failure threshold, an initial probability to refine, and flags to control transformations
void initialize (const RealVector &full_point, bool x_space_data, size_t resp_index, Real initial_prob, Real failure_threshold)
initializes data needed for importance sampling: an initial point around which to sample, a failure threshold, an initial probability to refine, and flags to control transformations
Real final_probability ()
returns the final probability calculated by the importance sampling
const RealRealPairArray & extreme_values () const
return extremeValues
Public Member Functions inherited from NonDSampling
NonDSampling (Model &model, const RealMatrix &sample_matrix)
alternate constructor for evaluating and computing statistics for the provided set of samples
~NonDSampling ()
destructor
void compute_statistics (const RealMatrix &vars_samples, const IntResponseMap &resp_samples)
For the input sample set, computes mean, standard deviation, and probability/reliability/response levels (aleatory uncertainties) or intervals (epsitemic or mixed uncertainties)
void compute_intervals (RealRealPairArray &extreme_fns)
called by compute_statistics() to calculate min/max intervals using allResponses
void compute_intervals (const IntResponseMap &samples)
called by compute_statistics() to calculate extremeValues from samples
void compute_intervals (RealRealPairArray &extreme_fns, const IntResponseMap &samples)
called by compute_statistics() to calculate min/max intervals using samples
void compute_moments (const RealVectorArray &fn_samples)
calculates sample moments from a matrix of observations for a set of QoI
void compute_moments (const IntResponseMap &samples)
calculate sample moments and confidence intervals from a map of response observations
void compute_moments (const IntResponseMap &samples, RealMatrix &moment_stats, RealMatrix &moment_grads, RealMatrix &moment_conf_ints, short moments_type, const StringArray &labels)
convert IntResponseMap to RealVectorArray and invoke helpers
void compute_moment_gradients (const RealVectorArray &fn_samples, const RealMatrixArray &grad_samples, const RealMatrix &moment_stats, RealMatrix &moment_grads, short moments_type)
compute moment_grads from function and gradient samples
void compute_moment_confidence_intervals (const RealMatrix &moment_stats, RealMatrix &moment_conf_ints, const SizetArray &sample_counts, short moments_type)
compute moment confidence intervals from moment values
void archive_moments (size_t inc_id=0)
archive moment statistics in results DB
void archive_moment_confidence_intervals (size_t inc_id=0)
archive moment confidence intervals in results DB
void archive_extreme_responses (size_t inc_id=0)
archive extreme values (epistemic result) in results DB
void compute_level_mappings (const IntResponseMap &samples)
called by compute_statistics() to calculate CDF/CCDF mappings of z to p/beta and of p/beta to z as well as PDFs
void print_statistics (std::ostream &s) const
prints the statistics computed in compute_statistics()
void print_intervals (std::ostream &s) const
prints the intervals computed in compute_intervals() with default qoi_type and moment_labels
void print_intervals (std::ostream &s, String qoi_type, const StringArray &interval_labels) const
prints the intervals computed in compute_intervals()
void print_moments (std::ostream &s) const
prints the moments computed in compute_moments() with default qoi_type and moment_labels
void print_moments (std::ostream &s, String qoi_type, const StringArray &moment_labels) const
prints the moments computed in compute_moments()
void print_wilks_stastics (std::ostream &s) const
prints the Wilks stastics
void update_final_statistics ()
update finalStatistics from minValues/maxValues, momentStats, and computedProbLevels/computedRelLevels/computedRespLevels
void transform_samples (Pecos::ProbabilityTransformation &nataf, bool x_to_u=true)
transform allSamples imported by alternate constructor. This is needed since random variable distribution parameters are not updated until run time and an imported sample_matrix is typically in x-space.
void transform_samples (Pecos::ProbabilityTransformation &nataf, RealMatrix &sample_matrix, size_t num_samples=0, bool x_to_u=true)
transform the specified samples matrix from x to u or u to x
unsigned short sampling_scheme () const
return sampleType
const String & random_number_generator () const
return rngName
Public Member Functions inherited from NonD
void requested_levels (const RealVectorArray &req_resp_levels, const RealVectorArray &req_prob_levels, const RealVectorArray &req_rel_levels, const RealVectorArray &req_gen_rel_levels, short resp_lev_tgt, short resp_lev_tgt_reduce, bool cdf_flag, bool pdf_output)
set requestedRespLevels, requestedProbLevels, requestedRelLevels, requestedGenRelLevels, respLevelTarget, cdfFlag, and pdfOutput (used in combination with alternate ctors)
void print_level_mappings (std::ostream &s) const
prints the z/p/beta/beta* mappings reflected in {requested,computed}{Resp,Prob,Rel,GenRel}Levels for default qoi_type and qoi_labels
void print_level_mappings (std::ostream &s, String qoi_type, const StringArray &qoi_labels) const
prints the z/p/beta/beta* mappings reflected in {requested,computed}{Resp,Prob,Rel,GenRel}Levels
void print_level_mappings (std::ostream &s, const RealVector &level_maps, bool moment_offset, const String &prepend="")
print level mapping statistics using optional pre-pend
bool pdf_output () const
get pdfOutput
void pdf_output (bool output)
set pdfOutput
short final_moments_type () const
get finalMomentsType
void final_moments_type (short type)
set finalMomentsType
Public Member Functions inherited from Analyzer
const VariablesArray & all_variables ()
return the complete set of evaluated variables
const RealMatrix & all_samples ()
return the complete set of evaluated samples
const IntResponseMap & all_responses () const
return the complete set of computed responses
Public Member Functions inherited from Iterator
Iterator (std::shared_ptr< TraitsBase > traits=std::shared_ptr< TraitsBase >(new TraitsBase()))
default constructor
Iterator (ProblemDescDB &problem_db, std::shared_ptr< TraitsBase > traits=std::shared_ptr< TraitsBase >(new TraitsBase()))
standard envelope constructor, which constructs its own model(s)
Iterator (ProblemDescDB &problem_db, Model &model, std::shared_ptr< TraitsBase > traits=std::shared_ptr< TraitsBase >(new TraitsBase()))
alternate envelope constructor which uses the ProblemDescDB but accepts a model from a higher level (meta-iterator) context, instead of constructing its own
Iterator (const String &method_string, Model &model, std::shared_ptr< TraitsBase > traits=std::shared_ptr< TraitsBase >(new TraitsBase()))
alternate envelope constructor for instantiations by name without the ProblemDescDB
Iterator (const Iterator &iterator)
copy constructor
virtual ~Iterator ()
destructor
Iterator operator= (const Iterator &iterator)
assignment operator
virtual void post_input ()
read tabular data for post-run mode
virtual void reset ()
restore initial state for repeated sub-iterator executions
virtual void nested_response_mappings (const RealMatrix &primary_coeffs, const RealMatrix &secondary_coeffs)
set primaryResponseCoefficients, secondaryResponseCoefficients within derived Iterators; Necessary for scalarization case in MLMC NonDMultilevelSampling to map scalarization in nested context
virtual void initialize_iterator (int job_index)
used by IteratorScheduler to set the starting data for a run
virtual void pack_parameters_buffer (MPIPackBuffer &send_buffer, int job_index)
used by IteratorScheduler to pack starting data for an iterator run
virtual void unpack_parameters_buffer (MPIUnpackBuffer &recv_buffer, int job_index)
used by IteratorScheduler to unpack starting data for an iterator run
virtual void unpack_parameters_initialize (MPIUnpackBuffer &recv_buffer, int job_index)
used by IteratorScheduler to unpack starting data and initialize an iterator run
virtual void pack_results_buffer (MPIPackBuffer &send_buffer, int job_index)
used by IteratorScheduler to pack results data from an iterator run
virtual void unpack_results_buffer (MPIUnpackBuffer &recv_buffer, int job_index)
used by IteratorScheduler to unpack results data from an iterator run
virtual void update_local_results (int job_index)
used by IteratorScheduler to update local results arrays
virtual bool accepts_multiple_points () const
indicates if this iterator accepts multiple initial points. Default return is false. Override to return true if appropriate.
virtual void initial_point (const Variables &pt)
sets the initial point for this iterator (user-functions mode for which Model updating is not used)
virtual void initial_point (const RealVector &pt)
sets the initial point (active continuous variables) for this iterator (user-functions mode for which Model updating is not used)
virtual void initial_points (const VariablesArray &pts)
sets the multiple initial points for this iterator. This should only be used if accepts_multiple_points() returns true.
virtual void variable_bounds (const RealVector &cv_lower_bnds, const RealVector &cv_upper_bnds)
assign nonlinear inequality and equality constraint allowables for this iterator (user-functions mode for which Model updating is not used)
virtual void linear_constraints (const RealMatrix &lin_ineq_coeffs, const RealVector &lin_ineq_lb, const RealVector &lin_ineq_ub, const RealMatrix &lin_eq_coeffs, const RealVector &lin_eq_tgt)
assign linear inequality and linear equality constraints for this iterator (user-functions mode for which Model updating is not used)
virtual void nonlinear_constraints (const RealVector &nln_ineq_lb, const RealVector &nln_ineq_ub, const RealVector &nln_eq_tgt)
assign nonlinear inequality and equality constraint allowables for this iterator (user-functions mode for which Model updating is not used)
virtual void initialize_graphics (int iterator_server_id=1)
initialize the 2D graphics window and the tabular graphics data
virtual void check_sub_iterator_conflict ()
detect any conflicts due to recursive use of the same Fortran solver
virtual unsigned short uses_method () const
return name of any enabling iterator used by this iterator
virtual void method_recourse ()
perform a method switch, if possible, due to a detected conflict
virtual void sampling_increment ()
increment to next in sequence of refinement samples
virtual IntIntPair estimate_partition_bounds ()
estimate the minimum and maximum partition sizes that can be utilized by this Iterator
virtual void declare_sources ()
Declare sources to the evaluations database.
void init_communicators (ParLevLIter pl_iter)
initialize the communicators associated with this Iterator instance
void set_communicators (ParLevLIter pl_iter)
set the communicators associated with this Iterator instance
void free_communicators (ParLevLIter pl_iter)
free the communicators associated with this Iterator instance
void resize_communicators (ParLevLIter pl_iter, bool reinit_comms)
Resize the communicators. This is called from the letter's resize()
void parallel_configuration_iterator (ParConfigLIter pc_iter)
set methodPCIter
ParConfigLIter parallel_configuration_iterator () const
return methodPCIter
void parallel_configuration_iterator_map (std::map< size_t, ParConfigLIter > pci_map)
set methodPCIterMap
std::map< size_t, ParConfigLIter > parallel_configuration_iterator_map () const
return methodPCIterMap
void run (ParLevLIter pl_iter)
invoke set_communicators(pl_iter) prior to run()
void run ()
orchestrate initialize/pre/core/post/finalize phases
void assign_rep (std::shared_ptr< Iterator > iterator_rep)
replaces existing letter with a new one
void iterated_model (const Model &model)
set the iteratedModel (iterators and meta-iterators using a single model instance)
Model & iterated_model ()
return the iteratedModel (iterators & meta-iterators using a single model instance)
ProblemDescDB & problem_description_db () const
return the problem description database (probDescDB)
ParallelLibrary & parallel_library () const
return the parallel library (parallelLib)
void method_name (unsigned short m_name)
set the method name to an enumeration value
unsigned short method_name () const
return the method name via its native enumeration value
void method_string (const String &m_str)
set the method name by string
String method_string () const
return the method name by string
String method_enum_to_string (unsigned short method_enum) const
convert a method name enumeration value to a string
unsigned short method_string_to_enum (const String &method_str) const
convert a method name string to an enumeration value
String submethod_enum_to_string (unsigned short submethod_enum) const
convert a sub-method name enumeration value to a string
const String & method_id () const
return the method identifier (methodId)
int maximum_evaluation_concurrency () const
return the maximum evaluation concurrency supported by the iterator
void maximum_evaluation_concurrency (int max_conc)
set the maximum evaluation concurrency supported by the iterator
size_t maximum_iterations () const
return the maximum iterations for this iterator
void maximum_iterations (size_t max_iter)
set the maximum iterations for this iterator
void convergence_tolerance (Real conv_tol)
set the method convergence tolerance (convergenceTol)
Real convergence_tolerance () const
return the method convergence tolerance (convergenceTol)
void output_level (short out_lev)
set the method output level (outputLevel)
short output_level () const
return the method output level (outputLevel)
void summary_output (bool summary_output_flag)
Set summary output control; true enables evaluation/results summary.
size_t num_final_solutions () const
return the number of solutions to retain in best variables/response arrays
void num_final_solutions (size_t num_final)
set the number of solutions to retain in best variables/response arrays
void active_set (const ActiveSet &set)
set the default active set (for use with iterators that employ evaluate_parameter_sets())
const ActiveSet & active_set () const
return the default active set (used by iterators that employ evaluate_parameter_sets())
void active_set_request_vector (const ShortArray &asv)
return the default active set request vector (used by iterators that employ evaluate_parameter_sets())
const ShortArray & active_set_request_vector () const
return the default active set request vector (used by iterators that employ evaluate_parameter_sets())
void active_set_request_values (short asv_val)
return the default active set request vector (used by iterators that employ evaluate_parameter_sets())
void sub_iterator_flag (bool si_flag)
set subIteratorFlag (and update summaryOutputFlag if needed)
bool is_null () const
function to check iteratorRep (does this envelope contain a letter?)
std::shared_ptr< Iterator > iterator_rep () const
returns iteratorRep for access to derived class member functions that are not mapped to the top Iterator level
virtual void eval_tag_prefix (const String &eval_id_str)
set the hierarchical eval ID tag prefix
std::shared_ptr< TraitsBase > traits () const
returns methodTraits for access to derived class member functions that are not mapped to the top TraitsBase level
bool top_level ()
Return whether the iterator is the top level iterator.
void top_level (bool tflag)
Set the iterator's top level flag.
Private Member Functions
void select_rep_points (const RealVectorArray &var_samples_u, const RealVector &fn_samples)
select representative points from a set of samples
void converge_statistics (bool cov_flag)
iteratively generate samples and select representative points until probability and (optionally) coefficient of variation converge
void generate_samples (RealVectorArray &var_samples_u)
generate a set of samples based on multimodal sampling density
void evaluate_samples (const RealVectorArray &var_samples_u, RealVector &fn_samples)
evaluate the model at the sample points and store the responses
void calculate_statistics (const RealVectorArray &var_samples_u, const RealVector &fn_samples, size_t total_samples, Real &sum_prob, Real &prob, bool compute_cov, Real &sum_var, Real &cov)
calculate the probability of exceeding the failure threshold and the coefficent of variation (if requested)
Real distance (const RealVector &a, const RealVector &b)
compute Euclidean distance between points a and b
Real recentered_density (const RealVector &sample_point)
compute density between a representative point and a sample point, assuming standard normal
Private Attributes
Model uSpaceModel
importance sampling is performed in standardized probability space. This u-space model is either passed in (alternate constructor for helper AIS) or constructed using ProbabilityTransformModel (standard constructor for stand-alone AIS)
unsigned short importanceSamplingType
integration type (is, ais, mmais) provided by input specification
bool initLHS
flag to identify if initial points are generated from an LHS sample
bool useModelBounds
flag to control if the sampler should respect the model bounds
bool invertProb
flag for inversion of probability values using 1.-p
bool trackExtremeValues
flag for tracking min/max values encountered when evaluating samples
int refineSamples
size of sample batch within each refinement iteration
size_t respFnIndex
the active response function index in the model to be sampled
RealVector designPoint
design subset for which uncertain subset is being sampled
RealVectorArray initPointsU
the original set of u-space samples passed in initialize()
RealVectorArray repPointsU
the set of representative points in u-space around which to sample
RealVector repWeights
the weight associated with each representative point
Real probEstimate
the probability estimate that is iteratively refined by importance sampling
Real failThresh
the failure threshold (z-bar) for the problem.
Additional Inherited Members
Static Public Member Functions inherited from NonDSampling
static void compute_moments (const RealVectorArray &fn_samples, SizetArray &sample_counts, RealMatrix &moment_stats, short moments_type, const StringArray &labels)
core compute_moments() implementation with all data as inputs
static void compute_moments (const RealVectorArray &fn_samples, RealMatrix &moment_stats, short moments_type)
core compute_moments() implementation with all data as inputs
static void compute_moments (const RealMatrix &fn_samples, RealMatrix &moment_stats, short moments_type)
alternate RealMatrix samples API for use by external clients
static void print_moments (std::ostream &s, const RealMatrix &moment_stats, const RealMatrix moment_cis, String qoi_type, short moments_type, const StringArray &moment_labels, bool print_cis)
core print moments that can be called without object
static int compute_wilks_sample_size (unsigned short order, Real alpha, Real beta, bool twosided=false)
calculates the number of samples using the Wilks formula Static so I can test without instantiating a NonDSampling object - RWH
static Real compute_wilks_residual (unsigned short order, int nsamples, Real alpha, Real beta, bool twosided)
Helper function - calculates the Wilks residual.
static Real compute_wilks_alpha (unsigned short order, int nsamples, Real beta, bool twosided=false)
calculates the alpha paramter given number of samples using the Wilks formula Static so I can test without instantiating a NonDSampling object - RWH
static Real compute_wilks_beta (unsigned short order, int nsamples, Real alpha, bool twosided=false)
calculates the beta paramter given number of samples using the Wilks formula Static so I can test without instantiating a NonDSampling object - RWH
static Real get_wilks_alpha_min ()
Get the lower and upper bounds supported by Wilks bisection solves.
static Real get_wilks_alpha_max ()
static Real get_wilks_beta_min ()
static Real get_wilks_beta_max ()
Protected Member Functions inherited from NonDSampling
NonDSampling (ProblemDescDB &problem_db, Model &model)
constructor
NonDSampling (unsigned short method_name, Model &model, unsigned short sample_type, size_t samples, int seed, const String &rng, bool vary_pattern, short sampling_vars_mode)
alternate constructor for sample generation and evaluation "on the fly"
NonDSampling (unsigned short sample_type, size_t samples, int seed, const String &rng, const RealVector &lower_bnds, const RealVector &upper_bnds)
alternate constructor for sample generation "on the fly"
NonDSampling (unsigned short sample_type, size_t samples, int seed, const String &rng, const RealVector &means, const RealVector &std_devs, const RealVector &lower_bnds, const RealVector &upper_bnds, RealSymMatrix &correl)
alternate constructor for sample generation of correlated normals "on the fly"
void pre_run ()
pre-run portion of run (optional); re-implemented by Iterators which can generate all Variables (parameter sets) a priori
void core_run ()
size_t num_samples () const
void sampling_reset (size_t min_samples, bool all_data_flag, bool stats_flag)
resets number of samples and sampling flags
void sampling_reference (size_t samples_ref)
set reference number of samples, which is a lower bound during reset
void random_seed (int seed)
assign randomSeed
void vary_pattern (bool pattern_flag)
set varyPattern
void get_parameter_sets (Model &model)
Uses lhsDriver to generate a set of samples from the distributions/bounds defined in the incoming model.
void get_parameter_sets (Model &model, const size_t num_samples, RealMatrix &design_matrix)
Uses lhsDriver to generate a set of samples from the distributions/bounds defined in the incoming model and populates the specified design matrix.
void get_parameter_sets (Model &model, const size_t num_samples, RealMatrix &design_matrix, bool write_msg)
core of get_parameter_sets that accepts message print control
void get_parameter_sets (const RealVector &lower_bnds, const RealVector &upper_bnds)
Uses lhsDriver to generate a set of uniform samples over lower_bnds/upper_bnds.
void get_parameter_sets (const RealVector &means, const RealVector &std_devs, const RealVector &lower_bnds, const RealVector &upper_bnds, RealSymMatrix &correl)
Uses lhsDriver to generate a set of normal samples.
void update_model_from_sample (Model &model, const Real *sample_vars)
Override default update of continuous vars only.
void sample_to_variables (const Real *sample_vars, Variables &vars)
override default mapping of continuous variables only
void variables_to_sample (const Variables &vars, Real *sample_vars)
override default mapping of continuous variables only
const RealSymMatrix & response_error_estimates () const
return error estimates associated with each of the finalStatistics
virtual bool seed_updated ()
detect whether the seed has been updated since the most recent sample set generation
virtual void active_set_mapping ()
in the case of sub-iteration, map from finalStatistics.active_set() requests to activeSet used in evaluate_parameter_sets()
void initialize_sample_driver (bool write_message, size_t num_samples)
increments numLHSRuns, sets random seed, and initializes lhsDriver
void mode_counts (const Variables &vars, size_t &cv_start, size_t &num_cv, size_t &div_start, size_t &num_div, size_t &dsv_start, size_t &num_dsv, size_t &drv_start, size_t &num_drv) const
compute sampled subsets (all, active, uncertain) within all variables (acv/adiv/adrv) from samplingVarsMode and model
void mode_bits (const Variables &vars, BitArray &active_vars, BitArray &active_corr) const
define subset views for sampling modes
Protected Member Functions inherited from NonD
NonD (ProblemDescDB &problem_db, Model &model)
constructor
NonD (unsigned short method_name, Model &model)
alternate constructor for sample generation and evaluation "on the fly"
NonD (unsigned short method_name, const RealVector &lower_bnds, const RealVector &upper_bnds)
alternate constructor for sample generation "on the fly"
~NonD ()
destructor
void initialize_run ()
utility function to perform common operations prior to pre_run(); typically memory initialization; setting of instance pointers
void finalize_run ()
utility function to perform common operations following post_run(); deallocation and resetting of instance pointers
const Response & response_results () const
return the final statistics from the nondeterministic iteration
void response_results_active_set (const ActiveSet &set)
set the active set within finalStatistics
virtual void initialize_response_covariance ()
initializes respCovariance
virtual void initialize_final_statistics ()
initializes finalStatistics for storing NonD final results
virtual bool discrepancy_sample_counts () const
flag identifying whether sample counts correspond to level discrepancies
void pull_level_mappings (RealVector &level_maps, size_t offset)
concatenate computed{Resp,Prob,Rel,GenRel}Levels into level_maps
void push_level_mappings (const RealVector &level_maps, size_t offset)
update computed{Resp,Prob,Rel,GenRel}Levels from level_maps
void configure_sequence (size_t &num_steps, size_t &secondary_index, short &seq_type)
configure fidelity/level counts from model hierarchy
void configure_cost (unsigned short num_steps, bool multilevel, RealVector &cost)
extract cost estimates from model hierarchy (forms or resolutions)
bool query_cost (unsigned short num_steps, bool multilevel, RealVector &cost)
extract cost estimates from model hierarchy, if available
bool query_cost (unsigned short num_steps, Model &model, RealVector &cost)
extract cost estimates from model hierarchy, if available
bool valid_cost_values (const RealVector &cost)
test cost for valid values > 0
void load_pilot_sample (const SizetArray &pilot_spec, size_t num_steps, SizetArray &delta_N_l)
distribute pilot sample specification across model forms or levels
void load_pilot_sample (const SizetArray &pilot_spec, short seq_type, const Sizet3DArray &N_l, Sizet2DArray &delta_N_l)
distribute pilot sample specification across model forms and levels
template<typename ArrayType >
void inflate_approx_samples (const ArrayType &N_l, bool multilev, size_t secondary_index, std::vector< ArrayType > &N_l_vec)
update the relevant slice of N_l_3D from the final 2D multilevel or 2D multifidelity sample profile
template<typename ArrayType >
void inflate_sequence_samples (const ArrayType &N_l, bool multilev, size_t secondary_index, std::vector< ArrayType > &N_l_vec)
update the relevant slice of N_l_3D from the final 2D multilevel or 2D multifidelity sample profile
void resize_final_statistics_gradients ()
resizes finalStatistics::functionGradients based on finalStatistics ASV
void update_aleatory_final_statistics ()
update finalStatistics::functionValues from momentStats and computed{Prob,Rel,GenRel,Resp}Levels
void update_system_final_statistics ()
update system metrics from component metrics within finalStatistics
void update_system_final_statistics_gradients ()
update finalStatistics::functionGradients
void initialize_level_mappings ()
size computed{Resp,Prob,Rel,GenRel}Levels
void compute_densities (const RealRealPairArray &min_max_fns, bool prob_refinement=false, bool all_levels_computed=false)
compute the PDF bins from the CDF/CCDF values and store in computedPDF{Abscissas,Ordinates}
void print_densities (std::ostream &s) const
output the PDFs reflected in computedPDF{Abscissas,Ordinates} using default qoi_type and pdf_labels
void print_densities (std::ostream &s, String qoi_type, const StringArray &pdf_labels) const
output the PDFs reflected in computedPDF{Abscissas,Ordinates}
void print_system_mappings (std::ostream &s) const
print system series/parallel mappings for response levels
void print_multilevel_evaluation_summary (std::ostream &s, const SizetArray &N_m)
print evaluation summary for multilevel sampling across 1D level profile
void print_multilevel_evaluation_summary (std::ostream &s, const Sizet2DArray &N_m)
print evaluation summary for multilevel sampling across 2D level+QoI profile
void print_multilevel_discrepancy_summary (std::ostream &s, const SizetArray &N_m)
print evaluation summary for multilevel sampling across 1D level profile for discrepancy across levels
void print_multilevel_discrepancy_summary (std::ostream &s, const SizetArray &N_m, const SizetArray &N_mp1)
print evaluation summary for multilevel sampling across 1D level profile for discrepancy across model forms
void print_multilevel_discrepancy_summary (std::ostream &s, const Sizet2DArray &N_m)
print evaluation summary for multilevel sampling across 2D level+QoI profile for discrepancy across levels
void print_multilevel_discrepancy_summary (std::ostream &s, const Sizet2DArray &N_m, const Sizet2DArray &N_mp1)
print evaluation summary for multilevel sampling across 2D level+QoI profile for discrepancy across model forms
template<typename ArrayType >
void print_multilevel_model_summary (std::ostream &s, const std::vector< ArrayType > &N_samp, String type, short seq_type, bool discrep_flag)
print evaluation summary for multilevel sampling across 2D model+level profile (allocations) or 3D model+level+QoI profile (actual)
void construct_lhs (Iterator &u_space_sampler, Model &u_model, unsigned short sample_type, int num_samples, int seed, const String &rng, bool vary_pattern, short sampling_vars_mode=ACTIVE)
assign a NonDLHSSampling instance within u_space_sampler
unsigned short sub_optimizer_select (unsigned short requested_sub_method, unsigned short default_sub_method=SUBMETHOD_NPSOL)
utility for vetting sub-method request against optimizers within the package configuration
size_t one_sided_delta (Real current, Real target)
compute a one-sided sample increment for multilevel methods to move current sampling level to a new target
size_t one_sided_delta (const SizetArray &current, const RealVector &targets, size_t power)
compute a one-sided sample increment for multilevel methods to move current sampling level to a new target
size_t one_sided_delta (const SizetArray &current, Real target, size_t power)
compute a one-sided sample increment for multilevel methods to move current sampling level to a new target
bool differ (size_t N_alloc_ij, const SizetArray &N_actual_ij) const
return true if fine-grained reporting differs from coarse-grained
bool differ (const SizetArray &N_alloc_i, const Sizet2DArray &N_actual_i) const
return true if fine-grained reporting differs from coarse-grained
bool differ (const Sizet2DArray &N_alloc, const Sizet3DArray &N_actual) const
return true if fine-grained reporting differs from coarse-grained
void archive_allocate_mappings ()
allocate results array storage for distribution mappings
void archive_from_resp (size_t fn_index, size_t inc_id=0)
archive the mappings from specified response levels for specified fn
void archive_to_resp (size_t fn_index, size_t inc_id=0)
archive the mappings to computed response levels for specified fn and (optional) increment id.
void archive_allocate_pdf ()
allocate results array storage for pdf histograms
void archive_pdf (size_t fn_index, size_t inc_id=0)
archive a single pdf histogram for specified function
void archive_equiv_hf_evals (const Real equiv_hf_evals)
archive the equivalent number of HF evals (used by ML/MF methods)
Protected Member Functions inherited from Analyzer
Analyzer ()
default constructor
Analyzer (ProblemDescDB &problem_db, Model &model)
standard constructor
Analyzer (unsigned short method_name, Model &model)
alternate constructor for instantiations "on the fly" with a Model
Analyzer (unsigned short method_name)
alternate constructor for instantiations "on the fly" without a Model
~Analyzer ()
destructor
virtual void update_model_from_variables (Model &model, const Variables &vars)
update model's current variables with data from vars
void update_from_model (const Model &model)
set inherited data attributes based on extractions from incoming model
void post_run (std::ostream &s)
post-run portion of run (optional); verbose to print results; re-implemented by Iterators that can read all Variables/Responses and perform final analysis phase in a standalone way
void pre_output ()
const Model & algorithm_space_model () const
const Variables & variables_results () const
return a single final iterator solution (variables)
const VariablesArray & variables_array_results ()
return multiple final iterator solutions (variables). This should only be used if returns_multiple_points() returns true.
const ResponseArray & response_array_results ()
return multiple final iterator solutions (response). This should only be used if returns_multiple_points() returns true.
bool compact_mode () const
returns Analyzer::compactMode
bool returns_multiple_points () const
indicates if this iterator returns multiple final points. Default return is false. Override to return true if appropriate.
void evaluate_parameter_sets (Model &model, bool log_resp_flag, bool log_best_flag)
perform function evaluations to map parameter sets (allVariables) into response sets (allResponses)
void get_vbd_parameter_sets (Model &model, size_t num_samples)
generate replicate parameter sets for use in variance-based decomposition
void compute_vbd_stats (const size_t num_samples, const IntResponseMap &resp_samples)
compute VBD-based Sobol indices
void archive_sobol_indices () const
archive VBD-based Sobol indices
virtual void archive_model_variables (const Model &, size_t idx) const
archive model evaluation points
virtual void archive_model_response (const Response &, size_t idx) const
archive model evaluation responses
void read_variables_responses (int num_evals, size_t num_vars)
convenience function for reading variables/responses (used in derived classes post_input)
void print_sobol_indices (std::ostream &s) const
Printing of VBD results.
void samples_to_variables_array (const RealMatrix &sample_matrix, VariablesArray &vars_array)
convert samples array to variables array; e.g., allSamples to allVariables
void variables_array_to_samples (const VariablesArray &vars_array, RealMatrix &sample_matrix)
convert variables array to samples array; e.g., allVariables to allSamples
Protected Member Functions inherited from Iterator
Iterator (BaseConstructor, ProblemDescDB &problem_db, std::shared_ptr< TraitsBase > traits=std::shared_ptr< TraitsBase >(new TraitsBase()))
constructor initializes the base class part of letter classes (BaseConstructor overloading avoids infinite recursion in the derived class constructors - Coplien, p. 139)
Iterator (NoDBBaseConstructor, unsigned short method_name, Model &model, std::shared_ptr< TraitsBase > traits=std::shared_ptr< TraitsBase >(new TraitsBase()))
alternate constructor for base iterator classes constructed on the fly
Iterator (NoDBBaseConstructor, unsigned short method_name, std::shared_ptr< TraitsBase > traits=std::shared_ptr< TraitsBase >(new TraitsBase()))
alternate constructor for base iterator classes constructed on the fly
Iterator (NoDBBaseConstructor, Model &model, size_t max_iter, size_t max_eval, Real conv_tol, std::shared_ptr< TraitsBase > traits=std::shared_ptr< TraitsBase >(new TraitsBase()))
alternate envelope constructor for instantiations without ProblemDescDB
virtual const VariablesArray & initial_points () const
gets the multiple initial points for this iterator. This will only be meaningful after a call to initial_points mutator.
StrStrSizet run_identifier () const
get the unique run identifier based on method name, id, and number of executions
void initialize_model_graphics (Model &model, int iterator_server_id)
helper function that encapsulates initialization operations, modular on incoming Model instance
void export_final_surrogates (Model &data_fit_surr_model)
export final surrogates generated, e.g., GP in EGO and friends
Static Protected Member Functions inherited from Iterator
static void gnewton_set_recast (const Variables &recast_vars, const ActiveSet &recast_set, ActiveSet &sub_model_set)
conversion of request vector values for the Gauss-Newton Hessian approximation
Protected Attributes inherited from NonDSampling
int seedSpec
the user seed specification (default is 0)
int randomSeed
the current seed
const int samplesSpec
initial specification of number of samples
size_t samplesRef
reference number of samples updated for refinement
size_t numSamples
the current number of samples to evaluate
String rngName
name of the random number generator
unsigned short sampleType
the sample type: default, random, lhs, incremental random, or incremental lhs
bool wilksFlag
flags use of Wilks formula to calculate num samples
unsigned short wilksOrder
Real wilksAlpha
Real wilksBeta
short wilksSidedness
RealMatrix momentGrads
gradients of standardized or central moments of response functions, as determined by finalMomentsType. Calculated in compute_moments() and indexed as (var,moment) when moment id runs from 1:2*numFunctions.
RealSymMatrix finalStatErrors
standard errors (estimator std deviation) for each of the finalStatistics
int samplesIncrement
current increment in a sequence of samples
Pecos::LHSDriver lhsDriver
the C++ wrapper for the F90 LHS library
size_t numLHSRuns
counter for number of sample set generations
bool statsFlag
flags computation/output of statistics
bool allDataFlag
flags update of allResponses (allVariables or allSamples already defined)
short samplingVarsMode
the sampling mode: ALEATORY_UNCERTAIN{,_UNIFORM}, EPISTEMIC_UNCERTAIN{,_UNIFORM}, UNCERTAIN{,_UNIFORM}, ACTIVE{,_UNIFORM}, or ALL{,_UNIFORM}. This is a secondary control on top of the variables view that allows sampling over subsets of variables that may differ from the view.
short sampleRanksMode
mode for input/output of LHS sample ranks: IGNORE_RANKS, GET_RANKS, SET_RANKS, or SET_GET_RANKS
bool varyPattern
flag for generating a sequence of seed values within multiple get_parameter_sets() calls so that these executions (e.g., for SBO/SBNLS) are not repeated, but are still repeatable
RealMatrix sampleRanks
data structure to hold the sample ranks
SensAnalysisGlobal nonDSampCorr
initialize statistical post processing
bool backfillDuplicates
flags whether to use backfill to enforce uniqueness of discrete LHS samples
RealRealPairArray extremeValues
Minimum and maximum values of response functions for epistemic calculations (calculated in compute_intervals()),.
bool functionMomentsComputed
Function moments have been computed; used to determine whether to archive the moments.
Protected Attributes inherited from NonD
NonD * prevNondInstance
pointer containing previous value of nondInstance
size_t startCAUV
starting index of continuous aleatory uncertain variables within active continuous variables (convenience for managing offsets)
size_t numCAUV
number of active continuous aleatory uncertain variables
bool epistemicStats
flag for computing interval-type metrics instead of integrated metrics If any epistemic vars are active in a metric evaluation, then flag is set.
RealMatrix momentStats
standardized or central resp moments, as determined by finalMomentsType. Calculated in compute_moments()) and indexed as (moment,fn).
RealVectorArray requestedRespLevels
requested response levels for all response functions
RealVectorArray computedProbLevels
output probability levels for all response functions resulting from requestedRespLevels
RealVectorArray computedRelLevels
output reliability levels for all response functions resulting from requestedRespLevels
RealVectorArray computedGenRelLevels
output generalized reliability levels for all response functions resulting from requestedRespLevels
short respLevelTarget
indicates mapping of z->p (PROBABILITIES), z->beta (RELIABILITIES), or z->beta* (GEN_RELIABILITIES)
short respLevelTargetReduce
indicates component or system series/parallel failure metrics
RealVectorArray requestedProbLevels
requested probability levels for all response functions
RealVectorArray requestedRelLevels
requested reliability levels for all response functions
RealVectorArray requestedGenRelLevels
requested generalized reliability levels for all response functions
RealVectorArray computedRespLevels
output response levels for all response functions resulting from requestedProbLevels, requestedRelLevels, or requestedGenRelLevels
size_t totalLevelRequests
total number of levels specified within requestedRespLevels, requestedProbLevels, and requestedRelLevels
bool cdfFlag
flag for type of probabilities/reliabilities used in mappings: cumulative/CDF (true) or complementary/CCDF (false)
bool pdfOutput
flag for managing output of response probability density functions (PDFs)
RealVectorArray computedPDFAbscissas
sorted response PDF intervals bounds extracted from min/max sample and requested/computedRespLevels (vector lengths = num bins + 1)
RealVectorArray computedPDFOrdinates
response PDF densities computed from bin counts divided by (unequal) bin widths (vector lengths = num bins)
Response finalStatistics
final statistics from the uncertainty propagation used in strategies: response means, standard deviations, and probabilities of failure
short finalMomentsType
type of moments logged within finalStatistics: none, central, standard
size_t miPLIndex
index for the active ParallelLevel within ParallelConfiguration::miPLIters
BitArray pdfComputed
Whether PDF was computed for function i; used to determine whether a pdf should be archived.
Protected Attributes inherited from Analyzer
size_t numFunctions
number of response functions
size_t numContinuousVars
number of active continuous vars
size_t numDiscreteIntVars
number of active discrete integer vars
size_t numDiscreteStringVars
number of active discrete string vars
size_t numDiscreteRealVars
number of active discrete real vars
bool compactMode
switch for allSamples (compact mode) instead of allVariables (normal mode)
VariablesArray allVariables
array of all variables to be evaluated in evaluate_parameter_sets()
RealMatrix allSamples
compact alternative to allVariables
IntResponseMap allResponses
array of all responses to be computed in evaluate_parameter_sets()
StringArray allHeaders
array of headers to insert into output while evaluating allVariables
size_t numObjFns
number of objective functions
size_t numLSqTerms
number of least squares terms
RealPairPRPMultiMap bestVarsRespMap
map which stores best set of solutions
Protected Attributes inherited from Iterator
ProblemDescDB & probDescDB
class member reference to the problem description database
ParallelLibrary & parallelLib
class member reference to the parallel library
ParConfigLIter methodPCIter
the active ParallelConfiguration used by this Iterator instance
Model iteratedModel
the model to be iterated (for iterators and meta-iterators employing a single model instance)
size_t myModelLayers
number of Models locally (in Iterator or derived classes) wrapped around the initially passed in Model
unsigned short methodName
name of the iterator (the user's method spec)
Real convergenceTol
iteration convergence tolerance
size_t maxIterations
maximum number of iterations for the method
size_t maxFunctionEvals
maximum number of fn evaluations for the method
int maxEvalConcurrency
maximum number of concurrent model evaluations
ActiveSet activeSet
the response data requirements on each function evaluation
size_t numFinalSolutions
number of solutions to retain in best variables/response arrays
VariablesArray bestVariablesArray
collection of N best solution variables found during the study; always in context of Model originally passed to the Iterator (any in-flight Recasts must be undone)
ResponseArray bestResponseArray
collection of N best solution responses found during the study; always in context of Model originally passed to the Iterator (any in-flight Recasts must be undone)
bool subIteratorFlag
flag indicating if this Iterator is a sub-iterator (NestedModel::subIterator or DataFitSurrModel::daceIterator)
short outputLevel
output verbosity level: {SILENT,QUIET,NORMAL,VERBOSE,DEBUG}_OUTPUT
bool summaryOutputFlag
flag for summary output (evaluation stats, final results); default true, but false for on-the-fly (helper) iterators and sub-iterator use cases
ResultsManager & resultsDB
reference to the global iterator results database
EvaluationStore & evaluationsDB
reference to the global evaluation database
EvaluationsDBState evaluationsDBState
State of evaluations DB for this iterator.
ResultsNames resultsNames
valid names for iterator results
std::shared_ptr< TraitsBase > methodTraits
pointer that retains shared ownership of a TraitsBase object, or child thereof
bool topLevel
Whether this is the top level iterator.
bool exportSurrogate = false
whether to export final surrogates
String surrExportPrefix
base filename for exported surrogates
unsigned short surrExportFormat = NO_MODEL_FORMAT
(bitwise) format(s) to export
Static Protected Attributes inherited from NonD
static NonD * nondInstance
pointer to the active object instance used within static evaluator functions in order to avoid the need for static data
Detailed Description
Class for the Adaptive Importance Sampling methods within DAKOTA.
The NonDAdaptImpSampling implements the multi-modal adaptive importance sampling used for reliability calculations. (eventually we will want to broaden this). Need to add more detail to this description.
Constructor & Destructor Documentation
NonDAdaptImpSampling() [1/2]
NonDAdaptImpSampling (ProblemDescDB & problem_db, Model & model)
standard constructor
This is the primary constructor. It accepts a Model reference. It will perform refinement for all response QOI and all probability levels.
References Dakota::abort_handler(), Model::assign_rep(), NonD::finalMomentsType, ProblemDescDB::get_iv(), NonD::initialize_final_statistics(), Iterator::iteratedModel, NonDSampling::numSamples, Iterator::probDescDB, NonDAdaptImpSampling::refineSamples, NonDSampling::sampleType, NonDSampling::statsFlag, NonDAdaptImpSampling::useModelBounds, and NonDAdaptImpSampling::uSpaceModel.
NonDAdaptImpSampling() [2/2]
NonDAdaptImpSampling (Model & model, unsigned short sample_type, int refine_samples, int refine_seed, const String & rng, bool vary_pattern, unsigned short is_type, bool cdf_flag, bool x_space_model, bool use_model_bounds, bool track_extreme)
alternate constructor for on-the-fly instantiations
This is an alternate constructor for instantiations on the fly using a Model but no ProblemDescDB. It will perform refinement for one response QOI and one probability level (passed in initialize()).
References Model::assign_rep(), NonD::cdfFlag, NonDSampling::extremeValues, NonD::finalMomentsType, Iterator::maxEvalConcurrency, Analyzer::numFunctions, NonDAdaptImpSampling::refineSamples, NonDAdaptImpSampling::trackExtremeValues, NonDAdaptImpSampling::useModelBounds, and NonDAdaptImpSampling::uSpaceModel.
Member Function Documentation
initialize() [1/3]
void initialize (const RealVectorArray & acv_points, bool x_space_data, size_t resp_index, Real initial_prob, Real failure_threshold)
initializes data needed for importance sampling: an initial set of points around which to sample, a failure threshold, an initial probability to refine, and flags to control transformations
Initializes data using a vector array of starting points.
References NonDAdaptImpSampling::designPoint, NonDAdaptImpSampling::failThresh, NonDAdaptImpSampling::initPointsU, NonDAdaptImpSampling::invertProb, NonD::numCAUV, Model::probability_transformation(), NonDAdaptImpSampling::probEstimate, NonDAdaptImpSampling::respFnIndex, NonD::startCAUV, and NonDAdaptImpSampling::uSpaceModel.
Referenced by NonDAdaptImpSampling::core_run().
initialize() [2/3]
void initialize (const RealMatrix & acv_points, bool x_space_data, size_t resp_index, Real initial_prob, Real failure_threshold)
initializes data needed for importance sampling: an initial set of points around which to sample, a failure threshold, an initial probability to refine, and flags to control transformations
Initializes data using a matrix of starting points.
References NonDAdaptImpSampling::designPoint, NonDAdaptImpSampling::failThresh, NonDAdaptImpSampling::initPointsU, NonDAdaptImpSampling::invertProb, NonD::numCAUV, Analyzer::numContinuousVars, Model::probability_transformation(), NonDAdaptImpSampling::probEstimate, NonDAdaptImpSampling::respFnIndex, NonD::startCAUV, and NonDAdaptImpSampling::uSpaceModel.
initialize() [3/3]
void initialize (const RealVector & acv_point, bool x_space_data, size_t resp_index, Real initial_prob, Real failure_threshold)
initializes data needed for importance sampling: an initial point around which to sample, a failure threshold, an initial probability to refine, and flags to control transformations
Initializes data using only one starting point.
References NonDAdaptImpSampling::designPoint, NonDAdaptImpSampling::failThresh, NonDAdaptImpSampling::initPointsU, NonDAdaptImpSampling::invertProb, NonD::numCAUV, Model::probability_transformation(), NonDAdaptImpSampling::probEstimate, NonDAdaptImpSampling::respFnIndex, NonD::startCAUV, and NonDAdaptImpSampling::uSpaceModel.
The documentation for this class was generated from the following files:
NonDAdaptImpSampling.hpp
NonDAdaptImpSampling.cpp