Dakota: ResultsDBAny Class Reference
ResultsDBAny Class Reference
Public Member Functions
ResultsDBAny (const String &filename)
void insert (const StrStrSizet &iterator_id, const std::string &data_name, const boost::any &result, const MetaDataType &metadata) override
record addition with metadata map
void flush () const
Write data to file.
void insert (const StrStrSizet &iterator_id, const StringArray &location, const boost::any &data, const DimScaleMap &scales=DimScaleMap(), const AttributeArray &attrs=AttributeArray(), const bool &transpose=false) override
insert an arbitrary type (RealMatrix) with metadata
void allocate_vector (const StrStrSizet &iterator_id, const StringArray &location, ResultsOutputType stored_type, const int &len, const DimScaleMap &scales=DimScaleMap(), const AttributeArray &attrs=AttributeArray())
Pre-allocate a vector and (optionally) attach dimension scales and attributes. Insert elements using insert_into(...)
void allocate_matrix (const StrStrSizet &iterator_id, const StringArray &location, ResultsOutputType stored_type, const int &num_rows, const int &num_cols, const DimScaleMap &scales=DimScaleMap(), const AttributeArray &attrs=AttributeArray())
Pre-allocate a matrix and (optionally) attach dimension scales and attributes. Insert rows or columns using insert_into(...)
void insert_into (const StrStrSizet &iterator_id, const StringArray &location, const boost::any &data, const int &index, const bool &row)
Insert a row or column into a pre-allocated matrix.
void add_metadata_to_method (const StrStrSizet &iterator_id, const AttributeArray &attrs) override
Add key:value metadata to method.
void add_metadata_to_execution (const StrStrSizet &iterator_id, const AttributeArray &attrs) override
Add key:value metadata to execution.
void add_metadata_to_object (const StrStrSizet &iterator_id, const StringArray &location, const AttributeArray &attrs) override
Associate key:value metadata with the object at the location.
void add_metadata_to_study (const AttributeArray &attrs) override
Associate key:value metadata with the study.
Public Member Functions inherited from ResultsDBBase
template<typename StoredType >
void array_allocate (const StrStrSizet &iterator_id, const std::string &data_name, size_t array_size, const MetaDataType &metadata)
allocate an entry with sized array of the StoredType, e.g., array across response functions or optimization results sets
template<typename StoredType >
void array_insert (const StrStrSizet &iterator_id, const std::string &data_name, size_t index, const StoredType &sent_data)
insert sent_data in specified position in previously allocated array
Private Member Functions
void print_metadata (std::ostream &os, const MetaDataType &md) const
print metadata to ostream
void extract_data (const boost::any &dataholder, std::ostream &os) const
determine the type of contained data and output it to ostream
void output_data (const std::vector< double > &data, std::ostream &os) const
output data to ostream
void output_data (const std::vector< RealVector > &data, std::ostream &os) const
output data to ostream
void output_data (const std::vector< std::string > &data, std::ostream &os) const
output data to ostream
void output_data (const std::vector< std::vector< std::string > > &data, std::ostream &os) const
output data to ostream
void output_data (const std::vector< RealMatrix > &data, std::ostream &os) const
output data to ostream
void output_data (const RealMatrix &data, std::ostream &os) const
output data to ostream
Private Attributes
String fileName
name of database file
Additional Inherited Members
Protected Attributes inherited from ResultsDBBase
std::map< ResultsKeyType, ResultsValueType > iteratorData
core data storage (map from key to value type)
Detailed Description
Class: ResultsDBAny
Description: A map-based container to store DAKOTA Iterator results in underlying boost::anys, with optional metadata
Member Function Documentation
insert()
void insert (const StrStrSizet & iterator_id, const std::string & data_name, const boost::any & result, const MetaDataType & metadata) override virtual
record addition with metadata map
Add or update existing entry
Implements ResultsDBBase.
References ResultsDBBase::iteratorData, and Dakota::make_key().
extract_data()
void extract_data (const boost::any & dataholder, std::ostream & os) const private
determine the type of contained data and output it to ostream
Extract the data from the held any and map to supported concrete types int double RealVector (Teuchos::SerialDenseVector<int,double) RealMatrix (Teuchos::SerialDenseMatrix<int,double)
References ResultsDBAny::output_data().
Referenced by ResultsDBAny::flush().
The documentation for this class was generated from the following files:
ResultsDBAny.hpp
ResultsDBAny.cpp