Dakota: Matern32Kernel Class Reference
Matern32Kernel Class Reference
Stationary kernel with C^1 smooth realizations.
Public Member Functions
void compute_gram (const std::vector< MatrixXd > &dists2, const VectorXd &theta_values, MatrixXd &gram) override
Compute a Gram matrix given a vector of squared distances and kernel hyperparameters.
void compute_gram_derivs (const MatrixXd &gram, const std::vector< MatrixXd > &dists2, const VectorXd &theta_values, std::vector< MatrixXd > &gram_derivs) override
Compute the derivatives of the Gram matrix with respect to the kernel hyperparameters.
MatrixXd compute_first_deriv_pred_gram (const MatrixXd &pred_gram, const std::vector< MatrixXd > &mixed_dists, const VectorXd &theta_values, const int index) override
Compute the first derivatve of the prediction matrix for a given component.
MatrixXd compute_second_deriv_pred_gram (const MatrixXd &pred_gram, const std::vector< MatrixXd > &mixed_dists, const VectorXd &theta_values, const int index_i, const int index_j) override
Compute the second derivatve of the prediction matrix for a pair of components.
Private Attributes
const double sqrt3 = sqrt(3.)
Additional Inherited Members
Protected Member Functions inherited from Kernel
void compute_Dbar (const std::vector< MatrixXd > &cw_dists2, const VectorXd &theta_values, bool take_sqrt=true)
Compute the `‘Dbar’' matrices of scaled distances.
Protected Attributes inherited from Kernel
MatrixXd Dbar
MatrixXd Dbar2
Detailed Description
Stationary kernel with C^1 smooth realizations.
Member Function Documentation
compute_gram()
void compute_gram (const std::vector< MatrixXd > & dists2, const VectorXd & theta_values, MatrixXd & gram) override virtual
Compute a Gram matrix given a vector of squared distances and kernel hyperparameters.
Parameters
[in] dists2 Vector of squared distance matrices.
[in] theta_values Vector of hyperparameters.
[in,out] gram Gram matrix.
Returns
Gram matrix.
Implements Kernel.
References Kernel::compute_Dbar().
compute_gram_derivs()
void compute_gram_derivs (const MatrixXd & gram, const std::vector< MatrixXd > & dists2, const VectorXd & theta_values, std::vector< MatrixXd > & gram_derivs) override virtual
Compute the derivatives of the Gram matrix with respect to the kernel hyperparameters.
Parameters
[in] gram Gram Matrix
[in] dists2 Vector of squared distance matrices.
[in] theta_values Vector of hyperparameters.
[in,out] gram_derivs Vector of Gram matrix derivatives.
Returns
Derivatives of the Gram matrix w.r.t. the hyperparameters.
Implements Kernel.
References Kernel::compute_Dbar().
compute_first_deriv_pred_gram()
MatrixXd compute_first_deriv_pred_gram (const MatrixXd & pred_gram, const std::vector< MatrixXd > & mixed_dists, const VectorXd & theta_values, const int index) override virtual
Compute the first derivatve of the prediction matrix for a given component.
Parameters
[in] pred_gram Prediction Gram matrix - Rectangular matrix of kernel evaluations between the surrogate and prediction points.
[in] mixed_dists Component-wise signed distances between the prediction and build points.
[in] theta_values Vector of hyperparameters.
[in] index Specifies the component of the derivative.
Returns
first_deriv_pred_gram First derivative of the prediction Gram matrix for a given component.
Implements Kernel.
References dakota::surrogates::compute_cw_dists_squared(), Kernel::compute_Dbar(), and dakota::silence_unused_args().
compute_second_deriv_pred_gram()
MatrixXd compute_second_deriv_pred_gram (const MatrixXd & pred_gram, const std::vector< MatrixXd > & mixed_dists, const VectorXd & theta_values, const int index_i, const int index_j) override virtual
Compute the second derivatve of the prediction matrix for a pair of components.
Parameters
[in] pred_gram Prediction Gram matrix - Rectangular matrix of kernel evaluations between the surrogate and prediction points.
[in] mixed_dists Component-wise signed distances between the prediction and build points.
[in] theta_values Vector of hyperparameters.
[in] index_i Specifies the first component of the second derivative.
[in] index_j Specifies the second component of the second derivative.
Returns
second_deriv_pred_gram Second derivative of the prediction matrix for a pair of components.
Implements Kernel.
References dakota::silence_unused_args().
The documentation for this class was generated from the following files:
SurrogatesGPKernels.hpp
SurrogatesGPKernels.cpp