Dakota: dakota::util Namespace Reference
dakota::util Namespace Reference
namespace for new Dakota utilities module
Classes
class CholeskySolver
The CholeskySolver class is used to solve linear systems with a symmetric matrix with a pivoted Cholesky decomposition.
class DataScaler
The DataScaler class computes the scaling coefficients and scales a 2D data matrix with dimensions num_samples by num_features.
class LinearSolverBase
The LinearSolverBase class serves as an API for derived solvers.
class LUSolver
The LUSolver class is used to solve linear systems with the LU decomposition.
class NormalizationScaler
Normalizes the data using max and min feature values.
class NoScaler
Leaves the data unscaled.
class QRSolver
The QRSolver class solves the linear least squares problem with a QR decomposition.
class StandardizationScaler
Standardizes the data so the each feature has zero mean and unit variance.
class SVDSolver
The SVDSolver class is used to solve linear systems with the singular value decomposition.
Typedefs
using BimapMetrictypeStr = boost::bimap< METRIC_TYPE, std::string >
alias for Boost Bimap metric type <--> string
using SCALER_TYPE = DataScaler::SCALER_TYPE
alias for DataScaler's SCALER_TYPE
using BimapScalertypeStr = boost::bimap< SCALER_TYPE, std::string >
alias for Boost Bimap scaler type <--> string
using SOLVER_TYPE = LinearSolverBase::SOLVER_TYPE
alias for LinearSolverBase's SOLVER_TYPE
using BimapSolvertypeStr = boost::bimap< SOLVER_TYPE, std::string >
alias for Boost Bimap solver type <--> string
Enumerations
enum METRIC_TYPE {
SUM_SQUARED, MEAN_SQUARED, ROOT_MEAN_SQUARED, SUM_ABS,
MEAN_ABS, MAX_ABS, ABS_PERCENTAGE_ERROR, MEAN_ABS_PERCENTAGE_ERROR,
R_SQUARED
}
Enumeration for supported metric types.
Functions
void error (const std::string &msg)
Throws a std::runtime_error based on the message argument.
bool matrix_equals (const MatrixXi &A, const MatrixXi &B)
Tests whether two Eigen MatrixXi objects are equal.
bool matrix_equals (const MatrixXd &A, const MatrixXd &B, double tol)
Tests whether two Eigen MatrixXd objects are equal, within a given tolerance.
bool matrix_equals (const RealMatrix &A, const RealMatrix &B, double tol)
Tests whether two Teuchos RealMatrix objects are equal, within a given tolerance.
bool relative_allclose (const MatrixXd &A, const MatrixXd &B, const double tol)
Tests whether two Eigen MatrixXd objects relatively equal (element-wise) within a given tolerance.
double variance (const VectorXd &vec)
Calculates the variance based on an Eigen VectorXd of double values.
void populateVectorsFromFile (const std::string &filename, std::vector< VectorXd > &R, int num_datasets, int num_samples)
Populate a collection of vectors read in a from a text file assuming data layout is one dataset per row.
void populateMatricesFromFile (const std::string &filename, std::vector< MatrixXd > &S, int num_datasets, int num_vars, int num_samples)
Populate a collection of matrices read in a from a text file assuming data layout is a "column-major" stack of num_samples by num_vars matrices.
int n_choose_k (int n, int k)
Calculate Binomial coefficient n choose k.
void random_permutation (const int num_pts, const unsigned int seed, VectorXi &permutations)
Random permutation of int array.
void create_cv_folds (const int num_folds, const int num_pts, std::vector< VectorXi > &fold_indices, const int seed=22)
Generate indices for cross validation folds.
MatrixXd create_uniform_random_double_matrix (const int rows, const int cols)
Generate a real-valued matrix of uniformly distributed random values.
MatrixXd create_uniform_random_double_matrix (const int rows, const int cols, const unsigned int seed)
Generate a real-valued matrix of uniformly distributed random values.
MatrixXd create_uniform_random_double_matrix (const int rows, const int cols, const unsigned int seed, bool transform, const double low, const double high)
Generate a real-valued matrix of uniformly distributed random values.
template<typename T >
int num_nonzeros (const T &mat)
Caclulate and return number of nonzero entries in vector or matrix.
template<typename T1 , typename T2 >
void nonzero (const T1 &v, T2 &result)
Create a vector of indices based on nonzero entries in input vector.
template<typename T1 , typename T2 >
void append_columns (const T1 &new_cols, T2 &target)
Append columns of input matrix to existing matrix.
template<typename T >
double p_norm (const T &v, double p)
Caclulate and return p-norm of a vector.
METRIC_TYPE metric_type (const std::string &metric_name)
Convert the metric from string to enum.
double compute_metric (const VectorXd &p, const VectorXd &d, const std::string &metric_name)
Computes the difference between prediction and data vectors.
std::shared_ptr< DataScaler > scaler_factory (DataScaler::SCALER_TYPE scaler_type, const MatrixXd &unscaled_matrix)
Free function to construct DataScaler.
std::shared_ptr< LinearSolverBase > solver_factory (LinearSolverBase::SOLVER_TYPE type)
Free function to construct LinearSolverBase.
Variables
static BimapMetrictypeStr type_name_bimap
Bimap between metric types and names.
static BimapScalertypeStr type_name_bimap
Bimap between scaler types and names.
static BimapSolvertypeStr type_name_bimap
Bimap between solver types and names.
Detailed Description
namespace for new Dakota utilities module
Function Documentation
error()
void error (const std::string & msg)
Throws a std::runtime_error based on the message argument.
Parameters
[in] msg The error message to throw
Referenced by compute_metric(), create_cv_folds(), and matrix_equals().
matrix_equals() [1/3]
bool matrix_equals (const MatrixXi & A, const MatrixXi & B)
Tests whether two Eigen MatrixXi objects are equal.
Parameters
[in] A The first matrix to test
[in] B The second matrix to test
Returns
Whether the matrices are equal
matrix_equals() [2/3]
bool matrix_equals (const MatrixXd & A, const MatrixXd & B, double tol)
Tests whether two Eigen MatrixXd objects are equal, within a given tolerance.
Parameters
[in] A The first matrix to test
[in] B The second matrix to test
[in] tol The tolerance to use when comparing double values
Returns
Whether the matrices are equal to within tolerance
References error().
matrix_equals() [3/3]
bool matrix_equals (const RealMatrix & A, const RealMatrix & B, double tol)
Tests whether two Teuchos RealMatrix objects are equal, within a given tolerance.
Parameters
[in] A The first matrix to test
[in] B The second matrix to test
[in] tol The tolerance to use when comparing double values
Returns
Whether the matrices are equal to within tolerance
References error().
relative_allclose()
bool relative_allclose (const MatrixXd & A, const MatrixXd & B, const double tol)
Tests whether two Eigen MatrixXd objects relatively equal (element-wise) within a given tolerance.
Parameters
[in] A The first matrix to test
[in] B The second matrix to test
[in] tol The relative tolerance to use when comparing double values
Returns
Whether the matrices are relatively equal (within the tolerance)
variance()
double variance (const VectorXd & vec)
Calculates the variance based on an Eigen VectorXd of double values.
Parameters
[in] vec The vector
Returns
The calculated variance
populateVectorsFromFile()
void populateVectorsFromFile (const std::string & filename, std::vector< VectorXd > & R, int num_datasets, int num_samples)
Populate a collection of vectors read in a from a text file assuming data layout is one dataset per row.
Parameters
[in] filename The file that contains the data
[out] R The collection of vectors to be populated
[in] num_datasets The number of datasets to read in
[in] num_samples The number of data points (e.g. function values, build points) per dataset
populateMatricesFromFile()
void populateMatricesFromFile (const std::string & filename, std::vector< MatrixXd > & S, int num_datasets, int num_vars, int num_samples)
Populate a collection of matrices read in a from a text file assuming data layout is a "column-major" stack of num_samples by num_vars matrices.
Parameters
[in] filename The file that contains the data
[out] S The collection of vectors to be populated
[in] num_datasets The number of datasets to read in
[in] num_samples The number of data points (e.g. function values, build points) per dataset (row dim)
[in] num_vars The number of variables per dataset (column dim)
n_choose_k()
int n_choose_k (int n, int k)
Calculate Binomial coefficient n choose k.
Parameters
[in] n Number of elements in set
[in] k Number of elements in subset k where n >= k >= 0
Returns
Number of ways to choose an (unordered) subset of k elements from a fixed set of n elements
Referenced by dakota::surrogates::size_level_index_vector().
num_nonzeros()
int dakota::util::num_nonzeros (const T & mat)
Caclulate and return number of nonzero entries in vector or matrix.
Parameters
[in] mat Incoming vector or matrix
Returns
Number of nonzeros
Referenced by dakota::surrogates::compute_hyperbolic_level_indices(), dakota::surrogates::compute_hyperbolic_subdim_level_indices(), and nonzero().
nonzero()
void dakota::util::nonzero (const T1 & v, T2 & result)
Create a vector of indices based on nonzero entries in input vector.
Parameters
[in] v Incoming vector
[out] result Vector having values at nonzero locations of incoming vector and value equal to ordinal of occurrence
References num_nonzeros().
Referenced by dakota::surrogates::compute_hyperbolic_level_indices().
append_columns()
void dakota::util::append_columns (const T1 & new_cols, T2 & target)
Append columns of input matrix to existing matrix.
Parameters
[in] new_cols Incoming matrix of column vectors to append
[out] target Matrix to augment with appended columns
Referenced by dakota::surrogates::compute_hyperbolic_indices(), dakota::surrogates::compute_hyperbolic_level_indices(), and dakota::surrogates::compute_reduced_indices().
p_norm()
double dakota::util::p_norm (const T & v, double p)
Caclulate and return p-norm of a vector.
Parameters
[in] v Incoming vector
[in] p Order or norm to compute
Returns
p-norm of incoming vector
Referenced by dakota::surrogates::compute_hyperbolic_subdim_level_indices().
metric_type()
METRIC_TYPE metric_type (const std::string & metric_name)
Convert the metric from string to enum.
Parameters
[in] metric_name metric
Returns
converted metric
References type_name_bimap.
Referenced by compute_metric().
compute_metric()
double compute_metric (const VectorXd & p, const VectorXd & d, const std::string & metric_name)
Computes the difference between prediction and data vectors.
Parameters
[in] p prediction vector.
[in] d data vector.
[in] metric_name metric to compute.
Returns
the value of the computed metric.
References error(), and metric_type().
Referenced by Dakota::compute_regression_coeffs(), and Surrogate::evaluate_metrics().
scaler_factory()
std::shared_ptr< DataScaler > scaler_factory (DataScaler::SCALER_TYPE scaler_type, const MatrixXd & unscaled_matrix)
Free function to construct DataScaler.
Parameters
[in] scaler_type Which scaler to construct
[in] unscaled_matrix Unscaled data matrix - (num_samples by num_features)
Returns
Shared pointer to a DataScaler
Referenced by GaussianProcess::build(), and PolynomialRegression::build().
solver_factory()
std::shared_ptr< LinearSolverBase > solver_factory (LinearSolverBase::SOLVER_TYPE type)
Free function to construct LinearSolverBase.
Parameters
[in] type Which solver to construct
Returns
Shared pointer to a LinearSolverBase
Referenced by PolynomialRegression::build().
Variable Documentation
type_name_bimap [1/3]
BimapMetrictypeStr type_name_bimap static
Initial value:
=
    boost::assign::list_of<BimapMetrictypeStr::relation>
    (METRIC_TYPE::SUM_SQUARED, "sum_squared")
    (METRIC_TYPE::MEAN_SQUARED, "mean_squared")
    (METRIC_TYPE::ROOT_MEAN_SQUARED, "root_mean_squared")
    (METRIC_TYPE::SUM_ABS, "sum_abs")
    (METRIC_TYPE::MEAN_ABS, "mean_abs")
    (METRIC_TYPE::MAX_ABS, "max_abs")
    (METRIC_TYPE::ABS_PERCENTAGE_ERROR, "ape")
    (METRIC_TYPE::MEAN_ABS_PERCENTAGE_ERROR, "mape")
    (METRIC_TYPE::R_SQUARED, "rsquared")
Bimap between metric types and names.
Referenced by metric_type(), DataScaler::scaler_type(), and LinearSolverBase::solver_type().
type_name_bimap [2/3]
BimapScalertypeStr type_name_bimap static
Initial value:
=
    boost::assign::list_of<BimapScalertypeStr::relation>
    (SCALER_TYPE::NONE, "none")
    (SCALER_TYPE::STANDARDIZATION, "standardization")
    (SCALER_TYPE::MEAN_NORMALIZATION, "mean normalization")
    (SCALER_TYPE::MINMAX_NORMALIZATION, "min-max normalization")
Bimap between scaler types and names.
type_name_bimap [3/3]
BimapSolvertypeStr type_name_bimap static
Initial value:
=
    boost::assign::list_of<BimapSolvertypeStr::relation>
    (SOLVER_TYPE::CHOLESKY, "cholesky")
    (SOLVER_TYPE::EQ_CONS_LEAST_SQ_REGRESSION, "equality-constrained lsq regression")
    (SOLVER_TYPE::LASSO_REGRESSION, "lasso regression")
    (SOLVER_TYPE::LEAST_ANGLE_REGRESSION, "least angle regression")
    (SOLVER_TYPE::LU, "LU")
    (SOLVER_TYPE::ORTHOG_MATCH_PURSUIT, "orthogonal matching pursuit")
    (SOLVER_TYPE::QR_LEAST_SQ_REGRESSION, "QR lsq regression")
    (SOLVER_TYPE::SVD_LEAST_SQ_REGRESSION, "SVD")
Bimap between solver types and names.