Dakota: Dakota Namespace Reference
Dakota Namespace Reference
The primary namespace for DAKOTA.
Classes
class ActiveSet
Container class for active set tracking information. Contains the active set request vector and the derivative variables vector.
class ActiveSubspaceModel
Active subspace model for input (variable space) reduction.
class AdaptedBasisModel
Adapted basis model for input (variable space) reduction.
class AdapterModel
Derived model class which wraps call-back functions for solving minimization sub-problems.
class AddAttributeVisitor
Objects of this class are called by boost::appy_visitor to add attributes to HDF5 objects.
class Analyzer
Base class for NonD, DACE, and ParamStudy branches of the iterator hierarchy.
class ApplicationInterface
Derived class within the interface class hierarchy for supporting interfaces to simulation codes.
class Approximation
Base class for the approximation class hierarchy.
class ApproximationInterface
Derived class within the interface class hierarchy for supporting approximations to simulation-based results.
class APPSEvalMgr
Evaluation manager class for APPSPACK.
class APPSOptimizer
Wrapper class for HOPSPACK.
class AppsTraits
HOPSPACK-specific traits class.
class ApreproWriter
Utility used in derived write_core to write in aprepro format.
class AttachScaleVisitor
Objects of this class are called by boost::appy_visitor to add dimension scales (RealScale or StringScale) to HDF5 datasets.
struct BaseConstructor
Dummy struct for overloading letter-envelope constructors.
class BootstrapSampler
Actual boostrap sampler implementation for common data types.
class BootstrapSampler< Teuchos::SerialDenseMatrix< OrdinalType, ScalarType > >
Bootstrap sampler that is specialized to allow for the bootstrapping of RealMatrix.
class BootstrapSamplerBase
Base class/interface for the bootstrap sampler.
class BootstrapSamplerWithGS
A derived sampler to allow for user specification of the accessor methods.
class C3Approximation
Derived approximation class for global basis polynomials.
class C3FnTrainData
Handle for reference-counted pointer to C3FnTrainDataRep body.
class COLINApplication
class COLINOptimizer
Wrapper class for optimizers defined using COLIN.
class COLINTraits
A version of TraitsBase specialized for COLIN optimizers.
class CollabHybridMetaIterator
Meta-iterator for hybrid iteration using multiple collaborating optimization and nonlinear least squares methods.
class CommandLineHandler
Utility class for managing command line inputs to DAKOTA.
class CommandShell
Utility class which defines convenience operators for spawning processes with system calls.
class ConcurrentMetaIterator
Meta-iterator for multi-start iteration or pareto set optimization.
class CONMINOptimizer
Wrapper class for the CONMIN optimization library.
class CONMINTraits
A version of TraitsBase specialized for CONMIN optimizers.
class ConsoleRedirector
class Constraints
Base class for the variable constraints class hierarchy.
class DAGSolutionData
Container class for numerical solutions for a given DAG.
class DakotaROLEqConstraints
class DakotaROLEqConstraintsGrad
class DakotaROLEqConstraintsHess
class DakotaROLIneqConstraints
class DakotaROLIneqConstraintsGrad
class DakotaROLIneqConstraintsHess
class DakotaROLObjective
class DakotaROLObjectiveGrad
class DakotaROLObjectiveHess
class DataEnvironment
Handle class for environment specification data.
class DataEnvironmentRep
Body class for environment specification data.
class DataFitSurrBasedLocalTraits
Class for provably-convergent local surrogate-based optimization and nonlinear least squares.
class DataFitSurrModel
Derived model class within the surrogate model branch for managing data fit surrogates (global and local)
class DataInterface
Handle class for interface specification data.
class DataMethod
Handle class for method specification data.
class DataMethodRep
Body class for method specification data.
class DataModel
Handle class for model specification data.
class DataModelRep
Body class for model specification data.
class DataResponses
Handle class for responses specification data.
class DataResponsesRep
Body class for responses specification data.
class DataTransformModel
Data transformation specialization of RecastModel.
class DataVariables
Handle class for variables specification data.
class DataVariablesRep
Body class for variables specification data.
class DDACEDesignCompExp
Wrapper class for the DDACE design of experiments library.
class DerivInformedPropCovLogitTK
Dakota transition kernel that updates proposal covariance based on derivatives (for logit random walk case)
class DerivInformedPropCovTK
Dakota transition kernel that updates proposal covariance based on derivatives (for random walk case)
class DigitalNet
Class for digital nets in Dakota.
class DirectApplicInterface
Derived application interface class which spawns simulation codes and testers using direct procedure calls.
class DiscrepancyCorrection
Base class for discrepancy corrections.
class DLSolverTraits
A version of TraitsBase specialized for DLSolver.
class DOTTraits
Wrapper class for the DOT optimization library.
class EffGlobalMinimizer
class EffGlobalTraits
Implementation of Efficient Global Optimization/Least Squares algorithms.
class EmbedHybridMetaIterator
Meta-iterator for closely-coupled hybrid iteration, typically involving the embedding of local search methods within global search methods.
class EnsembleSurrModel
Derived model class within the surrogate model branch for managing a truth model alongside approximation models of varying fidelity.
class Environment
Base class for the environment class hierarchy.
class ExecutableEnvironment
Environment corresponding to execution as a stand-alone application.
class ExperimentData
class ExperimentResponse
Container class for response functions and their derivatives.
ExperimentResponse provides the body class.
class FileReadException
base class for Dakota file read exceptions (to allow catching both tabular and general file truncation issues)
class ForkApplicInterface
Derived application interface class which spawns simulation codes using fork/execvp/waitpid.
class FSUDesignCompExp
Wrapper class for the FSUDace QMC/CVT library.
class FunctionEvalFailure
exception class for function evaluation failures
class GaussProcApproximation
Derived approximation class for Gaussian Process implementation.
class GeneralReader
Utility used in derived read_core to read in generic format.
class GeneralWriter
Utility used in derived write_core to write in generic format.
class GetLongOpt
GetLongOpt is a general command line utility from S. Manoharan (Advanced Computer Research Institute, Lyon, France).
class Graphics
The Graphics class provides a single interface to 2D (motif) and 3D (PLPLOT) graphics; there is only one instance of this OutputManager::dakotaGraphics.
class GridApplicInterface
Derived application interface class which spawns simulation codes using grid services such as Condor or Globus.
class HDF5IOHelper
class HierarchSurrBasedLocalTraits
Class for multilevel-multifidelity optimization algorithm.
struct IntegerScale
Data structure for storing int-valued dimension scale.
class Interface
Base class for the interface class hierarchy.
class Iterator
Base class for the iterator class hierarchy.
class IteratorScheduler
This class encapsulates scheduling operations for concurrent sub-iteration within an outer level context (e.g., meta-iteration, nested models).
class JEGAOptimizer
A version of Dakota::Optimizer for instantiation of John Eddy's Genetic Algorithms (JEGA).
class JEGATraits
A version of TraitsBase specialized for John Eddy's Genetic Algorithms (JEGA).
class LabelsWriter
Utility used in derived write_core to write labels in tabular format.
class LeastSq
Base class for the nonlinear least squares branch of the iterator hierarchy.
class LibraryEnvironment
Environment corresponding to execution as an embedded library.
struct LightWtBaseConstructor
Dummy struct for overloading constructors used in on-the-fly Model instantiations.
class LowDiscrepancySequence
Abstract class for low-discrepancy sequences.
struct MatchesWC
Predicate that returns true when the passed path matches the wild_card with which it was configured.
Currently supports * and ?.
class MatlabInterface
class MetaIterator
Base class for meta-iterators.
class Minimizer
Base class for the optimizer and least squares branches of the iterator hierarchy.
class MinimizerAdapterModel
Derived model class which wraps call-back functions for solving minimization sub-problems.
class MixedVarConstraints
Derived class within the Constraints hierarchy which separates continuous and discrete variables (no domain type array merging).
class MixedVariables
Derived class within the Variables hierarchy which separates continuous and discrete variables (no domain type array merging).
class Model
Base class for the model class hierarchy.
class MPIManager
Class MPIManager to manage Dakota's MPI world, which may be a subset of MPI_COMM_WORLD.
class MPIPackBuffer
Class for packing MPI message buffers.
class MPIUnpackBuffer
Class for unpacking MPI message buffers.
class NCSUOptimizer
Wrapper class for the NCSU DIRECT optimization library.
class NCSUTraits
A version of TraitsBase specialized for NCSU optimizers.
class NestedModel
Derived model class which performs a complete sub-iterator execution within every evaluation of the model.
class NIDRProblemDescDB
The derived input file database utilizing the new IDR parser.
struct NL2Res
Auxiliary information passed to calcr and calcj via ur.
class NL2SOLLeastSq
Wrapper class for the NL2SOL nonlinear least squares library.
class NL2SOLLeastSqTraits
A version of TraitsBase specialized for NL2SOL nonlinear least squares library.
class NLPQLPTraits
Wrapper class for the NLPQLP optimization library, Version 2.0.
class NLSSOLLeastSq
Wrapper class for the NLSSOL nonlinear least squares library.
class NLSSOLLeastSqTraits
A version of TraitsBase specialized for NLSSOL nonlinear least squares library.
struct NoDBBaseConstructor
Dummy struct for overloading constructors used in on-the-fly instantiations without ProblemDescDB support.
class NomadTraits
Wrapper class for NOMAD Optimizer.
class NonD
Base class for all nondetermistic iterators (the DAKOTA/UQ branch).
class NonDACVSampling
Perform Approximate Control Variate Monte Carlo sampling for UQ.
class NonDAdaptImpSampling
Class for the Adaptive Importance Sampling methods within DAKOTA.
class NonDAdaptiveSampling
Class for testing various Adaptively sampling methods using geometric, statisctical, and topological information of the surrogate.
class NonDBayesCalibration
Base class for Bayesian inference: generates posterior distribution on model parameters given experimental data.
class NonDC3FunctionTrain
Nonintrusive uncertainty quantification with the C3 library ...
class NonDCalibration
class NonDCubature
Derived nondeterministic class that generates N-dimensional numerical cubature points for evaluation of expectation integrals.
class NonDDREAMBayesCalibration
Bayesian inference using the DREAM approach.
class NonDEnsembleSampling
Base class for Monte Carlo sampling across Model ensembles.
class NonDExpansion
Base class for polynomial chaos expansions (PCE), stochastic collocation (SC) and functional tensor train (FT)
class NonDGenACVSampling
Perform Generalized Approximate Control Variate Monte Carlo sampling.
class NonDGlobalEvidence
Class for the Dempster-Shafer Evidence Theory methods within DAKOTA/UQ.
class NonDGlobalInterval
Class for using global nongradient-based optimization approaches to calculate interval bounds for epistemic uncertainty quantification.
class NonDGlobalReliability
Class for global reliability methods within DAKOTA/UQ.
class NonDGlobalSingleInterval
Class for using global nongradient-based optimization approaches to calculate interval bounds for epistemic uncertainty quantification.
class NonDGPImpSampling
Class for the Gaussian Process-based Importance Sampling method.
class NonDGPMSABayesCalibration
Generates posterior distribution on model parameters given experiment data.
class NonDHierarchSampling
Performs Hierarch Monte Carlo sampling for uncertainty quantification.
class NonDIntegration
Derived nondeterministic class that generates N-dimensional numerical integration points for evaluation of expectation integrals.
class NonDInterval
Base class for interval-based methods within DAKOTA/UQ.
class NonDLHSEvidence
Class for the Dempster-Shafer Evidence Theory methods within DAKOTA/UQ.
class NonDLHSInterval
Class for the LHS-based interval methods within DAKOTA/UQ.
class NonDLHSSampling
Performs LHS and Monte Carlo sampling for uncertainty quantification.
class NonDLHSSingleInterval
Class for pure interval propagation using LHS.
class NonDLocalEvidence
Class for the Dempster-Shafer Evidence Theory methods within DAKOTA/UQ.
class NonDLocalInterval
Class for using local gradient-based optimization approaches to calculate interval bounds for epistemic uncertainty quantification.
class NonDLocalReliability
Class for the reliability methods within DAKOTA/UQ.
class NonDLocalSingleInterval
Class for using local gradient-based optimization approaches to calculate interval bounds for epistemic uncertainty quantification.
class NonDLowDiscrepancySampling
Class for low-discrepancy sampling in Dakota.
class NonDMultifidelitySampling
Perform Approximate Control Variate Monte Carlo sampling for UQ.
class NonDMultilevControlVarSampling
Performs multilevel-multifidelity Monte Carlo sampling for uncertainty quantification.
class NonDMultilevelFunctionTrain
Nonintrusive polynomial chaos expansion approaches to uncertainty quantification.
class NonDMultilevelPolynomialChaos
Nonintrusive polynomial chaos expansion approaches to uncertainty quantification.
class NonDMultilevelSampling
Performs Multilevel Monte Carlo sampling for uncertainty quantification.
class NonDMultilevelStochCollocation
Nonintrusive stochastic collocation approaches to uncertainty quantification.
class NonDMUQBayesCalibration
Dakota interface to MUQ (MIT Uncertainty Quantification) library.
class NonDNonHierarchSampling
Base class for non-hierarchical ensemble-based Monte Carlo sampling.
class NonDPOFDarts
Base class for POF Dart methods within DAKOTA/UQ.
class NonDPolynomialChaos
Nonintrusive polynomial chaos expansion approaches to uncertainty quantification.
class NonDQuadrature
Derived nondeterministic class that generates N-dimensional numerical quadrature points for evaluation of expectation integrals over uncorrelated standard normals/uniforms/exponentials/betas/gammas.
class NonDQUESOBayesCalibration
Bayesian inference using the QUESO library from UT Austin.
class NonDReliability
Base class for the reliability methods within DAKOTA/UQ.
class NonDRKDDarts
Base class for the Recursive k-d Dart methods within DAKOTA/UQ.
class NonDSampling
Base class for common code between NonDLHSSampling, NonDAdaptImpSampling, and other specializations.
class NonDSparseGrid
Derived nondeterministic class that generates N-dimensional Smolyak sparse grids for numerical evaluation of expectation integrals over independent standard random variables.
class NonDStochCollocation
Nonintrusive stochastic collocation approaches to uncertainty quantification.
class NonDSurrogateExpansion
Generic uncertainty quantification with Model-based stochastic expansions.
class NonDWASABIBayesCalibration
WASABI - Weighted Adaptive Surrogate Approximations for Bayesian Inference.
class NonlinearCGOptimizer
class NonlinearCGTraits
A version of TraitsBase specialized for NonlinearCG optimizers.
class NOWPACBlackBoxEvaluator
Derived class for plugging Dakota evaluations into NOWPAC solver.
class NOWPACOptimizer
Wrapper class for the (S)NOWPAC optimization algorithms from Florian Augustin (MIT)
class NOWPACTraits
A version of TraitsBase specialized for NOWPAC optimizers.
class NPSOLTraits
Wrapper class for the NPSOL optimization library.
class OptDartsOptimizer
Wrapper class for OptDarts Optimizer.
class OptDartsTraits
A version of TraitsBase specialized for OptDarts.
class Optimizer
Base class for the optimizer branch of the iterator hierarchy.
class OutputManager
Class to manage redirection of stdout/stderr, keep track of current redir state, and manage rank 0 output. Also manage tabular data output for post-processing with Matlab, Tecplot, etc. and delegate to Graphics for X Windows Graphics.
class OutputWriter
class ParallelConfiguration
Container class for a set of ParallelLevel list iterators that collectively identify a particular multilevel parallel configuration.
class ParallelLevel
Container class for the data associated with a single level of communicator partitioning.
class ParallelLibrary
Class for partitioning multiple levels of parallelism and managing message passing within these levels.
class ParamResponsePair
Container class for a variables object, a response object, and an evaluation id.
class ParamStudy
Class for vector, list, centered, and multidimensional parameter studies.
struct partial_prp_equality
predicate for comparing ONLY the interfaceId and Vars attributes of PRPair
struct partial_prp_hash
wrapper to delegate to the ParamResponsePair hash_value function
class PebbldBranching
Main Branching class for the PEBBL-based Minimizer.
class PebbldBranchSub
Sub Branch class for the PEBBL-based Minimizer.
class PebbldTraits
Wrapper class for experimental PebbldMinimizer.
class PecosApproximation
Derived approximation class for global basis polynomials.
class PrefixingLineFilter
class ProbabilityTransformModel
Probability transformation specialization of RecastModel.
class ProblemDescDB
The database containing information parsed from the DAKOTA input file.
class ProcessApplicInterface
Derived application interface class that spawns a simulation code using a separate process and communicates with it through files.
class ProcessHandleApplicInterface
Derived application interface class that spawns a simulation code using a separate process, receives a process identifier, and communicates with the spawned process through files.
class ProgramOptions
ProgramOptions stores options whether from the CLH or from library user; initially valid only on worldRank = 0, but then broadcast in ParallelLibrary::push_output_tag()
class PStudyDACE
Base class for managing common aspects of parameter studies and design of experiments methods.
class PSUADEDesignCompExp
Wrapper class for the PSUADE library.
class Pybind11Interface
class PythonInterface
class QMEApproximation
Derived approximation class for QMEA Quadratic Multipoint Exponential Approximation (a multipoint approximation).
class QuesoJointPdf
Dakota specialization of QUESO generic joint PDF.
class QuesoVectorRV
Dakota specialization of QUESO vector-valued random variable.
class RandomFieldModel
Random field model, capable of generating and then forward propagating.
class Rank1Lattice
Class for rank-1 lattice rules in Dakota.
struct RealScale
Data structure for storing real-valued dimension scale.
class RecastModel
Derived model class which provides a thin wrapper around a sub-model in order to recast the form of its inputs and/or outputs.
class ReducedBasis
class RelaxedVarConstraints
Derived class within the Constraints hierarchy which employs relaxation of discrete variables.
class RelaxedVariables
Derived class within the Variables hierarchy which employs the relaxation of discrete variables.
class Response
Container class for response functions and their derivatives.
Response provides the enveloper base class.
class RestartWriter
struct ResultAttribute
Data structure for a single Real, String, or int valued attribute.
class ResultsDBAny
class ResultsDBBase
class ResultsDBHDF5
Manage interactions between ResultsManager and the low-level HDFIOHelper class.
class ResultsEntry
Class to manage in-core vs. file database lookups.
class ResultsFileError
exception throw for other results file read error
class ResultsManager
Results manager for iterator final data.
class ResultsNames
List of valid names for iterator results.
class RichExtrapVerification
Class for Richardson extrapolation for code and solution verification.
class ROLOptimizer
class ROLTraits
class ScalingModel
Scaling specialization of RecastModel.
class ScalingOptions
Simple container for user-provided scaling data, possibly expanded by replicates through the models.
class ScilabInterface
class SensAnalysisGlobal
Class for a utility class containing correlation calculations and variance-based decomposition.
class SeqHybridMetaIterator
Method for sequential hybrid iteration using multiple optimization and nonlinear least squares methods on multiple models of varying fidelity.
class SharedApproxData
Base class for the shared approximation data class hierarchy.
class SharedC3ApproxData
Derived approximation class for global basis polynomials.
class SharedPecosApproxData
Derived approximation class for global basis polynomials.
class SharedResponseData
Container class encapsulating variables data that can be shared among a set of Response instances.
class SharedResponseDataRep
The representation of a SharedResponseData instance. This representation, or body, may be shared by multiple SharedResponseData handle instances.
class SharedSurfpackApproxData
Derived approximation class for Surfpack approximation classes. Interface between Surfpack and Dakota.
class SharedVariablesData
Container class encapsulating variables data that can be shared among a set of Variables instances.
class SharedVariablesDataRep
The representation of a SharedVariablesData instance. This representation, or body, may be shared by multiple SharedVariablesData handle instances.
class SimulationModel
Derived model class which utilizes a simulation-based application interface to map variables into responses.
class SimulationResponse
Container class for response functions and their derivatives.
SimulationResponse provides the body class.
class SNLLBase
Base class for OPT++ optimization and least squares methods.
class SNLLLeastSq
Wrapper class for the OPT++ optimization library.
class SNLLLeastSqTraits
A version of TraitsBase specialized for SNLLLeastSq.
class SNLLOptimizer
Wrapper class for the OPT++ optimization library.
class SNLLTraits
A version of TraitsBase specialized for SNLL optimizers.
class SOLBase
Base class for Stanford SOL software.
class SpawnApplicInterface
Derived application interface class which spawns simulation codes using spawnvp.
struct StringScale
Data structure for storing string-valued dimension scale.
class SubspaceModel
Subspace model for input (variable space) reduction.
class SurfpackApproximation
Derived approximation class for Surfpack approximation classes. Interface between Surfpack and Dakota.
class SurrBasedGlobalMinimizer
class SurrBasedGlobalTraits
The global surrogate-based minimizer which sequentially minimizes and updates a global surrogate model without trust region controls.
class SurrBasedLocalMinimizer
Class for provably-convergent local surrogate-based optimization and nonlinear least squares.
class SurrBasedMinimizer
Base class for local/global surrogate-based optimization/least squares.
class SurrogateModel
Base class for surrogate models (DataFitSurrModel and EnsembleSurrModel).
class SurrogatesBaseApprox
Derived Approximation class for new Surrogates modules.
class SurrogatesGPApprox
Derived approximation class for Surrogates approximation classes.
class SurrogatesPolyApprox
Derived approximation class for Surrogates Polynomial approximation classes.
class SysCallApplicInterface
Derived application interface class which spawns simulation codes using system calls.
class TabularDataTruncated
exception thrown when data read truncated
class TabularReader
Utility used in derived read_core to read values in tabular format.
class TabularWriter
Utility used in derived write_core to write values in tabular format.
class TANA3Approximation
Derived approximation class for TANA-3 two-point exponential approximation (a multipoint approximation).
class TaylorApproximation
Derived approximation class for first- or second-order Taylor series (a local approximation).
class TestDriverInterface
class TKFactoryDIPC
Custom RW TKfactory: passes Dakota QUESO instance pointer to the TK at build.
class TKFactoryDIPCLogit
Custom Logit RW TKfactory: passed Dakota QUESO instance pointer to the TK at build.
class TPLDataTransfer
class TrackerHTTP
TrackerHTTP: a usage tracking module that uses HTTP/HTTPS via the curl library.
class TraitsBase
Base class for traits.
class UsageTracker
Lightweight class to manage conditionally active Curl-based HTTP tracker via PIMPL.
struct Var_icheck
structure for verifying bounds and initial point for string-valued vars
struct Var_rcheck
structure for verifying bounds and initial point for real-valued vars
class Variables
Base class for the variables class hierarchy.
class Verification
Base class for managing common aspects of verification studies.
struct VLint
structure for validating integer uncertain variable labels, bounds, values
struct VLreal
structure for validating real uncertain variable labels, bounds, values
struct VLstr
structure for validating string uncertain variable labels, bounds, values
class VPSApproximation
Derived approximation class for VPS implementation.
class WeightingModel
Weighting specialization of RecastModel.
class WorkdirHelper
Typedefs
typedef boost::tuple< std::string, std::string, size_t, std::string > ResultsKeyType
Data type for results key (instance name / id, unique run, label), where data_key is a valid colon-delimited string from ResultsNames tuple<method_name, method_id, execution_number, data_key>
typedef std::string MetaDataKeyType
Data type for metadata key.
typedef std::vector< std::string > MetaDataValueType
Data type for metadata value.
typedef std::map< MetaDataKeyType, MetaDataValueType > MetaDataType
A single MetaData entry is map<string, vector<string> > Example: pair("Column labels", ["Mean", "Std Dev", "Skewness", "Kurtosis"])
typedef boost::tuple< std::string, std::string, size_t > StrStrSizet
Iterator unique ID: <method_name, method_id, exec_num>
typedef std::multimap< int, boost::variant< StringScale, RealScale, IntegerScale > > DimScaleMap
Datatype to communicate scales (stored in boost::variant) and their associated dimension (the int) to the ResultsManager instance.
typedef std::vector< boost::variant< ResultAttribute< int >, ResultAttribute< String >, ResultAttribute< Real > > > AttributeArray
Datatype to communcate metadata (attributes) to the ResultsManager instance.
typedef boost::bimap< unsigned short, std::string > UShortStrBimap
bimaps to convert from enums <--> strings
using RespMetadataT = double
typedef void(* dl_core_run_t) (void *, Optimizer1 *, char *)
typedef void(* dl_destructor_t) (void **)
typedef Teuchos::SerialDenseSolver< int, Real > RealSolver
typedef Teuchos::SerialSpdDenseSolver< int, Real > RealSpdSolver
typedef int(* start_grid_computing_t) (char *analysis_driver_script, char *params_file, char *results_file)
definition of start grid computing type (function pointer)
typedef int(* perform_analysis_t) (char *iteration_num)
definition of perform analysis type (function pointer)
typedef int *(* get_jobs_completed_t) ()
definition of get completed jobs type (function pointer)
typedef int(* stop_grid_computing_t) ()
definition of stop grid computing type (function pointer)
typedef int MPI_Comm
typedef void * MPI_Request
typedef unsigned char u_char
typedef unsigned short u_short
typedef unsigned int u_int
typedef unsigned long u_long
typedef long long long_long
typedef unsigned long UL
typedef void(* Calcrj) (int *n, int *p, Real *x, int *nf, Real *r, int *ui, void *ur, Vf vf)
typedef void(* Vf) ()
typedef void(* DbCallbackFunctionPtr) (Dakota::ProblemDescDB *db, void *data_ptr)
typedef boost::tuple< bfs::path, bfs::path, bfs::path > PathTriple
Triplet of filesystem paths: e.g., params, results, workdir.
typedef bmi::multi_index_container< Dakota::ParamResponsePair, bmi::indexed_by< bmi::ordered_non_unique< bmi::tag< ordered >, bmi::const_mem_fun< Dakota::ParamResponsePair, const IntStringPair &, &Dakota::ParamResponsePair::eval_interface_ids > >, bmi::hashed_non_unique< bmi::tag< hashed >, bmi::identity< Dakota::ParamResponsePair >, partial_prp_hash, partial_prp_equality > > > PRPMultiIndexCache
Boost Multi-Index Container for globally caching ParamResponsePairs.
typedef PRPMultiIndexCache PRPCache
typedef PRPCache::index_iterator< ordered >::type PRPCacheOIter
typedef PRPCache::index_const_iterator< ordered >::type PRPCacheOCIter
typedef PRPCache::index_iterator< hashed >::type PRPCacheHIter
typedef PRPCache::index_const_iterator< hashed >::type PRPCacheHCIter
typedef PRPCacheOIter PRPCacheIter
default cache iterator <0>
typedef PRPCacheOCIter PRPCacheCIter
default cache const iterator <0> default cache const reverse iterator <0>
typedef boost::reverse_iterator< PRPCacheCIter > PRPCacheCRevIter
typedef bmi::multi_index_container< Dakota::ParamResponsePair, bmi::indexed_by< bmi::ordered_unique< bmi::tag< ordered >, bmi::const_mem_fun< Dakota::ParamResponsePair, int, &Dakota::ParamResponsePair::eval_id > >, bmi::hashed_non_unique< bmi::tag< hashed >, bmi::identity< Dakota::ParamResponsePair >, partial_prp_hash, partial_prp_equality > > > PRPMultiIndexQueue
Boost Multi-Index Container for locally queueing ParamResponsePairs.
typedef PRPMultiIndexQueue PRPQueue
typedef PRPQueue::index_iterator< ordered >::type PRPQueueOIter
typedef PRPQueue::index_const_iterator< ordered >::type PRPQueueOCIter
typedef PRPQueue::index_iterator< hashed >::type PRPQueueHIter
typedef PRPQueue::index_const_iterator< hashed >::type PRPQueueHCIter
typedef PRPQueueOIter PRPQueueIter
typedef PRPQueueOCIter PRPQueueCIter
typedef std::pair< boost::any, MetaDataType > ResultsValueType
Core data storage type: boost::any, with optional metadata (see other types in results_types.hpp)
typedef boost::function< bool(const bfs::path &src_path, const bfs::path &dest_path, bool overwrite)> file_op_function
define a function type that operates from src to dest, with option to overwrite
typedef boost::filter_iterator< MatchesWC, bfs::directory_iterator > glob_iterator
a glob_iterator filters a directory_iterator based on a wildcard predicate
Enumerations
enum {
COBYLA, DIRECT, EA, MS,
PS, SW, BETA, VARS_ERROR = -11,
CONS_ERROR = -10, RESP_ERROR = -9, APPROX_ERROR = -8, METHOD_ERROR = -7,
MODEL_ERROR = -6, IO_ERROR = -5, INTERFACE_ERROR = -4, CONSTRUCT_ERROR = -3,
PARSE_ERROR = -2, OTHER_ERROR = -1, DEFAULT_INTERFACE =0, APPROX_INTERFACE,
FORK_INTERFACE =PROCESS_INTERFACE_BIT, SYSTEM_INTERFACE, GRID_INTERFACE, TEST_INTERFACE =DIRECT_INTERFACE_BIT,
PLUGIN_INTERFACE, MATLAB_INTERFACE, LEGACY_PYTHON_INTERFACE, PYTHON_INTERFACE,
SCILAB_INTERFACE, DEFAULT_METHOD =0, HYBRID =(META_BIT | PARALLEL_BIT), PARETO_SET,
MULTI_START, RICHARDSON_EXTRAP =(ANALYZER_BIT | VERIF_BIT), CENTERED_PARAMETER_STUDY =(ANALYZER_BIT | PSTUDYDACE_BIT), LIST_PARAMETER_STUDY,
MULTIDIM_PARAMETER_STUDY, VECTOR_PARAMETER_STUDY, DACE, FSU_CVT,
FSU_HALTON, FSU_HAMMERSLEY, PSUADE_MOAT, LOCAL_RELIABILITY =(ANALYZER_BIT | NOND_BIT),
GLOBAL_RELIABILITY, SURROGATE_BASED_UQ, POLYNOMIAL_CHAOS, MULTILEVEL_POLYNOMIAL_CHAOS,
MULTIFIDELITY_POLYNOMIAL_CHAOS, STOCH_COLLOCATION, MULTIFIDELITY_STOCH_COLLOCATION, C3_FUNCTION_TRAIN,
MULTILEVEL_FUNCTION_TRAIN, MULTIFIDELITY_FUNCTION_TRAIN, CUBATURE_INTEGRATION, SPARSE_GRID_INTEGRATION,
QUADRATURE_INTEGRATION, BAYES_CALIBRATION, GPAIS, POF_DARTS,
RKD_DARTS, IMPORTANCE_SAMPLING, ADAPTIVE_SAMPLING, MULTILEVEL_SAMPLING,
MULTIFIDELITY_SAMPLING, MULTILEVEL_MULTIFIDELITY_SAMPLING, APPROXIMATE_CONTROL_VARIATE, LIST_SAMPLING,
RANDOM_SAMPLING, LOCAL_INTERVAL_EST, LOCAL_EVIDENCE, GLOBAL_INTERVAL_EST,
GLOBAL_EVIDENCE, SURROGATE_BASED_LOCAL =(MINIMIZER_BIT | SURRBASED_BIT), DATA_FIT_SURROGATE_BASED_LOCAL, HIERARCH_SURROGATE_BASED_LOCAL,
SURROGATE_BASED_GLOBAL, EFFICIENT_GLOBAL, NL2SOL =(MINIMIZER_BIT | LEASTSQ_BIT), NLSSOL_SQP,
OPTPP_G_NEWTON, ASYNCH_PATTERN_SEARCH =(MINIMIZER_BIT | OPTIMIZER_BIT), OPTPP_PDS, COLINY_BETA,
COLINY_COBYLA, COLINY_DIRECT, COLINY_MULTI_START, COLINY_EA,
COLINY_PATTERN_SEARCH, COLINY_SOLIS_WETS, MOGA, SOGA,
NCSU_DIRECT, MESH_ADAPTIVE_SEARCH, MIT_NOWPAC, MIT_SNOWPAC,
GENIE_OPT_DARTS, GENIE_DIRECT, DEMO_TPL, NONLINEAR_CG,
OPTPP_CG, OPTPP_Q_NEWTON, OPTPP_FD_NEWTON, OPTPP_NEWTON,
NPSOL_SQP, NLPQL_SQP, DOT_BFGS, DOT_FRCG,
DOT_MMFD, DOT_SLP, DOT_SQP, CONMIN_FRCG,
CONMIN_MFD, ROL, DL_SOLVER, BRANCH_AND_BOUND =(MINIMIZER_BIT | OPTIMIZER_BIT | LEASTSQ_BIT),
DEFAULT_POINTS, MINIMUM_POINTS, RECOMMENDED_POINTS, TOTAL_POINTS,
BASE_RESPONSE =0, SIMULATION_RESPONSE, EXPERIMENT_RESPONSE, DEFAULT_DOMAIN =0,
RELAXED_DOMAIN, MIXED_DOMAIN, DEFAULT_CORRECTION = 0, SINGLE_CORRECTION,
FULL_MODEL_FORM_CORRECTION, FULL_SOLUTION_LEVEL_CORRECTION, SEQUENCE_CORRECTION, SETUP_MODEL,
SETUP_USERFUNC, CAUVar_normal = 0, CAUVar_lognormal = 1, CAUVar_uniform = 2,
CAUVar_loguniform = 3, CAUVar_triangular = 4, CAUVar_exponential = 5, CAUVar_beta = 6,
CAUVar_gamma = 7, CAUVar_gumbel = 8, CAUVar_frechet = 9, CAUVar_weibull = 10,
CAUVar_histogram_bin = 11, CAUVar_Nkinds = 12, ANALYTIC_SOLUTION = 1, REORDERED_ANALYTIC_SOLUTION,
R_ONLY_LINEAR_CONSTRAINT, N_VECTOR_LINEAR_CONSTRAINT, R_AND_N_NONLINEAR_CONSTRAINT, N_VECTOR_LINEAR_OBJECTIVE,
FULL_TENSOR, FILTERED_TENSOR, RANDOM_TENSOR, AS_FUNC =1,
AS_GRAD =2, AS_HESS =4, DISALLOW, TARGET,
BOUNDS, SCALE_NONE = 0, SCALE_VALUE = 1, SCALE_LOG = 2,
SCALE_AUTO = 4, APPROX_RESPONSE =1, TRUTH_RESPONSE, TH_SILENT_OUTPUT,
TH_QUIET_OUTPUT, TH_NORMAL_OUTPUT, TH_VERBOSE_OUTPUT, TH_DEBUG_OUTPUT,
DIR_CLEAN, DIR_PERSIST, DIR_ERROR
}
enum {
COBYLA, DIRECT, EA, MS,
PS, SW, BETA, VARS_ERROR = -11,
CONS_ERROR = -10, RESP_ERROR = -9, APPROX_ERROR = -8, METHOD_ERROR = -7,
MODEL_ERROR = -6, IO_ERROR = -5, INTERFACE_ERROR = -4, CONSTRUCT_ERROR = -3,
PARSE_ERROR = -2, OTHER_ERROR = -1, DEFAULT_INTERFACE =0, APPROX_INTERFACE,
FORK_INTERFACE =PROCESS_INTERFACE_BIT, SYSTEM_INTERFACE, GRID_INTERFACE, TEST_INTERFACE =DIRECT_INTERFACE_BIT,
PLUGIN_INTERFACE, MATLAB_INTERFACE, LEGACY_PYTHON_INTERFACE, PYTHON_INTERFACE,
SCILAB_INTERFACE, DEFAULT_METHOD =0, HYBRID =(META_BIT | PARALLEL_BIT), PARETO_SET,
MULTI_START, RICHARDSON_EXTRAP =(ANALYZER_BIT | VERIF_BIT), CENTERED_PARAMETER_STUDY =(ANALYZER_BIT | PSTUDYDACE_BIT), LIST_PARAMETER_STUDY,
MULTIDIM_PARAMETER_STUDY, VECTOR_PARAMETER_STUDY, DACE, FSU_CVT,
FSU_HALTON, FSU_HAMMERSLEY, PSUADE_MOAT, LOCAL_RELIABILITY =(ANALYZER_BIT | NOND_BIT),
GLOBAL_RELIABILITY, SURROGATE_BASED_UQ, POLYNOMIAL_CHAOS, MULTILEVEL_POLYNOMIAL_CHAOS,
MULTIFIDELITY_POLYNOMIAL_CHAOS, STOCH_COLLOCATION, MULTIFIDELITY_STOCH_COLLOCATION, C3_FUNCTION_TRAIN,
MULTILEVEL_FUNCTION_TRAIN, MULTIFIDELITY_FUNCTION_TRAIN, CUBATURE_INTEGRATION, SPARSE_GRID_INTEGRATION,
QUADRATURE_INTEGRATION, BAYES_CALIBRATION, GPAIS, POF_DARTS,
RKD_DARTS, IMPORTANCE_SAMPLING, ADAPTIVE_SAMPLING, MULTILEVEL_SAMPLING,
MULTIFIDELITY_SAMPLING, MULTILEVEL_MULTIFIDELITY_SAMPLING, APPROXIMATE_CONTROL_VARIATE, LIST_SAMPLING,
RANDOM_SAMPLING, LOCAL_INTERVAL_EST, LOCAL_EVIDENCE, GLOBAL_INTERVAL_EST,
GLOBAL_EVIDENCE, SURROGATE_BASED_LOCAL =(MINIMIZER_BIT | SURRBASED_BIT), DATA_FIT_SURROGATE_BASED_LOCAL, HIERARCH_SURROGATE_BASED_LOCAL,
SURROGATE_BASED_GLOBAL, EFFICIENT_GLOBAL, NL2SOL =(MINIMIZER_BIT | LEASTSQ_BIT), NLSSOL_SQP,
OPTPP_G_NEWTON, ASYNCH_PATTERN_SEARCH =(MINIMIZER_BIT | OPTIMIZER_BIT), OPTPP_PDS, COLINY_BETA,
COLINY_COBYLA, COLINY_DIRECT, COLINY_MULTI_START, COLINY_EA,
COLINY_PATTERN_SEARCH, COLINY_SOLIS_WETS, MOGA, SOGA,
NCSU_DIRECT, MESH_ADAPTIVE_SEARCH, MIT_NOWPAC, MIT_SNOWPAC,
GENIE_OPT_DARTS, GENIE_DIRECT, DEMO_TPL, NONLINEAR_CG,
OPTPP_CG, OPTPP_Q_NEWTON, OPTPP_FD_NEWTON, OPTPP_NEWTON,
NPSOL_SQP, NLPQL_SQP, DOT_BFGS, DOT_FRCG,
DOT_MMFD, DOT_SLP, DOT_SQP, CONMIN_FRCG,
CONMIN_MFD, ROL, DL_SOLVER, BRANCH_AND_BOUND =(MINIMIZER_BIT | OPTIMIZER_BIT | LEASTSQ_BIT),
DEFAULT_POINTS, MINIMUM_POINTS, RECOMMENDED_POINTS, TOTAL_POINTS,
BASE_RESPONSE =0, SIMULATION_RESPONSE, EXPERIMENT_RESPONSE, DEFAULT_DOMAIN =0,
RELAXED_DOMAIN, MIXED_DOMAIN, DEFAULT_CORRECTION = 0, SINGLE_CORRECTION,
FULL_MODEL_FORM_CORRECTION, FULL_SOLUTION_LEVEL_CORRECTION, SEQUENCE_CORRECTION, SETUP_MODEL,
SETUP_USERFUNC, CAUVar_normal = 0, CAUVar_lognormal = 1, CAUVar_uniform = 2,
CAUVar_loguniform = 3, CAUVar_triangular = 4, CAUVar_exponential = 5, CAUVar_beta = 6,
CAUVar_gamma = 7, CAUVar_gumbel = 8, CAUVar_frechet = 9, CAUVar_weibull = 10,
CAUVar_histogram_bin = 11, CAUVar_Nkinds = 12, ANALYTIC_SOLUTION = 1, REORDERED_ANALYTIC_SOLUTION,
R_ONLY_LINEAR_CONSTRAINT, N_VECTOR_LINEAR_CONSTRAINT, R_AND_N_NONLINEAR_CONSTRAINT, N_VECTOR_LINEAR_OBJECTIVE,
FULL_TENSOR, FILTERED_TENSOR, RANDOM_TENSOR, AS_FUNC =1,
AS_GRAD =2, AS_HESS =4, DISALLOW, TARGET,
BOUNDS, SCALE_NONE = 0, SCALE_VALUE = 1, SCALE_LOG = 2,
SCALE_AUTO = 4, APPROX_RESPONSE =1, TRUTH_RESPONSE, TH_SILENT_OUTPUT,
TH_QUIET_OUTPUT, TH_NORMAL_OUTPUT, TH_VERBOSE_OUTPUT, TH_DEBUG_OUTPUT,
DIR_CLEAN, DIR_PERSIST, DIR_ERROR
}
enum for Dakota abort reasons; using negative numbers to distinguish Dakota exit states from signals / uncaught signals. These need to be in range [-63, -1], so exit code (256+enum) is in [193, 255]. See RATIONALE in dakota_global_defs.cpp.
enum {
MODEL_EVAL_STORE_TOP_METHOD = 0, MODEL_EVAL_STORE_NONE, MODEL_EVAL_STORE_ALL, MODEL_EVAL_STORE_ALL_METHODS,
SYNCHRONOUS_INTERFACE, ASYNCHRONOUS_INTERFACE, SUBMETHOD_DEFAULT =0, SUBMETHOD_NONE,
SUBMETHOD_COLLABORATIVE, SUBMETHOD_EMBEDDED, SUBMETHOD_SEQUENTIAL, SUBMETHOD_LHS,
SUBMETHOD_RANDOM, SUBMETHOD_LOW_DISCREPANCY_SAMPLING, SUBMETHOD_BOX_BEHNKEN, SUBMETHOD_CENTRAL_COMPOSITE,
SUBMETHOD_GRID, SUBMETHOD_OA_LHS, SUBMETHOD_OAS, SUBMETHOD_MFMC,
SUBMETHOD_ACV_IS, SUBMETHOD_ACV_MF, SUBMETHOD_ACV_RD, SUBMETHOD_DREAM,
SUBMETHOD_GPMSA, SUBMETHOD_MUQ, SUBMETHOD_QUESO, SUBMETHOD_WASABI,
SUBMETHOD_CONMIN, SUBMETHOD_DOT, SUBMETHOD_NLPQL, SUBMETHOD_NPSOL,
SUBMETHOD_OPTPP, SUBMETHOD_NPSOL_OPTPP, SUBMETHOD_DIRECT, SUBMETHOD_DIRECT_NPSOL_OPTPP,
SUBMETHOD_DIRECT_NPSOL, SUBMETHOD_DIRECT_OPTPP, SUBMETHOD_EA, SUBMETHOD_EGO,
SUBMETHOD_SBLO, SUBMETHOD_SBGO, SUBMETHOD_AMV_X, SUBMETHOD_AMV_U,
SUBMETHOD_AMV_PLUS_X, SUBMETHOD_AMV_PLUS_U, SUBMETHOD_TANA_X, SUBMETHOD_TANA_U,
SUBMETHOD_QMEA_X, SUBMETHOD_QMEA_U, SUBMETHOD_NO_APPROX, SUBMETHOD_EGRA_X,
SUBMETHOD_EGRA_U, SUBMETHOD_CONVERGE_ORDER, SUBMETHOD_CONVERGE_QOI, SUBMETHOD_ESTIMATE_ORDER,
DEFAULT_SURROGATE_RESP_MODE =0, NO_SURROGATE, UNCORRECTED_SURROGATE, AUTO_CORRECTED_SURROGATE,
BYPASS_SURROGATE, MODEL_DISCREPANCY, AGGREGATED_MODEL_PAIR, AGGREGATED_MODELS,
GENERIC_FNS = 0, OBJECTIVE_FNS, CALIB_TERMS, DEFAULT_VIEW =0,
ALL_VIEW, DESIGN_VIEW, UNCERTAIN_VIEW, ALEATORY_UNCERTAIN_VIEW,
EPISTEMIC_UNCERTAIN_VIEW, STATE_VIEW, DAUIVar_poisson = 0, DAUIVar_binomial = 1,
DAUIVar_negative_binomial = 2, DAUIVar_geometric = 3, DAUIVar_hypergeometric = 4, DAUIVar_histogram_point_int = 5,
DAUIVar_Nkinds = 6, TYPE_U =1, TYPE_B =2, TYPE_E =3,
TYPE_EB =4, CORR_APPROX_RESPONSE =1, UNCORR_APPROX_RESPONSE, CORR_TRUTH_RESPONSE,
UNCORR_TRUTH_RESPONSE, FILEOP_SILENT, FILEOP_WARN, FILEOP_ERROR
}
enum for selecting the models that store evaluations
enum {
INTERF_EVAL_STORE_SIMULATION = 0, INTERF_EVAL_STORE_NONE, INTERF_EVAL_STORE_ALL, OBJECTIVE,
INEQUALITY_CONSTRAINT, EQUALITY_CONSTRAINT, VBD_BINNED =0, VBD_PICK_AND_FREEZE,
NO_CORRECTION =0, ADDITIVE_CORRECTION, MULTIPLICATIVE_CORRECTION, COMBINED_CORRECTION,
EMPTY_VIEW =0, RELAXED_ALL, MIXED_ALL, RELAXED_DESIGN,
RELAXED_UNCERTAIN, RELAXED_ALEATORY_UNCERTAIN, RELAXED_EPISTEMIC_UNCERTAIN, RELAXED_STATE,
MIXED_DESIGN, MIXED_UNCERTAIN, MIXED_ALEATORY_UNCERTAIN, MIXED_EPISTEMIC_UNCERTAIN,
MIXED_STATE, DAUSVar_histogram_point_str = 0, DAUSVar_Nkinds = 1, NEW_CANDIDATE = 1,
CANDIDATE_ACCEPTED = 2, CANDIDATE_STATE = (NEW_CANDIDATE | CANDIDATE_ACCEPTED), NEW_CENTER = 8, CENTER_BUILT = 16,
CENTER_STATE = (NEW_CENTER | CENTER_BUILT), NEW_TR_FACTOR = 64, NEW_TRUST_REGION = (NEW_CENTER | NEW_TR_FACTOR), HARD_CONVERGED = 128,
SOFT_CONVERGED = 256, MIN_TR_CONVERGED = 512, MAX_ITER_CONVERGED = 1024, CONVERGED
}
enum for selecting the interfaces that store evaluations
enum {
ABORT_EXITS, ABORT_THROWS, NO_GRAPH_RECURSION =0, KL_GRAPH_RECURSION,
PARTIAL_GRAPH_RECURSION, FULL_GRAPH_RECURSION, RF_KARHUNEN_LOEVE =0, RF_PCA_GP,
RF_ICA, ALL_VARS =0, ACTIVE_VARS, INACTIVE_VARS,
DAURVar_histogram_point_real = 0, DAURVar_Nkinds = 1
}
enum for dakota abort behaviors
enum {
CV_ID_DEFAULT = 0, MINIMUM_METRIC, RELATIVE_TOLERANCE, DECREASE_TOLERANCE,
NO_MODEL_SELECTION =0, ALL_MODEL_COMBINATIONS, NOCOVAR =0, EXP_L2,
EXP_L1, EMPTY_TYPE =0, CONTINUOUS_DESIGN, DISCRETE_DESIGN_RANGE,
DISCRETE_DESIGN_SET_INT, DISCRETE_DESIGN_SET_STRING, DISCRETE_DESIGN_SET_REAL, NORMAL_UNCERTAIN,
LOGNORMAL_UNCERTAIN, UNIFORM_UNCERTAIN, LOGUNIFORM_UNCERTAIN, TRIANGULAR_UNCERTAIN,
EXPONENTIAL_UNCERTAIN, BETA_UNCERTAIN, GAMMA_UNCERTAIN, GUMBEL_UNCERTAIN,
FRECHET_UNCERTAIN, WEIBULL_UNCERTAIN, HISTOGRAM_BIN_UNCERTAIN, POISSON_UNCERTAIN,
BINOMIAL_UNCERTAIN, NEGATIVE_BINOMIAL_UNCERTAIN, GEOMETRIC_UNCERTAIN, HYPERGEOMETRIC_UNCERTAIN,
HISTOGRAM_POINT_UNCERTAIN_INT, HISTOGRAM_POINT_UNCERTAIN_STRING, HISTOGRAM_POINT_UNCERTAIN_REAL, CONTINUOUS_INTERVAL_UNCERTAIN,
DISCRETE_INTERVAL_UNCERTAIN, DISCRETE_UNCERTAIN_SET_INT, DISCRETE_UNCERTAIN_SET_STRING, DISCRETE_UNCERTAIN_SET_REAL,
CONTINUOUS_STATE, DISCRETE_STATE_RANGE, DISCRETE_STATE_SET_INT, DISCRETE_STATE_SET_STRING,
DISCRETE_STATE_SET_REAL, CEUVar_interval = 0, CEUVar_Nkinds = 1
}
enum for active subspace cross validation identification
enum {
TABULAR_NONE = 0, TABULAR_HEADER = 1, TABULAR_EVAL_ID = 2, TABULAR_IFACE_ID = 4,
TABULAR_EXPER_ANNOT = TABULAR_HEADER | TABULAR_EVAL_ID, TABULAR_ANNOTATED = TABULAR_HEADER | TABULAR_EVAL_ID | TABULAR_IFACE_ID, SILENT_OUTPUT, QUIET_OUTPUT,
NORMAL_OUTPUT, VERBOSE_OUTPUT, DEBUG_OUTPUT, SUBSPACE_NORM_DEFAULT =0,
SUBSPACE_NORM_MEAN_VALUE, SUBSPACE_NORM_MEAN_GRAD, SUBSPACE_NORM_LOCAL_GRAD, TOTAL_CDV =0,
TOTAL_DDIV, TOTAL_DDSV, TOTAL_DDRV, TOTAL_CAUV,
TOTAL_DAUIV, TOTAL_DAUSV, TOTAL_DAURV, TOTAL_CEUV,
TOTAL_DEUIV, TOTAL_DEUSV, TOTAL_DEURV, TOTAL_CSV,
TOTAL_DSIV, TOTAL_DSSV, TOTAL_DSRV, NUM_VC_TOTALS,
DEUIVar_interval = 0, DEUIVar_set_int = 1, DEUIVar_Nkinds = 2
}
options for tabular columns
enum {
RESULTS_OUTPUT_TEXT = 1, RESULTS_OUTPUT_HDF5 = 2, NO_RESULTS =0, REFINEMENT_RESULTS,
INTERMEDIATE_RESULTS, FINAL_RESULTS, ROTATION_METHOD_UNRANKED, ROTATION_METHOD_RANKED,
DEUSVar_set_str = 0, DEUSVar_Nkinds = 1
}
Results output format.
enum {
FLEXIBLE_RESULTS, LABELED_RESULTS, DEFAULT_SYNCHRONIZATION =0, BLOCKING_SYNCHRONIZATION,
NONBLOCKING_SYNCHRONIZATION, NO_PARALLEL_MODE =0, SURROGATE_MODEL_MODE, TRUTH_MODEL_MODE,
SUB_MODEL_MODE, INTERFACE_MODE, DEURVar_set_real = 0, DEURVar_Nkinds = 1
}
options for results file format
enum {
NO_MODEL_FORMAT =0, TEXT_ARCHIVE =1, BINARY_ARCHIVE =2, ALGEBRAIC_FILE =4,
ALGEBRAIC_CONSOLE =8, DEFAULT_SCHEDULING, MASTER_SCHEDULING, PEER_SCHEDULING,
PEER_DYNAMIC_SCHEDULING, PEER_STATIC_SCHEDULING, DYNAMIC_SCHEDULING, STATIC_SCHEDULING,
NO_DERIVS =0, ALL_DERIVS, MIXED_DERIVS, DiscSetVar_design_set_int = 0,
DiscSetVar_design_set_str = 1, DiscSetVar_design_set_real = 2, DiscSetVar_state_set_int = 3, DiscSetVar_state_set_str = 4,
DiscSetVar_state_set_real = 5, DiscSetVar_Nkinds = 6
}
define special values for surrogateExportFormats
enum ScaleScope { SHARED, UNSHARED }
Enum to specify whether a scale shared among responses.
enum ResultsOutputType { REAL, INTEGER, UINTEGER, STRING }
enum for setting type on allocted matrix for Results Output
enum CONSTRAINT_TYPE { LINEAR, NONLINEAR }
enum CONSTRAINT_EQUALITY_TYPE { EQUALITY, INEQUALITY }
enum LINEAR_INEQUALITY_FORMAT { NONE, TWO_SIDED, ONE_SIDED_LOWER, ONE_SIDED_UPPER }
enum NONLINEAR_EQUALITY_FORMAT { NONE, TRUE_EQUALITY, TWO_INEQUALITY }
enum NONLINEAR_INEQUALITY_FORMAT { NONE, ONE_SIDED_UPPER, ONE_SIDED_LOWER, TWO_SIDED }
enum {
COBYLA, DIRECT, EA, MS,
PS, SW, BETA, VARS_ERROR = -11,
CONS_ERROR = -10, RESP_ERROR = -9, APPROX_ERROR = -8, METHOD_ERROR = -7,
MODEL_ERROR = -6, IO_ERROR = -5, INTERFACE_ERROR = -4, CONSTRUCT_ERROR = -3,
PARSE_ERROR = -2, OTHER_ERROR = -1, DEFAULT_INTERFACE =0, APPROX_INTERFACE,
FORK_INTERFACE =PROCESS_INTERFACE_BIT, SYSTEM_INTERFACE, GRID_INTERFACE, TEST_INTERFACE =DIRECT_INTERFACE_BIT,
PLUGIN_INTERFACE, MATLAB_INTERFACE, LEGACY_PYTHON_INTERFACE, PYTHON_INTERFACE,
SCILAB_INTERFACE, DEFAULT_METHOD =0, HYBRID =(META_BIT | PARALLEL_BIT), PARETO_SET,
MULTI_START, RICHARDSON_EXTRAP =(ANALYZER_BIT | VERIF_BIT), CENTERED_PARAMETER_STUDY =(ANALYZER_BIT | PSTUDYDACE_BIT), LIST_PARAMETER_STUDY,
MULTIDIM_PARAMETER_STUDY, VECTOR_PARAMETER_STUDY, DACE, FSU_CVT,
FSU_HALTON, FSU_HAMMERSLEY, PSUADE_MOAT, LOCAL_RELIABILITY =(ANALYZER_BIT | NOND_BIT),
GLOBAL_RELIABILITY, SURROGATE_BASED_UQ, POLYNOMIAL_CHAOS, MULTILEVEL_POLYNOMIAL_CHAOS,
MULTIFIDELITY_POLYNOMIAL_CHAOS, STOCH_COLLOCATION, MULTIFIDELITY_STOCH_COLLOCATION, C3_FUNCTION_TRAIN,
MULTILEVEL_FUNCTION_TRAIN, MULTIFIDELITY_FUNCTION_TRAIN, CUBATURE_INTEGRATION, SPARSE_GRID_INTEGRATION,
QUADRATURE_INTEGRATION, BAYES_CALIBRATION, GPAIS, POF_DARTS,
RKD_DARTS, IMPORTANCE_SAMPLING, ADAPTIVE_SAMPLING, MULTILEVEL_SAMPLING,
MULTIFIDELITY_SAMPLING, MULTILEVEL_MULTIFIDELITY_SAMPLING, APPROXIMATE_CONTROL_VARIATE, LIST_SAMPLING,
RANDOM_SAMPLING, LOCAL_INTERVAL_EST, LOCAL_EVIDENCE, GLOBAL_INTERVAL_EST,
GLOBAL_EVIDENCE, SURROGATE_BASED_LOCAL =(MINIMIZER_BIT | SURRBASED_BIT), DATA_FIT_SURROGATE_BASED_LOCAL, HIERARCH_SURROGATE_BASED_LOCAL,
SURROGATE_BASED_GLOBAL, EFFICIENT_GLOBAL, NL2SOL =(MINIMIZER_BIT | LEASTSQ_BIT), NLSSOL_SQP,
OPTPP_G_NEWTON, ASYNCH_PATTERN_SEARCH =(MINIMIZER_BIT | OPTIMIZER_BIT), OPTPP_PDS, COLINY_BETA,
COLINY_COBYLA, COLINY_DIRECT, COLINY_MULTI_START, COLINY_EA,
COLINY_PATTERN_SEARCH, COLINY_SOLIS_WETS, MOGA, SOGA,
NCSU_DIRECT, MESH_ADAPTIVE_SEARCH, MIT_NOWPAC, MIT_SNOWPAC,
GENIE_OPT_DARTS, GENIE_DIRECT, DEMO_TPL, NONLINEAR_CG,
OPTPP_CG, OPTPP_Q_NEWTON, OPTPP_FD_NEWTON, OPTPP_NEWTON,
NPSOL_SQP, NLPQL_SQP, DOT_BFGS, DOT_FRCG,
DOT_MMFD, DOT_SLP, DOT_SQP, CONMIN_FRCG,
CONMIN_MFD, ROL, DL_SOLVER, BRANCH_AND_BOUND =(MINIMIZER_BIT | OPTIMIZER_BIT | LEASTSQ_BIT),
DEFAULT_POINTS, MINIMUM_POINTS, RECOMMENDED_POINTS, TOTAL_POINTS,
BASE_RESPONSE =0, SIMULATION_RESPONSE, EXPERIMENT_RESPONSE, DEFAULT_DOMAIN =0,
RELAXED_DOMAIN, MIXED_DOMAIN, DEFAULT_CORRECTION = 0, SINGLE_CORRECTION,
FULL_MODEL_FORM_CORRECTION, FULL_SOLUTION_LEVEL_CORRECTION, SEQUENCE_CORRECTION, SETUP_MODEL,
SETUP_USERFUNC, CAUVar_normal = 0, CAUVar_lognormal = 1, CAUVar_uniform = 2,
CAUVar_loguniform = 3, CAUVar_triangular = 4, CAUVar_exponential = 5, CAUVar_beta = 6,
CAUVar_gamma = 7, CAUVar_gumbel = 8, CAUVar_frechet = 9, CAUVar_weibull = 10,
CAUVar_histogram_bin = 11, CAUVar_Nkinds = 12, ANALYTIC_SOLUTION = 1, REORDERED_ANALYTIC_SOLUTION,
R_ONLY_LINEAR_CONSTRAINT, N_VECTOR_LINEAR_CONSTRAINT, R_AND_N_NONLINEAR_CONSTRAINT, N_VECTOR_LINEAR_OBJECTIVE,
FULL_TENSOR, FILTERED_TENSOR, RANDOM_TENSOR, AS_FUNC =1,
AS_GRAD =2, AS_HESS =4, DISALLOW, TARGET,
BOUNDS, SCALE_NONE = 0, SCALE_VALUE = 1, SCALE_LOG = 2,
SCALE_AUTO = 4, APPROX_RESPONSE =1, TRUTH_RESPONSE, TH_SILENT_OUTPUT,
TH_QUIET_OUTPUT, TH_NORMAL_OUTPUT, TH_VERBOSE_OUTPUT, TH_DEBUG_OUTPUT,
DIR_CLEAN, DIR_PERSIST, DIR_ERROR
}
special values for interface type
enum {
MODEL_EVAL_STORE_TOP_METHOD = 0, MODEL_EVAL_STORE_NONE, MODEL_EVAL_STORE_ALL, MODEL_EVAL_STORE_ALL_METHODS,
SYNCHRONOUS_INTERFACE, ASYNCHRONOUS_INTERFACE, SUBMETHOD_DEFAULT =0, SUBMETHOD_NONE,
SUBMETHOD_COLLABORATIVE, SUBMETHOD_EMBEDDED, SUBMETHOD_SEQUENTIAL, SUBMETHOD_LHS,
SUBMETHOD_RANDOM, SUBMETHOD_LOW_DISCREPANCY_SAMPLING, SUBMETHOD_BOX_BEHNKEN, SUBMETHOD_CENTRAL_COMPOSITE,
SUBMETHOD_GRID, SUBMETHOD_OA_LHS, SUBMETHOD_OAS, SUBMETHOD_MFMC,
SUBMETHOD_ACV_IS, SUBMETHOD_ACV_MF, SUBMETHOD_ACV_RD, SUBMETHOD_DREAM,
SUBMETHOD_GPMSA, SUBMETHOD_MUQ, SUBMETHOD_QUESO, SUBMETHOD_WASABI,
SUBMETHOD_CONMIN, SUBMETHOD_DOT, SUBMETHOD_NLPQL, SUBMETHOD_NPSOL,
SUBMETHOD_OPTPP, SUBMETHOD_NPSOL_OPTPP, SUBMETHOD_DIRECT, SUBMETHOD_DIRECT_NPSOL_OPTPP,
SUBMETHOD_DIRECT_NPSOL, SUBMETHOD_DIRECT_OPTPP, SUBMETHOD_EA, SUBMETHOD_EGO,
SUBMETHOD_SBLO, SUBMETHOD_SBGO, SUBMETHOD_AMV_X, SUBMETHOD_AMV_U,
SUBMETHOD_AMV_PLUS_X, SUBMETHOD_AMV_PLUS_U, SUBMETHOD_TANA_X, SUBMETHOD_TANA_U,
SUBMETHOD_QMEA_X, SUBMETHOD_QMEA_U, SUBMETHOD_NO_APPROX, SUBMETHOD_EGRA_X,
SUBMETHOD_EGRA_U, SUBMETHOD_CONVERGE_ORDER, SUBMETHOD_CONVERGE_QOI, SUBMETHOD_ESTIMATE_ORDER,
DEFAULT_SURROGATE_RESP_MODE =0, NO_SURROGATE, UNCORRECTED_SURROGATE, AUTO_CORRECTED_SURROGATE,
BYPASS_SURROGATE, MODEL_DISCREPANCY, AGGREGATED_MODEL_PAIR, AGGREGATED_MODELS,
GENERIC_FNS = 0, OBJECTIVE_FNS, CALIB_TERMS, DEFAULT_VIEW =0,
ALL_VIEW, DESIGN_VIEW, UNCERTAIN_VIEW, ALEATORY_UNCERTAIN_VIEW,
EPISTEMIC_UNCERTAIN_VIEW, STATE_VIEW, DAUIVar_poisson = 0, DAUIVar_binomial = 1,
DAUIVar_negative_binomial = 2, DAUIVar_geometric = 3, DAUIVar_hypergeometric = 4, DAUIVar_histogram_point_int = 5,
DAUIVar_Nkinds = 6, TYPE_U =1, TYPE_B =2, TYPE_E =3,
TYPE_EB =4, CORR_APPROX_RESPONSE =1, UNCORR_APPROX_RESPONSE, CORR_TRUTH_RESPONSE,
UNCORR_TRUTH_RESPONSE, FILEOP_SILENT, FILEOP_WARN, FILEOP_ERROR
}
interface synchronization types
enum {
INTERF_EVAL_STORE_SIMULATION = 0, INTERF_EVAL_STORE_NONE, INTERF_EVAL_STORE_ALL, OBJECTIVE,
INEQUALITY_CONSTRAINT, EQUALITY_CONSTRAINT, VBD_BINNED =0, VBD_PICK_AND_FREEZE,
NO_CORRECTION =0, ADDITIVE_CORRECTION, MULTIPLICATIVE_CORRECTION, COMBINED_CORRECTION,
EMPTY_VIEW =0, RELAXED_ALL, MIXED_ALL, RELAXED_DESIGN,
RELAXED_UNCERTAIN, RELAXED_ALEATORY_UNCERTAIN, RELAXED_EPISTEMIC_UNCERTAIN, RELAXED_STATE,
MIXED_DESIGN, MIXED_UNCERTAIN, MIXED_ALEATORY_UNCERTAIN, MIXED_EPISTEMIC_UNCERTAIN,
MIXED_STATE, DAUSVar_histogram_point_str = 0, DAUSVar_Nkinds = 1, NEW_CANDIDATE = 1,
CANDIDATE_ACCEPTED = 2, CANDIDATE_STATE = (NEW_CANDIDATE | CANDIDATE_ACCEPTED), NEW_CENTER = 8, CENTER_BUILT = 16,
CENTER_STATE = (NEW_CENTER | CENTER_BUILT), NEW_TR_FACTOR = 64, NEW_TRUST_REGION = (NEW_CENTER | NEW_TR_FACTOR), HARD_CONVERGED = 128,
SOFT_CONVERGED = 256, MIN_TR_CONVERGED = 512, MAX_ITER_CONVERGED = 1024, CONVERGED
}
define algebraic function types
enum {
COBYLA, DIRECT, EA, MS,
PS, SW, BETA, VARS_ERROR = -11,
CONS_ERROR = -10, RESP_ERROR = -9, APPROX_ERROR = -8, METHOD_ERROR = -7,
MODEL_ERROR = -6, IO_ERROR = -5, INTERFACE_ERROR = -4, CONSTRUCT_ERROR = -3,
PARSE_ERROR = -2, OTHER_ERROR = -1, DEFAULT_INTERFACE =0, APPROX_INTERFACE,
FORK_INTERFACE =PROCESS_INTERFACE_BIT, SYSTEM_INTERFACE, GRID_INTERFACE, TEST_INTERFACE =DIRECT_INTERFACE_BIT,
PLUGIN_INTERFACE, MATLAB_INTERFACE, LEGACY_PYTHON_INTERFACE, PYTHON_INTERFACE,
SCILAB_INTERFACE, DEFAULT_METHOD =0, HYBRID =(META_BIT | PARALLEL_BIT), PARETO_SET,
MULTI_START, RICHARDSON_EXTRAP =(ANALYZER_BIT | VERIF_BIT), CENTERED_PARAMETER_STUDY =(ANALYZER_BIT | PSTUDYDACE_BIT), LIST_PARAMETER_STUDY,
MULTIDIM_PARAMETER_STUDY, VECTOR_PARAMETER_STUDY, DACE, FSU_CVT,
FSU_HALTON, FSU_HAMMERSLEY, PSUADE_MOAT, LOCAL_RELIABILITY =(ANALYZER_BIT | NOND_BIT),
GLOBAL_RELIABILITY, SURROGATE_BASED_UQ, POLYNOMIAL_CHAOS, MULTILEVEL_POLYNOMIAL_CHAOS,
MULTIFIDELITY_POLYNOMIAL_CHAOS, STOCH_COLLOCATION, MULTIFIDELITY_STOCH_COLLOCATION, C3_FUNCTION_TRAIN,
MULTILEVEL_FUNCTION_TRAIN, MULTIFIDELITY_FUNCTION_TRAIN, CUBATURE_INTEGRATION, SPARSE_GRID_INTEGRATION,
QUADRATURE_INTEGRATION, BAYES_CALIBRATION, GPAIS, POF_DARTS,
RKD_DARTS, IMPORTANCE_SAMPLING, ADAPTIVE_SAMPLING, MULTILEVEL_SAMPLING,
MULTIFIDELITY_SAMPLING, MULTILEVEL_MULTIFIDELITY_SAMPLING, APPROXIMATE_CONTROL_VARIATE, LIST_SAMPLING,
RANDOM_SAMPLING, LOCAL_INTERVAL_EST, LOCAL_EVIDENCE, GLOBAL_INTERVAL_EST,
GLOBAL_EVIDENCE, SURROGATE_BASED_LOCAL =(MINIMIZER_BIT | SURRBASED_BIT), DATA_FIT_SURROGATE_BASED_LOCAL, HIERARCH_SURROGATE_BASED_LOCAL,
SURROGATE_BASED_GLOBAL, EFFICIENT_GLOBAL, NL2SOL =(MINIMIZER_BIT | LEASTSQ_BIT), NLSSOL_SQP,
OPTPP_G_NEWTON, ASYNCH_PATTERN_SEARCH =(MINIMIZER_BIT | OPTIMIZER_BIT), OPTPP_PDS, COLINY_BETA,
COLINY_COBYLA, COLINY_DIRECT, COLINY_MULTI_START, COLINY_EA,
COLINY_PATTERN_SEARCH, COLINY_SOLIS_WETS, MOGA, SOGA,
NCSU_DIRECT, MESH_ADAPTIVE_SEARCH, MIT_NOWPAC, MIT_SNOWPAC,
GENIE_OPT_DARTS, GENIE_DIRECT, DEMO_TPL, NONLINEAR_CG,
OPTPP_CG, OPTPP_Q_NEWTON, OPTPP_FD_NEWTON, OPTPP_NEWTON,
NPSOL_SQP, NLPQL_SQP, DOT_BFGS, DOT_FRCG,
DOT_MMFD, DOT_SLP, DOT_SQP, CONMIN_FRCG,
CONMIN_MFD, ROL, DL_SOLVER, BRANCH_AND_BOUND =(MINIMIZER_BIT | OPTIMIZER_BIT | LEASTSQ_BIT),
DEFAULT_POINTS, MINIMUM_POINTS, RECOMMENDED_POINTS, TOTAL_POINTS,
BASE_RESPONSE =0, SIMULATION_RESPONSE, EXPERIMENT_RESPONSE, DEFAULT_DOMAIN =0,
RELAXED_DOMAIN, MIXED_DOMAIN, DEFAULT_CORRECTION = 0, SINGLE_CORRECTION,
FULL_MODEL_FORM_CORRECTION, FULL_SOLUTION_LEVEL_CORRECTION, SEQUENCE_CORRECTION, SETUP_MODEL,
SETUP_USERFUNC, CAUVar_normal = 0, CAUVar_lognormal = 1, CAUVar_uniform = 2,
CAUVar_loguniform = 3, CAUVar_triangular = 4, CAUVar_exponential = 5, CAUVar_beta = 6,
CAUVar_gamma = 7, CAUVar_gumbel = 8, CAUVar_frechet = 9, CAUVar_weibull = 10,
CAUVar_histogram_bin = 11, CAUVar_Nkinds = 12, ANALYTIC_SOLUTION = 1, REORDERED_ANALYTIC_SOLUTION,
R_ONLY_LINEAR_CONSTRAINT, N_VECTOR_LINEAR_CONSTRAINT, R_AND_N_NONLINEAR_CONSTRAINT, N_VECTOR_LINEAR_OBJECTIVE,
FULL_TENSOR, FILTERED_TENSOR, RANDOM_TENSOR, AS_FUNC =1,
AS_GRAD =2, AS_HESS =4, DISALLOW, TARGET,
BOUNDS, SCALE_NONE = 0, SCALE_VALUE = 1, SCALE_LOG = 2,
SCALE_AUTO = 4, APPROX_RESPONSE =1, TRUTH_RESPONSE, TH_SILENT_OUTPUT,
TH_QUIET_OUTPUT, TH_NORMAL_OUTPUT, TH_VERBOSE_OUTPUT, TH_DEBUG_OUTPUT,
DIR_CLEAN, DIR_PERSIST, DIR_ERROR
}
enum {
MODEL_EVAL_STORE_TOP_METHOD = 0, MODEL_EVAL_STORE_NONE, MODEL_EVAL_STORE_ALL, MODEL_EVAL_STORE_ALL_METHODS,
SYNCHRONOUS_INTERFACE, ASYNCHRONOUS_INTERFACE, SUBMETHOD_DEFAULT =0, SUBMETHOD_NONE,
SUBMETHOD_COLLABORATIVE, SUBMETHOD_EMBEDDED, SUBMETHOD_SEQUENTIAL, SUBMETHOD_LHS,
SUBMETHOD_RANDOM, SUBMETHOD_LOW_DISCREPANCY_SAMPLING, SUBMETHOD_BOX_BEHNKEN, SUBMETHOD_CENTRAL_COMPOSITE,
SUBMETHOD_GRID, SUBMETHOD_OA_LHS, SUBMETHOD_OAS, SUBMETHOD_MFMC,
SUBMETHOD_ACV_IS, SUBMETHOD_ACV_MF, SUBMETHOD_ACV_RD, SUBMETHOD_DREAM,
SUBMETHOD_GPMSA, SUBMETHOD_MUQ, SUBMETHOD_QUESO, SUBMETHOD_WASABI,
SUBMETHOD_CONMIN, SUBMETHOD_DOT, SUBMETHOD_NLPQL, SUBMETHOD_NPSOL,
SUBMETHOD_OPTPP, SUBMETHOD_NPSOL_OPTPP, SUBMETHOD_DIRECT, SUBMETHOD_DIRECT_NPSOL_OPTPP,
SUBMETHOD_DIRECT_NPSOL, SUBMETHOD_DIRECT_OPTPP, SUBMETHOD_EA, SUBMETHOD_EGO,
SUBMETHOD_SBLO, SUBMETHOD_SBGO, SUBMETHOD_AMV_X, SUBMETHOD_AMV_U,
SUBMETHOD_AMV_PLUS_X, SUBMETHOD_AMV_PLUS_U, SUBMETHOD_TANA_X, SUBMETHOD_TANA_U,
SUBMETHOD_QMEA_X, SUBMETHOD_QMEA_U, SUBMETHOD_NO_APPROX, SUBMETHOD_EGRA_X,
SUBMETHOD_EGRA_U, SUBMETHOD_CONVERGE_ORDER, SUBMETHOD_CONVERGE_QOI, SUBMETHOD_ESTIMATE_ORDER,
DEFAULT_SURROGATE_RESP_MODE =0, NO_SURROGATE, UNCORRECTED_SURROGATE, AUTO_CORRECTED_SURROGATE,
BYPASS_SURROGATE, MODEL_DISCREPANCY, AGGREGATED_MODEL_PAIR, AGGREGATED_MODELS,
GENERIC_FNS = 0, OBJECTIVE_FNS, CALIB_TERMS, DEFAULT_VIEW =0,
ALL_VIEW, DESIGN_VIEW, UNCERTAIN_VIEW, ALEATORY_UNCERTAIN_VIEW,
EPISTEMIC_UNCERTAIN_VIEW, STATE_VIEW, DAUIVar_poisson = 0, DAUIVar_binomial = 1,
DAUIVar_negative_binomial = 2, DAUIVar_geometric = 3, DAUIVar_hypergeometric = 4, DAUIVar_histogram_point_int = 5,
DAUIVar_Nkinds = 6, TYPE_U =1, TYPE_B =2, TYPE_E =3,
TYPE_EB =4, CORR_APPROX_RESPONSE =1, UNCORR_APPROX_RESPONSE, CORR_TRUTH_RESPONSE,
UNCORR_TRUTH_RESPONSE, FILEOP_SILENT, FILEOP_WARN, FILEOP_ERROR
}
Sub-methods, including sampling, inference algorithm, opt algorithm types.
enum {
INTERF_EVAL_STORE_SIMULATION = 0, INTERF_EVAL_STORE_NONE, INTERF_EVAL_STORE_ALL, OBJECTIVE,
INEQUALITY_CONSTRAINT, EQUALITY_CONSTRAINT, VBD_BINNED =0, VBD_PICK_AND_FREEZE,
NO_CORRECTION =0, ADDITIVE_CORRECTION, MULTIPLICATIVE_CORRECTION, COMBINED_CORRECTION,
EMPTY_VIEW =0, RELAXED_ALL, MIXED_ALL, RELAXED_DESIGN,
RELAXED_UNCERTAIN, RELAXED_ALEATORY_UNCERTAIN, RELAXED_EPISTEMIC_UNCERTAIN, RELAXED_STATE,
MIXED_DESIGN, MIXED_UNCERTAIN, MIXED_ALEATORY_UNCERTAIN, MIXED_EPISTEMIC_UNCERTAIN,
MIXED_STATE, DAUSVar_histogram_point_str = 0, DAUSVar_Nkinds = 1, NEW_CANDIDATE = 1,
CANDIDATE_ACCEPTED = 2, CANDIDATE_STATE = (NEW_CANDIDATE | CANDIDATE_ACCEPTED), NEW_CENTER = 8, CENTER_BUILT = 16,
CENTER_STATE = (NEW_CENTER | CENTER_BUILT), NEW_TR_FACTOR = 64, NEW_TRUST_REGION = (NEW_CENTER | NEW_TR_FACTOR), HARD_CONVERGED = 128,
SOFT_CONVERGED = 256, MIN_TR_CONVERGED = 512, MAX_ITER_CONVERGED = 1024, CONVERGED
}
Sampling method for variance based decomposition (VBD)
enum {
ABORT_EXITS, ABORT_THROWS, NO_GRAPH_RECURSION =0, KL_GRAPH_RECURSION,
PARTIAL_GRAPH_RECURSION, FULL_GRAPH_RECURSION, RF_KARHUNEN_LOEVE =0, RF_PCA_GP,
RF_ICA, ALL_VARS =0, ACTIVE_VARS, INACTIVE_VARS,
DAURVar_histogram_point_real = 0, DAURVar_Nkinds = 1
}
Graph recursion options for generalized ACV.
enum {
CV_ID_DEFAULT = 0, MINIMUM_METRIC, RELATIVE_TOLERANCE, DECREASE_TOLERANCE,
NO_MODEL_SELECTION =0, ALL_MODEL_COMBINATIONS, NOCOVAR =0, EXP_L2,
EXP_L1, EMPTY_TYPE =0, CONTINUOUS_DESIGN, DISCRETE_DESIGN_RANGE,
DISCRETE_DESIGN_SET_INT, DISCRETE_DESIGN_SET_STRING, DISCRETE_DESIGN_SET_REAL, NORMAL_UNCERTAIN,
LOGNORMAL_UNCERTAIN, UNIFORM_UNCERTAIN, LOGUNIFORM_UNCERTAIN, TRIANGULAR_UNCERTAIN,
EXPONENTIAL_UNCERTAIN, BETA_UNCERTAIN, GAMMA_UNCERTAIN, GUMBEL_UNCERTAIN,
FRECHET_UNCERTAIN, WEIBULL_UNCERTAIN, HISTOGRAM_BIN_UNCERTAIN, POISSON_UNCERTAIN,
BINOMIAL_UNCERTAIN, NEGATIVE_BINOMIAL_UNCERTAIN, GEOMETRIC_UNCERTAIN, HYPERGEOMETRIC_UNCERTAIN,
HISTOGRAM_POINT_UNCERTAIN_INT, HISTOGRAM_POINT_UNCERTAIN_STRING, HISTOGRAM_POINT_UNCERTAIN_REAL, CONTINUOUS_INTERVAL_UNCERTAIN,
DISCRETE_INTERVAL_UNCERTAIN, DISCRETE_UNCERTAIN_SET_INT, DISCRETE_UNCERTAIN_SET_STRING, DISCRETE_UNCERTAIN_SET_REAL,
CONTINUOUS_STATE, DISCRETE_STATE_RANGE, DISCRETE_STATE_SET_INT, DISCRETE_STATE_SET_STRING,
DISCRETE_STATE_SET_REAL, CEUVar_interval = 0, CEUVar_Nkinds = 1
}
Model selection options for generalized ACV.
enum {
TABULAR_NONE = 0, TABULAR_HEADER = 1, TABULAR_EVAL_ID = 2, TABULAR_IFACE_ID = 4,
TABULAR_EXPER_ANNOT = TABULAR_HEADER | TABULAR_EVAL_ID, TABULAR_ANNOTATED = TABULAR_HEADER | TABULAR_EVAL_ID | TABULAR_IFACE_ID, SILENT_OUTPUT, QUIET_OUTPUT,
NORMAL_OUTPUT, VERBOSE_OUTPUT, DEBUG_OUTPUT, SUBSPACE_NORM_DEFAULT =0,
SUBSPACE_NORM_MEAN_VALUE, SUBSPACE_NORM_MEAN_GRAD, SUBSPACE_NORM_LOCAL_GRAD, TOTAL_CDV =0,
TOTAL_DDIV, TOTAL_DDSV, TOTAL_DDRV, TOTAL_CAUV,
TOTAL_DAUIV, TOTAL_DAUSV, TOTAL_DAURV, TOTAL_CEUV,
TOTAL_DEUIV, TOTAL_DEUSV, TOTAL_DEURV, TOTAL_CSV,
TOTAL_DSIV, TOTAL_DSSV, TOTAL_DSRV, NUM_VC_TOTALS,
DEUIVar_interval = 0, DEUIVar_set_int = 1, DEUIVar_Nkinds = 2
}
enum {
RESULTS_OUTPUT_TEXT = 1, RESULTS_OUTPUT_HDF5 = 2, NO_RESULTS =0, REFINEMENT_RESULTS,
INTERMEDIATE_RESULTS, FINAL_RESULTS, ROTATION_METHOD_UNRANKED, ROTATION_METHOD_RANKED,
DEUSVar_set_str = 0, DEUSVar_Nkinds = 1
}
enum {
FLEXIBLE_RESULTS, LABELED_RESULTS, DEFAULT_SYNCHRONIZATION =0, BLOCKING_SYNCHRONIZATION,
NONBLOCKING_SYNCHRONIZATION, NO_PARALLEL_MODE =0, SURROGATE_MODEL_MODE, TRUTH_MODEL_MODE,
SUB_MODEL_MODE, INTERFACE_MODE, DEURVar_set_real = 0, DEURVar_Nkinds = 1
}
enum {
NO_MODEL_FORMAT =0, TEXT_ARCHIVE =1, BINARY_ARCHIVE =2, ALGEBRAIC_FILE =4,
ALGEBRAIC_CONSOLE =8, DEFAULT_SCHEDULING, MASTER_SCHEDULING, PEER_SCHEDULING,
PEER_DYNAMIC_SCHEDULING, PEER_STATIC_SCHEDULING, DYNAMIC_SCHEDULING, STATIC_SCHEDULING,
NO_DERIVS =0, ALL_DERIVS, MIXED_DERIVS, DiscSetVar_design_set_int = 0,
DiscSetVar_design_set_str = 1, DiscSetVar_design_set_real = 2, DiscSetVar_state_set_int = 3, DiscSetVar_state_set_str = 4,
DiscSetVar_state_set_real = 5, DiscSetVar_Nkinds = 6
}
enum {
DEFAULT_CONFIG, PUSH_DOWN, PUSH_UP, FT_LS,
FT_RLS2, NUM_UNC_REAL_CONT = 4
}
enum {
STD_NORMAL_U, STD_UNIFORM_U, PARTIAL_ASKEY_U, ASKEY_U,
EXTENDED_U, NO_C3_ADVANCEMENT =0, START_RANK_ADVANCEMENT, START_ORDER_ADVANCEMENT,
MAX_RANK_ADVANCEMENT, MAX_ORDER_ADVANCEMENT, MAX_RANK_ORDER_ADVANCEMENT, NUM_UNC_INT_CONT = 2
}
enum {
DEFAULT_COVARIANCE, NO_COVARIANCE, DIAGONAL_COVARIANCE, FULL_COVARIANCE,
NUM_UNC_STR_CONT = 2
}
enum { NO_INT_REFINE =0, IS, AIS, MMAIS }
enum { PROBABILITIES, RELIABILITIES, GEN_RELIABILITIES }
enum { COMPONENT =0, SYSTEM_SERIES, SYSTEM_PARALLEL }
enum { CUMULATIVE, COMPLEMENTARY }
enum { DEFAULT_LS =0, SVD_LS, EQ_CON_LS }
enum {
DEFAULT_MLMF_CONTROL =0, ESTIMATOR_VARIANCE, RIP_SAMPLING, RANK_SAMPLING,
GREEDY_REFINEMENT
}
enum { DEFAULT_EMULATION, DISTINCT_EMULATION, RECURSIVE_EMULATION }
enum {
NO_EMULATOR, PCE_EMULATOR, ML_PCE_EMULATOR, MF_PCE_EMULATOR,
SC_EMULATOR, MF_SC_EMULATOR, GP_EMULATOR, KRIGING_EMULATOR,
EXPGP_EMULATOR, VPS_EMULATOR
}
enum {
CALIBRATE_NONE = 0, CALIBRATE_ONE, CALIBRATE_PER_EXPER, CALIBRATE_PER_RESP,
CALIBRATE_BOTH
}
enum { IGNORE_RANKS, SET_RANKS, GET_RANKS, SET_GET_RANKS }
enum {
DESIGN, UNCERTAIN, UNCERTAIN_UNIFORM, ALEATORY_UNCERTAIN,
ALEATORY_UNCERTAIN_UNIFORM, EPISTEMIC_UNCERTAIN, EPISTEMIC_UNCERTAIN_UNIFORM, STATE,
ACTIVE, ACTIVE_UNIFORM, ALL, ALL_UNIFORM
}
enum {
ONE_SIDED_LOWER, ONE_SIDED_UPPER, NONE, TWO_SIDED,
ONE_SIDED_LOWER, ONE_SIDED_UPPER, TWO_SIDED, NONE,
ONE_SIDED_UPPER, ONE_SIDED_LOWER, TWO_SIDED
}
enum { NO_FINAL_STATS =0, QOI_STATISTICS, ESTIMATOR_PERFORMANCE }
enum { QOI_AGGREGATION_MAX, QOI_AGGREGATION_SUM }
enum { TARGET_MEAN, TARGET_VARIANCE, TARGET_SIGMA, TARGET_SCALARIZATION }
enum { CONVERGENCE_TOLERANCE_TYPE_RELATIVE, CONVERGENCE_TOLERANCE_TYPE_ABSOLUTE }
enum { CONVERGENCE_TOLERANCE_TARGET_VARIANCE_CONSTRAINT, CONVERGENCE_TOLERANCE_TARGET_COST_CONSTRAINT }
enum { ONLINE_PILOT, OFFLINE_PILOT, PILOT_PROJECTION }
enum { REORDERED_FALLBACK, NUMERICAL_FALLBACK, NUMERICAL_OVERRIDE }
enum { BREITUNG, HOHENRACK, HONG }
enum { ORIGINAL_PRIMARY, SINGLE_OBJECTIVE, LAGRANGIAN_OBJECTIVE, AUGMENTED_LAGRANGIAN_OBJECTIVE }
enum { NO_CONSTRAINTS, LINEARIZED_CONSTRAINTS, ORIGINAL_CONSTRAINTS }
enum { NO_RELAX, HOMOTOPY, COMPOSITE_STEP }
enum { PENALTY_MERIT, ADAPTIVE_PENALTY_MERIT, LAGRANGIAN_MERIT, AUGMENTED_LAGRANGIAN_MERIT }
enum { FILTER, TR_RATIO }
enum {
COBYLA, DIRECT, EA, MS,
PS, SW, BETA, VARS_ERROR = -11,
CONS_ERROR = -10, RESP_ERROR = -9, APPROX_ERROR = -8, METHOD_ERROR = -7,
MODEL_ERROR = -6, IO_ERROR = -5, INTERFACE_ERROR = -4, CONSTRUCT_ERROR = -3,
PARSE_ERROR = -2, OTHER_ERROR = -1, DEFAULT_INTERFACE =0, APPROX_INTERFACE,
FORK_INTERFACE =PROCESS_INTERFACE_BIT, SYSTEM_INTERFACE, GRID_INTERFACE, TEST_INTERFACE =DIRECT_INTERFACE_BIT,
PLUGIN_INTERFACE, MATLAB_INTERFACE, LEGACY_PYTHON_INTERFACE, PYTHON_INTERFACE,
SCILAB_INTERFACE, DEFAULT_METHOD =0, HYBRID =(META_BIT | PARALLEL_BIT), PARETO_SET,
MULTI_START, RICHARDSON_EXTRAP =(ANALYZER_BIT | VERIF_BIT), CENTERED_PARAMETER_STUDY =(ANALYZER_BIT | PSTUDYDACE_BIT), LIST_PARAMETER_STUDY,
MULTIDIM_PARAMETER_STUDY, VECTOR_PARAMETER_STUDY, DACE, FSU_CVT,
FSU_HALTON, FSU_HAMMERSLEY, PSUADE_MOAT, LOCAL_RELIABILITY =(ANALYZER_BIT | NOND_BIT),
GLOBAL_RELIABILITY, SURROGATE_BASED_UQ, POLYNOMIAL_CHAOS, MULTILEVEL_POLYNOMIAL_CHAOS,
MULTIFIDELITY_POLYNOMIAL_CHAOS, STOCH_COLLOCATION, MULTIFIDELITY_STOCH_COLLOCATION, C3_FUNCTION_TRAIN,
MULTILEVEL_FUNCTION_TRAIN, MULTIFIDELITY_FUNCTION_TRAIN, CUBATURE_INTEGRATION, SPARSE_GRID_INTEGRATION,
QUADRATURE_INTEGRATION, BAYES_CALIBRATION, GPAIS, POF_DARTS,
RKD_DARTS, IMPORTANCE_SAMPLING, ADAPTIVE_SAMPLING, MULTILEVEL_SAMPLING,
MULTIFIDELITY_SAMPLING, MULTILEVEL_MULTIFIDELITY_SAMPLING, APPROXIMATE_CONTROL_VARIATE, LIST_SAMPLING,
RANDOM_SAMPLING, LOCAL_INTERVAL_EST, LOCAL_EVIDENCE, GLOBAL_INTERVAL_EST,
GLOBAL_EVIDENCE, SURROGATE_BASED_LOCAL =(MINIMIZER_BIT | SURRBASED_BIT), DATA_FIT_SURROGATE_BASED_LOCAL, HIERARCH_SURROGATE_BASED_LOCAL,
SURROGATE_BASED_GLOBAL, EFFICIENT_GLOBAL, NL2SOL =(MINIMIZER_BIT | LEASTSQ_BIT), NLSSOL_SQP,
OPTPP_G_NEWTON, ASYNCH_PATTERN_SEARCH =(MINIMIZER_BIT | OPTIMIZER_BIT), OPTPP_PDS, COLINY_BETA,
COLINY_COBYLA, COLINY_DIRECT, COLINY_MULTI_START, COLINY_EA,
COLINY_PATTERN_SEARCH, COLINY_SOLIS_WETS, MOGA, SOGA,
NCSU_DIRECT, MESH_ADAPTIVE_SEARCH, MIT_NOWPAC, MIT_SNOWPAC,
GENIE_OPT_DARTS, GENIE_DIRECT, DEMO_TPL, NONLINEAR_CG,
OPTPP_CG, OPTPP_Q_NEWTON, OPTPP_FD_NEWTON, OPTPP_NEWTON,
NPSOL_SQP, NLPQL_SQP, DOT_BFGS, DOT_FRCG,
DOT_MMFD, DOT_SLP, DOT_SQP, CONMIN_FRCG,
CONMIN_MFD, ROL, DL_SOLVER, BRANCH_AND_BOUND =(MINIMIZER_BIT | OPTIMIZER_BIT | LEASTSQ_BIT),
DEFAULT_POINTS, MINIMUM_POINTS, RECOMMENDED_POINTS, TOTAL_POINTS,
BASE_RESPONSE =0, SIMULATION_RESPONSE, EXPERIMENT_RESPONSE, DEFAULT_DOMAIN =0,
RELAXED_DOMAIN, MIXED_DOMAIN, DEFAULT_CORRECTION = 0, SINGLE_CORRECTION,
FULL_MODEL_FORM_CORRECTION, FULL_SOLUTION_LEVEL_CORRECTION, SEQUENCE_CORRECTION, SETUP_MODEL,
SETUP_USERFUNC, CAUVar_normal = 0, CAUVar_lognormal = 1, CAUVar_uniform = 2,
CAUVar_loguniform = 3, CAUVar_triangular = 4, CAUVar_exponential = 5, CAUVar_beta = 6,
CAUVar_gamma = 7, CAUVar_gumbel = 8, CAUVar_frechet = 9, CAUVar_weibull = 10,
CAUVar_histogram_bin = 11, CAUVar_Nkinds = 12, ANALYTIC_SOLUTION = 1, REORDERED_ANALYTIC_SOLUTION,
R_ONLY_LINEAR_CONSTRAINT, N_VECTOR_LINEAR_CONSTRAINT, R_AND_N_NONLINEAR_CONSTRAINT, N_VECTOR_LINEAR_OBJECTIVE,
FULL_TENSOR, FILTERED_TENSOR, RANDOM_TENSOR, AS_FUNC =1,
AS_GRAD =2, AS_HESS =4, DISALLOW, TARGET,
BOUNDS, SCALE_NONE = 0, SCALE_VALUE = 1, SCALE_LOG = 2,
SCALE_AUTO = 4, APPROX_RESPONSE =1, TRUTH_RESPONSE, TH_SILENT_OUTPUT,
TH_QUIET_OUTPUT, TH_NORMAL_OUTPUT, TH_VERBOSE_OUTPUT, TH_DEBUG_OUTPUT,
DIR_CLEAN, DIR_PERSIST, DIR_ERROR
}
define special values for pointsManagement
enum {
MODEL_EVAL_STORE_TOP_METHOD = 0, MODEL_EVAL_STORE_NONE, MODEL_EVAL_STORE_ALL, MODEL_EVAL_STORE_ALL_METHODS,
SYNCHRONOUS_INTERFACE, ASYNCHRONOUS_INTERFACE, SUBMETHOD_DEFAULT =0, SUBMETHOD_NONE,
SUBMETHOD_COLLABORATIVE, SUBMETHOD_EMBEDDED, SUBMETHOD_SEQUENTIAL, SUBMETHOD_LHS,
SUBMETHOD_RANDOM, SUBMETHOD_LOW_DISCREPANCY_SAMPLING, SUBMETHOD_BOX_BEHNKEN, SUBMETHOD_CENTRAL_COMPOSITE,
SUBMETHOD_GRID, SUBMETHOD_OA_LHS, SUBMETHOD_OAS, SUBMETHOD_MFMC,
SUBMETHOD_ACV_IS, SUBMETHOD_ACV_MF, SUBMETHOD_ACV_RD, SUBMETHOD_DREAM,
SUBMETHOD_GPMSA, SUBMETHOD_MUQ, SUBMETHOD_QUESO, SUBMETHOD_WASABI,
SUBMETHOD_CONMIN, SUBMETHOD_DOT, SUBMETHOD_NLPQL, SUBMETHOD_NPSOL,
SUBMETHOD_OPTPP, SUBMETHOD_NPSOL_OPTPP, SUBMETHOD_DIRECT, SUBMETHOD_DIRECT_NPSOL_OPTPP,
SUBMETHOD_DIRECT_NPSOL, SUBMETHOD_DIRECT_OPTPP, SUBMETHOD_EA, SUBMETHOD_EGO,
SUBMETHOD_SBLO, SUBMETHOD_SBGO, SUBMETHOD_AMV_X, SUBMETHOD_AMV_U,
SUBMETHOD_AMV_PLUS_X, SUBMETHOD_AMV_PLUS_U, SUBMETHOD_TANA_X, SUBMETHOD_TANA_U,
SUBMETHOD_QMEA_X, SUBMETHOD_QMEA_U, SUBMETHOD_NO_APPROX, SUBMETHOD_EGRA_X,
SUBMETHOD_EGRA_U, SUBMETHOD_CONVERGE_ORDER, SUBMETHOD_CONVERGE_QOI, SUBMETHOD_ESTIMATE_ORDER,
DEFAULT_SURROGATE_RESP_MODE =0, NO_SURROGATE, UNCORRECTED_SURROGATE, AUTO_CORRECTED_SURROGATE,
BYPASS_SURROGATE, MODEL_DISCREPANCY, AGGREGATED_MODEL_PAIR, AGGREGATED_MODELS,
GENERIC_FNS = 0, OBJECTIVE_FNS, CALIB_TERMS, DEFAULT_VIEW =0,
ALL_VIEW, DESIGN_VIEW, UNCERTAIN_VIEW, ALEATORY_UNCERTAIN_VIEW,
EPISTEMIC_UNCERTAIN_VIEW, STATE_VIEW, DAUIVar_poisson = 0, DAUIVar_binomial = 1,
DAUIVar_negative_binomial = 2, DAUIVar_geometric = 3, DAUIVar_hypergeometric = 4, DAUIVar_histogram_point_int = 5,
DAUIVar_Nkinds = 6, TYPE_U =1, TYPE_B =2, TYPE_E =3,
TYPE_EB =4, CORR_APPROX_RESPONSE =1, UNCORR_APPROX_RESPONSE, CORR_TRUTH_RESPONSE,
UNCORR_TRUTH_RESPONSE, FILEOP_SILENT, FILEOP_WARN, FILEOP_ERROR
}
define special values for SurrogateModel::responseMode
enum {
INTERF_EVAL_STORE_SIMULATION = 0, INTERF_EVAL_STORE_NONE, INTERF_EVAL_STORE_ALL, OBJECTIVE,
INEQUALITY_CONSTRAINT, EQUALITY_CONSTRAINT, VBD_BINNED =0, VBD_PICK_AND_FREEZE,
NO_CORRECTION =0, ADDITIVE_CORRECTION, MULTIPLICATIVE_CORRECTION, COMBINED_CORRECTION,
EMPTY_VIEW =0, RELAXED_ALL, MIXED_ALL, RELAXED_DESIGN,
RELAXED_UNCERTAIN, RELAXED_ALEATORY_UNCERTAIN, RELAXED_EPISTEMIC_UNCERTAIN, RELAXED_STATE,
MIXED_DESIGN, MIXED_UNCERTAIN, MIXED_ALEATORY_UNCERTAIN, MIXED_EPISTEMIC_UNCERTAIN,
MIXED_STATE, DAUSVar_histogram_point_str = 0, DAUSVar_Nkinds = 1, NEW_CANDIDATE = 1,
CANDIDATE_ACCEPTED = 2, CANDIDATE_STATE = (NEW_CANDIDATE | CANDIDATE_ACCEPTED), NEW_CENTER = 8, CENTER_BUILT = 16,
CENTER_STATE = (NEW_CENTER | CENTER_BUILT), NEW_TR_FACTOR = 64, NEW_TRUST_REGION = (NEW_CENTER | NEW_TR_FACTOR), HARD_CONVERGED = 128,
SOFT_CONVERGED = 256, MIN_TR_CONVERGED = 512, MAX_ITER_CONVERGED = 1024, CONVERGED
}
define special values for approxCorrectionType
enum {
ABORT_EXITS, ABORT_THROWS, NO_GRAPH_RECURSION =0, KL_GRAPH_RECURSION,
PARTIAL_GRAPH_RECURSION, FULL_GRAPH_RECURSION, RF_KARHUNEN_LOEVE =0, RF_PCA_GP,
RF_ICA, ALL_VARS =0, ACTIVE_VARS, INACTIVE_VARS,
DAURVar_histogram_point_real = 0, DAURVar_Nkinds = 1
}
define types of random field approximations
enum {
CV_ID_DEFAULT = 0, MINIMUM_METRIC, RELATIVE_TOLERANCE, DECREASE_TOLERANCE,
NO_MODEL_SELECTION =0, ALL_MODEL_COMBINATIONS, NOCOVAR =0, EXP_L2,
EXP_L1, EMPTY_TYPE =0, CONTINUOUS_DESIGN, DISCRETE_DESIGN_RANGE,
DISCRETE_DESIGN_SET_INT, DISCRETE_DESIGN_SET_STRING, DISCRETE_DESIGN_SET_REAL, NORMAL_UNCERTAIN,
LOGNORMAL_UNCERTAIN, UNIFORM_UNCERTAIN, LOGUNIFORM_UNCERTAIN, TRIANGULAR_UNCERTAIN,
EXPONENTIAL_UNCERTAIN, BETA_UNCERTAIN, GAMMA_UNCERTAIN, GUMBEL_UNCERTAIN,
FRECHET_UNCERTAIN, WEIBULL_UNCERTAIN, HISTOGRAM_BIN_UNCERTAIN, POISSON_UNCERTAIN,
BINOMIAL_UNCERTAIN, NEGATIVE_BINOMIAL_UNCERTAIN, GEOMETRIC_UNCERTAIN, HYPERGEOMETRIC_UNCERTAIN,
HISTOGRAM_POINT_UNCERTAIN_INT, HISTOGRAM_POINT_UNCERTAIN_STRING, HISTOGRAM_POINT_UNCERTAIN_REAL, CONTINUOUS_INTERVAL_UNCERTAIN,
DISCRETE_INTERVAL_UNCERTAIN, DISCRETE_UNCERTAIN_SET_INT, DISCRETE_UNCERTAIN_SET_STRING, DISCRETE_UNCERTAIN_SET_REAL,
CONTINUOUS_STATE, DISCRETE_STATE_RANGE, DISCRETE_STATE_SET_INT, DISCRETE_STATE_SET_STRING,
DISCRETE_STATE_SET_REAL, CEUVar_interval = 0, CEUVar_Nkinds = 1
}
define types of analytic covariance functions
enum {
TABULAR_NONE = 0, TABULAR_HEADER = 1, TABULAR_EVAL_ID = 2, TABULAR_IFACE_ID = 4,
TABULAR_EXPER_ANNOT = TABULAR_HEADER | TABULAR_EVAL_ID, TABULAR_ANNOTATED = TABULAR_HEADER | TABULAR_EVAL_ID | TABULAR_IFACE_ID, SILENT_OUTPUT, QUIET_OUTPUT,
NORMAL_OUTPUT, VERBOSE_OUTPUT, DEBUG_OUTPUT, SUBSPACE_NORM_DEFAULT =0,
SUBSPACE_NORM_MEAN_VALUE, SUBSPACE_NORM_MEAN_GRAD, SUBSPACE_NORM_LOCAL_GRAD, TOTAL_CDV =0,
TOTAL_DDIV, TOTAL_DDSV, TOTAL_DDRV, TOTAL_CAUV,
TOTAL_DAUIV, TOTAL_DAUSV, TOTAL_DAURV, TOTAL_CEUV,
TOTAL_DEUIV, TOTAL_DEUSV, TOTAL_DEURV, TOTAL_CSV,
TOTAL_DSIV, TOTAL_DSSV, TOTAL_DSRV, NUM_VC_TOTALS,
DEUIVar_interval = 0, DEUIVar_set_int = 1, DEUIVar_Nkinds = 2
}
define special values for active subspace normalizations
enum {
RESULTS_OUTPUT_TEXT = 1, RESULTS_OUTPUT_HDF5 = 2, NO_RESULTS =0, REFINEMENT_RESULTS,
INTERMEDIATE_RESULTS, FINAL_RESULTS, ROTATION_METHOD_UNRANKED, ROTATION_METHOD_RANKED,
DEUSVar_set_str = 0, DEUSVar_Nkinds = 1
}
enum {
FLEXIBLE_RESULTS, LABELED_RESULTS, DEFAULT_SYNCHRONIZATION =0, BLOCKING_SYNCHRONIZATION,
NONBLOCKING_SYNCHRONIZATION, NO_PARALLEL_MODE =0, SURROGATE_MODEL_MODE, TRUTH_MODEL_MODE,
SUB_MODEL_MODE, INTERFACE_MODE, DEURVar_set_real = 0, DEURVar_Nkinds = 1
}
define special values for componentParallelMode (active model for parallel scheduling)
enum {
NO_MODEL_FORMAT =0, TEXT_ARCHIVE =1, BINARY_ARCHIVE =2, ALGEBRAIC_FILE =4,
ALGEBRAIC_CONSOLE =8, DEFAULT_SCHEDULING, MASTER_SCHEDULING, PEER_SCHEDULING,
PEER_DYNAMIC_SCHEDULING, PEER_STATIC_SCHEDULING, DYNAMIC_SCHEDULING, STATIC_SCHEDULING,
NO_DERIVS =0, ALL_DERIVS, MIXED_DERIVS, DiscSetVar_design_set_int = 0,
DiscSetVar_design_set_str = 1, DiscSetVar_design_set_real = 2, DiscSetVar_state_set_int = 3, DiscSetVar_state_set_str = 4,
DiscSetVar_state_set_real = 5, DiscSetVar_Nkinds = 6
}
define special values for distParamDerivs
enum {
DEFAULT_CONFIG, PUSH_DOWN, PUSH_UP, FT_LS,
FT_RLS2, NUM_UNC_REAL_CONT = 4
}
enum {
STD_NORMAL_U, STD_UNIFORM_U, PARTIAL_ASKEY_U, ASKEY_U,
EXTENDED_U, NO_C3_ADVANCEMENT =0, START_RANK_ADVANCEMENT, START_ORDER_ADVANCEMENT,
MAX_RANK_ADVANCEMENT, MAX_ORDER_ADVANCEMENT, MAX_RANK_ORDER_ADVANCEMENT, NUM_UNC_INT_CONT = 2
}
enum {
COBYLA, DIRECT, EA, MS,
PS, SW, BETA, VARS_ERROR = -11,
CONS_ERROR = -10, RESP_ERROR = -9, APPROX_ERROR = -8, METHOD_ERROR = -7,
MODEL_ERROR = -6, IO_ERROR = -5, INTERFACE_ERROR = -4, CONSTRUCT_ERROR = -3,
PARSE_ERROR = -2, OTHER_ERROR = -1, DEFAULT_INTERFACE =0, APPROX_INTERFACE,
FORK_INTERFACE =PROCESS_INTERFACE_BIT, SYSTEM_INTERFACE, GRID_INTERFACE, TEST_INTERFACE =DIRECT_INTERFACE_BIT,
PLUGIN_INTERFACE, MATLAB_INTERFACE, LEGACY_PYTHON_INTERFACE, PYTHON_INTERFACE,
SCILAB_INTERFACE, DEFAULT_METHOD =0, HYBRID =(META_BIT | PARALLEL_BIT), PARETO_SET,
MULTI_START, RICHARDSON_EXTRAP =(ANALYZER_BIT | VERIF_BIT), CENTERED_PARAMETER_STUDY =(ANALYZER_BIT | PSTUDYDACE_BIT), LIST_PARAMETER_STUDY,
MULTIDIM_PARAMETER_STUDY, VECTOR_PARAMETER_STUDY, DACE, FSU_CVT,
FSU_HALTON, FSU_HAMMERSLEY, PSUADE_MOAT, LOCAL_RELIABILITY =(ANALYZER_BIT | NOND_BIT),
GLOBAL_RELIABILITY, SURROGATE_BASED_UQ, POLYNOMIAL_CHAOS, MULTILEVEL_POLYNOMIAL_CHAOS,
MULTIFIDELITY_POLYNOMIAL_CHAOS, STOCH_COLLOCATION, MULTIFIDELITY_STOCH_COLLOCATION, C3_FUNCTION_TRAIN,
MULTILEVEL_FUNCTION_TRAIN, MULTIFIDELITY_FUNCTION_TRAIN, CUBATURE_INTEGRATION, SPARSE_GRID_INTEGRATION,
QUADRATURE_INTEGRATION, BAYES_CALIBRATION, GPAIS, POF_DARTS,
RKD_DARTS, IMPORTANCE_SAMPLING, ADAPTIVE_SAMPLING, MULTILEVEL_SAMPLING,
MULTIFIDELITY_SAMPLING, MULTILEVEL_MULTIFIDELITY_SAMPLING, APPROXIMATE_CONTROL_VARIATE, LIST_SAMPLING,
RANDOM_SAMPLING, LOCAL_INTERVAL_EST, LOCAL_EVIDENCE, GLOBAL_INTERVAL_EST,
GLOBAL_EVIDENCE, SURROGATE_BASED_LOCAL =(MINIMIZER_BIT | SURRBASED_BIT), DATA_FIT_SURROGATE_BASED_LOCAL, HIERARCH_SURROGATE_BASED_LOCAL,
SURROGATE_BASED_GLOBAL, EFFICIENT_GLOBAL, NL2SOL =(MINIMIZER_BIT | LEASTSQ_BIT), NLSSOL_SQP,
OPTPP_G_NEWTON, ASYNCH_PATTERN_SEARCH =(MINIMIZER_BIT | OPTIMIZER_BIT), OPTPP_PDS, COLINY_BETA,
COLINY_COBYLA, COLINY_DIRECT, COLINY_MULTI_START, COLINY_EA,
COLINY_PATTERN_SEARCH, COLINY_SOLIS_WETS, MOGA, SOGA,
NCSU_DIRECT, MESH_ADAPTIVE_SEARCH, MIT_NOWPAC, MIT_SNOWPAC,
GENIE_OPT_DARTS, GENIE_DIRECT, DEMO_TPL, NONLINEAR_CG,
OPTPP_CG, OPTPP_Q_NEWTON, OPTPP_FD_NEWTON, OPTPP_NEWTON,
NPSOL_SQP, NLPQL_SQP, DOT_BFGS, DOT_FRCG,
DOT_MMFD, DOT_SLP, DOT_SQP, CONMIN_FRCG,
CONMIN_MFD, ROL, DL_SOLVER, BRANCH_AND_BOUND =(MINIMIZER_BIT | OPTIMIZER_BIT | LEASTSQ_BIT),
DEFAULT_POINTS, MINIMUM_POINTS, RECOMMENDED_POINTS, TOTAL_POINTS,
BASE_RESPONSE =0, SIMULATION_RESPONSE, EXPERIMENT_RESPONSE, DEFAULT_DOMAIN =0,
RELAXED_DOMAIN, MIXED_DOMAIN, DEFAULT_CORRECTION = 0, SINGLE_CORRECTION,
FULL_MODEL_FORM_CORRECTION, FULL_SOLUTION_LEVEL_CORRECTION, SEQUENCE_CORRECTION, SETUP_MODEL,
SETUP_USERFUNC, CAUVar_normal = 0, CAUVar_lognormal = 1, CAUVar_uniform = 2,
CAUVar_loguniform = 3, CAUVar_triangular = 4, CAUVar_exponential = 5, CAUVar_beta = 6,
CAUVar_gamma = 7, CAUVar_gumbel = 8, CAUVar_frechet = 9, CAUVar_weibull = 10,
CAUVar_histogram_bin = 11, CAUVar_Nkinds = 12, ANALYTIC_SOLUTION = 1, REORDERED_ANALYTIC_SOLUTION,
R_ONLY_LINEAR_CONSTRAINT, N_VECTOR_LINEAR_CONSTRAINT, R_AND_N_NONLINEAR_CONSTRAINT, N_VECTOR_LINEAR_OBJECTIVE,
FULL_TENSOR, FILTERED_TENSOR, RANDOM_TENSOR, AS_FUNC =1,
AS_GRAD =2, AS_HESS =4, DISALLOW, TARGET,
BOUNDS, SCALE_NONE = 0, SCALE_VALUE = 1, SCALE_LOG = 2,
SCALE_AUTO = 4, APPROX_RESPONSE =1, TRUTH_RESPONSE, TH_SILENT_OUTPUT,
TH_QUIET_OUTPUT, TH_NORMAL_OUTPUT, TH_VERBOSE_OUTPUT, TH_DEBUG_OUTPUT,
DIR_CLEAN, DIR_PERSIST, DIR_ERROR
}
special values for derived Response type
enum {
MODEL_EVAL_STORE_TOP_METHOD = 0, MODEL_EVAL_STORE_NONE, MODEL_EVAL_STORE_ALL, MODEL_EVAL_STORE_ALL_METHODS,
SYNCHRONOUS_INTERFACE, ASYNCHRONOUS_INTERFACE, SUBMETHOD_DEFAULT =0, SUBMETHOD_NONE,
SUBMETHOD_COLLABORATIVE, SUBMETHOD_EMBEDDED, SUBMETHOD_SEQUENTIAL, SUBMETHOD_LHS,
SUBMETHOD_RANDOM, SUBMETHOD_LOW_DISCREPANCY_SAMPLING, SUBMETHOD_BOX_BEHNKEN, SUBMETHOD_CENTRAL_COMPOSITE,
SUBMETHOD_GRID, SUBMETHOD_OA_LHS, SUBMETHOD_OAS, SUBMETHOD_MFMC,
SUBMETHOD_ACV_IS, SUBMETHOD_ACV_MF, SUBMETHOD_ACV_RD, SUBMETHOD_DREAM,
SUBMETHOD_GPMSA, SUBMETHOD_MUQ, SUBMETHOD_QUESO, SUBMETHOD_WASABI,
SUBMETHOD_CONMIN, SUBMETHOD_DOT, SUBMETHOD_NLPQL, SUBMETHOD_NPSOL,
SUBMETHOD_OPTPP, SUBMETHOD_NPSOL_OPTPP, SUBMETHOD_DIRECT, SUBMETHOD_DIRECT_NPSOL_OPTPP,
SUBMETHOD_DIRECT_NPSOL, SUBMETHOD_DIRECT_OPTPP, SUBMETHOD_EA, SUBMETHOD_EGO,
SUBMETHOD_SBLO, SUBMETHOD_SBGO, SUBMETHOD_AMV_X, SUBMETHOD_AMV_U,
SUBMETHOD_AMV_PLUS_X, SUBMETHOD_AMV_PLUS_U, SUBMETHOD_TANA_X, SUBMETHOD_TANA_U,
SUBMETHOD_QMEA_X, SUBMETHOD_QMEA_U, SUBMETHOD_NO_APPROX, SUBMETHOD_EGRA_X,
SUBMETHOD_EGRA_U, SUBMETHOD_CONVERGE_ORDER, SUBMETHOD_CONVERGE_QOI, SUBMETHOD_ESTIMATE_ORDER,
DEFAULT_SURROGATE_RESP_MODE =0, NO_SURROGATE, UNCORRECTED_SURROGATE, AUTO_CORRECTED_SURROGATE,
BYPASS_SURROGATE, MODEL_DISCREPANCY, AGGREGATED_MODEL_PAIR, AGGREGATED_MODELS,
GENERIC_FNS = 0, OBJECTIVE_FNS, CALIB_TERMS, DEFAULT_VIEW =0,
ALL_VIEW, DESIGN_VIEW, UNCERTAIN_VIEW, ALEATORY_UNCERTAIN_VIEW,
EPISTEMIC_UNCERTAIN_VIEW, STATE_VIEW, DAUIVar_poisson = 0, DAUIVar_binomial = 1,
DAUIVar_negative_binomial = 2, DAUIVar_geometric = 3, DAUIVar_hypergeometric = 4, DAUIVar_histogram_point_int = 5,
DAUIVar_Nkinds = 6, TYPE_U =1, TYPE_B =2, TYPE_E =3,
TYPE_EB =4, CORR_APPROX_RESPONSE =1, UNCORR_APPROX_RESPONSE, CORR_TRUTH_RESPONSE,
UNCORR_TRUTH_RESPONSE, FILEOP_SILENT, FILEOP_WARN, FILEOP_ERROR
}
values for primary response types
enum {
COBYLA, DIRECT, EA, MS,
PS, SW, BETA, VARS_ERROR = -11,
CONS_ERROR = -10, RESP_ERROR = -9, APPROX_ERROR = -8, METHOD_ERROR = -7,
MODEL_ERROR = -6, IO_ERROR = -5, INTERFACE_ERROR = -4, CONSTRUCT_ERROR = -3,
PARSE_ERROR = -2, OTHER_ERROR = -1, DEFAULT_INTERFACE =0, APPROX_INTERFACE,
FORK_INTERFACE =PROCESS_INTERFACE_BIT, SYSTEM_INTERFACE, GRID_INTERFACE, TEST_INTERFACE =DIRECT_INTERFACE_BIT,
PLUGIN_INTERFACE, MATLAB_INTERFACE, LEGACY_PYTHON_INTERFACE, PYTHON_INTERFACE,
SCILAB_INTERFACE, DEFAULT_METHOD =0, HYBRID =(META_BIT | PARALLEL_BIT), PARETO_SET,
MULTI_START, RICHARDSON_EXTRAP =(ANALYZER_BIT | VERIF_BIT), CENTERED_PARAMETER_STUDY =(ANALYZER_BIT | PSTUDYDACE_BIT), LIST_PARAMETER_STUDY,
MULTIDIM_PARAMETER_STUDY, VECTOR_PARAMETER_STUDY, DACE, FSU_CVT,
FSU_HALTON, FSU_HAMMERSLEY, PSUADE_MOAT, LOCAL_RELIABILITY =(ANALYZER_BIT | NOND_BIT),
GLOBAL_RELIABILITY, SURROGATE_BASED_UQ, POLYNOMIAL_CHAOS, MULTILEVEL_POLYNOMIAL_CHAOS,
MULTIFIDELITY_POLYNOMIAL_CHAOS, STOCH_COLLOCATION, MULTIFIDELITY_STOCH_COLLOCATION, C3_FUNCTION_TRAIN,
MULTILEVEL_FUNCTION_TRAIN, MULTIFIDELITY_FUNCTION_TRAIN, CUBATURE_INTEGRATION, SPARSE_GRID_INTEGRATION,
QUADRATURE_INTEGRATION, BAYES_CALIBRATION, GPAIS, POF_DARTS,
RKD_DARTS, IMPORTANCE_SAMPLING, ADAPTIVE_SAMPLING, MULTILEVEL_SAMPLING,
MULTIFIDELITY_SAMPLING, MULTILEVEL_MULTIFIDELITY_SAMPLING, APPROXIMATE_CONTROL_VARIATE, LIST_SAMPLING,
RANDOM_SAMPLING, LOCAL_INTERVAL_EST, LOCAL_EVIDENCE, GLOBAL_INTERVAL_EST,
GLOBAL_EVIDENCE, SURROGATE_BASED_LOCAL =(MINIMIZER_BIT | SURRBASED_BIT), DATA_FIT_SURROGATE_BASED_LOCAL, HIERARCH_SURROGATE_BASED_LOCAL,
SURROGATE_BASED_GLOBAL, EFFICIENT_GLOBAL, NL2SOL =(MINIMIZER_BIT | LEASTSQ_BIT), NLSSOL_SQP,
OPTPP_G_NEWTON, ASYNCH_PATTERN_SEARCH =(MINIMIZER_BIT | OPTIMIZER_BIT), OPTPP_PDS, COLINY_BETA,
COLINY_COBYLA, COLINY_DIRECT, COLINY_MULTI_START, COLINY_EA,
COLINY_PATTERN_SEARCH, COLINY_SOLIS_WETS, MOGA, SOGA,
NCSU_DIRECT, MESH_ADAPTIVE_SEARCH, MIT_NOWPAC, MIT_SNOWPAC,
GENIE_OPT_DARTS, GENIE_DIRECT, DEMO_TPL, NONLINEAR_CG,
OPTPP_CG, OPTPP_Q_NEWTON, OPTPP_FD_NEWTON, OPTPP_NEWTON,
NPSOL_SQP, NLPQL_SQP, DOT_BFGS, DOT_FRCG,
DOT_MMFD, DOT_SLP, DOT_SQP, CONMIN_FRCG,
CONMIN_MFD, ROL, DL_SOLVER, BRANCH_AND_BOUND =(MINIMIZER_BIT | OPTIMIZER_BIT | LEASTSQ_BIT),
DEFAULT_POINTS, MINIMUM_POINTS, RECOMMENDED_POINTS, TOTAL_POINTS,
BASE_RESPONSE =0, SIMULATION_RESPONSE, EXPERIMENT_RESPONSE, DEFAULT_DOMAIN =0,
RELAXED_DOMAIN, MIXED_DOMAIN, DEFAULT_CORRECTION = 0, SINGLE_CORRECTION,
FULL_MODEL_FORM_CORRECTION, FULL_SOLUTION_LEVEL_CORRECTION, SEQUENCE_CORRECTION, SETUP_MODEL,
SETUP_USERFUNC, CAUVar_normal = 0, CAUVar_lognormal = 1, CAUVar_uniform = 2,
CAUVar_loguniform = 3, CAUVar_triangular = 4, CAUVar_exponential = 5, CAUVar_beta = 6,
CAUVar_gamma = 7, CAUVar_gumbel = 8, CAUVar_frechet = 9, CAUVar_weibull = 10,
CAUVar_histogram_bin = 11, CAUVar_Nkinds = 12, ANALYTIC_SOLUTION = 1, REORDERED_ANALYTIC_SOLUTION,
R_ONLY_LINEAR_CONSTRAINT, N_VECTOR_LINEAR_CONSTRAINT, R_AND_N_NONLINEAR_CONSTRAINT, N_VECTOR_LINEAR_OBJECTIVE,
FULL_TENSOR, FILTERED_TENSOR, RANDOM_TENSOR, AS_FUNC =1,
AS_GRAD =2, AS_HESS =4, DISALLOW, TARGET,
BOUNDS, SCALE_NONE = 0, SCALE_VALUE = 1, SCALE_LOG = 2,
SCALE_AUTO = 4, APPROX_RESPONSE =1, TRUTH_RESPONSE, TH_SILENT_OUTPUT,
TH_QUIET_OUTPUT, TH_NORMAL_OUTPUT, TH_VERBOSE_OUTPUT, TH_DEBUG_OUTPUT,
DIR_CLEAN, DIR_PERSIST, DIR_ERROR
}
enum {
MODEL_EVAL_STORE_TOP_METHOD = 0, MODEL_EVAL_STORE_NONE, MODEL_EVAL_STORE_ALL, MODEL_EVAL_STORE_ALL_METHODS,
SYNCHRONOUS_INTERFACE, ASYNCHRONOUS_INTERFACE, SUBMETHOD_DEFAULT =0, SUBMETHOD_NONE,
SUBMETHOD_COLLABORATIVE, SUBMETHOD_EMBEDDED, SUBMETHOD_SEQUENTIAL, SUBMETHOD_LHS,
SUBMETHOD_RANDOM, SUBMETHOD_LOW_DISCREPANCY_SAMPLING, SUBMETHOD_BOX_BEHNKEN, SUBMETHOD_CENTRAL_COMPOSITE,
SUBMETHOD_GRID, SUBMETHOD_OA_LHS, SUBMETHOD_OAS, SUBMETHOD_MFMC,
SUBMETHOD_ACV_IS, SUBMETHOD_ACV_MF, SUBMETHOD_ACV_RD, SUBMETHOD_DREAM,
SUBMETHOD_GPMSA, SUBMETHOD_MUQ, SUBMETHOD_QUESO, SUBMETHOD_WASABI,
SUBMETHOD_CONMIN, SUBMETHOD_DOT, SUBMETHOD_NLPQL, SUBMETHOD_NPSOL,
SUBMETHOD_OPTPP, SUBMETHOD_NPSOL_OPTPP, SUBMETHOD_DIRECT, SUBMETHOD_DIRECT_NPSOL_OPTPP,
SUBMETHOD_DIRECT_NPSOL, SUBMETHOD_DIRECT_OPTPP, SUBMETHOD_EA, SUBMETHOD_EGO,
SUBMETHOD_SBLO, SUBMETHOD_SBGO, SUBMETHOD_AMV_X, SUBMETHOD_AMV_U,
SUBMETHOD_AMV_PLUS_X, SUBMETHOD_AMV_PLUS_U, SUBMETHOD_TANA_X, SUBMETHOD_TANA_U,
SUBMETHOD_QMEA_X, SUBMETHOD_QMEA_U, SUBMETHOD_NO_APPROX, SUBMETHOD_EGRA_X,
SUBMETHOD_EGRA_U, SUBMETHOD_CONVERGE_ORDER, SUBMETHOD_CONVERGE_QOI, SUBMETHOD_ESTIMATE_ORDER,
DEFAULT_SURROGATE_RESP_MODE =0, NO_SURROGATE, UNCORRECTED_SURROGATE, AUTO_CORRECTED_SURROGATE,
BYPASS_SURROGATE, MODEL_DISCREPANCY, AGGREGATED_MODEL_PAIR, AGGREGATED_MODELS,
GENERIC_FNS = 0, OBJECTIVE_FNS, CALIB_TERMS, DEFAULT_VIEW =0,
ALL_VIEW, DESIGN_VIEW, UNCERTAIN_VIEW, ALEATORY_UNCERTAIN_VIEW,
EPISTEMIC_UNCERTAIN_VIEW, STATE_VIEW, DAUIVar_poisson = 0, DAUIVar_binomial = 1,
DAUIVar_negative_binomial = 2, DAUIVar_geometric = 3, DAUIVar_hypergeometric = 4, DAUIVar_histogram_point_int = 5,
DAUIVar_Nkinds = 6, TYPE_U =1, TYPE_B =2, TYPE_E =3,
TYPE_EB =4, CORR_APPROX_RESPONSE =1, UNCORR_APPROX_RESPONSE, CORR_TRUTH_RESPONSE,
UNCORR_TRUTH_RESPONSE, FILEOP_SILENT, FILEOP_WARN, FILEOP_ERROR
}
enum {
INTERF_EVAL_STORE_SIMULATION = 0, INTERF_EVAL_STORE_NONE, INTERF_EVAL_STORE_ALL, OBJECTIVE,
INEQUALITY_CONSTRAINT, EQUALITY_CONSTRAINT, VBD_BINNED =0, VBD_PICK_AND_FREEZE,
NO_CORRECTION =0, ADDITIVE_CORRECTION, MULTIPLICATIVE_CORRECTION, COMBINED_CORRECTION,
EMPTY_VIEW =0, RELAXED_ALL, MIXED_ALL, RELAXED_DESIGN,
RELAXED_UNCERTAIN, RELAXED_ALEATORY_UNCERTAIN, RELAXED_EPISTEMIC_UNCERTAIN, RELAXED_STATE,
MIXED_DESIGN, MIXED_UNCERTAIN, MIXED_ALEATORY_UNCERTAIN, MIXED_EPISTEMIC_UNCERTAIN,
MIXED_STATE, DAUSVar_histogram_point_str = 0, DAUSVar_Nkinds = 1, NEW_CANDIDATE = 1,
CANDIDATE_ACCEPTED = 2, CANDIDATE_STATE = (NEW_CANDIDATE | CANDIDATE_ACCEPTED), NEW_CENTER = 8, CENTER_BUILT = 16,
CENTER_STATE = (NEW_CENTER | CENTER_BUILT), NEW_TR_FACTOR = 64, NEW_TRUST_REGION = (NEW_CENTER | NEW_TR_FACTOR), HARD_CONVERGED = 128,
SOFT_CONVERGED = 256, MIN_TR_CONVERGED = 512, MAX_ITER_CONVERGED = 1024, CONVERGED
}
enum {
ABORT_EXITS, ABORT_THROWS, NO_GRAPH_RECURSION =0, KL_GRAPH_RECURSION,
PARTIAL_GRAPH_RECURSION, FULL_GRAPH_RECURSION, RF_KARHUNEN_LOEVE =0, RF_PCA_GP,
RF_ICA, ALL_VARS =0, ACTIVE_VARS, INACTIVE_VARS,
DAURVar_histogram_point_real = 0, DAURVar_Nkinds = 1
}
values differentiating subsets of variables for I/O
enum {
CV_ID_DEFAULT = 0, MINIMUM_METRIC, RELATIVE_TOLERANCE, DECREASE_TOLERANCE,
NO_MODEL_SELECTION =0, ALL_MODEL_COMBINATIONS, NOCOVAR =0, EXP_L2,
EXP_L1, EMPTY_TYPE =0, CONTINUOUS_DESIGN, DISCRETE_DESIGN_RANGE,
DISCRETE_DESIGN_SET_INT, DISCRETE_DESIGN_SET_STRING, DISCRETE_DESIGN_SET_REAL, NORMAL_UNCERTAIN,
LOGNORMAL_UNCERTAIN, UNIFORM_UNCERTAIN, LOGUNIFORM_UNCERTAIN, TRIANGULAR_UNCERTAIN,
EXPONENTIAL_UNCERTAIN, BETA_UNCERTAIN, GAMMA_UNCERTAIN, GUMBEL_UNCERTAIN,
FRECHET_UNCERTAIN, WEIBULL_UNCERTAIN, HISTOGRAM_BIN_UNCERTAIN, POISSON_UNCERTAIN,
BINOMIAL_UNCERTAIN, NEGATIVE_BINOMIAL_UNCERTAIN, GEOMETRIC_UNCERTAIN, HYPERGEOMETRIC_UNCERTAIN,
HISTOGRAM_POINT_UNCERTAIN_INT, HISTOGRAM_POINT_UNCERTAIN_STRING, HISTOGRAM_POINT_UNCERTAIN_REAL, CONTINUOUS_INTERVAL_UNCERTAIN,
DISCRETE_INTERVAL_UNCERTAIN, DISCRETE_UNCERTAIN_SET_INT, DISCRETE_UNCERTAIN_SET_STRING, DISCRETE_UNCERTAIN_SET_REAL,
CONTINUOUS_STATE, DISCRETE_STATE_RANGE, DISCRETE_STATE_SET_INT, DISCRETE_STATE_SET_STRING,
DISCRETE_STATE_SET_REAL, CEUVar_interval = 0, CEUVar_Nkinds = 1
}
enum {
TABULAR_NONE = 0, TABULAR_HEADER = 1, TABULAR_EVAL_ID = 2, TABULAR_IFACE_ID = 4,
TABULAR_EXPER_ANNOT = TABULAR_HEADER | TABULAR_EVAL_ID, TABULAR_ANNOTATED = TABULAR_HEADER | TABULAR_EVAL_ID | TABULAR_IFACE_ID, SILENT_OUTPUT, QUIET_OUTPUT,
NORMAL_OUTPUT, VERBOSE_OUTPUT, DEBUG_OUTPUT, SUBSPACE_NORM_DEFAULT =0,
SUBSPACE_NORM_MEAN_VALUE, SUBSPACE_NORM_MEAN_GRAD, SUBSPACE_NORM_LOCAL_GRAD, TOTAL_CDV =0,
TOTAL_DDIV, TOTAL_DDSV, TOTAL_DDRV, TOTAL_CAUV,
TOTAL_DAUIV, TOTAL_DAUSV, TOTAL_DAURV, TOTAL_CEUV,
TOTAL_DEUIV, TOTAL_DEUSV, TOTAL_DEURV, TOTAL_CSV,
TOTAL_DSIV, TOTAL_DSSV, TOTAL_DSRV, NUM_VC_TOTALS,
DEUIVar_interval = 0, DEUIVar_set_int = 1, DEUIVar_Nkinds = 2
}
enum DigitalNetOrdering { DIGITAL_NET_NATURAL_ORDERING, DIGITAL_NET_GRAY_CODE_ORDERING }
Enum for digital net ordering.
enum var_t {
VAR_x1, VAR_x2, VAR_x3, VAR_b,
VAR_h, VAR_P, VAR_M, VAR_Y,
VAR_w, VAR_t, VAR_R, VAR_E,
VAR_X, VAR_area_type, VAR_Fs, VAR_P1,
VAR_P2, VAR_P3, VAR_B, VAR_D,
VAR_H, VAR_F0, VAR_d, VAR_MForm,
VAR_x, VAR_xi, VAR_Af, VAR_Ac,
VAR_y, VAR_theta, VAR_theta1, VAR_theta2,
VAR_delta, VAR_gamma
}
enumeration of possible variable types (to index to names)
enum driver_t {
NO_DRIVER =0, CANTILEVER_BEAM, MOD_CANTILEVER_BEAM, CANTILEVER_BEAM_ML,
CYLINDER_HEAD, EXTENDED_ROSENBROCK, GENERALIZED_ROSENBROCK, LF_ROSENBROCK,
EXTRA_LF_ROSENBROCK, MF_ROSENBROCK, MODIFIED_ROSENBROCK, ROSENBROCK,
LF_POLY_PROD, POLY_PROD, GERSTNER, SCALABLE_GERSTNER,
LOGNORMAL_RATIO, MULTIMODAL, PLUGIN_ROSENBROCK, PLUGIN_TEXT_BOOK,
SHORT_COLUMN, LF_SHORT_COLUMN, MF_SHORT_COLUMN, SIDE_IMPACT_COST,
SIDE_IMPACT_PERFORMANCE, SOBOL_RATIONAL, SOBOL_G_FUNCTION, SOBOL_ISHIGAMI,
STEEL_COLUMN_COST, STEEL_COLUMN_PERFORMANCE, TEXT_BOOK, TEXT_BOOK1,
TEXT_BOOK2, TEXT_BOOK3, TEXT_BOOK_OUU, SCALABLE_TEXT_BOOK,
SCALABLE_MONOMIALS, MOGATEST1, MOGATEST2, MOGATEST3,
ILLUMINATION, BARNES, BARNES_LF, HERBIE,
SMOOTH_HERBIE, SHUBERT, SALINAS, MODELCENTER,
GENZ, DAMPED_OSCILLATOR, ANISOTROPIC_QUADRATIC_FORM, BAYES_LINEAR,
STEADY_STATE_DIFFUSION_1D, SS_DIFFUSION_DISCREPANCY, TRANSIENT_DIFFUSION_1D, PREDATOR_PREY,
PROBLEM18, TUNABLE_MODEL
}
enumeration of possible direct driver types (to index to names)
enum local_data_t { VARIABLES_MAP =1, VARIABLES_VECTOR =2 }
enumeration for how local variables are stored (values must employ a bit representation)
enum {
COBYLA, DIRECT, EA, MS,
PS, SW, BETA, VARS_ERROR = -11,
CONS_ERROR = -10, RESP_ERROR = -9, APPROX_ERROR = -8, METHOD_ERROR = -7,
MODEL_ERROR = -6, IO_ERROR = -5, INTERFACE_ERROR = -4, CONSTRUCT_ERROR = -3,
PARSE_ERROR = -2, OTHER_ERROR = -1, DEFAULT_INTERFACE =0, APPROX_INTERFACE,
FORK_INTERFACE =PROCESS_INTERFACE_BIT, SYSTEM_INTERFACE, GRID_INTERFACE, TEST_INTERFACE =DIRECT_INTERFACE_BIT,
PLUGIN_INTERFACE, MATLAB_INTERFACE, LEGACY_PYTHON_INTERFACE, PYTHON_INTERFACE,
SCILAB_INTERFACE, DEFAULT_METHOD =0, HYBRID =(META_BIT | PARALLEL_BIT), PARETO_SET,
MULTI_START, RICHARDSON_EXTRAP =(ANALYZER_BIT | VERIF_BIT), CENTERED_PARAMETER_STUDY =(ANALYZER_BIT | PSTUDYDACE_BIT), LIST_PARAMETER_STUDY,
MULTIDIM_PARAMETER_STUDY, VECTOR_PARAMETER_STUDY, DACE, FSU_CVT,
FSU_HALTON, FSU_HAMMERSLEY, PSUADE_MOAT, LOCAL_RELIABILITY =(ANALYZER_BIT | NOND_BIT),
GLOBAL_RELIABILITY, SURROGATE_BASED_UQ, POLYNOMIAL_CHAOS, MULTILEVEL_POLYNOMIAL_CHAOS,
MULTIFIDELITY_POLYNOMIAL_CHAOS, STOCH_COLLOCATION, MULTIFIDELITY_STOCH_COLLOCATION, C3_FUNCTION_TRAIN,
MULTILEVEL_FUNCTION_TRAIN, MULTIFIDELITY_FUNCTION_TRAIN, CUBATURE_INTEGRATION, SPARSE_GRID_INTEGRATION,
QUADRATURE_INTEGRATION, BAYES_CALIBRATION, GPAIS, POF_DARTS,
RKD_DARTS, IMPORTANCE_SAMPLING, ADAPTIVE_SAMPLING, MULTILEVEL_SAMPLING,
MULTIFIDELITY_SAMPLING, MULTILEVEL_MULTIFIDELITY_SAMPLING, APPROXIMATE_CONTROL_VARIATE, LIST_SAMPLING,
RANDOM_SAMPLING, LOCAL_INTERVAL_EST, LOCAL_EVIDENCE, GLOBAL_INTERVAL_EST,
GLOBAL_EVIDENCE, SURROGATE_BASED_LOCAL =(MINIMIZER_BIT | SURRBASED_BIT), DATA_FIT_SURROGATE_BASED_LOCAL, HIERARCH_SURROGATE_BASED_LOCAL,
SURROGATE_BASED_GLOBAL, EFFICIENT_GLOBAL, NL2SOL =(MINIMIZER_BIT | LEASTSQ_BIT), NLSSOL_SQP,
OPTPP_G_NEWTON, ASYNCH_PATTERN_SEARCH =(MINIMIZER_BIT | OPTIMIZER_BIT), OPTPP_PDS, COLINY_BETA,
COLINY_COBYLA, COLINY_DIRECT, COLINY_MULTI_START, COLINY_EA,
COLINY_PATTERN_SEARCH, COLINY_SOLIS_WETS, MOGA, SOGA,
NCSU_DIRECT, MESH_ADAPTIVE_SEARCH, MIT_NOWPAC, MIT_SNOWPAC,
GENIE_OPT_DARTS, GENIE_DIRECT, DEMO_TPL, NONLINEAR_CG,
OPTPP_CG, OPTPP_Q_NEWTON, OPTPP_FD_NEWTON, OPTPP_NEWTON,
NPSOL_SQP, NLPQL_SQP, DOT_BFGS, DOT_FRCG,
DOT_MMFD, DOT_SLP, DOT_SQP, CONMIN_FRCG,
CONMIN_MFD, ROL, DL_SOLVER, BRANCH_AND_BOUND =(MINIMIZER_BIT | OPTIMIZER_BIT | LEASTSQ_BIT),
DEFAULT_POINTS, MINIMUM_POINTS, RECOMMENDED_POINTS, TOTAL_POINTS,
BASE_RESPONSE =0, SIMULATION_RESPONSE, EXPERIMENT_RESPONSE, DEFAULT_DOMAIN =0,
RELAXED_DOMAIN, MIXED_DOMAIN, DEFAULT_CORRECTION = 0, SINGLE_CORRECTION,
FULL_MODEL_FORM_CORRECTION, FULL_SOLUTION_LEVEL_CORRECTION, SEQUENCE_CORRECTION, SETUP_MODEL,
SETUP_USERFUNC, CAUVar_normal = 0, CAUVar_lognormal = 1, CAUVar_uniform = 2,
CAUVar_loguniform = 3, CAUVar_triangular = 4, CAUVar_exponential = 5, CAUVar_beta = 6,
CAUVar_gamma = 7, CAUVar_gumbel = 8, CAUVar_frechet = 9, CAUVar_weibull = 10,
CAUVar_histogram_bin = 11, CAUVar_Nkinds = 12, ANALYTIC_SOLUTION = 1, REORDERED_ANALYTIC_SOLUTION,
R_ONLY_LINEAR_CONSTRAINT, N_VECTOR_LINEAR_CONSTRAINT, R_AND_N_NONLINEAR_CONSTRAINT, N_VECTOR_LINEAR_OBJECTIVE,
FULL_TENSOR, FILTERED_TENSOR, RANDOM_TENSOR, AS_FUNC =1,
AS_GRAD =2, AS_HESS =4, DISALLOW, TARGET,
BOUNDS, SCALE_NONE = 0, SCALE_VALUE = 1, SCALE_LOG = 2,
SCALE_AUTO = 4, APPROX_RESPONSE =1, TRUTH_RESPONSE, TH_SILENT_OUTPUT,
TH_QUIET_OUTPUT, TH_NORMAL_OUTPUT, TH_VERBOSE_OUTPUT, TH_DEBUG_OUTPUT,
DIR_CLEAN, DIR_PERSIST, DIR_ERROR
}
enum sigtype { NO_SIGMA, SCALAR_SIGMA, DIAGONAL_SIGMA, MATRIX_SIGMA }
special values for sigmaType
enum edtype { SCALAR_DATA, FUNCTIONAL_DATA }
special values for experimental data type
enum {
COBYLA, DIRECT, EA, MS,
PS, SW, BETA, VARS_ERROR = -11,
CONS_ERROR = -10, RESP_ERROR = -9, APPROX_ERROR = -8, METHOD_ERROR = -7,
MODEL_ERROR = -6, IO_ERROR = -5, INTERFACE_ERROR = -4, CONSTRUCT_ERROR = -3,
PARSE_ERROR = -2, OTHER_ERROR = -1, DEFAULT_INTERFACE =0, APPROX_INTERFACE,
FORK_INTERFACE =PROCESS_INTERFACE_BIT, SYSTEM_INTERFACE, GRID_INTERFACE, TEST_INTERFACE =DIRECT_INTERFACE_BIT,
PLUGIN_INTERFACE, MATLAB_INTERFACE, LEGACY_PYTHON_INTERFACE, PYTHON_INTERFACE,
SCILAB_INTERFACE, DEFAULT_METHOD =0, HYBRID =(META_BIT | PARALLEL_BIT), PARETO_SET,
MULTI_START, RICHARDSON_EXTRAP =(ANALYZER_BIT | VERIF_BIT), CENTERED_PARAMETER_STUDY =(ANALYZER_BIT | PSTUDYDACE_BIT), LIST_PARAMETER_STUDY,
MULTIDIM_PARAMETER_STUDY, VECTOR_PARAMETER_STUDY, DACE, FSU_CVT,
FSU_HALTON, FSU_HAMMERSLEY, PSUADE_MOAT, LOCAL_RELIABILITY =(ANALYZER_BIT | NOND_BIT),
GLOBAL_RELIABILITY, SURROGATE_BASED_UQ, POLYNOMIAL_CHAOS, MULTILEVEL_POLYNOMIAL_CHAOS,
MULTIFIDELITY_POLYNOMIAL_CHAOS, STOCH_COLLOCATION, MULTIFIDELITY_STOCH_COLLOCATION, C3_FUNCTION_TRAIN,
MULTILEVEL_FUNCTION_TRAIN, MULTIFIDELITY_FUNCTION_TRAIN, CUBATURE_INTEGRATION, SPARSE_GRID_INTEGRATION,
QUADRATURE_INTEGRATION, BAYES_CALIBRATION, GPAIS, POF_DARTS,
RKD_DARTS, IMPORTANCE_SAMPLING, ADAPTIVE_SAMPLING, MULTILEVEL_SAMPLING,
MULTIFIDELITY_SAMPLING, MULTILEVEL_MULTIFIDELITY_SAMPLING, APPROXIMATE_CONTROL_VARIATE, LIST_SAMPLING,
RANDOM_SAMPLING, LOCAL_INTERVAL_EST, LOCAL_EVIDENCE, GLOBAL_INTERVAL_EST,
GLOBAL_EVIDENCE, SURROGATE_BASED_LOCAL =(MINIMIZER_BIT | SURRBASED_BIT), DATA_FIT_SURROGATE_BASED_LOCAL, HIERARCH_SURROGATE_BASED_LOCAL,
SURROGATE_BASED_GLOBAL, EFFICIENT_GLOBAL, NL2SOL =(MINIMIZER_BIT | LEASTSQ_BIT), NLSSOL_SQP,
OPTPP_G_NEWTON, ASYNCH_PATTERN_SEARCH =(MINIMIZER_BIT | OPTIMIZER_BIT), OPTPP_PDS, COLINY_BETA,
COLINY_COBYLA, COLINY_DIRECT, COLINY_MULTI_START, COLINY_EA,
COLINY_PATTERN_SEARCH, COLINY_SOLIS_WETS, MOGA, SOGA,
NCSU_DIRECT, MESH_ADAPTIVE_SEARCH, MIT_NOWPAC, MIT_SNOWPAC,
GENIE_OPT_DARTS, GENIE_DIRECT, DEMO_TPL, NONLINEAR_CG,
OPTPP_CG, OPTPP_Q_NEWTON, OPTPP_FD_NEWTON, OPTPP_NEWTON,
NPSOL_SQP, NLPQL_SQP, DOT_BFGS, DOT_FRCG,
DOT_MMFD, DOT_SLP, DOT_SQP, CONMIN_FRCG,
CONMIN_MFD, ROL, DL_SOLVER, BRANCH_AND_BOUND =(MINIMIZER_BIT | OPTIMIZER_BIT | LEASTSQ_BIT),
DEFAULT_POINTS, MINIMUM_POINTS, RECOMMENDED_POINTS, TOTAL_POINTS,
BASE_RESPONSE =0, SIMULATION_RESPONSE, EXPERIMENT_RESPONSE, DEFAULT_DOMAIN =0,
RELAXED_DOMAIN, MIXED_DOMAIN, DEFAULT_CORRECTION = 0, SINGLE_CORRECTION,
FULL_MODEL_FORM_CORRECTION, FULL_SOLUTION_LEVEL_CORRECTION, SEQUENCE_CORRECTION, SETUP_MODEL,
SETUP_USERFUNC, CAUVar_normal = 0, CAUVar_lognormal = 1, CAUVar_uniform = 2,
CAUVar_loguniform = 3, CAUVar_triangular = 4, CAUVar_exponential = 5, CAUVar_beta = 6,
CAUVar_gamma = 7, CAUVar_gumbel = 8, CAUVar_frechet = 9, CAUVar_weibull = 10,
CAUVar_histogram_bin = 11, CAUVar_Nkinds = 12, ANALYTIC_SOLUTION = 1, REORDERED_ANALYTIC_SOLUTION,
R_ONLY_LINEAR_CONSTRAINT, N_VECTOR_LINEAR_CONSTRAINT, R_AND_N_NONLINEAR_CONSTRAINT, N_VECTOR_LINEAR_OBJECTIVE,
FULL_TENSOR, FILTERED_TENSOR, RANDOM_TENSOR, AS_FUNC =1,
AS_GRAD =2, AS_HESS =4, DISALLOW, TARGET,
BOUNDS, SCALE_NONE = 0, SCALE_VALUE = 1, SCALE_LOG = 2,
SCALE_AUTO = 4, APPROX_RESPONSE =1, TRUTH_RESPONSE, TH_SILENT_OUTPUT,
TH_QUIET_OUTPUT, TH_NORMAL_OUTPUT, TH_VERBOSE_OUTPUT, TH_DEBUG_OUTPUT,
DIR_CLEAN, DIR_PERSIST, DIR_ERROR
}
enum {
COBYLA, DIRECT, EA, MS,
PS, SW, BETA, VARS_ERROR = -11,
CONS_ERROR = -10, RESP_ERROR = -9, APPROX_ERROR = -8, METHOD_ERROR = -7,
MODEL_ERROR = -6, IO_ERROR = -5, INTERFACE_ERROR = -4, CONSTRUCT_ERROR = -3,
PARSE_ERROR = -2, OTHER_ERROR = -1, DEFAULT_INTERFACE =0, APPROX_INTERFACE,
FORK_INTERFACE =PROCESS_INTERFACE_BIT, SYSTEM_INTERFACE, GRID_INTERFACE, TEST_INTERFACE =DIRECT_INTERFACE_BIT,
PLUGIN_INTERFACE, MATLAB_INTERFACE, LEGACY_PYTHON_INTERFACE, PYTHON_INTERFACE,
SCILAB_INTERFACE, DEFAULT_METHOD =0, HYBRID =(META_BIT | PARALLEL_BIT), PARETO_SET,
MULTI_START, RICHARDSON_EXTRAP =(ANALYZER_BIT | VERIF_BIT), CENTERED_PARAMETER_STUDY =(ANALYZER_BIT | PSTUDYDACE_BIT), LIST_PARAMETER_STUDY,
MULTIDIM_PARAMETER_STUDY, VECTOR_PARAMETER_STUDY, DACE, FSU_CVT,
FSU_HALTON, FSU_HAMMERSLEY, PSUADE_MOAT, LOCAL_RELIABILITY =(ANALYZER_BIT | NOND_BIT),
GLOBAL_RELIABILITY, SURROGATE_BASED_UQ, POLYNOMIAL_CHAOS, MULTILEVEL_POLYNOMIAL_CHAOS,
MULTIFIDELITY_POLYNOMIAL_CHAOS, STOCH_COLLOCATION, MULTIFIDELITY_STOCH_COLLOCATION, C3_FUNCTION_TRAIN,
MULTILEVEL_FUNCTION_TRAIN, MULTIFIDELITY_FUNCTION_TRAIN, CUBATURE_INTEGRATION, SPARSE_GRID_INTEGRATION,
QUADRATURE_INTEGRATION, BAYES_CALIBRATION, GPAIS, POF_DARTS,
RKD_DARTS, IMPORTANCE_SAMPLING, ADAPTIVE_SAMPLING, MULTILEVEL_SAMPLING,
MULTIFIDELITY_SAMPLING, MULTILEVEL_MULTIFIDELITY_SAMPLING, APPROXIMATE_CONTROL_VARIATE, LIST_SAMPLING,
RANDOM_SAMPLING, LOCAL_INTERVAL_EST, LOCAL_EVIDENCE, GLOBAL_INTERVAL_EST,
GLOBAL_EVIDENCE, SURROGATE_BASED_LOCAL =(MINIMIZER_BIT | SURRBASED_BIT), DATA_FIT_SURROGATE_BASED_LOCAL, HIERARCH_SURROGATE_BASED_LOCAL,
SURROGATE_BASED_GLOBAL, EFFICIENT_GLOBAL, NL2SOL =(MINIMIZER_BIT | LEASTSQ_BIT), NLSSOL_SQP,
OPTPP_G_NEWTON, ASYNCH_PATTERN_SEARCH =(MINIMIZER_BIT | OPTIMIZER_BIT), OPTPP_PDS, COLINY_BETA,
COLINY_COBYLA, COLINY_DIRECT, COLINY_MULTI_START, COLINY_EA,
COLINY_PATTERN_SEARCH, COLINY_SOLIS_WETS, MOGA, SOGA,
NCSU_DIRECT, MESH_ADAPTIVE_SEARCH, MIT_NOWPAC, MIT_SNOWPAC,
GENIE_OPT_DARTS, GENIE_DIRECT, DEMO_TPL, NONLINEAR_CG,
OPTPP_CG, OPTPP_Q_NEWTON, OPTPP_FD_NEWTON, OPTPP_NEWTON,
NPSOL_SQP, NLPQL_SQP, DOT_BFGS, DOT_FRCG,
DOT_MMFD, DOT_SLP, DOT_SQP, CONMIN_FRCG,
CONMIN_MFD, ROL, DL_SOLVER, BRANCH_AND_BOUND =(MINIMIZER_BIT | OPTIMIZER_BIT | LEASTSQ_BIT),
DEFAULT_POINTS, MINIMUM_POINTS, RECOMMENDED_POINTS, TOTAL_POINTS,
BASE_RESPONSE =0, SIMULATION_RESPONSE, EXPERIMENT_RESPONSE, DEFAULT_DOMAIN =0,
RELAXED_DOMAIN, MIXED_DOMAIN, DEFAULT_CORRECTION = 0, SINGLE_CORRECTION,
FULL_MODEL_FORM_CORRECTION, FULL_SOLUTION_LEVEL_CORRECTION, SEQUENCE_CORRECTION, SETUP_MODEL,
SETUP_USERFUNC, CAUVar_normal = 0, CAUVar_lognormal = 1, CAUVar_uniform = 2,
CAUVar_loguniform = 3, CAUVar_triangular = 4, CAUVar_exponential = 5, CAUVar_beta = 6,
CAUVar_gamma = 7, CAUVar_gumbel = 8, CAUVar_frechet = 9, CAUVar_weibull = 10,
CAUVar_histogram_bin = 11, CAUVar_Nkinds = 12, ANALYTIC_SOLUTION = 1, REORDERED_ANALYTIC_SOLUTION,
R_ONLY_LINEAR_CONSTRAINT, N_VECTOR_LINEAR_CONSTRAINT, R_AND_N_NONLINEAR_CONSTRAINT, N_VECTOR_LINEAR_OBJECTIVE,
FULL_TENSOR, FILTERED_TENSOR, RANDOM_TENSOR, AS_FUNC =1,
AS_GRAD =2, AS_HESS =4, DISALLOW, TARGET,
BOUNDS, SCALE_NONE = 0, SCALE_VALUE = 1, SCALE_LOG = 2,
SCALE_AUTO = 4, APPROX_RESPONSE =1, TRUTH_RESPONSE, TH_SILENT_OUTPUT,
TH_QUIET_OUTPUT, TH_NORMAL_OUTPUT, TH_VERBOSE_OUTPUT, TH_DEBUG_OUTPUT,
DIR_CLEAN, DIR_PERSIST, DIR_ERROR
}
enum {
MODEL_EVAL_STORE_TOP_METHOD = 0, MODEL_EVAL_STORE_NONE, MODEL_EVAL_STORE_ALL, MODEL_EVAL_STORE_ALL_METHODS,
SYNCHRONOUS_INTERFACE, ASYNCHRONOUS_INTERFACE, SUBMETHOD_DEFAULT =0, SUBMETHOD_NONE,
SUBMETHOD_COLLABORATIVE, SUBMETHOD_EMBEDDED, SUBMETHOD_SEQUENTIAL, SUBMETHOD_LHS,
SUBMETHOD_RANDOM, SUBMETHOD_LOW_DISCREPANCY_SAMPLING, SUBMETHOD_BOX_BEHNKEN, SUBMETHOD_CENTRAL_COMPOSITE,
SUBMETHOD_GRID, SUBMETHOD_OA_LHS, SUBMETHOD_OAS, SUBMETHOD_MFMC,
SUBMETHOD_ACV_IS, SUBMETHOD_ACV_MF, SUBMETHOD_ACV_RD, SUBMETHOD_DREAM,
SUBMETHOD_GPMSA, SUBMETHOD_MUQ, SUBMETHOD_QUESO, SUBMETHOD_WASABI,
SUBMETHOD_CONMIN, SUBMETHOD_DOT, SUBMETHOD_NLPQL, SUBMETHOD_NPSOL,
SUBMETHOD_OPTPP, SUBMETHOD_NPSOL_OPTPP, SUBMETHOD_DIRECT, SUBMETHOD_DIRECT_NPSOL_OPTPP,
SUBMETHOD_DIRECT_NPSOL, SUBMETHOD_DIRECT_OPTPP, SUBMETHOD_EA, SUBMETHOD_EGO,
SUBMETHOD_SBLO, SUBMETHOD_SBGO, SUBMETHOD_AMV_X, SUBMETHOD_AMV_U,
SUBMETHOD_AMV_PLUS_X, SUBMETHOD_AMV_PLUS_U, SUBMETHOD_TANA_X, SUBMETHOD_TANA_U,
SUBMETHOD_QMEA_X, SUBMETHOD_QMEA_U, SUBMETHOD_NO_APPROX, SUBMETHOD_EGRA_X,
SUBMETHOD_EGRA_U, SUBMETHOD_CONVERGE_ORDER, SUBMETHOD_CONVERGE_QOI, SUBMETHOD_ESTIMATE_ORDER,
DEFAULT_SURROGATE_RESP_MODE =0, NO_SURROGATE, UNCORRECTED_SURROGATE, AUTO_CORRECTED_SURROGATE,
BYPASS_SURROGATE, MODEL_DISCREPANCY, AGGREGATED_MODEL_PAIR, AGGREGATED_MODELS,
GENERIC_FNS = 0, OBJECTIVE_FNS, CALIB_TERMS, DEFAULT_VIEW =0,
ALL_VIEW, DESIGN_VIEW, UNCERTAIN_VIEW, ALEATORY_UNCERTAIN_VIEW,
EPISTEMIC_UNCERTAIN_VIEW, STATE_VIEW, DAUIVar_poisson = 0, DAUIVar_binomial = 1,
DAUIVar_negative_binomial = 2, DAUIVar_geometric = 3, DAUIVar_hypergeometric = 4, DAUIVar_histogram_point_int = 5,
DAUIVar_Nkinds = 6, TYPE_U =1, TYPE_B =2, TYPE_E =3,
TYPE_EB =4, CORR_APPROX_RESPONSE =1, UNCORR_APPROX_RESPONSE, CORR_TRUTH_RESPONSE,
UNCORR_TRUTH_RESPONSE, FILEOP_SILENT, FILEOP_WARN, FILEOP_ERROR
}
enum {
INTERF_EVAL_STORE_SIMULATION = 0, INTERF_EVAL_STORE_NONE, INTERF_EVAL_STORE_ALL, OBJECTIVE,
INEQUALITY_CONSTRAINT, EQUALITY_CONSTRAINT, VBD_BINNED =0, VBD_PICK_AND_FREEZE,
NO_CORRECTION =0, ADDITIVE_CORRECTION, MULTIPLICATIVE_CORRECTION, COMBINED_CORRECTION,
EMPTY_VIEW =0, RELAXED_ALL, MIXED_ALL, RELAXED_DESIGN,
RELAXED_UNCERTAIN, RELAXED_ALEATORY_UNCERTAIN, RELAXED_EPISTEMIC_UNCERTAIN, RELAXED_STATE,
MIXED_DESIGN, MIXED_UNCERTAIN, MIXED_ALEATORY_UNCERTAIN, MIXED_EPISTEMIC_UNCERTAIN,
MIXED_STATE, DAUSVar_histogram_point_str = 0, DAUSVar_Nkinds = 1, NEW_CANDIDATE = 1,
CANDIDATE_ACCEPTED = 2, CANDIDATE_STATE = (NEW_CANDIDATE | CANDIDATE_ACCEPTED), NEW_CENTER = 8, CENTER_BUILT = 16,
CENTER_STATE = (NEW_CENTER | CENTER_BUILT), NEW_TR_FACTOR = 64, NEW_TRUST_REGION = (NEW_CENTER | NEW_TR_FACTOR), HARD_CONVERGED = 128,
SOFT_CONVERGED = 256, MIN_TR_CONVERGED = 512, MAX_ITER_CONVERGED = 1024, CONVERGED
}
enum {
ABORT_EXITS, ABORT_THROWS, NO_GRAPH_RECURSION =0, KL_GRAPH_RECURSION,
PARTIAL_GRAPH_RECURSION, FULL_GRAPH_RECURSION, RF_KARHUNEN_LOEVE =0, RF_PCA_GP,
RF_ICA, ALL_VARS =0, ACTIVE_VARS, INACTIVE_VARS,
DAURVar_histogram_point_real = 0, DAURVar_Nkinds = 1
}
enum {
CV_ID_DEFAULT = 0, MINIMUM_METRIC, RELATIVE_TOLERANCE, DECREASE_TOLERANCE,
NO_MODEL_SELECTION =0, ALL_MODEL_COMBINATIONS, NOCOVAR =0, EXP_L2,
EXP_L1, EMPTY_TYPE =0, CONTINUOUS_DESIGN, DISCRETE_DESIGN_RANGE,
DISCRETE_DESIGN_SET_INT, DISCRETE_DESIGN_SET_STRING, DISCRETE_DESIGN_SET_REAL, NORMAL_UNCERTAIN,
LOGNORMAL_UNCERTAIN, UNIFORM_UNCERTAIN, LOGUNIFORM_UNCERTAIN, TRIANGULAR_UNCERTAIN,
EXPONENTIAL_UNCERTAIN, BETA_UNCERTAIN, GAMMA_UNCERTAIN, GUMBEL_UNCERTAIN,
FRECHET_UNCERTAIN, WEIBULL_UNCERTAIN, HISTOGRAM_BIN_UNCERTAIN, POISSON_UNCERTAIN,
BINOMIAL_UNCERTAIN, NEGATIVE_BINOMIAL_UNCERTAIN, GEOMETRIC_UNCERTAIN, HYPERGEOMETRIC_UNCERTAIN,
HISTOGRAM_POINT_UNCERTAIN_INT, HISTOGRAM_POINT_UNCERTAIN_STRING, HISTOGRAM_POINT_UNCERTAIN_REAL, CONTINUOUS_INTERVAL_UNCERTAIN,
DISCRETE_INTERVAL_UNCERTAIN, DISCRETE_UNCERTAIN_SET_INT, DISCRETE_UNCERTAIN_SET_STRING, DISCRETE_UNCERTAIN_SET_REAL,
CONTINUOUS_STATE, DISCRETE_STATE_RANGE, DISCRETE_STATE_SET_INT, DISCRETE_STATE_SET_STRING,
DISCRETE_STATE_SET_REAL, CEUVar_interval = 0, CEUVar_Nkinds = 1
}
enum {
TABULAR_NONE = 0, TABULAR_HEADER = 1, TABULAR_EVAL_ID = 2, TABULAR_IFACE_ID = 4,
TABULAR_EXPER_ANNOT = TABULAR_HEADER | TABULAR_EVAL_ID, TABULAR_ANNOTATED = TABULAR_HEADER | TABULAR_EVAL_ID | TABULAR_IFACE_ID, SILENT_OUTPUT, QUIET_OUTPUT,
NORMAL_OUTPUT, VERBOSE_OUTPUT, DEBUG_OUTPUT, SUBSPACE_NORM_DEFAULT =0,
SUBSPACE_NORM_MEAN_VALUE, SUBSPACE_NORM_MEAN_GRAD, SUBSPACE_NORM_LOCAL_GRAD, TOTAL_CDV =0,
TOTAL_DDIV, TOTAL_DDSV, TOTAL_DDRV, TOTAL_CAUV,
TOTAL_DAUIV, TOTAL_DAUSV, TOTAL_DAURV, TOTAL_CEUV,
TOTAL_DEUIV, TOTAL_DEUSV, TOTAL_DEURV, TOTAL_CSV,
TOTAL_DSIV, TOTAL_DSSV, TOTAL_DSRV, NUM_VC_TOTALS,
DEUIVar_interval = 0, DEUIVar_set_int = 1, DEUIVar_Nkinds = 2
}
enum {
RESULTS_OUTPUT_TEXT = 1, RESULTS_OUTPUT_HDF5 = 2, NO_RESULTS =0, REFINEMENT_RESULTS,
INTERMEDIATE_RESULTS, FINAL_RESULTS, ROTATION_METHOD_UNRANKED, ROTATION_METHOD_RANKED,
DEUSVar_set_str = 0, DEUSVar_Nkinds = 1
}
enum {
FLEXIBLE_RESULTS, LABELED_RESULTS, DEFAULT_SYNCHRONIZATION =0, BLOCKING_SYNCHRONIZATION,
NONBLOCKING_SYNCHRONIZATION, NO_PARALLEL_MODE =0, SURROGATE_MODEL_MODE, TRUTH_MODEL_MODE,
SUB_MODEL_MODE, INTERFACE_MODE, DEURVar_set_real = 0, DEURVar_Nkinds = 1
}
enum {
NO_MODEL_FORMAT =0, TEXT_ARCHIVE =1, BINARY_ARCHIVE =2, ALGEBRAIC_FILE =4,
ALGEBRAIC_CONSOLE =8, DEFAULT_SCHEDULING, MASTER_SCHEDULING, PEER_SCHEDULING,
PEER_DYNAMIC_SCHEDULING, PEER_STATIC_SCHEDULING, DYNAMIC_SCHEDULING, STATIC_SCHEDULING,
NO_DERIVS =0, ALL_DERIVS, MIXED_DERIVS, DiscSetVar_design_set_int = 0,
DiscSetVar_design_set_str = 1, DiscSetVar_design_set_real = 2, DiscSetVar_state_set_int = 3, DiscSetVar_state_set_str = 4,
DiscSetVar_state_set_real = 5, DiscSetVar_Nkinds = 6
}
enum {
DEFAULT_CONFIG, PUSH_DOWN, PUSH_UP, FT_LS,
FT_RLS2, NUM_UNC_REAL_CONT = 4
}
number of real-valued uncertain contiguous containers
enum {
STD_NORMAL_U, STD_UNIFORM_U, PARTIAL_ASKEY_U, ASKEY_U,
EXTENDED_U, NO_C3_ADVANCEMENT =0, START_RANK_ADVANCEMENT, START_ORDER_ADVANCEMENT,
MAX_RANK_ADVANCEMENT, MAX_ORDER_ADVANCEMENT, MAX_RANK_ORDER_ADVANCEMENT, NUM_UNC_INT_CONT = 2
}
number of int-valued uncertain contiguous containers
enum {
DEFAULT_COVARIANCE, NO_COVARIANCE, DIAGONAL_COVARIANCE, FULL_COVARIANCE,
NUM_UNC_STR_CONT = 2
}
number of string-valued uncertain contiguous containers
enum miAlg : unsigned short { MI_ALG_KSG1 = 0, MI_ALG_KSG2 = 1 }
enum {
COBYLA, DIRECT, EA, MS,
PS, SW, BETA, VARS_ERROR = -11,
CONS_ERROR = -10, RESP_ERROR = -9, APPROX_ERROR = -8, METHOD_ERROR = -7,
MODEL_ERROR = -6, IO_ERROR = -5, INTERFACE_ERROR = -4, CONSTRUCT_ERROR = -3,
PARSE_ERROR = -2, OTHER_ERROR = -1, DEFAULT_INTERFACE =0, APPROX_INTERFACE,
FORK_INTERFACE =PROCESS_INTERFACE_BIT, SYSTEM_INTERFACE, GRID_INTERFACE, TEST_INTERFACE =DIRECT_INTERFACE_BIT,
PLUGIN_INTERFACE, MATLAB_INTERFACE, LEGACY_PYTHON_INTERFACE, PYTHON_INTERFACE,
SCILAB_INTERFACE, DEFAULT_METHOD =0, HYBRID =(META_BIT | PARALLEL_BIT), PARETO_SET,
MULTI_START, RICHARDSON_EXTRAP =(ANALYZER_BIT | VERIF_BIT), CENTERED_PARAMETER_STUDY =(ANALYZER_BIT | PSTUDYDACE_BIT), LIST_PARAMETER_STUDY,
MULTIDIM_PARAMETER_STUDY, VECTOR_PARAMETER_STUDY, DACE, FSU_CVT,
FSU_HALTON, FSU_HAMMERSLEY, PSUADE_MOAT, LOCAL_RELIABILITY =(ANALYZER_BIT | NOND_BIT),
GLOBAL_RELIABILITY, SURROGATE_BASED_UQ, POLYNOMIAL_CHAOS, MULTILEVEL_POLYNOMIAL_CHAOS,
MULTIFIDELITY_POLYNOMIAL_CHAOS, STOCH_COLLOCATION, MULTIFIDELITY_STOCH_COLLOCATION, C3_FUNCTION_TRAIN,
MULTILEVEL_FUNCTION_TRAIN, MULTIFIDELITY_FUNCTION_TRAIN, CUBATURE_INTEGRATION, SPARSE_GRID_INTEGRATION,
QUADRATURE_INTEGRATION, BAYES_CALIBRATION, GPAIS, POF_DARTS,
RKD_DARTS, IMPORTANCE_SAMPLING, ADAPTIVE_SAMPLING, MULTILEVEL_SAMPLING,
MULTIFIDELITY_SAMPLING, MULTILEVEL_MULTIFIDELITY_SAMPLING, APPROXIMATE_CONTROL_VARIATE, LIST_SAMPLING,
RANDOM_SAMPLING, LOCAL_INTERVAL_EST, LOCAL_EVIDENCE, GLOBAL_INTERVAL_EST,
GLOBAL_EVIDENCE, SURROGATE_BASED_LOCAL =(MINIMIZER_BIT | SURRBASED_BIT), DATA_FIT_SURROGATE_BASED_LOCAL, HIERARCH_SURROGATE_BASED_LOCAL,
SURROGATE_BASED_GLOBAL, EFFICIENT_GLOBAL, NL2SOL =(MINIMIZER_BIT | LEASTSQ_BIT), NLSSOL_SQP,
OPTPP_G_NEWTON, ASYNCH_PATTERN_SEARCH =(MINIMIZER_BIT | OPTIMIZER_BIT), OPTPP_PDS, COLINY_BETA,
COLINY_COBYLA, COLINY_DIRECT, COLINY_MULTI_START, COLINY_EA,
COLINY_PATTERN_SEARCH, COLINY_SOLIS_WETS, MOGA, SOGA,
NCSU_DIRECT, MESH_ADAPTIVE_SEARCH, MIT_NOWPAC, MIT_SNOWPAC,
GENIE_OPT_DARTS, GENIE_DIRECT, DEMO_TPL, NONLINEAR_CG,
OPTPP_CG, OPTPP_Q_NEWTON, OPTPP_FD_NEWTON, OPTPP_NEWTON,
NPSOL_SQP, NLPQL_SQP, DOT_BFGS, DOT_FRCG,
DOT_MMFD, DOT_SLP, DOT_SQP, CONMIN_FRCG,
CONMIN_MFD, ROL, DL_SOLVER, BRANCH_AND_BOUND =(MINIMIZER_BIT | OPTIMIZER_BIT | LEASTSQ_BIT),
DEFAULT_POINTS, MINIMUM_POINTS, RECOMMENDED_POINTS, TOTAL_POINTS,
BASE_RESPONSE =0, SIMULATION_RESPONSE, EXPERIMENT_RESPONSE, DEFAULT_DOMAIN =0,
RELAXED_DOMAIN, MIXED_DOMAIN, DEFAULT_CORRECTION = 0, SINGLE_CORRECTION,
FULL_MODEL_FORM_CORRECTION, FULL_SOLUTION_LEVEL_CORRECTION, SEQUENCE_CORRECTION, SETUP_MODEL,
SETUP_USERFUNC, CAUVar_normal = 0, CAUVar_lognormal = 1, CAUVar_uniform = 2,
CAUVar_loguniform = 3, CAUVar_triangular = 4, CAUVar_exponential = 5, CAUVar_beta = 6,
CAUVar_gamma = 7, CAUVar_gumbel = 8, CAUVar_frechet = 9, CAUVar_weibull = 10,
CAUVar_histogram_bin = 11, CAUVar_Nkinds = 12, ANALYTIC_SOLUTION = 1, REORDERED_ANALYTIC_SOLUTION,
R_ONLY_LINEAR_CONSTRAINT, N_VECTOR_LINEAR_CONSTRAINT, R_AND_N_NONLINEAR_CONSTRAINT, N_VECTOR_LINEAR_OBJECTIVE,
FULL_TENSOR, FILTERED_TENSOR, RANDOM_TENSOR, AS_FUNC =1,
AS_GRAD =2, AS_HESS =4, DISALLOW, TARGET,
BOUNDS, SCALE_NONE = 0, SCALE_VALUE = 1, SCALE_LOG = 2,
SCALE_AUTO = 4, APPROX_RESPONSE =1, TRUTH_RESPONSE, TH_SILENT_OUTPUT,
TH_QUIET_OUTPUT, TH_NORMAL_OUTPUT, TH_VERBOSE_OUTPUT, TH_DEBUG_OUTPUT,
DIR_CLEAN, DIR_PERSIST, DIR_ERROR
}
enum {
COBYLA, DIRECT, EA, MS,
PS, SW, BETA, VARS_ERROR = -11,
CONS_ERROR = -10, RESP_ERROR = -9, APPROX_ERROR = -8, METHOD_ERROR = -7,
MODEL_ERROR = -6, IO_ERROR = -5, INTERFACE_ERROR = -4, CONSTRUCT_ERROR = -3,
PARSE_ERROR = -2, OTHER_ERROR = -1, DEFAULT_INTERFACE =0, APPROX_INTERFACE,
FORK_INTERFACE =PROCESS_INTERFACE_BIT, SYSTEM_INTERFACE, GRID_INTERFACE, TEST_INTERFACE =DIRECT_INTERFACE_BIT,
PLUGIN_INTERFACE, MATLAB_INTERFACE, LEGACY_PYTHON_INTERFACE, PYTHON_INTERFACE,
SCILAB_INTERFACE, DEFAULT_METHOD =0, HYBRID =(META_BIT | PARALLEL_BIT), PARETO_SET,
MULTI_START, RICHARDSON_EXTRAP =(ANALYZER_BIT | VERIF_BIT), CENTERED_PARAMETER_STUDY =(ANALYZER_BIT | PSTUDYDACE_BIT), LIST_PARAMETER_STUDY,
MULTIDIM_PARAMETER_STUDY, VECTOR_PARAMETER_STUDY, DACE, FSU_CVT,
FSU_HALTON, FSU_HAMMERSLEY, PSUADE_MOAT, LOCAL_RELIABILITY =(ANALYZER_BIT | NOND_BIT),
GLOBAL_RELIABILITY, SURROGATE_BASED_UQ, POLYNOMIAL_CHAOS, MULTILEVEL_POLYNOMIAL_CHAOS,
MULTIFIDELITY_POLYNOMIAL_CHAOS, STOCH_COLLOCATION, MULTIFIDELITY_STOCH_COLLOCATION, C3_FUNCTION_TRAIN,
MULTILEVEL_FUNCTION_TRAIN, MULTIFIDELITY_FUNCTION_TRAIN, CUBATURE_INTEGRATION, SPARSE_GRID_INTEGRATION,
QUADRATURE_INTEGRATION, BAYES_CALIBRATION, GPAIS, POF_DARTS,
RKD_DARTS, IMPORTANCE_SAMPLING, ADAPTIVE_SAMPLING, MULTILEVEL_SAMPLING,
MULTIFIDELITY_SAMPLING, MULTILEVEL_MULTIFIDELITY_SAMPLING, APPROXIMATE_CONTROL_VARIATE, LIST_SAMPLING,
RANDOM_SAMPLING, LOCAL_INTERVAL_EST, LOCAL_EVIDENCE, GLOBAL_INTERVAL_EST,
GLOBAL_EVIDENCE, SURROGATE_BASED_LOCAL =(MINIMIZER_BIT | SURRBASED_BIT), DATA_FIT_SURROGATE_BASED_LOCAL, HIERARCH_SURROGATE_BASED_LOCAL,
SURROGATE_BASED_GLOBAL, EFFICIENT_GLOBAL, NL2SOL =(MINIMIZER_BIT | LEASTSQ_BIT), NLSSOL_SQP,
OPTPP_G_NEWTON, ASYNCH_PATTERN_SEARCH =(MINIMIZER_BIT | OPTIMIZER_BIT), OPTPP_PDS, COLINY_BETA,
COLINY_COBYLA, COLINY_DIRECT, COLINY_MULTI_START, COLINY_EA,
COLINY_PATTERN_SEARCH, COLINY_SOLIS_WETS, MOGA, SOGA,
NCSU_DIRECT, MESH_ADAPTIVE_SEARCH, MIT_NOWPAC, MIT_SNOWPAC,
GENIE_OPT_DARTS, GENIE_DIRECT, DEMO_TPL, NONLINEAR_CG,
OPTPP_CG, OPTPP_Q_NEWTON, OPTPP_FD_NEWTON, OPTPP_NEWTON,
NPSOL_SQP, NLPQL_SQP, DOT_BFGS, DOT_FRCG,
DOT_MMFD, DOT_SLP, DOT_SQP, CONMIN_FRCG,
CONMIN_MFD, ROL, DL_SOLVER, BRANCH_AND_BOUND =(MINIMIZER_BIT | OPTIMIZER_BIT | LEASTSQ_BIT),
DEFAULT_POINTS, MINIMUM_POINTS, RECOMMENDED_POINTS, TOTAL_POINTS,
BASE_RESPONSE =0, SIMULATION_RESPONSE, EXPERIMENT_RESPONSE, DEFAULT_DOMAIN =0,
RELAXED_DOMAIN, MIXED_DOMAIN, DEFAULT_CORRECTION = 0, SINGLE_CORRECTION,
FULL_MODEL_FORM_CORRECTION, FULL_SOLUTION_LEVEL_CORRECTION, SEQUENCE_CORRECTION, SETUP_MODEL,
SETUP_USERFUNC, CAUVar_normal = 0, CAUVar_lognormal = 1, CAUVar_uniform = 2,
CAUVar_loguniform = 3, CAUVar_triangular = 4, CAUVar_exponential = 5, CAUVar_beta = 6,
CAUVar_gamma = 7, CAUVar_gumbel = 8, CAUVar_frechet = 9, CAUVar_weibull = 10,
CAUVar_histogram_bin = 11, CAUVar_Nkinds = 12, ANALYTIC_SOLUTION = 1, REORDERED_ANALYTIC_SOLUTION,
R_ONLY_LINEAR_CONSTRAINT, N_VECTOR_LINEAR_CONSTRAINT, R_AND_N_NONLINEAR_CONSTRAINT, N_VECTOR_LINEAR_OBJECTIVE,
FULL_TENSOR, FILTERED_TENSOR, RANDOM_TENSOR, AS_FUNC =1,
AS_GRAD =2, AS_HESS =4, DISALLOW, TARGET,
BOUNDS, SCALE_NONE = 0, SCALE_VALUE = 1, SCALE_LOG = 2,
SCALE_AUTO = 4, APPROX_RESPONSE =1, TRUTH_RESPONSE, TH_SILENT_OUTPUT,
TH_QUIET_OUTPUT, TH_NORMAL_OUTPUT, TH_VERBOSE_OUTPUT, TH_DEBUG_OUTPUT,
DIR_CLEAN, DIR_PERSIST, DIR_ERROR
}
enum CG_UPDATETYPE {
CG_STEEPEST, CG_FLETCHER_REEVES, CG_POLAK_RIBIERE, CG_POLAK_RIBIERE_PLUS,
CG_HESTENES_STIEFEL
}
NonlinearCG update options.
enum CG_LINESEARCHTYPE { CG_FIXED_STEP, CG_LS_SIMPLE, CG_LS_BRENT, CG_LS_WOLFE }
NonlinearCG linesearch options.
enum Rank1LatticeOrdering { RANK_1_LATTICE_NATURAL_ORDERING, RANK_1_LATTICE_RADICAL_INVERSE_ORDERING }
Enum for rank-1 lattice rule ordering.
enum {
COBYLA, DIRECT, EA, MS,
PS, SW, BETA, VARS_ERROR = -11,
CONS_ERROR = -10, RESP_ERROR = -9, APPROX_ERROR = -8, METHOD_ERROR = -7,
MODEL_ERROR = -6, IO_ERROR = -5, INTERFACE_ERROR = -4, CONSTRUCT_ERROR = -3,
PARSE_ERROR = -2, OTHER_ERROR = -1, DEFAULT_INTERFACE =0, APPROX_INTERFACE,
FORK_INTERFACE =PROCESS_INTERFACE_BIT, SYSTEM_INTERFACE, GRID_INTERFACE, TEST_INTERFACE =DIRECT_INTERFACE_BIT,
PLUGIN_INTERFACE, MATLAB_INTERFACE, LEGACY_PYTHON_INTERFACE, PYTHON_INTERFACE,
SCILAB_INTERFACE, DEFAULT_METHOD =0, HYBRID =(META_BIT | PARALLEL_BIT), PARETO_SET,
MULTI_START, RICHARDSON_EXTRAP =(ANALYZER_BIT | VERIF_BIT), CENTERED_PARAMETER_STUDY =(ANALYZER_BIT | PSTUDYDACE_BIT), LIST_PARAMETER_STUDY,
MULTIDIM_PARAMETER_STUDY, VECTOR_PARAMETER_STUDY, DACE, FSU_CVT,
FSU_HALTON, FSU_HAMMERSLEY, PSUADE_MOAT, LOCAL_RELIABILITY =(ANALYZER_BIT | NOND_BIT),
GLOBAL_RELIABILITY, SURROGATE_BASED_UQ, POLYNOMIAL_CHAOS, MULTILEVEL_POLYNOMIAL_CHAOS,
MULTIFIDELITY_POLYNOMIAL_CHAOS, STOCH_COLLOCATION, MULTIFIDELITY_STOCH_COLLOCATION, C3_FUNCTION_TRAIN,
MULTILEVEL_FUNCTION_TRAIN, MULTIFIDELITY_FUNCTION_TRAIN, CUBATURE_INTEGRATION, SPARSE_GRID_INTEGRATION,
QUADRATURE_INTEGRATION, BAYES_CALIBRATION, GPAIS, POF_DARTS,
RKD_DARTS, IMPORTANCE_SAMPLING, ADAPTIVE_SAMPLING, MULTILEVEL_SAMPLING,
MULTIFIDELITY_SAMPLING, MULTILEVEL_MULTIFIDELITY_SAMPLING, APPROXIMATE_CONTROL_VARIATE, LIST_SAMPLING,
RANDOM_SAMPLING, LOCAL_INTERVAL_EST, LOCAL_EVIDENCE, GLOBAL_INTERVAL_EST,
GLOBAL_EVIDENCE, SURROGATE_BASED_LOCAL =(MINIMIZER_BIT | SURRBASED_BIT), DATA_FIT_SURROGATE_BASED_LOCAL, HIERARCH_SURROGATE_BASED_LOCAL,
SURROGATE_BASED_GLOBAL, EFFICIENT_GLOBAL, NL2SOL =(MINIMIZER_BIT | LEASTSQ_BIT), NLSSOL_SQP,
OPTPP_G_NEWTON, ASYNCH_PATTERN_SEARCH =(MINIMIZER_BIT | OPTIMIZER_BIT), OPTPP_PDS, COLINY_BETA,
COLINY_COBYLA, COLINY_DIRECT, COLINY_MULTI_START, COLINY_EA,
COLINY_PATTERN_SEARCH, COLINY_SOLIS_WETS, MOGA, SOGA,
NCSU_DIRECT, MESH_ADAPTIVE_SEARCH, MIT_NOWPAC, MIT_SNOWPAC,
GENIE_OPT_DARTS, GENIE_DIRECT, DEMO_TPL, NONLINEAR_CG,
OPTPP_CG, OPTPP_Q_NEWTON, OPTPP_FD_NEWTON, OPTPP_NEWTON,
NPSOL_SQP, NLPQL_SQP, DOT_BFGS, DOT_FRCG,
DOT_MMFD, DOT_SLP, DOT_SQP, CONMIN_FRCG,
CONMIN_MFD, ROL, DL_SOLVER, BRANCH_AND_BOUND =(MINIMIZER_BIT | OPTIMIZER_BIT | LEASTSQ_BIT),
DEFAULT_POINTS, MINIMUM_POINTS, RECOMMENDED_POINTS, TOTAL_POINTS,
BASE_RESPONSE =0, SIMULATION_RESPONSE, EXPERIMENT_RESPONSE, DEFAULT_DOMAIN =0,
RELAXED_DOMAIN, MIXED_DOMAIN, DEFAULT_CORRECTION = 0, SINGLE_CORRECTION,
FULL_MODEL_FORM_CORRECTION, FULL_SOLUTION_LEVEL_CORRECTION, SEQUENCE_CORRECTION, SETUP_MODEL,
SETUP_USERFUNC, CAUVar_normal = 0, CAUVar_lognormal = 1, CAUVar_uniform = 2,
CAUVar_loguniform = 3, CAUVar_triangular = 4, CAUVar_exponential = 5, CAUVar_beta = 6,
CAUVar_gamma = 7, CAUVar_gumbel = 8, CAUVar_frechet = 9, CAUVar_weibull = 10,
CAUVar_histogram_bin = 11, CAUVar_Nkinds = 12, ANALYTIC_SOLUTION = 1, REORDERED_ANALYTIC_SOLUTION,
R_ONLY_LINEAR_CONSTRAINT, N_VECTOR_LINEAR_CONSTRAINT, R_AND_N_NONLINEAR_CONSTRAINT, N_VECTOR_LINEAR_OBJECTIVE,
FULL_TENSOR, FILTERED_TENSOR, RANDOM_TENSOR, AS_FUNC =1,
AS_GRAD =2, AS_HESS =4, DISALLOW, TARGET,
BOUNDS, SCALE_NONE = 0, SCALE_VALUE = 1, SCALE_LOG = 2,
SCALE_AUTO = 4, APPROX_RESPONSE =1, TRUTH_RESPONSE, TH_SILENT_OUTPUT,
TH_QUIET_OUTPUT, TH_NORMAL_OUTPUT, TH_VERBOSE_OUTPUT, TH_DEBUG_OUTPUT,
DIR_CLEAN, DIR_PERSIST, DIR_ERROR
}
enum {
MODEL_EVAL_STORE_TOP_METHOD = 0, MODEL_EVAL_STORE_NONE, MODEL_EVAL_STORE_ALL, MODEL_EVAL_STORE_ALL_METHODS,
SYNCHRONOUS_INTERFACE, ASYNCHRONOUS_INTERFACE, SUBMETHOD_DEFAULT =0, SUBMETHOD_NONE,
SUBMETHOD_COLLABORATIVE, SUBMETHOD_EMBEDDED, SUBMETHOD_SEQUENTIAL, SUBMETHOD_LHS,
SUBMETHOD_RANDOM, SUBMETHOD_LOW_DISCREPANCY_SAMPLING, SUBMETHOD_BOX_BEHNKEN, SUBMETHOD_CENTRAL_COMPOSITE,
SUBMETHOD_GRID, SUBMETHOD_OA_LHS, SUBMETHOD_OAS, SUBMETHOD_MFMC,
SUBMETHOD_ACV_IS, SUBMETHOD_ACV_MF, SUBMETHOD_ACV_RD, SUBMETHOD_DREAM,
SUBMETHOD_GPMSA, SUBMETHOD_MUQ, SUBMETHOD_QUESO, SUBMETHOD_WASABI,
SUBMETHOD_CONMIN, SUBMETHOD_DOT, SUBMETHOD_NLPQL, SUBMETHOD_NPSOL,
SUBMETHOD_OPTPP, SUBMETHOD_NPSOL_OPTPP, SUBMETHOD_DIRECT, SUBMETHOD_DIRECT_NPSOL_OPTPP,
SUBMETHOD_DIRECT_NPSOL, SUBMETHOD_DIRECT_OPTPP, SUBMETHOD_EA, SUBMETHOD_EGO,
SUBMETHOD_SBLO, SUBMETHOD_SBGO, SUBMETHOD_AMV_X, SUBMETHOD_AMV_U,
SUBMETHOD_AMV_PLUS_X, SUBMETHOD_AMV_PLUS_U, SUBMETHOD_TANA_X, SUBMETHOD_TANA_U,
SUBMETHOD_QMEA_X, SUBMETHOD_QMEA_U, SUBMETHOD_NO_APPROX, SUBMETHOD_EGRA_X,
SUBMETHOD_EGRA_U, SUBMETHOD_CONVERGE_ORDER, SUBMETHOD_CONVERGE_QOI, SUBMETHOD_ESTIMATE_ORDER,
DEFAULT_SURROGATE_RESP_MODE =0, NO_SURROGATE, UNCORRECTED_SURROGATE, AUTO_CORRECTED_SURROGATE,
BYPASS_SURROGATE, MODEL_DISCREPANCY, AGGREGATED_MODEL_PAIR, AGGREGATED_MODELS,
GENERIC_FNS = 0, OBJECTIVE_FNS, CALIB_TERMS, DEFAULT_VIEW =0,
ALL_VIEW, DESIGN_VIEW, UNCERTAIN_VIEW, ALEATORY_UNCERTAIN_VIEW,
EPISTEMIC_UNCERTAIN_VIEW, STATE_VIEW, DAUIVar_poisson = 0, DAUIVar_binomial = 1,
DAUIVar_negative_binomial = 2, DAUIVar_geometric = 3, DAUIVar_hypergeometric = 4, DAUIVar_histogram_point_int = 5,
DAUIVar_Nkinds = 6, TYPE_U =1, TYPE_B =2, TYPE_E =3,
TYPE_EB =4, CORR_APPROX_RESPONSE =1, UNCORR_APPROX_RESPONSE, CORR_TRUTH_RESPONSE,
UNCORR_TRUTH_RESPONSE, FILEOP_SILENT, FILEOP_WARN, FILEOP_ERROR
}
enum {
COBYLA, DIRECT, EA, MS,
PS, SW, BETA, VARS_ERROR = -11,
CONS_ERROR = -10, RESP_ERROR = -9, APPROX_ERROR = -8, METHOD_ERROR = -7,
MODEL_ERROR = -6, IO_ERROR = -5, INTERFACE_ERROR = -4, CONSTRUCT_ERROR = -3,
PARSE_ERROR = -2, OTHER_ERROR = -1, DEFAULT_INTERFACE =0, APPROX_INTERFACE,
FORK_INTERFACE =PROCESS_INTERFACE_BIT, SYSTEM_INTERFACE, GRID_INTERFACE, TEST_INTERFACE =DIRECT_INTERFACE_BIT,
PLUGIN_INTERFACE, MATLAB_INTERFACE, LEGACY_PYTHON_INTERFACE, PYTHON_INTERFACE,
SCILAB_INTERFACE, DEFAULT_METHOD =0, HYBRID =(META_BIT | PARALLEL_BIT), PARETO_SET,
MULTI_START, RICHARDSON_EXTRAP =(ANALYZER_BIT | VERIF_BIT), CENTERED_PARAMETER_STUDY =(ANALYZER_BIT | PSTUDYDACE_BIT), LIST_PARAMETER_STUDY,
MULTIDIM_PARAMETER_STUDY, VECTOR_PARAMETER_STUDY, DACE, FSU_CVT,
FSU_HALTON, FSU_HAMMERSLEY, PSUADE_MOAT, LOCAL_RELIABILITY =(ANALYZER_BIT | NOND_BIT),
GLOBAL_RELIABILITY, SURROGATE_BASED_UQ, POLYNOMIAL_CHAOS, MULTILEVEL_POLYNOMIAL_CHAOS,
MULTIFIDELITY_POLYNOMIAL_CHAOS, STOCH_COLLOCATION, MULTIFIDELITY_STOCH_COLLOCATION, C3_FUNCTION_TRAIN,
MULTILEVEL_FUNCTION_TRAIN, MULTIFIDELITY_FUNCTION_TRAIN, CUBATURE_INTEGRATION, SPARSE_GRID_INTEGRATION,
QUADRATURE_INTEGRATION, BAYES_CALIBRATION, GPAIS, POF_DARTS,
RKD_DARTS, IMPORTANCE_SAMPLING, ADAPTIVE_SAMPLING, MULTILEVEL_SAMPLING,
MULTIFIDELITY_SAMPLING, MULTILEVEL_MULTIFIDELITY_SAMPLING, APPROXIMATE_CONTROL_VARIATE, LIST_SAMPLING,
RANDOM_SAMPLING, LOCAL_INTERVAL_EST, LOCAL_EVIDENCE, GLOBAL_INTERVAL_EST,
GLOBAL_EVIDENCE, SURROGATE_BASED_LOCAL =(MINIMIZER_BIT | SURRBASED_BIT), DATA_FIT_SURROGATE_BASED_LOCAL, HIERARCH_SURROGATE_BASED_LOCAL,
SURROGATE_BASED_GLOBAL, EFFICIENT_GLOBAL, NL2SOL =(MINIMIZER_BIT | LEASTSQ_BIT), NLSSOL_SQP,
OPTPP_G_NEWTON, ASYNCH_PATTERN_SEARCH =(MINIMIZER_BIT | OPTIMIZER_BIT), OPTPP_PDS, COLINY_BETA,
COLINY_COBYLA, COLINY_DIRECT, COLINY_MULTI_START, COLINY_EA,
COLINY_PATTERN_SEARCH, COLINY_SOLIS_WETS, MOGA, SOGA,
NCSU_DIRECT, MESH_ADAPTIVE_SEARCH, MIT_NOWPAC, MIT_SNOWPAC,
GENIE_OPT_DARTS, GENIE_DIRECT, DEMO_TPL, NONLINEAR_CG,
OPTPP_CG, OPTPP_Q_NEWTON, OPTPP_FD_NEWTON, OPTPP_NEWTON,
NPSOL_SQP, NLPQL_SQP, DOT_BFGS, DOT_FRCG,
DOT_MMFD, DOT_SLP, DOT_SQP, CONMIN_FRCG,
CONMIN_MFD, ROL, DL_SOLVER, BRANCH_AND_BOUND =(MINIMIZER_BIT | OPTIMIZER_BIT | LEASTSQ_BIT),
DEFAULT_POINTS, MINIMUM_POINTS, RECOMMENDED_POINTS, TOTAL_POINTS,
BASE_RESPONSE =0, SIMULATION_RESPONSE, EXPERIMENT_RESPONSE, DEFAULT_DOMAIN =0,
RELAXED_DOMAIN, MIXED_DOMAIN, DEFAULT_CORRECTION = 0, SINGLE_CORRECTION,
FULL_MODEL_FORM_CORRECTION, FULL_SOLUTION_LEVEL_CORRECTION, SEQUENCE_CORRECTION, SETUP_MODEL,
SETUP_USERFUNC, CAUVar_normal = 0, CAUVar_lognormal = 1, CAUVar_uniform = 2,
CAUVar_loguniform = 3, CAUVar_triangular = 4, CAUVar_exponential = 5, CAUVar_beta = 6,
CAUVar_gamma = 7, CAUVar_gumbel = 8, CAUVar_frechet = 9, CAUVar_weibull = 10,
CAUVar_histogram_bin = 11, CAUVar_Nkinds = 12, ANALYTIC_SOLUTION = 1, REORDERED_ANALYTIC_SOLUTION,
R_ONLY_LINEAR_CONSTRAINT, N_VECTOR_LINEAR_CONSTRAINT, R_AND_N_NONLINEAR_CONSTRAINT, N_VECTOR_LINEAR_OBJECTIVE,
FULL_TENSOR, FILTERED_TENSOR, RANDOM_TENSOR, AS_FUNC =1,
AS_GRAD =2, AS_HESS =4, DISALLOW, TARGET,
BOUNDS, SCALE_NONE = 0, SCALE_VALUE = 1, SCALE_LOG = 2,
SCALE_AUTO = 4, APPROX_RESPONSE =1, TRUTH_RESPONSE, TH_SILENT_OUTPUT,
TH_QUIET_OUTPUT, TH_NORMAL_OUTPUT, TH_VERBOSE_OUTPUT, TH_DEBUG_OUTPUT,
DIR_CLEAN, DIR_PERSIST, DIR_ERROR
}
to restrict type of auto scaling allowed
enum {
COBYLA, DIRECT, EA, MS,
PS, SW, BETA, VARS_ERROR = -11,
CONS_ERROR = -10, RESP_ERROR = -9, APPROX_ERROR = -8, METHOD_ERROR = -7,
MODEL_ERROR = -6, IO_ERROR = -5, INTERFACE_ERROR = -4, CONSTRUCT_ERROR = -3,
PARSE_ERROR = -2, OTHER_ERROR = -1, DEFAULT_INTERFACE =0, APPROX_INTERFACE,
FORK_INTERFACE =PROCESS_INTERFACE_BIT, SYSTEM_INTERFACE, GRID_INTERFACE, TEST_INTERFACE =DIRECT_INTERFACE_BIT,
PLUGIN_INTERFACE, MATLAB_INTERFACE, LEGACY_PYTHON_INTERFACE, PYTHON_INTERFACE,
SCILAB_INTERFACE, DEFAULT_METHOD =0, HYBRID =(META_BIT | PARALLEL_BIT), PARETO_SET,
MULTI_START, RICHARDSON_EXTRAP =(ANALYZER_BIT | VERIF_BIT), CENTERED_PARAMETER_STUDY =(ANALYZER_BIT | PSTUDYDACE_BIT), LIST_PARAMETER_STUDY,
MULTIDIM_PARAMETER_STUDY, VECTOR_PARAMETER_STUDY, DACE, FSU_CVT,
FSU_HALTON, FSU_HAMMERSLEY, PSUADE_MOAT, LOCAL_RELIABILITY =(ANALYZER_BIT | NOND_BIT),
GLOBAL_RELIABILITY, SURROGATE_BASED_UQ, POLYNOMIAL_CHAOS, MULTILEVEL_POLYNOMIAL_CHAOS,
MULTIFIDELITY_POLYNOMIAL_CHAOS, STOCH_COLLOCATION, MULTIFIDELITY_STOCH_COLLOCATION, C3_FUNCTION_TRAIN,
MULTILEVEL_FUNCTION_TRAIN, MULTIFIDELITY_FUNCTION_TRAIN, CUBATURE_INTEGRATION, SPARSE_GRID_INTEGRATION,
QUADRATURE_INTEGRATION, BAYES_CALIBRATION, GPAIS, POF_DARTS,
RKD_DARTS, IMPORTANCE_SAMPLING, ADAPTIVE_SAMPLING, MULTILEVEL_SAMPLING,
MULTIFIDELITY_SAMPLING, MULTILEVEL_MULTIFIDELITY_SAMPLING, APPROXIMATE_CONTROL_VARIATE, LIST_SAMPLING,
RANDOM_SAMPLING, LOCAL_INTERVAL_EST, LOCAL_EVIDENCE, GLOBAL_INTERVAL_EST,
GLOBAL_EVIDENCE, SURROGATE_BASED_LOCAL =(MINIMIZER_BIT | SURRBASED_BIT), DATA_FIT_SURROGATE_BASED_LOCAL, HIERARCH_SURROGATE_BASED_LOCAL,
SURROGATE_BASED_GLOBAL, EFFICIENT_GLOBAL, NL2SOL =(MINIMIZER_BIT | LEASTSQ_BIT), NLSSOL_SQP,
OPTPP_G_NEWTON, ASYNCH_PATTERN_SEARCH =(MINIMIZER_BIT | OPTIMIZER_BIT), OPTPP_PDS, COLINY_BETA,
COLINY_COBYLA, COLINY_DIRECT, COLINY_MULTI_START, COLINY_EA,
COLINY_PATTERN_SEARCH, COLINY_SOLIS_WETS, MOGA, SOGA,
NCSU_DIRECT, MESH_ADAPTIVE_SEARCH, MIT_NOWPAC, MIT_SNOWPAC,
GENIE_OPT_DARTS, GENIE_DIRECT, DEMO_TPL, NONLINEAR_CG,
OPTPP_CG, OPTPP_Q_NEWTON, OPTPP_FD_NEWTON, OPTPP_NEWTON,
NPSOL_SQP, NLPQL_SQP, DOT_BFGS, DOT_FRCG,
DOT_MMFD, DOT_SLP, DOT_SQP, CONMIN_FRCG,
CONMIN_MFD, ROL, DL_SOLVER, BRANCH_AND_BOUND =(MINIMIZER_BIT | OPTIMIZER_BIT | LEASTSQ_BIT),
DEFAULT_POINTS, MINIMUM_POINTS, RECOMMENDED_POINTS, TOTAL_POINTS,
BASE_RESPONSE =0, SIMULATION_RESPONSE, EXPERIMENT_RESPONSE, DEFAULT_DOMAIN =0,
RELAXED_DOMAIN, MIXED_DOMAIN, DEFAULT_CORRECTION = 0, SINGLE_CORRECTION,
FULL_MODEL_FORM_CORRECTION, FULL_SOLUTION_LEVEL_CORRECTION, SEQUENCE_CORRECTION, SETUP_MODEL,
SETUP_USERFUNC, CAUVar_normal = 0, CAUVar_lognormal = 1, CAUVar_uniform = 2,
CAUVar_loguniform = 3, CAUVar_triangular = 4, CAUVar_exponential = 5, CAUVar_beta = 6,
CAUVar_gamma = 7, CAUVar_gumbel = 8, CAUVar_frechet = 9, CAUVar_weibull = 10,
CAUVar_histogram_bin = 11, CAUVar_Nkinds = 12, ANALYTIC_SOLUTION = 1, REORDERED_ANALYTIC_SOLUTION,
R_ONLY_LINEAR_CONSTRAINT, N_VECTOR_LINEAR_CONSTRAINT, R_AND_N_NONLINEAR_CONSTRAINT, N_VECTOR_LINEAR_OBJECTIVE,
FULL_TENSOR, FILTERED_TENSOR, RANDOM_TENSOR, AS_FUNC =1,
AS_GRAD =2, AS_HESS =4, DISALLOW, TARGET,
BOUNDS, SCALE_NONE = 0, SCALE_VALUE = 1, SCALE_LOG = 2,
SCALE_AUTO = 4, APPROX_RESPONSE =1, TRUTH_RESPONSE, TH_SILENT_OUTPUT,
TH_QUIET_OUTPUT, TH_NORMAL_OUTPUT, TH_VERBOSE_OUTPUT, TH_DEBUG_OUTPUT,
DIR_CLEAN, DIR_PERSIST, DIR_ERROR
}
indicate type of scaling active for a component (bitwise)
enum EvalType { NO_EVALUATOR, NLF_EVALUATOR, CON_EVALUATOR }
enumeration for the type of evaluator function
enum {
COBYLA, DIRECT, EA, MS,
PS, SW, BETA, VARS_ERROR = -11,
CONS_ERROR = -10, RESP_ERROR = -9, APPROX_ERROR = -8, METHOD_ERROR = -7,
MODEL_ERROR = -6, IO_ERROR = -5, INTERFACE_ERROR = -4, CONSTRUCT_ERROR = -3,
PARSE_ERROR = -2, OTHER_ERROR = -1, DEFAULT_INTERFACE =0, APPROX_INTERFACE,
FORK_INTERFACE =PROCESS_INTERFACE_BIT, SYSTEM_INTERFACE, GRID_INTERFACE, TEST_INTERFACE =DIRECT_INTERFACE_BIT,
PLUGIN_INTERFACE, MATLAB_INTERFACE, LEGACY_PYTHON_INTERFACE, PYTHON_INTERFACE,
SCILAB_INTERFACE, DEFAULT_METHOD =0, HYBRID =(META_BIT | PARALLEL_BIT), PARETO_SET,
MULTI_START, RICHARDSON_EXTRAP =(ANALYZER_BIT | VERIF_BIT), CENTERED_PARAMETER_STUDY =(ANALYZER_BIT | PSTUDYDACE_BIT), LIST_PARAMETER_STUDY,
MULTIDIM_PARAMETER_STUDY, VECTOR_PARAMETER_STUDY, DACE, FSU_CVT,
FSU_HALTON, FSU_HAMMERSLEY, PSUADE_MOAT, LOCAL_RELIABILITY =(ANALYZER_BIT | NOND_BIT),
GLOBAL_RELIABILITY, SURROGATE_BASED_UQ, POLYNOMIAL_CHAOS, MULTILEVEL_POLYNOMIAL_CHAOS,
MULTIFIDELITY_POLYNOMIAL_CHAOS, STOCH_COLLOCATION, MULTIFIDELITY_STOCH_COLLOCATION, C3_FUNCTION_TRAIN,
MULTILEVEL_FUNCTION_TRAIN, MULTIFIDELITY_FUNCTION_TRAIN, CUBATURE_INTEGRATION, SPARSE_GRID_INTEGRATION,
QUADRATURE_INTEGRATION, BAYES_CALIBRATION, GPAIS, POF_DARTS,
RKD_DARTS, IMPORTANCE_SAMPLING, ADAPTIVE_SAMPLING, MULTILEVEL_SAMPLING,
MULTIFIDELITY_SAMPLING, MULTILEVEL_MULTIFIDELITY_SAMPLING, APPROXIMATE_CONTROL_VARIATE, LIST_SAMPLING,
RANDOM_SAMPLING, LOCAL_INTERVAL_EST, LOCAL_EVIDENCE, GLOBAL_INTERVAL_EST,
GLOBAL_EVIDENCE, SURROGATE_BASED_LOCAL =(MINIMIZER_BIT | SURRBASED_BIT), DATA_FIT_SURROGATE_BASED_LOCAL, HIERARCH_SURROGATE_BASED_LOCAL,
SURROGATE_BASED_GLOBAL, EFFICIENT_GLOBAL, NL2SOL =(MINIMIZER_BIT | LEASTSQ_BIT), NLSSOL_SQP,
OPTPP_G_NEWTON, ASYNCH_PATTERN_SEARCH =(MINIMIZER_BIT | OPTIMIZER_BIT), OPTPP_PDS, COLINY_BETA,
COLINY_COBYLA, COLINY_DIRECT, COLINY_MULTI_START, COLINY_EA,
COLINY_PATTERN_SEARCH, COLINY_SOLIS_WETS, MOGA, SOGA,
NCSU_DIRECT, MESH_ADAPTIVE_SEARCH, MIT_NOWPAC, MIT_SNOWPAC,
GENIE_OPT_DARTS, GENIE_DIRECT, DEMO_TPL, NONLINEAR_CG,
OPTPP_CG, OPTPP_Q_NEWTON, OPTPP_FD_NEWTON, OPTPP_NEWTON,
NPSOL_SQP, NLPQL_SQP, DOT_BFGS, DOT_FRCG,
DOT_MMFD, DOT_SLP, DOT_SQP, CONMIN_FRCG,
CONMIN_MFD, ROL, DL_SOLVER, BRANCH_AND_BOUND =(MINIMIZER_BIT | OPTIMIZER_BIT | LEASTSQ_BIT),
DEFAULT_POINTS, MINIMUM_POINTS, RECOMMENDED_POINTS, TOTAL_POINTS,
BASE_RESPONSE =0, SIMULATION_RESPONSE, EXPERIMENT_RESPONSE, DEFAULT_DOMAIN =0,
RELAXED_DOMAIN, MIXED_DOMAIN, DEFAULT_CORRECTION = 0, SINGLE_CORRECTION,
FULL_MODEL_FORM_CORRECTION, FULL_SOLUTION_LEVEL_CORRECTION, SEQUENCE_CORRECTION, SETUP_MODEL,
SETUP_USERFUNC, CAUVar_normal = 0, CAUVar_lognormal = 1, CAUVar_uniform = 2,
CAUVar_loguniform = 3, CAUVar_triangular = 4, CAUVar_exponential = 5, CAUVar_beta = 6,
CAUVar_gamma = 7, CAUVar_gumbel = 8, CAUVar_frechet = 9, CAUVar_weibull = 10,
CAUVar_histogram_bin = 11, CAUVar_Nkinds = 12, ANALYTIC_SOLUTION = 1, REORDERED_ANALYTIC_SOLUTION,
R_ONLY_LINEAR_CONSTRAINT, N_VECTOR_LINEAR_CONSTRAINT, R_AND_N_NONLINEAR_CONSTRAINT, N_VECTOR_LINEAR_OBJECTIVE,
FULL_TENSOR, FILTERED_TENSOR, RANDOM_TENSOR, AS_FUNC =1,
AS_GRAD =2, AS_HESS =4, DISALLOW, TARGET,
BOUNDS, SCALE_NONE = 0, SCALE_VALUE = 1, SCALE_LOG = 2,
SCALE_AUTO = 4, APPROX_RESPONSE =1, TRUTH_RESPONSE, TH_SILENT_OUTPUT,
TH_QUIET_OUTPUT, TH_NORMAL_OUTPUT, TH_VERBOSE_OUTPUT, TH_DEBUG_OUTPUT,
DIR_CLEAN, DIR_PERSIST, DIR_ERROR
}
enum {
MODEL_EVAL_STORE_TOP_METHOD = 0, MODEL_EVAL_STORE_NONE, MODEL_EVAL_STORE_ALL, MODEL_EVAL_STORE_ALL_METHODS,
SYNCHRONOUS_INTERFACE, ASYNCHRONOUS_INTERFACE, SUBMETHOD_DEFAULT =0, SUBMETHOD_NONE,
SUBMETHOD_COLLABORATIVE, SUBMETHOD_EMBEDDED, SUBMETHOD_SEQUENTIAL, SUBMETHOD_LHS,
SUBMETHOD_RANDOM, SUBMETHOD_LOW_DISCREPANCY_SAMPLING, SUBMETHOD_BOX_BEHNKEN, SUBMETHOD_CENTRAL_COMPOSITE,
SUBMETHOD_GRID, SUBMETHOD_OA_LHS, SUBMETHOD_OAS, SUBMETHOD_MFMC,
SUBMETHOD_ACV_IS, SUBMETHOD_ACV_MF, SUBMETHOD_ACV_RD, SUBMETHOD_DREAM,
SUBMETHOD_GPMSA, SUBMETHOD_MUQ, SUBMETHOD_QUESO, SUBMETHOD_WASABI,
SUBMETHOD_CONMIN, SUBMETHOD_DOT, SUBMETHOD_NLPQL, SUBMETHOD_NPSOL,
SUBMETHOD_OPTPP, SUBMETHOD_NPSOL_OPTPP, SUBMETHOD_DIRECT, SUBMETHOD_DIRECT_NPSOL_OPTPP,
SUBMETHOD_DIRECT_NPSOL, SUBMETHOD_DIRECT_OPTPP, SUBMETHOD_EA, SUBMETHOD_EGO,
SUBMETHOD_SBLO, SUBMETHOD_SBGO, SUBMETHOD_AMV_X, SUBMETHOD_AMV_U,
SUBMETHOD_AMV_PLUS_X, SUBMETHOD_AMV_PLUS_U, SUBMETHOD_TANA_X, SUBMETHOD_TANA_U,
SUBMETHOD_QMEA_X, SUBMETHOD_QMEA_U, SUBMETHOD_NO_APPROX, SUBMETHOD_EGRA_X,
SUBMETHOD_EGRA_U, SUBMETHOD_CONVERGE_ORDER, SUBMETHOD_CONVERGE_QOI, SUBMETHOD_ESTIMATE_ORDER,
DEFAULT_SURROGATE_RESP_MODE =0, NO_SURROGATE, UNCORRECTED_SURROGATE, AUTO_CORRECTED_SURROGATE,
BYPASS_SURROGATE, MODEL_DISCREPANCY, AGGREGATED_MODEL_PAIR, AGGREGATED_MODELS,
GENERIC_FNS = 0, OBJECTIVE_FNS, CALIB_TERMS, DEFAULT_VIEW =0,
ALL_VIEW, DESIGN_VIEW, UNCERTAIN_VIEW, ALEATORY_UNCERTAIN_VIEW,
EPISTEMIC_UNCERTAIN_VIEW, STATE_VIEW, DAUIVar_poisson = 0, DAUIVar_binomial = 1,
DAUIVar_negative_binomial = 2, DAUIVar_geometric = 3, DAUIVar_hypergeometric = 4, DAUIVar_histogram_point_int = 5,
DAUIVar_Nkinds = 6, TYPE_U =1, TYPE_B =2, TYPE_E =3,
TYPE_EB =4, CORR_APPROX_RESPONSE =1, UNCORR_APPROX_RESPONSE, CORR_TRUTH_RESPONSE,
UNCORR_TRUTH_RESPONSE, FILEOP_SILENT, FILEOP_WARN, FILEOP_ERROR
}
enum {
INTERF_EVAL_STORE_SIMULATION = 0, INTERF_EVAL_STORE_NONE, INTERF_EVAL_STORE_ALL, OBJECTIVE,
INEQUALITY_CONSTRAINT, EQUALITY_CONSTRAINT, VBD_BINNED =0, VBD_PICK_AND_FREEZE,
NO_CORRECTION =0, ADDITIVE_CORRECTION, MULTIPLICATIVE_CORRECTION, COMBINED_CORRECTION,
EMPTY_VIEW =0, RELAXED_ALL, MIXED_ALL, RELAXED_DESIGN,
RELAXED_UNCERTAIN, RELAXED_ALEATORY_UNCERTAIN, RELAXED_EPISTEMIC_UNCERTAIN, RELAXED_STATE,
MIXED_DESIGN, MIXED_UNCERTAIN, MIXED_ALEATORY_UNCERTAIN, MIXED_EPISTEMIC_UNCERTAIN,
MIXED_STATE, DAUSVar_histogram_point_str = 0, DAUSVar_Nkinds = 1, NEW_CANDIDATE = 1,
CANDIDATE_ACCEPTED = 2, CANDIDATE_STATE = (NEW_CANDIDATE | CANDIDATE_ACCEPTED), NEW_CENTER = 8, CENTER_BUILT = 16,
CENTER_STATE = (NEW_CENTER | CENTER_BUILT), NEW_TR_FACTOR = 64, NEW_TRUST_REGION = (NEW_CENTER | NEW_TR_FACTOR), HARD_CONVERGED = 128,
SOFT_CONVERGED = 256, MIN_TR_CONVERGED = 512, MAX_ITER_CONVERGED = 1024, CONVERGED
}
enum {
COBYLA, DIRECT, EA, MS,
PS, SW, BETA, VARS_ERROR = -11,
CONS_ERROR = -10, RESP_ERROR = -9, APPROX_ERROR = -8, METHOD_ERROR = -7,
MODEL_ERROR = -6, IO_ERROR = -5, INTERFACE_ERROR = -4, CONSTRUCT_ERROR = -3,
PARSE_ERROR = -2, OTHER_ERROR = -1, DEFAULT_INTERFACE =0, APPROX_INTERFACE,
FORK_INTERFACE =PROCESS_INTERFACE_BIT, SYSTEM_INTERFACE, GRID_INTERFACE, TEST_INTERFACE =DIRECT_INTERFACE_BIT,
PLUGIN_INTERFACE, MATLAB_INTERFACE, LEGACY_PYTHON_INTERFACE, PYTHON_INTERFACE,
SCILAB_INTERFACE, DEFAULT_METHOD =0, HYBRID =(META_BIT | PARALLEL_BIT), PARETO_SET,
MULTI_START, RICHARDSON_EXTRAP =(ANALYZER_BIT | VERIF_BIT), CENTERED_PARAMETER_STUDY =(ANALYZER_BIT | PSTUDYDACE_BIT), LIST_PARAMETER_STUDY,
MULTIDIM_PARAMETER_STUDY, VECTOR_PARAMETER_STUDY, DACE, FSU_CVT,
FSU_HALTON, FSU_HAMMERSLEY, PSUADE_MOAT, LOCAL_RELIABILITY =(ANALYZER_BIT | NOND_BIT),
GLOBAL_RELIABILITY, SURROGATE_BASED_UQ, POLYNOMIAL_CHAOS, MULTILEVEL_POLYNOMIAL_CHAOS,
MULTIFIDELITY_POLYNOMIAL_CHAOS, STOCH_COLLOCATION, MULTIFIDELITY_STOCH_COLLOCATION, C3_FUNCTION_TRAIN,
MULTILEVEL_FUNCTION_TRAIN, MULTIFIDELITY_FUNCTION_TRAIN, CUBATURE_INTEGRATION, SPARSE_GRID_INTEGRATION,
QUADRATURE_INTEGRATION, BAYES_CALIBRATION, GPAIS, POF_DARTS,
RKD_DARTS, IMPORTANCE_SAMPLING, ADAPTIVE_SAMPLING, MULTILEVEL_SAMPLING,
MULTIFIDELITY_SAMPLING, MULTILEVEL_MULTIFIDELITY_SAMPLING, APPROXIMATE_CONTROL_VARIATE, LIST_SAMPLING,
RANDOM_SAMPLING, LOCAL_INTERVAL_EST, LOCAL_EVIDENCE, GLOBAL_INTERVAL_EST,
GLOBAL_EVIDENCE, SURROGATE_BASED_LOCAL =(MINIMIZER_BIT | SURRBASED_BIT), DATA_FIT_SURROGATE_BASED_LOCAL, HIERARCH_SURROGATE_BASED_LOCAL,
SURROGATE_BASED_GLOBAL, EFFICIENT_GLOBAL, NL2SOL =(MINIMIZER_BIT | LEASTSQ_BIT), NLSSOL_SQP,
OPTPP_G_NEWTON, ASYNCH_PATTERN_SEARCH =(MINIMIZER_BIT | OPTIMIZER_BIT), OPTPP_PDS, COLINY_BETA,
COLINY_COBYLA, COLINY_DIRECT, COLINY_MULTI_START, COLINY_EA,
COLINY_PATTERN_SEARCH, COLINY_SOLIS_WETS, MOGA, SOGA,
NCSU_DIRECT, MESH_ADAPTIVE_SEARCH, MIT_NOWPAC, MIT_SNOWPAC,
GENIE_OPT_DARTS, GENIE_DIRECT, DEMO_TPL, NONLINEAR_CG,
OPTPP_CG, OPTPP_Q_NEWTON, OPTPP_FD_NEWTON, OPTPP_NEWTON,
NPSOL_SQP, NLPQL_SQP, DOT_BFGS, DOT_FRCG,
DOT_MMFD, DOT_SLP, DOT_SQP, CONMIN_FRCG,
CONMIN_MFD, ROL, DL_SOLVER, BRANCH_AND_BOUND =(MINIMIZER_BIT | OPTIMIZER_BIT | LEASTSQ_BIT),
DEFAULT_POINTS, MINIMUM_POINTS, RECOMMENDED_POINTS, TOTAL_POINTS,
BASE_RESPONSE =0, SIMULATION_RESPONSE, EXPERIMENT_RESPONSE, DEFAULT_DOMAIN =0,
RELAXED_DOMAIN, MIXED_DOMAIN, DEFAULT_CORRECTION = 0, SINGLE_CORRECTION,
FULL_MODEL_FORM_CORRECTION, FULL_SOLUTION_LEVEL_CORRECTION, SEQUENCE_CORRECTION, SETUP_MODEL,
SETUP_USERFUNC, CAUVar_normal = 0, CAUVar_lognormal = 1, CAUVar_uniform = 2,
CAUVar_loguniform = 3, CAUVar_triangular = 4, CAUVar_exponential = 5, CAUVar_beta = 6,
CAUVar_gamma = 7, CAUVar_gumbel = 8, CAUVar_frechet = 9, CAUVar_weibull = 10,
CAUVar_histogram_bin = 11, CAUVar_Nkinds = 12, ANALYTIC_SOLUTION = 1, REORDERED_ANALYTIC_SOLUTION,
R_ONLY_LINEAR_CONSTRAINT, N_VECTOR_LINEAR_CONSTRAINT, R_AND_N_NONLINEAR_CONSTRAINT, N_VECTOR_LINEAR_OBJECTIVE,
FULL_TENSOR, FILTERED_TENSOR, RANDOM_TENSOR, AS_FUNC =1,
AS_GRAD =2, AS_HESS =4, DISALLOW, TARGET,
BOUNDS, SCALE_NONE = 0, SCALE_VALUE = 1, SCALE_LOG = 2,
SCALE_AUTO = 4, APPROX_RESPONSE =1, TRUTH_RESPONSE, TH_SILENT_OUTPUT,
TH_QUIET_OUTPUT, TH_NORMAL_OUTPUT, TH_VERBOSE_OUTPUT, TH_DEBUG_OUTPUT,
DIR_CLEAN, DIR_PERSIST, DIR_ERROR
}
enum {
COBYLA, DIRECT, EA, MS,
PS, SW, BETA, VARS_ERROR = -11,
CONS_ERROR = -10, RESP_ERROR = -9, APPROX_ERROR = -8, METHOD_ERROR = -7,
MODEL_ERROR = -6, IO_ERROR = -5, INTERFACE_ERROR = -4, CONSTRUCT_ERROR = -3,
PARSE_ERROR = -2, OTHER_ERROR = -1, DEFAULT_INTERFACE =0, APPROX_INTERFACE,
FORK_INTERFACE =PROCESS_INTERFACE_BIT, SYSTEM_INTERFACE, GRID_INTERFACE, TEST_INTERFACE =DIRECT_INTERFACE_BIT,
PLUGIN_INTERFACE, MATLAB_INTERFACE, LEGACY_PYTHON_INTERFACE, PYTHON_INTERFACE,
SCILAB_INTERFACE, DEFAULT_METHOD =0, HYBRID =(META_BIT | PARALLEL_BIT), PARETO_SET,
MULTI_START, RICHARDSON_EXTRAP =(ANALYZER_BIT | VERIF_BIT), CENTERED_PARAMETER_STUDY =(ANALYZER_BIT | PSTUDYDACE_BIT), LIST_PARAMETER_STUDY,
MULTIDIM_PARAMETER_STUDY, VECTOR_PARAMETER_STUDY, DACE, FSU_CVT,
FSU_HALTON, FSU_HAMMERSLEY, PSUADE_MOAT, LOCAL_RELIABILITY =(ANALYZER_BIT | NOND_BIT),
GLOBAL_RELIABILITY, SURROGATE_BASED_UQ, POLYNOMIAL_CHAOS, MULTILEVEL_POLYNOMIAL_CHAOS,
MULTIFIDELITY_POLYNOMIAL_CHAOS, STOCH_COLLOCATION, MULTIFIDELITY_STOCH_COLLOCATION, C3_FUNCTION_TRAIN,
MULTILEVEL_FUNCTION_TRAIN, MULTIFIDELITY_FUNCTION_TRAIN, CUBATURE_INTEGRATION, SPARSE_GRID_INTEGRATION,
QUADRATURE_INTEGRATION, BAYES_CALIBRATION, GPAIS, POF_DARTS,
RKD_DARTS, IMPORTANCE_SAMPLING, ADAPTIVE_SAMPLING, MULTILEVEL_SAMPLING,
MULTIFIDELITY_SAMPLING, MULTILEVEL_MULTIFIDELITY_SAMPLING, APPROXIMATE_CONTROL_VARIATE, LIST_SAMPLING,
RANDOM_SAMPLING, LOCAL_INTERVAL_EST, LOCAL_EVIDENCE, GLOBAL_INTERVAL_EST,
GLOBAL_EVIDENCE, SURROGATE_BASED_LOCAL =(MINIMIZER_BIT | SURRBASED_BIT), DATA_FIT_SURROGATE_BASED_LOCAL, HIERARCH_SURROGATE_BASED_LOCAL,
SURROGATE_BASED_GLOBAL, EFFICIENT_GLOBAL, NL2SOL =(MINIMIZER_BIT | LEASTSQ_BIT), NLSSOL_SQP,
OPTPP_G_NEWTON, ASYNCH_PATTERN_SEARCH =(MINIMIZER_BIT | OPTIMIZER_BIT), OPTPP_PDS, COLINY_BETA,
COLINY_COBYLA, COLINY_DIRECT, COLINY_MULTI_START, COLINY_EA,
COLINY_PATTERN_SEARCH, COLINY_SOLIS_WETS, MOGA, SOGA,
NCSU_DIRECT, MESH_ADAPTIVE_SEARCH, MIT_NOWPAC, MIT_SNOWPAC,
GENIE_OPT_DARTS, GENIE_DIRECT, DEMO_TPL, NONLINEAR_CG,
OPTPP_CG, OPTPP_Q_NEWTON, OPTPP_FD_NEWTON, OPTPP_NEWTON,
NPSOL_SQP, NLPQL_SQP, DOT_BFGS, DOT_FRCG,
DOT_MMFD, DOT_SLP, DOT_SQP, CONMIN_FRCG,
CONMIN_MFD, ROL, DL_SOLVER, BRANCH_AND_BOUND =(MINIMIZER_BIT | OPTIMIZER_BIT | LEASTSQ_BIT),
DEFAULT_POINTS, MINIMUM_POINTS, RECOMMENDED_POINTS, TOTAL_POINTS,
BASE_RESPONSE =0, SIMULATION_RESPONSE, EXPERIMENT_RESPONSE, DEFAULT_DOMAIN =0,
RELAXED_DOMAIN, MIXED_DOMAIN, DEFAULT_CORRECTION = 0, SINGLE_CORRECTION,
FULL_MODEL_FORM_CORRECTION, FULL_SOLUTION_LEVEL_CORRECTION, SEQUENCE_CORRECTION, SETUP_MODEL,
SETUP_USERFUNC, CAUVar_normal = 0, CAUVar_lognormal = 1, CAUVar_uniform = 2,
CAUVar_loguniform = 3, CAUVar_triangular = 4, CAUVar_exponential = 5, CAUVar_beta = 6,
CAUVar_gamma = 7, CAUVar_gumbel = 8, CAUVar_frechet = 9, CAUVar_weibull = 10,
CAUVar_histogram_bin = 11, CAUVar_Nkinds = 12, ANALYTIC_SOLUTION = 1, REORDERED_ANALYTIC_SOLUTION,
R_ONLY_LINEAR_CONSTRAINT, N_VECTOR_LINEAR_CONSTRAINT, R_AND_N_NONLINEAR_CONSTRAINT, N_VECTOR_LINEAR_OBJECTIVE,
FULL_TENSOR, FILTERED_TENSOR, RANDOM_TENSOR, AS_FUNC =1,
AS_GRAD =2, AS_HESS =4, DISALLOW, TARGET,
BOUNDS, SCALE_NONE = 0, SCALE_VALUE = 1, SCALE_LOG = 2,
SCALE_AUTO = 4, APPROX_RESPONSE =1, TRUTH_RESPONSE, TH_SILENT_OUTPUT,
TH_QUIET_OUTPUT, TH_NORMAL_OUTPUT, TH_VERBOSE_OUTPUT, TH_DEBUG_OUTPUT,
DIR_CLEAN, DIR_PERSIST, DIR_ERROR
}
define directory creation options
enum {
MODEL_EVAL_STORE_TOP_METHOD = 0, MODEL_EVAL_STORE_NONE, MODEL_EVAL_STORE_ALL, MODEL_EVAL_STORE_ALL_METHODS,
SYNCHRONOUS_INTERFACE, ASYNCHRONOUS_INTERFACE, SUBMETHOD_DEFAULT =0, SUBMETHOD_NONE,
SUBMETHOD_COLLABORATIVE, SUBMETHOD_EMBEDDED, SUBMETHOD_SEQUENTIAL, SUBMETHOD_LHS,
SUBMETHOD_RANDOM, SUBMETHOD_LOW_DISCREPANCY_SAMPLING, SUBMETHOD_BOX_BEHNKEN, SUBMETHOD_CENTRAL_COMPOSITE,
SUBMETHOD_GRID, SUBMETHOD_OA_LHS, SUBMETHOD_OAS, SUBMETHOD_MFMC,
SUBMETHOD_ACV_IS, SUBMETHOD_ACV_MF, SUBMETHOD_ACV_RD, SUBMETHOD_DREAM,
SUBMETHOD_GPMSA, SUBMETHOD_MUQ, SUBMETHOD_QUESO, SUBMETHOD_WASABI,
SUBMETHOD_CONMIN, SUBMETHOD_DOT, SUBMETHOD_NLPQL, SUBMETHOD_NPSOL,
SUBMETHOD_OPTPP, SUBMETHOD_NPSOL_OPTPP, SUBMETHOD_DIRECT, SUBMETHOD_DIRECT_NPSOL_OPTPP,
SUBMETHOD_DIRECT_NPSOL, SUBMETHOD_DIRECT_OPTPP, SUBMETHOD_EA, SUBMETHOD_EGO,
SUBMETHOD_SBLO, SUBMETHOD_SBGO, SUBMETHOD_AMV_X, SUBMETHOD_AMV_U,
SUBMETHOD_AMV_PLUS_X, SUBMETHOD_AMV_PLUS_U, SUBMETHOD_TANA_X, SUBMETHOD_TANA_U,
SUBMETHOD_QMEA_X, SUBMETHOD_QMEA_U, SUBMETHOD_NO_APPROX, SUBMETHOD_EGRA_X,
SUBMETHOD_EGRA_U, SUBMETHOD_CONVERGE_ORDER, SUBMETHOD_CONVERGE_QOI, SUBMETHOD_ESTIMATE_ORDER,
DEFAULT_SURROGATE_RESP_MODE =0, NO_SURROGATE, UNCORRECTED_SURROGATE, AUTO_CORRECTED_SURROGATE,
BYPASS_SURROGATE, MODEL_DISCREPANCY, AGGREGATED_MODEL_PAIR, AGGREGATED_MODELS,
GENERIC_FNS = 0, OBJECTIVE_FNS, CALIB_TERMS, DEFAULT_VIEW =0,
ALL_VIEW, DESIGN_VIEW, UNCERTAIN_VIEW, ALEATORY_UNCERTAIN_VIEW,
EPISTEMIC_UNCERTAIN_VIEW, STATE_VIEW, DAUIVar_poisson = 0, DAUIVar_binomial = 1,
DAUIVar_negative_binomial = 2, DAUIVar_geometric = 3, DAUIVar_hypergeometric = 4, DAUIVar_histogram_point_int = 5,
DAUIVar_Nkinds = 6, TYPE_U =1, TYPE_B =2, TYPE_E =3,
TYPE_EB =4, CORR_APPROX_RESPONSE =1, UNCORR_APPROX_RESPONSE, CORR_TRUTH_RESPONSE,
UNCORR_TRUTH_RESPONSE, FILEOP_SILENT, FILEOP_WARN, FILEOP_ERROR
}
enum indicating action on failed file operation
Functions
void batch_means_interval (RealMatrix &mcmc_matrix, RealMatrix &interval_matrix, RealMatrix &means_matrix, int moment, Real alpha)
void batch_means_percentile (RealMatrix &mcmc_matrix, RealMatrix &interval_matrix, RealMatrix &means_matrix, Real percentile, Real alpha)
CommandShell & flush (CommandShell &shell)
convenient shell manipulator function to "flush" the shell
template<typename T >
T bitget (T v, int j)
Bit operations are taken from the Stanford Bithack webpage http://www.graphics.stanford.edu/~seander/bithacks.html.
unsigned count_consecutive_trailing_zero_bits (UInt32 v)
Count consecutive trailing zero bits.
UInt32 bitreverse (UInt32 k)
Reverse bits of unsigned 32 bit integer.
UInt64 bitreverse (UInt64 v)
Reverse bits of unsigned 64 bit integer.
template<typename T >
T bitreverse (T v, int s)
Reverse bits of arbitrary unsigned integer.
UInt64 binary2gray (UInt64 v)
Convert binary to Gray code order.
bool ispow2 (unsigned v)
Check if given integer is a power of 2.
template<typename UnsignedArrayType >
UnsignedArrayType matmul_base2 (UnsignedArrayType A, UnsignedArrayType B)
Matrix matrix multiplication in base 2.
void read_sized_data (std::istream &s, RealVectorArray &va, size_t num_rows, int num_cols)
void read_fixed_rowsize_data (std::istream &s, RealVectorArray &va, int num_cols, bool row_major)
void read_unsized_data (std::istream &s, RealVectorArray &va, bool row_major)
void read_config_vars_multifile (const std::string &basename, int num_expts, int ncv, std::vector< Variables > &config_vars)
void read_config_vars_singlefile (const std::string &basename, int num_expts, int ncv, std::vector< Variables > &config_vars)
void read_field_values (const std::string &basename, int expt_num, RealVectorArray &field_vars)
void read_field_values (const std::string &basename, int expt_num, RealVector &field_vars)
void read_coord_values (const std::string &basename, int expt_num, RealMatrix &coords)
void read_coord_values (const std::string &basename, RealMatrix &coords)
void read_covariance (const std::string &basename, int expt_num, RealMatrix &cov_vals)
void read_covariance (const std::string &basename, int expt_num, Dakota::CovarianceMatrix::FORMAT format, int num_vals, RealMatrix &cov_vals)
int count_rows (String file_name)
int count_columns (String file_name)
bool nearby (const RealVector &rv1, const RealVector &rv2, Real rel_tol)
tolerance-based equality operator for RealVector
bool operator== (const ShortArray &dsa1, const ShortArray &dsa2)
equality operator for ShortArray
bool operator== (const StringArray &dsa1, const StringArray &dsa2)
equality operator for StringArray
Real rel_change_L2 (const RealVector &curr_rv, const RealVector &prev_rv)
Computes relative change between RealVectors using Euclidean L2 norm.
Real rel_change_L2 (const RealVector &curr_rv1, const RealVector &prev_rv1, const IntVector &curr_iv, const IntVector &prev_iv, const RealVector &curr_rv2, const RealVector &prev_rv2)
Computes relative change between Real/int/Real vector triples using Euclidean L2 norm.
void compute_col_means (RealMatrix &matrix, RealVector &avg_vals)
Computes means of columns of matrix.
void compute_col_stdevs (RealMatrix &matrix, RealVector &avg_vals, RealVector &std_devs)
Computes standard deviations of columns of matrix.
void compute_col_variances (RealMatrix &matrix, RealVector &avg_vals, RealVector &variances)
Computes variances of columns of matrix.
void sort_vector (const RealVector &vec, RealVector &sort_vec, IntVector &indices)
Sort incoming vector with result and corresponding indices returned in passed arguments.
void sort_matrix_columns (const RealMatrix &mat, RealMatrix &sort_mat, IntMatrix &indices)
Sort incoming matrix columns with result and corresponding indices returned in passed arguments.
void reorder_matrix_columns_from_index_vector (const RealMatrix &mat, RealMatrix &reordered_mat, const IntVector &indices)
Reorders matrix columns according to the passed index vector.
void center_matrix_rows (RealMatrix &mat)
center the incoming matrix rows by their means, in-place
void center_matrix_cols (RealMatrix &mat)
center the incoming matrix columns by their means, in-place
bool is_matrix_symmetric (const RealMatrix &matrix)
Test if incoming matrix is symmetric.
void remove_column (RealMatrix &matrix, int index)
Removes column from matrix.
void copy_data (const MatrixXd &src_mat, RealMatrix &dst_mat)
Copy data from Eigen::MatrixXd to RealMatrix.
void copy_data (const RealMatrix &src_mat, MatrixXd &dst_mat)
Copy data from RealMatrix to Eigen::MatrixXd.
void view_data (const RealMatrix &src_mat, Eigen::Map< MatrixXd > &dst_mat)
Create a view of data in RealMatrix as an Eigen::MatrixXd.
std::vector< std::string > strsplit (const std::string &input)
Trim then split a string on {space, tab} and return as vector of strings.
std::string::size_type longest_strlen (const std::vector< std::string > &vecstr)
Return the length of the longest string in the passed vector.
void iround (const RealVector &input_vec, IntVector &rounded_vec)
round entries of a RealVector yielding an IntVector
bool operator== (const IntArray &dia1, const IntArray &dia2)
equality operator for IntArray
template<typename T >
bool operator== (const std::vector< T > &vec, typename boost::multi_array< T, 1 >::template const_array_view< 1 >::type mav)
equality operator for std::vector and boost::multi_array::const_array_view
template<typename T >
bool operator== (typename boost::multi_array< T, 1 >::template const_array_view< 1 >::type mav, const std::vector< T > &vec)
equality operator for boost::multi_array::const_array_view and std::vector
template<typename T >
bool operator== (const boost::multi_array< T, 1 > &ma, typename boost::multi_array< T, 1 >::template const_array_view< 1 >::type mav)
equality operator for boost::multi_array and boost::multi_array::const_array_view
template<typename T >
bool operator== (typename boost::multi_array< T, 1 >::template const_array_view< 1 >::type mav, const boost::multi_array< T, 1 > &ma)
equality operator for boost::multi_array::const_array_view and boost::multi_array
bool operator!= (const IntArray &dia1, const IntArray &dia2)
inequality operator for IntArray
bool operator!= (const ShortArray &dsa1, const ShortArray &dsa2)
inequality operator for ShortArray
bool operator!= (const StringArray &dsa1, const StringArray &dsa2)
inequality operator for StringArray
template<typename T >
bool operator!= (const std::vector< T > &vec, typename boost::multi_array< T, 1 >::template const_array_view< 1 >::type mav)
inequality operator for std::vector and boost::multi_array::const_array_view
template<typename T >
bool operator!= (typename boost::multi_array< T, 1 >::template const_array_view< 1 >::type mav, const std::vector< T > &vec)
inequality operator for boost::multi_array::const_array_view and std::vector
template<typename T >
bool operator!= (const boost::multi_array< T, 1 > &ma, typename boost::multi_array< T, 1 >::template const_array_view< 1 >::type mav)
inequality operator for boost::multi_array and boost::multi_array::const_array_view
template<typename T >
bool operator!= (typename boost::multi_array< T, 1 >::template const_array_view< 1 >::type mav, const boost::multi_array< T, 1 > &ma)
inequality operator for boost::multi_array::const_array_view and boost::multi_array
template<typename OrdinalType >
bool non_zero (const std::vector< OrdinalType > &vec)
checks for any non-zero value in std::vector(); useful for determining whether an array of request codes (e.g., an ASV) has any actionable content
template<typename VectorType >
bool is_equal_vec (const RealVector &vec1, const VectorType &vec2)
equality function for RealVector and a vector of arbitrary type
template<typename OrdinalType1 , typename OrdinalType2 , typename ScalarType >
bool is_equal_partial (const Teuchos::SerialDenseVector< OrdinalType1, ScalarType > &vec1, const Teuchos::SerialDenseVector< OrdinalType1, ScalarType > &vec2, OrdinalType2 start_index2)
partial equality operator for navigating different views
bool is_equal_partial (const StringMultiArray &ma1, const StringMultiArray &ma2, size_t start_index2)
partial equality operator for navigating different views
template<typename MatrixType , typename VectorType >
void apply_matrix_partial (const MatrixType &M, const VectorType &v1, VectorType &v2)
Applies a RealMatrix to a vector (or subset of vector) v1.
template<typename VectorType >
void apply_matrix_transpose_partial (const RealMatrix &M, const VectorType &v1, VectorType &v2)
Applies transpose of a RealMatrix to a vector (or subset of vector) v1.
std::string strtolower (const std::string &s)
Return lowercase copy of string s.
bool strbegins (const std::string &input, const std::string &test)
Return true if input string begins with string test.
bool strends (const std::string &input, const std::string &test)
Return true if input string ends with string test.
bool strcontains (const std::string &input, const std::string &test)
Return true if input string contains string test.
void build_label (String &label, const String &root_label, size_t tag, const String &separator="")
create a label by appending a numerical tag to the root_label, o
void build_labels (StringArray &label_array, const String &root_label)
create an array of labels by tagging root_label for each entry in label_array. Uses build_label().
void build_labels (StringMultiArray &label_array, const String &root_label)
create an array of labels by tagging root_label for each entry in label_array. Uses build_label().
void build_labels_partial (StringArray &label_array, const String &root_label, size_t start_index, size_t num_items)
create a partial array of labels by tagging root_label for a subset of entries in label_array. Uses build_label().
template<typename vecType , typename valueType >
void assign_value (vecType &target, valueType val)
assign a value to an arbitrary vector
template<typename vecType , typename valueType >
void assign_value (vecType &target, valueType val, size_t start, size_t len)
assign a value to a portion of an arbitrary vector
template<typename OrdinalType , typename ScalarType >
void copy_data (const std::vector< Teuchos::SerialDenseVector< OrdinalType, ScalarType > > &sdva, Teuchos::SerialDenseMatrix< OrdinalType, ScalarType > &sdm)
copy Array<Teuchos::SerialDenseVector<OT,ST> > to Teuchos::SerialDenseMatrix<OT,ST> - used by read_data_tabular - RWH
template<typename OrdinalType , typename ScalarType >
void copy_data_transpose (const std::vector< Teuchos::SerialDenseVector< OrdinalType, ScalarType > > &sdva, Teuchos::SerialDenseMatrix< OrdinalType, ScalarType > &sdm)
copy Array<Teuchos::SerialDenseVector<OT,ST> > to transposed Teuchos::SerialDenseMatrix<OT,ST> - used by read_data_tabular - RWH
template<typename OrdinalType1 , typename OrdinalType2 , typename ScalarType >
void copy_data (const Teuchos::SerialDenseVector< OrdinalType1, ScalarType > &sdv, Teuchos::SerialDenseMatrix< OrdinalType1, ScalarType > &sdm, OrdinalType2 nr, OrdinalType2 nc)
copy Teuchos::SerialDenseVector<OT,ST> to Teuchos::SerialDenseMatrix<OT,ST> - used by NestedModel::update_sub_iterator - RWH
template<typename T >
void copy_data (const std::vector< std::vector< T > > &d2a, std::vector< T > &da)
copy std::vector<vector<T> > to std::vector<T>(unroll vecOfvecs into vector) - used by ProcessApplicInterface::write_parameters_files - RWH
template<typename T >
void copy_data (const std::map< int, T > &im, std::vector< T > &da)
copy map<int, T> to std::vector<T> (discard integer keys) - used by SurrBasedGlobalMinimizer::core_run - RWH
template<typename OrdinalType , typename ScalarType >
void copy_data (const Teuchos::SerialDenseVector< OrdinalType, ScalarType > &sdv1, Teuchos::SerialDenseVector< OrdinalType, ScalarType > &sdv2)
copy Teuchos::SerialDenseVector<OrdinalType, ScalarType> to same (used in place of operator= when a deep copy is required) - used by Response - MSE
template<typename OrdinalType , typename ScalarType >
void copy_data (const Teuchos::SerialDenseMatrix< OrdinalType, ScalarType > &sdm1, Teuchos::SerialDenseMatrix< OrdinalType, ScalarType > &sdm2)
copy Teuchos::SerialDenseMatrix<OrdinalType, ScalarType> to same (used in place of operator= when a deep copy is required) - used by Response - MSE
template<typename OrdinalType , typename ScalarType >
void copy_data (const Teuchos::SerialSymDenseMatrix< OrdinalType, ScalarType > &ssdm1, Teuchos::SerialSymDenseMatrix< OrdinalType, ScalarType > &ssdm2)
copy Teuchos::SerialSymDenseMatrix<OrdinalType, ScalarType> to same (used in place of operator= when a deep copy is required) - used by Response - MSE
void copy_data (const RealMatrix &source, RealMatrix &dest, int num_rows, int num_cols, int start_row=0, int start_col=0)
Taken from pecos/src/MathTools.hpp, BUT not templated because the implementation is specific to RealMatrix.
template<typename OrdinalType , typename ScalarType , typename VecType >
void copy_data (const Teuchos::SerialDenseVector< OrdinalType, ScalarType > &sdv, VecType &vec)
copy Teuchos::SerialDenseVector<OrdinalType, ScalarType> to VecType - used by APPS for HOPS vector types
template<typename OrdinalType , typename ScalarType1 , typename ScalarType2 >
void copy_data (const Teuchos::SerialDenseVector< OrdinalType, ScalarType1 > &sdv, std::vector< ScalarType2 > &vec)
copy Teuchos::SerialDenseVector<OrdinalType, ScalarType> to std::vector<ScalarType> - used by DakotaModel
template<typename OrdinalType , typename ScalarType >
void copy_data (const std::vector< ScalarType > &da, Teuchos::SerialDenseVector< OrdinalType, ScalarType > &sdv)
copy Array<ScalarType> to Teuchos::SerialDenseVector<OrdinalType, ScalarType> - used by NOWPACOptimizer - MSE
template<typename OrdinalType1 , typename OrdinalType2 , typename ScalarType >
void copy_data (const ScalarType *ptr, const OrdinalType2 ptr_len, Teuchos::SerialDenseVector< OrdinalType1, ScalarType > &sdv)
copy ScalarType* to Teuchos::SerialDenseVector<OrdinalType, ScalarType> - used by ScalingModel::response_modify_n2s - RWH
template<typename OrdinalType1 , typename OrdinalType2 , typename ScalarType >
void copy_data (const Teuchos::SerialDenseVector< OrdinalType1, ScalarType > &sdv, ScalarType *ptr, const OrdinalType2 ptr_len)
copy ScalarType* to Teuchos::SerialDenseVector<OrdinalType, ScalarType> - used by NL2SOLLeastSq::core_run - RWH
template<typename OrdinalType , typename ScalarType >
void copy_data (const ScalarType *ptr1, ScalarType *ptr2, const OrdinalType ptr_len)
copy ScalarType* to ScalarType*
template<typename OrdinalType1 , typename OrdinalType2 , typename ScalarType >
void copy_data (const Teuchos::SerialDenseVector< OrdinalType1, ScalarType > &sdv, std::vector< Teuchos::SerialDenseVector< OrdinalType1, ScalarType > > &sdva, OrdinalType2 num_vec, OrdinalType2 vec_len)
copy SerialDenseVector<> to Array<SerialDenseVector<> > - used by ConcurrentMetaIterator constructor - RWH
template<typename vecType1 , typename vecType2 >
void copy_data_partial (const vecType1 &source, size_t source_start_idx, vecType2 &target, size_t target_start_idx, size_t len)
copy a portion arbitrary vector to all of another arbitrary vector
template<typename OrdinalType1 , typename OrdinalType2 , typename ScalarType >
void copy_data_partial (const Teuchos::SerialDenseVector< OrdinalType1, ScalarType > &sdv1, OrdinalType2 start_index1, OrdinalType2 num_items, Teuchos::SerialDenseVector< OrdinalType1, ScalarType > &sdv2)
copy portion of first SerialDenseVector to all of second SerialDenseVector - used by DataTransformModel::vars_mapping - RWH
template<typename OrdinalType1 , typename OrdinalType2 , typename ScalarType >
void copy_data_partial (const Teuchos::SerialDenseVector< OrdinalType1, ScalarType > &sdv1, Teuchos::SerialDenseVector< OrdinalType1, ScalarType > &sdv2, OrdinalType2 start_index2)
copy all of first SerialDenseVector to portion of second SerialDenseVector - used by MixedVariables - RWH, NLSSOLLeastSq - BMA
template<typename OrdinalType1 , typename OrdinalType2 , typename ScalarType >
void copy_data_partial (const Teuchos::SerialDenseVector< OrdinalType1, ScalarType > &sdv1, OrdinalType2 start_index1, OrdinalType2 num_items, Teuchos::SerialDenseVector< OrdinalType1, ScalarType > &sdv2, OrdinalType2 start_index2)
copy portion of first SerialDenseVector to portion of second SerialDenseVector - used by ScalingModel::secondary_resp_scaled2native - RWH
template<typename OrdinalType1 , typename OrdinalType2 , typename ScalarType >
void copy_data_partial (const Teuchos::SerialDenseVector< OrdinalType1, ScalarType > &sdv1, std::vector< ScalarType > &da2, OrdinalType2 start_index2)
copy all of first SerialDenseVector to portion of second SerialDenseVector - used by SharedSurfpackApproxData::merge_variable_arrays - RWH
template<typename T >
void copy_data_partial (const std::vector< T > &da1, size_t start_index1, size_t num_items, std::vector< T > &da2)
copy portion of first Array<T> to all of second Array<T> - used by SharedResponseDataRep constructor - RWH
template<typename T >
void copy_data_partial (const std::vector< T > &da1, std::vector< T > &da2, size_t start_index2)
copy all of first Array<T> to portion of second Array<T> - used by ParamStudy::multidim_loop - RWH
template<typename T >
void copy_data_partial (const std::vector< T > &da, boost::multi_array< T, 1 > &bma, size_t start_index_bma)
copy all of first Array<T> to portion of boost::multi_array<T, 1> - used by RelaxedVariables - RWH
template<typename VectorType >
void copy_column_vector (const RealMatrix &m, RealMatrix::ordinalType j, VectorType &col)
Copies a column of a Teuchos_SerialDenseMatrix<int,Real> to std::vector<Real>
template<typename VectorType >
void copy_row_vector (const RealMatrix &m, RealMatrix::ordinalType i, VectorType &row)
Copies a row of a Teuchos_SerialDenseMatrix<int,Real> to std::vector<Real>
template<typename ScalarType >
void insert_row_vector (const std::vector< ScalarType > &row, RealMatrix::ordinalType i, RealMatrix &m)
Inserts a std::vector<Real> into a row of a Teuchos_SerialDenseMatrix<int,Real>
void merge_data_partial (const IntVector &d_vec, RealVector &m_vec, size_t start_index_ma)
merge a discrete integer vector into a single continuous vector
void merge_data_partial (const IntVector &d_vec, RealArray &m_array, size_t start_index_ma)
merge a discrete integer vector into a single continuous array
template<typename OrdinalType , typename ScalarType >
const ScalarType & set_index_to_value (OrdinalType index, const std::set< ScalarType > &values)
retrieve the set value corresponding to the passed index
template<typename ScalarType >
size_t set_value_to_index (const ScalarType &value, const std::set< ScalarType > &values)
calculate the set index corresponding to the passed value
template<typename OrdinalType , typename KeyType , typename ValueType >
const KeyType & map_index_to_key (OrdinalType index, const std::map< KeyType, ValueType > &pairs)
retrieve the set value corresponding to the passed index
template<typename OrdinalType , typename KeyType , typename ValueType >
const ValueType & map_index_to_value (OrdinalType index, const std::map< KeyType, ValueType > &pairs)
retrieve the set value corresponding to the passed index
template<typename KeyType , typename ValueType >
void map_keys_to_set (const std::map< KeyType, ValueType > &source_map, std::set< KeyType > &target_set)
calculate the map index corresponding to the passed key
template<typename KeyType , typename ValueType >
size_t map_key_to_index (const KeyType &key, const std::map< KeyType, ValueType > &pairs)
calculate the map index corresponding to the passed key
template<typename KeyType , typename ValueType >
size_t map_value_to_index (const ValueType &value, const std::map< KeyType, ValueType > &pairs)
calculate the map index corresponding to the passed value (not the key)
template<typename KeyType , typename ValueType >
size_t map_value_to_index (const ValueType &value, const std::multimap< KeyType, ValueType > &pairs)
calculate the map index corresponding to the passed value (not the key)
template<typename OrdinalType , typename ScalarType >
void x_y_pairs_to_x_set (const Teuchos::SerialDenseVector< OrdinalType, ScalarType > &xy_pairs, std::set< ScalarType > &x_set)
convert a SerialDenseVector of head-to-tail (x,y) pairs into a std::set of (x), discarding the y values
template<typename ScalarType >
ScalarType find_min (const std::vector< ScalarType > &vec)
template<typename OrdinalType , typename ScalarType >
ScalarType find_min (const std::vector< ScalarType > &vec, OrdinalType start, OrdinalType end)
template<typename OrdinalType , typename ScalarType >
ScalarType find_min (const Teuchos::SerialDenseVector< OrdinalType, ScalarType > &vec)
template<typename OrdinalType , typename ScalarType >
ScalarType find_min (const ScalarType *vec, OrdinalType len)
template<typename ScalarType >
ScalarType find_max (const std::vector< ScalarType > &vec)
template<typename OrdinalType , typename ScalarType >
ScalarType find_max (const Teuchos::SerialDenseVector< OrdinalType, ScalarType > &vec)
template<typename OrdinalType , typename ScalarType >
ScalarType find_max (const ScalarType *vec, const OrdinalType len)
template<typename ContainerType >
size_t find_index (const ContainerType &c, const typename ContainerType::value_type &search_data)
generic find_index (inactive)
template<typename T >
size_t find_index (const boost::multi_array< T, 1 > &bma, const T &search_data)
compute the index of an entry within a boost::multi_array
size_t find_index (SizetMultiArrayConstView bmacv, size_t search_data)
compute the index of an entry within a boost::multi_array view
size_t find_index (StringMultiArrayConstView bmacv, const String &search_data)
compute the index of an entry within a boost::multi_array view
template<typename ListT >
size_t find_index (const ListT &l, const typename ListT::value_type &val)
compute the index of an entry within a std::list
template<typename ListT >
ListT::const_iterator find_if (const ListT &c, bool(*test_fn)(const typename ListT::value_type &, const std::string &), const std::string &test_fn_data)
return an iterator to the first list element satisfying the predicate test_fn w.r.t. the passed test_fn_data; end if not found
template<typename VectorType , typename ScalarType >
void copy_data (const std::vector< VectorType > &va, ScalarType *ptr, int ptr_len)
void copy_data (SizetMultiArrayConstView ma, SizetArray &da)
copy boost::multi_array view to Array - used by ActiveSet::derivative_vector - RWH
void copy_data (StringMultiArrayConstView ma, StringArray &da)
copy boost::multi_array view to Array - used by Pecos::copy_data - RWH
template<typename DakContainerType >
bool contains (const DakContainerType &v, const typename DakContainerType::value_type &val)
return true if the item val appears in container v
template<class RandomIt , class URBG >
void rand_shuffle (RandomIt first, RandomIt last, URBG &&g)
Random shuffle with C++17 shuffle API, but using Boost for portability.
void abort_handler (int code)
global function which handles serial or parallel aborts
void abort_throw_or_exit (int dakota_code)
throw or exit depending on abort_mode
void register_signal_handlers ()
Tie various signal handlers to Dakota's abort_handler function.
void mpi_debug_hold ()
Global function to hold Dakota processes to help with MPI debugging.
template<typename T >
T abort_handler_t (int code)
void svd (RealMatrix &matrix, RealVector &singular_vals, RealMatrix &v_trans, bool compute_vectors=true)
Compute the SVD of an arbitrary matrix A = USV^T.
void singular_values (RealMatrix &matrix, RealVector &singular_values)
compute the singular values without storing any singular vectors (A will be destroyed)
int qr (RealMatrix &A)
Compute an in-place QR factorization A = QR.
int qr_rsolve (const RealMatrix &q_r, bool transpose, RealMatrix &rhs)
Perform a multiple right-hand sides Rinv * rhs solve using the R from a qr factorization.
double det_AtransA (RealMatrix &A)
Use SVD to compute det(A'*A), destroying A with the SVD.
std::string string_to_tmpfile (const std::string &dump_string)
utility to write an input string to a tmpfile in PWD
std::string pyprepro_input (const std::string &template_file, const std::string &preproc_cmd="pyprepro.py")
run pyprepro on the user-provided input file and return generated tmp output
ResultsKeyType make_key (const StrStrSizet &iterator_id, const std::string &data_name)
Make a full ResultsKeyType from the passed iterator_id and data_name.
MetaDataValueType make_metadatavalue (StringMultiArrayConstView labels)
create MetaDataValueType from the passed strings
MetaDataValueType make_metadatavalue (StringMultiArrayConstView cv_labels, StringMultiArrayConstView div_labels, StringMultiArrayConstView drv_labels, const StringArray &resp_labels)
create MetaDataValueType from the passed strings
MetaDataValueType make_metadatavalue (const StringArray &resp_labels)
create MetaDataValueType from the passed strings
MetaDataValueType make_metadatavalue (const std::string &)
create MetaDataValueType from the passed strings
MetaDataValueType make_metadatavalue (const std::string &, const std::string &)
create MetaDataValueType from the passed strings
MetaDataValueType make_metadatavalue (const std::string &, const std::string &, const std::string &)
create MetaDataValueType from the passed strings
MetaDataValueType make_metadatavalue (const std::string &, const std::string &, const std::string &, const std::string &)
create MetaDataValueType from the passed strings
MetaDataValueType make_metadatavalue (StringMultiArrayConstView cv_labels, StringMultiArrayConstView div_labels, StringMultiArrayConstView dsv_labels, StringMultiArrayConstView drv_labels, const StringArray &resp_labels)
int generate_system_seed ()
clock microseconds-based random seed in [1, 1000000]
void compute_regression_coeffs (const RealMatrix &samples, const RealMatrix &resps, RealMatrix &coeffs, RealVector &cods)
Compute (non-standardized) linear regression coefficients and return R^2.
void compute_std_regression_coeffs (const RealMatrix &samples, const RealMatrix &resps, RealMatrix &coeffs, RealVector &cods)
Compute standardized linear regression coefficients.
std::istream & operator>> (std::istream &s, ActiveSet &set)
std::istream extraction operator for ActiveSet. Calls read(std::istream&).
std::ostream & operator<< (std::ostream &s, const ActiveSet &set)
std::ostream insertion operator for ActiveSet. Calls write(std::istream&).
MPIUnpackBuffer & operator>> (MPIUnpackBuffer &s, ActiveSet &set)
MPIUnpackBuffer extraction operator for ActiveSet. Calls read(MPIUnpackBuffer&).
MPIPackBuffer & operator<< (MPIPackBuffer &s, const ActiveSet &set)
MPIPackBuffer insertion operator for ActiveSet. Calls write(MPIPackBuffer&).
bool operator!= (const ActiveSet &set1, const ActiveSet &set2)
inequality operator for ActiveSet
std::istream & operator>> (std::istream &s, Constraints &con)
std::istream extraction operator for Constraints
std::ostream & operator<< (std::ostream &s, const Constraints &con)
std::ostream insertion operator for Constraints
std::string re_match (const std::string &token, const boost::regex &re)
Global utility function to ease migration from CtelRegExp to Boost.Regex.
bool interface_id_compare (const Interface &interface_in, const void *id)
global comparison function for Interface
bool method_id_compare (const Iterator &iterator, const void *id)
global comparison function for Iterator
bool model_id_compare (const Model &model, const void *id)
global comparison function for Model
bool operator== (const Model &m1, const Model &m2)
equality operator for Envelope is true if same letter instance
bool operator!= (const Model &m1, const Model &m2)
inequality operator for Envelope is true if different letter instance
template<typename VecT >
void get_initial_values (const Model &model, VecT &values)
template<typename VecT >
bool get_bounds (const RealVector &lower_source, const RealVector &upper_source, VecT &lower_target, VecT &upper_target, Real big_real_bound_size, Real no_value)
template<typename VecT >
void get_bounds (const Model &model, VecT &lower_target, VecT &upper_target)
template<typename SetT , typename VecT >
void get_bounds (const SetT &source_set, VecT &lower_target, VecT &upper_target, int target_offset)
template<typename OrdinalType , typename ScalarType , typename VectorType2 , typename MaskType , typename SetArray >
bool get_mixed_bounds (const MaskType &mask_set, const SetArray &source_set, const Teuchos::SerialDenseVector< OrdinalType, ScalarType > &lower_source, const Teuchos::SerialDenseVector< OrdinalType, ScalarType > &upper_source, VectorType2 &lower_target, VectorType2 &upper_target, ScalarType bigBoundSize, ScalarType no_value, int target_offset=0)
template<typename AdapterT >
bool get_variable_bounds (Model &model, Real big_real_bound_size, int big_int_bound_size, typename AdapterT::VecT &lower, typename AdapterT::VecT &upper)
template<typename RVecT , typename IVecT >
int configure_inequality_constraint_maps (const Model &model, Real big_real_bound_size, CONSTRAINT_TYPE ctype, IVecT &map_indices, RVecT &map_multipliers, RVecT &map_offsets, Real scaling=1.0)
template<typename RVecT , typename IVecT >
void configure_equality_constraint_maps (Model &model, CONSTRAINT_TYPE ctype, IVecT &indices, size_t index_offset, RVecT &multipliers, RVecT &values, bool make_one_sided)
template<typename AdapterT >
void get_linear_constraints (Model &model, Real big_real_bound_size, typename AdapterT::VecT &lin_ineq_lower_bnds, typename AdapterT::VecT &lin_ineq_upper_bnds, typename AdapterT::VecT &lin_eq_targets, typename AdapterT::MatT &lin_ineq_coeffs, typename AdapterT::MatT &lin_eq_coeffs)
template<typename VecT >
void apply_linear_constraints (const Model &model, CONSTRAINT_EQUALITY_TYPE etype, const VecT &in_vals, VecT &values, bool adjoint=false)
template<typename VecT >
void apply_nonlinear_constraints (const Model &model, CONSTRAINT_EQUALITY_TYPE etype, const VecT &in_vals, VecT &values, bool adjoint=false)
template<typename VectorType1 , typename VectorType2 , typename SetArray >
void copy_variables (const VectorType1 &source, const BitArray &set_bits, const SetArray &set_vars, VectorType2 &dest, size_t offset, size_t len)
template<typename VectorType1 , typename VectorType2 , typename SetArray >
void copy_variables (const VectorType1 &source, const SetArray &set_vars, VectorType2 &dest, size_t offset, size_t len)
template<typename VectorType1 , typename VectorType2 >
void copy_variables (const VectorType1 &source, VectorType2 &dest, const BitArray &int_set_bits, const IntSetArray &set_int_vars, size_t offset, size_t len)
template<typename AdapterT >
void set_best_responses (typename AdapterT::OptT &optimizer, const Model &model, bool set_objectives, size_t num_user_primary_fns, const std::vector< int > constraint_map_indices, const std::vector< double > constraint_map_multipliers, const std::vector< double > constraint_map_offsets, ResponseArray &response_array)
template<typename VectorType >
void set_variables (const VectorType &source, Model &model, Variables &vars)
template<typename VectorType >
void get_variables (Model &model, VectorType &vec)
template<typename vectorType >
void get_responses (const Model &model, const RealVector &dak_fn_vals, const std::vector< int > constraint_map_indices, const std::vector< double > constraint_map_multipliers, const std::vector< double > constraint_map_offsets, vectorType &f_vec, vectorType &cEqs_vec, vectorType &cIneqs_vec)
template<typename VecT >
void get_nonlinear_eq_constraints (const Model &model, VecT &values, Real scale, int offset=-1)
template<typename VecT >
void get_nonlinear_eq_constraints (Model &model, const RealVector &curr_resp_vals, VecT &values, Real scale, int offset=0)
template<typename VecT >
void get_nonlinear_ineq_constraints (const Model &model, VecT &values)
template<typename VecT >
void get_nonlinear_bounds (Model &model, VecT &nonlin_ineq_lower, VecT &nonlin_ineq_upper, VecT &nonlin_eq_targets)
Would like to combine the previous adapter with this one (based on APPSOptimizer and COLINOptimizer) and then see how much more generalization is needed to support other TPLs like JEGA.
bool responses_id_compare (const Response &resp, const void *id)
global comparison function for Response
std::istream & operator>> (std::istream &s, Response &response)
std::istream extraction operator for Response. Calls read(std::istream&).
std::ostream & operator<< (std::ostream &s, const Response &response)
std::ostream insertion operator for Response. Calls write(std::ostream&).
MPIUnpackBuffer & operator>> (MPIUnpackBuffer &s, Response &response)
MPIUnpackBuffer extraction operator for Response. Calls read(MPIUnpackBuffer&).
MPIPackBuffer & operator<< (MPIPackBuffer &s, const Response &response)
MPIPackBuffer insertion operator for Response. Calls write(MPIPackBuffer&).
bool operator!= (const Response &resp1, const Response &resp2)
inequality operator for Response
void set_model_gp_options (Model &model, const String &options_file)
bool variables_id_compare (const Variables &vars, const void *id)
global comparison function for Variables
std::istream & operator>> (std::istream &s, Variables &vars)
std::istream extraction operator for Variables.
std::ostream & operator<< (std::ostream &s, const Variables &vars)
std::ostream insertion operator for Variables.
MPIUnpackBuffer & operator>> (MPIUnpackBuffer &s, Variables &vars)
MPIUnpackBuffer extraction operator for Variables.
MPIPackBuffer & operator<< (MPIPackBuffer &s, const Variables &vars)
MPIPackBuffer insertion operator for Variables.
bool operator!= (const Variables &vars1, const Variables &vars2)
inequality operator for Variables
template<typename OrdinalType , typename ScalarType1 , typename ScalarType2 , typename ScalarType3 , typename ScalarType4 >
void write_ordered (std::ostream &s, const SizetArray &comp_totals, const Teuchos::SerialDenseVector< OrdinalType, ScalarType1 > &c_vector, const Teuchos::SerialDenseVector< OrdinalType, ScalarType2 > &di_vector, const Teuchos::SerialDenseVector< OrdinalType, ScalarType3 > &ds_vector, const Teuchos::SerialDenseVector< OrdinalType, ScalarType4 > &dr_vector)
free function to write Variables data vectors in input spec ordering
template<typename OrdinalType , typename ScalarType1 , typename ScalarType2 , typename ScalarType3 , typename ScalarType4 >
void write_ordered (std::ostream &s, const SizetArray &comp_totals, const Teuchos::SerialDenseVector< OrdinalType, ScalarType1 > &c_vector, const Teuchos::SerialDenseVector< OrdinalType, ScalarType2 > &di_vector, const boost::multi_array< ScalarType3, 1 > &ds_array, const Teuchos::SerialDenseVector< OrdinalType, ScalarType4 > &dr_vector)
free function to write Variables data vectors in input spec ordering
template<typename ScalarType >
void write_ordered (std::ostream &s, const SizetArray &comp_totals, const std::vector< ScalarType > &c_array, const std::vector< ScalarType > &di_array, const std::vector< ScalarType > &ds_array, const std::vector< ScalarType > &dr_array)
free function to write Variables data vectors in input spec ordering
void size_and_fill (const SharedVariablesData &svd, size_t array_size, VariablesArray &vars_array)
Reinitialize var_array to contain array_size freshly constructed Variables, sharing provided SVD.
MPIPackBuffer & operator<< (MPIPackBuffer &s, const DataEnvironment &data)
MPIPackBuffer insertion operator for DataEnvironment.
MPIUnpackBuffer & operator>> (MPIUnpackBuffer &s, DataEnvironment &data)
MPIUnpackBuffer extraction operator for DataEnvironment.
std::ostream & operator<< (std::ostream &s, const DataEnvironment &data)
std::ostream insertion operator for DataEnvironment
String interface_enum_to_string (unsigned short interface_type)
MPIPackBuffer & operator<< (MPIPackBuffer &s, const DataInterface &data)
MPIPackBuffer insertion operator for DataInterface.
MPIUnpackBuffer & operator>> (MPIUnpackBuffer &s, DataInterface &data)
MPIUnpackBuffer extraction operator for DataInterface.
std::ostream & operator<< (std::ostream &s, const DataInterface &data)
std::ostream insertion operator for DataInterface
MPIPackBuffer & operator<< (MPIPackBuffer &s, const DataMethod &data)
MPIPackBuffer insertion operator for DataMethod.
MPIUnpackBuffer & operator>> (MPIUnpackBuffer &s, DataMethod &data)
MPIUnpackBuffer extraction operator for DataMethod.
std::ostream & operator<< (std::ostream &s, const DataMethod &data)
std::ostream insertion operator for DataMethod
MPIPackBuffer & operator<< (MPIPackBuffer &s, const DataModel &data)
MPIPackBuffer insertion operator for DataModel.
MPIUnpackBuffer & operator>> (MPIUnpackBuffer &s, DataModel &data)
MPIUnpackBuffer extraction operator for DataModel.
std::ostream & operator<< (std::ostream &s, const DataModel &data)
std::ostream insertion operator for DataModel
MPIPackBuffer & operator<< (MPIPackBuffer &s, const DataResponses &data)
MPIPackBuffer insertion operator for DataResponses.
MPIUnpackBuffer & operator>> (MPIUnpackBuffer &s, DataResponses &data)
MPIUnpackBuffer extraction operator for DataResponses.
std::ostream & operator<< (std::ostream &s, const DataResponses &data)
std::ostream insertion operator for DataResponses
MPIPackBuffer & operator<< (MPIPackBuffer &s, const DataVariables &data)
MPIPackBuffer insertion operator for DataVariables.
MPIUnpackBuffer & operator>> (MPIUnpackBuffer &s, DataVariables &data)
MPIUnpackBuffer extraction operator for DataVariables.
std::ostream & operator<< (std::ostream &s, const DataVariables &data)
std::ostream insertion operator for DataVariables
int dlsolver_option (Opt_Info *)
RealVector const * continuous_lower_bounds (Optimizer1 *o)
RealVector const * continuous_upper_bounds (Optimizer1 *o)
RealVector const * nonlinear_ineq_constraint_lower_bounds (Optimizer1 *o)
RealVector const * nonlinear_ineq_constraint_upper_bounds (Optimizer1 *o)
RealVector const * nonlinear_eq_constraint_targets (Optimizer1 *o)
RealVector const * linear_ineq_constraint_lower_bounds (Optimizer1 *o)
RealVector const * linear_ineq_constraint_upper_bounds (Optimizer1 *o)
RealVector const * linear_eq_constraint_targets (Optimizer1 *o)
RealMatrix const * linear_ineq_constraint_coeffs (Optimizer1 *o)
RealMatrix const * linear_eq_constraint_coeffs (Optimizer1 *o)
void ComputeResponses (Optimizer1 *o, int mode, int n, double *x)
void GetFuncs (Optimizer1 *o, int m0, int m1, double *f)
void GetGrads (Optimizer1 *o, int m0, int m1, int n, int is, int js, double *g)
void GetContVars (Optimizer1 *o, int n, double *x)
void SetBestContVars (Optimizer1 *o, int n, double *x)
void SetBestRespFns (Optimizer1 *o, int n, double *x)
void * dl_constructor (Optimizer1 *, Dakota_funcs *, dl_core_run_t *, dl_destructor_t *)
static RealVector const * continuous_lower_bounds1 (Optimizer1 *o)
static RealVector const * continuous_upper_bounds1 (Optimizer1 *o)
static RealVector const * nonlinear_ineq_constraint_lower_bounds1 (Optimizer1 *o)
static RealVector const * nonlinear_ineq_constraint_upper_bounds1 (Optimizer1 *o)
static RealVector const * nonlinear_eq_constraint_targets1 (Optimizer1 *o)
static RealVector const * linear_ineq_constraint_lower_bounds1 (Optimizer1 *o)
static RealVector const * linear_ineq_constraint_upper_bounds1 (Optimizer1 *o)
static RealVector const * linear_eq_constraint_targets1 (Optimizer1 *o)
static RealMatrix const * linear_eq_constraint_coeffs1 (Optimizer1 *o)
static RealMatrix const * linear_ineq_constraint_coeffs1 (Optimizer1 *o)
static void ComputeResponses1 (Optimizer1 *o, int mode, int n, double *x)
static void GetFuncs1 (Optimizer1 *o, int m0, int m1, double *f)
static void GetGrads1 (Optimizer1 *o, int m0, int m1, int n, int is, int js, double *g)
static void GetContVars1 (Optimizer1 *o, int n, double *x)
static void SetBestContVars1 (Optimizer1 *o, int n, double *x)
static void SetBestDiscVars1 (Optimizer1 *o, int n, int *x)
static void SetBestRespFns1 (Optimizer1 *o, int n, double *x)
static double Get_Real1 (Optimizer1 *o, const char *name)
static int Get_Int1 (Optimizer1 *o, const char *name)
static bool Get_Bool1 (Optimizer1 *o, const char *name)
DOTOptimizer * new_DOTOptimizer (ProblemDescDB &problem_db)
DOTOptimizer * new_DOTOptimizer (Model &model)
DOTOptimizer * new_DOTOptimizer (ProblemDescDB &problem_db, Model &model)
void copy_field_data (const RealVector &fn_vals, RealMatrix &fn_grad, const RealSymMatrixArray &fn_hess, size_t offset, size_t num_fns, Response &response)
void copy_field_data (const RealVector &fn_vals, RealMatrix &fn_grad, const RealSymMatrixArray &fn_hess, size_t offset, size_t num_fns, short total_asv, Response &response)
void interpolate_simulation_field_data (const Response &sim_resp, const RealMatrix &exp_coords, size_t field_num, short total_asv, size_t interp_resp_offset, Response &interp_resp)
void linear_interpolate_1d (const RealMatrix &build_pts, const RealVector &build_vals, const RealMatrix &build_grads, const RealSymMatrixArray &build_hessians, const RealMatrix &pred_pts, RealVector &pred_vals, RealMatrix &pred_grads, RealSymMatrixArray &pred_hessians)
Returns the value of at 1D function f and its gradient and hessians (if available) at the points of vector pred_pts using linear interpolation. The vector build_pts specifies the coordinates of the underlying interval at which the values (build_vals) of the function f are known. The length of output pred_vals is equal to the length of pred_pts. This function assumes the build_pts is in ascending order.
void symmetric_eigenvalue_decomposition (const RealSymMatrix &matrix, RealVector &eigenvalues, RealMatrix &eigenvectors)
Computes the eigenvalues and, optionally, eigenvectors of a real symmetric matrix A.
template<typename O , typename T >
int binary_search (T target, Teuchos::SerialDenseVector< O, T > &data)
find the interval containing a target value. This function assumes the data is in ascending order.
Real getdist (const RealVector &x1, const RealVector &x2)
Real mindist (const RealVector &x, const RealMatrix &xset, int except)
Real mindistindx (const RealVector &x, const RealMatrix &xset, const IntArray &indx)
Real getRmax (const RealMatrix &xset)
int start_grid_computing (char *analysis_driver_script, char *params_file, char *results_file)
int stop_grid_computing ()
int perform_analysis (char *iteration_num)
int length (const StringMultiArrayConstView &vec)
Return the length of a StringMultiArrayConstView.
H5::DataType h5_file_dtype (const short &)
Return the HDF5 datatype to store a short.
H5::DataType h5_file_dtype (const int &)
Return the HDF5 datatype to store a int.
H5::DataType h5_file_dtype (const unsigned int &)
H5::DataType h5_file_dtype (const unsigned long &)
H5::DataType h5_file_dtype (const unsigned long long &)
H5::DataType h5_file_dtype (const Real &)
Return the HDF5 datatype to store a Real.
H5::DataType h5_file_dtype (const char *)
Return the HDF5 datatype to store a string.
H5::DataType h5_file_dtype (const ResultsOutputType t)
Overloads for ResultsOutputType (used when creating empty datasets)
H5::DataType h5_file_dtype (const String &)
Return the HDF5 datatype to store a string.
H5::DataType h5_mem_dtype (const Real &)
Return the HDF5 datatype to read a Real in memory.
H5::DataType h5_mem_dtype (const short &)
Return the HDF5 datatype to read a short in memory.
H5::DataType h5_mem_dtype (const int &)
Return the HDF5 datatype to read an int in memory.
H5::DataType h5_mem_dtype (const unsigned int &)
Return the HDF5 datatype to read an unsigned int in memory.
H5::DataType h5_mem_dtype (const unsigned long &)
Return the HDF5 datatype to read an unsigned long (maybe a size_t) in memory.
H5::DataType h5_mem_dtype (const unsigned long long &)
Return the HDF5 datatype to read an unsigned long long (maybe a size_t) in memory.
H5::DataType h5_mem_dtype (const char *)
Return the HDF5 datatype to read a string in memory.
H5::DataType h5_mem_dtype (const String &)
Return the HDF5 datatype to read a string in memory.
H5::DataType h5_mem_dtype (const ResultsOutputType t)
Overloads for ResultsOutputType (used when creating empty datasets)
template<typename T >
int length (const std::vector< T > &vec)
Return the length of seeral types.
template<typename T >
int length (const Teuchos::SerialDenseVector< int, T > &vec)
Return the length of an SDV.
template<typename T >
std::vector< const char * > pointers_to_strings (const T &data)
Return a vector of pointers to strings.
template<typename T >
string asstring (const T &val)
Creates a string from the argument val using an ostringstream.
PACKBUF (int, MPI_INT) PACKBUF(u_int
MPI_UNSIGNED PACKBUF (long, MPI_LONG) PACKBUF(u_long
MPI_UNSIGNED MPI_UNSIGNED_LONG PACKBUF (long long, MPI_LONG_LONG) PACKBUF(unsigned long long
MPI_UNSIGNED MPI_UNSIGNED_LONG MPI_UNSIGNED_LONG_LONG PACKBUF (short, MPI_SHORT) PACKBUF(u_short
MPI_UNSIGNED MPI_UNSIGNED_LONG MPI_UNSIGNED_LONG_LONG MPI_UNSIGNED_SHORT PACKBUF (char, MPI_CHAR) PACKBUF(u_char
MPI_UNSIGNED MPI_UNSIGNED_LONG MPI_UNSIGNED_LONG_LONG MPI_UNSIGNED_SHORT MPI_UNSIGNED_CHAR PACKBUF (double, MPI_DOUBLE) PACKBUF(float
UNPACKBUF (int, MPI_INT) UNPACKBUF(u_int
MPI_UNSIGNED UNPACKBUF (long, MPI_LONG) UNPACKBUF(u_long
MPI_UNSIGNED MPI_UNSIGNED_LONG UNPACKBUF (long long, MPI_LONG_LONG) UNPACKBUF(unsigned long long
MPI_UNSIGNED MPI_UNSIGNED_LONG MPI_UNSIGNED_LONG_LONG UNPACKBUF (short, MPI_SHORT) UNPACKBUF(u_short
MPI_UNSIGNED MPI_UNSIGNED_LONG MPI_UNSIGNED_LONG_LONG MPI_UNSIGNED_SHORT UNPACKBUF (char, MPI_CHAR) UNPACKBUF(u_char
MPI_UNSIGNED MPI_UNSIGNED_LONG MPI_UNSIGNED_LONG_LONG MPI_UNSIGNED_SHORT MPI_UNSIGNED_CHAR UNPACKBUF (double, MPI_DOUBLE) UNPACKBUF(float
PACKSIZE (int, MPI_INT) PACKSIZE(u_int
MPI_UNSIGNED PACKSIZE (long, MPI_LONG) PACKSIZE(u_long
MPI_UNSIGNED MPI_UNSIGNED_LONG PACKSIZE (long long, MPI_LONG_LONG) PACKSIZE(unsigned long long
MPI_UNSIGNED MPI_UNSIGNED_LONG MPI_UNSIGNED_LONG_LONG PACKSIZE (short, MPI_SHORT) PACKSIZE(u_short
MPI_UNSIGNED MPI_UNSIGNED_LONG MPI_UNSIGNED_LONG_LONG MPI_UNSIGNED_SHORT PACKSIZE (char, MPI_CHAR) PACKSIZE(u_char
MPI_UNSIGNED MPI_UNSIGNED_LONG MPI_UNSIGNED_LONG_LONG MPI_UNSIGNED_SHORT MPI_UNSIGNED_CHAR PACKSIZE (double, MPI_DOUBLE) PACKSIZE(float
MPI_UNSIGNED MPI_UNSIGNED_LONG MPI_UNSIGNED_LONG_LONG MPI_UNSIGNED_SHORT MPI_UNSIGNED_CHAR MPI_FLOAT int MPIPackSize (const bool &data, const int num=1)
return packed size of a bool
MPIPackBuffer & operator<< (MPIPackBuffer &buff, const int &data)
insert an int
MPIPackBuffer & operator<< (MPIPackBuffer &buff, const u_int &data)
insert a u_int
MPIPackBuffer & operator<< (MPIPackBuffer &buff, const long &data)
insert a long
MPIPackBuffer & operator<< (MPIPackBuffer &buff, const u_long &data)
insert a u_long
MPIPackBuffer & operator<< (MPIPackBuffer &buff, const long long &data)
insert a long long
MPIPackBuffer & operator<< (MPIPackBuffer &buff, const unsigned long long &data)
insert a unsigned long long
MPIPackBuffer & operator<< (MPIPackBuffer &buff, const short &data)
insert a short
MPIPackBuffer & operator<< (MPIPackBuffer &buff, const u_short &data)
insert a u_short
MPIPackBuffer & operator<< (MPIPackBuffer &buff, const char &data)
insert a char
MPIPackBuffer & operator<< (MPIPackBuffer &buff, const u_char &data)
insert a u_char
MPIPackBuffer & operator<< (MPIPackBuffer &buff, const double &data)
insert a double
MPIPackBuffer & operator<< (MPIPackBuffer &buff, const float &data)
insert a float
MPIPackBuffer & operator<< (MPIPackBuffer &buff, const bool &data)
insert a bool
MPIUnpackBuffer & operator>> (MPIUnpackBuffer &buff, int &data)
extract an int
MPIUnpackBuffer & operator>> (MPIUnpackBuffer &buff, u_int &data)
extract a u_int
MPIUnpackBuffer & operator>> (MPIUnpackBuffer &buff, long &data)
extract a long
MPIUnpackBuffer & operator>> (MPIUnpackBuffer &buff, u_long &data)
extract a u_long
MPIUnpackBuffer & operator>> (MPIUnpackBuffer &buff, long long &data)
extract a long long
MPIUnpackBuffer & operator>> (MPIUnpackBuffer &buff, unsigned long long &data)
extract an unsigned long long
MPIUnpackBuffer & operator>> (MPIUnpackBuffer &buff, short &data)
extract a short
MPIUnpackBuffer & operator>> (MPIUnpackBuffer &buff, u_short &data)
extract a u_short
MPIUnpackBuffer & operator>> (MPIUnpackBuffer &buff, char &data)
extract a char
MPIUnpackBuffer & operator>> (MPIUnpackBuffer &buff, u_char &data)
extract a u_char
MPIUnpackBuffer & operator>> (MPIUnpackBuffer &buff, double &data)
extract a double
MPIUnpackBuffer & operator>> (MPIUnpackBuffer &buff, float &data)
extract a float
MPIUnpackBuffer & operator>> (MPIUnpackBuffer &buff, bool &data)
extract a bool
int MPIPackSize (const int &data, const int num=1)
return packed size of an int
int MPIPackSize (const u_int &data, const int num=1)
return packed size of a u_int
int MPIPackSize (const long &data, const int num=1)
return packed size of a long
int MPIPackSize (const u_long &data, const int num=1)
return packed size of a u_long
int MPIPackSize (const long long &data, const int num=1)
return packed size of a long long
int MPIPackSize (const unsigned long long &data, const int num=1)
return packed size of an unsigned long long
int MPIPackSize (const short &data, const int num=1)
return packed size of a short
int MPIPackSize (const u_short &data, const int num=1)
return packed size of a u_short
int MPIPackSize (const char &data, const int num=1)
return packed size of a char
int MPIPackSize (const u_char &data, const int num=1)
return packed size of a u_char
int MPIPackSize (const double &data, const int num=1)
return packed size of a double
int MPIPackSize (const float &data, const int num=1)
return packed size of a float
int nidr_parse (const char *, FILE *)
const char ** arg_list_adjust (const char **, void **)
int not_executable (const char *driver_name, const char *tdir)
static void scale_chk (StringArray &ST, RealVector &S, const char *what, const char **univ)
static void BuildLabels (StringArray *sa, size_t nsa, size_t n1, size_t n2, const char *stub)
static int mixed_check (IntSet *S, int n, IntArray *iv, const char *what)
static void mixed_check2 (size_t n, IntArray *iv, const char *what)
static int wronglen (size_t n, RealVector *V, const char *what)
static int wronglen (size_t n, IntVector *V, const char *what)
static void Vcopyup (RealVector *V, RealVector *M, size_t i, size_t n)
static void Set_rv (RealVector *V, double d, size_t n)
static void Set_iv (IntVector *V, int d, size_t n)
static void wrong_number (const char *what, const char *kind, size_t nsv, size_t m)
static void too_small (const char *kind)
static void not_div (const char *kind, size_t nsv, size_t m)
static void suppressed (const char *kind, int ndup, int *ip, String *sp, Real *rp)
static void bad_initial_ivalue (const char *kind, int val)
static void bad_initial_svalue (const char *kind, String val)
static void bad_initial_rvalue (const char *kind, Real val)
static void Vgen_ContinuousDes (DataVariablesRep *dv, size_t offset)
static void Vgen_DiscreteDesRange (DataVariablesRep *dv, size_t offset)
static void Vgen_ContinuousState (DataVariablesRep *dv, size_t offset)
static void Vgen_DiscreteStateRange (DataVariablesRep *dv, size_t offset)
static void Vchk_NormalUnc (DataVariablesRep *dv, size_t offset, Var_Info *vi)
static void Vgen_NormalUnc (DataVariablesRep *dv, size_t offset)
static void Vchk_LognormalUnc (DataVariablesRep *dv, size_t offset, Var_Info *vi)
static void Vgen_LognormalUnc (DataVariablesRep *dv, size_t offset)
static void Vchk_UniformUnc (DataVariablesRep *dv, size_t offset, Var_Info *vi)
static void Vgen_UniformUnc (DataVariablesRep *dv, size_t offset)
static void Vchk_LoguniformUnc (DataVariablesRep *dv, size_t offset, Var_Info *vi)
static void Vgen_LoguniformUnc (DataVariablesRep *dv, size_t offset)
static void Vchk_TriangularUnc (DataVariablesRep *dv, size_t offset, Var_Info *vi)
static void Vgen_TriangularUnc (DataVariablesRep *dv, size_t offset)
static void Vchk_ExponentialUnc (DataVariablesRep *dv, size_t offset, Var_Info *vi)
static void Vgen_ExponentialUnc (DataVariablesRep *dv, size_t offset)
static void Vchk_BetaUnc (DataVariablesRep *dv, size_t offset, Var_Info *vi)
static void Vgen_BetaUnc (DataVariablesRep *dv, size_t offset)
static void Vchk_GammaUnc (DataVariablesRep *dv, size_t offset, Var_Info *vi)
static void Vgen_GammaUnc (DataVariablesRep *dv, size_t offset)
static void Vchk_GumbelUnc (DataVariablesRep *dv, size_t offset, Var_Info *vi)
static void Vgen_GumbelUnc (DataVariablesRep *dv, size_t offset)
static void Vchk_FrechetUnc (DataVariablesRep *dv, size_t offset, Var_Info *vi)
static void Vgen_FrechetUnc (DataVariablesRep *dv, size_t offset)
static void Vchk_WeibullUnc (DataVariablesRep *dv, size_t offset, Var_Info *vi)
static void Vgen_WeibullUnc (DataVariablesRep *dv, size_t offset)
static void Vchk_HistogramBinUnc (DataVariablesRep *dv, size_t offset, Var_Info *vi)
Check the histogram bin input data, normalize the counts and populate the histogramUncBinPairs map data structure; map keys are guaranteed unique since the abscissas must increase.
static void Vgen_HistogramBinUnc (DataVariablesRep *dv, size_t offset)
Infer lower/upper bounds for histogram and set initial variable values based on initial_point or moments, snapping to bounds as needed. (Histogram bin doesn't have lower/upper bounds specifcation)
static void Vchk_PoissonUnc (DataVariablesRep *dv, size_t offset, Var_Info *vi)
static void Vgen_PoissonUnc (DataVariablesRep *dv, size_t offset)
static void Vchk_BinomialUnc (DataVariablesRep *dv, size_t offset, Var_Info *vi)
static void Vgen_BinomialUnc (DataVariablesRep *dv, size_t offset)
static void Vchk_NegBinomialUnc (DataVariablesRep *dv, size_t offset, Var_Info *vi)
static void Vgen_NegBinomialUnc (DataVariablesRep *dv, size_t offset)
static void Vchk_GeometricUnc (DataVariablesRep *dv, size_t offset, Var_Info *vi)
static void Vgen_GeometricUnc (DataVariablesRep *dv, size_t offset)
static void Vchk_HyperGeomUnc (DataVariablesRep *dv, size_t offset, Var_Info *vi)
static void Vgen_HyperGeomUnc (DataVariablesRep *dv, size_t offset)
static void Vchk_HistogramPtIntUnc (DataVariablesRep *dv, size_t offset, Var_Info *vi)
Check the histogram point integer input data, normalize the counts, and populate DataVariables::histogramUncPointIntPairs; map keys are guaranteed unique since the abscissas must increase.
static void Vgen_HistogramPtIntUnc (DataVariablesRep *dv, size_t offset)
Use the integer-valued point histogram data to initialize the lower, upper, and initial values of the variables, using value closest to mean if no initial point.
static void Vchk_HistogramPtStrUnc (DataVariablesRep *dv, size_t offset, Var_Info *vi)
Check the histogram point string input data, normalize the counts, and populate DataVariables::histogramUncPointStrPairs; map keys are guaranteed unique since the abscissas must increase (lexicographically)
static void Vgen_HistogramPtStrUnc (DataVariablesRep *dv, size_t offset)
Use the string-valued point histogram data to initialize the lower, upper, and initial values of the variables, using index closest to mean index if no initial point.
static void Vchk_HistogramPtRealUnc (DataVariablesRep *dv, size_t offset, Var_Info *vi)
Check the histogram point integer real data, normalize the counts, and populate DataVariables::histogramUncPointRealPairs; map keys are guaranteed unique since the abscissas must increase.
static void Vgen_HistogramPtRealUnc (DataVariablesRep *dv, size_t offset)
Use the real-valued point histogram data to initialize the lower, upper, and initial values of the variables, using value closest to mean if no initial point.
static void Vchk_ContinuousIntervalUnc (DataVariablesRep *dv, size_t offset, Var_Info *vi)
Check the continuous interval uncertain input data and populate DataVariables::continuousIntervalUncBasicProbs; map keys (real intervals) are checked for uniqueness because we don't have a theoretically sound way to combine duplicate intervals.
static void Vgen_ContinuousIntervalUnc (DataVariablesRep *dv, size_t offset)
static void Vchk_DiscreteIntervalUnc (DataVariablesRep *dv, size_t offset, Var_Info *vi)
Check the discrete interval uncertain input data and populate DataVariables::discreteIntervalUncBasicProbs; map keys (integer intervals) are checked for uniqueness because we don't have a theoretically sound way to combine duplicate intervals.
static void Vgen_DiscreteIntervalUnc (DataVariablesRep *dv, size_t offset)
static bool check_set_keys (size_t num_v, size_t ds_len, const char *kind, IntArray *input_nds, int &avg_num_ds)
validate the number of set elements (values) given the number of variables and an optional apportionment with elements_per_variable; return the average number per variable if equally distributed
static void Vchk_DIset (size_t num_v, const char *kind, IntArray *input_ndsi, IntVector *input_dsi, IntSetArray &dsi_all, IntVector &dsi_init_pt)
check discrete sets of integers (design and state variables); error if a duplicate value is specified error if not ordered to prevent user confusion
static void Vchk_DIset (size_t num_v, const char *kind, IntArray *input_ndsi, IntVector *input_dsi, RealVector *input_dsip, IntRealMapArray &dsi_vals_probs, IntVector &dsi_init_pt)
check discrete sets of integers (uncertain variables); error if a duplicate value is specified error if not ordered to prevent user confusion
static void Vchk_DSset (size_t num_v, const char *kind, IntArray *input_ndss, StringArray *input_dss, StringSetArray &dss_all, StringArray &dss_init_pt)
static void Vchk_DSset (size_t num_v, const char *kind, IntArray *input_ndss, StringArray *input_dss, RealVector *input_dssp, StringRealMapArray &dss_vals_probs, StringArray &dss_init_pt)
static void Vchk_DRset (size_t num_v, const char *kind, IntArray *input_ndsr, RealVector *input_dsr, RealSetArray &dsr_all, RealVector &dsr_init_pt)
static void Vchk_DRset (size_t num_v, const char *kind, IntArray *input_ndsr, RealVector *input_dsr, RealVector *input_dsrp, RealRealMapArray &dsr_vals_probs, RealVector &dsr_init_pt)
static void Vchk_Adjacency (size_t num_v, const char *kind, const IntArray &num_e, const IntVector &input_ddsa, RealMatrixArray &dda_all)
static bool check_LUV_size (size_t num_v, IntVector &L, IntVector &U, IntVector &V, bool aggregate_LUV, size_t offset)
static bool check_LUV_size (size_t num_v, StringArray &L, StringArray &U, StringArray &V, bool aggregate_LUV, size_t offset)
static bool check_LUV_size (size_t num_v, RealVector &L, RealVector &U, RealVector &V, bool aggregate_LUV, size_t offset)
template<typename T >
T midpoint (T a, T b)
Compute the midpoint of floating-point or integer range [a, b] (a <= b), possibly indices, rounding toward a if needed. (Eventually replace with C++20 midpoint, which is more general.)
static size_t mid_or_next_lower_index (const size_t num_inds)
get the middle or left-of-middle index among indices [0,num_inds-1]
static void Vgen_DIset (size_t num_v, IntSetArray &sets, IntVector &L, IntVector &U, IntVector &V, bool aggregate_LUV=false, size_t offset=0)
static void Vgen_DSset (size_t num_v, StringSetArray &sets, StringArray &L, StringArray &U, StringArray &V, bool aggregate_LUV=false, size_t offset=0)
generate lower, upper, and initial point for string-valued sets
static void Vgen_DIset (size_t num_v, IntRealMapArray &vals_probs, IntVector &IP, IntVector &L, IntVector &U, IntVector &V, bool aggregate_LUV=false, size_t offset=0)
static void Vgen_DRset (size_t num_v, RealSetArray &sets, RealVector &L, RealVector &U, RealVector &V, bool aggregate_LUV=false, size_t offset=0)
static void Vgen_DRset (size_t num_v, RealRealMapArray &vals_probs, RealVector &IP, RealVector &L, RealVector &U, RealVector &V, bool aggregate_LUV=false, size_t offset=0)
static void Vgen_DSset (size_t num_v, StringRealMapArray &vals_probs, StringArray &IP, StringArray &L, StringArray &U, StringArray &V, bool aggregate_LUV=false, size_t offset=0)
static void Vchk_DiscreteDesSetInt (DataVariablesRep *dv, size_t offset, Var_Info *vi)
static void Vgen_DiscreteDesSetInt (DataVariablesRep *dv, size_t offset)
static void Vchk_DiscreteDesSetStr (DataVariablesRep *dv, size_t offset, Var_Info *vi)
static void Vgen_DiscreteDesSetStr (DataVariablesRep *dv, size_t offset)
static void Vchk_DiscreteDesSetReal (DataVariablesRep *dv, size_t offset, Var_Info *vi)
static void Vgen_DiscreteDesSetReal (DataVariablesRep *dv, size_t offset)
static void Vchk_DiscreteUncSetInt (DataVariablesRep *dv, size_t offset, Var_Info *vi)
static void Vgen_DiscreteUncSetInt (DataVariablesRep *dv, size_t offset)
static void Vchk_DiscreteUncSetStr (DataVariablesRep *dv, size_t offset, Var_Info *vi)
static void Vgen_DiscreteUncSetStr (DataVariablesRep *dv, size_t offset)
static void Vchk_DiscreteUncSetReal (DataVariablesRep *dv, size_t offset, Var_Info *vi)
static void Vgen_DiscreteUncSetReal (DataVariablesRep *dv, size_t offset)
static void Vchk_DiscreteStateSetInt (DataVariablesRep *dv, size_t offset, Var_Info *vi)
static void Vgen_DiscreteStateSetInt (DataVariablesRep *dv, size_t offset)
static void Vchk_DiscreteStateSetStr (DataVariablesRep *dv, size_t offset, Var_Info *vi)
static void Vgen_DiscreteStateSetStr (DataVariablesRep *dv, size_t offset)
static void Vchk_DiscreteStateSetReal (DataVariablesRep *dv, size_t offset, Var_Info *vi)
static void Vgen_DiscreteStateSetReal (DataVariablesRep *dv, size_t offset)
static const char * Var_Name (StringArray *sa, char *buf, size_t i)
static void Var_RealBoundIPCheck (DataVariablesRep *dv, Var_rcheck *b)
For real-valued variables: verify lengths of bounds and initial point, validate bounds and adjust initial point to bounds.
static void Var_IntBoundIPCheck (DataVariablesRep *dv, Var_icheck *ib)
For integer-valued variables: verify lengths of bounds and initial point, validate bounds and initial point against bounds.
static void flatten_rva (RealVectorArray *rva, RealVector **prv)
static void flatten_iva (IntVectorArray *iva, IntVector **piv)
static void flatten_rsm (RealSymMatrix *rsm, RealVector **prv)
static void flatten_rsa (RealSetArray *rsa, RealVector **prv)
static void flatten_ssa (StringSetArray *ssa, StringArray **psa)
static void flatten_isa (IntSetArray *isa, IntVector **piv)
static void flatten_rrma_keys (RealRealMapArray *rrma, RealVector **prv)
static void flatten_rrma_values (RealRealMapArray *rrma, RealVector **prv)
static void flatten_irma_keys (IntRealMapArray *irma, IntVector **piv)
static void flatten_irma_values (IntRealMapArray *irma, RealVector **prv)
static void flatten_srma_keys (StringRealMapArray *srma, StringArray **psa)
static void flatten_srma_values (StringRealMapArray *srma, RealVector **prv)
static void flatten_real_intervals (const RealRealPairRealMapArray &rrprma, RealVector **probs, RealVector **lb, RealVector **ub)
Flatten real-valued interval uncertain variable intervals and probabilities back into separate arrays.
static void flatten_int_intervals (const IntIntPairRealMapArray &iiprma, RealVector **probs, IntVector **lb, IntVector **ub)
Flatten integer-valued interval uncertain variable intervals and probabilities back into separate arrays.
static void var_iulbl (const char *keyname, Values *val, VarLabel *vl)
static Iface_mp_Rlit MP3 (failAction, recoveryFnVals, recover)
static Iface_mp_ilit MP3 (failAction, retryLimit, retry)
static Iface_mp_lit MP2 (failAction, abort)
static Iface_mp_lit MP2 (failAction, continuation)
static Iface_mp_type MP2s (analysisScheduling, MASTER_SCHEDULING)
static Iface_mp_type MP2s (analysisScheduling, PEER_SCHEDULING)
static Iface_mp_type MP2s (evalScheduling, MASTER_SCHEDULING)
static Iface_mp_type MP2s (evalScheduling, PEER_DYNAMIC_SCHEDULING)
static Iface_mp_type MP2s (evalScheduling, PEER_STATIC_SCHEDULING)
static Iface_mp_type MP2s (asynchLocalEvalScheduling, DYNAMIC_SCHEDULING)
static Iface_mp_type MP2s (asynchLocalEvalScheduling, STATIC_SCHEDULING)
static Iface_mp_utype MP2s (interfaceType, TEST_INTERFACE)
static Iface_mp_utype MP2s (interfaceType, FORK_INTERFACE)
static Iface_mp_utype MP2s (interfaceType, GRID_INTERFACE)
static Iface_mp_utype MP2s (interfaceType, LEGACY_PYTHON_INTERFACE)
static Iface_mp_utype MP2s (interfaceType, MATLAB_INTERFACE)
static Iface_mp_utype MP2s (interfaceType, PLUGIN_INTERFACE)
static Iface_mp_utype MP2s (interfaceType, PYTHON_INTERFACE)
static Iface_mp_utype MP2s (interfaceType, SCILAB_INTERFACE)
static Iface_mp_utype MP2s (interfaceType, SYSTEM_INTERFACE)
static Iface_mp_utype MP2s (resultsFileFormat, LABELED_RESULTS)
static String MP_ (algebraicMappings)
static String MP_ (idInterface)
static String MP_ (inputFilter)
static String MP_ (outputFilter)
static String MP_ (parametersFile)
static String MP_ (pluginLibraryPath)
static String MP_ (resultsFile)
static String MP_ (workDir)
static String2DArray MP_ (analysisComponents)
static StringArray MP_ (analysisDrivers)
static StringArray MP_ (copyFiles)
static StringArray MP_ (linkFiles)
static bool MP_ (activeSetVectorFlag)
static bool MP_ (allowExistingResultsFlag)
static bool MP_ (apreproFlag)
static bool MP_ (asynchFlag)
static bool MP_ (batchEvalFlag)
static bool MP_ (dirSave)
static bool MP_ (dirTag)
static bool MP_ (evalCacheFlag)
static bool MP_ (fileSaveFlag)
static bool MP_ (fileTagFlag)
static bool MP_ (nearbyEvalCacheFlag)
static bool MP_ (numpyFlag)
static bool MP_ (restartFileFlag)
static bool MP_ (templateReplace)
static bool MP_ (useWorkdir)
static bool MP_ (verbatimFlag)
static int MP_ (analysisServers)
static int MP_ (asynchLocalAnalysisConcurrency)
static int MP_ (asynchLocalEvalConcurrency)
static int MP_ (evalServers)
static int MP_ (procsPerAnalysis)
static int MP_ (procsPerEval)
static Real MP_ (nearbyEvalCacheTol)
static IntVector MP_ (primeBase)
static IntVector MP_ (refineSamples)
static IntVector MP_ (sequenceLeap)
static IntVector MP_ (sequenceStart)
static IntVector MP_ (stepsPerVariable)
static IntVector MP_ (generatingVector)
static IntVector MP_ (generatingMatrices)
static Method_mp_ilit2 MP3 (replacementType, numberRetained, chc)
static Method_mp_ilit2 MP3 (replacementType, numberRetained, elitist)
static Method_mp_ilit2 MP3 (replacementType, numberRetained, random)
static Method_mp_ilit2z MP3 (crossoverType, numCrossPoints, multi_point_binary)
static Method_mp_ilit2z MP3 (crossoverType, numCrossPoints, multi_point_parameterized_binary)
static Method_mp_ilit2z MP3 (crossoverType, numCrossPoints, multi_point_real)
static Method_mp_lit MP2 (batchSelectionType, naive)
static Method_mp_lit MP2 (batchSelectionType, distance)
static Method_mp_lit MP2 (batchSelectionType, topology)
static Method_mp_lit MP2 (batchSelectionType, cl)
static Method_mp_lit MP2 (boxDivision, all_dimensions)
static Method_mp_lit MP2 (boxDivision, major_dimension)
static Method_mp_lit MP2 (convergenceType, average_fitness_tracker)
static Method_mp_lit MP2 (convergenceType, best_fitness_tracker)
static Method_mp_lit MP2 (convergenceType, metric_tracker)
static Method_mp_lit MP2 (crossoverType, blend)
static Method_mp_lit MP2 (crossoverType, two_point)
static Method_mp_lit MP2 (crossoverType, uniform)
static Method_mp_lit MP2 (dataDistCovInputType, diagonal)
static Method_mp_lit MP2 (dataDistCovInputType, matrix)
static Method_mp_lit MP2 (exploratoryMoves, adaptive)
static Method_mp_lit MP2 (exploratoryMoves, multi_step)
static Method_mp_lit MP2 (exploratoryMoves, simple)
static Method_mp_lit MP2 (fitnessType, domination_count)
static Method_mp_lit MP2 (fitnessType, layer_rank)
static Method_mp_lit MP2 (fitnessType, linear_rank)
static Method_mp_lit MP2 (fitnessType, merit_function)
static Method_mp_lit MP2 (fitnessType, proportional)
static Method_mp_lit MP2 (fitnessMetricType, predicted_variance)
static Method_mp_lit MP2 (fitnessMetricType, distance)
static Method_mp_lit MP2 (fitnessMetricType, gradient)
static Method_mp_lit MP2 (initializationType, random)
static Method_mp_lit MP2 (initializationType, unique_random)
static Method_mp_lit MP2 (lipschitzType, global)
static Method_mp_lit MP2 (lipschitzType, local)
static Method_mp_lit MP2 (meritFunction, merit_max)
static Method_mp_lit MP2 (meritFunction, merit_max_smooth)
static Method_mp_lit MP2 (meritFunction, merit1)
static Method_mp_lit MP2 (meritFunction, merit1_smooth)
static Method_mp_lit MP2 (meritFunction, merit2)
static Method_mp_lit MP2 (meritFunction, merit2_smooth)
static Method_mp_lit MP2 (meritFunction, merit2_squared)
static Method_mp_lit MP2 (mcmcType, adaptive_metropolis)
static Method_mp_lit MP2 (mcmcType, delayed_rejection)
static Method_mp_lit MP2 (mcmcType, dram)
static Method_mp_lit MP2 (mcmcType, metropolis_hastings)
static Method_mp_lit MP2 (mcmcType, multilevel)
static Method_mp_lit MP2 (modelDiscrepancyType, global_kriging)
static Method_mp_lit MP2 (modelDiscrepancyType, global_polynomial)
static Method_mp_lit MP2 (mutationType, bit_random)
static Method_mp_lit MP2 (mutationType, offset_cauchy)
static Method_mp_lit MP2 (mutationType, offset_normal)
static Method_mp_lit MP2 (mutationType, offset_uniform)
static Method_mp_lit MP2 (mutationType, replace_uniform)
static Method_mp_lit MP2 (patternBasis, coordinate)
static Method_mp_lit MP2 (patternBasis, simplex)
static Method_mp_lit MP2 (pointReuse, all)
static Method_mp_lit MP2 (proposalCovInputType, diagonal)
static Method_mp_lit MP2 (proposalCovInputType, matrix)
static Method_mp_lit MP2 (proposalCovType, derivatives)
static Method_mp_lit MP2 (proposalCovType, prior)
static Method_mp_lit MP2 (proposalCovType, user)
static Method_mp_lit MP2 (reliabilityIntegration, first_order)
static Method_mp_lit MP2 (reliabilityIntegration, second_order)
static Method_mp_lit MP2 (replacementType, elitist)
static Method_mp_lit MP2 (replacementType, favor_feasible)
static Method_mp_lit MP2 (replacementType, roulette_wheel)
static Method_mp_lit MP2 (replacementType, unique_roulette_wheel)
static Method_mp_lit MP2 (rngName, mt19937)
static Method_mp_lit MP2 (rngName, rnum2)
static Method_mp_lit MP2 (searchMethod, gradient_based_line_search)
static Method_mp_lit MP2 (searchMethod, tr_pds)
static Method_mp_lit MP2 (searchMethod, trust_region)
static Method_mp_lit MP2 (searchMethod, value_based_line_search)
static Method_mp_lit MP2 (trialType, grid)
static Method_mp_lit MP2 (trialType, halton)
static Method_mp_lit MP2 (trialType, random)
static Method_mp_lit MP2 (useSurrogate, inform_search)
static Method_mp_lit MP2 (useSurrogate, optimize)
static Method_mp_litc MP3 (crossoverType, crossoverRate, shuffle_random)
static Method_mp_litc MP3 (crossoverType, crossoverRate, null_crossover)
static Method_mp_litc MP3 (mutationType, mutationRate, null_mutation)
static Method_mp_litc MP3 (mutationType, mutationRate, offset_cauchy)
static Method_mp_litc MP3 (mutationType, mutationRate, offset_normal)
static Method_mp_litc MP3 (mutationType, mutationRate, offset_uniform)
static Method_mp_litc MP3 (replacementType, fitnessLimit, below_limit)
static Method_mp_litrv MP3 (nichingType, nicheVector, distance)
static Method_mp_litrv MP3 (nichingType, nicheVector, max_designs)
static Method_mp_litrv MP3 (nichingType, nicheVector, radial)
static Method_mp_litrv MP3 (postProcessorType, distanceVector, distance_postprocessor)
static Method_mp_slit2 MP3 (initializationType, flatFile, flat_file)
static Method_mp_utype_lit MP3s (methodName, dlDetails, DL_SOLVER)
static Real MP_ (absConvTol)
static Real MP_ (centeringParam)
static Real MP_ (collocationRatio)
static Real MP_ (collocRatioTermsOrder)
static Real MP_ (constraintPenalty)
static Real MP_ (constrPenalty)
static Real MP_ (constraintTolerance)
static Real MP_ (contractFactor)
static Real MP_ (contractStepLength)
static Real MP_ (convergenceTolerance)
static Real MP_ (crossoverRate)
static Real MP_ (falseConvTol)
static Real MP_ (functionPrecision)
static Real MP_ (globalBalanceParam)
static Real MP_ (gradientTolerance)
static Real MP_ (hybridLSProb)
static Real MP_ (grThreshold)
static Real MP_ (initDelta)
static Real MP_ (initMeshSize)
static Real MP_ (initStepLength)
static Real MP_ (initTRRadius)
static Real MP_ (lineSearchTolerance)
static Real MP_ (localBalanceParam)
static Real MP_ (maxBoxSize)
static Real MP_ (maxStep)
static Real MP_ (minBoxSize)
static Real MP_ (minMeshSize)
static Real MP_ (multilevEstimatorRate)
static Real MP_ (mutationRate)
static Real MP_ (mutationScale)
static Real MP_ (percentVarianceExplained)
static Real MP_ (priorPropCovMult)
static Real MP_ (refinementRate)
static Real MP_ (regressionL2Penalty)
static Real MP_ (shrinkagePercent)
static Real MP_ (singConvTol)
static Real MP_ (singRadius)
static Real MP_ (smoothFactor)
static Real MP_ (solnTarget)
static Real MP_ (solverRoundingTol)
static Real MP_ (solverTol)
static Real MP_ (statsRoundingTol)
static Real MP_ (stepLenToBoundary)
static Real MP_ (threshDelta)
static Real MP_ (threshStepLength)
static Real MP_ (trustRegionContract)
static Real MP_ (trustRegionContractTrigger)
static Real MP_ (trustRegionExpand)
static Real MP_ (trustRegionExpandTrigger)
static Real MP_ (trustRegionMinSize)
static Real MP_ (vbdDropTolerance)
static Real MP_ (volBoxSize)
static Real MP_ (vns)
static Real MP_ (wilksConfidenceLevel)
static Real MP_ (tiCoverage)
static Real MP_ (tiConfidenceLevel)
static Real MP_ (xConvTol)
static RealVector MP_ (anisoDimPref)
static RealVector MP_ (concurrentParameterSets)
static RealVector MP_ (dataDistCovariance)
static RealVector MP_ (dataDistMeans)
static RealVector MP_ (finalPoint)
static RealVector MP_ (hyperPriorAlphas)
static RealVector MP_ (hyperPriorBetas)
static RealVector MP_ (listOfPoints)
static RealVector MP_ (predictionConfigList)
static RealVector MP_ (proposalCovData)
static RealVector MP_ (regressionNoiseTol)
static RealVector MP_ (scalarizationRespCoeffs)
static RealVector MP_ (stepVector)
static RealVector MP_ (trustRegionInitSize)
static RealVectorArray MP_ (genReliabilityLevels)
static RealVectorArray MP_ (probabilityLevels)
static RealVectorArray MP_ (reliabilityLevels)
static RealVectorArray MP_ (responseLevels)
static unsigned short MP_ (adaptedBasisAdvancements)
static unsigned short MP_ (cubIntOrder)
static unsigned short MP_ (dagDepthLimit)
static unsigned short MP_ (expansionOrder)
static unsigned short MP_ (kickOrder)
static unsigned short MP_ (maxCVOrderCandidates)
static unsigned short MP_ (maxOrder)
static unsigned short MP_ (quadratureOrder)
static unsigned short MP_ (softConvLimit)
static unsigned short MP_ (sparseGridLevel)
static unsigned short MP_ (startOrder)
static unsigned short MP_ (vbdOrder)
static unsigned short MP_ (wilksOrder)
static unsigned short MP_ (vbdViaSamplingMethod)
static SizetArray MP_ (collocationPointsSeq)
static SizetArray MP_ (expansionSamplesSeq)
static SizetArray MP_ (pilotSamples)
static SizetArray MP_ (randomSeedSeq)
static SizetArray MP_ (startRankSeq)
static UShortArray MP_ (expansionOrderSeq)
static UShortArray MP_ (quadratureOrderSeq)
static UShortArray MP_ (sparseGridLevelSeq)
static UShortArray MP_ (startOrderSeq)
static UShortArray MP_ (tensorGridOrder)
static UShortArray MP_ (varPartitions)
static String MP_ (advancedOptionsFilename)
static String MP_ (betaSolverName)
static String MP_ (dataDistFile)
static String MP_ (displayFormat)
static String MP_ (exportApproxPtsFile)
static String MP_ (exportCorrModelFile)
static String MP_ (exportCorrVarFile)
static String MP_ (exportDiscrepFile)
static String MP_ (exportExpansionFile)
static String MP_ (exportMCMCPtsFile)
static String MP_ (historyFile)
static String MP_ (hybridGlobalMethodName)
static String MP_ (hybridGlobalMethodPointer)
static String MP_ (hybridGlobalModelPointer)
static String MP_ (hybridLocalMethodName)
static String MP_ (hybridLocalMethodPointer)
static String MP_ (hybridLocalModelPointer)
static String MP_ (idMethod)
static String MP_ (importApproxPtsFile)
static String MP_ (importBuildPtsFile)
static String MP_ (importCandPtsFile)
static String MP_ (importExpansionFile)
static String MP_ (importPredConfigs)
static String MP_ (logFile)
static String MP_ (lowFidModelPointer)
static String MP_ (modelExportPrefix)
static String MP_ (modelPointer)
static String MP_ (posteriorDensityExportFilename)
static String MP_ (posteriorSamplesExportFilename)
static String MP_ (posteriorSamplesImportFilename)
static String MP_ (proposalCovFile)
static String MP_ (pstudyFilename)
static String MP_ (subMethodName)
static String MP_ (subMethodPointer)
static String MP_ (subModelPointer)
static String MP_ (generatingVectorFileName)
static String MP_ (generatingMatricesFileName)
static StringArray MP_ (hybridMethodNames)
static StringArray MP_ (hybridMethodPointers)
static StringArray MP_ (hybridModelPointers)
static StringArray MP_ (miscOptions)
static bool MP_ (adaptExpDesign)
static bool MP_ (adaptOrder)
static bool MP_ (adaptPosteriorRefine)
static bool MP_ (adaptRank)
static bool MP_ (backfillFlag)
static bool MP_ (calModelDiscrepancy)
static bool MP_ (chainDiagnostics)
static bool MP_ (chainDiagnosticsCI)
static bool MP_ (constantPenalty)
static bool MP_ (crossValidation)
static bool MP_ (crossValidNoiseOnly)
static bool MP_ (dOptimal)
static bool MP_ (evaluatePosteriorDensity)
static bool MP_ (expansionFlag)
static bool MP_ (exportSampleSeqFlag)
static bool MP_ (exportSurrogate)
static bool MP_ (fixedSeedFlag)
static bool MP_ (fixedSequenceFlag)
static bool MP_ (generatePosteriorSamples)
static bool MP_ (gpmsaNormalize)
static bool MP_ (importApproxActive)
static bool MP_ (importBuildActive)
static bool MP_ (latinizeFlag)
static bool MP_ (logitTransform)
static bool MP_ (mainEffectsFlag)
static bool MP_ (methodScaling)
static bool MP_ (methodUseDerivsFlag)
static bool MP_ (modelEvidence)
static bool MP_ (modelEvidLaplace)
static bool MP_ (modelEvidMC)
static bool MP_ (mutualInfoKSG2)
static bool MP_ (mutationAdaptive)
static bool MP_ (normalizedCoeffs)
static bool MP_ (pcaFlag)
static bool MP_ (posteriorStatsKL)
static bool MP_ (posteriorStatsKDE)
static bool MP_ (posteriorStatsMutual)
static bool MP_ (printPopFlag)
static bool MP_ (pstudyFileActive)
static bool MP_ (randomizeOrderFlag)
static bool MP_ (regressDiag)
static bool MP_ (relativeConvMetric)
static bool MP_ (respScalingFlag)
static bool MP_ (showAllEval)
static bool MP_ (showMiscOptions)
static bool MP_ (speculativeFlag)
static bool MP_ (standardizedSpace)
static bool MP_ (stdRegressionCoeffs)
static bool MP_ (toleranceIntervalsFlag)
static bool MP_ (surrBasedGlobalReplacePts)
static bool MP_ (surrBasedLocalLayerBypass)
static bool MP_ (tensorGridFlag)
static bool MP_ (truthPilotConstraint)
static bool MP_ (useTargetVarianceOptimizationFlag)
static bool MP_ (vbdFlag)
static bool MP_ (volQualityFlag)
static bool MP_ (wilksFlag)
static bool MP_ (rank1LatticeFlag)
static bool MP_ (noRandomShiftFlag)
static bool MP_ (kuo)
static bool MP_ (cools_kuo_nuyens)
static bool MP_ (naturalOrdering)
static bool MP_ (radicalInverseOrdering)
static bool MP_ (digitalNetFlag)
static bool MP_ (noDigitalShiftFlag)
static bool MP_ (noScramblingFlag)
static bool MP_ (mostSignificantBitFirst)
static bool MP_ (leastSignificantBitFirst)
static bool MP_ (joe_kuo)
static bool MP_ (sobol_order_2)
static bool MP_ (grayCodeOrdering)
static short MP_ (polynomialOrder)
static int MP_ (batchSize)
static int MP_ (batchSizeExplore)
static int MP_ (buildSamples)
static int MP_ (burnInSamples)
static int MP_ (chainSamples)
static int MP_ (concurrentRandomJobs)
static int MP_ (contractAfterFail)
static int MP_ (covarianceType)
static int MP_ (crossoverChainPairs)
static int MP_ (emulatorOrder)
static int MP_ (expandAfterSuccess)
static int MP_ (evidenceSamples)
static int MP_ (iteratorServers)
static int MP_ (jumpStep)
static int MP_ (maxCrossIterations)
static int MP_ (maxHifiEvals)
static int MP_ (mutationRange)
static int MP_ (neighborOrder)
static int MP_ (newSolnsGenerated)
static int MP_ (numChains)
static int MP_ (numCR)
static int MP_ (numSamples)
static int MP_ (numSteps)
static int MP_ (numSymbols)
static int MP_ (numTrials)
static int MP_ (populationSize)
static int MP_ (procsPerIterator)
static int MP_ (proposalCovUpdatePeriod)
static int MP_ (numPushforwardSamples)
static int MP_ (randomSeed)
static int MP_ (samplesOnEmulator)
static int MP_ (searchSchemeSize)
static int MP_ (subSamplingPeriod)
static int MP_ (totalPatternSize)
static int MP_ (verifyLevel)
static int MP_ (vbdViaSamplingNumBins)
static int MP_ (log2MaxPoints)
static int MP_ (numberOfBits)
static int MP_ (scrambleSize)
static size_t MP_ (collocationPoints)
static size_t MP_ (expansionSamples)
static size_t MP_ (kickRank)
static size_t MP_ (maxCVRankCandidates)
static size_t MP_ (maxFunctionEvals)
static size_t MP_ (maxIterations)
static size_t MP_ (maxRank)
static size_t MP_ (maxRefineIterations)
static size_t MP_ (maxSolverIterations)
static size_t MP_ (numCandidateDesigns)
static size_t MP_ (numCandidates)
static size_t MP_ (numDesigns)
static size_t MP_ (numFinalSolutions)
static size_t MP_ (numGenerations)
static size_t MP_ (numOffspring)
static size_t MP_ (numParents)
static size_t MP_ (numPredConfigs)
static size_t MP_ (startRank)
static Method_mp_type MP2s (allocationTarget, TARGET_MEAN)
static Method_mp_type MP2s (allocationTarget, TARGET_SCALARIZATION)
static Method_mp_type MP2s (allocationTarget, TARGET_SIGMA)
static Method_mp_type MP2s (allocationTarget, TARGET_VARIANCE)
static Method_mp_type MP2s (c3AdvanceType, MAX_ORDER_ADVANCEMENT)
static Method_mp_type MP2s (c3AdvanceType, MAX_RANK_ADVANCEMENT)
static Method_mp_type MP2s (c3AdvanceType, MAX_RANK_ORDER_ADVANCEMENT)
static Method_mp_type MP2s (c3AdvanceType, START_ORDER_ADVANCEMENT)
static Method_mp_type MP2s (c3AdvanceType, START_RANK_ADVANCEMENT)
static Method_mp_type MP2s (convergenceToleranceTarget, CONVERGENCE_TOLERANCE_TARGET_COST_CONSTRAINT)
static Method_mp_type MP2s (convergenceToleranceTarget, CONVERGENCE_TOLERANCE_TARGET_VARIANCE_CONSTRAINT)
static Method_mp_type MP2s (convergenceToleranceType, CONVERGENCE_TOLERANCE_TYPE_ABSOLUTE)
static Method_mp_type MP2s (convergenceToleranceType, CONVERGENCE_TOLERANCE_TYPE_RELATIVE)
static Method_mp_type MP2s (covarianceControl, DIAGONAL_COVARIANCE)
static Method_mp_type MP2s (covarianceControl, FULL_COVARIANCE)
static Method_mp_type MP2s (dagRecursionType, FULL_GRAPH_RECURSION)
static Method_mp_type MP2s (dagRecursionType, KL_GRAPH_RECURSION)
static Method_mp_type MP2s (dagRecursionType, NO_GRAPH_RECURSION)
static Method_mp_type MP2s (dagRecursionType, PARTIAL_GRAPH_RECURSION)
static Method_mp_type MP2s (distributionType, COMPLEMENTARY)
static Method_mp_type MP2s (distributionType, CUMULATIVE)
static Method_mp_type MP2s (emulatorType, EXPGP_EMULATOR)
static Method_mp_type MP2s (emulatorType, GP_EMULATOR)
static Method_mp_type MP2s (emulatorType, KRIGING_EMULATOR)
static Method_mp_type MP2s (emulatorType, MF_PCE_EMULATOR)
static Method_mp_type MP2s (emulatorType, MF_SC_EMULATOR)
static Method_mp_type MP2s (emulatorType, ML_PCE_EMULATOR)
static Method_mp_type MP2s (emulatorType, PCE_EMULATOR)
static Method_mp_type MP2s (emulatorType, SC_EMULATOR)
static Method_mp_type MP2s (emulatorType, VPS_EMULATOR)
static Method_mp_type MP2s (ensembleSampSolnMode, OFFLINE_PILOT)
static Method_mp_type MP2s (ensembleSampSolnMode, ONLINE_PILOT)
static Method_mp_type MP2s (ensembleSampSolnMode, PILOT_PROJECTION)
static Method_mp_type MP2s (evalSynchronize, BLOCKING_SYNCHRONIZATION)
static Method_mp_type MP2s (evalSynchronize, NONBLOCKING_SYNCHRONIZATION)
static Method_mp_type MP2p (expansionBasisType, ADAPTED_BASIS_EXPANDING_FRONT)
static Method_mp_type MP2p (expansionBasisType, ADAPTED_BASIS_GENERALIZED)
static Method_mp_type MP2p (expansionBasisType, HIERARCHICAL_INTERPOLANT)
static Method_mp_type MP2p (expansionBasisType, NODAL_INTERPOLANT)
static Method_mp_type MP2p (expansionBasisType, TENSOR_PRODUCT_BASIS)
static Method_mp_type MP2p (expansionBasisType, TOTAL_ORDER_BASIS)
static Method_mp_type MP2s (expansionType, ASKEY_U)
static Method_mp_type MP2s (expansionType, STD_NORMAL_U)
static Method_mp_type MP2p (finalMomentsType, CENTRAL_MOMENTS)
static Method_mp_type MP2p (finalMomentsType, NO_MOMENTS)
static Method_mp_type MP2p (finalMomentsType, STANDARD_MOMENTS)
static Method_mp_type MP2s (finalStatsType, ESTIMATOR_PERFORMANCE)
static Method_mp_type MP2s (finalStatsType, NO_FINAL_STATS)
static Method_mp_type MP2s (finalStatsType, QOI_STATISTICS)
static Method_mp_type MP2p (growthOverride, RESTRICTED)
static Method_mp_type MP2p (growthOverride, UNRESTRICTED)
static Method_mp_type MP2s (iteratorScheduling, MASTER_SCHEDULING)
static Method_mp_type MP2s (iteratorScheduling, PEER_SCHEDULING)
static Method_mp_type MP2s (lsRegressionType, EQ_CON_LS)
static Method_mp_type MP2s (lsRegressionType, SVD_LS)
static Method_mp_type MP2o (meritFn, ArgaezTapia)
static Method_mp_type MP2o (meritFn, NormFmu)
static Method_mp_type MP2o (meritFn, VanShanno)
static Method_mp_type MP2s (methodOutput, DEBUG_OUTPUT)
static Method_mp_type MP2s (methodOutput, NORMAL_OUTPUT)
static Method_mp_type MP2s (methodOutput, QUIET_OUTPUT)
static Method_mp_type MP2s (methodOutput, SILENT_OUTPUT)
static Method_mp_type MP2s (methodOutput, VERBOSE_OUTPUT)
static Method_mp_type MP2s (modelSelectType, ALL_MODEL_COMBINATIONS)
static Method_mp_type MP2s (multilevAllocControl, ESTIMATOR_VARIANCE)
static Method_mp_type MP2s (multilevAllocControl, GREEDY_REFINEMENT)
static Method_mp_type MP2s (multilevAllocControl, RANK_SAMPLING)
static Method_mp_type MP2s (multilevAllocControl, RIP_SAMPLING)
static Method_mp_type MP2s (multilevDiscrepEmulation, DISTINCT_EMULATION)
static Method_mp_type MP2s (multilevDiscrepEmulation, RECURSIVE_EMULATION)
static Method_mp_type MP2p (nestingOverride, NESTED)
static Method_mp_type MP2p (nestingOverride, NON_NESTED)
static Method_mp_type MP2s (qoiAggregation, QOI_AGGREGATION_MAX)
static Method_mp_type MP2s (qoiAggregation, QOI_AGGREGATION_SUM)
static Method_mp_type MP2p (refinementControl, DIMENSION_ADAPTIVE_CONTROL_GENERALIZED)
static Method_mp_type MP2p (refinementControl, DIMENSION_ADAPTIVE_CONTROL_DECAY)
static Method_mp_type MP2p (refinementControl, DIMENSION_ADAPTIVE_CONTROL_SOBOL)
static Method_mp_type MP2p (refinementControl, LOCAL_ADAPTIVE_CONTROL)
static Method_mp_type MP2p (refinementControl, UNIFORM_CONTROL)
static Method_mp_type MP2p (refinementType, P_REFINEMENT)
static Method_mp_type MP2p (refinementType, H_REFINEMENT)
static Method_mp_type MP2p (regressionType, BASIS_PURSUIT)
static Method_mp_type MP2p (regressionType, BASIS_PURSUIT_DENOISING)
static Method_mp_type MP2p (regressionType, DEFAULT_LEAST_SQ_REGRESSION)
static Method_mp_type MP2p (regressionType, LASSO_REGRESSION)
static Method_mp_type MP2p (regressionType, LEAST_ANGLE_REGRESSION)
static Method_mp_type MP2p (regressionType, ORTHOG_LEAST_INTERPOLATION)
static Method_mp_type MP2p (regressionType, ORTHOG_MATCH_PURSUIT)
static Method_mp_type MP2s (regressionType, FT_LS)
static Method_mp_type MP2s (regressionType, FT_RLS2)
static Method_mp_type MP2s (responseLevelTarget, GEN_RELIABILITIES)
static Method_mp_type MP2s (responseLevelTarget, PROBABILITIES)
static Method_mp_type MP2s (responseLevelTarget, RELIABILITIES)
static Method_mp_type MP2s (responseLevelTargetReduce, SYSTEM_PARALLEL)
static Method_mp_type MP2s (responseLevelTargetReduce, SYSTEM_SERIES)
static Method_mp_type MP2p (statsMetricMode, ACTIVE_EXPANSION_STATS)
static Method_mp_type MP2p (statsMetricMode, COMBINED_EXPANSION_STATS)
static Method_mp_type MP2s (surrBasedLocalAcceptLogic, FILTER)
static Method_mp_type MP2s (surrBasedLocalAcceptLogic, TR_RATIO)
static Method_mp_type MP2s (surrBasedLocalConstrRelax, HOMOTOPY)
static Method_mp_type MP2s (surrBasedLocalMeritFn, ADAPTIVE_PENALTY_MERIT)
static Method_mp_type MP2s (surrBasedLocalMeritFn, AUGMENTED_LAGRANGIAN_MERIT)
static Method_mp_type MP2s (surrBasedLocalMeritFn, LAGRANGIAN_MERIT)
static Method_mp_type MP2s (surrBasedLocalMeritFn, PENALTY_MERIT)
static Method_mp_type MP2s (surrBasedLocalSubProbCon, LINEARIZED_CONSTRAINTS)
static Method_mp_type MP2s (surrBasedLocalSubProbCon, NO_CONSTRAINTS)
static Method_mp_type MP2s (surrBasedLocalSubProbCon, ORIGINAL_CONSTRAINTS)
static Method_mp_type MP2s (surrBasedLocalSubProbObj, AUGMENTED_LAGRANGIAN_OBJECTIVE)
static Method_mp_type MP2s (surrBasedLocalSubProbObj, LAGRANGIAN_OBJECTIVE)
static Method_mp_type MP2s (surrBasedLocalSubProbObj, ORIGINAL_PRIMARY)
static Method_mp_type MP2s (surrBasedLocalSubProbObj, SINGLE_OBJECTIVE)
static Method_mp_type MP2s (wilksSidedInterval, ONE_SIDED_LOWER)
static Method_mp_type MP2s (wilksSidedInterval, ONE_SIDED_UPPER)
static Method_mp_type MP2s (wilksSidedInterval, TWO_SIDED)
static Method_mp_utype MP2s (calibrateErrorMode, CALIBRATE_ONE)
static Method_mp_utype MP2s (calibrateErrorMode, CALIBRATE_PER_EXPER)
static Method_mp_utype MP2s (calibrateErrorMode, CALIBRATE_PER_RESP)
static Method_mp_utype MP2s (calibrateErrorMode, CALIBRATE_BOTH)
static Method_mp_utype MP2s (exportApproxFormat, TABULAR_NONE)
static Method_mp_utype MP2s (exportApproxFormat, TABULAR_HEADER)
static Method_mp_utype MP2s (exportApproxFormat, TABULAR_EVAL_ID)
static Method_mp_utype MP2s (exportApproxFormat, TABULAR_IFACE_ID)
static Method_mp_utype MP2s (exportApproxFormat, TABULAR_ANNOTATED)
static Method_mp_utype MP2s (exportCorrModelFormat, TABULAR_NONE)
static Method_mp_utype MP2s (exportCorrModelFormat, TABULAR_HEADER)
static Method_mp_utype MP2s (exportCorrModelFormat, TABULAR_EVAL_ID)
static Method_mp_utype MP2s (exportCorrModelFormat, TABULAR_IFACE_ID)
static Method_mp_utype MP2s (exportCorrModelFormat, TABULAR_ANNOTATED)
static Method_mp_utype MP2s (exportCorrVarFormat, TABULAR_NONE)
static Method_mp_utype MP2s (exportCorrVarFormat, TABULAR_HEADER)
static Method_mp_utype MP2s (exportCorrVarFormat, TABULAR_EVAL_ID)
static Method_mp_utype MP2s (exportCorrVarFormat, TABULAR_IFACE_ID)
static Method_mp_utype MP2s (exportCorrVarFormat, TABULAR_ANNOTATED)
static Method_mp_utype MP2s (exportDiscrepFormat, TABULAR_NONE)
static Method_mp_utype MP2s (exportDiscrepFormat, TABULAR_HEADER)
static Method_mp_utype MP2s (exportDiscrepFormat, TABULAR_EVAL_ID)
static Method_mp_utype MP2s (exportDiscrepFormat, TABULAR_IFACE_ID)
static Method_mp_utype MP2s (exportDiscrepFormat, TABULAR_ANNOTATED)
static Method_mp_utype MP2s (exportSamplesFormat, TABULAR_NONE)
static Method_mp_utype MP2s (exportSamplesFormat, TABULAR_HEADER)
static Method_mp_utype MP2s (exportSamplesFormat, TABULAR_EVAL_ID)
static Method_mp_utype MP2s (exportSamplesFormat, TABULAR_IFACE_ID)
static Method_mp_utype MP2s (exportSamplesFormat, TABULAR_ANNOTATED)
static Method_mp_utype MP2s (importApproxFormat, TABULAR_NONE)
static Method_mp_utype MP2s (importApproxFormat, TABULAR_HEADER)
static Method_mp_utype MP2s (importApproxFormat, TABULAR_EVAL_ID)
static Method_mp_utype MP2s (importApproxFormat, TABULAR_IFACE_ID)
static Method_mp_utype MP2s (importApproxFormat, TABULAR_ANNOTATED)
static Method_mp_utype MP2s (importBuildFormat, TABULAR_NONE)
static Method_mp_utype MP2s (importBuildFormat, TABULAR_HEADER)
static Method_mp_utype MP2s (importBuildFormat, TABULAR_EVAL_ID)
static Method_mp_utype MP2s (importBuildFormat, TABULAR_IFACE_ID)
static Method_mp_utype MP2s (importBuildFormat, TABULAR_ANNOTATED)
static Method_mp_utype MP2s (importCandFormat, TABULAR_NONE)
static Method_mp_utype MP2s (importCandFormat, TABULAR_HEADER)
static Method_mp_utype MP2s (importCandFormat, TABULAR_EVAL_ID)
static Method_mp_utype MP2s (importCandFormat, TABULAR_IFACE_ID)
static Method_mp_utype MP2s (importCandFormat, TABULAR_ANNOTATED)
static Method_mp_utype MP2s (importPredConfigFormat, TABULAR_NONE)
static Method_mp_utype MP2s (importPredConfigFormat, TABULAR_HEADER)
static Method_mp_utype MP2s (importPredConfigFormat, TABULAR_EVAL_ID)
static Method_mp_utype MP2s (importPredConfigFormat, TABULAR_IFACE_ID)
static Method_mp_utype MP2s (importPredConfigFormat, TABULAR_ANNOTATED)
static Method_mp_utype MP2s (integrationRefine, AIS)
static Method_mp_utype MP2s (integrationRefine, IS)
static Method_mp_utype MP2s (integrationRefine, MMAIS)
static Method_mp_utype MP2s (methodName, APPROXIMATE_CONTROL_VARIATE)
static Method_mp_utype MP2s (methodName, ASYNCH_PATTERN_SEARCH)
static Method_mp_utype MP2s (methodName, BRANCH_AND_BOUND)
static Method_mp_utype MP2s (methodName, C3_FUNCTION_TRAIN)
static Method_mp_utype MP2s (methodName, COLINY_BETA)
static Method_mp_utype MP2s (methodName, COLINY_COBYLA)
static Method_mp_utype MP2s (methodName, COLINY_DIRECT)
static Method_mp_utype MP2s (methodName, COLINY_EA)
static Method_mp_utype MP2s (methodName, COLINY_PATTERN_SEARCH)
static Method_mp_utype MP2s (methodName, COLINY_SOLIS_WETS)
static Method_mp_utype MP2s (methodName, CONMIN_FRCG)
static Method_mp_utype MP2s (methodName, CONMIN_MFD)
static Method_mp_utype MP2s (methodName, DACE)
static Method_mp_utype MP2s (methodName, DATA_FIT_SURROGATE_BASED_LOCAL)
static Method_mp_utype MP2s (methodName, DOT_BFGS)
static Method_mp_utype MP2s (methodName, DOT_FRCG)
static Method_mp_utype MP2s (methodName, DOT_MMFD)
static Method_mp_utype MP2s (methodName, DOT_SLP)
static Method_mp_utype MP2s (methodName, DOT_SQP)
static Method_mp_utype MP2s (methodName, EFFICIENT_GLOBAL)
static Method_mp_utype MP2s (methodName, FSU_CVT)
static Method_mp_utype MP2s (methodName, FSU_HALTON)
static Method_mp_utype MP2s (methodName, FSU_HAMMERSLEY)
static Method_mp_utype MP2s (methodName, HIERARCH_SURROGATE_BASED_LOCAL)
static Method_mp_utype MP2s (methodName, HYBRID)
static Method_mp_utype MP2s (methodName, MESH_ADAPTIVE_SEARCH)
static Method_mp_utype MP2s (methodName, MOGA)
static Method_mp_utype MP2s (methodName, MULTI_START)
static Method_mp_utype MP2s (methodName, NCSU_DIRECT)
static Method_mp_utype MP2s (methodName, ROL)
static Method_mp_utype MP2s (methodName, DEMO_TPL)
static Method_mp_utype MP2s (methodName, NL2SOL)
static Method_mp_utype MP2s (methodName, NLPQL_SQP)
static Method_mp_utype MP2s (methodName, NLSSOL_SQP)
static Method_mp_utype MP2s (methodName, MIT_NOWPAC)
static Method_mp_utype MP2s (methodName, MIT_SNOWPAC)
static Method_mp_utype MP2s (methodName, ADAPTIVE_SAMPLING)
static Method_mp_utype MP2s (methodName, BAYES_CALIBRATION)
static Method_mp_utype MP2s (methodName, GENIE_DIRECT)
static Method_mp_utype MP2s (methodName, GENIE_OPT_DARTS)
static Method_mp_utype MP2s (methodName, GPAIS)
static Method_mp_utype MP2s (methodName, GLOBAL_EVIDENCE)
static Method_mp_utype MP2s (methodName, GLOBAL_INTERVAL_EST)
static Method_mp_utype MP2s (methodName, GLOBAL_RELIABILITY)
static Method_mp_utype MP2s (methodName, IMPORTANCE_SAMPLING)
static Method_mp_utype MP2s (methodName, LOCAL_EVIDENCE)
static Method_mp_utype MP2s (methodName, LOCAL_INTERVAL_EST)
static Method_mp_utype MP2s (methodName, LOCAL_RELIABILITY)
static Method_mp_utype MP2s (methodName, MULTIFIDELITY_FUNCTION_TRAIN)
static Method_mp_utype MP2s (methodName, MULTIFIDELITY_POLYNOMIAL_CHAOS)
static Method_mp_utype MP2s (methodName, MULTIFIDELITY_SAMPLING)
static Method_mp_utype MP2s (methodName, MULTIFIDELITY_STOCH_COLLOCATION)
static Method_mp_utype MP2s (methodName, MULTILEVEL_FUNCTION_TRAIN)
static Method_mp_utype MP2s (methodName, MULTILEVEL_MULTIFIDELITY_SAMPLING)
static Method_mp_utype MP2s (methodName, MULTILEVEL_POLYNOMIAL_CHAOS)
static Method_mp_utype MP2s (methodName, MULTILEVEL_SAMPLING)
static Method_mp_utype MP2s (methodName, POF_DARTS)
static Method_mp_utype MP2s (methodName, RKD_DARTS)
static Method_mp_utype MP2s (methodName, POLYNOMIAL_CHAOS)
static Method_mp_utype MP2s (methodName, STOCH_COLLOCATION)
static Method_mp_utype MP2s (methodName, SURROGATE_BASED_UQ)
static Method_mp_utype MP2s (methodName, RANDOM_SAMPLING)
static Method_mp_utype MP2s (methodName, NONLINEAR_CG)
static Method_mp_utype MP2s (methodName, NPSOL_SQP)
static Method_mp_utype MP2s (methodName, OPTPP_CG)
static Method_mp_utype MP2s (methodName, OPTPP_FD_NEWTON)
static Method_mp_utype MP2s (methodName, OPTPP_G_NEWTON)
static Method_mp_utype MP2s (methodName, OPTPP_NEWTON)
static Method_mp_utype MP2s (methodName, OPTPP_PDS)
static Method_mp_utype MP2s (methodName, OPTPP_Q_NEWTON)
static Method_mp_utype MP2s (methodName, PARETO_SET)
static Method_mp_utype MP2s (methodName, PSUADE_MOAT)
static Method_mp_utype MP2s (methodName, RICHARDSON_EXTRAP)
static Method_mp_utype MP2s (methodName, SOGA)
static Method_mp_utype MP2s (methodName, SURROGATE_BASED_GLOBAL)
static Method_mp_utype MP2s (methodName, SURROGATE_BASED_LOCAL)
static Method_mp_utype MP2s (methodName, VECTOR_PARAMETER_STUDY)
static Method_mp_utype MP2s (methodName, LIST_PARAMETER_STUDY)
static Method_mp_utype MP2s (methodName, CENTERED_PARAMETER_STUDY)
static Method_mp_utype MP2s (methodName, MULTIDIM_PARAMETER_STUDY)
static Method_mp_utype MP2s (modelExportFormat, TEXT_ARCHIVE)
static Method_mp_utype MP2s (modelExportFormat, BINARY_ARCHIVE)
static Method_mp_utype MP2s (numericalSolveMode, NUMERICAL_FALLBACK)
static Method_mp_utype MP2s (numericalSolveMode, NUMERICAL_OVERRIDE)
static Method_mp_utype MP2s (optSubProbSolver, SUBMETHOD_NONE)
static Method_mp_utype MP2s (optSubProbSolver, SUBMETHOD_OPTPP)
static Method_mp_utype MP2s (optSubProbSolver, SUBMETHOD_NPSOL)
static Method_mp_utype MP2s (optSubProbSolver, SUBMETHOD_NPSOL_OPTPP)
static Method_mp_utype MP2s (optSubProbSolver, SUBMETHOD_SBLO)
static Method_mp_utype MP2s (optSubProbSolver, SUBMETHOD_EA)
static Method_mp_utype MP2s (optSubProbSolver, SUBMETHOD_EGO)
static Method_mp_utype MP2s (optSubProbSolver, SUBMETHOD_SBGO)
static Method_mp_utype MP2s (optSubProbSolver, SUBMETHOD_DIRECT_NPSOL_OPTPP)
static Method_mp_utype MP2s (optSubProbSolver, SUBMETHOD_LHS)
static Method_mp_utype MP2s (sampleType, SUBMETHOD_LOW_DISCREPANCY_SAMPLING)
static Method_mp_utype MP2s (pstudyFileFormat, TABULAR_NONE)
static Method_mp_utype MP2s (pstudyFileFormat, TABULAR_HEADER)
static Method_mp_utype MP2s (pstudyFileFormat, TABULAR_EVAL_ID)
static Method_mp_utype MP2s (pstudyFileFormat, TABULAR_IFACE_ID)
static Method_mp_utype MP2s (pstudyFileFormat, TABULAR_ANNOTATED)
static Method_mp_utype MP2s (sampleType, SUBMETHOD_LHS)
static Method_mp_utype MP2s (sampleType, SUBMETHOD_RANDOM)
static Method_mp_utype MP2s (vbdViaSamplingMethod, VBD_BINNED)
static Method_mp_utype MP2s (vbdViaSamplingMethod, VBD_PICK_AND_FREEZE)
static Method_mp_utype MP2s (subMethod, SUBMETHOD_AMV_PLUS_U)
static Method_mp_utype MP2s (subMethod, SUBMETHOD_AMV_PLUS_X)
static Method_mp_utype MP2s (subMethod, SUBMETHOD_AMV_U)
static Method_mp_utype MP2s (subMethod, SUBMETHOD_AMV_X)
static Method_mp_utype MP2s (subMethod, SUBMETHOD_QMEA_U)
static Method_mp_utype MP2s (subMethod, SUBMETHOD_QMEA_X)
static Method_mp_utype MP2s (subMethod, SUBMETHOD_TANA_U)
static Method_mp_utype MP2s (subMethod, SUBMETHOD_TANA_X)
static Method_mp_utype MP2s (subMethod, SUBMETHOD_NO_APPROX)
static Method_mp_utype MP2s (subMethod, SUBMETHOD_EGRA_U)
static Method_mp_utype MP2s (subMethod, SUBMETHOD_EGRA_X)
static Method_mp_utype MP2s (subMethod, SUBMETHOD_ACV_IS)
static Method_mp_utype MP2s (subMethod, SUBMETHOD_ACV_MF)
static Method_mp_utype MP2s (subMethod, SUBMETHOD_ACV_RD)
static Method_mp_utype MP2s (subMethod, SUBMETHOD_COLLABORATIVE)
static Method_mp_utype MP2s (subMethod, SUBMETHOD_EMBEDDED)
static Method_mp_utype MP2s (subMethod, SUBMETHOD_SEQUENTIAL)
static Method_mp_utype MP2s (subMethod, SUBMETHOD_MUQ)
static Method_mp_utype MP2s (subMethod, SUBMETHOD_DREAM)
static Method_mp_utype MP2s (subMethod, SUBMETHOD_WASABI)
static Method_mp_utype MP2s (subMethod, SUBMETHOD_GPMSA)
static Method_mp_utype MP2s (subMethod, SUBMETHOD_QUESO)
static Method_mp_utype MP2s (subMethod, SUBMETHOD_LHS)
static Method_mp_utype MP2s (subMethod, SUBMETHOD_RANDOM)
static Method_mp_utype MP2s (subMethod, SUBMETHOD_OA_LHS)
static Method_mp_utype MP2s (subMethod, SUBMETHOD_OAS)
static Method_mp_utype MP2s (subMethod, SUBMETHOD_BOX_BEHNKEN)
static Method_mp_utype MP2s (subMethod, SUBMETHOD_CENTRAL_COMPOSITE)
static Method_mp_utype MP2s (subMethod, SUBMETHOD_GRID)
static Method_mp_utype MP2s (subMethod, SUBMETHOD_CONVERGE_ORDER)
static Method_mp_utype MP2s (subMethod, SUBMETHOD_CONVERGE_QOI)
static Method_mp_utype MP2s (subMethod, SUBMETHOD_ESTIMATE_ORDER)
static SizetSet MP_ (surrogateFnIndices)
static Model_mp_lit MP2 (approxPointReuse, all)
static Model_mp_lit MP2 (approxPointReuse, none)
static Model_mp_lit MP2 (approxPointReuse, region)
static Model_mp_lit MP2 (marsInterpolation, linear)
static Model_mp_lit MP2 (marsInterpolation, cubic)
static Model_mp_lit MP2 (modelType, active_subspace)
static Model_mp_lit MP2 (modelType, adapted_basis)
static Model_mp_lit MP2 (modelType, nested)
static Model_mp_lit MP2 (modelType, random_field)
static Model_mp_lit MP2 (modelType, simulation)
static Model_mp_lit MP2 (modelType, surrogate)
static Model_mp_lit MP2 (surrogateType, ensemble)
static Model_mp_lit MP2 (surrogateType, global_exp_gauss_proc)
static Model_mp_lit MP2 (surrogateType, global_exp_poly)
static Model_mp_lit MP2 (surrogateType, global_function_train)
static Model_mp_lit MP2 (surrogateType, global_gaussian)
static Model_mp_lit MP2 (surrogateType, global_kriging)
static Model_mp_lit MP2 (surrogateType, global_mars)
static Model_mp_lit MP2 (surrogateType, global_moving_least_squares)
static Model_mp_lit MP2 (surrogateType, global_neural_network)
static Model_mp_lit MP2 (surrogateType, global_polynomial)
static Model_mp_lit MP2 (surrogateType, global_radial_basis)
static Model_mp_lit MP2 (surrogateType, global_voronoi_surrogate)
static Model_mp_lit MP2 (surrogateType, local_taylor)
static Model_mp_lit MP2 (surrogateType, multipoint_qmea)
static Model_mp_lit MP2 (surrogateType, multipoint_tana)
static Model_mp_lit MP2 (trendOrder, none)
static Model_mp_lit MP2 (trendOrder, constant)
static Model_mp_lit MP2 (trendOrder, linear)
static Model_mp_lit MP2 (trendOrder, reduced_quadratic)
static Model_mp_lit MP2 (trendOrder, quadratic)
static Model_mp_ord MP2s (approxCorrectionOrder, 0)
static Model_mp_ord MP2s (approxCorrectionOrder, 1)
static Model_mp_ord MP2s (approxCorrectionOrder, 2)
static Model_mp_ord MP2s (polynomialOrder, 1)
static Model_mp_ord MP2s (polynomialOrder, 2)
static Model_mp_ord MP2s (polynomialOrder, 3)
static Model_mp_type MP2s (approxCorrectionType, ADDITIVE_CORRECTION)
static Model_mp_type MP2s (approxCorrectionType, COMBINED_CORRECTION)
static Model_mp_type MP2s (approxCorrectionType, MULTIPLICATIVE_CORRECTION)
static Model_mp_type MP2s (pointsManagement, MINIMUM_POINTS)
static Model_mp_type MP2s (pointsManagement, RECOMMENDED_POINTS)
static Model_mp_type MP2s (subMethodScheduling, MASTER_SCHEDULING)
static Model_mp_type MP2s (method_rotation, ROTATION_METHOD_UNRANKED)
static Model_mp_type MP2s (method_rotation, ROTATION_METHOD_RANKED)
static Model_mp_type MP2s (subMethodScheduling, PEER_SCHEDULING)
static Model_mp_utype MP2s (analyticCovIdForm, EXP_L2)
static Model_mp_utype MP2s (analyticCovIdForm, EXP_L1)
static Model_mp_utype MP2s (exportApproxVarianceFormat, TABULAR_NONE)
static Model_mp_utype MP2s (exportApproxVarianceFormat, TABULAR_HEADER)
static Model_mp_utype MP2s (exportApproxVarianceFormat, TABULAR_EVAL_ID)
static Model_mp_utype MP2s (exportApproxVarianceFormat, TABULAR_IFACE_ID)
static Model_mp_utype MP2s (exportApproxVarianceFormat, TABULAR_ANNOTATED)
static Model_mp_utype MP2s (importChallengeFormat, TABULAR_NONE)
static Model_mp_utype MP2s (importChallengeFormat, TABULAR_HEADER)
static Model_mp_utype MP2s (importChallengeFormat, TABULAR_EVAL_ID)
static Model_mp_utype MP2s (importChallengeFormat, TABULAR_IFACE_ID)
static Model_mp_utype MP2s (importChallengeFormat, TABULAR_ANNOTATED)
static Model_mp_utype MP2s (modelExportFormat, ALGEBRAIC_FILE)
static Model_mp_utype MP2s (modelExportFormat, ALGEBRAIC_CONSOLE)
static Model_mp_utype MP2s (modelImportFormat, TEXT_ARCHIVE)
static Model_mp_utype MP2s (modelImportFormat, BINARY_ARCHIVE)
static Model_mp_utype MP2s (randomFieldIdForm, RF_KARHUNEN_LOEVE)
static Model_mp_utype MP2s (randomFieldIdForm, RF_PCA_GP)
static Model_mp_utype MP2s (subspaceNormalization, SUBSPACE_NORM_MEAN_VALUE)
static Model_mp_utype MP2s (subspaceNormalization, SUBSPACE_NORM_MEAN_GRAD)
static Model_mp_utype MP2s (subspaceNormalization, SUBSPACE_NORM_LOCAL_GRAD)
static Model_mp_utype MP2s (subspaceSampleType, SUBMETHOD_LHS)
static Model_mp_utype MP2s (subspaceSampleType, SUBMETHOD_RANDOM)
static Model_mp_utype MP2s (subspaceIdCVMethod, MINIMUM_METRIC)
static Model_mp_utype MP2s (subspaceIdCVMethod, RELATIVE_TOLERANCE)
static Model_mp_utype MP2s (subspaceIdCVMethod, DECREASE_TOLERANCE)
static Real MP_ (adaptedBasisCollocRatio)
static Real MP_ (annRange)
static Real MP_ (decreaseTolerance)
static Real MP_ (discontGradThresh)
static Real MP_ (discontJumpThresh)
static Real MP_ (krigingNugget)
static Real MP_ (percentFold)
static Real MP_ (relTolerance)
static Real MP_ (truncationTolerance)
static Real MP_ (adaptedBasisTruncationTolerance)
static RealVector MP_ (krigingCorrelations)
static RealVector MP_ (primaryRespCoeffs)
static RealVector MP_ (secondaryRespCoeffs)
static RealVector MP_ (solutionLevelCost)
static String MP_ (costRecoveryMetadata)
static String MP_ (decompCellType)
static String MP_ (exportApproxVarianceFile)
static String MP_ (idModel)
static String MP_ (importChallengePtsFile)
static String MP_ (interfacePointer)
static String MP_ (krigingOptMethod)
static String MP_ (modelImportPrefix)
static String MP_ (optionalInterfRespPointer)
static String MP_ (propagationModelPointer)
static String MP_ (refineCVMetric)
static String MP_ (responsesPointer)
static String MP_ (rfDataFileName)
static String MP_ (solutionLevelControl)
static String MP_ (truthModelPointer)
static String MP_ (variablesPointer)
static StringArray MP_ (diagMetrics)
static StringArray MP_ (ensembleModelPointers)
static StringArray MP_ (primaryVarMaps)
static StringArray MP_ (secondaryVarMaps)
static bool MP_ (autoRefine)
static bool MP_ (crossValidateFlag)
static bool MP_ (decompDiscontDetect)
static bool MP_ (importSurrogate)
static bool MP_ (hierarchicalTags)
static bool MP_ (identityRespMap)
static bool MP_ (importChallengeActive)
static bool MP_ (importChalUseVariableLabels)
static bool MP_ (importUseVariableLabels)
static bool MP_ (modelUseDerivsFlag)
static bool MP_ (domainDecomp)
static bool MP_ (pointSelection)
static bool MP_ (pressFlag)
static bool MP_ (subspaceIdBingLi)
static bool MP_ (subspaceIdConstantine)
static bool MP_ (subspaceIdEnergy)
static bool MP_ (subspaceBuildSurrogate)
static bool MP_ (subspaceIdCV)
static bool MP_ (subspaceCVIncremental)
static unsigned short MP_ (adaptedBasisSparseGridLev)
static unsigned short MP_ (adaptedBasisExpOrder)
static short MP_ (annNodes)
static short MP_ (annRandomWeight)
static short MP_ (c3AdvanceType)
static short MP_ (krigingFindNugget)
static short MP_ (krigingMaxTrials)
static short MP_ (marsMaxBases)
static short MP_ (mlsWeightFunction)
static short MP_ (rbfBases)
static short MP_ (rbfMaxPts)
static short MP_ (rbfMaxSubsets)
static short MP_ (rbfMinPartition)
static int MP_ (decompSupportLayers)
static int MP_ (initialSamples)
static int MP_ (numFolds)
static int MP_ (numReplicates)
static int MP_ (numRestarts)
static int MP_ (pointsTotal)
static int MP_ (refineCVFolds)
static int MP_ (softConvergenceLimit)
static int MP_ (subMethodProcs)
static int MP_ (subMethodServers)
static int MP_ (subspaceDimension)
static int MP_ (subspaceCVMaxRank)
static IntSet MP_ (idAnalyticGrads)
static IntSet MP_ (idAnalyticHessians)
static IntSet MP_ (idNumericalGrads)
static IntSet MP_ (idNumericalHessians)
static IntSet MP_ (idQuasiHessians)
static IntVector MP_ (fieldLengths)
static IntVector MP_ (numCoordsPerField)
static RealVector MP_ (expConfigVars)
static RealVector MP_ (expObservations)
static RealVector MP_ (primaryRespFnWeights)
static RealVector MP_ (nonlinearEqTargets)
static RealVector MP_ (nonlinearIneqLowerBnds)
static RealVector MP_ (nonlinearIneqUpperBnds)
static RealVector MP_ (simVariance)
static RealVector MP_ (fdGradStepSize)
static RealVector MP_ (fdHessStepSize)
static RealVector MP_ (primaryRespFnScales)
static RealVector MP_ (nonlinearEqScales)
static RealVector MP_ (nonlinearIneqScales)
static Resp_mp_lit MP2 (gradientType, analytic)
static Resp_mp_lit MP2 (gradientType, mixed)
static Resp_mp_lit MP2 (gradientType, none)
static Resp_mp_lit MP2 (gradientType, numerical)
static Resp_mp_lit MP2 (hessianType, analytic)
static Resp_mp_lit MP2 (hessianType, mixed)
static Resp_mp_lit MP2 (hessianType, none)
static Resp_mp_lit MP2 (hessianType, numerical)
static Resp_mp_lit MP2 (hessianType, quasi)
static Resp_mp_lit MP2 (intervalType, central)
static Resp_mp_lit MP2 (intervalType, forward)
static Resp_mp_lit MP2 (methodSource, dakota)
static Resp_mp_lit MP2 (methodSource, vendor)
static Resp_mp_lit MP2 (fdGradStepType, absolute)
static Resp_mp_lit MP2 (fdGradStepType, bounds)
static Resp_mp_lit MP2 (fdGradStepType, relative)
static Resp_mp_lit MP2 (fdHessStepType, absolute)
static Resp_mp_lit MP2 (fdHessStepType, bounds)
static Resp_mp_lit MP2 (fdHessStepType, relative)
static Resp_mp_lit MP2 (quasiHessianType, bfgs)
static Resp_mp_lit MP2 (quasiHessianType, damped_bfgs)
static Resp_mp_lit MP2 (quasiHessianType, sr1)
static String MP_ (dataPathPrefix)
static String MP_ (scalarDataFileName)
static String MP_ (idResponses)
static StringArray MP_ (metadataLabels)
static StringArray MP_ (nonlinearEqScaleTypes)
static StringArray MP_ (nonlinearIneqScaleTypes)
static StringArray MP_ (primaryRespFnScaleTypes)
static StringArray MP_ (primaryRespFnSense)
static StringArray MP_ (responseLabels)
static StringArray MP_ (varianceType)
static bool MP_ (calibrationDataFlag)
static bool MP_ (centralHess)
static bool MP_ (interpolateFlag)
static bool MP_ (ignoreBounds)
static bool MP_ (readFieldCoords)
static size_t MP_ (numExpConfigVars)
static size_t MP_ (numExperiments)
static size_t MP_ (numFieldLeastSqTerms)
static size_t MP_ (numFieldObjectiveFunctions)
static size_t MP_ (numFieldResponseFunctions)
static size_t MP_ (numLeastSqTerms)
static size_t MP_ (numNonlinearEqConstraints)
static size_t MP_ (numNonlinearIneqConstraints)
static size_t MP_ (numObjectiveFunctions)
static size_t MP_ (numResponseFunctions)
static size_t MP_ (numScalarLeastSqTerms)
static size_t MP_ (numScalarObjectiveFunctions)
static size_t MP_ (numScalarResponseFunctions)
static Resp_mp_utype MP2s (scalarDataFormat, TABULAR_NONE)
static Resp_mp_utype MP2s (scalarDataFormat, TABULAR_HEADER)
static Resp_mp_utype MP2s (scalarDataFormat, TABULAR_EVAL_ID)
static Resp_mp_utype MP2s (scalarDataFormat, TABULAR_EXPER_ANNOT)
static Env_mp_utype MP2s (postRunInputFormat, TABULAR_NONE)
static Env_mp_utype MP2s (postRunInputFormat, TABULAR_HEADER)
static Env_mp_utype MP2s (postRunInputFormat, TABULAR_EVAL_ID)
static Env_mp_utype MP2s (postRunInputFormat, TABULAR_IFACE_ID)
static Env_mp_utype MP2s (postRunInputFormat, TABULAR_ANNOTATED)
static Env_mp_utype MP2s (preRunOutputFormat, TABULAR_NONE)
static Env_mp_utype MP2s (preRunOutputFormat, TABULAR_HEADER)
static Env_mp_utype MP2s (preRunOutputFormat, TABULAR_EVAL_ID)
static Env_mp_utype MP2s (preRunOutputFormat, TABULAR_IFACE_ID)
static Env_mp_utype MP2s (preRunOutputFormat, TABULAR_ANNOTATED)
static Env_mp_utype MP2s (tabularFormat, TABULAR_NONE)
static Env_mp_utype MP2s (tabularFormat, TABULAR_HEADER)
static Env_mp_utype MP2s (tabularFormat, TABULAR_EVAL_ID)
static Env_mp_utype MP2s (tabularFormat, TABULAR_IFACE_ID)
static Env_mp_utype MP2s (tabularFormat, TABULAR_ANNOTATED)
static Env_mp_utype MP2s (resultsOutputFormat, RESULTS_OUTPUT_TEXT)
static Env_mp_utype MP2s (resultsOutputFormat, RESULTS_OUTPUT_HDF5)
static Env_mp_utype MP2s (modelEvalsSelection, MODEL_EVAL_STORE_TOP_METHOD)
static Env_mp_utype MP2s (modelEvalsSelection, MODEL_EVAL_STORE_NONE)
static Env_mp_utype MP2s (modelEvalsSelection, MODEL_EVAL_STORE_ALL)
static Env_mp_utype MP2s (modelEvalsSelection, MODEL_EVAL_STORE_ALL_METHODS)
static Env_mp_utype MP2s (interfEvalsSelection, INTERF_EVAL_STORE_SIMULATION)
static Env_mp_utype MP2s (interfEvalsSelection, INTERF_EVAL_STORE_NONE)
static Env_mp_utype MP2s (interfEvalsSelection, INTERF_EVAL_STORE_ALL)
static String MP_ (errorFile)
static String MP_ (outputFile)
static String MP_ (postRunInput)
static String MP_ (postRunOutput)
static String MP_ (preRunInput)
static String MP_ (preRunOutput)
static String MP_ (readRestart)
static String MP_ (resultsOutputFile)
static String MP_ (runInput)
static String MP_ (runOutput)
static String MP_ (tabularDataFile)
static String MP_ (topMethodPointer)
static String MP_ (writeRestart)
static bool MP_ (checkFlag)
static bool MP_ (graphicsFlag)
static bool MP_ (postRunFlag)
static bool MP_ (preRunFlag)
static bool MP_ (resultsOutputFlag)
static bool MP_ (runFlag)
static bool MP_ (tabularDataFlag)
static int MP_ (outputPrecision)
static int MP_ (stopRestart)
static size_t MP_ (numBetaUncVars)
static size_t MP_ (numBinomialUncVars)
static size_t MP_ (numContinuousDesVars)
static size_t MP_ (numContinuousIntervalUncVars)
static size_t MP_ (numContinuousStateVars)
static size_t MP_ (numDiscreteDesRangeVars)
static size_t MP_ (numDiscreteDesSetIntVars)
static size_t MP_ (numDiscreteDesSetStrVars)
static size_t MP_ (numDiscreteDesSetRealVars)
static size_t MP_ (numDiscreteIntervalUncVars)
static size_t MP_ (numDiscreteStateRangeVars)
static size_t MP_ (numDiscreteStateSetIntVars)
static size_t MP_ (numDiscreteStateSetStrVars)
static size_t MP_ (numDiscreteStateSetRealVars)
static size_t MP_ (numDiscreteUncSetIntVars)
static size_t MP_ (numDiscreteUncSetStrVars)
static size_t MP_ (numDiscreteUncSetRealVars)
static size_t MP_ (numExponentialUncVars)
static size_t MP_ (numFrechetUncVars)
static size_t MP_ (numGammaUncVars)
static size_t MP_ (numGeometricUncVars)
static size_t MP_ (numGumbelUncVars)
static size_t MP_ (numHistogramBinUncVars)
static size_t MP_ (numHistogramPtIntUncVars)
static size_t MP_ (numHistogramPtStrUncVars)
static size_t MP_ (numHistogramPtRealUncVars)
static size_t MP_ (numHyperGeomUncVars)
static size_t MP_ (numLognormalUncVars)
static size_t MP_ (numLoguniformUncVars)
static size_t MP_ (numNegBinomialUncVars)
static size_t MP_ (numNormalUncVars)
static size_t MP_ (numPoissonUncVars)
static size_t MP_ (numTriangularUncVars)
static size_t MP_ (numUniformUncVars)
static size_t MP_ (numWeibullUncVars)
static IntVector VP_ (ddsi)
static IntVector VP_ (DIlb)
static IntVector MP_ (discreteDesignRangeLowerBnds)
static IntVector MP_ (discreteDesignRangeUpperBnds)
static IntVector MP_ (discreteDesignRangeVars)
static IntVector MP_ (discreteDesignSetIntVars)
static IntVector MP_ (discreteIntervalUncVars)
static IntVector MP_ (discreteStateRangeLowerBnds)
static IntVector MP_ (discreteStateRangeUpperBnds)
static IntVector MP_ (discreteStateRangeVars)
static IntVector MP_ (discreteStateSetIntVars)
static IntVector MP_ (discreteUncSetIntVars)
static IntVector VP_ (DIub)
static IntVector MP_ (histogramPointIntUncVars)
static IntVector VP_ (hpia)
static IntVector VP_ (dssi)
static IntVector VP_ (ddsia)
static IntVector VP_ (ddssa)
static IntVector VP_ (ddsra)
static IntVector VP_ (dusi)
static IntArray VP_ (nddsi)
static IntArray VP_ (nddss)
static IntArray VP_ (nddsr)
static IntArray VP_ (ndssi)
static IntArray VP_ (ndsss)
static IntArray VP_ (ndssr)
static IntArray VP_ (ndusi)
static IntArray VP_ (nduss)
static IntArray VP_ (ndusr)
static IntArray VP_ (nhbp)
static IntArray VP_ (nhpip)
static IntArray VP_ (nhpsp)
static IntArray VP_ (nhprp)
static IntArray VP_ (nCI)
static IntArray VP_ (nDI)
static RealVector MP_ (betaUncLowerBnds)
static RealVector MP_ (betaUncUpperBnds)
static RealVector MP_ (betaUncVars)
static RealVector MP_ (binomialUncProbPerTrial)
static RealVector MP_ (continuousDesignLowerBnds)
static RealVector MP_ (continuousDesignUpperBnds)
static RealVector MP_ (continuousDesignVars)
static RealVector MP_ (continuousDesignScales)
static RealVector MP_ (continuousIntervalUncVars)
static RealVector MP_ (continuousStateLowerBnds)
static RealVector MP_ (continuousStateUpperBnds)
static RealVector MP_ (continuousStateVars)
static RealVector MP_ (discreteDesignSetRealVars)
static RealVector MP_ (discreteStateSetRealVars)
static RealVector MP_ (discreteUncSetRealVars)
static RealVector MP_ (frechetUncBetas)
static RealVector MP_ (frechetUncVars)
static RealVector MP_ (geometricUncProbPerTrial)
static RealVector MP_ (gumbelUncBetas)
static RealVector MP_ (gumbelUncVars)
static RealVector MP_ (histogramBinUncVars)
static RealVector MP_ (histogramPointRealUncVars)
static RealVector MP_ (linearEqConstraintCoeffs)
static RealVector MP_ (linearEqScales)
static RealVector MP_ (linearEqTargets)
static RealVector MP_ (linearIneqConstraintCoeffs)
static RealVector MP_ (linearIneqLowerBnds)
static RealVector MP_ (linearIneqUpperBnds)
static RealVector MP_ (linearIneqScales)
static RealVector MP_ (negBinomialUncProbPerTrial)
static RealVector MP_ (normalUncLowerBnds)
static RealVector MP_ (normalUncMeans)
static RealVector MP_ (normalUncUpperBnds)
static RealVector MP_ (normalUncVars)
static RealVector MP_ (triangularUncModes)
static RealVector MP_ (triangularUncVars)
static RealVector MP_ (uniformUncVars)
static RealVector MP_ (weibullUncVars)
static RealVector VP_ (ddsr)
static RealVector VP_ (dssr)
static RealVector VP_ (dusr)
static RealVector VP_ (CIlb)
static RealVector VP_ (CIub)
static RealVector VP_ (CIp)
static RealVector VP_ (DIp)
static RealVector VP_ (DSIp)
static RealVector VP_ (DSSp)
static RealVector VP_ (DSRp)
static RealVector VP_ (hba)
static RealVector VP_ (hbo)
static RealVector VP_ (hbc)
static RealVector VP_ (hpic)
static RealVector VP_ (hpsc)
static RealVector VP_ (hpra)
static RealVector VP_ (hprc)
static RealVector VP_ (ucm)
static String MP_ (idVariables)
static StringArray MP_ (continuousDesignLabels)
static StringArray MP_ (continuousDesignScaleTypes)
static StringArray MP_ (continuousStateLabels)
static StringArray MP_ (discreteDesignRangeLabels)
static StringArray MP_ (discreteDesignSetIntLabels)
static StringArray MP_ (discreteDesignSetStrLabels)
static StringArray MP_ (discreteDesignSetRealLabels)
static StringArray MP_ (discreteStateRangeLabels)
static StringArray MP_ (discreteStateSetIntLabels)
static StringArray MP_ (discreteStateSetStrLabels)
static StringArray MP_ (discreteStateSetRealLabels)
static StringArray MP_ (discreteDesignSetStrVars)
static StringArray MP_ (discreteUncSetStrVars)
static StringArray MP_ (discreteStateSetStrVars)
static StringArray MP_ (histogramPointStrUncVars)
static StringArray MP_ (linearEqScaleTypes)
static StringArray MP_ (linearIneqScaleTypes)
static StringArray VP_ (hpsa)
static StringArray VP_ (ddss)
static StringArray VP_ (duss)
static StringArray VP_ (dsss)
static BitArray MP_ (discreteDesignSetIntCat)
static BitArray MP_ (discreteDesignSetRealCat)
static BitArray MP_ (discreteStateSetIntCat)
static BitArray MP_ (discreteStateSetRealCat)
static BitArray MP_ (discreteUncSetIntCat)
static BitArray MP_ (discreteUncSetRealCat)
static Var_brv MP2s (betaUncAlphas, 0.)
static Var_brv MP2s (betaUncBetas, 0.)
static Var_brv MP2s (exponentialUncBetas, 0.)
static Var_brv MP2s (exponentialUncVars, 0.)
static Var_brv MP2s (frechetUncAlphas, 2.)
static Var_brv MP2s (gammaUncAlphas, 0.)
static Var_brv MP2s (gammaUncBetas, 0.)
static Var_brv MP2s (gammaUncVars, 0.)
static Var_brv MP2s (gumbelUncAlphas, 0.)
static Var_brv MP2s (lognormalUncErrFacts, 1.)
static Var_brv MP2s (lognormalUncLambdas, 0.)
static Var_brv MP2s (lognormalUncLowerBnds, 0.)
static Var_brv MP2s (lognormalUncMeans, 0.)
static Var_brv MP2s (lognormalUncStdDevs, 0.)
static Var_brv MP2s (lognormalUncUpperBnds, std::numeric_limits< Real >::infinity())
static Var_brv MP2s (lognormalUncVars, 0.)
static Var_brv MP2s (lognormalUncZetas, 0.)
static Var_brv MP2s (loguniformUncLowerBnds, 0.)
static Var_brv MP2s (loguniformUncUpperBnds, std::numeric_limits< Real >::infinity())
static Var_brv MP2s (loguniformUncVars, 0.)
static Var_brv MP2s (normalUncStdDevs, 0.)
static Var_brv MP2s (poissonUncLambdas, 0.)
static Var_brv MP2s (triangularUncLowerBnds,-std::numeric_limits< Real >::infinity())
static Var_brv MP2s (triangularUncUpperBnds, std::numeric_limits< Real >::infinity())
static Var_brv MP2s (uniformUncLowerBnds,-std::numeric_limits< Real >::infinity())
static Var_brv MP2s (uniformUncUpperBnds, std::numeric_limits< Real >::infinity())
static Var_brv MP2s (weibullUncAlphas, 0.)
static Var_brv MP2s (weibullUncBetas, 0.)
static Var_biv MP2s (binomialUncNumTrials, 0)
static Var_biv MP2s (binomialUncVars, 0)
static Var_biv MP2s (geometricUncVars, 0)
static Var_biv MP2s (hyperGeomUncNumDrawn, 0)
static Var_biv MP2s (hyperGeomUncSelectedPop, 0)
static Var_biv MP2s (hyperGeomUncTotalPop, 0)
static Var_biv MP2s (hyperGeomUncVars, 0)
static Var_biv MP2s (negBinomialUncNumTrials, 0)
static Var_biv MP2s (negBinomialUncVars, 0)
static Var_biv MP2s (poissonUncVars, 0)
static Var_mp_type Vtype (varsDomain, MIXED_DOMAIN)
static Var_mp_type Vtype (varsDomain, RELAXED_DOMAIN)
static Var_mp_type Vtype (varsView, ALL_VIEW)
static Var_mp_type Vtype (varsView, DESIGN_VIEW)
static Var_mp_type Vtype (varsView, UNCERTAIN_VIEW)
static Var_mp_type Vtype (varsView, ALEATORY_UNCERTAIN_VIEW)
static Var_mp_type Vtype (varsView, EPISTEMIC_UNCERTAIN_VIEW)
static Var_mp_type Vtype (varsView, STATE_VIEW)
template<class ContainerT >
void flatten_num_array (const std::vector< ContainerT > &input_array, IntArray **pia)
Free convenience function that flatten sizes of an array of std containers; takes an array of containers and returns an IntArray containing the sizes of each container in the input array. Note: Did not specialize for vector<RealVector> as no current use cases.
void dn2f_ (int *n, int *p, Real *x, Calcrj, int *iv, int *liv, int *lv, Real *v, int *ui, void *ur, Vf)
void dn2fb_ (int *n, int *p, Real *x, Real *b, Calcrj, int *iv, int *liv, int *lv, Real *v, int *ui, void *ur, Vf)
void dn2g_ (int *n, int *p, Real *x, Calcrj, Calcrj, int *iv, int *liv, int *lv, Real *v, int *ui, void *ur, Vf)
void dn2gb_ (int *n, int *p, Real *x, Real *b, Calcrj, Calcrj, int *iv, int *liv, int *lv, Real *v, int *ui, void *ur, Vf)
void divset_ (int *, int *, int *, int *, Real *)
double dr7mdc_ (int *)
static void Rswapchk (Nl2Misc *q)
static int hasnaninf (const double *d, int n)
NLPQLPOptimizer * new_NLPQLPOptimizer (ProblemDescDB &problem_db, Model &model)
NLPQLPOptimizer * new_NLPQLPOptimizer (Model &model)
void print_c3_sobol_indices (double value, size_t ninteract, size_t *interactions, void *arg)
static const RealVector * static_lev_cost_vec (NULL)
static size_t * static_qoi (NULL)
static const Real * static_eps_sq_div_2 (NULL)
static const RealVector * static_Nlq_pilot (NULL)
static const size_t * static_numFunctions (NULL)
static const size_t * static_qoiAggregation (NULL)
static int * static_randomSeed (NULL)
static const IntRealMatrixMap * static_sum_Ql (NULL)
static const IntRealMatrixMap * static_sum_Qlm1 (NULL)
static const IntIntPairRealMatrixMap * static_sum_QlQlm1 (NULL)
static const RealMatrix * static_scalarization_response_mapping (NULL)
static const IntRealMatrixMap * static_levQoisamplesmatrixMap (NULL)
static const short * static_cov_approximation_type (NULL)
static const Real * static_mu_four_L (NULL)
static const Real * static_mu_four_H (NULL)
static const Real * static_var_L (NULL)
static const Real * static_var_H (NULL)
static const Real * static_Ax (NULL)
NOWPACOptimizer * new_NOWPACOptimizer (ProblemDescDB &problem_db, Model &model)
NOWPACOptimizer * new_NOWPACOptimizer (Model &model)
NPSOLOptimizer * new_NPSOLOptimizer (ProblemDescDB &problem_db)
NPSOLOptimizer * new_NPSOLOptimizer1 (Model &model)
NPSOLOptimizer * new_NPSOLOptimizer2 (Model &model, int derivative_level, Real conv_tol)
NPSOLOptimizer * new_NPSOLOptimizer3 (const RealVector &cv_initial, const RealVector &cv_lower_bnds, const RealVector &cv_upper_bnds, const RealMatrix &lin_ineq_coeffs, const RealVector &lin_ineq_lower_bnds, const RealVector &lin_ineq_upper_bnds, const RealMatrix &lin_eq_coeffs, const RealVector &lin_eq_targets, const RealVector &nonlin_ineq_lower_bnds, const RealVector &nonlin_ineq_upper_bnds, const RealVector &nonlin_eq_targets, void(*user_obj_eval)(int &, int &, double *, double &, double *, int &), void(*user_con_eval)(int &, int &, int &, int &, int *, double *, double *, double *, int &), int derivative_level, Real conv_tol)
NPSOLOptimizer * new_NPSOLOptimizer (ProblemDescDB &problem_db, Model &model)
NPSOLOptimizer * new_NPSOLOptimizer (Model &model)
NPSOLOptimizer * new_NPSOLOptimizer (Model &model, int, Real)
NPSOLOptimizer * new_NPSOLOptimizer (const RealVector &cv_initial, const RealVector &cv_lower_bnds, const RealVector &cv_upper_bnds, const RealMatrix &lin_ineq_coeffs, const RealVector &lin_ineq_lower_bnds, const RealVector &lin_ineq_upper_bnds, const RealMatrix &lin_eq_coeffs, const RealVector &lin_eq_targets, const RealVector &nonlin_ineq_lower_bnds, const RealVector &nonlin_ineq_upper_bnds, const RealVector &nonlin_eq_targets, void(*user_obj_eval)(int &, int &, double *, double &, double *, int &), void(*user_con_eval)(int &, int &, int &, int &, int *, double *, double *, double *, int &), int derivative_level, Real conv_tol)
void start_dakota_heartbeat (int)
void dak_sigcatch (int sig)
MPIUnpackBuffer & operator>> (MPIUnpackBuffer &s, ParallelLevel &pl)
MPIUnpackBuffer extraction operator for ParallelLevel. Calls read(MPIUnpackBuffer&).
MPIPackBuffer & operator<< (MPIPackBuffer &s, const ParallelLevel &pl)
MPIPackBuffer insertion operator for ParallelLevel. Calls write(MPIPackBuffer&).
std::istream & operator>> (std::istream &s, ParamResponsePair &pair)
std::istream extraction operator for ParamResponsePair
std::ostream & operator<< (std::ostream &s, const ParamResponsePair &pair)
std::ostream insertion operator for ParamResponsePair
MPIUnpackBuffer & operator>> (MPIUnpackBuffer &s, ParamResponsePair &pair)
MPIUnpackBuffer extraction operator for ParamResponsePair.
MPIPackBuffer & operator<< (MPIPackBuffer &s, const ParamResponsePair &pair)
MPIPackBuffer insertion operator for ParamResponsePair.
bool operator== (const ParamResponsePair &pair1, const ParamResponsePair &pair2)
equality operator for ParamResponsePair
bool operator!= (const ParamResponsePair &pair1, const ParamResponsePair &pair2)
inequality operator for ParamResponsePair
void copy_gradient (int const fun_idx, std::vector< std::vector< double >> const &source, RealMatrix &dest)
void copy_hessian (std::vector< std::vector< double >> const &source, RealSymMatrix &dest)
static void Bad_name (const String &entry_name, const String &where)
static void Locked_db ()
static void Null_rep (const String &who)
std::pair< std::string, std::string > split_entry_name (const std::string &entry_name, const std::string &context_msg)
boost::regex PARAMS_TOKEN ("\\{PARAMETERS\\}")
boost::regex RESULTS_TOKEN ("\\{RESULTS\\}")
String substitute_params_and_results (const String &driver, const String &params, const String &results)
Substitute parameters and results file names into driver strings.
MPIUnpackBuffer & operator>> (MPIUnpackBuffer &s, ProgramOptions &p_opt)
MPIUnpackBuffer extraction operator.
MPIPackBuffer & operator<< (MPIPackBuffer &s, const ProgramOptions &p_opt)
MPIPackBuffer insertion operator.
bool set_compare (const ParamResponsePair &database_pr, const ActiveSet &search_set)
search function for a particular ParamResponsePair within a PRPList based on ActiveSet content (request vector and derivative variables vector)
bool id_vars_exact_compare (const ParamResponsePair &database_pr, const ParamResponsePair &search_pr)
search function for a particular ParamResponsePair within a PRPMultiIndex
std::size_t hash_value (const ParamResponsePair &prp)
hash_value for ParamResponsePairs stored in a PRPMultiIndex
PRPCacheHIter hashedCacheBegin (PRPCache &prp_cache)
hashed definition of cache begin
PRPCacheHIter hashedCacheEnd (PRPCache &prp_cache)
hashed definition of cache end
PRPQueueHIter hashedQueueBegin (PRPQueue &prp_queue)
hashed definition of queue begin
PRPQueueHIter hashedQueueEnd (PRPQueue &prp_queue)
hashed definition of queue end
PRPCacheHIter lookup_by_val (PRPMultiIndexCache &prp_cache, const ParamResponsePair &search_pr)
find a ParamResponsePair based on the interface id, variables, and ActiveSet search data within search_pr.
PRPCacheHIter lookup_by_val (PRPMultiIndexCache &prp_cache, const String &search_interface_id, const Variables &search_vars, const ActiveSet &search_set)
find a ParamResponsePair within a PRPMultiIndexCache based on the interface id, variables, and ActiveSet search data
PRPCacheOIter lookup_by_nearby_val (PRPMultiIndexCache &prp_cache, const String &search_interface_id, const Variables &search_vars, const ActiveSet &search_set, Real tol)
PRPCacheOIter lookup_by_ids (PRPMultiIndexCache &prp_cache, const IntStringPair &search_ids)
find a ParamResponsePair within a PRPMultiIndexCache based on search_ids (i.e. std::pair<eval_id,interface_id>) search data
PRPCacheOIter lookup_by_ids (PRPMultiIndexCache &prp_cache, const IntStringPair &search_ids, const ParamResponsePair &search_pr)
PRPQueueHIter lookup_by_val (PRPMultiIndexQueue &prp_queue, const ParamResponsePair &search_pr)
find a ParamResponsePair based on the interface id, variables, and ActiveSet search data within search_pr.
PRPQueueHIter lookup_by_val (PRPMultiIndexQueue &prp_queue, const String &search_interface_id, const Variables &search_vars, const ActiveSet &search_set)
find a ParamResponsePair within a PRPMultiIndexQueue based on interface id, variables, and ActiveSet search data
PRPQueueOIter lookup_by_eval_id (PRPMultiIndexQueue &prp_queue, int search_id)
find a ParamResponsePair within a PRPMultiIndexQueue based on search_id (i.e. integer eval_id) search data
void print_usage (std::ostream &s)
print restart utility help message
void print_restart (StringArray pos_args, String print_dest)
print a restart file
void print_restart_pdb (StringArray pos_args, String print_dest)
print a restart file (PDB format)
void print_restart_tabular (StringArray pos_args, String print_dest, unsigned short tabular_format, int tabular_precision)
print a restart file (tabular format)
void read_neutral (StringArray pos_args)
read a restart file (neutral file format)
void repair_restart (StringArray pos_args, String identifier_type)
repair a restart file by removing corrupted evaluations
void concatenate_restart (StringArray pos_args)
concatenate multiple restart files
String method_results_hdf5_link_name (const StrStrSizet &iterator_id)
Create a method results name (HDF5 link name) from iterator_id.
String method_hdf5_link_name (const StrStrSizet &iterator_id)
Create a method name (HDF5 link name) from iterator_id.
String execution_hdf5_link_name (const StrStrSizet &iterator_id)
Create an execution name (HDF5 link name) from iterator_id.
String object_hdf5_link_name (const StrStrSizet &iterator_id, const StringArray &location)
template<typename ScaleType >
String scale_hdf5_link_name (const StrStrSizet &iterator_id, const StringArray &location, const ScaleType &scale)
Create a scale name (hdf5 link name) for a scale from an iterator_id, the name of the result, the name of the response (can be empty), and the scale itself.
template<typename T >
void expand_for_fields_sdv (const SharedResponseData &srd, const T &src_array, const String &src_desc, bool allow_by_element, T &expanded_array)
expand primary response specs in SerialDenseVectors, e.g. scales, for fields no change on empty, expands 1 and num_groups, copies num_elements
template<typename T >
void expand_for_fields_stl (const SharedResponseData &srd, const T &src_array, const String &src_desc, bool allow_by_element, T &expanded_array)
expand primary response specs in STL containers, e.g. scale types, for fields no change on empty, expands 1 and num_groups, copies num_elements
static HANDLE * wait_setup (std::map< pid_t, int > *M, size_t *pn)
static int wait_for_one (size_t n, HANDLE *h, int req1, size_t *pi)
void gauss_legendre_pts_wts_1D (int level, RealVector &result_0, RealVector &result_1)
void lagrange_interpolation_1d (const RealVector &samples, const RealVector &abscissa, const RealVector &values, RealVector &result)
void kronecker_product_2d (const RealMatrix &matrix1, const RealMatrix &matrix2, RealMatrix &matrix)
void get_chebyshev_points (int order, RealVector &points)
void chebyshev_derivative_matrix (int order, RealMatrix &derivative_matrix, RealVector &points)
int salinas_main (int argc, char *argv[], MPI_Comm *comm)
subroutine interface to SALINAS simulation code
Real std_normal_coverage_inverse (const Real coverage)
Given a required coverage c \in [0,1], this routine computes the value b such that.
Real computeDSTIEN_conversion_factor (const size_t number_of_samples, const Real alpha)
This routine computes the multiplicative conversion factor to be applied to the sample standard deviation in order to get the standard deviation corresponding to the 'two sided tolerance interval equivalent normal' (DSTIEN).
void computeDSTIEN (const IntResponseMap &resp_samples, const Real coverage, const Real alpha, size_t &num_valid_samples, RealVector &dstien_mus, Real &delta_mf, RealVector &sample_sigmas, RealVector &dstien_sigmas)
This routine computes the r averages and r standard deviations corresponding to the 'two sided tolerance interval equivalent normal' (DSTIEN).
std::string get_cwd_str ()
std::vector< std::string > get_pathext ()
bool contains (const bfs::path &dir_path, const std::string &file_name, boost::filesystem::path &complete_filepath)
Variables
PRPCache data_pairs
contains all parameter/response pairs.
double PI = boost::math::constants::pi<double>()
constant pi
double HALF_LOG_2PI = std::log(2.0*PI)/2.0
constant log(2*pi)/2.0
short abort_mode = ABORT_EXITS
by default Dakota exits or calls MPI_Abort on errors
std::ostream * dakota_cout = &std::cout
DAKOTA stdout initially points to std::cout, but may be redirected to a tagged ofstream if there are concurrent iterators.
std::ostream * dakota_cerr = &std::cerr
DAKOTA stderr initially points to std::cerr, but may be redirected to a tagged ofstream if there are concurrent iterators.
ResultsManager iterator_results_db
Global results database for iterator results.
EvaluationStore evaluation_store_db
Global database for evaluation storage.
int write_precision = 10
used in ostream data output functions (restart_util.cpp overrides default value)
MPIManager dummy_mpi_mgr
dummy MPIManager for ref initialization
ProgramOptions dummy_prg_opt
dummy ProgramOptions for ref initialization
OutputManager dummy_out_mgr
dummy OutputManager for ref initialization
ParallelLibrary dummy_lib
dummy ParallelLibrary for ref initialization
ProblemDescDB dummy_db
dummy ProblemDescDB for ref initialization
int mc_ptr_int = 0
global pointer for ModelCenter API
int dc_ptr_int = 0
global pointer for ModelCenter eval DB
ProblemDescDB * Dak_pddb
set by ProblemDescDB, for use in parsing
const size_t SZ_MAX = std::numeric_limits<size_t>::max()
special value returned by index() when entry not found
const size_t _NPOS = SZ_MAX
const double BIG_REAL_BOUND = 1.0e+30
bound beyond which constraints are considered inactive
static UShortStrBimap method_map
bimap between method enums and strings; only used in this compilation unit
static UShortStrBimap submethod_map
bimap between sub-method enums and strings; only used in this compilation unit (using bimap for consistency, though at time of addition, only uni-directional mapping is supported)
Interface dummy_interface
dummy Interface object used for mandatory reference initialization or default virtual function return by reference when a real Interface instance is unavailable
Model dummy_model
dummy Model object used for mandatory reference initialization or default virtual function return by reference when a real Model instance is unavailable
Iterator dummy_iterator
dummy Iterator object used for mandatory reference initialization or default virtual function return by reference when a real Iterator instance is unavailable
Dakota_funcs * DF
Dakota_funcs DakFuncs0
const Real REAL_DSET_FILL_VAL = NAN
const int INT_DSET_FILL_VAL = INT_MAX
const String STR_DSET_FILL_VAL = ""
const int HDF5_CHUNK_SIZE = 40000
UInt32 cools_kuo_nuyens_d250_m20 [] = { 1, 182667, 469891, 498753, 110745, 446247, 250185, 118627, 245333, 283199, 408519, 391023, 246327, 126539, 399185, 461527, 300343, 69681, 516695, 436179, 106383, 238523, 413283, 70841, 47719, 300129, 113029, 123925, 410745, 211325, 17489, 511893, 40767, 186077, 519471, 255369, 101819, 243573, 66189, 152143, 503455, 113217, 132603, 463967, 297717, 157383, 224015, 502917, 36237, 94049, 170665, 79397, 123963, 223451, 323871, 303633, 98567, 318855, 494245, 477137, 177975, 64483, 26695, 88779, 94497, 239429, 381007, 110205, 339157, 73397, 407559, 181791, 442675, 301397, 32569, 147737, 189949, 138655, 350241, 63371, 511925, 515861, 434045, 383435, 249187, 492723, 479195, 84589, 99703, 239831, 269423, 182241, 61063, 130789, 143095, 471209, 139019, 172565, 487045, 304803, 45669, 380427, 19547, 425593, 337729, 237863, 428453, 291699, 238587, 110653, 196113, 465711, 141583, 224183, 266671, 169063, 317617, 68143, 291637, 263355, 427191, 200211, 365773, 254701, 368663, 248047, 209221, 279201, 323179, 80217, 122791, 316633, 118515, 14253, 129509, 410941, 402601, 511437, 10469, 366469, 463959, 442841, 54641, 44167, 19703, 209585, 69037, 33317, 433373, 55879, 245295, 10905, 468881, 128617, 417919, 45067, 442243, 359529, 51109, 290275, 168691, 212061, 217775, 405485, 313395, 256763, 152537, 326437, 332981, 406755, 423147, 412621, 362019, 279679, 169189, 107405, 251851, 5413, 316095, 247945, 422489, 2555, 282267, 121027, 369319, 204587, 445191, 337315, 322505, 388411, 102961, 506099, 399801, 254381, 452545, 309001, 147013, 507865, 32283, 320511, 264647, 417965, 227069, 341461, 466581, 386241, 494585, 201479, 151243, 481337, 68195, 75401, 58359, 448107, 459499, 9873, 365117, 350845, 181873, 7917, 436695, 43899, 348367, 423927, 437399, 385089, 21693, 268793, 49257, 250211, 125071, 341631, 310163, 94631, 108795, 21175, 142847, 383599, 71105, 65989, 446433, 177457, 107311, 295679, 442763, 40729, 322721, 420175, 430359, 480757 }
Generating vector from Cools, Kuo and Nuyens (2006)
UInt32 kuo_d3600_m20 [] = { 1, 182667, 469891, 498753, 110745, 446247, 250185, 118627, 245333, 283199, 408519, 391023, 246327, 126539, 399185, 461527, 300343, 69681, 516695, 436179, 106383, 238523, 413283, 70841, 47719, 300129, 113029, 123925, 410745, 211325, 17489, 511893, 40767, 186077, 519471, 255369, 101819, 243573, 66189, 152143, 503455, 113217, 132603, 463967, 297717, 157383, 224015, 502917, 36237, 94049, 170665, 79397, 123963, 223451, 323871, 303633, 98567, 318855, 494245, 477137, 177975, 64483, 26695, 88779, 94497, 239429, 381007, 110205, 339157, 73397, 407559, 181791, 442675, 301397, 32569, 147737, 189949, 138655, 350241, 63371, 511925, 515861, 434045, 383435, 249187, 492723, 479195, 84589, 99703, 239831, 269423, 182241, 61063, 130789, 143095, 471209, 139019, 172565, 487045, 304803, 45669, 380427, 19547, 425593, 337729, 237863, 428453, 291699, 238587, 110653, 196113, 465711, 141583, 224183, 266671, 169063, 317617, 68143, 291637, 263355, 427191, 200211, 365773, 254701, 368663, 248047, 209221, 279201, 323179, 80217, 122791, 316633, 118515, 14253, 129509, 410941, 402601, 511437, 10469, 366469, 463959, 442841, 54641, 44167, 19703, 209585, 69037, 33317, 433373, 55879, 245295, 10905, 468881, 128617, 417919, 45067, 442243, 359529, 51109, 290275, 168691, 212061, 217775, 405485, 313395, 256763, 152537, 326437, 332981, 406755, 423147, 412621, 362019, 279679, 169189, 107405, 251851, 5413, 316095, 247945, 422489, 2555, 282267, 121027, 369319, 204587, 445191, 337315, 322505, 388411, 102961, 506099, 399801, 254381, 452545, 309001, 147013, 507865, 32283, 320511, 264647, 417965, 227069, 341461, 466581, 386241, 494585, 201479, 151243, 481337, 68195, 75401, 58359, 448107, 459499, 9873, 365117, 350845, 181873, 7917, 436695, 43899, 348367, 423927, 437399, 385089, 21693, 268793, 49257, 250211, 125071, 341631, 310163, 94631, 108795, 21175, 142847, 383599, 71105, 65989, 446433, 177457, 107311, 295679, 442763, 40729, 322721, 420175, 430359, 480757, 221417, 460963, 263529, 263625, 16919, 289121, 243609, 414769, 147195, 326731, 277925, 185497, 29735, 11185, 212811, 371743, 33547, 250809, 390965, 486257, 348223, 263649, 241785, 425685, 240127, 447899, 182195, 306733, 465107, 434787, 239361, 437289, 183495, 75179, 431157, 376487, 141253, 293903, 399797, 325045, 277541, 215657, 263115, 193361, 478441, 299477, 319217, 176929, 279451, 32237, 346181, 374911, 443279, 319283, 306211, 70449, 88145, 272219, 178705, 159715, 177793, 164999, 16833, 49379, 83863, 223583, 22615, 225323, 111767, 361309, 182521, 154685, 426543, 482481, 122871, 250773, 324031, 227329, 465853, 165123, 163615, 245155, 192403, 364635, 276575, 195289, 439767, 386711, 472741, 6385, 435121, 299865, 151695, 344227, 505437, 130021, 254671, 165583, 129277, 513679, 155197, 147197, 161911, 408721, 134261, 56599, 410699, 110337, 18283, 393383, 222965, 244381, 89807, 198515, 219643, 467277, 69251, 227483, 90213, 405587, 225651, 349029, 365859, 448277, 284285, 85247, 8363, 235701, 168505, 11797, 326593, 482271, 181411, 424383, 486111, 136879, 467187, 523659, 357769, 102621, 120121, 253107, 11107, 410147, 315347, 1551, 60525, 265467, 404483, 174571, 303643, 12741, 486785, 382527, 264167, 438949, 73635, 149281, 482205, 150185, 256827, 108249, 38907, 511485, 437613, 401415, 196935, 228179, 207375, 366367, 55589, 84509, 108335, 371355, 384565, 35521, 175225, 111363, 61861, 183569, 406605, 71801, 211703, 132611, 241903, 215337, 235709, 415963, 274405, 4703, 240525, 416779, 243755, 157423, 286867, 227441, 254477, 462447, 276941, 111189, 144789, 368511, 321515, 355653, 330037, 193619, 172623, 357807, 255105, 265789, 348989, 399829, 88709, 147959, 397901, 25605, 426447, 223367, 281913, 109421, 354737, 97901, 221801, 483127, 331811, 284329, 200029, 472285, 161795, 142317, 521093, 375505, 103755, 166279, 57527, 161091, 215319, 485895, 25887, 89591, 240303, 253535, 491933, 137349, 26775, 1729, 409481, 468105, 114849, 396207, 131517, 179647, 82499, 270263, 507511, 126811, 392021, 290691, 144999, 409189, 25557, 217529, 292351, 418783, 192003, 162237, 300457, 283151, 244869, 372931, 245703, 124071, 1135, 286385, 256437, 277087, 351965, 88117, 379293, 177055, 5879, 372417, 277241, 204087, 28287, 510057, 509695, 148637, 173693, 18863, 410971, 490307, 158579, 180629, 292825, 56021, 161863, 391107, 441385, 41333, 88349, 248261, 414605, 250945, 258519, 519295, 428331, 82417, 297583, 236509, 193353, 521611, 252473, 8615, 315077, 356463, 168977, 225931, 471707, 523789, 283671, 107083, 338195, 64035, 422417, 114519, 179967, 228957, 249611, 300357, 414135, 316269, 482363, 349081, 247739, 257763, 514731, 459623, 273057, 190725, 16075, 225093, 263631, 304121, 456955, 185759, 447357, 463223, 507381, 91535, 293531, 336195, 338591, 233527, 475567, 202419, 497965, 427305, 292097, 87701, 46525, 425127, 162119, 91059, 509853, 439515, 193197, 489889, 247123, 72951, 19091, 32249, 175185, 401645, 481103, 156391, 461987, 274743, 258789, 363861, 329821, 441411, 494409, 523681, 275133, 476635, 356313, 301287, 370055, 223247, 474385, 235885, 464331, 100449, 154789, 354597, 46075, 509469, 293887, 118997, 94605, 130853, 62381, 446211, 110775, 441749, 11647, 441327, 518019, 266745, 303321, 428073, 439511, 327309, 370317, 99099, 92823, 47303, 508365, 122925, 371521, 413947, 381997, 128693, 338147, 68609, 298361, 142827, 78791, 110299, 74983, 399743, 248095, 446313, 211653, 42373, 380463, 305563, 287069, 174685, 350981, 87739, 118153, 130365, 288001, 85703, 370809, 261363, 243289, 127027, 450185, 230997, 96425, 165333, 329901, 166631, 451049, 124935, 425907, 187583, 426405, 407503, 481683, 436815, 36701, 230675, 142295, 384337, 97869, 174277, 105907, 411309, 442025, 420455, 275357, 36543, 399931, 369307, 300069, 198191, 275635, 74869, 395981, 154569, 425805, 209447, 511999, 311137, 401091, 114095, 123237, 409775, 313845, 411497, 307259, 252635, 486853, 415967, 393585, 252305, 248807, 429869, 19877, 238767, 465765, 251435, 31931, 9375, 394037, 482327, 226155, 276901, 145515, 515957, 58865, 432665, 317515, 202675, 194919, 363725, 167451, 496379, 88081, 429401, 193909, 464257, 21783, 255519, 173419, 4525, 396301, 323707, 301965, 58913, 181921, 392791, 517181, 199121, 150613, 498367, 353209, 362387, 426477, 30755, 481743, 79335, 242545, 193489, 154217, 152365, 248003, 160629, 450905, 119515, 312019, 221569, 470791, 42569, 305501, 107903, 322337, 40815, 2239, 45407, 377109, 222897, 408051, 334611, 102593, 474007, 449755, 395473, 183207, 445655, 359145, 480015, 506445, 415163, 459765, 240993, 348643, 311311, 301277, 506281, 478109, 106897, 475519, 295603, 329847, 177575, 127243, 272713, 304281, 50573, 349417, 131487, 502907, 412417, 397071, 147315, 235781, 255885, 421135, 161223, 77175, 331995, 78655, 211715, 301259, 219035, 127701, 83493, 61371, 300739, 312513, 466155, 314441, 345733, 156889, 487233, 146325, 73709, 23791, 469019, 429905, 210955, 512205, 237585, 38469, 380697, 299875, 275393, 388021, 354889, 266469, 293501, 186931, 124695, 432785, 242425, 107199, 57331, 200461, 371767, 159645, 217483, 299463, 443487, 387823, 288247, 231339, 69451, 167207, 474283, 288285, 35023, 310071, 52017, 377933, 184317, 236333, 100811, 6867, 225535, 495413, 237521, 165557, 466251, 494583, 41971, 325869, 497911, 107613, 261385, 254175, 420485, 345119, 271503, 474889, 79655, 131139, 494331, 204103, 56679, 30945, 103137, 387471, 375569, 347443, 84925, 109079, 121365, 28371, 23283, 402765, 45085, 203239, 332045, 280521, 511521, 420779, 457787, 308723, 213891, 340515, 6077, 469349, 317283, 193051, 84615, 26411, 111133, 384309, 89225, 15061, 451299, 253109, 283983, 272139, 224493, 457497, 198591, 60857, 170653, 516063, 63655, 176635, 496653, 142945, 181199, 271031, 262767, 431349, 82049, 441275, 496297, 469933, 413335, 194583, 105247, 500683, 139889, 100381, 440753, 193069, 5979, 193247, 301363, 33843, 221103, 132691, 130351, 367705, 132071, 410455, 5763, 280417, 359827, 30087, 290263, 357573, 86205, 65473, 144355, 146417, 84499, 5649, 518281, 65049, 42149, 145689, 314395, 235127, 205711, 182221, 346969, 227929, 428517, 31343, 431861, 300643, 498615, 100851, 488335, 310185, 322423, 497201, 484405, 444527, 51333, 413769, 65027, 412357, 287663, 99387, 508665, 134905, 337535, 351489, 290759, 513485, 391501, 139009, 514003, 360051, 194857, 214625, 190319, 193121, 279099, 188459, 465397, 444741, 1599, 376567, 502721, 300331, 309899, 105713, 221565, 209529, 226541, 168083, 172953, 480521, 41525, 503357, 513735, 20585, 509665, 415835, 268953, 318039, 318647, 61943, 406283, 159249, 243265, 86427, 356525, 161945, 88741, 155739, 30999, 469509, 416535, 516925, 20595, 492481, 118079, 67531, 93975, 254945, 460265, 32577, 286941, 461315, 229511, 205789, 123411, 228447, 405775, 316867, 12567, 480181, 507221, 463329, 360803, 271225, 433273, 489915, 164057, 389401, 61883, 365689, 120717, 7725, 97135, 145163, 311659, 517775, 47851, 109593, 472773, 400637, 19087, 293147, 484279, 38049, 331861, 226935, 451367, 60083, 507751, 256185, 159613, 478559, 466397, 243859, 474635, 69159, 75285, 471867, 436483, 194003, 332149, 521247, 221209, 459463, 195993, 201455, 15545, 137185, 204247, 474959, 324651, 121031, 328369, 486033, 104301, 256295, 306443, 275897, 321283, 350205, 330847, 367481, 475923, 207701, 494919, 336813, 267257, 227219, 472323, 78973, 513131, 225923, 434771, 483219, 114577, 357429, 165589, 408211, 494065, 77643, 355371, 286569, 35217, 179467, 36367, 443261, 142009, 354987, 186625, 817, 243731, 383875, 40125, 13155, 367409, 468829, 447387, 13997, 356469, 285679, 92327, 419925, 442095, 392039, 176961, 146825, 175823, 88141, 199553, 14927, 123441, 90739, 241217, 53023, 264725, 283201, 143723, 408395, 481677, 348225, 320161, 37003, 522423, 70665, 340285, 146281, 445675, 385085, 250727, 502921, 399081, 199841, 400747, 180879, 442621, 338349, 376305, 286299, 298983, 148231, 188293, 312811, 374571, 15025, 80623, 460867, 71815, 191007, 370419, 285835, 103895, 34305, 366809, 137355, 312313, 393671, 123371, 211783, 492741, 371635, 68305, 448925, 491667, 390687, 469303, 455913, 131369, 23171, 387865, 229647, 357387, 44221, 85497, 497103, 331905, 63131, 522595, 121011, 512597, 367289, 91267, 72693, 40989, 83659, 344031, 323869, 453437, 226351, 29011, 274231, 396789, 439683, 397207, 341859, 374821, 213971, 20097, 174827, 437687, 205455, 109395, 309329, 32869, 284877, 333319, 167233, 157959, 389749, 484567, 265265, 99497, 288789, 319989, 133933, 487021, 278713, 323331, 450597, 404371, 135937, 311647, 363539, 486493, 440019, 414487, 232917, 851, 429267, 93357, 383357, 112977, 390981, 139493, 117513, 482133, 447549, 14093, 218813, 320407, 212417, 34553, 38101, 185693, 185261, 474591, 502403, 204315, 476157, 118695, 262023, 217349, 433597, 276007, 205027, 497981, 159879, 450003, 78073, 449741, 394723, 276655, 302909, 73193, 485803, 128453, 190853, 448625, 423923, 450751, 84341, 88515, 278945, 15023, 460179, 432595, 31905, 81855, 83211, 460571, 125237, 2637, 206799, 382775, 96453, 467767, 96071, 332519, 175269, 187643, 337227, 378167, 6565, 317723, 435053, 39425, 377629, 240171, 210049, 141119, 341063, 318885, 239455, 110491, 65875, 335251, 336349, 77589, 157821, 62429, 522025, 168735, 130331, 489131, 446475, 116305, 262001, 99991, 482961, 421499, 245947, 359321, 38481, 321173, 161151, 406195, 7507, 72795, 256199, 306699, 314195, 438761, 181227, 349763, 431907, 26319, 441141, 44541, 486865, 326673, 379261, 361973, 521935, 19205, 90667, 231881, 287905, 269053, 128239, 251485, 423591, 503993, 225627, 155339, 518847, 374369, 329871, 219073, 360565, 54941, 244749, 414575, 281531, 229491, 321177, 287485, 301621, 206741, 340997, 231751, 389515, 347819, 176747, 161639, 429653, 445151, 94467, 224415, 291995, 497733, 414631, 418071, 233485, 470293, 96223, 76519, 181327, 105741, 25159, 491531, 160453, 314353, 99767, 337271, 113963, 467495, 30361, 499149, 13275, 67849, 351547, 452929, 237379, 392947, 337257, 190073, 294111, 201073, 216495, 25003, 513811, 316363, 211719, 258485, 274409, 187933, 227047, 250167, 430745, 285839, 44841, 215175, 181493, 234721, 467439, 457019, 509077, 359201, 11027, 429903, 268385, 97401, 139475, 412901, 384039, 216497, 22511, 368699, 428213, 124377, 436615, 360837, 429077, 400709, 514399, 241011, 80915, 66531, 173107, 524193, 65449, 357243, 472359, 457421, 276537, 332615, 121161, 30523, 66625, 493851, 75357, 72053, 138243, 498569, 241009, 482601, 166199, 302657, 272589, 92643, 492011, 118737, 308979, 6617, 305097, 466585, 318419, 149945, 380153, 291261, 259013, 88595, 476949, 41391, 170045, 256319, 295207, 372873, 438169, 196221, 49225, 200173, 269399, 202607, 299353, 221825, 391325, 248509, 183861, 62937, 370937, 308047, 208963, 362413, 230899, 518307, 187739, 460067, 391577, 434663, 35647, 286715, 294589, 389463, 162933, 411537, 167093, 65127, 121753, 344463, 516765, 414291, 128981, 243439, 470701, 437981, 342493, 322629, 504431, 383423, 468615, 402015, 262491, 225053, 195803, 145011, 460657, 289933, 490493, 258547, 51845, 284765, 300867, 142667, 50691, 172085, 353993, 500573, 254085, 113615, 519945, 129487, 277663, 164767, 416047, 155579, 248353, 109161, 382985, 388793, 507679, 299015, 274125, 204053, 431273, 513631, 483277, 36177, 471323, 306393, 17351, 87967, 382551, 4019, 377623, 114051, 355573, 523977, 484437, 271457, 199003, 108197, 271007, 344501, 234951, 157225, 409627, 129345, 96097, 264835, 255921, 338915, 251267, 277093, 73221, 392169, 183719, 139877, 344877, 195725, 163315, 6783, 43537, 244069, 362533, 97361, 189961, 240165, 118595, 452911, 427757, 314895, 494405, 21653, 399265, 330607, 369479, 491155, 31265, 434459, 288753, 84455, 293565, 460293, 21425, 61805, 437609, 259113, 305619, 234341, 408429, 294183, 424917, 521281, 437047, 430353, 81257, 393247, 382355, 131613, 299665, 20109, 201617, 185989, 428861, 94113, 511567, 412233, 429035, 519411, 314931, 519951, 77705, 87461, 333213, 284637, 7935, 371921, 237783, 428329, 442883, 322605, 277795, 103027, 85391, 176447, 43693, 323725, 311337, 344439, 208419, 93071, 25893, 395859, 451291, 448075, 173979, 397339, 491231, 93091, 454985, 351989, 302041, 361357, 67663, 170813, 387243, 224899, 20489, 484965, 313779, 361233, 469957, 332483, 62329, 246513, 168613, 11503, 177541, 333063, 195349, 295523, 259807, 142231, 269037, 482291, 299483, 252479, 283629, 240193, 320163, 486023, 520959, 63111, 10213, 431655, 439659, 147217, 411661, 308157, 321907, 501265, 419839, 371177, 513683, 419235, 162683, 346933, 37079, 455955, 491201, 343417, 111105, 516529, 47713, 171791, 388113, 247363, 484029, 169773, 250871, 439705, 249861, 93563, 276649, 347735, 275159, 444463, 444457, 340165, 238219, 511421, 3711, 293153, 433595, 498467, 328597, 462993, 242767, 280633, 188319, 147243, 59519, 10371, 109385, 421289, 519729, 311493, 55557, 62243, 332767, 132337, 502769, 190475, 220289, 368661, 101033, 159287, 346783, 88817, 322189, 297843, 22851, 314555, 30719, 226467, 316875, 64935, 348957, 411789, 321345, 100427, 196969, 216519, 212671, 238033, 470295, 428273, 85607, 368793, 146055, 169169, 38043, 26807, 146255, 400421, 174601, 491897, 233119, 387201, 348875, 68805, 187145, 20447, 486529, 60531, 124855, 456157, 471813, 183515, 375031, 107323, 448423, 283509, 379319, 417789, 209295, 238877, 395877, 427147, 23411, 223803, 22595, 108801, 322185, 58469, 483411, 394163, 413329, 354901, 522441, 109481, 168295, 269339, 238611, 503677, 437089, 379373, 57093, 91041, 125787, 324727, 177279, 50247, 416961, 506185, 404993, 374955, 52633, 301157, 236643, 167913, 393529, 178293, 73215, 385523, 260125, 486055, 449495, 58677, 375277, 320979, 451277, 330395, 438251, 310281, 317481, 126541, 214215, 475315, 315097, 318983, 317505, 474263, 496911, 125405, 43067, 33517, 389253, 42313, 129447, 421007, 362237, 227073, 126017, 479819, 210921, 79791, 198363, 384549, 329489, 44665, 356461, 134445, 135127, 449099, 155947, 168329, 365601, 353765, 419155, 150437, 119517, 298069, 28947, 35443, 413727, 269677, 366217, 136227, 155333, 464397, 130865, 241509, 320225, 137493, 271105, 75223, 375527, 143779, 112229, 245705, 112867, 411037, 89325, 237307, 161365, 484761, 207255, 206127, 321743, 384985, 442877, 263129, 211505, 325823, 85081, 445183, 409583, 283329, 65059, 131307, 243747, 387529, 423355, 2995, 491469, 125507, 411969, 27743, 437423, 506305, 259567, 3309, 286473, 358905, 160297, 4615, 42525, 152491, 237177, 171253, 356853, 320371, 66075, 134765, 365639, 276209, 498613, 353187, 176017, 29435, 113007, 501773, 207885, 370521, 345009, 148935, 43737, 36005, 386465, 137591, 20111, 52163, 84625, 67001, 244925, 408647, 90653, 112981, 416825, 192987, 291471, 408537, 370213, 487317, 195075, 484829, 452531, 491715, 175131, 296705, 182743, 401533, 145133, 47655, 106901, 385389, 333105, 495649, 198013, 490969, 15769, 517559, 360277, 99815, 523297, 61605, 140317, 140553, 206363, 373783, 441221, 331555, 53047, 15759, 252725, 100597, 410343, 471953, 159549, 327959, 441471, 110655, 283353, 356177, 63757, 264055, 154289, 234919, 175549, 66581, 218069, 47281, 185375, 94719, 117301, 486893, 239833, 54185, 320917, 67735, 104983, 304465, 440313, 470631, 28787, 381879, 207727, 98081, 119355, 141793, 522435, 499393, 95157, 251465, 93685, 247587, 462773, 360895, 193175, 47033, 421069, 240597, 9847, 496635, 353401, 21525, 514603, 215633, 324941, 266803, 195843, 457817, 297245, 87983, 247833, 404853, 209401, 130941, 371029, 274429, 141599, 340233, 402543, 243355, 502569, 219343, 316665, 409117, 467413, 167563, 8767, 490011, 31969, 244789, 173937, 488819, 279215, 331, 31395, 79851, 360451, 91743, 453003, 247647, 50239, 130511, 266153, 436609, 305001, 386119, 51055, 391537, 118293, 189295, 436559, 6587, 484879, 185985, 369453, 39209, 85417, 61079, 515227, 378617, 369691, 289961, 417129, 216939, 66181, 161249, 221775, 523799, 291817, 170383, 418119, 363171, 454299, 207721, 447149, 456603, 391507, 36489, 152227, 75227, 172843, 68107, 452955, 145421, 150221, 246009, 78407, 287993, 399961, 344161, 224507, 296827, 435787, 373389, 405083, 299121, 224369, 86133, 289307, 341689, 380379, 247229, 111781, 193173, 381567, 90409, 87017, 379085, 195549, 328503, 448819, 521439, 523211, 317559, 508697, 435439, 31307, 300425, 516943, 337803, 476487, 78833, 168493, 82991, 1813, 279039, 139735, 212037, 507637, 27191, 342299, 333581, 217225, 361105, 141349, 217139, 455297, 22027, 208285, 105195, 343399, 365187, 166003, 267747, 173265, 104309, 263875, 437963, 390657, 186295, 221165, 285495, 385165, 350075, 373929, 47901, 362017, 223307, 221823, 171781, 317267, 452633, 120487, 425947, 71937, 144669, 30537, 320807, 496709, 36143, 35249, 54399, 457465, 374257, 259027, 434899, 192051, 107773, 215557, 272847, 145053, 179531, 149193, 455445, 7111, 146859, 325841, 500423, 330427, 332067, 224651, 142941, 281513, 524213, 43221, 44235, 440259, 330081, 413537, 455371, 58199, 47729, 95937, 211567, 206227, 427361, 466909, 1005, 206647, 104791, 257555, 255555, 236197, 24417, 47507, 357477, 347973, 131241, 452411, 494475, 342379, 489111, 6675, 509787, 329523, 142947, 212759, 502533, 12323, 499179, 353173, 5519, 146257, 136979, 333593, 242981, 76435, 369869, 520221, 170155, 299129, 373969, 297759, 168945, 258359, 383557, 73439, 304311, 488225, 185907, 242127, 479013, 296237, 143831, 376901, 384261, 70843, 267839, 390079, 207373, 336845, 188153, 441483, 502729, 144489, 143595, 521973, 347585, 174495, 362967, 195351, 430933, 331571, 155305, 78807, 252037, 67461, 105441, 204725, 517849, 236481, 441255, 272255, 396343, 120681, 105631, 236671, 192703, 130503, 470853, 156907, 370583, 346321, 412653, 332919, 284217, 395281, 283305, 108461, 518885, 321629, 465913, 138519, 499083, 391627, 318493, 146001, 167501, 478239, 469563, 311423, 82501, 337647, 462381, 496957, 417031, 449591, 322099, 110997, 361467, 124215, 310941, 457079, 343763, 274689, 454023, 196851, 140011, 329071, 387481, 408773, 40235, 351537, 463559, 73109, 366319, 370429, 61679, 399063, 252481, 429989, 58691, 470643, 485623, 402333, 225503, 144559, 121153, 76475, 350553, 3935, 31375, 94239, 302415, 401575, 211757, 271075, 159559, 463171, 251429, 357403, 432513, 106507, 255729, 429641, 291489, 71215, 99219, 45203, 83541, 203975, 337455, 142077, 129255, 466479, 110353, 222145, 184543, 4223, 61693, 480821, 124743, 487855, 176403, 194931, 380825, 487637, 337069, 508087, 497721, 181339, 398547, 516409, 139969, 185615, 25049, 51321, 279923, 195797, 80977, 520641, 206053, 51091, 226235, 475763, 449191, 25233, 390933, 365715, 114355, 336241, 345473, 253533, 170419, 276927, 52391, 192871, 348987, 404949, 365431, 150615, 363203, 273999, 25469, 341535, 197597, 491999, 191295, 360335, 436757, 400821, 488647, 292951, 164863, 419047, 410339, 364887, 447227, 312255, 401577, 491153, 520151, 28657, 137485, 288963, 172713, 366519, 293067, 505061, 221561, 376689, 209791, 274969, 61145, 143303, 157459, 518153, 349473, 169179, 3579, 364721, 142975, 311275, 474695, 85031, 14031, 57731, 399487, 51707, 103261, 38863, 356271, 472975, 160727, 168239, 468851, 130069, 188281, 515097, 119167, 74835, 62219, 81827, 573, 464349, 323045, 201719, 332681, 131117, 288875, 509111, 341827, 59475, 352861, 83495, 3797, 30739, 454485, 411881, 167767, 168457, 268881, 425747, 186685, 351955, 108987, 475831, 222691, 399295, 422525, 353383, 397973, 200631, 91443, 267695, 217305, 454703, 479915, 357239, 383125, 425711, 449165, 505985, 470431, 12239, 514817, 348329, 304277, 465579, 128661, 238205, 432041, 30891, 324155, 486707, 189683, 124635, 76543, 335841, 330153, 42873, 33289, 404423, 432881, 372293, 56239, 22533, 479905, 378149, 245273, 141797, 343875, 146241, 271381, 297861, 424403, 36713, 211755, 387069, 243775, 216099, 258397, 100383, 459721, 415609, 330499, 417793, 87947, 314485, 5171, 472093, 133175, 517795, 57461, 159591, 518095, 385625, 477059, 301889, 278983, 449397, 430415, 484097, 214421, 64161, 484031, 252913, 147907, 497375, 79797, 321555, 36029, 403759, 306137, 106975, 278317, 352455, 311517, 257131, 98943, 513449, 68961, 295611, 9281, 106999, 37679, 410957, 356071, 237009, 452951, 120029, 4327, 299495, 302453, 266965, 75049, 299435, 33105, 105635, 58447, 468661, 49143, 184387, 304455, 161973, 383407, 161591, 99557, 136555, 227539, 53703, 183421, 1309, 219647, 181273, 225657, 499885, 7793, 316853, 203725, 510555, 439029, 140139, 226933, 53193, 426793, 323911, 197289, 451239, 400865, 186897, 415817, 247495, 338897, 81519, 508191, 51431, 138341, 168981, 509307, 425997, 31671, 466107, 107807, 119149, 45445, 463293, 169005, 494957, 233889, 379071, 56207, 370557, 190641, 313037, 409251, 115275, 432787, 149865, 128547, 387723, 208827, 513141, 342985, 451773, 123373, 266837, 356005, 210101, 222037, 309733, 291245, 198909, 109053, 338203, 358821, 315763, 260497, 270577, 50711, 16659, 432321, 426009, 363977, 169873, 397129, 506275, 34723, 406577, 512633, 446285, 126645, 359527, 234217, 248385, 72351, 490133, 353629, 275083, 257899, 286679, 506675, 392463, 64919, 304447, 167823, 469789, 128867, 341797, 269127, 139817, 73833, 474985, 146207, 259459, 514783, 225979, 379661, 65709, 159455, 68921, 406531, 165331, 162783, 134373, 524181, 325319, 382207, 374607, 459885, 110169, 109615, 207343, 242825, 26893, 304861, 271033, 39067, 69399, 398623, 82457, 68137, 30655, 357523, 110607, 70321, 200023, 333595, 519989, 406867, 454885, 371469, 181747, 287901, 328919, 452885, 268871, 114371, 174289, 204689, 339681, 244961, 138059, 23775, 157431, 364049, 168241, 386843, 304593, 244153, 455883, 135783, 189137, 72541, 436449, 17323, 184745, 281281, 392061, 349459, 451941, 36721, 442071, 215979, 96757, 148521, 45921, 77641, 362129, 362027, 1419, 213361, 206533, 416007, 304031, 432157, 55333, 318205, 399399, 259627, 269895, 113389, 470083, 267011, 224557, 4671, 387213, 73547, 288035, 267849, 439837, 294697, 236133, 59493, 188573, 453863, 27265, 422439, 183715, 310065, 436519, 347411, 378187, 92151, 444977, 215793, 388667, 346607, 219657, 470907, 105075, 382637, 318467, 193169, 405245, 304635, 140987, 100999, 44247, 193987, 333067, 504099, 458487, 78945, 113979, 327675, 182731, 190221, 109961, 47721, 137905, 509935, 415927, 296613, 151271, 397933, 475833, 209163, 122023, 121877, 7681, 390363, 188591, 37265, 102951, 510389, 491125, 184595, 150425, 174379, 496253, 397359, 142605, 32063, 278813, 176873, 85853, 234275, 234797, 377841, 484883, 342529, 218631, 200297, 328805, 400701, 223069, 181567, 309437, 405825, 205209, 296555, 308911, 411577, 410949, 13167, 272245, 163751, 136507, 110507, 165829, 435515, 63761, 474227, 445641, 163547, 311013, 18131, 189441, 78087, 390825, 491063, 154625, 445825, 178395, 160541, 129953, 17663, 59561, 259215, 418625, 345359, 268621, 225865, 102075, 372677, 227767, 437373, 403481, 151031, 477203, 150857, 147693, 245381, 231701, 201019, 284969, 41339, 430169, 7919, 243345, 9655, 391383, 345769, 58521, 329835, 178569, 474807, 66627, 231369, 439087, 298597, 200877, 512175, 352351, 87387, 269711, 458703, 369055, 402877, 252607, 197639, 213247, 232615, 92657, 429865, 91295, 60675, 515225, 394623, 167027, 91441, 168589, 407489, 61537, 12727, 419841, 116529, 431501, 27431, 59541, 422421, 352663, 160503, 105091, 440027, 391909, 499147, 227823, 356185, 209859, 237757, 294719, 198541, 93801, 193925, 226339, 449107, 131637, 385919, 191353, 507939, 119171, 120225, 194801, 420895, 390275, 357333, 82391, 369141, 57705, 477633, 468597, 497491, 329805, 363165, 314103, 41947, 217175, 456325, 508435, 370641, 149311, 377971, 492869, 88373, 220541, 269265, 519127, 302535, 450231, 114681, 439607, 48657, 195225, 441259, 270287, 123281, 157339, 24067, 277467, 23209, 480037, 75733, 120049, 74375, 308017, 289173, 95853, 45987, 115339, 466973, 506551, 254681, 334965, 243101, 238815, 326495, 172489, 73113, 119345, 79275, 119931, 30161, 240745, 428825, 47675, 121967, 233195, 123165, 479149, 97037, 142089, 257253, 214405, 251141, 119029, 514015, 248751, 517863, 142393, 154935, 12367, 106931, 267209, 416673, 176893, 384475, 119825, 164611, 358501, 357389, 452533, 460727, 142831, 31497, 408089, 392383, 67637, 288857, 175585, 266747, 41765, 393901, 72789, 107687, 30391, 285671, 213485, 146743, 428499, 168767, 73743, 253675, 333159, 40307, 454903, 474825, 437973, 44739, 308231, 179883, 134153, 475069, 188537, 508973, 220637, 188005, 192269, 383763, 408723, 173275, 34577, 399119, 84701, 198817, 328407, 198645, 90179, 468431, 116563, 333127, 211005, 246461, 268813, 96113, 3447, 212257, 39265, 168843, 281933, 149947, 392735, 194069, 418871, 378107, 399309, 45741, 396531, 448939, 388199, 474421, 41241, 213887, 56587, 177657, 494225, 278607, 176267, 59741, 270589, 165791, 155361, 6473, 162547, 115111, 453061, 50925, 405033, 489907, 471277, 514717, 267253, 417221, 300903, 482243, 48449, 322747, 130635, 506133, 206951, 93809, 511615, 106977, 511393, 165785, 289257, 105363, 293217, 30345, 79175, 60301, 461261, 401323, 5943, 491845, 148305, 104025, 39305, 474573, 341611, 274603, 441219, 334337, 195011, 183303, 96023, 495489, 380921, 203041, 388783, 235133, 281039, 38607, 62285, 123401, 89741, 410791, 32253, 173905, 342407, 315951, 33885, 336275, 243533, 283835, 290881, 183377, 305311, 467285, 464893, 197217, 61965, 45613, 517645, 313339, 450115, 167999, 514009, 68119, 32235, 77667, 29657, 462767, 231101, 236467, 173483, 378741, 437545, 428441, 487347, 125753, 439559, 313519, 176115, 203733, 361193, 66291, 372245, 228819, 457165, 353889, 271861, 2961, 290687, 114523, 106185, 115973, 301141, 143421, 471109, 499515, 398857, 512545, 331319, 159897, 309705, 426123, 196201, 253965, 441231, 363183, 413997, 72719, 418185, 136949, 84053, 66205, 385911, 166495, 440155, 428225, 19885, 56283, 138471, 26285, 381021, 465113, 266033, 496847, 419331, 494525, 10463, 460669, 63139, 441583, 144601, 151503, 503305, 84051, 24255, 497473, 97709, 184819, 263255, 115365, 308643, 199949, 261511, 227647, 83109, 144957, 254307, 102661, 95753, 392433, 310997, 203229, 308719, 240017, 138373, 29295, 254391, 16235, 143789, 257247, 265947, 92127, 110075, 164045, 455097, 122351, 305117, 137161, 84205, 512991, 422887, 442063, 75573, 292001, 141359, 14853, 306481, 102725, 81015, 14697, 86609, 146273, 238385, 385869, 485749, 60087, 147359, 62247, 117087, 352319, 38317, 404431, 361969, 148009 }
Recommended generating vector from Kuo's website https://web.maths.unsw.edu.au/~fkuo/lattice/index.html.
UInt64 joe_kuo_d1024_t32_m32 [][1024]
Sobol generating matrices from Joe and Kuo (2008) NOTE: Truncated to 1024 dimensions (to avoid storage issues)
UInt64 sobol_d250_t64_m32 [][250]
Order 2 Sobol generating matrices [source?].
const char * FIELD_NAMES []
const int NUMBER_OF_FIELDS = 23
static const int MPI_COMM_WORLD = 1
static const int MPI_COMM_NULL = 0
static const int MPI_COMM_SELF = 92
static const int MPI_ANY_TAG = -1
static void * MPI_REQUEST_NULL = NULL
FILE * nidrin
const size_t NIDR_MAX_ERROR_LEN = 8192
maximum error length is roughly 100 lines at 80 char; using fixed error length instead of investing in converting to vsnprintf (C++11)
static const char * auto_log_scaletypes [] = { "auto", "log", "none", 0 }
static Var_uinfo CAUVLbl [CAUVar_Nkinds]
static Var_uinfo DAUIVLbl [DAUIVar_Nkinds]
static Var_uinfo DAUSVLbl [DAUSVar_Nkinds]
static Var_uinfo DAURVLbl [DAURVar_Nkinds]
static Var_uinfo CEUVLbl [CEUVar_Nkinds]
static Var_uinfo DEUIVLbl [DEUIVar_Nkinds]
static Var_uinfo DEUSVLbl [DEUSVar_Nkinds]
static Var_uinfo DEURVLbl [DEURVar_Nkinds]
static Var_uinfo DiscSetLbl [DiscSetVar_Nkinds]
static VarLabelChk DesignAndStateLabelsCheck []
Variables label array designations for design and state. All non-uncertain variables need to be in this array. Used in check_variables_node to check lengths and make_variable_defaults to build labels.
static VLreal VLUncertainReal [NUM_UNC_REAL_CONT]
Variables labels/bounds/values check array for real-valued uncertain variables; one array entry per contiguous container. These associate the individual variables given by, e.g., CAUVLbl, with the contiguous container in which they are stored.
static VLint VLUncertainInt [NUM_UNC_INT_CONT]
Variables labels/bounds/values check array for integer-valued uncertain variables; one array entry per contiguous container. These associate the individual variables given by, e.g., DAUIVLbl, with the contiguous container in which they are stored.
static VLstr VLUncertainStr [NUM_UNC_STR_CONT]
Variables labels/bounds/values check array for string-valued uncertain variables; one array entry per contiguous container. These associate the individual variables given by, e.g., DAUSVLbl, with the contiguous container in which they are stored.
static int VLR_aleatory [NUM_UNC_REAL_CONT] = { 1, 0, 1, 0 }
which uncertain real check array containers are aleatory (true = 1)
static int VLI_aleatory [NUM_UNC_INT_CONT] = { 1, 0 }
which uncertain integer check array containers are aleatory (true = 1)
static int VLS_aleatory [NUM_UNC_STR_CONT] = { 1, 0 }
which uncertain string check array containers are aleatory (true = 1)
static Var_check var_mp_check_cv []
static Var_check var_mp_check_dset []
static Var_check var_mp_check_cau []
static Var_check var_mp_check_daui []
static Var_check var_mp_check_daus []
static Var_check var_mp_check_daur []
static Var_check var_mp_check_ceu []
static Var_check var_mp_check_deui []
static Var_check var_mp_check_deus []
static Var_check var_mp_check_deur []
static Var_rcheck var_mp_cbound []
This is used within check_variables_node(): Var_RealBoundIPCheck() is applied to validate bounds and initial points.
static Var_icheck var_mp_drange []
This is used in check_variables_node(): Var_IntBoundIPCheck() is applied to validate bounds and initial points, and in make_variable_defaults(): Vgen_* is called to infer bounds.
TKFactoryDIPC tk_factory_dipc ("dakota_dipc_tk")
Static registration of RW TK with the QUESO TK factory.
TKFactoryDIPCLogit tk_factory_dipclogit ("dakota_dipc_logit_tk")
Static registration of Logit RW TK with the QUESO TK factory.
static time_t start_time
const double SCALING_MIN_SCALE = 1.0e10*DBL_MIN
minimum value allowed for a characteristic value when scaling; ten orders of magnitude greater than DBL_MIN
const double SCALING_MIN_LOG = SCALING_MIN_SCALE
lower bound on domain of logarithm function when scaling
const double SCALING_LOGBASE = 10.0
logarithm base to be used when scaling
const double SCALING_LN_LOGBASE = std::log(SCALING_LOGBASE)
ln(SCALING_LOGBASE); needed in transforming variables in several places
const char * SCI_FIELD_NAMES []
const int SCI_NUMBER_OF_FIELDS = 26
const int LARGE_SCALE = 100
a (perhaps arbitrary) definition of large scale; choose a large-scale algorithm if numVars >= LARGE_SCALE
const double POW_VAL = 1.0
offset used text_book exponent: 1.0 is nominal, 1.4 used for B&B testing
const String LEV_REF = "Dakota"
levenshtein_distance computes the distance between its argument and this
Detailed Description
The primary namespace for DAKOTA.
The Dakota namespace encapsulates the core classes of the DAKOTA framework and prevents name clashes with third-party libraries from methods and packages. The C++ source files defining these core classes reside in Dakota/src as *.[ch]pp.
Typedef Documentation
PRPMultiIndexCache
typedef bmi::multi_index_container<Dakota::ParamResponsePair, bmi::indexed_by< bmi::ordered_non_unique<bmi::tag<ordered>, bmi::const_mem_fun<Dakota::ParamResponsePair, const IntStringPair&, &Dakota::ParamResponsePair::eval_interface_ids> >, bmi::hashed_non_unique<bmi::tag<hashed>, bmi::identity<Dakota::ParamResponsePair>, partial_prp_hash, partial_prp_equality> > > PRPMultiIndexCache
Boost Multi-Index Container for globally caching ParamResponsePairs.
For a global cache, both evaluation and interface id's are used for tagging ParamResponsePair records.
PRPMultiIndexQueue
typedef bmi::multi_index_container<Dakota::ParamResponsePair, bmi::indexed_by< bmi::ordered_unique<bmi::tag<ordered>, bmi::const_mem_fun<Dakota::ParamResponsePair, int, &Dakota::ParamResponsePair::eval_id> >, bmi::hashed_non_unique<bmi::tag<hashed>, bmi::identity<Dakota::ParamResponsePair>, partial_prp_hash, partial_prp_equality> > > PRPMultiIndexQueue
Boost Multi-Index Container for locally queueing ParamResponsePairs.
For a local queue, interface id's are expected to be consistent, such that evaluation id's are sufficient for tracking particular evaluations.
Enumeration Type Documentation
anonymous enum [1/10]
anonymous enum
enum for selecting the models that store evaluations
Enumerator
SUBMETHOD_COLLABORATIVE
Type of hybrid meta-iterator:
anonymous enum [2/10]
anonymous enum
interface synchronization types
Enumerator
SUBMETHOD_COLLABORATIVE
Type of hybrid meta-iterator:
anonymous enum [3/10]
anonymous enum
Sub-methods, including sampling, inference algorithm, opt algorithm types.
Enumerator
SUBMETHOD_COLLABORATIVE
Type of hybrid meta-iterator:
anonymous enum [4/10]
anonymous enum
define special values for SurrogateModel::responseMode
Enumerator
SUBMETHOD_COLLABORATIVE
Type of hybrid meta-iterator:
anonymous enum [5/10]
anonymous enum
values for primary response types
Enumerator
SUBMETHOD_COLLABORATIVE
Type of hybrid meta-iterator:
anonymous enum [6/10]
anonymous enum
Enumerator
SUBMETHOD_COLLABORATIVE
Type of hybrid meta-iterator:
anonymous enum [7/10]
anonymous enum
Enumerator
SUBMETHOD_COLLABORATIVE
Type of hybrid meta-iterator:
anonymous enum [8/10]
anonymous enum
Enumerator
SUBMETHOD_COLLABORATIVE
Type of hybrid meta-iterator:
anonymous enum [9/10]
anonymous enum
Enumerator
SUBMETHOD_COLLABORATIVE
Type of hybrid meta-iterator:
anonymous enum [10/10]
anonymous enum
enum indicating action on failed file operation
Enumerator
SUBMETHOD_COLLABORATIVE
Type of hybrid meta-iterator:
Function Documentation
flush()
CommandShell & flush (CommandShell & shell)
convenient shell manipulator function to "flush" the shell
global convenience function for manipulating the shell; invokes the class member flush function.
References CommandShell::flush().
Referenced by HDF5IOHelper::append_empty(), HDF5IOHelper::create_dataset(), HDF5IOHelper::create_empty_dataset(), HDF5IOHelper::create_group(), SysCallApplicInterface::spawn_analysis_to_shell(), SysCallApplicInterface::spawn_evaluation_to_shell(), SysCallApplicInterface::spawn_input_filter_to_shell(), and SysCallApplicInterface::spawn_output_filter_to_shell().
bitget()
T Dakota::bitget (T v, int j) inline
Bit operations are taken from the Stanford Bithack webpage http://www.graphics.stanford.edu/~seander/bithacks.html.
Get the bit at position 'j'
Referenced by matmul_base2().
apply_matrix_partial()
void Dakota::apply_matrix_partial (const MatrixType & M, const VectorType & v1, VectorType & v2)
Applies a RealMatrix to a vector (or subset of vector) v1.
Optionally works with a subset of the passed vectors; applies the matrix M to the first M.numCols() entries in v1, and populates the first M.numRows entries in v2.
References abort_handler().
Referenced by apply_linear_constraints(), DakotaROLIneqConstraintsHess::applyAdjointHessian(), DakotaROLEqConstraintsHess::applyAdjointHessian(), DakotaROLIneqConstraintsGrad::applyJacobian(), DakotaROLEqConstraintsGrad::applyJacobian(), and DakotaROLObjectiveHess::hessVec().
apply_matrix_transpose_partial()
void Dakota::apply_matrix_transpose_partial (const RealMatrix & M, const VectorType & v1, VectorType & v2)
Applies transpose of a RealMatrix to a vector (or subset of vector) v1.
Optionally works with a subset of the passed vectors; applies the matrix M^T to the first M.numRows() entries in v1, and populates the first M.numCols() entries in v2.
References abort_handler().
Referenced by DakotaROLIneqConstraintsGrad::applyAdjointJacobian(), and DakotaROLEqConstraintsGrad::applyAdjointJacobian().
abort_throw_or_exit()
void abort_throw_or_exit (int dakota_code)
throw or exit depending on abort_mode
Throw a system_error or call std::exit, with (256 + dakota_code), where dakota_code < 0
RATIONALE: Avoid common "standard" exit codes and signals (signum.h) as well as uncaught signals / uncatchable SIGKILL which return 128
<signum> on Linux = [129, 192]
Return a value in [0,255] since some operating systems only return the 8 least significant bits, leaves [193, 255] for Dakota. This should make return codes consistent cross-platform.
References abort_mode.
Referenced by abort_handler(), and ParallelLibrary::abort_helper().
register_signal_handlers()
void register_signal_handlers ()
Tie various signal handlers to Dakota's abort_handler function.
Global function to register signal handlers at top-level.
References abort_handler().
Referenced by main().
mpi_debug_hold()
void mpi_debug_hold ()
Global function to hold Dakota processes to help with MPI debugging.
See details in code for details, depending on MPI implementation in use.
Referenced by main().
abort_handler_t()
T Dakota::abort_handler_t (int code)
Templatized abort_handler_t method that allows for convenient return from methods that otherwise have no sensible return from error clauses. Usage: MyType& method() { return abort_handler<MyType&>(-1); }
References abort_handler().
svd()
void svd (RealMatrix & matrix, RealVector & singular_vals, RealMatrix & v_trans, bool compute_vectors = true)
Compute the SVD of an arbitrary matrix A = USV^T.
Uses Teuchos::LAPACK.GESVD() to compute the singular value decomposition, overwriting A with the left singular vectors U (or destroying A if compute_vectors = false); optionally returns right singular vectors in v_trans.
References abort_handler().
Referenced by ProbabilityTransformModel::acv_index_to_corr_index(), ExperimentData::add_data(), Model::assign_max_strings(), NonDBayesCalibration::augment_gradient_with_log_prior(), NonDBayesCalibration::augment_hessian_with_log_prior(), NonDAdaptImpSampling::calculate_statistics(), NonDDREAMBayesCalibration::calibrate(), NonDWASABIBayesCalibration::calibrate(), PebbldBranchSub::candidateSolution(), ActiveSubspaceModel::compute_bing_li_criterion(), ActiveSubspaceModel::compute_constantine_metric(), ActiveSubspaceModel::compute_svd(), Variables::continuous_variable_id(), Variables::continuous_variable_ids(), Variables::continuous_variable_label(), Variables::continuous_variable_labels(), Variables::continuous_variable_type(), Variables::continuous_variable_types(), Model::discrete_int_sets(), Variables::discrete_int_variable_label(), Variables::discrete_int_variable_labels(), Variables::discrete_int_variable_type(), Variables::discrete_int_variable_types(), Variables::discrete_real_variable_label(), Variables::discrete_real_variable_labels(), Variables::discrete_real_variable_type(), Variables::discrete_real_variable_types(), Model::discrete_set_int_values(), Model::discrete_set_real_values(), Model::discrete_set_string_values(), Variables::discrete_string_variable_label(), Variables::discrete_string_variable_labels(), Variables::discrete_string_variable_type(), Variables::discrete_string_variable_types(), ParamStudy::distribute(), ExperimentData::ExperimentData(), QMEApproximation::find_scaled_coefficients(), NonDAdaptImpSampling::generate_samples(), Constraints::get_constraints(), DataTransformModel::get_hyperparam_vc_index(), Variables::inactive_continuous_variable_ids(), Variables::inactive_continuous_variable_labels(), Variables::inactive_continuous_variable_types(), Variables::inactive_discrete_int_variable_labels(), Variables::inactive_discrete_int_variable_types(), Variables::inactive_discrete_real_variable_labels(), Variables::inactive_discrete_real_variable_types(), Variables::inactive_discrete_string_variable_labels(), Variables::inactive_discrete_string_variable_types(), NonDLHSSampling::increm_lhs_parameter_set(), RecastModel::init_constraints(), DataTransformModel::init_continuous_vars(), SimulationModel::initialize_solution_control(), MinimizerAdapterModel::initialize_variables(), ExperimentData::load_data(), MixedVarConstraints::MixedVarConstraints(), NonDSampling::mode_bits(), NonDSampling::mode_counts(), Model::Model(), NestedModel::NestedModel(), NonDInterval::NonDInterval(), NonDLHSSampling::NonDLHSSampling(), SharedVariablesData::operator=(), Optimizer::Optimizer(), SensAnalysisGlobal::partial_corr(), ParamStudy::pre_run(), NonDBayesCalibration::prior_sample(), Constraints::reshape(), SubspaceModel::resize_variable_totals(), NonDSampling::sample_to_variables(), NonDAdaptImpSampling::select_rep_points(), SharedVariablesData::SharedVariablesData(), singular_values(), size_and_fill(), NonDQUESOBayesCalibration::specify_prior(), PebbldBranchSub::splitComputation(), SubspaceModel::uncertain_vars_to_subspace(), SurrogateModel::update_distributions_from_model(), NonDExpansion::update_final_statistics_gradients(), SurrogateModel::update_model_distributions(), NestedModel::update_sub_model(), ReducedBasis::update_svd(), DataTransformModel::variables_expand(), RandomFieldModel::variables_resize(), and NonDSampling::variables_to_sample().
qr()
int qr (RealMatrix & A)
Compute an in-place QR factorization A = QR.
Uses Teuchos::LAPACK.GEQRF() to compute the QR decomposition, overwriting A with the transformations and R.
References abort_handler().
Referenced by SensAnalysisGlobal::partial_corr().
qr_rsolve()
int qr_rsolve (const RealMatrix & q_r, bool transpose, RealMatrix & rhs)
Perform a multiple right-hand sides Rinv * rhs solve using the R from a qr factorization.
Returns info > 0 if the matrix is singular
Uses Teuchos::LAPACK.TRTRS() to perform a triangular backsolve
References abort_handler().
Referenced by SensAnalysisGlobal::partial_corr().
generate_system_seed()
int generate_system_seed ()
clock microseconds-based random seed in [1, 1000000]
Mimics DDACE timeSeed(), which returns the trailing microseconds on the time of day clock. Historically, most algorithms opted for DDACE, Utilib, std::clock(), in that order.
Referenced by NonDWASABIBayesCalibration::calibrate(), DigitalNet::digital_shift(), NonDQuadrature::get_parameter_sets(), PSUADEDesignCompExp::get_parameter_sets(), FSUDesignCompExp::get_parameter_sets(), NonDSampling::initialize_sample_driver(), NonDBayesCalibration::NonDBayesCalibration(), Rank1Lattice::random_shift(), and DigitalNet::scramble().
operator!=() [1/5]
bool Dakota::operator!= (const ActiveSet & set1, const ActiveSet & set2) inline
inequality operator for ActiveSet
inequality operator
operator==() [1/2]
bool Dakota::operator== (const Model & m1, const Model & m2) inline
equality operator for Envelope is true if same letter instance
equality operator (detect same letter instance)
References Model::modelRep.
operator!=() [2/5]
bool Dakota::operator!= (const Model & m1, const Model & m2) inline
inequality operator for Envelope is true if different letter instance
inequality operator (detect different letter instances)
References Model::modelRep.
get_initial_values()
void Dakota::get_initial_values (const Model & model, VecT & values)
Adapter for copying initial continuous variables values from a Dakota Model into TPL vectors
References Model::continuous_variables(), and Model::cv().
Referenced by ROLOptimizer::set_problem().
get_bounds() [1/3]
bool Dakota::get_bounds (const RealVector & lower_source, const RealVector & upper_source, VecT & lower_target, VecT & upper_target, Real big_real_bound_size, Real no_value)
Adapter for copying continuous variables data from Dakota RealVector into TPL vectors
Referenced by get_linear_constraints(), get_variable_bounds(), and ROLOptimizer::set_problem().
get_bounds() [2/3]
void Dakota::get_bounds (const Model & model, VecT & lower_target, VecT & upper_target)
Adapter for copying continuous variables data from a Dakota Model into TPL vectors
References Model::continuous_lower_bounds(), and Model::continuous_upper_bounds().
get_bounds() [3/3]
void Dakota::get_bounds (const SetT & source_set, VecT & lower_target, VecT & upper_target, int target_offset)
Adapter originating from (and somewhat specialized based on) APPSOptimizer for copying discrete variables from a set-based Dakota container into TPL vectors
get_mixed_bounds()
bool Dakota::get_mixed_bounds (const MaskType & mask_set, const SetArray & source_set, const Teuchos::SerialDenseVector< OrdinalType, ScalarType > & lower_source, const Teuchos::SerialDenseVector< OrdinalType, ScalarType > & upper_source, VectorType2 & lower_target, VectorType2 & upper_target, ScalarType bigBoundSize, ScalarType no_value, int target_offset = 0)
Adapter originating from (and somewhat specialized based on) APPSOptimizer for copying discrete integer variables data with bit masking from Dakota into TPL vectors
Referenced by get_variable_bounds().
get_variable_bounds()
bool Dakota::get_variable_bounds (Model & model, Real big_real_bound_size, int big_int_bound_size, typename AdapterT::VecT & lower, typename AdapterT::VecT & upper)
Adapter originating from (and somewhat specialized based on) APPSOptimizer for copying heterogeneous bounded data from Dakota::Variables into concatenated TPL vectors
References Model::continuous_lower_bounds(), Model::continuous_upper_bounds(), Model::cv(), Model::discrete_int_lower_bounds(), Model::discrete_int_sets(), Model::discrete_int_upper_bounds(), Model::discrete_real_lower_bounds(), Model::discrete_real_upper_bounds(), Model::discrete_set_int_values(), Model::discrete_set_real_values(), Model::discrete_set_string_values(), Model::div(), Model::drv(), get_bounds(), and get_mixed_bounds().
configure_inequality_constraint_maps()
int Dakota::configure_inequality_constraint_maps (const Model & model, Real big_real_bound_size, CONSTRAINT_TYPE ctype, IVecT & map_indices, RVecT & map_multipliers, RVecT & map_offsets, Real scaling = 1.0)
Adapter for configuring inequality constraint maps used when transferring data between Dakota and a TPL
Referenced by Optimizer::configure_constraint_maps().
configure_equality_constraint_maps()
void Dakota::configure_equality_constraint_maps (Model & model, CONSTRAINT_TYPE ctype, IVecT & indices, size_t index_offset, RVecT & multipliers, RVecT & values, bool make_one_sided)
Adapter for configuring equality constraint maps used when transferring data between Dakota and a TPL
get_linear_constraints()
void Dakota::get_linear_constraints (Model & model, Real big_real_bound_size, typename AdapterT::VecT & lin_ineq_lower_bnds, typename AdapterT::VecT & lin_ineq_upper_bnds, typename AdapterT::VecT & lin_eq_targets, typename AdapterT::MatT & lin_ineq_coeffs, typename AdapterT::MatT & lin_eq_coeffs)
Adapter based initially on APPSOptimizer for linear constraint maps and including matrix and bounds data; bundles a few steps together which could (should?) be broken into two or more adapters
References copy_data(), get_bounds(), Model::linear_eq_constraint_coeffs(), Model::linear_eq_constraint_targets(), Model::linear_ineq_constraint_coeffs(), Model::linear_ineq_constraint_lower_bounds(), and Model::linear_ineq_constraint_upper_bounds().
apply_linear_constraints()
void Dakota::apply_linear_constraints (const Model & model, CONSTRAINT_EQUALITY_TYPE etype, const VecT & in_vals, VecT & values, bool adjoint = false)
Data adapter to transfer data from Dakota to third-party opt packages. The vector values might contain additional constraints; the first entries corresponding to linear constraints are populated by apply.
References apply_matrix_partial(), Model::linear_eq_constraint_coeffs(), Model::linear_eq_constraint_targets(), Model::linear_ineq_constraint_coeffs(), Model::num_linear_eq_constraints(), and Model::num_linear_ineq_constraints().
Referenced by DakotaROLIneqConstraints::value(), and DakotaROLEqConstraints::value().
apply_nonlinear_constraints()
void Dakota::apply_nonlinear_constraints (const Model & model, CONSTRAINT_EQUALITY_TYPE etype, const VecT & in_vals, VecT & values, bool adjoint = false)
Data adapter to transfer data from Dakota to third-party opt packages
If adjoint = false, (perhaps counter-intuitively) apply the Jacobian (transpose of the gradient) to in_vals, which should be of size num_continuous_vars: J*x = G'*x, resulting in num_nonlinear_const values getting populated (possibly a subset of the total constraint vector).
If adjoint = true, apply the adjoint Jacobian (gradient) to the nonlinear constraint portion of in_vals, which should be of size at least num_nonlinear_consts: J'*y = G*y, resulting in num_continuous_vars values getting populated.
References Model::current_response(), Model::cv(), Response::function_gradients(), Model::num_linear_eq_constraints(), Model::num_linear_ineq_constraints(), Model::num_nonlinear_eq_constraints(), and Model::num_nonlinear_ineq_constraints().
Referenced by DakotaROLIneqConstraintsGrad::applyAdjointJacobian(), DakotaROLEqConstraintsGrad::applyAdjointJacobian(), DakotaROLIneqConstraintsGrad::applyJacobian(), and DakotaROLEqConstraintsGrad::applyJacobian().
set_best_responses()
void Dakota::set_best_responses (typename AdapterT::OptT & optimizer, const Model & model, bool set_objectives, size_t num_user_primary_fns, const std::vector< int > constraint_map_indices, const std::vector< double > constraint_map_multipliers, const std::vector< double > constraint_map_offsets, ResponseArray & response_array)
Data adapter for use by third-party opt packages to transfer response data to Dakota
References Model::num_nonlinear_eq_constraints(), Model::num_nonlinear_ineq_constraints(), and Model::primary_response_fn_sense().
set_variables()
void Dakota::set_variables (const VectorType & source, Model & model, Variables & vars)
copy appropriate slices of source vector to Dakota::Variables
References Variables::continuous_variables(), copy_data_partial(), Variables::cv(), Model::discrete_int_sets(), Variables::discrete_int_variables(), Variables::discrete_real_variables(), Model::discrete_set_int_values(), Model::discrete_set_real_values(), Model::discrete_set_string_values(), Variables::discrete_string_variable(), Variables::div(), Variables::drv(), Variables::dsv(), and set_index_to_value().
Referenced by NomadOptimizer::Evaluator::eval_x().
get_variables()
void Dakota::get_variables (Model & model, VectorType & vec)
copy the various pieces comprising Dakota::Variables into a concatenated TPL vector
References abort_handler(), Model::continuous_variables(), copy_data_partial(), Model::cv(), Model::discrete_int_sets(), Model::discrete_int_variables(), Model::discrete_real_variables(), Model::discrete_set_int_values(), Model::discrete_set_real_values(), Model::discrete_set_string_values(), Model::discrete_string_variables(), Model::div(), Model::drv(), and Model::dsv().
get_responses()
void Dakota::get_responses (const Model & model, const RealVector & dak_fn_vals, const std::vector< int > constraint_map_indices, const std::vector< double > constraint_map_multipliers, const std::vector< double > constraint_map_offsets, vectorType & f_vec, vectorType & cEqs_vec, vectorType & cIneqs_vec)
Data adapter to transfer data from Dakota to third-party opt packages
References Model::num_nonlinear_eq_constraints(), and Model::primary_response_fn_sense().
Referenced by NomadOptimizer::Evaluator::eval_x(), and Optimizer::get_responses_from_dakota().
get_nonlinear_eq_constraints() [1/2]
void Dakota::get_nonlinear_eq_constraints (const Model & model, VecT & values, Real scale, int offset = -1)
Data adapter to transfer data from Dakota to third-party opt packages
References Model::current_response(), Response::function_values(), Model::nonlinear_eq_constraint_targets(), Model::num_linear_eq_constraints(), Model::num_nonlinear_eq_constraints(), and Model::num_nonlinear_ineq_constraints().
Referenced by DakotaROLEqConstraints::value().
get_nonlinear_eq_constraints() [2/2]
void Dakota::get_nonlinear_eq_constraints (Model & model, const RealVector & curr_resp_vals, VecT & values, Real scale, int offset = 0)
Data adapter to transfer data from Dakota to third-party opt packages
References Model::nonlinear_eq_constraint_targets(), and Model::num_nonlinear_eq_constraints().
get_nonlinear_ineq_constraints()
void Dakota::get_nonlinear_ineq_constraints (const Model & model, VecT & values)
Data adapter to transfer data from Dakota to third-party opt packages (ROL-specific)
References copy_data_partial(), Model::current_response(), Response::function_values(), Model::num_linear_ineq_constraints(), and Model::num_nonlinear_ineq_constraints().
get_nonlinear_bounds()
void Dakota::get_nonlinear_bounds (Model & model, VecT & nonlin_ineq_lower, VecT & nonlin_ineq_upper, VecT & nonlin_eq_targets)
Would like to combine the previous adapter with this one (based on APPSOptimizer and COLINOptimizer) and then see how much more generalization is needed to support other TPLs like JEGA.
Data adapter to transfer data from Dakota to third-party opt packages
References copy_data(), Model::nonlinear_eq_constraint_targets(), Model::nonlinear_ineq_constraint_lower_bounds(), and Model::nonlinear_ineq_constraint_upper_bounds().
Referenced by COLINApplication::set_problem().
operator!=() [3/5]
bool Dakota::operator!= (const Response & resp1, const Response & resp2) inline
inequality operator for Response
inequality operator
operator!=() [4/5]
bool Dakota::operator!= (const Variables & vars1, const Variables & vars2) inline
inequality operator for Variables
strict inequality operator
write_ordered() [1/2]
void Dakota::write_ordered (std::ostream & s, const SizetArray & comp_totals, const Teuchos::SerialDenseVector< OrdinalType, ScalarType1 > & c_vector, const Teuchos::SerialDenseVector< OrdinalType, ScalarType2 > & di_vector, const Teuchos::SerialDenseVector< OrdinalType, ScalarType3 > & ds_vector, const Teuchos::SerialDenseVector< OrdinalType, ScalarType4 > & dr_vector) inline
free function to write Variables data vectors in input spec ordering
written for arbitrary types, but typical use will be ScalarType1 = Real, ScalarType2 = int, ScalarType3 = string, and ScalarType4 = int or Real.
Referenced by ParamStudy::pre_run().
write_ordered() [2/2]
void Dakota::write_ordered (std::ostream & s, const SizetArray & comp_totals, const Teuchos::SerialDenseVector< OrdinalType, ScalarType1 > & c_vector, const Teuchos::SerialDenseVector< OrdinalType, ScalarType2 > & di_vector, const boost::multi_array< ScalarType3, 1 > & ds_array, const Teuchos::SerialDenseVector< OrdinalType, ScalarType4 > & dr_vector) inline
free function to write Variables data vectors in input spec ordering
written for arbitrary types, but typical use will be ScalarType1 = Real, ScalarType2 = int, ScalarType3 = string, and ScalarType4 = int or Real.
copy_field_data() [1/2]
void copy_field_data (const RealVector & fn_vals, RealMatrix & fn_grad, const RealSymMatrixArray & fn_hess, size_t offset, size_t num_fns, Response & response)
This assumes the souce gradient/Hessian are size less or equal to the destination response, and that the leading part is to be populated.
References Response::active_set_request_vector(), Response::function_gradient_view(), Response::function_hessian_view(), and Response::function_value().
Referenced by ExperimentData::scale_residuals().
copy_field_data() [2/2]
void Dakota::copy_field_data (const RealVector & fn_vals, RealMatrix & fn_grad, const RealSymMatrixArray & fn_hess, size_t offset, size_t num_fns, short total_asv, Response & response)
This assumes the souce gradient/Hessian are size less or equal to the destination response, and that the leading part is to be populated.
References Response::function_gradient_view(), Response::function_hessian_view(), and Response::function_value().
symmetric_eigenvalue_decomposition()
void symmetric_eigenvalue_decomposition (const RealSymMatrix & matrix, RealVector & eigenvalues, RealMatrix & eigenvectors)
Computes the eigenvalues and, optionally, eigenvectors of a real symmetric matrix A.
Eigenvalues are returned in ascending order.
References symmetric_eigenvalue_decomposition().
Referenced by NonDBayesCalibration::get_positive_definite_covariance_from_hessian(), and symmetric_eigenvalue_decomposition().
getdist()
Real Dakota::getdist (const RealVector & x1, const RealVector & x2)
Gets the Euclidean distance between x1 and x2
Referenced by mindist(), and mindistindx().
mindist()
Real Dakota::mindist (const RealVector & x, const RealMatrix & xset, int except)
Returns the minimum distance between the point x and the points in the set xset (compares against all points in xset except point "except"): if except is not needed, pass 0.
References getdist().
Referenced by getRmax().
mindistindx()
Real Dakota::mindistindx (const RealVector & x, const RealMatrix & xset, const IntArray & indx)
Gets the min distance between x and points in the set xset defined by the nindx values in indx.
References getdist().
Referenced by GaussProcApproximation::pointsel_add_sel().
getRmax()
Real Dakota::getRmax (const RealMatrix & xset)
Gets the maximum of the min distance between each point and the rest of the set.
References mindist().
Referenced by GaussProcApproximation::pointsel_add_sel().
start_grid_computing()
int Dakota::start_grid_computing (char * analysis_driver_script, char * params_file, char * results_file)
sample function prototype for launching grid computing
stop_grid_computing()
int Dakota::stop_grid_computing ()
sample function prototype for terminating grid computing
perform_analysis()
int Dakota::perform_analysis (char * iteration_num)
sample function prototype for submitting a grid evaluation
asstring()
string Dakota::asstring (const T & val)
Creates a string from the argument val using an ostringstream.
This only gets used in this file and is only ever called with ints so no error checking is in place.
Parameters
val The value of type T to convert to a string.
Returns
The string representation of val created using an ostringstream.
Referenced by JEGAOptimizer::LoadTheConstraints().
start_dakota_heartbeat()
void start_dakota_heartbeat (int seconds)
Heartbeat function provided by dakota_filesystem_utils; pass output interval in seconds, or -1 to use $DAKOTA_HEARTBEAT
Referenced by OutputManager::OutputManager().
operator==() [2/2]
bool Dakota::operator== (const ParamResponsePair & pair1, const ParamResponsePair & pair2) inline
equality operator for ParamResponsePair
equality operator
References ParamResponsePair::evalInterfaceIds, ParamResponsePair::prpResponse, and ParamResponsePair::prpVariables.
operator!=() [5/5]
bool Dakota::operator!= (const ParamResponsePair & pair1, const ParamResponsePair & pair2) inline
inequality operator for ParamResponsePair
inequality operator
set_compare()
bool Dakota::set_compare (const ParamResponsePair & database_pr, const ActiveSet & search_set) inline
search function for a particular ParamResponsePair within a PRPList based on ActiveSet content (request vector and derivative variables vector)
a global function to compare the ActiveSet of a particular database_pr (presumed to be in the global history list) with a passed in ActiveSet (search_set).
References ParamResponsePair::active_set(), ActiveSet::derivative_vector(), and ActiveSet::request_vector().
Referenced by lookup_by_val().
id_vars_exact_compare()
bool Dakota::id_vars_exact_compare (const ParamResponsePair & database_pr, const ParamResponsePair & search_pr) inline
search function for a particular ParamResponsePair within a PRPMultiIndex
a global function to compare the interface id and variables of a particular database_pr (presumed to be in the global history list) with a passed in key of interface id and variables provided by search_pr.
References ParamResponsePair::interface_id(), and ParamResponsePair::variables().
Referenced by partial_prp_equality::operator()().
lookup_by_val() [1/2]
PRPCacheHIter Dakota::lookup_by_val (PRPMultiIndexCache & prp_cache, const ParamResponsePair & search_pr) inline
find a ParamResponsePair based on the interface id, variables, and ActiveSet search data within search_pr.
Lookup occurs in two steps: (1) PRPMultiIndexCache lookup based on strict equality in interface id and variables, and (2) set_compare() post-processing based on ActiveSet subset logic.
References ParamResponsePair::active_set(), and set_compare().
Referenced by NonDDREAMBayesCalibration::archive_acceptance_chain(), Minimizer::archive_best_results(), DataTransformModel::archive_submodel_responses(), NonDMUQBayesCalibration::cache_chain(), NonDQUESOBayesCalibration::cache_chain(), Model::db_lookup(), ApplicationInterface::duplication_detect(), SurrBasedLocalMinimizer::find_response(), Minimizer::local_recast_retrieve(), lookup_by_val(), Minimizer::print_best_eval_ids(), DiscrepancyCorrection::search_db(), and NonDLocalReliability::update_mpp_search_data().
lookup_by_val() [2/2]
PRPQueueHIter Dakota::lookup_by_val (PRPMultiIndexQueue & prp_queue, const ParamResponsePair & search_pr) inline
find a ParamResponsePair based on the interface id, variables, and ActiveSet search data within search_pr.
Lookup occurs in two steps: (1) PRPMultiIndexQueue lookup based on strict equality in interface id and variables, and (2) set_compare() post-processing based on ActiveSet subset logic.
References ParamResponsePair::active_set(), and set_compare().
print_restart()
void print_restart (StringArray pos_args, String print_dest)
print a restart file
Usage: "dakota_restart_util print dakota.rst"
"dakota_restart_util to_neutral dakota.rst dakota.neu"
Prints all evals. in full precision to either stdout or a neutral file. The former is useful for ensuring that duplicate detection is successful in a restarted run (e.g., starting a new method from the previous best), and the latter is used for translating binary files between platforms.
References abort_handler(), ParamResponsePair::eval_id(), ParamResponsePair::write_annotated(), and write_precision.
Referenced by main().
print_restart_pdb()
void print_restart_pdb (StringArray pos_args, String print_dest)
print a restart file (PDB format)
Usage: "dakota_restart_util to_pdb dakota.rst dakota.pdb"
Unrolls all data associated with a particular tag for all evaluations and then writes this data in a tabular format (e.g., to a PDB database or MATLAB/TECPLOT data file).
References abort_handler(), Variables::continuous_variables(), Variables::discrete_int_variables(), Variables::discrete_real_variables(), and Response::function_values().
Referenced by main().
print_restart_tabular()
void print_restart_tabular (StringArray pos_args, String print_dest, unsigned short tabular_format, int tabular_precision)
print a restart file (tabular format)
Usage: "dakota_restart_util to_tabular dakota.rst dakota.txt"
Unrolls all data associated with a particular tag for all evaluations and then writes this data in a tabular format (e.g., to a PDB database or MATLAB/TECPLOT data file).
References abort_handler(), Variables::acv(), Variables::adiv(), Variables::adrv(), Variables::adsv(), Variables::all_continuous_variable_labels(), Variables::all_discrete_int_variable_labels(), Variables::all_discrete_real_variable_labels(), Variables::all_discrete_string_variable_labels(), Response::function_labels(), ParamResponsePair::interface_id(), ParamResponsePair::response(), ParamResponsePair::variables(), write_precision, ParamResponsePair::write_tabular(), and ParamResponsePair::write_tabular_labels().
Referenced by main().
read_neutral()
void read_neutral (StringArray pos_args)
read a restart file (neutral file format)
Usage: "dakota_restart_util from_neutral dakota.neu dakota.rst"
Reads evaluations from a neutral file. This is used for translating binary files between platforms.
References abort_handler(), and ParamResponsePair::read_annotated().
Referenced by main().
repair_restart()
void repair_restart (StringArray pos_args, String identifier_type)
repair a restart file by removing corrupted evaluations
Usage: "dakota_restart_util remove 0.0 dakota_old.rst dakota_new.rst"
"dakota_restart_util remove_ids 2 7 13 dakota_old.rst dakota_new.rst"
Repairs a restart file by removing corrupted evaluations. The identifier for evaluation removal can be either a double precision number (all evaluations having a matching response function value are removed) or a list of integers (all evaluations with matching evaluation ids are removed).
References abort_handler(), Response::active_set_request_vector(), contains(), ParamResponsePair::eval_id(), Response::function_values(), and ParamResponsePair::response().
Referenced by main().
concatenate_restart()
void concatenate_restart (StringArray pos_args)
concatenate multiple restart files
Usage: "dakota_restart_util cat dakota_1.rst ... dakota_n.rst dakota_new.rst"
Combines multiple restart files into a single restart database.
References abort_handler().
Referenced by main().
std_normal_coverage_inverse()
Real std_normal_coverage_inverse (const Real coverage)
Given a required coverage c \in [0,1], this routine computes the value b such that.
   F(b) = \int_{-b}^{b} (1/sqrt(2\pi)) * exp{-x*x/2) dx = c
   There are two ways to compute b:
   1) b is the value such that \int_{-\infty}^{b} (1/sqrt(2\pi)) * exp{-x*x/2) dx = (1+c)/2.
      This is the approach used when calling the python scipy stats.norm.ppf((1+c)/2) routine.
   2) c = F(b) = 2 * \int_{0}^{b} (1/sqrt(2\pi)) * exp{-x*x/2) dx = erf(b/sqrt(2)), that is,
      b = sqrt(2) * erf_inv(c). This is the approach used in this DAKOTA routine.
   If c \in [0,1], this routine returns b, otherwise it aborts/throws an exception.
Parameters
[in] coverage = the required coverage level c above
return = the value b explained above
References abort_handler().
Referenced by computeDSTIEN().
computeDSTIEN_conversion_factor()
Real computeDSTIEN_conversion_factor (const size_t number_of_samples, const Real alpha)
This routine computes the multiplicative conversion factor to be applied to the sample standard deviation in order to get the standard deviation corresponding to the 'two sided tolerance interval equivalent normal' (DSTIEN).
More especifically, this routine expects the following input information:
m, the number of samples;
alpha, a value in the closed interval [0,1] such that (1-alpha) is the required confidence level.
The input information must satisty the following conditions, otherwise the routine aborts/throws an exception:
m >= 2;
alpha \in [0,1].
If all input information is valid, then this routine returns the following value 'mcf' for the multiplicative conversion factor:
mcf = sqrt(1. + 1./m)
sqrt((m - 1.) / quant)
sqrt(1. + (m - 3. - quant) / (2.*(m+1.)*(m+1.))), where:
quant is the alpha-quantile of a chi-square random variable with m-1 degrees of freedom.
See: Charles F. Jekel and Vicente Romero, "Conservative and Efficient Tail Probability Estimation from Sparse Sample Data", Sandia Report SAND2020-7572J, equations (4) and (5).
Parameters
[in] number_of_samples = the value 'm' on the text above
[in] alpha = the value such that (1-alpha) is the required confidence level
return = value of the multiplicative conversion factor
References abort_handler().
Referenced by computeDSTIEN().
computeDSTIEN()
void computeDSTIEN (const IntResponseMap & resp_samples, const Real coverage, const Real alpha, size_t & num_valid_samples, RealVector & dstien_mus, Real & delta_mf, RealVector & sample_sigmas, RealVector & dstien_sigmas)
This routine computes the r averages and r standard deviations corresponding to the 'two sided tolerance interval equivalent normal' (DSTIEN).
More especifically, this routine expects the following input information:
n >= 2 response samples, each sample being a vector of r >= 1 responses;
c, the required coverage level;
a value alpha in the closed interval [0,1] such that (1-alpha) is the required confidence level.
The input information must satisty the following conditions, otherwise the routine aborts/throws an exception:
n >= 2;
r >= 1, where r is the number of responses in the first response sample;
all remaining (n-1) response samples must have the same number r of resposens;
c \in [0,1];
alpha \in [0,1];
The output vectors dstien_mus and dstien_sigmas will have size r on output (that is, they are internally resized if they are not supplied with size r)
If all input information is valid, then this routine selects the m <= n response samples that are valid (meaning, all r responses are finite values):
if m == 0, this routine returns:
all r averages equal to std::numeric_limits<Real>::quiet_NaN(),
the delta_mf equal to std::numeric_limits<Real>::quiet_NaN(),
all r sample std deviations equal to std::numeric_limits<Real>::quiet_NaN(),
all r DSTIEN std deviations equal to std::numeric_limits<Real>::quiet_NaN();
if m == 1, this routine returns:
the r averages equal to the only valid sample,
the delta_mf equal to std::numeric_limits<Real>::quiet_NaN(),
all r sample std deviations equal to std::numeric_limits<Real>::quiet_NaN(),
all r DSTIEN std deviations equal to std::numeric_limits<Real>::quiet_NaN();
if m >= 2, this routine uses such m response samples to compute:
the r averages dstien_mus,
delta_mf = computeDSTIEN_conversion_factor(m, alpha)
std_normal_coverage_inverse(c), so that the tolerance intervals are given by [dstien_mus - delta_mf*sample_sigmas, dstien_mus + delta_mf*sample_sigmas]
the r sample standard deviations sample_sigmas,
the r DSTIEN standard deviations dstien_sigmas = computeDSTIEN_conversion_factor(m, alpha) * sample_sigmas.
Parameters
[in] resp_samples = the set of n response samples, each sample with r components
[in] coverage = the required coverage level c above
[in] alpha = the value such that (1-alpha) is the required confidence level
[out] num_valid_samples = number of valid samples ('m' on the text above) used to compute 'ties_mus' and 'dstien_sigmas'
[out] dstien_mus = the r averages
[out] delta_mf = the multiplicative factor explained above
[out] sample_sigmas = the r sample standard deviations
[out] dstien_sigmas = the r DSTIEN standard deviations
References abort_handler(), computeDSTIEN_conversion_factor(), and std_normal_coverage_inverse().
Referenced by NonDSampling::compute_statistics().
get_pathext()
std::vector<std::string> Dakota::get_pathext ()
Utility function for executable file search algorithms
Referenced by WorkdirHelper::which().
contains()
bool Dakota::contains (const bfs::path & dir_path, const std::string & file_name, boost::filesystem::path & complete_filepath) inline
Utility function for "which" sets complete_filepath from dir_path/file_name combo
Variable Documentation
abort_mode
short abort_mode = ABORT_EXITS
by default Dakota exits or calls MPI_Abort on errors
whether dakota exits/aborts or throws on errors
Referenced by abort_throw_or_exit(), Environment::exit_mode(), and PythonInterface::python_run().
DakFuncs0
Dakota_funcs DakFuncs0
Initial value:
= {
        fprintf,
        abort_handler,
        dlsolver_option,
        continuous_lower_bounds1,
        continuous_upper_bounds1,
        nonlinear_ineq_constraint_lower_bounds1,
        nonlinear_ineq_constraint_upper_bounds1,
        nonlinear_eq_constraint_targets1,
        linear_ineq_constraint_lower_bounds1,
        linear_ineq_constraint_upper_bounds1,
        linear_eq_constraint_targets1,
        linear_ineq_constraint_coeffs1,
        linear_eq_constraint_coeffs1,
        ComputeResponses1,
        GetFuncs1,
        GetGrads1,
        GetContVars1,
        SetBestContVars1,
        SetBestDiscVars1,
        SetBestRespFns1,
        Get_Real1,
        Get_Int1,
        Get_Bool1
        }
FIELD_NAMES
const char* FIELD_NAMES[]
Initial value:
= { "numFns", "numVars", "numACV", "numADIV",
                              "numADRV", "numDerivVars", "xC", "xDI",
                              "xDR", "xCLabels", "xDILabels",
                              "xDRLabels", "directFnASV", "directFnDVV",
                              "fnFlag", "gradFlag", "hessFlag",
                              "fnVals",  "fnGrads",  "fnHessians",
                              "fnLabels", "failure", "currEvalId" }
fields to pass to Matlab in Dakota structure
Referenced by MatlabInterface::matlab_engine_run(), and MatlabInterface::MatlabInterface().
NUMBER_OF_FIELDS
const int NUMBER_OF_FIELDS = 23
number of fields in above structure
Referenced by MatlabInterface::matlab_engine_run(), and MatlabInterface::MatlabInterface().
CAUVLbl
Var_uinfo CAUVLbl[CAUVar_Nkinds] static
Initial value:
= {
  VarLabelInfo(nuv_, NormalUnc),
  VarLabelInfo(lnuv_, LognormalUnc),
  VarLabelInfo(uuv_, UniformUnc),
  VarLabelInfo(luuv_, LoguniformUnc),
  VarLabelInfo(tuv_, TriangularUnc),
  VarLabelInfo(euv_, ExponentialUnc),
  VarLabelInfo(beuv_, BetaUnc),
  VarLabelInfo(gauv_, GammaUnc),
  VarLabelInfo(guuv_, GumbelUnc),
  VarLabelInfo(fuv_, FrechetUnc),
  VarLabelInfo(wuv_, WeibullUnc),
  VarLabelInfo(hbuv_, HistogramBinUnc)
}
DAUIVLbl
Var_uinfo DAUIVLbl[DAUIVar_Nkinds] static
Initial value:
= {
  VarLabelInfo(puv_, PoissonUnc),
  VarLabelInfo(biuv_, BinomialUnc),
  VarLabelInfo(nbuv_, NegBinomialUnc),
  VarLabelInfo(geuv_, GeometricUnc),
  VarLabelInfo(hguv_, HyperGeomUnc),
  VarLabelInfo(hpiuv_, HistogramPtIntUnc)
}
DAUSVLbl
Var_uinfo DAUSVLbl[DAUSVar_Nkinds] static
Initial value:
= {
  VarLabelInfo(hpsuv_, HistogramPtStrUnc)
}
DAURVLbl
Var_uinfo DAURVLbl[DAURVar_Nkinds] static
Initial value:
= {
  VarLabelInfo(hpruv_, HistogramPtRealUnc)
}
CEUVLbl
Var_uinfo CEUVLbl[CEUVar_Nkinds] static
Initial value:
= {
  VarLabelInfo(ciuv_, ContinuousIntervalUnc)
}
DEUIVLbl
Var_uinfo DEUIVLbl[DEUIVar_Nkinds] static
Initial value:
= {
  VarLabelInfo(diuv_, DiscreteIntervalUnc),
  VarLabelInfo(dusiv_, DiscreteUncSetInt)
}
DEUSVLbl
Var_uinfo DEUSVLbl[DEUSVar_Nkinds] static
Initial value:
= {
  VarLabelInfo(dussv_, DiscreteUncSetStr)
}
DEURVLbl
Var_uinfo DEURVLbl[DEURVar_Nkinds] static
Initial value:
= {
  VarLabelInfo(dusrv_, DiscreteUncSetReal)
}
DiscSetLbl
Var_uinfo DiscSetLbl[DiscSetVar_Nkinds] static
Initial value:
= {
  VarLabelInfo(ddsiv_, DiscreteDesSetInt),
  VarLabelInfo(ddssv_, DiscreteDesSetStr),
  VarLabelInfo(ddsrv_, DiscreteDesSetReal),
  VarLabelInfo(dssiv_, DiscreteStateSetInt),
  VarLabelInfo(dsssv_, DiscreteStateSetStr),
  VarLabelInfo(dssrv_, DiscreteStateSetReal)
}
DesignAndStateLabelsCheck
VarLabelChk DesignAndStateLabelsCheck[] static
Initial value:
= {
  { AVI numContinuousDesVars, AVI continuousDesignLabels, "cdv_", "cdv_descriptors" },
  { AVI numDiscreteDesRangeVars, AVI discreteDesignRangeLabels, "ddriv_", "ddriv_descriptors" },
  { AVI numDiscreteDesSetIntVars, AVI discreteDesignSetIntLabels, "ddsiv_", "ddsiv_descriptors" },
  { AVI numDiscreteDesSetStrVars, AVI discreteDesignSetStrLabels, "ddssv_", "ddssv_descriptors" },
  { AVI numDiscreteDesSetRealVars, AVI discreteDesignSetRealLabels, "ddsrv_", "ddsrv_descriptors" },
  { AVI numContinuousStateVars, AVI continuousStateLabels, "csv_", "csv_descriptors" },
  { AVI numDiscreteStateRangeVars, AVI discreteStateRangeLabels, "dsriv_", "dsriv_descriptors" },
  { AVI numDiscreteStateSetIntVars, AVI discreteStateSetIntLabels, "dssiv_", "dssiv_descriptors" },
  { AVI numDiscreteStateSetStrVars, AVI discreteStateSetStrLabels, "dsssv_", "dsssv_descriptors" },
  { AVI numDiscreteStateSetRealVars, AVI discreteStateSetRealLabels, "dssrv_", "dssrv_descriptors" },
  { AVI numContinuousDesVars, AVI continuousDesignScaleTypes, 0, "cdv_scale_types" }
}
Variables label array designations for design and state. All non-uncertain variables need to be in this array. Used in check_variables_node to check lengths and make_variable_defaults to build labels.
Referenced by NIDRProblemDescDB::check_variables_node(), and NIDRProblemDescDB::make_variable_defaults().
VLUncertainReal
VLreal VLUncertainReal[NUM_UNC_REAL_CONT] static
Initial value:
= {
 {CAUVar_Nkinds,  AVI CAUv,  CAUVLbl,
        DVR continuousAleatoryUncLabels,
        DVR continuousAleatoryUncLowerBnds,
        DVR continuousAleatoryUncUpperBnds,
        DVR continuousAleatoryUncVars},
 {CEUVar_Nkinds,  AVI CEUv,  CEUVLbl,
        DVR continuousEpistemicUncLabels,
        DVR continuousEpistemicUncLowerBnds,
        DVR continuousEpistemicUncUpperBnds,
        DVR continuousEpistemicUncVars},
 {DAURVar_Nkinds, AVI DAURv, DAURVLbl,
        DVR discreteRealAleatoryUncLabels,
        DVR discreteRealAleatoryUncLowerBnds,
        DVR discreteRealAleatoryUncUpperBnds,
        DVR discreteRealAleatoryUncVars},
 {DEURVar_Nkinds, AVI DEURv, DEURVLbl,
        DVR discreteRealEpistemicUncLabels,
        DVR discreteRealEpistemicUncLowerBnds,
        DVR discreteRealEpistemicUncUpperBnds,
        DVR discreteRealEpistemicUncVars}}
Variables labels/bounds/values check array for real-valued uncertain variables; one array entry per contiguous container. These associate the individual variables given by, e.g., CAUVLbl, with the contiguous container in which they are stored.
Referenced by NIDRProblemDescDB::check_variables_node(), and NIDRProblemDescDB::make_variable_defaults().
VLUncertainInt
VLint VLUncertainInt[NUM_UNC_INT_CONT] static
Initial value:
= {
 {DAUIVar_Nkinds, AVI DAUIv, DAUIVLbl,
        DVR discreteIntAleatoryUncLabels,
        DVR discreteIntAleatoryUncLowerBnds,
        DVR discreteIntAleatoryUncUpperBnds,
        DVR discreteIntAleatoryUncVars},
 {DEUIVar_Nkinds, AVI DEUIv, DEUIVLbl,
        DVR discreteIntEpistemicUncLabels,
        DVR discreteIntEpistemicUncLowerBnds,
        DVR discreteIntEpistemicUncUpperBnds,
        DVR discreteIntEpistemicUncVars}}
Variables labels/bounds/values check array for integer-valued uncertain variables; one array entry per contiguous container. These associate the individual variables given by, e.g., DAUIVLbl, with the contiguous container in which they are stored.
Referenced by NIDRProblemDescDB::check_variables_node(), and NIDRProblemDescDB::make_variable_defaults().
VLUncertainStr
VLstr VLUncertainStr[NUM_UNC_STR_CONT] static
Initial value:
= {
 {DAUSVar_Nkinds, AVI DAUSv, DAUSVLbl,
        DVR discreteStrAleatoryUncLabels,
        DVR discreteStrAleatoryUncLowerBnds,
        DVR discreteStrAleatoryUncUpperBnds,
        DVR discreteStrAleatoryUncVars},
 {DEUSVar_Nkinds, AVI DEUSv, DEUSVLbl,
        DVR discreteStrEpistemicUncLabels,
        DVR discreteStrEpistemicUncLowerBnds,
        DVR discreteStrEpistemicUncUpperBnds,
        DVR discreteStrEpistemicUncVars}}
Variables labels/bounds/values check array for string-valued uncertain variables; one array entry per contiguous container. These associate the individual variables given by, e.g., DAUSVLbl, with the contiguous container in which they are stored.
Referenced by NIDRProblemDescDB::check_variables_node(), and NIDRProblemDescDB::make_variable_defaults().
var_mp_check_cv
Var_check var_mp_check_cv[] static
Initial value:
= {
        Vchk_3(continuous_design,ContinuousDes),
        Vchk_3(continuous_state,ContinuousState) }
var_mp_check_dset
Var_check var_mp_check_dset[] static
Initial value:
= {
        Vchk_3(discrete_design_set_integer,DiscreteDesSetInt),
        Vchk_3(discrete_design_set_string,DiscreteDesSetStr),
        Vchk_3(discrete_design_set_real,DiscreteDesSetReal),
        Vchk_3(discrete_state_set_integer,DiscreteStateSetInt),
        Vchk_3(discrete_state_set_string,DiscreteStateSetStr),
        Vchk_3(discrete_state_set_real,DiscreteStateSetReal) }
var_mp_check_cau
Var_check var_mp_check_cau[] static
Initial value:
= {
        Vchk_3(normal_uncertain,NormalUnc),
        Vchk_3(lognormal_uncertain,LognormalUnc),
        Vchk_3(uniform_uncertain,UniformUnc),
        Vchk_3(loguniform_uncertain,LoguniformUnc),
        Vchk_3(triangular_uncertain,TriangularUnc),
        Vchk_3(exponential_uncertain,ExponentialUnc),
        Vchk_3(beta_uncertain,BetaUnc),
        Vchk_3(gamma_uncertain,GammaUnc),
        Vchk_3(gumbel_uncertain,GumbelUnc),
        Vchk_3(frechet_uncertain,FrechetUnc),
        Vchk_3(weibull_uncertain,WeibullUnc),
        Vchk_3(histogram_bin_uncertain,HistogramBinUnc) }
var_mp_check_daui
Var_check var_mp_check_daui[] static
Initial value:
= {
        Vchk_3(poisson_uncertain,PoissonUnc),
        Vchk_3(binomial_uncertain,BinomialUnc),
        Vchk_3(negative_binomial_uncertain,NegBinomialUnc),
        Vchk_3(geometric_uncertain,GeometricUnc),
        Vchk_3(hypergeometric_uncertain,HyperGeomUnc),
        Vchk_3(histogram_point_int_uncertain,HistogramPtIntUnc) }
var_mp_check_daus
Var_check var_mp_check_daus[] static
Initial value:
= {
        Vchk_3(histogram_point_str_uncertain,HistogramPtStrUnc) }
var_mp_check_daur
Var_check var_mp_check_daur[] static
Initial value:
= {
        Vchk_3(histogram_point_real_uncertain,HistogramPtRealUnc) }
var_mp_check_ceu
Var_check var_mp_check_ceu[] static
Initial value:
= {
        Vchk_3(continuous_interval_uncertain,ContinuousIntervalUnc) }
var_mp_check_deui
Var_check var_mp_check_deui[] static
Initial value:
= {
        Vchk_3(discrete_interval_uncertain,DiscreteIntervalUnc),
        Vchk_3(discrete_uncertain_set_integer,DiscreteUncSetInt) }
var_mp_check_deus
Var_check var_mp_check_deus[] static
Initial value:
= {
        Vchk_3(discrete_uncertain_set_string,DiscreteUncSetStr) }
var_mp_check_deur
Var_check var_mp_check_deur[] static
Initial value:
= {
        Vchk_3(discrete_uncertain_set_real,DiscreteUncSetReal) }
var_mp_cbound
Var_rcheck var_mp_cbound[] static
Initial value:
= {
        Vchk_7(continuous_design,ContinuousDes,continuousDesign),
        Vchk_7(continuous_state,ContinuousState,continuousState),
        Vchk_5(normal_uncertain,NormalUnc,normalUnc),
        Vchk_5(lognormal_uncertain,LognormalUnc,lognormalUnc),
        Vchk_5(uniform_uncertain,UniformUnc,uniformUnc),
        Vchk_5(loguniform_uncertain,LoguniformUnc,loguniformUnc),
        Vchk_5(triangular_uncertain,TriangularUnc,triangularUnc),
        Vchk_5(beta_uncertain,BetaUnc,betaUnc) }
This is used within check_variables_node(): Var_RealBoundIPCheck() is applied to validate bounds and initial points.
Referenced by NIDRProblemDescDB::check_variables_node().
var_mp_drange
Var_icheck var_mp_drange[] static
Initial value:
= {
        Vchk_7(discrete_design_range,DiscreteDesRange,discreteDesignRange),
        Vchk_7(discrete_state_range,DiscreteStateRange,discreteStateRange) }
This is used in check_variables_node(): Var_IntBoundIPCheck() is applied to validate bounds and initial points, and in make_variable_defaults(): Vgen_* is called to infer bounds.
Referenced by NIDRProblemDescDB::check_variables_node(), and NIDRProblemDescDB::make_variable_defaults().
SCI_FIELD_NAMES
const char* SCI_FIELD_NAMES[]
Initial value:
= { "dakota_type", "numFns", "numVars", "numACV", "numADIV",
                                  "numADRV", "numDerivVars", "xC", "xDI",
                                  "xDR", "xCLabels", "xDILabels",
                                  "xDRLabels", "directFnASV", "directFnASM",
                                  "directFnDVV", "directFnDVV_bool",
                                  "fnFlag", "gradFlag", "hessFlag",
                                  "fnVals",  "fnGrads",  "fnHessians",
                                  "fnLabels", "failure", "currEvalId" }
fields to pass to Scilab in Dakota structure
Referenced by ScilabInterface::scilab_engine_run().
SCI_NUMBER_OF_FIELDS
const int SCI_NUMBER_OF_FIELDS = 26
number of fields in above structure
Referenced by ScilabInterface::scilab_engine_run().